### ISSUE TITLE
Docket Alert should check if document has been uploaded vs. going directly to buy on Pacer

### ISSUE THREAD

**Issue by lkj19zpdiDDe** [freelawproject/courtlistener#1003]
Frequently documents are uploaded after docket alert emails are sent out. However, the email still links to buy the document on PACER. It would be great to check the status of the document at the time of opening the email or clicking on the link for the document. 

I'd be happy to implement this. My general strategy would be to embed an image that would show the document's upload status.  Then, the link would be to Court Listner and would redirect to PACER or the file-based upon the status.

Let me know what you think about this strategy.

**Comment by mlissner** [comment]
This is a great suggestion and one that I've considered too. It's definitely annoying when the links are wrong and the email was faster than the update.

**Comment by mlissner** [comment]
I guess all we'd need is some sort of redirect mechanism at a link endpoint that we created. Probably shouldn't be that hard, actually.

**Comment by lkj19zpdiDDe** [comment]
I'm thinking we link to the docket entry page (ie. https://www.courtlistener.com/docket/6139924/630/curling-v-raffensperger/) as step 1. Then, we can add a URL parameter to automatically redirect to the document in phase 2.

**Comment by lkj19zpdiDDe** [comment]
Pull request https://github.com/freelawproject/courtlistener/pull/1031 created. I've not yet been able to create a full environment so this is insufficiently tested.

**Comment by lkj19zpdiDDe** [comment]
Here's my brief proposal for how to create the URL that will automatically redirect to Court Listner or PACER which can be used in the email.

- Add a URL parameter of redirectToDownload=true to 
'^docket/(?P<docket_id>\d*)/(?P<doc_num>\d*)/(?P<slug>[^/]*)/$' and '^docket/(?P<docket_id>\d*)/(?P<doc_num>\d*)/(?P<att_num>\d*)/(?P<slug>[^/]*)/$'. 
-  Check for that parameter at https://github.com/freelawproject/courtlistener/blob/master/cl/opinion_page/views.py#L223
-  If the file exist on Court Listner (i.e. item.is_available), redirect the user to that file (i.e. item.filepath_local)
- If the file doesn't exist on Court Listner, redirect the user to PACER (ie. item.pacer_url)

**Comment by mlissner** [comment]
That's a much better solution than I had in mind, please proceed! Do you need help getting docker up and running? DEVELOPING.md has a lot of notes (and we welcome additional tweaks to the process, if you're an expert.)

**Comment by lkj19zpdiDDe** [comment]
Thanks for the offer of help. I'm not super docker experience and am running into a few issue
- I get a `django.db.utils.OperationalError: FATAL:  role "django" does not exist` error when trying to run the migration command (`docker exec -it cl-django python /opt/courtlistener/manage.py migrate`)
- The create super user command doesn't appear to exist (i.e. `docker exec -it cl-django python /opt/courtlistener/manage.py createsuperuser` doesn't work)

Any ideas on how to work past these?

**Comment by flooie** [comment]
Please, I'd love to hear your thoughts on updating the documentation.

**Comment by lkj19zpdiDDe** [comment]
Next question, any recommendations on how to populate the environment with test data?

**Comment by mlissner** [comment]
Test data is tricky and kind of an unsolved problem. I think if I were working on this, I'd just do it with the Python shell and fake-up some data. Would that work for you?

**Comment by nemobis** [comment]
Is this still needed? When the RECAP extension is installed, nowadays I see a very clear [R] icon next to stuff which has already been purchased by others.

**Comment by mlissner** [comment]
This is about the links that are in email alerts that we send. When the emails go out, those links often take people to PACER. Then we get the doc, and...the links in the emails still go to PACER. It's be better if we had a URL in the middle that either redirected to PACER if we didn't have it, or redirected to the file if we did.
