### ISSUE TITLE
Dependencies in dockerfiles

### ISSUE THREAD

**Issue by GPPassos** [freelawproject/courtlistener#1004]
Hi, I have recently rebuilt the project images used in the docker-compose, but I found some problems in dependencies:

`docker/django/Dockerfile` and `docker/task-server/Dockerfile` install `libav-tools`, but it was not found in `apt-get`, and it seems that is was superseded by `ffmpeg`. 

Those also try to install Tesseract by
```
RUN echo "deb http://deb.debian.org/debian stretch-backports main" > \
      /etc/apt/sources.list.d/backports.list && \
    apt-get update && \
    apt-get install -t stretch-backports -y tesseract-ocr tesseract-ocr-eng
```
However, I receive the error `tesseract-ocr : Depends: libicu57 (>= 57.1-1~) but it is not installable`.

Changing to 
```
RUN apt-get update && \
     apt-get install -y tesseract-ocr tesseract-ocr-eng
```
works for the building (but not sure if it works for the code here).

I am not submitting a PR as I did not run tests to know if those changes work, but definitely by building the Dockerfiles as they are now I have problems.

Thank you for your work!

**Comment by mlissner** [comment]
I....thought docker was supposed to solve these things! It's been a few days since I did a build, but I guess it's possible that the python2.7 image relies on a version of ubuntu that changed underneath it? Do you know how to check something like that?

**Comment by GPPassos** [comment]
It would make sense if it is a change in the ubuntu version of the python2.7 image.
Tags can be updated in the docker hub. From what I have seen, there are other "more specified" python images, things like 2.7.11-alpine (it seems to follow semantic versioning convention).

According to their page in [docker hub](https://hub.docker.com/_/python?tab=description&page=33), 2.7 is not even a "simple" tag, it is ambiguous among different images (but this is not the problem here as the others are Windows images).

I would suggest either using a more specific tag, such as 2.7.16-buster, or using an [immutable identifier](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier).

It seems the current metadata of the 2.7 image is here: https://github.com/docker-library/repo-info/blob/master/repos/python/remote/2.7.md
You can check if your local python2.7 image has the same image ID (mine is indeed what they say currently, `Image ID: sha256:d75b4eed9ada21ac6b19223a95d56113b54b244aa64848559f146c8c829fb4e8`).

However, if you did a build in the last few days, that's way weirder for me.

It could be a change in the apt server as well, I guess? But that would be pretty tricky.

**Comment by GPPassos** [comment]
Of course, if the goal is having shared images that anyone could use, I think that's more the point of the registry / of the docker images than of the Dockerfile, so you could push images to Docker Hub. I think in that sense docker solves this kind of think, but only at image level, not at build level.

I think that's good as a user, but as a developer what I'd prefer is indeed reproducible build / dockerfile.

My suggestion is that you specify the image up to metadata version (they say `2.7` is currently `2.7.16-buster` so you could try this one, or replace with the one that is working for you if you can find out which one it is)

**Comment by mlissner** [comment]
Hm, I'm not sure what's going on here. I just ran:

    docker build --no-cache --file docker/task-server/Dockerfile .

And it got through the apt layers without throwing any issues?

**Comment by GPPassos** [comment]
All right, what is your output for
```
docker images python:2.7
```
?

**Comment by mlissner** [comment]
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
python              2.7                 6fccad0f9438        3 months ago        914MB
```

I suspect if I pull the latest, I'll kill everything?

**Comment by GPPassos** [comment]
Yep, that's right.

What we may try is seeing if your particular version can be download from the repository.

What is your output for `docker images python:2.7 --no-trunc`?

We can try `docker pull python@<digest_of_your_image_here>"`

**Comment by mlissner** [comment]
I think actually, rather than pinning docker, I'd rather just pull the latest, see what breaks, and fix it. ffmpeg vs. libav is actually already handled in the source:

https://github.com/freelawproject/courtlistener/blob/d8decefaaeba88d0ba3a8ea7699863d4ab0447b8/cl/audio/utils.py#L6-L32

Do you have the bandwidth to take a stab at that?

**Comment by GPPassos** [comment]
Currently the first thing which breaks is the dockerfile itself, as it tries to download the package that does not exist (and doesn't know about the other one).

I believe I do, what is the size of the data? Is this covered in the instructions? (I didn't try yet getting the audio data or any other data)

**Comment by mlissner** [comment]
@GPPassos, I got a new laptop and had to get this fixed, so I just went ahead and did it. I didn't do quite the level of diligence I would have preferred, but I'm going to do some integration testing and we should learn if we have issues shortly. 

Thank you again for testing this. I think with the latest git and docker pushes, everything should be working again.
