### ISSUE TITLE
Create temporary robots.txt entries for blocked cases to achieve best of all worlds

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1007]
I've been giving it some thought over the past seven years, [since we implemented our current Google blocking technique][0], and I think there's a way we can do better. Currently, we do the following:

0. Do not use robots.txt at all.
1. Add noindex tags and HTTP headers to items.
2. Include items in our sitemaps.xml files.
3. Add noindex tags to the sitemap files so they don't wind up in Google (indeed I updated Django to include this by default!)
4. Sometimes: Go into Google's webmaster tools to remove an item manually.

The good parts of this:

1. noindex is the *correct* way to make sure an item isn't in the search engines. Using only robots.txt means that the item can still show up if it's linked to from elsewhere (robots.txt says not to crawl the item, but if it's linked from elsewhere they don't have to crawl it to have it in results).

2. By not using robots.txt, we avoid creating a public master list of blocked items. Further, we don't have to generate robots.txt with tens of thousands of items on it.

But:

1. noindex only works *after* a search engine re-crawls a page. That can take *months* for a random page since we now have tens of millions of pages. In the meantime, people are in the lurch and I have to tell them to please be patient. Some of these people are litigious, though we haven't been sued yet (because we're not doing anything illegal, but still).

2. The original idea was to use Google Webmaster tools more, and that they'd eventually provide an API or a library or something. They haven't, and as a result I pretty much never use Webmaster tools. It's just too much work.

So what can we do about this? Well, first of all robots.txt is a *fast* mechanism. Google re-crawls it regularly and is good about updating their search results based on it. It'd be great if we could use it to hide results. 

How do we get the benefits of noindex and the speed of robots.txt? Use both:

1. For some period of time after we receive a removal request, put it on robots.txt and also update it with noindex tags. This should get the item taken down quickly, unless it's linked to from elsewhere, in which case it may stay up.

2. After that period of time, remove it from robots.txt, but leave the noindex records. This should get it taken down permanently and thoroughly.

If we're lucky, Google et al may interpret us removing an item from robots.txt as a hint to go crawl it again.

How long is the period of time that we put items on robots.txt? Long enough for Google to come crawl robots.txt and remove the item from it's cache. Let's call it a week. 

I think this will create *fast*, *complete* and *automated* removal process. No more compromises? 

[0]: https://michaeljaylissner.com/posts/2012/01/16/respecting-privacy-while-providing-hundreds-of-thousands-of-public-documents/

**Comment by waldoj** [comment]
I think that's a fine idea. I bet you'd need to put that URL in `robots.txt` for less than 24 hours, which seems just fine. You could either generate it dynamically (and cache that in Redis or Memcached) or have a cron job that spits out a new `robots.txt` every hour or whatever.

Feels to me like you've hit on a new design pattern here.

**Comment by mlissner** [comment]
>  I bet you'd need to put that URL in robots.txt for less than 24 hours, which seems just fine. 

I was thinking that too, but wasn't sure of it. Votes++

> You could either generate it dynamically (and cache that in Redis or Memcached)

If it only had 24 hours worth of stuff, generating it dynamically isn't too bad. Looks like about 2k items/day (most of these are automated, thank goodness). Probably will throw it in a redis cache.

> Feels to me like you've hit on a new design pattern here.

Let's hope so. The current situation has annoyed me for years. Thanks for taking a look.

**Comment by mlissner** [comment]
OK, this is deployed. Let's hope it works. The easiest way to know is to keep track of whether people seem happier in my inbox or not. I think they will. I hope so.

**Comment by mlissner** [comment]
This hasn't made *any* meaningful improvement that I can tell. I'm going to try tweaking the robots.txt length and see if that helps.

**Comment by mlissner** [comment]
In #1032 I fixed a bug with this. Turns out robots.txt wants paths, not full URLs. No idea if it'll make a difference. We'll see.

**Comment by mlissner** [comment]
Well, bad news. This approach and logic is flawed, according to a thread I started here:

https://support.google.com/webmasters/thread/102074727?hl=en#

Sort of makes sense. Once you set up robots.txt, it doesn't trigger a removal from Google. Like it says on the tin, it just makes it so Google *doesn't* crawl it. So if you're using noindex and robots.txt in tandem as described here, you're drawing out the process. Damn.

**Comment by mlissner** [comment]
I think this is literally the first time I've reverted a commit in the canonical way of "I did something that was a mistake and want to undo it."
