### ISSUE TITLE
Build an API for having us download items from PACER

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1018]
We have a client that has paid us to generate an API where they can request a document or docket and have us go get it. I think there are several tasks that we could try to accomplish here:

Dockets:
1. Update a docket we already have
 - query by: a CL docket ID
 - query by: a PACER case ID and court
 - query by: a docket number and court ID

1. Get a docket we don't yet have
 - query by: a pacer case ID
 - query by: a docket number and court ID

Additional parameters to consider (taken from Juriscraper):
 - `date_start`: A filter for only docket entries after this date (default: blank)
 - `date_end`: A filter for only docket entries before this date (default: blank)
 - `doc_number_start`: Only docket entries larger than this (no numberless entries) (default: blank)
 - `doc_number_end`: Only docket entries smaller than this (no numberless entries) (default: blank)
 - `show_parties_and_counsel`: Whether to purchase parties and counsel (default: True)
 - `show_terminated_parties`: Whether to purchase terminated parties (default: False)
 - `show_list_of_member_cases`: Whether to show member cases (default: false)

PDFs:
1. Get a PDF we don't yet have
 - query by: a CL recap_document ID
 - query by: a pacer internal document ID and court
 - query by: a CL docket ID, a document number, and an attachment number
 - query by: a docket number, court ID, document number, and attachment number

Other (out of scope for now):
1. Get an attachment page we don't yet have
1. Get a docket history page
1. Appellate docket support?
1. Claims registries

For now we don't do webhooks for these, and folks can just poll for a status of complete.

**Comment by mlissner** [comment]
First version only has to support docket by pacer_case_id & court_id; and PDF by pacer_doc_id and court_id.

**Comment by mlissner** [comment]
A couple design thoughts:

1. The API endpoint will be a single path. I haven't come up with a good one for it yet, but it might be something like `recap-this`, `recap/fetch` or `recap/get`. Ideas welcome.

    Using only one path for this implies that, like the `recap` endpoint (where clients upload things), this endpoint will have some sort of `upload_type` parameter. Maybe just `type` or `fetch_type`?

2. I think this API will be fully available to anybody that is interested in it. I could be more restrictive here, but I'm not sure why. More interesting is to make it publicly accessible. 

3. If this is publicly accessible, we can even have something like an interface where people input their PACER credentials, fill out an HTML form of what they want, and we go and get it for them. In other words, this doesn't have to be *just* an API.

4. PACER credentials or PACER cookies are required on every submission. When people give us their credentials, we will use them to log into PACER. We'll save the cookies from that login into redis with a short expiration time (an hour, say?) and then throw away the rest. If somebody makes another request while we have their cookies in redis, we use the existing cookies. For now, there's no way for a user to programmatically ask us to clear their cookies from our cache.

**Comment by knowtheory** [comment]
Depending on how you implement this i just want to toss in a word of caution.  Letting users submit URL like objects opens up a bunch of surface area for abuse.  ([hacker news thread about Pocket](https://news.ycombinator.com/item?id=10078967), [Internet Archive snapshot of original post about Pocket](https://web.archive.org/web/20171227185627/https://www.gnu.gl/blog/Posts/multiple-vulnerabilities-in-pocket/)).

Having people use another reference where you then craft the request URLs is a good way to go, or if you do let users Bring Their Own Address, you should isolate/sandbox the request fetching.

**Comment by mlissner** [comment]
Hm, we'll be allowing parameters that we then convert into URLs or that we just submit as POST params. I think we're clear. I can't think of a way to do URL injection into the middle of a URL. I suppose our code will probably eventually contain something like:

    url = 'https://%s.ecf.uscourts.gov/some/path' % court_supplied_by_user
    GET url

So the user gets to inject the subdomain, but I can't think of anything evil you can do with that.

**Comment by mlissner** [comment]
I'm pulling these out of scope for now:

> query by: a CL docket ID, a document number, and an attachment number

(Because it feels esoteric. If you know the CL docket ID, you will also know the RECAP Document ID; just use that, right?)

> query by: a docket number, court ID, document number, and attachment number

(Because this makes for a two step process. We first might have to get the docket, then we'd have to get the PDF. If they want that, they should make two requests instead of one, and then use the other request parameters that are available.)

**Comment by mlissner** [comment]
> but I can't think of anything evil you can do with that.

I still can't, but the good news is that we'll be validating this anyway.

**Comment by mlissner** [comment]
One more minimization of scope, I'm declaring this out of scope too:

> query by: a pacer internal document ID and court

The problem with requesting a PDF this way is that if you do that, you can make a request for a PDF from a docket we don't yet have. If that happens, we *can* technically go get the PDF, but it would immediately be an orphan, with no docket to associate itself with. We have a lot of these orphans currently and they're a problem.

**Comment by CaseGuide** [comment]
That sounds fine, in our conops we’d always want a complaint associated with a case.

Kyle Harris

**Comment by johnhawkinson** [comment]
> We have a lot of these orphans currently and they're a problem.

If we already have orphans, we need a way to deal with them, and whatever that is will ultimately clean up all the existing ones, and the solution should be scale-independant (so what if the batch job runs for 2 days instead of 1 day?).

So that seems a pretty odd reason to not want to make the problem "worse."

**Comment by mlissner** [comment]
The part of the issue that'd be worse is that we'd have additional people confused about orphans, in this case, API users. Right now it happens to RECAP extension users when they send us docs prior to us getting dockets. That's not great, but if it also happens to API users, that's worse. (The scale in terms of number of documents being worse isn't such an issue, I agree.) Also, I don't think this API *needs* this feature, so removing it makes life easier in general.

I also agree that we should deal with the orphan problem (it has a ticket somewhere?), but I still don't know what a good solution looks like.

**Comment by mlissner** [comment]
A beta version of this is now complete in 7ae6de8279cbbf0c94c6260b95713b0096662f61
