### ISSUE TITLE
Remove badly scraped tax cases

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1052]
See broken cases [broken tax case](https://www.courtlistener.com/opinion/3066807/doris-simmons-brown-joe-brown-v-commissioner/?q=Doris+Simmons-Brown+%26+Joe+Brown+v.+Commissioner&type=o&order_by=score+desc&stat_Precedential=on&stat_Unknown+Status=on)

Most likely need to be found and replaced.

**Comment by flooie** [comment]
Initial research suggests 336 cases are broken. 

See CL search [Search Results](https://www.courtlistener.com/?q=Today%27s+Opinions&type=o&order_by=score+desc&stat_Unknown+Status=on&court=tax)

**Comment by flooie** [comment]
For quick reference:

1. https://www.courtlistener.com/opinion/3193787/deborah-lee-bean-neal-allan-berkowitz-v-commissioner/
2. https://www.courtlistener.com/opinion/3203834/elazar-m-cole-v-commissioner/
3. https://www.courtlistener.com/opinion/2938920/lucrezia-iona-canaday-v-commissioner/
4. https://www.courtlistener.com/opinion/2961321/linda-s-spjute-v-commissioner/
5. https://www.courtlistener.com/opinion/3005580/million-hussein-v-commissioner/
6. https://www.courtlistener.com/opinion/3006546/cheryl-lynn-ireland-v-commissioner/
7. https://www.courtlistener.com/opinion/3007109/richard-irwin-wideman-kristina-novak-v-commissione/
8. https://www.courtlistener.com/opinion/3066807/doris-simmons-brown-joe-brown-v-commissioner/
9. https://www.courtlistener.com/opinion/3148553/mark-e-huber-colleen-l-huber-v-commissioner/
10. https://www.courtlistener.com/opinion/3153234/robert-glenn-mcdougall-v-commissioner/
11. https://www.courtlistener.com/opinion/3156228/troy-s-podraza-jill-a-podraza-v-commissioner/
12. https://www.courtlistener.com/opinion/3157714/richard-a-boring-margaret-a-boring-v-commissioner/
13. https://www.courtlistener.com/opinion/3158731/reinaldo-vargas-v-commissioner/
14. https://www.courtlistener.com/opinion/3159462/kenneth-lee-newhouse-lindsay-rae-newhouse-v-commissioner/
15. https://www.courtlistener.com/opinion/3161624/bruce-r-hoffman-debra-s-hoffman-v-commissioner/
16. https://www.courtlistener.com/opinion/3164431/matthew-thomas-parmeter-v-commissioner/
17. https://www.courtlistener.com/opinion/3167972/hazem-garada-noha-elghosein-v-commissioner/
18. https://www.courtlistener.com/opinion/3168602/albert-martin-elbe-and-adah-m-elbe-intervenor-v-commissioner/
19. https://www.courtlistener.com/opinion/3175598/jose-g-henao-v-commissioner/
20. https://www.courtlistener.com/opinion/3178617/sofien-beltifa-v-commissioner/
21. https://www.courtlistener.com/opinion/3183210/robert-w-nuzum-mary-alane-nuzum-v-commissioner/
22. https://www.courtlistener.com/opinion/3183606/john-h-fisher-lisa-m-fisher-v-commissioner/
23. https://www.courtlistener.com/opinion/3184044/dona-de-primavera-jackson-joseph-dwight-jackson-v-commissioner/
24. https://www.courtlistener.com/opinion/3185273/rodney-j-guarino-lauraine-guarino-v-commissioner/
25. https://www.courtlistener.com/opinion/3187344/christopher-h-kaiser-linda-l-kaiser-v-commissioner/
26. https://www.courtlistener.com/opinion/3214974/james-e-hess-robyn-j-hess-v-commissioner/
27. https://www.courtlistener.com/opinion/3215504/barton-slavin-amy-weinstock-slavin-v-commissioner/
28. https://www.courtlistener.com/opinion/3216119/christopher-michael-haag-christine-ann-haag-v-commissioner/
29. https://www.courtlistener.com/opinion/3216673/perry-walter-payne-florence-nakakande-kasule-v-commissioner/
30. https://www.courtlistener.com/opinion/3219170/nayemul-b-chowdhury-laila-banu-v-commissioner/
31. https://www.courtlistener.com/opinion/3402109/joseph-l-evans-v-commissioner/
32. https://www.courtlistener.com/opinion/4243711/daniel-l-cook-v-commissioner/
33. https://www.courtlistener.com/opinion/4245325/ruben-jauregui-v-commissioner/
34. https://www.courtlistener.com/opinion/4248257/melissa-a-simonetta-v-commissioner/
35. https://www.courtlistener.com/opinion/4248704/cynthia-a-bullock-and-brian-bullock-intervenor-v-commissioner/
36. https://www.courtlistener.com/opinion/4249833/kevin-a-peck-v-commissioner/
37. https://www.courtlistener.com/opinion/4251307/lavell-white-adriene-white-v-commissioner/
38. https://www.courtlistener.com/opinion/4252158/diran-li-v-commissioner/
39. https://www.courtlistener.com/opinion/4253500/bruce-w-peterson-lisa-a-peterson-v-commissioner/
40. https://www.courtlistener.com/opinion/4254275/eric-l-cox-v-commissioner/
41. https://www.courtlistener.com/opinion/4254554/donald-nathaniel-cooper-jr-v-commissioner/
42. https://www.courtlistener.com/opinion/4256395/warren-satchell-v-commissioner/
43. https://www.courtlistener.com/opinion/4256775/diana-c-czekalski-v-commissioner/
44. https://www.courtlistener.com/opinion/4257654/mario-joseph-collodi-jr-elizabeth-louise-collodi-v-commissioner/
45. https://www.courtlistener.com/opinion/4258408/nathan-pilmer-brittany-dow-pilmer-v-commissioner/
46. https://www.courtlistener.com/opinion/4259882/william-lester-kennedy-jr-v-commissioner/
47. https://www.courtlistener.com/opinion/4260190/lawrence-l-cole-v-commissioner/
48. https://www.courtlistener.com/opinion/4282083/rosella-marie-hill-v-commissioner/
49. https://www.courtlistener.com/opinion/4312183/harvey-c-hubbell-trust-harry-j-finke-iv-trustee-v-commissioner/
50. https://www.courtlistener.com/opinion/4390692/jagtar-singh-khinda-v-commissioner/
51. https://www.courtlistener.com/opinion/4253044/tiffany-marie-mcsweeney-v-commissioner/
52. https://www.courtlistener.com/opinion/4258899/andrew-christopher-sanek-v-commissioner/
53. https://www.courtlistener.com/opinion/4303154/julie-tishkoff-v-commissioner/
54. https://www.courtlistener.com/opinion/4312804/dennis-k-hicks-sherry-l-hicks-v-commissioner/
55. https://www.courtlistener.com/opinion/4314851/joseph-l-jackson-sylvia-a-jackson-v-commissioner/
56. https://www.courtlistener.com/opinion/4315709/clyde-a-arashiro-v-commissioner/
57. https://www.courtlistener.com/opinion/4318067/orobosa-obayagbona-v-commissioner/
58. https://www.courtlistener.com/opinion/4319214/peter-phuong-k-pham-bach-t-nguyen-v-commissioner/
59. https://www.courtlistener.com/opinion/4319609/bohong-zhang-thomas-mckee-conservatee-barbara-strait-conservator/
60. https://www.courtlistener.com/opinion/4321593/gregor-macinnis-v-commissioner/
61. https://www.courtlistener.com/opinion/4329274/john-j-ekeh-v-commissioner/
62. https://www.courtlistener.com/opinion/4329593/guthrie-washaurwa-chibanguza-v-commissioner/
63. https://www.courtlistener.com/opinion/4331333/timothy-charles-qunell-jr-v-commissioner/
64. https://www.courtlistener.com/opinion/4332448/edgar-david-brown-v-commissioner/
65. https://www.courtlistener.com/opinion/4333136/daniel-binns-v-commissioner/
66. https://www.courtlistener.com/opinion/4343660/ellen-m-sas-roger-a-jones-v-commissioner/
67. https://www.courtlistener.com/opinion/4345549/mark-a-quintal-v-commissioner/
68. https://www.courtlistener.com/opinion/4346778/alvin-jones-chanee-jones-v-commissioner/
69. https://www.courtlistener.com/opinion/4347236/laverne-renee-hudson-v-commissioner/
70. https://www.courtlistener.com/opinion/4348355/tommy-j-walker-jr-v-commissioner/
71. https://www.courtlistener.com/opinion/4371749/william-h-tinsley-amaryllis-e-tinsley-v-commissioner/
72. https://www.courtlistener.com/opinion/4373201/larry-lee-lock-ii-v-commissioner/
73. https://www.courtlistener.com/opinion/4373884/william-henry-paynter-elizabeth-a-paynter-v-commissioner/
74. https://www.courtlistener.com/opinion/4374885/samuel-s-beckey-jennifer-j-beckey-v-commissioner/
75. https://www.courtlistener.com/opinion/4376169/rita-lopez-v-commissioner/
76. https://www.courtlistener.com/opinion/4377914/walter-cancel-v-commissioner/
77. https://www.courtlistener.com/opinion/4379658/windy-w-harris-v-commissioner/
78. https://www.courtlistener.com/opinion/4380248/adrian-corey-jenkins-v-commissioner/
79. https://www.courtlistener.com/opinion/4381958/william-a-alexander-jr-diane-c-alexander-v-commissioner/
80. https://www.courtlistener.com/opinion/4385889/gregory-alan-brown-v-commissioner/
81. https://www.courtlistener.com/opinion/4394663/mary-t-kahmann-eric-c-kahmann-v-commissioner/
82. https://www.courtlistener.com/opinion/4399549/alan-david-snow-v-commissioner/
83. https://www.courtlistener.com/opinion/4400185/reza-zia-ahmadi-rachelle-l-zia-ahmadi-v-commissioner/
84. https://www.courtlistener.com/opinion/4400648/alfred-h-shum-v-commissioner/
85. https://www.courtlistener.com/opinion/4403548/adolph-martinez-jr-racquel-m-martinez-v-commissioner/
86. https://www.courtlistener.com/opinion/4404570/timothy-john-crissey-dianne-elizabeth-crissey-v-commissioner/
87. https://www.courtlistener.com/opinion/4405041/michel-k-petree-aka-michel-k-swanson-v-commissioner/
88. https://www.courtlistener.com/opinion/4408413/liudmela-oksana-maciujec-v-commissioner/
89. https://www.courtlistener.com/opinion/4409483/victor-a-edwards-v-commissioner/
90. https://www.courtlistener.com/opinion/4409819/robert-george-welemin-arsenia-z-welemin-v-commissioner/
91. https://www.courtlistener.com/opinion/4413969/louis-m-gachette-v-commissioner/
92. https://www.courtlistener.com/opinion/4416644/ivan-levine-v-commissioner/
93. https://www.courtlistener.com/opinion/4417325/charles-edward-fagan-v-commissioner/
94. https://www.courtlistener.com/opinion/4417683/alan-gregory-woolsey-anita-lee-woolsey-v-commissioner/
95. https://www.courtlistener.com/opinion/4419139/wilfred-omoloh-v-commissioner/
96. https://www.courtlistener.com/opinion/4419680/stephen-b-howard-v-commissioner/
97. https://www.courtlistener.com/opinion/4421513/randall-l-grago-v-commissioner/
98. https://www.courtlistener.com/opinion/4422291/timothy-c-roeckel-v-commissioner/
99. https://www.courtlistener.com/opinion/4425896/david-l-jones-v-commissioner/
100. https://www.courtlistener.com/opinion/4410812/samuel-joseph-carrick-v-commissioner/
101. https://www.courtlistener.com/opinion/4411578/michael-wooten-joan-wooten-v-commissioner/
102. https://www.courtlistener.com/opinion/4422537/rachelle-edanna-michaels-david-c-michaels-v-commissioner/
103. https://www.courtlistener.com/opinion/4423008/gary-patrick-johnson-v-commissioner/
104. https://www.courtlistener.com/opinion/4424579/michael-lee-martin-carol-feather-martin-v-commissioner/
105. https://www.courtlistener.com/opinion/4425281/edward-collins-v-commissioner/
106. https://www.courtlistener.com/opinion/4431088/joshua-brandon-tiller-v-commissioner/
107. https://www.courtlistener.com/opinion/4431476/eric-alan-harris-v-commissioner/
108. https://www.courtlistener.com/opinion/4431840/raymond-ochoa-v-commissioner/
109. https://www.courtlistener.com/opinion/4439673/samuel-scott-beckey-jennifer-jean-beckey-v-commissioner/
110. https://www.courtlistener.com/opinion/4437472/paul-peter-partyka-catherine-elaine-partyka-v-commissioner/
111. https://www.courtlistener.com/opinion/4442042/wesley-g-fleming-jeana-l-thompson-v-commissioner/
112. https://www.courtlistener.com/opinion/4447228/matthew-eric-baham-jennifer-michelle-baham-v-commissioner/
113. https://www.courtlistener.com/opinion/4447766/andrey-andreyevich-dovzhenok-v-commissioner/
114. https://www.courtlistener.com/opinion/4451298/paul-chen-v-commissioner/
115. https://www.courtlistener.com/opinion/4452534/steve-pemberton-v-commissioner/
116. https://www.courtlistener.com/opinion/4455143/robert-gollnick-jr-piyanut-ustsasan-gollnick-v-commissioner/
117. https://www.courtlistener.com/opinion/4455481/mindy-lessard-fka-mindy-tomko-and-john-m-tomko-intervenor-v/
118. https://www.courtlistener.com/opinion/4457104/colin-c-bishop-and-lisa-bishop-intervenor-v-commissioner/
119. https://www.courtlistener.com/opinion/4458436/evgeny-kiselev-v-commissioner/
120. https://www.courtlistener.com/opinion/4459875/pantano-baptist-church-v-commissioner/
121. https://www.courtlistener.com/opinion/4462776/michael-royce-preston-v-commissioner/
122. https://www.courtlistener.com/opinion/4463723/david-alan-devaleria-v-commissioner/
123. https://www.courtlistener.com/opinion/4465099/brandon-brown-christi-cloaninger-brown-v-commissioner/
124. https://www.courtlistener.com/opinion/4465446/rick-colbert-traci-marie-kruse-colbert-v-commissioner/
125. https://www.courtlistener.com/opinion/4474903/jose-franco-linda-anne-franco-v-commissioner/
126. https://www.courtlistener.com/opinion/4475690/bruce-joseph-levitz-evelyn-borlongan-levitz-v-commissioner/
127. https://www.courtlistener.com/opinion/4476494/ron-william-thompson-v-commissioner/
128. https://www.courtlistener.com/opinion/4476834/toni-harris-v-commissioner/
129. https://www.courtlistener.com/opinion/4478751/james-edward-bradley-jr-margaret-letitia-hayes-hunter-v-commissioner/
130. https://www.courtlistener.com/opinion/4479075/hamid-jahangirian-shohreh-chalshtari-v-commissioner/
131. https://www.courtlistener.com/opinion/4483065/gary-k-sherman-gwendolyn-l-sherman-aka-gwen-l-sherman-v/
132. https://www.courtlistener.com/opinion/4484008/shane-havener-amy-e-costa-v-commissioner/
133. https://www.courtlistener.com/opinion/4484491/salina-jivani-v-commissioner/
134. https://www.courtlistener.com/opinion/4485159/stanislav-antoniev-dimitrov-v-commissioner/
135. https://www.courtlistener.com/opinion/4486975/teresa-j-henley-v-commissioner/
136. https://www.courtlistener.com/opinion/4487890/aaron-keith-nicholson-v-commissioner/
137. https://www.courtlistener.com/opinion/4498473/adam-d-fehr-v-commissioner/
138. https://www.courtlistener.com/opinion/4500959/homayoun-samadi-sarabano-samadi-v-commissioner/
139. https://www.courtlistener.com/opinion/4503636/joseph-engesser-v-commissioner/
140. https://www.courtlistener.com/opinion/3170923/howard-bernstein-lorraine-f-britto-bernstein-v-commissioner/
141. https://www.courtlistener.com/opinion/3173231/xionghui-he-v-commissioner/
142. https://www.courtlistener.com/opinion/4497784/john-a-voigt-lorinda-c-martin-v-commissioner/
143. https://www.courtlistener.com/opinion/4502415/rhoeda-joy-tan-farolan-v-commissioner/
144. https://www.courtlistener.com/opinion/4504644/roger-g-maki-lilane-j-gervais-v-commissioner/
145. https://www.courtlistener.com/opinion/4245604/paul-parisi-v-commissioner/
146. https://www.courtlistener.com/opinion/4247144/mandie-bradford-gaston-v-commissioner/
147. https://www.courtlistener.com/opinion/4511758/rodrigo-kho-loreta-kho-v-commissioner/
148. https://www.courtlistener.com/opinion/4513511/donald-l-zinger-nicole-a-zinger-v-commissioner/
149. https://www.courtlistener.com/opinion/4515250/eric-amaefuna-v-commissioner/
150. https://www.courtlistener.com/opinion/4515626/shash-schaekar-v-commissioner/
151. https://www.courtlistener.com/opinion/4516441/jacques-l-french-sherry-l-french-v-commissioner/
152. https://www.courtlistener.com/opinion/4524421/john-a-garcia-jamie-garcia-v-commissioner/
153. https://www.courtlistener.com/opinion/4526088/joseph-brian-whiteford-gwenn-catherine-whiteford-v-commissioner/
154. https://www.courtlistener.com/opinion/4321159/gary-frederick-roy-v-commissioner/
155. https://www.courtlistener.com/opinion/4326622/dwight-mcdonald-donna-mcdonald-v-commissioner/
156. https://www.courtlistener.com/opinion/4331800/tao-long-v-commissioner/
157. https://www.courtlistener.com/opinion/4337761/mahmoud-a-makhlouf-jane-m-makhlouf-v-commissioner/
158. https://www.courtlistener.com/opinion/4346397/james-ramone-taylor-v-commissioner/
159. https://www.courtlistener.com/opinion/4394143/joseph-palisi-lisa-palisi-v-commissioner/
160. https://www.courtlistener.com/opinion/4395387/michael-e-nordloh-sharon-j-nordloh-v-commissioner/
161. https://www.courtlistener.com/opinion/4534079/jason-j-gartlan-v-commissioner/
162. https://www.courtlistener.com/opinion/4535740/richard-bryan-jackson-nora-irene-jackson-v-commissioner/
163. https://www.courtlistener.com/opinion/3191301/victor-m-crown-v-commissioner/
164. https://www.courtlistener.com/opinion/3194510/leonard-b-gilbert-v-commissioner/
165. https://www.courtlistener.com/opinion/3196800/richard-a-eichinger-diana-suarez-v-commissioner/
166. https://www.courtlistener.com/opinion/3197578/wendell-wilson-angelica-m-wilson-v-commissioner/
167. https://www.courtlistener.com/opinion/3203234/lawrence-m-aleamoni-marjorie-c-aleamoni-v-commissioner/
168. https://www.courtlistener.com/opinion/3206038/lynn-marie-domaschko-v-commissioner/
169. https://www.courtlistener.com/opinion/3207295/don-stephen-mcauliffe-v-commissioner/
170. https://www.courtlistener.com/opinion/4386812/megan-zhao-creigh-john-l-creigh-v-commissioner/
171. https://www.courtlistener.com/opinion/4387727/agwu-u-okiyi-chinyere-a-okiyi-v-commissioner/
172. https://www.courtlistener.com/opinion/4389648/trudy-s-reed-v-commissioner/
173. https://www.courtlistener.com/opinion/4393868/paul-niski-v-commissioner/
174. https://www.courtlistener.com/opinion/4401508/eric-zudak-v-commissioner/
175. https://www.courtlistener.com/opinion/4407664/victor-emmanuel-metzger-v-commissioner/
176. https://www.courtlistener.com/opinion/4407943/gary-lee-mcintee-v-commissioner/
177. https://www.courtlistener.com/opinion/4408772/arthur-dulik-jr-ellen-b-kugler-dulik-v-commissioner/
178. https://www.courtlistener.com/opinion/4530501/horace-r-weaver-candace-m-weaver-v-commissioner/
179. https://www.courtlistener.com/opinion/4536355/chevy-frankel-v-commissioner/
180. https://www.courtlistener.com/opinion/4537664/jin-man-park-v-commissioner/
181. https://www.courtlistener.com/opinion/4541111/letitia-burns-oconnor-and-estate-of-dana-levy-letitia-burns-oconnor/
182. https://www.courtlistener.com/opinion/4250811/richard-g-braddock-v-commissioner/
183. https://www.courtlistener.com/opinion/4532675/jeremy-adam-vanderhal-v-commissioner/
184. https://www.courtlistener.com/opinion/4549680/rolanda-michelle-curtis-bryon-curtis-v-commissioner/
185. https://www.courtlistener.com/opinion/4550793/enrique-fernando-dancausa-valle-v-commissioner/
186. https://www.courtlistener.com/opinion/4551931/larry-l-leuenberger-v-commissioner/

**Comment by mlissner** [comment]
These items are deleted from the DB, but we forgot to nuke them from Solr. Gotta do that too.

**Comment by mlissner** [comment]
- [ ] Now we've got some tax cases from volume 1 of TC. Those need to go too (including solr!)

**Comment by mlissner** [comment]
These items are deleted using the following:

```
In [12]: from cl.lib.scorched_utils import ExtraSolrInterface

In [13]: from django.conf import settings

In [14]: si = ExtraSolrInterface(settings.SOLR_OPINION_URL, mode='w')

In [44]: bad = set()

In [45]: for result in si.query().add_extra(**{'q': 'court_id:tax', 'rows': '15000'}).execute():
    try:
        Opinion.objects.get(pk=result['id'])
    except Opinion.DoesNotExist:
        bad.add(result['id'])

In [46]: len(bad)
Out[46]: 186

In [50]: si.delete_by_ids(list(bad))
```

There are also a bunch that we added from volume 1 of the TC reporter. Those were deleted from both Solr and the DB with. I found them in the DB and then deleted them as above.
