### ISSUE TITLE
Flesh out the pics for federal judges

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1055]
Priority is probably:
 - Active judges:
    - SCOTUS 
    - Circuit court
    - District court
    - Bankruptcy
    - Magistrate
 - Retired judges according to the order above, going back in time a decade at a time.

**Comment by mlissner** [comment]
Update: Do district first per client requirements.

**Comment by mlissner** [comment]
@jonashleyo is this done?

**Comment by jonashleyo** [comment]
Yes.  It's done.
