### ISSUE TITLE
Do some performance enhancements for testing

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1059]
Tests take about 13 minutes right now. About eight of that is tests and the rest is getting code, docker images, etc. The fixes are clear, but they won't necessarily be easy:

 - We've got about a decade of Git commits as of now and our repository has grown large. #796 is to remove files from our repository. We should do that too, but more important is to nuke anything more than a few years old. I have no idea how to do this, but it'd be great if it weren't too difficult.

 - Running tests in parallel would speed them up. The tricky part is that if two tests use the same data in the database, we're in trouble. Maybe we can split Selenium tests up from the rest? Django has some good tools for this, as does Github Actions.

 - Shrink our docker images? I think we currently have different images for cl-celery and cl-django, but they're basically identical if you look at their Dockerfile files. Could one inherit from the other, say, for a big boost? Secondly, can we use the alpine images to make slim images? 

 - Our selenium tests are stupidly slow. I literally put a five minute timeout on them. What is wrong with these that makes them so slow?

**Comment by mlissner** [comment]
Another thing: Squashing migrations should help. I'm going to give that a try as soon as the PR backlog is flushed.

**Comment by divergentdave** [comment]
Regarding the first bullet point, doing a shallow clone of the repository would allow you to speed up CI without having to rewrite git history. Travis CI builds do `git clone --depth 50` by default. Once `actions/checkout@v2` is released, (https://github.com/actions/checkout/pull/70) this will be easy to configure.

**Comment by mlissner** [comment]
It's funny, it didn't occur to me that was possible when I wrote this up, and then a couple days ago I realized it must be a thing and that it'd be much easier than deleting old commits. Thanks for digging it up.
