### ISSUE TITLE
Remove core API before Python 3

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1060]
This should make our lives slightly easier in the future. Remove it from requirements.txt, nuke it's view (commented in requirements.txt), and read through the docs here:

https://www.django-rest-framework.org/coreapi/schemas/#core-api

**Comment by mlissner** [comment]
And remove it from our documentation.

**Comment by drewsilcock** [comment]
Are there any plans to improve support for OpenAPI as the de-facto standard for API client generation?

I have tried generating a Python client using [OpenAPI Generator](https://openapi-generator.tech/) using the specification at https://www.courtlistener.com/api/swagger/?format=openapi, however the lack of typing in the responses causes the client to return `None` for all of the endpoints instead of the actual data.

**Comment by mlissner** [comment]
Sounds like we haven't kept up with these "standards" or perhaps Django REST Framework hasn't? I'm not sure how much energy we'll put into any of these API client generators. So far it's been a "go with the flow" kind of thing, since the standards have been evolving so quickly. 

We do need to do our Python 3 upgrade, so that'll probably bring us to the latest DRF library, but I don't know what that means for this?

**Comment by drewsilcock** [comment]
Thanks for the response and clarification. DRF seems to have good support for this, and the currently generated OpenAPI spec does the endpoints and parameters absolutely fine, it just doesn't generate the responses.

It might be that updating to a more recent DRF fixes this, if not there are external dependencies which should do the trick, in particular [drf-spectacular](https://github.com/tfranzel/drf-spectacular/).

This library allows you to easily extend the schema where it's not able to automatically pick up on things like responses. It also has out-of-the-box support for [ReDoc](https://redoc.ly/) (i.e. you don't need to do anything else apart from register the endpoint) which I think is a pretty neat tool for exploring APIs.

I'd be happy to have a look at this this once the Python 3 version is ready to play with 🙂

**Comment by mlissner** [comment]
Thanks for the details. We'll get back in touch after the py3 upgrade is done, but that's a big lift for a project of our size. Right now we're working to break off large pieces of code into smaller py3 docker images. Once that's done, we will hopefully be able to get this upgrade and we can get back in touch — unless you want to help with the py3 conversion? Gotta ask.

**Comment by drewsilcock** [comment]
I'd be happy to help in whichever way I can. Do you have a work-plan lying around anywhere? How do you organise big tasks like this?

**Comment by mlissner** [comment]
Well, we usually create issues and projects. Here's the py3 one, though it's in a very early stage: https://github.com/orgs/freelawproject/projects/13. From there, we do a lot of discussion over on Slack. I'm not sure how to upgrade to py3, honestly. The issue is we have a lot of dependencies and they're all pretty old, so we'd have to upgrade all of them, probably all at once and take the hits and breakage that comes along with that.

**Comment by drewsilcock** [comment]
Feel free to ping over a Slack link if you want 🙂

I made a fork with some preliminary investigation and put up a PR for discussion: https://github.com/freelawproject/courtlistener/pull/1407.

Tbh it might be best to just port it over, upgrade the dependencies and then try to find anywhere it breaks. (This is where comprehensive tests come in useful!)

**Comment by mlissner** [comment]
Sent the slack invite. And yep, just upgrading everything and figuring out what breaks does seem like the right thing.

**Comment by mlissner** [comment]
CoreAPI is now removed in a58f33cea12dd4bf7e27feba208eab42fd351d14. Thanks, @drewsilcock.
