### ISSUE TITLE
Make "date_start" in people_db optional instead of required.

### ISSUE THREAD

**Issue by jonashleyo** [freelawproject/courtlistener#1079]
Many of the data sources we're looking at to round out judge information in people_db often lack pieces of information.  Usually this isn't a big deal but in some cases, where we know where a judge worked but not when, it becomes an issue.  At the moment, "date_start" is a required field but before we make it optional we need to track down all the ways it might impact other aspects of the site.

**Comment by mlissner** [comment]
For now we just gathered the data instead of updating the DB (and front end). This would be good to do, but not a priority for the moment.

**Comment by mlissner** [comment]
@flooie, @jonashleyo, @aekey1 this is complete. Hooray.
