### ISSUE TITLE
Citation parser fails when cite gives first and last page

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1091]
See example

```
313 Or. 209-211        Supreme Court of Oregon
```
This is more common than you would expect in the data sets we are analyzing.

**Comment by mattdahl** [comment]
I think this may have been fixed in 1bca38b2f5f1361289a54ecec7dbcebe1cf283d9, PR #1183. There is now an explicit check for possible page ranges.

**Comment by mlissner** [comment]
Yeah, I think this is fixed too, especially looking at that code.
