### ISSUE TITLE
Create upload portal for TN clerks to upload their PDFs

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1095]
Should be pretty basic, but include:

1. Court drop down (appeals court or no?)

1. Case name

1. Docket number (allow consolidated)

1. Neutral citation

1. Upload PDF

1. Date of decision

1. Authoring judge (are there ever multiple authoring judges?)

1. Button to submit (takes the user to the resulting page)

1. Button to submit and add another (submits it and then reloads the current page)

Once uploaded, it should:

Verify:

 - Neutral citation (correct format?)
 - Case name (not all uppercase?)
 - Date of decision (not in the future; must be within one year)

Process:

 - Extract the PDF
 - Scan for private information 
 - Add it to search
 - Save it all to the DB
 - Redirect the clerk to the correct page (what happens if OCR isn't done yet?)

**Comment by mlissner** [comment]
Here's one view of the data that they have:
![Screen Shot 2019-09-27 at 12 17 28 PM](https://user-images.githubusercontent.com/236970/71220161-74421b80-227c-11ea-86bf-2d3d0ff91e12.png)

**Comment by flooie** [comment]
This has been completed
