### ISSUE TITLE
Do bulk load of Tennessee Workers' Comp data

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1096]
Before we can start displaying things for TN, we need to get the historical data. We will be assigning neutral citations to these, so whatever bulk import system we use should be able to do that as well.

Probably, we'll assign neutral citations by date and then case name as a tie breaker.

**Comment by mlissner** [comment]
@flooie is working on some cleanup here, but seems like it should be done fairly soon.

**Comment by flooie** [comment]
@mlissner your timing is great... I think the cleanup has been completed
