### ISSUE TITLE
Populate per curiam fields for Harvard data

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1102]
During our first pass we skipped the per curiam field, marking it as always False. Some good examples of the challenge are here:

https://cite.case.law/super-ct-jud/1/193/
https://cite.case.law/va-col-dec/2/43/6038638/
https://cite.case.law/fla/1/25/

We haven't found a way of checking if the author field ever contains per curiam. It probably does, but we'll investigate in a later pass.

**Comment by flooie** [comment]
Appears that per curium is often designated in the author string of the document - I found numerous examples.  I think it should be added to the current update.

**Comment by mlissner** [comment]
That's great!

**Comment by flooie** [comment]
This is closed
