### ISSUE TITLE
Nuke the federal_cite_one, federal_cite_two, etc fields

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1112]
These should get removed from the code base pretty much entirely. I *think* the only place they should remain is:

 - The migration that put them into existence
 - The migration that removed them from the Earth
 - The notes in the API docs explaining that they're going away

They were deprecated around Q1 this year, so they can definitely go.

**Comment by flooie** [comment]
This is essentially finished - waiting for the right to time to submit PR for replication.

**Comment by mlissner** [comment]
Let's get this one submitted. Please try to link up the PR and the issue when you submit it.
