### ISSUE TITLE
(Some) RSS updates not added to CourtListener

### ISSUE THREAD

**Issue by csnardi** [freelawproject/courtlistener#1120]
I've noticed some issues with RSS updates again. For instance, currently on the RSS feed for the Southern District of IN is:

```rss
<item>
<title>
1:19-cv-02078 HADDOCK v. CITY OF INDIANAPOLIS et al
</title>
<link>
https://ecf.insd.uscourts.gov/cgi-bin/DktRpt.pl?95091
</link>
<description>
[Status Conference] (<a href="https://ecf.insd.uscourts.gov/doc1/07317707217?caseid=95091&de_seq_num=117" >32</a>)
</description>
<guid isPermaLink="true">
https://ecf.insd.uscourts.gov/cgi-bin/DktRpt.pl?95091&117
</guid>
<pubDate>Mon, 06 Jan 2020 21:39:39 GMT</pubDate>
</item>
```

But this item has not appeared on [the case's CourtListener page](https://www.courtlistener.com/docket/15672797/haddock-v-city-of-indianapolis/). I believe some RSS updates are working though, since (for instance) [this case](https://www.courtlistener.com/docket/15738894/united-states-v-perry/) shows a docket item that is also on today's RSS feed.

**Comment by johnhawkinson** [comment]
This appears to be a courtlistener server-side problem that @mlissner is looking into. It encountered some error processing the RSS feed (I don't know what!). But the current RSS feed is properly parsed by the juriscraper parser now, and returns

```js
  { u'assigned_to_str': u'',
    u'case_name': u'HADDOCK v. CITY OF INDIANAPOLIS',
    u'cause': u'',
    u'court_id': u'insd',
    u'date_converted': None,
    u'date_discharged': None,
    u'date_filed': None,
    u'date_terminated': None,
    u'demand': u'',
    u'docket_entries': [ { u'date_filed': datetime.date(2020, 1, 6),
                           u'description': u'',
                           u'document_number': u'32',
                           u'pacer_doc_id': u'07307707217',
                           u'pacer_seq_no': u'117',
                           u'short_description': u'Status Conference'}],
    u'docket_number': u'1:19-cv-02078',
    u'jurisdiction': u'',
    u'jury_demand': u'',
    u'nature_of_suit': u'',
    u'pacer_case_id': u'95091',
    u'parties': None,
    u'referred_to_str': u''},
```

which looks fine.

**Comment by mlissner** [comment]
OK, yeah, got this while running locally:

```
ERROR:celery.app.trace:Task cl.recap_rss.tasks.merge_rss_feed_contents[a4d62476-8030-4d64-8672-0c50eda86508] raised unexpected: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/courtlistener/cl/recap_rss/tasks.py", line 202, in merge_rss_feed_contents
    for docket in feed_data:
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/courtlistener/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/courtlistener/cl/recap_rss/management/commands/scrape_rss.py", line 162, in handle
    mark_status_successful.si(new_status.pk),
  File "/usr/local/lib/python2.7/site-packages/celery/canvas.py", line 576, in apply_async
    return self.apply(args, kwargs, **options)
  File "/usr/local/lib/python2.7/site-packages/celery/canvas.py", line 732, in apply
    last and (last.get(),), **dict(self.options, **options))
  File "/usr/local/lib/python2.7/site-packages/celery/result.py", line 1021, in get
    raise self.result
TypeError: 'NoneType' object is not iterable
```

**Comment by mlissner** [comment]
Hm, that URL works fine from my browser:

https://ecf.insd.uscourts.gov/cgi-bin/rss_outside.pl

Perhaps something to do with python requests or some kind of timeout.

**Comment by mlissner** [comment]
OK, dialing in more closely, we get this error: 


```
In [10]:     rss_feed = PacerRssFeed(map_cl_to_pacer_id(court_pk))

In [11]: rss_feed.query()
2020-01-07 17:04:21,637 - INFO: Querying the RSS feed for insd
---------------------------------------------------------------------------
ReadTimeout                               Traceback (most recent call last)
<ipython-input-11-d7785828217c> in <module>()
----> 1 rss_feed.query()

/usr/local/lib/python2.7/site-packages/juriscraper/pacer/rss_feeds.pyc in query(self)
    125         logger.info(u"Querying the RSS feed for %s" % self.court_id)
    126         timeout = 5
--> 127         self.response = self.session.get(self.url, timeout=timeout)
    128 
    129     def parse(self):

/usr/local/lib/python2.7/site-packages/requests/sessions.pyc in get(self, url, **kwargs)
    535 
    536         kwargs.setdefault('allow_redirects', True)
--> 537         return self.request('GET', url, **kwargs)
    538 
    539     def options(self, url, **kwargs):

/usr/local/lib/python2.7/site-packages/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    522         }
    523         send_kwargs.update(settings)
--> 524         resp = self.send(prep, **send_kwargs)
    525 
    526         return resp

/usr/local/lib/python2.7/site-packages/requests/sessions.pyc in send(self, request, **kwargs)
    635 
    636         # Send the request
--> 637         r = adapter.send(request, **kwargs)
    638 
    639         # Total elapsed time of the request (approximately)

/usr/local/lib/python2.7/site-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    527                 raise SSLError(e, request=request)
    528             elif isinstance(e, ReadTimeoutError):
--> 529                 raise ReadTimeout(e, request=request)
    530             else:
    531                 raise

ReadTimeout: HTTPSConnectionPool(host='ecf.insd.uscourts.gov', port=443): Read timed out. (read timeout=5)
```

**Comment by mlissner** [comment]
OK, so there's a bit of confusion here because my version of Jursicraper in my dev environment is a bit old, but the answer here is that our timeout is too aggressive. This...is a tricky business. Right now our deployed timeout is 5s. I set that timeout back in October when PACER had its national outage because otherwise our celery tasks would pile up, each one waiting several minutes before aborting. But apparently 5s is too aggressive for this sad, sad court, so I tinkered with it a bit and 20s seems to do the trick. I'll tweak it to that and deploy now.

**Comment by johnhawkinson** [comment]
Twenty seconds? There's no way that is sufficient for RSS feeds.

In non-comprehensive random interactive queries to RSS feeds (when I randomly decide that XML is the best way for me as a human being to learn something; happens more than you'd expect, I think), I often see browser rendering delays in the tens of seconds that seem to approach minutes. I wouldn't be comfortable with an automated non-interactive timeout of less than 90 seconds. RSS feeds can be large to download, and CM/ECF servers can be quite slow and overloaded (no doubt these are not unrelated).

What is this "tricky"? What goes wrong with a longer timeout?

If there's a national PACER outage and everything is breaking, that doesn't seem to suggest that that timeout value was wrong. After all, if CourtListener breaks when PACER is broken, that is to be expected. Setting constants based on that kind of abnormal situation is likely to have bad effects on the usual case. What was the value before?

Is this a global CL/juriscraper timeout, or specific to RSS?

This also argues for far better error reporting (in addition to, as implied above, finer-grained timeout specifications).

**Comment by mlissner** [comment]
It's a RSS feed specific one, but I think it should work, based on testing. The original (which caused issues during outages) was `(5, 300)`. That translates to 5 seconds for connect, and 300 to first data (I think): https://2.python-requests.org//en/master/user/advanced/#timeouts

Since October, without many issues, we had a mere five seconds for both, so I think this isn't so bad. I think a larger fix would help, say, by slowing our crawl of RSS feeds during an outage, but short of that the 20s seems like an OK middle ground.
