### ISSUE TITLE
Docket char length too short

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1140]
We have one case in the tax courts that had a docket length ~11k characters long.  The model allows for 5k length.  Update to model needed

**Comment by flooie** [comment]
Should I just roll this into the same branch as as nuke fields for simplicity?

**Comment by flooie** [comment]
So we are attempting to covert the varchar to a text field in our database.
Django generated the following sql command:

`ALTER TABLE "search_docket" ALTER COLUMN "docket_number" TYPE text USING "docket_number"::text;`

Using ALTER TABLE will not rewrite the table for a char to text conversion because they are  are binary coercible both ways.  According to stack, it would actually take longer if we were increasing the size of the char field again to 15,000 because that actually requires a rewrite of the column. 

But because the field is indexed it will still need to lock the table to rewrite the index.  Other than the amount of time it takes to rewrite the index, I'm not sure there is going to be an issue with the conversion though.  

I've excerpted part of the Postgres documentation to discuss the full sql command that was generated. 

> SET DATA TYPE
This form changes the type of a column of a table. Indexes and simple table constraints involving the column will be automatically converted to use the new column type by reparsing the originally supplied expression. The optional COLLATE clause specifies a collation for the new column; if omitted, the collation is the default for the new column type. The optional USING clause specifies how to compute the new column value from the old; if omitted, the default conversion is the same as an assignment cast from old data type to new. A USING clause must be provided if there is no implicit or assignment cast from old to new type.

[https://www.postgresqltutorial.com/postgresql-change-column-type/](url)
[https://www.postgresql.org/docs/10/sql-altertable.html](url)
[https://stackoverflow.com/questions/44142966/change-column-type-varchar-to-text-in-postgresql-without-lock-table](url)

**Comment by mlissner** [comment]
Hm, so I found this post interesting:

https://dba.stackexchange.com/questions/189890/does-changing-the-length-limit-type-modifier-of-varchar-result-in-a-table-or

Note that it was asked and answered by the same person at the same time, so this guy is trying to document this. I think by just increasing the varchar length we can avoid the DB index rewrite too, but his excerpt is from postgres12's docs and we're on 10 (I didn't even think 12 was out yet!).

Want to run his tests on a docker image running 10 and see how it goes?

**Comment by flooie** [comment]
To recap: 

Both @mlissner and I found that increasing the varchar size and/or altering varchar into text was appropriately quick regardless of whether the column was indexed.  

This is contrary to the documentation we have reviewed.  Either option appears to be fine moving forward.

**Comment by mlissner** [comment]
Documenting this a bit further for future-us.

1. I spent some time testing whether converting a varchar to text required an index rewrite for the field, which is what the documentation says. Tests indicate that the documentation may be wrong and that this conversion may be safe and fast. More conversation on this here: https://github.com/ankane/strong_migrations/pull/112. I've asked on the postgresql mailing list whether the docs are wrong; will fix them if so.

2. @flooie did a test as in the SO URL above, to test the speed of making a varchar bigger. That was instant too. 

So, having a wealth of options that work well, we decided to go with the future-proof approach, which is to use a text field going forward.

**Comment by mlissner** [comment]
The docs were indeed wrong, as discussed here: 

https://www.postgresql.org/message-id/flat/CAMp9%3DExXtH0NeF%2BLTsNrew_oXycAJTNVKbRYnqgoEAT01t%3D67A%40mail.gmail.com

Changing the type of a binary coercible column does not rewrite the index. A commit that landed in 9.2 back in 2011 fixed this, so somewhat shockingly we're sufficiently in the weeds that nobody else fixed this documentation bug until now. I don't understand that, since this feels like an important point to me, but perhaps they have more robust testing environments so they don't need to rely on the docs as much? Anyway, this is good news. Postgresql is even better than it says it is.
