### ISSUE TITLE
Difference between expected and actual for harvard imports

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1154]
We are two cases short from expected imports in B.T.A. (1 case is understood).

We have ~ 40 case difference between expected and actual for T.C.

**Comment by flooie** [comment]
This issue has two parts, I'm going to address BTA in this comment and come back to TC later.

### By the numbers
11,751 cases for BTA on  -- case.law
11,746 cases for BTA on -- archive.org
11,746 files in our backend on -- courtlistener.com
11,729 cases are visible on -- courtlistener.com
11,709 opinions in search results on courtlistener.com

The different between search results and cases we can see is probably an issue with SOLR.

The difference between cases visible and cases in our backend/on IA is 17.  I was able to identify that each of theses cases is has a duplicate citation string and we skipped them thinking they were the same case.  This has been addressed in a new branch --1154-cleanup-harvard-imports


```1 B.T.A. 15
1 B.T.A. 1255
2 B.T.A. 511
3 B.T.A. 697
4 B.T.A. 836
4 B.T.A. 810
4 B.T.A. 834
4 B.T.A. 825
4 B.T.A. 1074
5 B.T.A. 1177
5 B.T.A. 132
6 B.T.A. 373
6 B.T.A. 822
7 B.T.A. 1084
7 B.T.A. 450
12 B.T.A. 1195
13 B.T.A. 496
```


The difference between archive.org and case.law is 5 cases.  Case.law misattributed 5 ohio cases 4 state tax and 1 state criminal case to the BTA.  

TODO for BTA
- [ ] Rerun SOLR for BTA cases.
- [ ] Merge new branch and rerun harvard import.

**Comment by flooie** [comment]
Issue Part II - T.C. 

### By the numbers

11,850 cases for TC on -- case.law
11,848 cases for TC on -- archive.org
11,848 files in our backend on -- courtlistener.com
11,935 cases are total visible on -- courtlistener.com

Too many cases.  So we can start with - we are only looking at harvard imports.  

The 2 case difference between case.law and archive.org amount to two virgin island cases reported in Tax and can be ignored.  

We found 90 duplicate cases and three skipped imports.  -90 + 3 = -87 difference we should expect to see between files and visible.  
This matches the difference between 11,848 and 11,935.

### Duplicates that need to be merged with already added cases that didn't have citations
```
134 T.C. 1
134 T.C. 122
134 T.C. 141
135 T.C. 199
135 T.C. 238
135 T.C. 288
135 T.C. 344
135 T.C. 393
135 T.C. 471
135 T.C. 557
135 T.C. 581
135 T.C. 70
136 T.C. 1
136 T.C. 120
136 T.C. 151
136 T.C. 326
136 T.C. 341
136 T.C. 356
136 T.C. 373
136 T.C. 406
136 T.C. 585
136 T.C. 597
136 T.C. 67
136 T.C. 81
136 T.C. 99
137 T.C. 147
137 T.C. 159
137 T.C. 165
137 T.C. 25
137 T.C. 46
137 T.C. 70
137 T.C. 93
138 T.C. 1
138 T.C. 18
138 T.C. 213
138 T.C. 271
138 T.C. 306
138 T.C. 320
138 T.C. 395
138 T.C. 51
138 T.C. 67
139 T.C. 219
139 T.C. 290
139 T.C. 304
139 T.C. 371
139 T.C. 396
139 T.C. 418
139 T.C. 45
139 T.C. 468
140 T.C. 1
140 T.C. 15
140 T.C. 193
140 T.C. 216
140 T.C. 273
140 T.C. 410
140 T.C. 73
140 T.C. 86
141 T.C. 1
141 T.C. 214
141 T.C. 331
141 T.C. 376
141 T.C. 477
141 T.C. 533
142 T.C. 124
142 T.C. 140
142 T.C. 151
142 T.C. 165
142 T.C. 197
142 T.C. 248
142 T.C. 279
142 T.C. 308
142 T.C. 317
142 T.C. 355
142 T.C. 405
142 T.C. 413
142 T.C. 46
143 T.C. 140
143 T.C. 149
143 T.C. 170
143 T.C. 194
143 T.C. 274
143 T.C. 322
143 T.C. 41
143 T.C. 83
144 T.C. 123
144 T.C. 152
144 T.C. 161
144 T.C. 279
144 T.C. 306
144 T.C. 63
```

### Missing cases to add
```
19 T.C. 474
85 T.C. 397 
87 T.C. 1087 --- Large docket case
```

**Comment by flooie** [comment]
B.T.A. is now complete.

**Comment by mlissner** [comment]
Anything else to do here, @flooie ?
