### ISSUE TITLE
Update citation finder to work with html_harvard

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1155]
In Pull #931, I've noticed a few places where we list a bunch of HTML-type fields for parsing or updating citations. Once that code is merged, we should make sure that the harvard HTML works too and add a little test for it.

It'd be nice to make this future proof too somehow, so when we add `html_some_other_college` in 2025, we don't make this mistake again. Not sure how practical that is though.

**Comment by flooie** [comment]
Can we include find quote of citation to this?
