### ISSUE TITLE
Twenty (20) Board of Tax Appeal Cases missing case text

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1167]
The following twenty cases have no case text.  They are missing from the source we collected them from.  

1. https://www.courtlistener.com/opinion/4714876/appeal-of-national-bank-of-baltimore/
2. https://www.courtlistener.com/opinion/4714886/appeal-of-fred-cantrell-co/
3. https://www.courtlistener.com/opinion/4707713/appeal-of-confectioners-mercantile-agency/
4. https://www.courtlistener.com/opinion/4707720/appeal-of-dover-iron-co/
5. https://www.courtlistener.com/opinion/4707799/appeal-of-cunningham/
6. https://www.courtlistener.com/opinion/4707731/appeal-of-taylor-parker-co/
7. https://www.courtlistener.com/opinion/4707800/appeal-of-weinburg/
8. https://www.courtlistener.com/opinion/4707746/appeal-of-richardson/
9. https://www.courtlistener.com/opinion/4707966/appeal-of-cohen/
10. https://www.courtlistener.com/opinion/4707753/appeal-of-hawks-nursery-co/
11. https://www.courtlistener.com/opinion/4707894/appeal-of-birn/
12. https://www.courtlistener.com/opinion/4707916/appeal-of-conlen/
13. https://www.courtlistener.com/opinion/4707984/appeal-of-holman/
14. https://www.courtlistener.com/opinion/4707936/appeal-of-college-point-boat-corp/
15. https://www.courtlistener.com/opinion/4707830/appeal-of-commonwealth-realty-co/
16. https://www.courtlistener.com/opinion/4707954/appeal-of-clayburgh/
17. https://www.courtlistener.com/opinion/4708028/appeal-of-hirschmann/
18. https://www.courtlistener.com/opinion/4708067/appeal-of-albion-land-co/
19. https://www.courtlistener.com/opinion/4709388/hartmann-v-commissioner/
20. https://www.courtlistener.com/opinion/4709350/alexander-v-commissioner/

**Comment by mlissner** [comment]
Was there a related issue at Harvard for this one that we're waiting on? If so, can you please link them?

**Comment by flooie** [comment]
There appears to be an issue with perhaps over censoring?  
I opened a ticket weeks ago, but no response yet.
  
https://github.com/harvard-lil/capstone/issues/1329

**Comment by flooie** [comment]
I extracted the case text from copyright free versions of the original source material.  And can add them in manually.

**Comment by flooie** [comment]
All cases have been added
