### ISSUE TITLE
Add bankruptcy courts to the court picker as an option to delimit judge searches by

### ISSUE THREAD

**Issue by ghost** [freelawproject/courtlistener#1177]
There's currently no way for users to explicitly delimit by bankruptcy courts when searching by judges.  This hasn't been an issue so far since these we haven't collected data on them but this is changing fast and with it the need for a better search.

**Comment by mlissner** [comment]
Thanks. Let me know if you can't find the place to tweak the code for this and I'll do some digging. I'd start by looking in the template that generates the court picker.

**Comment by mlissner** [comment]
Pretty sure this is fixed. Please let me know if not, but if you try to look up judges, you can select which bankruptcy courts you want to filter to.
