### ISSUE TITLE
If multiple cases match citation query, don't show tip

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1207]
This used to work, but it looks like we lost it as part of the depth of treatment code. OTOH, I didn't think that code had entirely landed, sooo....it's unclear what's happening.

**Comment by mlissner** [comment]
Dang, I didn't get the example of this. @flooie, do you happen to still have it in a note or something? If not, I'll see if I can reproduce it.

**Comment by flooie** [comment]
https://www.courtlistener.com/?type=o&q=19%20T.C.%20474&type=o&order_by=score%20desc&stat_Precedential=on

Lots of duplicate citations in Tax Court.  I think we looked at

```
Black v. Commissioner
Date Filed: December 17th, 1952  Citations: 19 T.C. 474  Docket Number: 37398
McDaniel v. Commissioner
Date Filed: December 18th, 1952  Citations: 19 T.C. 474  Docket Number: 31507
```

**Comment by mlissner** [comment]
This is a slightly better query for that: https://www.courtlistener.com/?q=%2219%20T.C.%20474%22&type=o&order_by=score%20desc&stat_Precedential=on

**Comment by mlissner** [comment]
If you look at the commit I just referenced this from, you'll see that showing the tip when there was more than one match was actually the design (there was even a comment saying that we'd pick the first result in that instance). But I think it caused confusion and was actively *not* helpful, so now we only show the tip when there is exactly one item.
