### ISSUE TITLE
Citator fails to parse id and ibid tokens wrapped in <i></i> tags

### ISSUE THREAD

**Issue by mattdahl** [freelawproject/courtlistener#1218]
Similar to #449, except relating to `id.` and `ibid.` tokens. In many (older?) opinions, these tokens are wrapped in italics HTML tags (even in the ostensible "plain text" of an opinion), and so they aren't detected by our regular expressions. See https://www.courtlistener.com/opinion/107082/griswold-v-connecticut/ for many examples.

**Comment by mlissner** [comment]
This one looks resolved, right, @mattdahl ? Anything left on your mind to do here?

**Comment by mattdahl** [comment]
No, I think this is good! I'd just note that I see that many opinions are still not displaying these correctly, but I assume that that's just because you haven't re-run the parser on the whole corpus yet. I also recognize that doing so is computationally expensive so you may not want to immediately. You should wait to do so until we finish work on #1226, at least.
