### ISSUE TITLE
Opinions without docket numbers cant display docket page

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1240]
I'm not sure how widespread this issue is, but opinions without docket numbers can not display the docket page because of the following example bug and code. 

https://www.courtlistener.com/docket/2520846/commonwealth-v-hadley/

The core_docket_data code fails in cl/opinion_page/views.py because s.strip() fails when None is passed in.  
```
def core_docket_data(request, pk):
    """Gather the core data for a docket, party, or IDB page."""
    docket = get_object_or_404(Docket, pk=pk)
    title = ", ".join(
        [
            s
            for s in [
                trunc(best_case_name(docket), 100, ellipsis="..."),
                docket.docket_number,
            ]
            if s.strip()
        ]
    )```

**Comment by mlissner** [comment]
This looks fixed. Please close if so, @flooie.

**Comment by flooie** [comment]
Yes, this has been resolved.
