### ISSUE TITLE
FJC Integration Not Working for Criminal Cases

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#1252]
Right now, CourtListener does not appear to distinguish between criminal cases and civil cases for its FJC integration. I have not checked on appeals or bankruptcy either (there are separate FJC databases for all four categories).

Trial level criminal cases will always have "cr" in the docket. e.g, United States v. Fenwick (1:06-cr-00108). The IDB page for this in CL is treating like a habeas, which is technically a civil matter.
https://www.courtlistener.com/docket/12103791/idb/united-states-v-fenwick/

Anyway, I have looked at 100s of criminal cases on CL and they all appear to use the civil template and have the wrong data. It would be great to integrate the criminal cases correctly.

**Comment by mlissner** [comment]
Yes, this is definitely an issue with the original FJC importer. I think it generally worked well, but I didn't make it distinguish on this variable when I should have. I'm surprised how badly it went, but I'll be fixing this next time the data is imported. Thanks for reminding me.

**Comment by mlissner** [comment]
I guess as a first step, I should nuke any FJC info on a docket that contains `cr`. That can only make things better, then during the next import I can make sure civil goes to civil, etc.

**Comment by Colinstarger** [comment]
Makes sense to me!

Also: are you trying to use the FJC bankruptcy and appeal DBs? From my perspective, they are less important than civil/criminal, but I’m sure other researchers would appreciate them…

Best,
Colin

On Apr 16, 2020, at 8:09 PM, Mike Lissner <notifications@github.com<mailto:notifications@github.com>> wrote:

[EXTERNAL EMAIL]



I guess as a first step, I should nuke any FJC info on a docket that contains cr. That can only make things better, then during the next import I can make sure civil goes to civil, etc.

**Comment by mlissner** [comment]
I think at this point I've only ever imported the civil DB.

**Comment by flooie** [comment]
@mlissner I think this might be closed?  Looks like you might have already nuked the bad data as well as fixed the importer.
