### ISSUE TITLE
Maximize usage of iquery page on PACER to get last_date_filing, case_name, and date_filed fields (among others)

### ISSUE THREAD

**Issue by ikeboy** [freelawproject/courtlistener#1264]
PACER shows the last date something was filed, for free, if you go to the case directly. Is there some way to make use of this? 

A few ideas:

1. Scrape this on a regular basis and use it for alerts 
2. Have a button on the page that goes directly to the page with this info
3. Have a button on the page called "refresh last filed date" that goes out and scrapes the page and checks if it's more recent than the latest docket entry. For dockets with new filings, show a notice on the page saying there's new filings not in the list, encouraging people to update the docket. This button could be shown only to those with RECAP installed and do the scraping on the local machine.

related: https://github.com/freelawproject/courtlistener/issues/885#issuecomment-432826811

**Comment by ikeboy** [comment]
Could be helpful for jurisdictions without RSS feeds, and if you only scrape cases with docket alerts, it should be manageable?

**Comment by mlissner** [comment]
I'd be very much in favor of setting up a system to scrape these pages hourly or daily for updated dates, and I agree that the obvious first step is to begin doing it for any non-terminated case with an alert set up. I'd say doing it hourly probably makes sense for active cases, and that things can be slowed down as cases become quiescent? 

For reference, there are currently 9300 dockets with alerts.

You interested in contributing this?

**Comment by mlissner** [comment]
Oh, and I think once we figure out how to get this data regularly (and get that landed), changing gears to make this trigger alerts somehow would be great. Note that this would also be useful for issue #/1266, since that feature will also need to know when cases have changed.

**Comment by ikeboy** [comment]
You'd have to point me at which part of the codebase does alerts / scraping, but I'm definitely down to adding this. Seems simple enough. 

For alerts, we'd need a way to say "there's new filings" without actually knowing anything about the filing like docket number or having a link to buy directly. 

Is Pacer completely fine with scraping as long as you don't go overboard? Like if you do this for a million cases will they shut down your account? I have experience with large scale scraping projects, but usually was for sites that didn't need a login and we just switched IPs when blocked.

**Comment by ikeboy** [comment]
Just an obvious note - if there was already an update one day, the field is useless for that date, so don't scrape again till the next day. I guess we need to add a field to the database and store this. Probably two fields, for the timestamp of the last time it was scraped.

**Comment by mlissner** [comment]
Yeah, PACER is scraped so much, it's part of their business model. I've never heard of anybody having much in the way of issues, provided they spread their crawling around so it doesn't hit one court too hard all at once. Even then, they try to work with you in my experience.

I think the general architecture here would be to create a Django management script that is called from a supervisor daemon and which thus runs around the clock. The management command would look for things that needed to be checked, and then for each it found, it'd create a celery task to do the actual work. 

I think all of that would get put into roughly:
 - management command: cl/recap/management/commands/check_iquery.py
 - supervisor script: scripts/supervisor/check_iquery
 - celery task: cl/recap/tasks.py#scrape_iqurey.pl

We've got code for the parsing bits that's in Juriscraper, in juriscraper/pacer/iquery.py, I think.

Is that enough to run with it? Happy to provide more too?

**Comment by ikeboy** [comment]
I'm starting with writing a network test for the CaseQuery class to figure out how to use it.

**Comment by ikeboy** [comment]
How would I get a list of dockets with alerts set on them?

**Comment by ikeboy** [comment]
How about putting this into https://github.com/freelawproject/courtlistener/blob/7ffb3ebbb1f747437722f85e77512a1f69224cfe/cl/alerts/tasks.py#L65

After this, have an else clause if the alert would otherwise not trigger, which checks last date this field was updated, if it was more than 24 hours ago, scrape the field and send alert if there's a new filing.

**Comment by johnhawkinson** [comment]
Just a reminder, in case it's not obvious, this field is the filing date of the last entry, which is not the same as the entry date of the last filing. It is not rare (although also not the most common case) that court entries are entered a day (or more) after they are "filed."

This is not fatal to any of this, but it speaks to robustness.

**Comment by ikeboy** [comment]
> Just a reminder, in case it's not obvious, this field is the filing date of the last entry, which is not the same as the entry date of the last filing. It is not rare (although also not the most common case) that court entries are entered a day (or more) after they are "filed."
> 
> This is not fatal to any of this, but it speaks to robustness.

I think the primary benefit of this is for dockets that update rarely without RSS (or where RSS misses some entries, which I've seen often), where this isn't as significant. I'll draft an email along the lines of "we don't have any new docket entries but the court indicates there's a no entry, go check."

**Comment by johnhawkinson** [comment]
> or where RSS misses some entries, which I've seen often

Again, at the risk of stating what is well-known: CMECF RSS is defined by _category_ and many feeds are only set up with limited categories,

> Docket entries of type: order,order-cr

such as civil orders and criminal orders only. (This is shown at the top of the field and also in CourtInfo).

It is not a matter of missing entries (as, randomly) but rather wholesale categorical exclusion.

**Comment by ikeboy** [comment]
> > or where RSS misses some entries, which I've seen often
> 
> Again, at the risk of stating what is well-known: CMECF RSS is defined by _category_ and many feeds are only set up with limited categories,
> 
> > Docket entries of type: order,order-cr
> 
> such as civil orders and criminal orders only. (This is shown at the top of the field and also in CourtInfo).
> 
> It is not a matter of missing entries (as, randomly) but rather wholesale categorical exclusion.

Thanks, that's helpful. I figured it was some kind of "unimportant" entries being dropped but wasn't quite sure how.

**Comment by ikeboy** [comment]
Getting an error "django.db.utils.ProgrammingError: column search_docket.date_last_filing_updated does not exist" for the new field I tried to add. Where else other than models.py do I need to add this?

**Comment by ikeboy** [comment]
Figured it out and now it passes tests, at least. I'm not sure if it actually works as expected on live docket data. Going to try writing a few tests and see if the results are sane.

**Comment by ikeboy** [comment]
Wrote a test that checks for alerts in a case, and it works. 

I hacked around to get the test not to fail if you don't have PACER credentials, so it can pass the docker tests.

**Comment by ikeboy** [comment]
I think this feature is complete now. Should I put it behind the is_tester flag and maybe switch it to daily updates instead of hourly?

**Comment by ikeboy** [comment]
https://github.com/freelawproject/courtlistener/blob/2fa2d117e6ddc0d8f6d5ba820d3f316b4cb1e907/cl/alerts/tasks.py#L98 
I'd like to make a small change to behavior here - indent this line further so it only runs if an alert was actually sent. I don't think it makes a difference to any current behavior, but it will make a difference once I have a script calling this hourly - if it updates the "date_last_hit" field each time even if there's no update then when there is an update it won't notice because the dates will match.

**Comment by ikeboy** [comment]
https://github.com/freelawproject/courtlistener/issues/837 bumped into this prior issue, linking for completeness, it can be closed once this issue is.

**Comment by mlissner** [comment]
A couple more tasks here, after our first run last night. Noting them so we get them done:

 - [ ] The iquery page also gives us the date filing information, which we lack on about 3.5M dockets. We can go and start gathering that. @ikeboy to add some functionality to get a configurable number of those dockets per night. Perhaps we do this by ordering by `view_count`? 

 - [ ] Some case names are missing and we can use this to fix those as well. @ikeboy to add functionality for that as well, as part of the nightly function.

 - [ ] This currently crawls appellate dockets, which doesn't make sense, since appellate PACER doesn't have iquery pages. I'll fix that.

**Comment by mlissner** [comment]
I've been monitoring the errors coming back from these calls and I've fixed a few that showed up in Sentry. I think this is ready to go, so I just deployed the last piece of it via a cronjob. 

@ikeboy thank you for helping us with this long-desired feature. We're updating at *least* 25k cases per night thanks to this code. Dang!
