### ISSUE TITLE
Encourage RECAP, Opinions, People, or Oral Argument search from homepage

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1271]
This bug hurts: https://twitter.com/mmasnick/status/1260263560539566080

> Now that I realize there's a totally separate RECAP search it's like someone just gave me the correct pill and I've witnessed how the matrix works.

He uses the homepage to start his searches, and despite being a RECAP user for a decade didn't know RECAP search exists. Ouch, ouch, ouch. 

As soon as possible, let's fix this. I'm open to solutions, but even something crappy would be an improvement. This has happened because I've let the perfect be the enemy of the good. I've done nothing because doing something well would take too much time.

Option ideas:

 - Add a button into the search bar to switch between RECAP/Opinions/Oral Arguments/People
 - Wrap the search bar in some horrible tabs for each of those
 - Use radio buttons.

Honestly, anything is improvement.

**Comment by flooie** [comment]
I vote Add a button into the search bar to switch between RECAP/Opinions/Oral Arguments/People

**Comment by mlissner** [comment]
That seems simple enough and like a decent UX if we have space for it. Seconded.

**Comment by mlissner** [comment]
After some discussion today, we realized this is going to be particularly hard because of the new court picker that's getting added to the main query bar. The issue is that the courts that are available to the picker vary according to the archive that you're searching. So if you have something like:

```
┌─────────────────────────────────────────────┬────────┬──────────┬──────────┐
│ Search 400 courts...                            │ RECAP v │ Courts v  │ Search 🔍 │
└─────────────────────────────────────────────┴────────┴──────────┴──────────┘
```

<sup>(Grrrr, Github's monospace font isn't actually monospace?!)</sup>

And if a user selects some courts, then goes and switches from RECAP to something else, havoc will ensue. They'll properly think that they selected some courts, but the courts they selected may have only been available to RECAP, not the other archive they switched to. 

Solution:

1. Clear the courts when users switch archives. 
2. Instead of just saying "Courts" in the bar, say "All Courts" and then when they select some courts, update it with a number "23 Courts". This way, when the user switches archives and their courts are cleared, it'll go back to saying, "All Courts" and they'll have the feedback they need.

I did a little searching for how to build the archive switcher. So far, I've found:

https://stackoverflow.com/questions/28297706/responsive-bootstrap-button-with-dropdown-in-input-group
https://stackoverflow.com/questions/26054119/input-group-addon-with-bootstrap-select
https://stackoverflow.com/a/29512028/64911

**Comment by mlissner** [comment]
- [ ] After this lands, let's send a tweet asking how we can make search better. Something like: 

    > What can we do to make search work better in RECAP or Opinions?

    It'd be nice to get some feedback once we take care of our lowest-hanging fruit.

**Comment by brianwc** [comment]
It might be messier, but there should probably be one search bar to rule
them all. Within the mixed results one might indicate that some are recap
results and others are CL, (and yet others oral args?).

Much easier would be keep things as is, but redesign the homepage with two
big search bars clearly indicating "Search RECAP" vs "Search
CourtListener". However, saying that out loud makes one of the problems
clear "Courtlistener" is the name of the site! How can searching THAT not
be a search of everything? We have no good name for "stuff we scraped from
all manner of places except PACER" so people are always going to find that
confusing. Which brings me back to unified search...

Perhaps we should just create "dockets" for everything in CL (usually with
a single item, the opinion), and then everything would look the same as
RECAP and unifying everything under one search would be less jarring.

There's a lot of duplication to think about if we ever get Appellate RECAP
working and some even for the district courts, but the end result might be
worth it.

**Comment by mlissner** [comment]
This is getting done as part of our re-design. Closing now since otherwise we'll forget it exists (again).
