### ISSUE TITLE
Make docket numbers into phrases when searching

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1272]
Another bit of feedback we received today is that people get bad results when searching for things like:

12-9238

or 

3:18-cv-2383

This is simple. These need to be treated as phrase searches internally by wrapping them with quotes. As a first pass, any phrase that starts with a number can get made into a phrase.

**Comment by litewarp** [comment]
Where do you want the conversion to take place? In the form, prior to the ajax request, on the server?

**Comment by mlissner** [comment]
Server is best, that way it works equally in an API request or a front end one.

**Comment by litewarp** [comment]
So inject quotes if the first number is a string right [here](https://github.com/freelawproject/courtlistener/blob/97cbb67cef0a637c0de452b9dc3b262f5f0d72b3/cl/search/forms.py#L35)?

**Comment by mlissner** [comment]
I think if we did it there, the user's query would be tweaked when it was returned (they'd see "3:19-cv-2338" come back in their query). 

Sometimes we do that (like if we want to educate them about how to do better queries in the future), but I think for this one it's better if we just handle it silently on the back end.

For that, I think the two places I could find it were:

https://github.com/freelawproject/courtlistener/blob/497902f6e1f8cdd99bff30d15d5db2f822c0f2de/cl/lib/search_utils.py#L842

and:

https://github.com/freelawproject/courtlistener/blob/497902f6e1f8cdd99bff30d15d5db2f822c0f2de/cl/lib/search_utils.py#L779

(there might be other instances, I haven't looked thoroughly.)

I think we could add a little function there that cleans up the user's query so that it becomes, say:

    "q": cleanup_main_query(cd["q"] or "*"),

That should work? A couple tests might be nice too, even if they only test the regex function itself and don't do searches.
