### ISSUE TITLE
Use datetime instead of date for date_filed field of docket entries

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1282]
By all appearances, the filing date of docket entries is a date, not a date time — that's what you see when you look on docket sheets, docket history reports, and almost anywhere else in the PACER system. 

So it's actually good news that on the RSS feeds, they provide the date *and* the time. In https://github.com/freelawproject/juriscraper/pull/317, I'm adding support for the datetime and timezone to Juriscraper.

In 65e963053f3931bad23d5b96040ced222d1b7cea, I blocked scraped datetimes from causing issues in CourtListener. 

Eventually, we need to:

 - [ ] Convert the field in the database to be a datetime instead of a date (but how?)
 - [ ] Stop converting datetimes into dates when importing data (like above)
 - [ ] Figure out a good approach to adding the time information when we don't know it (noon for the timezone of the court?)
 - [ ] Figure out a good approach for *supplementing* an entry with time information when we get it later.

This...might be surprisingly difficult.

**Comment by mlissner** [comment]
Following up from #1790, @albertisfu where you said:

> we need to decide which time are we going to append to the date, maybe just adding 00:00:00:000000 as time?

Yeah, I don't think we can do that either for new data we're importing or for old data. The DB should really only have information in it that's correct, not stuff we made up. 

I think the way to fix this is probably to just add a nullable TimeField. Something like `time_filed`. It'd start out null for everything and then we'd fill it in whenever we knew what it was. 

> The API thing seems like a breakthrough [sic] change for users

Well, by adding a time field instead of migrating the date field, I think we avoid this.

---

With regards to timezones, both the new time field and the date field should be in UTC. We convert data to UTC when we import it and convert to local timezone when we show it to users (like a `local<->UTC<->local` sandwich).

---

Going through my comments from #1790 with the above approach in mind:

> 1. We have filing dates that come to us as datetimes and ones that come just as dates. For example, when we scrape emails or RSS feeds, we get datetimes, but when we scrape HTML dockets, we only get the date, which would need to be converted. 

This is solved in the proposed approach.

> 2. The API currently returns a date. Do we just continue it this way by coercing the new datetime field into a date, and then when we release a breaking API change down the road, we include this fix too?

This is solved in the proposed approach b/c we just add a new field to the API response.

> If so, that's OK for me, but replication users might have more trouble with the change to the field.

This is solved in the proposed approach b/c we just add a new field to the DB.
 
> 3. Do we use the date fields to look things up or do ordering? If so, how do those things break?

In the other thread you reply that this should be fine:

>> About using the date_field for ordering or looking for objects, I think it won't be an issue, since we use the entry_number or the recap_sequence_number to order docket entries, and the recap_sequence_number could be also generated using the datetime

But you say:

>> we might consider doing a conversion before using the court time zone, so the recap_sequence_number is reliable.

Why not do this with UTC? Because we haven't done so in the past?

> 4. We should store these times as UTC in the DB. When we present the dates to users, ideally we use the timezone of the court, which we have in a variable somewhere. 

This is solved by the UTC sandwich approach above.

What do you think? 

cc @johnhawkinson

**Comment by albertisfu** [comment]
Great, the nullable `time_filed` approach sounds good, It solves the data migration issues.

 When you mention:

> With regards to timezones, both the new time field and the date field should be in UTC. We convert data to UTC when we import it and convert to local timezone when we show it to users (like a local<->UTC<->local sandwich).

That means when we get a `DateTime` from a source like the RSS, we should convert it to UTC, then separate `date` and `time`,  store the `date` into `date_filed` and the `time` into `time_filed`, is that right?

Then when we show the `date_filed` to the users:

For entries where the `time_filed` is `null`, we'll show only the `date_filed` as is now, right?

For entries where the 'time_filed' is not `null`, we'll use the `date_filed` and the `time_filed` (that are in UTC) and convert it to a local `DateTime`.  Here my questions are:

Would the target timezone be the Court timezone to which docket entries belong to, right?
Or are you referring to converting it to a unique local timezone like Pacific time for everything?

Should we continue only showing the `date` (converted to the local timezone) as now or should we include the time when is available?

**Comment by mlissner** [comment]
> That means when we get a DateTime from a source like the RSS, we should convert it to UTC, then separate date and time, store the date into date_filed and the time into time_filed, is that right?

Bingo. Yes.

> For entries where the time_filed is null, we'll show only the date_filed as is now, right?
> 
> For entries where the 'time_filed' is not null, we'll use the date_filed and the time_filed (that are in UTC) and convert it to a local DateTime. 

There are three possibilities here:

1. **Historical data**: In this case, the time field will be null and the timezone unknown, but the date value is generally correct. We should just show the date to the users without conversion. The date is the date.

2. **New data, no time info**: When we get docket sheets, we don't get the time info, only the date. In this case, the time field is null, again, the timezone is unknown. As above, we should just show the date to users without conversion. The date is the date.

3. **New data, with time info**: When we get emails and RSS feeds, we actually get the time and timezone info. Normalize the date and time to UTC and put them in the DB. When showing to users, convert to local time zones from UTC.

This approach means that the date field is sometimes normalized to UTC and sometimes is not. That's lame, but it covers all possibilities and is both backwards and forwards compatible. Honestly, I'm not sure how we'd do this better even if we started over from scratch. The bottom line is that we get dates without timezone info sometimes, and when that's the case, we just have to save them as-is. 

> Would the target timezone be the Court timezone to which docket entries belong to, right?

Yes. When datetimes are imported from data or exported to users, we convert from/to UTC using local timezones.

> Should we continue only showing the date (converted to the local timezone) as now or should we include the time when is available?

Not many people will want the time, so let's just put it in a mouseover in the HTML unless somebody proposes something better that doesn't add needless clutter.

**Comment by mlissner** [comment]
There was extensive conversation about this on 2023-01-19 in the #development channel.
