### ISSUE TITLE
Collect political donation information on judges from FEC

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1288]
One of our clients is interested in this data, and it'll be a boon to journalists to have it too. Do a deep dive to see how feasible it is, then the various pieces will probably be:

1. data model upgrades
2. scraping script
3. UI tweaks
4. API tweaks (probably)

**Comment by jonashleyo** [comment]
Is this data for state judges and not federal?  It looks like federal judges are highly discouraged from making campaign donations based on the [Code of Conduct for U.S. Judges](https://www.uscourts.gov/judges-judgeships/code-conduct-united-states-judges#f):

Canon 5: A Judge Should Refrain from Political Activity

(A) General Prohibitions. A judge should not:

(1) act as a leader or hold any office in a political organization;

(2) make speeches for a political organization or candidate, or publicly endorse or oppose a candidate for public office; or

(3) solicit funds for, pay an assessment to, or make a contribution to a political organization or candidate, or attend or purchase a ticket for a dinner or other event sponsored by a political organization or candidate.

(B) Resignation upon Candidacy. A judge should resign the judicial office if the judge becomes a candidate in a primary or general election for any office.

(C) Other Political Activity. A judge should not engage in any other political activity. This provision does not prevent a judge from engaging in activities described in Canon 4.

COMMENTARY

The term “political organization” refers to a political party, a group affiliated with a political party or candidate for public office, or an entity whose principal purpose is to advocate for or against political candidates or parties in connection with elections for public office.

**Comment by mlissner** [comment]
I guess that's not a surprise. This is about federal judges, so let me see if we still want to pursue this with the above in mind.

**Comment by mlissner** [comment]
Right, so judges may have made donations prior to becoming judges. We want to collect that. This project is ON.

**Comment by jonashleyo** [comment]
Attaching a possible schema.  There are still some questions in here to discuss.

[db-schema.xlsx](https://github.com/freelawproject/courtlistener/files/4962682/db-schema.xlsx)

**Comment by mlissner** [comment]
Seems like this probably isn't worth the squeeze, at least not right now.
