### ISSUE TITLE
Add part-time/recalled options for judges in people_db.

### ISSUE THREAD

**Issue by jonashleyo** [freelawproject/courtlistener#1291]
Some magistrate judges work part-time and other retired judges are sometimes recalled and brought back to work.  Other titles like "chief" are included but these are not.

**Comment by mlissner** [comment]
@jonashleyo can you clarify what needs to happen here, so I get it right? I'm interpreting this to mean that we need to add these options to the `POSITION_TYPES` variable, but what exactly needs to get added? Can you paste in what you think is missing, maybe?

**Comment by jonashleyo** [comment]
Something like this:

(MAGISTRATE_RECALLED, "Magistrate Judge (recalled)"),
(MAGISTRATE_PART_TIME, "Magistrate Judge (part-time)"),

or this:

(MAGISTRATE_RECALLED, "Recalled Magistrate Judge"),
(MAGISTRATE_PART_TIME, "Part-time Magistrate Judge"),

**Comment by mlissner** [comment]
All set.
