### ISSUE TITLE
Thoughts on financial disclosures

### ISSUE THREAD

**Issue by aekey1** [freelawproject/courtlistener#1295]
Summarize the documents we have thus far:

- number of documents
- years covered
- which judges included - parse these from file names
- file formats - some files are already PDFs (Judicial Watch), majority are TIFFs
- generate a sample of documents for testing - need to determine appropriate sample size

I've been thinking about the judge names in particular and searchability. Is there a documented format for how judge names appear in the file name? The general pattern I've seen is "<last name>-<first initial><middle initial>" at the beginning of the file name, but curious how variations like suffixes and/or honorifics would be included. I've also seen at least one example of only a last name shown in the file name. A better question is probably "how do we interpret the full file name"?

**Comment by aekey1** [comment]
Counted documents in S3 bucket:
There are 29364 total documents (.pdf/.tif/.tiff), spanning years 2003 - 2018
- 9157 of these are PDFs from Judicial Watch - this accounts for all the JW docs, 2003 - 2011
- 20203 .tif/.tiff files, covering 2011 - 2018

The average number of documents for 2003 - 2010 is about 1000 per year, then for 2011 - 2018 the average jumps to about 2500. The overall yearly average number of documents is 1800 for the 2003 - 2018 period.

**Comment by mlissner** [comment]
Nice summary. The filenames are just what you see. It's how we get them from the Administrative Office of the courts, unfortunately. As for what we have, this is the latest I have in my tracking spreadsheet:

Year | Request Made | Status | USB Count
-- | -- | -- | --
2003-2010 | N/A | Scraped  from Judicial Watch | 0
2011 | 2017-10-26 | Complete | 1
2012 | 2017-10-26 | Complete | 1
2013 | 2017-10-26 | Complete | 1
2014 | 2017-10-26 | Complete | 2
2015 | 2017-10-26 | Complete | 2
2016 | 2017-10-26 | Complete | 3
2017 | 2018-06-11 | Completed 2019-12-21 | 1
2018 | 2019-01-02 | About half received | 3
2019 | 2019-01-01 | Still Waiting | 0

**Comment by aekey1** [comment]
Here's a CSV of the files from AWS: [Google Drive link](https://docs.google.com/spreadsheets/d/1dOxu2TgktqvyB-C5fdnBdHiEBSLqoqGQiMj-Cq7AgFI/edit?usp=sharing)

**Comment by mlissner** [comment]
Presumably this is resolved? Can you close if so, @flooie ?
