### ISSUE TITLE
Some documents may be pre-split

### ISSUE THREAD

**Issue by aekey1** [freelawproject/courtlistener#1302]
While reviewing some of the sample files today, some of the documents look like they have already been split into pages.

**Comment by aekey1** [comment]
Here's an example: [Snyder-CA J3. 09. CAC_SPE_R_16_Page_40.tiff](<http://storage.courtlistener.com/financial-disclosures/2016/Snyder-CA J3. 09. CAC/Snyder-CA J3. 09. CAC_SPE_R_16_Page_40.tiff>)

**Comment by mlissner** [comment]
Why are humans so bad at everything??? Here's the link to that judge's directory: https://com-courtlistener-storage.s3-us-west-2.amazonaws.com/list.html?prefix=financial-disclosures/2016/Snyder-CA%20J3.%2009.%20CAC/

**Comment by flooie** [comment]
I suppose it’s not in our nature? @mlissner

**Comment by flooie** [comment]
@aekey1 does that change your total count of documents?

**Comment by aekey1** [comment]
> @aekey1 does that change your total count of documents?

@flooie Yes, my total count is just a file count at this point :/ If the pre-split documents follow a similar naming scheme of "blahblah_Page_xx.tiff" we might be able to track them down and revise the document count.
