### ISSUE TITLE
Wrap up latest judge input, do blog post, update judge product page. (Jon)

### ISSUE THREAD

**Issue by jonashleyo** [freelawproject/courtlistener#1322]
The latest judge input requires a few minor tweaks to how we ingest FJC judges, hence the change from a note to an issue.

**Comment by jonashleyo** [comment]
Attaching latest round of FJC updates to be ingested after pull request approved.
[new_art3_judges_20200527.txt](https://github.com/freelawproject/courtlistener/files/4808415/new_art3_judges_20200527.txt)

**Comment by mlissner** [comment]
Blog and page updated. Just need the last few judges tweaked.

**Comment by jonashleyo** [comment]
Every judge from the last import should now have a record that includes their most recent position.  The last 10 or so were added manually.

**Comment by mlissner** [comment]
Yeehaw! Thank you John. Closing this issue at last!
