### ISSUE TITLE
Incorporate all California judges into our judge DB

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1328]
I made a request to the CA Judicial Council for information about all of their judges, past and present, including changes in position, and got back a wildly great response that I'll attempt to attach in a moment as a spreadsheet and an email. The email has a ton of detail and the spreadsheet has thousands of rows about CA judges. 

All of this should be incorporated into our judge DB.

Redacted, see next message: ~CA Judges 1964-2020.xlsx~
[Judge information.txt](https://github.com/freelawproject/courtlistener/files/4861335/Judge.information.txt)

**Comment by mlissner** [comment]
The earlier upload on this issue contained disability information in Column H of the data and the Judicial Council has asked us to delete that data and not use it. The horse may be out of the barn since it was uploaded here previously, but I've removed it from the issue description above and here is the corrected version.

[CA Judges 1964-2020 fnl.xls.txt](https://github.com/freelawproject/courtlistener/files/4861334/CA.Judges.1964-2020.fnl.xls.txt)

**Comment by mlissner** [comment]
And, after some additional cajoling and back and forth, I've gotten almost all of the data from their database. My process was to first do a request for all the headers in their database, and then to do a request for the content of those headers. Boom, baby. 

Here's what they wrote me today:

```
Dear Mr. Lissner,

Below, you requested that we provide you another record showing additional fields of 
information for California state court judges between 1964 and 2020. The record is 
attached. We have not included gender and age because individuals have a privacy 
interest in their physical descriptions. (See Cal. Rules of Court, rule 10.500(f)(3); see
also, e.g., Cal. Const., art. I, § 1; Civ. Code, § 1798.3(a); Perkey v. Department of Motor
Vehicles (1986) 42 Cal.3d 185, 191–192.) We again redacted one other piece of private
information for some judges, as we did when we provided you an earlier (more limited) 
version of this record. (See Cal. Rules of Court, rule 10.500(f)(3).)

Please note the following regarding column headings:

o   “Job Title” refers to the highest position an individual held;

o   “My title” refers to the position held for the judicial “experience” described in an individual
 row of the document;

o   “Person ID” and “Exp ID” (or “Experience ID”) are numbers automatically assigned by our 
system;

o   The entry in “Judicial Indicator” will be “Y” for “yes,” indicating all included individuals held 
judicial office;

o   “Judicial Position ID” is a system-assigned number for individual judgeships;

o   “Jud Position Active Date” is the date the position (or judgeship) was created. Due to staff 
turnover, we cannot be certain data entered in this column is accurate. In many instances, for 
example, the entry is January 1, 1900. It is possible this field is relatively recent and a date 
arbitrarily was assigned for judgeships existing before a certain date.

o   “Jud Position Inactive Date” refers to dates on which judgeships were eliminated, for example, 
because all trial courts were consolidated into a single superior court in each county. (See, e.g., 
https://www.courts.ca.gov/7790.htm.)

o   “Jud Experience Pending Date” is the date a judge was appointed or elected.

o   “Jud Experience Active Date” is the date a judge took the oath of office.

o   “Jud Experience Inactive Date” is the last day the judge held the listed office.

o   Data entered in the “Jud Experience Term End Date” field may not be reliable. Some of the 
data was migrated from a prior system, which may have applied a different calculation method.

If you have inquiries regarding this matter, you may direct them to Debora Morrison, using the 
contact information contained in the signature block below.

Sincerely,


Public Access to Judicial Administrative Records
```

And the file itself is attached (change the extension to make it work properly).
[20200806 CA Judges 1964-2020.xls.txt](https://github.com/freelawproject/courtlistener/files/5038400/20200806.CA.Judges.1964-2020.xls.txt)

**Comment by litewarp** [comment]
In case anyone is interested, I've deduped the judges and grouped their positions by name. You can find those results in the attached json (need to unzip first).

[ca_judges.json.zip](https://github.com/freelawproject/courtlistener/files/6941819/ca_judges.json.zip)

**Comment by mlissner** [comment]
Well, this was very hard, but I had the honor of finishing it last night. Nick, thank you for your dogged work against all odds to get this done. CLOOOOOSING.
