### ISSUE TITLE
Update DB to add FEC data fields

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1330]
Not sure yet what these will look like, @jonashleyo to do some investigation of what's possible.

**Comment by jonashleyo** [comment]
This seems pretty straightforward.  The FEC provides bulk data downloads and data dictionaries here:  [https://www.fec.gov/data/browse-data/?tab=bulk-data](https://www.fec.gov/data/browse-data/?tab=bulk-data).  The "Contributions by individuals" files reference a committee ID ("CMTE_ID") but not the candidate.  The "Committee master" files include both the "CMTE_ID" and references the candidate so it's a matter of joining three files together per election cycle (2 years).

**Comment by mlissner** [comment]
Any luck thinking through the DB changes needed for incorporating this?

**Comment by mlissner** [comment]
This is a big priority for the week. I'm hoping to do a DB migration with these changes on Thursday.

**Comment by mlissner** [comment]
See https://github.com/freelawproject/courtlistener/issues/1288#issuecomment-662700173 for some field decisions.

**Comment by mlissner** [comment]
Closing this one. Hasn't met demand.
