### ISSUE TITLE
Searches for mixed-case judges don't work right

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#1332]
Colleen McMahon is the Chief Judge of an idiosyncratic insular court known as the Southern District of New York.
A search for "colleen mcmahon" 
https://www.courtlistener.com/?q=colleen%20mcmahon&type=p&order_by=name_reverse%20asc
returns no results.

However, a search for "Colleen McMahon" works:
https://www.courtlistener.com/?q=Colleen%20McMahon&type=p&order_by=name_reverse%20asc

lowercase searches work for most judges, but not those with internal capitals, it would seem.

> Tag it with search and it can be included in the next major solr upgrade.

**Comment by mlissner** [comment]
Duplicate of #824.
