### ISSUE TITLE
Terminated alerts could use better wording

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#1334]
In re the alerts recently added in #1284, I got one on Sunday that seems it leaves some room for improvement. This issue enumerates the questions it raises for me:

> Date: Sun, 05 Jul 2020 16:00:04 -0000 
> From: CourtListener Alerts `<alerts@courtlistener.com>`
> Subject: Weekly PACER alert report — You have 2 old or expiring alerts 
> 
> This email lists docket alerts on long-stagnant cases that you may want to disable or that have been automatically disabled by our systems.
> 
> Disabling these alerts will prevent them from counting towards your quota and will help ease the load on our servers.
> Cases Terminated about 90 Days Ago
> 
> The following terminated cases were last updated about 90 days ago. Are you still monitoring them?
> 
>     [American Immigration Council v. Executive Office For Immigration Review](https://www.courtlistener.com/docket/14604073/american-immigration-council-v-executive-office-for-immigration-review/)
>     Terminated: Apr 3, 2020
> 
>     [RAGBIR v. United States](https://www.courtlistener.com/docket/6286134/ragbir-v-united-states/)
>     Terminated: Jan 25, 2019
> 
> This message brought to you by the non-profit Free Law Project. Please donate to support our work. 

So:

1. Is it really wise to send these alerts on a Sunday? In opposition, a lot of CL users see CL as a business activity that does not get attention on the weekends, and so warnings that get sent on a Sunday won't be seen for at least a day. To the extent they are timely (e.g. disabling alerts), that not great. On the other hand, Sunday is a day of low filing activity, so there's an argument that says it's better to miss things then than other days.

2. I would not have chosen UTC as a timezone, except when I would.

1. The alert asks, "Are you still monitoring them?" If my answer is YES, then what do I do? Both of these alerts are still active, am I supposed to disable them and reenable them to avoid them being disabled automatically later and my missing events? Or would I be (further) warned before that happens?

1. Why am I being alerted for these cases? The first was terminated on April 3, so the 90-day mark makes sense. The second, not as much. The answer is the 2nd had a filing in early April (mandate from the appeals court). But that would be a lot more clear if the report included Date of Las Filing.

1. What case is this, actually? I happen to be following a whole bunch of _Ragbir_ cases (four! two with this identical caption!), and it would be nice to know which one this is. Now, obviously I can click on the link to find out (although mouseover the link is not helpful, since almost nobody memorizes CL docket ID numbers. There's an argument in favor of having the court name or the docket number or both here.

**Comment by mlissner** [comment]
Some responses:

1. Let's discuss on Slack. It was deliberate, but I'm open to being convinced it's not optimal.

2. I don't understand if there's a change requested here.

3. Good feedback. I'll think on that and try tweaking the phrasing a bit.

4. I'll add the date of last filing. Great point.

5. That's an oversight. We usually provide both the court and the docket number; should have done that here. 

Are you looking at the HTML or plaintext? I think they're the same, but I'm curious if that weighed into anything.

**Comment by mlissner** [comment]
OK, so looking at number 3, the phrasing goes like this:

## After 90 days:

> The following terminated cases were last updated about *90* days ago. Are you still monitoring them?

## After 180 days

> *The alerts for these cases will be disabled next week unless you take action.*

> Please disable and re-enable these alerts if you are still monitoring these cases. Doing so will keep them running another 180 days.

## After ~187 days

> Your alerts on the cases below have been automatically disabled. These terminated cases haven't had updates for over 180 days. If these alerts were disabled in error, you can recreate them by clicking below.

So it's not so, so bad. The only one that's utterly un-actionable is the first, and I'll tweak it. The other two basically say what to do.
