### ISSUE TITLE
RECAP docket merging code loses parties

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#1336]
With alarming frequency. For instance, https://www.courtlistener.com/docket/17341219/zw-v-us-department-of-homeland-security/ now has no parties tab.
That means when I run my search at https://www.courtlistener.com/?q=&type=r&order_by=dateFiled%20desc&nature_of_suit=899&filed_after=07%2F06%2F2020&party_name=-CITIZENSHIP%20%22homeland%22%20%22security%22
the case does not show up, which is very…annoying.
And it makes the CL RSS feeds have cases go in and out of them which means they trigger phantom new cases all the time.

Presumably this is a serious bug in the docket merging code.
Not sure if it is the HTML parser or in the CL part.
I think we need access to the uploaded docket HTML to debug, so I think @mlissner  needs to dredge it up.

If you can find some examples for this case and attach them here I should be able to confirm whether or not it's a juriscraper bug.

**Comment by mlissner** [comment]
These are the identifiers, types, and creation dates for the six HTML docs we've gotten so far:

```
3526123 HTML Docket 2020-07-11 08:42:08.610843+00:00
3529196 HTML Docket 2020-07-13 21:07:11.797514+00:00
3526368 HTML Docket 2020-07-11 21:19:39.613725+00:00
3526373 HTML Docket 2020-07-11 21:30:27.657157+00:00
3527405 HTML Docket 2020-07-13 11:25:37.838498+00:00
3529563 HTML Docket 2020-07-14 00:15:07.053588+00:00
```

I'll attach a zip in a moment with the HTML, I think.

**Comment by mlissner** [comment]
Here are the anonymized dockets.

[html-dockets.zip](https://github.com/freelawproject/courtlistener/files/4915868/html-dockets.zip)

**Comment by mlissner** [comment]
OK, so when parsing, the last one has no parties, but the second to last one does. Our DB isn't versioned (yet), so it's hard to figure out when things really went wrong here, but it's a good bet that the one without parties is where things went wrong.

**Comment by mlissner** [comment]
And confirmed with the following two commands. After the first, the parties appear, after the second, they're gone:

```
curl -v  --form upload_type=1 --form "filepath_local=@/tmp/dockets/3529196.html" --form court=cacd --form pacer_case_id=787913 'http://localhost:8000/api/rest/v3/recap/' --header 'Authorization: Token 4605b148dfad4478864415099df79a9f69a503fa '
```

```
curl -v  --form upload_type=1 --form "filepath_local=@/tmp/dockets/3529563.html" --form court=cacd --form pacer_case_id=787913 'http://localhost:8000/api/rest/v3/recap/' --header 'Authorization: Token 4605b148dfad4478864415099df79a9f69a503fa '
```

(Tokens are from my local machine, you can have 'em, so long as my office mates on the network don't find this.)

**Comment by mlissner** [comment]
Well, the code is pretty obviously wrong. First, it adds each party it sees:

```
def add_parties_and_attorneys(d, parties):
    """Add parties and attorneys from the docket data to the docket.

    :param d: The docket to update
    :param parties: The parties to update the docket with, with their
    associated attorney objects. This is typically the
    docket_data['parties'] field.
    :return: None

    """
    normalize_attorney_roles(parties)

    updated_parties = set()
    updated_attorneys = set()
    for party in parties:
        # Add the party and their attorneys
        [...]
```

Then it deletes all the ones it had before that it didn't just see:

```
    disassociate_extraneous_entities(
        d, parties, updated_parties, updated_attorneys
    )
```

The idea here is to remove any entities that are no longer on the docket (with some exceptions and subtleties I didn't study). 

Anyway, you can see the painful thing that's wrong here: There's no check to ensure that there is at least one party. So if there are none, it'll just delete everything. Easy fix and a test coming in a moment.

**Comment by mlissner** [comment]
Yes, this is another reason to re-parse everything. No, I'm not planning to do that now. But we will one day.
