### ISSUE TITLE
[EPIC] Create "Projects" as a top level object in CourtListener

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1339]
A user reported to us today that they want their alerts to be put into "folders" of some kind. That way, when they get alerts, the project name can be in the subject line and they can use email rules to direct the emails to the right place. Seems reasonable. 

Another user has asked that his *favorites* be added to some sort of folders or projects or something. 

Another user wants to make public collections of dockets that they can share for various reasons. 

Another idea is to allow tagging on particular items, like del.ico.us or something.

Another issue is that favorites are really hard to notice. People have never used them as much as I think they should. 

So people want favorites, they want folders, they want tags, etc. 

Getting this right is tricky. I think a simple solution is to just allow stuff to be added to "projects". This can work in a similar way to Github's Project drop down when creating or editing an issue. There's also prior art on MuckRock, where things can be added to projects. 

Anyway, any top-level object should be allowed in a project: Opinions, Clusters, Dockets, Oral Arguments, and maybe People. 

Projects themselves get URLs. They can be public or private, but there's no finer-grained permissions beyond that. They get name and a description. When you look at a project page (`/projects/yourusername/1` or `/projects/1`), you see all the objects that are a part of it, possibly in a tabbed interface? And you should probably see who created it, I guess. We can borrow from the visualizations to make this consistent. 

When docket alerts are sent, the emails get subject lines containing something like: `[civil-rights, 1st-A]`. 

Question: Do we allow whitespace in project names? If not, I guess we could put them in URLs: `/projects/civil-rights/`, but of course that makes them less readable. I also like that it'd limit people to a few characters, which makes for better subject lines.

**Comment by mlissner** [comment]
I guess if a docket is in a public project, we should show that on the project page? 

Oh, and project pages should get view counts, even if we don't display those to users.

**Comment by mlissner** [comment]
Projects also show up:
 - in the favorites section of user's profile
 - in the alerts section of the user's profile
 - in their own tab in the user's profile

What else?

**Comment by ikeboy** [comment]
Just noting that it should be possible to clone a public project to your own user.

**Comment by MargoSchlanger** [comment]
Maybe already clear, but it would be best if things could have more than one project tag.  (So folders is definitely a metaphor)

**Comment by mlissner** [comment]
This feature is a tough one to design. Another concept was to have this feature subsume the favorites feature, with existing features just merged into a new project called "Favorites". The problem with that is that we want a way for folks to save a note along with objects, so if we only allow things to be added to projects, we lose our existing notes. So that approach is out.

I think that leaves either folders, projects, or tags:

 - I don't really like that "projects" implies you're doing...something with the content there. Like...it's not something you're working on, so why is it a project? 

 - Folders feels weird to me too. It's too...skeuomorphic. We're putting dockets full of files into...folders? Feels weird to me. And you can put one docket in multiple folders? That defies both the real-world and the desktop metaphor. I also just don't like the URLs: `/folder/22/some-slug-i-guess/`

 - Tags feels kind of boring and overdone, but it's also not horrible. They totally lack personality, but people know what tags are, and having a url like `/tag/22/some-slug/` somehow feels OK. 

Tags also support all of the use cases requested here:
 - Yes: Subject lines with special words
 - Yes: Having a page with a collection of things (Currently requested by @Avi Eisenberg as allowing favorites to be put in a folder.)
 - Yes: Creating public collections
 - Yes: Promoting favorites better (via UI tweaks)
 - Yes: Clonable public projects
 - Yes: Multiple tags per object

I'm going to start building this out.

**Comment by mlissner** [comment]
The database part of this is complete and deployed. @flooie I think we should work on this together. I'll do Python, you do JavaScript. Unless @litewarp is interested in making a little JS picker thing?

**Comment by mlissner** [comment]
OK, here's our URL design, I think. Comments very welcome:

## AJAX endpoints

`/tags/` --> Shows all tags for the user. Accepts a GET parameter `q`, probably, that can search tags for the user by tag name

`/tags/new/` --> Create new tags, plural

`/tags/edit/` --> Edit a tag (allows name, title, description, published (true/false))

`/tags/delete/` --> Delete a tag

## HTML pages

`/tags/mlissner/intellectual-property/` --> Shows a given tag's page (returns a 404 if the tag is private, like the visualizations pages)

`/tags/mlissner/` --> Redirects to /account/tags/, where tags can be edited

**Comment by mlissner** [comment]
Getting ready to deploy this. Comes with some SQL changes again, so those will require that I run:

```
cl && psql -h aws -U django --dbname courtlistener -p 5432 <  cl/favorites/migrations/0006_ditch_generic_fk.sql
```

and:

```
GRANT SELECT ON favorites_dockettag to replica;
```

Then run:

```
 alter subscription replicasubscription2 REFRESH PUBLICATION;
```

**Comment by mlissner** [comment]
I'm pretty comfy saying this is done. Tags are a good way for folks to organize things.

**Comment by MargoSchlanger** [comment]
This is excellent! Thanks!
