### ISSUE TITLE
Need a button fo "Last Page" on long dockets

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1354]
Our users currently have to flip the ordering or URL hack to accomplish this. Both are lame workarounds. We should have "Last Page" buttons.

**Comment by flooie** [comment]
Or a view all would be nice.

**Comment by flooie** [comment]
Even ifs its a one off.  What if we put a limit where if the docket is more than 10 pages long.  No view all option.

**Comment by mlissner** [comment]
Dup of https://github.com/freelawproject/courtlistener/issues/1368
