### ISSUE TITLE
Searching for a docket number with initials should return the docket

### ISSUE THREAD

**Issue by ikeboy** [freelawproject/courtlistener#1394]
Example: https://www.courtlistener.com/?type=r&q=1%3A17-cv-08603-JSR&type=r&order_by=score%20desc

No results. But it should return https://www.courtlistener.com/docket/6218685/stevens-v-vodka-milk-llc/, at least. Preprocess the docket number to remove the ending initials, perhaps?

**Comment by mlissner** [comment]
Seems like a good idea to me. Want to take a stab at it?

**Comment by mlissner** [comment]
Duplicate of: https://github.com/freelawproject/courtlistener/issues/764
