### ISSUE TITLE
What black version is used?

### ISSUE THREAD

**Issue by malteos** [freelawproject/courtlistener#1395]
Hi @mlissner 

I see you added a black test to the CI. What version is used? 

Locally everything works fine:

```
black --version
black, version 19.10b0
...
black cl/search/tests.py --check -t py27
All done! ✨ 🍰 ✨
1 file would be left unchanged.
```

But the CI fails: https://github.com/freelawproject/courtlistener/pull/1281/checks

The GitHub action (https://github.com/lgeiger/black-action) does not have a fixed black version.

**Comment by malteos** [comment]
With this it works:
```
black --version
black, version 20.8b1
```

Maybe specify the explicit version in the workflow?

**Comment by mlissner** [comment]
I created a PR for this, but it seems like the thing we use isn't being maintained anymore. Perhaps we need to fork it instead: https://github.com/lgeiger/black-action/pull/10

**Comment by malteos** [comment]
In another project, we use pre-commit with black and GitHub actions. Maybe this would be an alternative?

https://black.readthedocs.io/en/stable/version_control_integration.html
https://github.com/openredact/expose-text/blob/master/.pre-commit-config.yaml
https://github.com/openredact/expose-text/blob/master/.github/workflows/ci.yml#L5-L11

**Comment by mlissner** [comment]
Yeah, I kind of hate the idea of the precommit project. It's a meta package manager that can install stuff from Ruby or Python or node, and...it's just too much for me to trust, recommend, and install.

**Comment by drewsilcock** [comment]
Just an FYI, there's an official Black GitHub Action which is located at the main Black repo at https://github.com/psf/black.

Example usage can be found at:

- https://github.com/psf/black#github-actions
- https://black.readthedocs.io/en/stable/github_actions.html.

**Comment by mlissner** [comment]
Yeah, somebody mentioned that elsewhere. Must be a new thing. We should switch over to it if it's not too difficult/messy. No reason to stick with the unmaintained one.

**Comment by drewsilcock** [comment]
FYI I've put a PR up for moving to the official Black GH action (it wasn't difficult or messy!): #1409

**Comment by mlissner** [comment]
I think we're good here? The change in #1409 prints the version of black, so I think that's about as good a fix as we can hope for. It should also keep us on the latest stable version.
