### ISSUE TITLE
Add password check before deleting accounts

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1399]
We got a vulnerability report this weekend that reported that we don't require a password prompt before deleting accounts. I don't think this is a vulnerability, but I do think it's a good suggestion we should do at some point. The UX is currently:

- Click button that says, "delete my account"
- Click button on next page that says, "Yes I'm sure."

I think on that second page we could have a little password box and that'd take care of this nicely.

**Comment by lilianaguerrero** [comment]
Hi I'm interested in taking this on. Just to be clear: we want the flow to be: 1. Click the button that says, "delete my account" 2. A password prompt pops up 3. Click button says "Yes I'm sure".

**Comment by mlissner** [comment]
Awesome! Yeah, I think that'd be great. I actually think the confirmation page doesn't really need a popup though. It could just be like it is now and also ask for a password as part of the "Yes I'm sure" form. 

Thank you!

**Comment by lilianaguerrero** [comment]
Ok that makes more sense! I'm on it.

**Comment by mlissner** [comment]
Hey, whatever happened here?

**Comment by lilianaguerrero** [comment]
Hi, I have not had time to address this yet. I hope to get to it in the
coming weeks, but if someone else wants to fix this sooner please go ahead.

**Comment by mlissner** [comment]
No, nobody is vying for it. I thought I'd ask because we had another vuln researcher report this today, so I guess there's becoming something of a chorus saying that it needs to be done. No rush!

**Comment by mlissner** [comment]
Just to keep a tally here (no pressure, @lilianaguerrero), another sec researcher reported this today.
