### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by wesdesign** [freelawproject/courtlistener#1436]
It seems that when I try to do a search with RECAP it causes an error. It happens when I search jurisdictions within the southern district of California.

Here is the error message:

An Unknown Error Occurred
It appears the site is having an error. We've been automatically alerted, and we will work to resolve it as soon as possible.

In the mean time, you have some options, if you like:

Wait a bit, and come back later — sometimes the errors are temporary
File a bug if you think we may not know about this error, or if you have more details to share with us
Try something else, like a new search or sending us a message with what happened
Sorry about this. If you continue having problems, please do let us know.

**Comment by mlissner** [comment]
Should be fixed now. If not, please share a link.
