### ISSUE TITLE
Deprecation warning while sending alerts

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1441]
Got these logs while sending alerts. Looks like most or all of them can be nuked:

```
Warning: No such file or directory: /var/log/juriscraper/debug.log. Have you created the directory for the log?
Juriscraper will continue to run, and all logs will be sent to stderr.
/usr/local/src/scorched/scorched/search.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  return not isinstance(val, basestring) and isinstance(val, collections.Iterable)
/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py:356: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.21.0.2', 48138), raddr=('192.168.0.243', 8983)>
  self.fetch_command(subcommand).run_from_argv(self.argv)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py:356: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.21.0.2', 48148), raddr=('192.168.0.243', 8983)>
  self.fetch_command(subcommand).run_from_argv(self.argv)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py:356: ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.21.0.2', 48150), raddr=('192.168.0.243', 8983)>
  self.fetch_command(subcommand).run_from_argv(self.argv)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>
```

**Comment by mlissner** [comment]
Most of this issue is resolved, but I haven't been able to track down the last line:

    sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>

**Comment by flooie** [comment]
I think this should actually be ignored.  Its saying we dont close dev null but dev null is technically not a file it just pretends to be a file.

**Comment by mlissner** [comment]
Right, I'm happy to ignore it, but since this is coming from a cron job, if there are errors, they get emailed to me, so doing *something* about this is needed.

**Comment by mlissner** [comment]
Well, I squashed the error, but to do it I had to strip out all of CourtListener. Progress!

**Comment by mlissner** [comment]
OK, I've pinned it down to the simple pages url. Removing this line fixes the error:

url("", include("cl.simple_pages.urls")),  # <<--- !!!

Getting close!

**Comment by mlissner** [comment]
I have now binary searched the entire codebase. It comes to this line (but possibly others):

    from juriscraper.lib.test_utils import MockRequest

With most of the code base commented out such that the error message goes away, and with that line and nothing else in a management command, the error comes back:

```python
from django.core.management import BaseCommand
from juriscraper.lib.test_utils import MockRequest


class Command(BaseCommand):
    def handle(self, *args, **options):
        print("Ran it.")
```

Comment out line 2 above, and the error goes away.

**Comment by mlissner** [comment]
Got it. Juriscraper has a line that says:

    warnings.simplefilter("always")

That'll do it, folks. Remove that so that we have normal logging and that warning is filtered by default. Off to fix Juriscraper.
