### ISSUE TITLE
REST api pagination is broken

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1453]
The REST api returns a JSON response containing up to 20 results at a time with a URL to the next page of results named `next`.

This was discovered when researching data in Nebraska, so I am adding URL for examples.  I'm dropping 

`https://www.courtlistener.com/api/rest/v3/search/` from the examples below.

We should see the following pattern
```
1) ?court=neb&court_citation_string=Neb.&filed_after=2017-06-01
2) ?court=neb&court_citation_string=Neb.&filed_after=2017-06-01&page=2
3) ?court=neb&court_citation_string=Neb.&filed_after=2017-06-01&page=3
4) ?court=neb&court_citation_string=Neb.&filed_after=2017-06-01&page=4
5) ?court=neb&court_citation_string=Neb.&filed_after=2017-06-01&page=5
```

What we are actually seeing is this
```
1) ?court=neb&court_citation_string=Neb.&filed_after=2017-06-01
2) ?court=neb&court_citation_string=Neb.&filed_after=2017-06-01&page=2
3) ?court=neb&court=neb&court_citation_string=Neb.&court_citation_string=Neb.&filed_after=2017-06-01&filed_after=2017-06-01&page=3
4) ?court=neb&court=neb&court=neb&court_citation_string=Neb.&court_citation_string=Neb.&court_citation_string=Neb.&filed_after=2017-06-01&filed_after=2017-06-01&filed_after=2017-06-01&page=4
5) ?court=neb&court=neb&court=neb&court=neb&court_citation_string=Neb.&court_citation_string=Neb.&court_citation_string=Neb.&court_citation_string=Neb.&filed_after=2017-06-01&filed_after=2017-06-01&filed_after=2017-06-01&filed_after=2017-06-01&page=5
```

Every call adds the parameters back into the API next call.  This is a problem for anyone that wants to paginate through a pages of data.  At some point this should bump into max size of URLs, slow our parsing down etc.

**Comment by mlissner** [comment]
Does this only affect the search API? Could be unrelated to py3 if so.

**Comment by flooie** [comment]
It affects other APIs 

Here is clusters

```
https://www.courtlistener.com/api/rest/v3/clusters/?court=neb
http://www.courtlistener.com/api/rest/v3/clusters/?court=neb&page=2
http://www.courtlistener.com/api/rest/v3/clusters/?court=neb&court=neb&page=3
http://www.courtlistener.com/api/rest/v3/clusters/?court=neb&court=neb&court=neb&page=4
http://www.courtlistener.com/api/rest/v3/clusters/?court=neb&court=neb&court=neb&court=neb&page=5
```

**Comment by mlissner** [comment]
I don't follow. When I go to:

    https://www.courtlistener.com/api/rest/v3/clusters/?court=neb&page=2

It shows good `next` and `prev` links? Clicking them continues to show good links?

**Comment by flooie** [comment]
This is not an issue.  I had a bug in my tests.
