### ISSUE TITLE
Supervisor unreliable due to calls into the docker stack

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1470]
On our docker host, we use supervisor to run our daemons, and while dockerizing I took the easy path by just tweaknig it to `docker exec` into our running containers. That kinda works...until the containers go down. I thought supervisor would figure this out and launch things again, but nope. 

The consensus for this seems to be that the better way of fixing this is to ditch supervisor and instead let docker compose run them.

This is a high priority because it lets us ditch supervisor (yay!) and because our daemons are not reliable right now.

Supervisor cleanup can happen in #1464.

**Comment by flooie** [comment]
I'm taking a first look at our ansible commands.  We can ditch the docx2txt I would imagine now that its integrated into the docker containers.

**Comment by mlissner** [comment]
This deployed cleanly. Supervisor is purged. Long live supervisor.
