### ISSUE TITLE
Unicode not rendering properly in search snippets

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1486]
I noticed today that the § mark does not render properly in the search results page.

For example a [search page](https://www.courtlistener.com/?type=o&q=Ga.%20Laws&type=o&order_by=score%20desc&stat_Precedential=on&court=gamd%20gand%20gasd%20gamb%20ganb%20gasb%20ga%20gactapp)

```Constitution of Georgia (Code, &#167; 2-103), which… ``` instead of 
```Constitution of Georgia (Code, § 2-103), which... ```

**Comment by mlissner** [comment]
In case we don't get to this for a while, [this might be a more focused search](https://www.courtlistener.com/?q=id%3A(3402331)%20Ga.%20Laws&type=o&order_by=score%20desc&stat_Precedential=on). (Look for the ampersand.)

**Comment by mlissner** [comment]
I still see this. We'll get it fixed as part of the switch to Elastic Search. Thanks Bill.

**Comment by mlissner** [comment]
![image](https://user-images.githubusercontent.com/236970/234131633-23a9c9bc-8c1e-4050-b0cc-e3dd067f471a.png)

**Comment by mlissner** [comment]
This is fixed in the new RECAP search (make sure you're a beta tester, then try): https://www.courtlistener.com/?q=%C2%A7%20-%22sec%22%20-%22section%22%20-%22sectional%22&type=r&order_by=score%20desc
