### ISSUE TITLE
Embedded visualizations no longer viewable after nginx upgrade

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1489]
In our latest nginx, we have a very string security config that includes:

    add_header X-Frame-Options         "SAMEORIGIN" always;

That config means that none of our pages can be embedded except on CourtListener.com. That's great, but it breaks the embedded visualizations we have on pages like this one: 

https://free.law/2016/02/22/our-newest-launch-a-scotus-data-viz-tool/

I'd like to try to fix this. I'm not sure how easy it will be. For example, if we set the header via Gunicorn, will nginx override it? We'll see, I suppose.

**Comment by flooie** [comment]
When you say fix - do you mean allow embeds on free.law or allow anyone embed visualizations.

**Comment by mlissner** [comment]
Any sites should be allowed to embed the emebeddable URLs, but no other URLs.

**Comment by mlissner** [comment]
Alas, the first solution didn't work. It just stacked the header so it's now sent twice somehow.
