### ISSUE TITLE
Strange intersection of citations and footnotes?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1496]
There's some weird stuff going on with the HTML of this opinion: 

https://www.courtlistener.com/opinion/2753804/evans-v-commr/

@flooie can you take a look?

**Comment by flooie** [comment]
On it.

**Comment by mlissner** [comment]
Another example reported by a client here: https://www.courtlistener.com/opinion/4824587/de-mendoza-v-commissioner/

**Comment by flooie** [comment]
This is strange and I think there is something strange about the anon- database that it relies upon.  It appears to have competing page numbers but I can only verify one set when I look at other sources so im going to only show one for now.

**Comment by mlissner** [comment]
Great to see you digging into this one. Is it possible it has multiple page numbers from multiple parallel citations?

**Comment by flooie** [comment]
I no longer see anything weird here.  I think we may have resolve this with the big redesign.
