### ISSUE TITLE
Customize Error Pages

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1516]
We should add custom error pages for our NGINX world.

<img width="1539" alt="Screen Shot 2020-12-23 at 2 02 06 PM" src="https://user-images.githubusercontent.com/6464529/103029358-a50bff00-4527-11eb-956b-74b38aa688ac.png">

**Comment by mlissner** [comment]
I have no idea how to do this, but Django does give custom ones for 404's, so it seems like it shouldn't be that hard — maybe.

**Comment by flooie** [comment]
I've done it before, I think I used this excellent [digital ocean tutorial](https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-to-use-custom-error-pages-on-ubuntu-14-04) to do it.

**Comment by mlissner** [comment]
Ah, yeah, that's not too bad. I was hoping to do it via Django somehow, but I suppose that is an impossible hope.

**Comment by flooie** [comment]
impossible ... <shrug>. but yes it looks uncomplicated.

**Comment by mlissner** [comment]
No more nginx, so closing this.
