### ISSUE TITLE
Disclosure low hanging fruit data cleanup

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1549]
The data is good but could be better.  Dates, and numbers, title casing and more can be done to large parts of the data.

**Comment by flooie** [comment]
Spouse and Gifts received a major update with regard to the low hanging fruit today.  

**Gift values** had around 800 easy or obvious tweaks. 
For example S1,100.00 could be converted easily to $1,100.00 or $10O.00 to $100.00

Additionally, about 40 objects meant to Liabilities or Reimbursements found their way into Gifts and they were removed and transferred.


**Spouse Income** actually received a larger cleanup due to an older formatted financial disclosure that was not taking into account before processing.  The disclosure extractor used document/line structure to identify changes in sections.  Unfortunately the older documents only had two entries for reimbursements instead of five.  That meant there was no indication that we were no longer in spousal incomes. This cause sections that follow spousal incomes to continue to slow into spousal incomes.  This includes reimbursements, liabilities, and gifts.

This means that we are moving incorrectly slotted spousal incomes back to their appropriate section.  

- Convert 291 spousal incomes objects to gifts
- Convert 4,925 spousal incomes objects to reimbursements
- Convert 1,706 spousal incomes to debts
- Delete 45 objects that fall into the other

This should not be a problem moving forward because the documents are more uniform and clean and dont use the older format, of which we didn't have that many.  


As for gifts, we should consider fine tuning the gift extraction OCR to only look for numbers as a first pass - and then look for text afterwards.  While there are sometimes commentary in the value section its not common.

**Comment by mlissner** [comment]
>  For example S1,100.00 could be converted easily to $1,100.00 or $10O.00 to $100.00

Can you say or better yet, provide code about how you identified these?

> Additionally, about 40 objects meant to Liabilities or Reimbursements found their way into Gifts and they were removed and transferred.

It'd be good to document what you mean by "found their way" if it's not the thing below.

> due to an older formatted financial disclosure that was not taking into account before processing

Sorry, I forget, is this fixed going forward by using a different approach, or is it fixed by us not having any more of that older format going forward? If the latter, should we have a warning somewhere or something that says, like, "You're parsing an old format that has bugs, beware of issues identified in #1549"?

**Comment by flooie** [comment]
@mlissner I can do that.

The full code should be available in the cleanup-scripts named `corrections_fd.py` as a complete file but here are the relevant snippets.

After filtering out the good gift amounts, I ran a series of regexes for common issues.  The following are common examples that were clear and easy to address.

1.000.00 => to 1,000.00
1,000. => 1,000.00
1.000 => 1,000.00
1,000.0 => 1,000.00

Other mistakes were reviewing by me and were less common but easy fixes 

$S00.00  => 800
$100.$0 => 100.00
$4,$00.00 => 4,500.20

I found that S's were particularly difficult for the OCR and were treated different depending on where they were found inside the number.  

If found directly after the $ sign they were mistaken for 8's.  If at the end of the number they were 0s and in the middle they were 5s.

The remainder where variations of the first issues, commas and periods etc.

```
    if re.match(r"^\$\d\.\d{3}\.\d$", v):
        v = v.replace(".", ",", 1)
    if re.match(r"^\$\d{3,}\.$", v):
        v = v + "00"
    if re.match(r"^\$\d\.\d{3}$", v):
        v = v.replace(".", ",") + ".00"
    if re.match(r'.*\d{4,}$', v):
        v = f'{v[:-2]}.{v[-2:]}'
    if re.match(r'^\$\d{3,}\.\d$', v):
        v = v+"0"
    if re.match(r"^\$S.*", v):
        v = v.replace("$S", "$8")
    if re.match(r"^S.*", v):
        v = "$"+v[1:]
    if re.match(r"^S?\d{1,3}?,?\d{1,3}?(\.\d{2})?$", v):
        v = v.replace("S", "$")
    if re.match(r"^S|\$?\d{1,3}(\.)\d{1,3}?(\.\d{2})$", v):
        # Fix Leading S
        v = v.replace(".", ",", 1)
    if re.match(r"^\$?(\d{1,3},)?\d{1,3}?(\.\d{1})?$", v):
        v = v + "0"
    if re.match(r"^(S|\$)(\d{1,3}) \d{2}$", v):
        v = v.replace(" ", ".").replace("S", "$")

    if re.match(r"^\$? ?(\d{1,3}?,?)?(\d{1,3}?(,| )?)?\d{1,3}?(\.\d{2})?$", v):
        v = v.replace(" ", ",")
```


Identifying incorrect data in sections is relatively easy now.   identifying the type of information that one would expect is quite informative.  Reimbursements are generally much longer in length, but other things as well.

Spousal income first field is a date, usually four digits but not always.  
So it makes filtering out incorrect spousal incomes easy as the following three sections are all text descriptions etc.

Each section is just unique enough to allow the filtering at a high degree of confidence.  This was followed with spot checks of perhaps a dozen key words and a hundred or so Pdf checks.  


As to "found their way" I dont know exactly how the other sections had a handful of errors yet.  But I will keep digging.  My gut tells me these are probably hand written or bad scans that cause these issues.

Lastly, nothing is fixed for these old documents but they shouldn't be an issue for us processing 2018 + and moving forward.  We should add a note to the readme for older documents.
