### ISSUE TITLE
Dependabot doesn't upgrade dependencies before running tests

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1582]
This is bad because it guarantees that tests run using the old docker images, which, in turn, will always pass.

**Comment by mlissner** [comment]
So the simple fix here, I thought, was to simply use `poetry install` inside the cl-celery and cl-django containers. Alas, that doesn't really work because:

1. cl-celery is run as www-data, which doesn't have install permissions
2. Even if you do the above, it's unclear how to restart celery with the new dependencies

Taking a step back, it seems like we can use this opportunity to make our deploy process more reliable. Here's how I think this will go:

1. We always build the latest docker image using docker's [build-push-action](https://github.com/docker/build-push-action). This will ensure that our tests are run on the latest dependencies.

2. When we build it, we cache it. That should make it fast, so it doesn't make our tests too much slower.

3. If we push to master, and it's tagged, and all tests pass, we push a new docker image to docker hub

I think this should take care of things pretty well, without adding too much delay. It could make our lives a bit easier too, since we won't have to push large docker images ourselves on our middling internet connections. This, instead, will push those images from Github to docker, which should make things smoother.

**Comment by flooie** [comment]
@mlissner I think conceptually that should work, but does that leave the possibility that we have an error not caught in tests?

**Comment by mlissner** [comment]
Ok, so the build-push-action is kind of a pile of hot garbage at the moment. The documentation is bad, the functionality is unclear, it breaks things I can't explain, and so, after trying things with it all day, I'm just going to accept that it totally doesn't work. 

Instead, I'm going to use docker hub as our cache. It'll be...fine:

1. We build and push for every commit.

1. If a layer already has been built and pushed, it won't need to be built again b/c it'll be found in docker hub

1. Step three as before. If it's a tagged push to master, and all the tests pass, we push a new docker image tagged as latest.

**Comment by mlissner** [comment]
OK, this is in *pretty* good shape. Here's the final solution:

1. We build and push on every commit before running tests. The built images are tagged with the commit hash and pushed.
2. Unfortunately, when we start docker compose, despite having *just* built the images, we download them again. This makes things slower and I don't know why it's happening. It's annoying and if somebody clever is paying attention, a fix would be fantastic.
3. Docker Hub automatically builds images every time we push to master. These are tagged with *latest*. 
4. There's a new feature in our compose file. If you want to override the tag being used when starting images, you can set it with command line variables! 

Altogether, this means that:
 - Our tests are run on images that integrate the latest dependencies.
 - Anything pushed to master automatically goes to docker hub as "latest"
 - Devs have a new feature for overriding the tag that's used in the compose file
