### ISSUE TITLE
Complete architecture design for recap.email

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1632]
This shouldn't be too bad, but we should write down hos SES, Lambda and our server works.

**Comment by mlissner** [comment]
Follows is a data flow diagram that explains the architecture. 

1. An email is received by AWS SES. 

2. This triggers a lambda function that:
    - Verifies the sender and eliminates spam by using SES tools or DMARC/SPF/DKIM
    - Sends a POST to the CourtListener server with the email attached and any additional information from the email envelope that might be useful.
    - Retries any failed tasks with an exponential backoff (can lambda do this?)
 
3. Upon receiving the email, the CourtListener server:
    - Verifies the source (an auth token can be hardcoded in the lambda code)
    - Stores the API request as a record in the DB, saves the original email in S3 using django-storage. 
    - Associates the new DB record with the correct CourtListener user by using the email's recipient email address. If the email address cannot be found, no further processing happens and an error status is set.
    - Sets a status flag on that record as queued for processing and returns a `201 CREATED` response to lambda
    - Creates a celery task to process the email

4. Celery workers monitor the queue for new tasks. Upon receiving a task, the worker:
    - Downloads the email from S3, parses it, downloads the PDF, and merges the results with the case database
        - Checks for sealed content. If found, does not fetch PDF, and sets a status flag.
        - Checks that the PDF is still free. If not, does not fetch the PDF and sets a status flag.
    - Checks if the user account has a webhook configured. If so, creates a webhook task for the item in the queue (this is done even if errors occur)
    - Checks if the user wants ECF emails forwarded. If so, creates and sends an email with the item attached. (this is done even if errors occur)

5. If a webhook is configured for an account:
    - Send it a POST with the information from the email
    - If it fails, log that failure to the user's account, notify them, and try again using exponential backoff.
    - If webhooks fail too much, disable them (and send an email)

## Questions 

1. Can lambda do automatic retries? What's the workflow for re-running a failed lambda task?

**Comment by tewen** [comment]
@mlissner As I mentioned when we went through it. Your documentation is excellent. I pulled down Court Listener today, and I have a few questions that I'll need in order to get the right scope of work together:

1. Where is the best example of Lambda functions in your codebase? Are you happy with how they are setup, or are you looking for some innovation here?
2. Did you specify the interface between the received SES email and the Lambda function that processes it? I don't think this is accounted for in your models, and that's fine, but I wanted to know if you had strong opinions on it?
3. I noticed in the recap section of the codebase, you have [management/commands](https://github.com/freelawproject/courtlistener/tree/master/cl/recap/management). Is this a good place to write the hooks for different operations? Are these more like manual integration tests?
4. When you say that the email is saved to S3 are we really just referring to the file itself? Or do you have a standard way for storing emails as an entire compressed entity?
5. Where in the code is a good example of the sealed vs. non sealed content in Pacer? Or you could show me example emails.
6. How much control will users have on their Webhooks from the UI? Is it as simple as a URL? Do they specify method? Do they add authorization?

Some information for you:
1. Looks like we get Dmarc validation from SES [here](https://aws.amazon.com/blogs/messaging-and-targeting/amazon-ses-now-supports-dmarc-validation-and-reporting-for-incoming-email/).
2. Looks like we can [support retries with Lambda](https://docs.aws.amazon.com/lambda/latest/dg/invocation-retries.html), not a huge suprise there.
3. Looks like we can use [this](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-action-lambda-event.html) to trigger the Lambda function when the email is received.

Thanks for making this easy. It's been nice to look at the codebase so far.

**Comment by mlissner** [comment]
>     1. Where is the best example of Lambda functions in your codebase? Are you happy with how they are setup, or are you looking for some innovation here?

We have only a few set up so far. One is functionally fully independent and doesn't do anything important, so I'm very comfy with it living only in the AWS console. I just created the other on Tuesday. It uses lambda@edge to add headers to S3 requests so they're extra secure and unfindable by search crawlers. 

If you have the expertise, I think the right way to do recap.email's lambda work is to set up CloudFormation, and deploy using the SAM CLI. The services are independent from the rest of our systems, so at least it won't be retrofitting CloudFormation onto existing stuff.

All this to say: Our lambda functions live in AWS console, which sucks. I think we should create a new repo for them and have them live there. I can't think of any reasons to put these in the CourtListener repo at the moment, and it feels cleaner to pull them into their own universe. Open to contrary thoughts here though.
 
>     2. Did you specify the interface between the received SES email and the Lambda function that processes it? I don't think this is accounted for in your models, and that's fine, but I wanted to know if you had strong opinions on it?

No, I'm not sure what the pipeline is there, sorry. I _think_ that SES puts messages into S3 and lambda picks them up from there? But boy, it'd be nice if lambda can subscribe directly to the SES messages somehow. Maybe via SQS? I'm out of my comfort here a bit, but I suspect one answer is going to be better than others.

>     3. I noticed in the recap section of the codebase, you have [management/commands](https://github.com/freelawproject/courtlistener/tree/master/cl/recap/management). Is this a good place to write the hooks for different operations? Are these more like manual integration tests?

What kinds of operations are you thinking of? These are usually for either cron-based or one-off scripts. Integration tests would live in the tests.py or the cl.tests.xyz files.

>     4. When you say that the email is saved to S3 are we really just referring to the file itself? Or do you have a standard way for storing emails as an entire compressed entity?

The idea here is to keep records just in case. Hopefully lambda works properly and all is well, but we want to have the originals around just in case. One just in case thing that's come up before is if our data extractor has a bug, we might want to go through and re-extract all of the emails, say.

>     5. Where in the code is a good example of the sealed vs. non sealed content in Pacer? Or you could show me example emails.

I'll have to do some digging for this. I have a note that says I have examples of sealed content, but it's been a few years. I think we'll be able to look for particular phrases in the emails and work from that, but we might need to do belt and suspenders and also look for similar phrases when downloading. Is that enough to go on for now, or would you prefer I go dig things up for you now?

>     6. How much control will users have on their Webhooks from the UI? Is it as simple as a URL? Do they specify method? Do they add authorization?

This is a very good question I hadn't considered. I started issue #1650 to discuss this, but the conclusion I came to is that we don't need it. I left that issue open in case you have an opposing view.


> Some information for you:
> 
>     1. Looks like we get Dmarc validation from SES [here](https://aws.amazon.com/blogs/messaging-and-targeting/amazon-ses-now-supports-dmarc-validation-and-reporting-for-incoming-email/).

Great. I went and looked and used mail-tester.com to check if DKIM, SPF, and DMARC are configured, and it sort of didn't seem like it for cand.uscourts.gov, at least. I'm guessing I'm missing something and we'll learn if they have good anti-spam stuff in place soon.

(This query finds all the notice examples I have in my inbox: `"uscourts.gov" -from:uscourts.gov notice "activity in case" `)


>     2. Looks like we can [support retries with Lambda](https://docs.aws.amazon.com/lambda/latest/dg/invocation-retries.html), not a huge suprise there.

Excellent.


>     3. Looks like we can use [this](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-action-lambda-event.html) to trigger the Lambda function when the email is received.

That looks right to me, yep.

**Comment by mlissner** [comment]
Sorry, in case I was unclear, we don't need to move the existing lambda stuff to CloudFormation, but we should do the right thing going forward.

**Comment by mlissner** [comment]
I'm just reviewing things @tewen, and this has some info about how the email is supposed to be associated:

> ### 3. Upon receiving the email, the CourtListener server:
>  [...]
> Associates the new DB record with the correct CourtListener user by using the email's recipient email address. If the email address cannot be found, no further processing happens and an error status is set.

And:

> ### 4. Celery workers monitor the queue for new tasks. Upon receiving a task, the worker:
>  [...]
>  Checks if the user account has a webhook configured. If so, creates a webhook task for the item in the queue (this is done even if errors occur)

Still looking for any notes on whether the email address format is specified anywhere.

**Comment by mlissner** [comment]
I think, since this is largely done, we can say the architecture is what it is.
