### ISSUE TITLE
Stopwords in phrases break queries

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1635]
At least I think the title is correct. In any case, a query for "freedom information act" works, while one for "freedom of information act" has no results:

Works: https://www.courtlistener.com/?q=cause%3A%22Freedom%20information%20act%22&type=r&order_by=score%20desc
Fails: https://www.courtlistener.com/?q=cause%3A%22Freedom%20of%20information%20act%22&type=r&order_by=score%20desc

Probably somethign to do with stopwords and phrases.

**Comment by johnhawkinson** [comment]
I think the important context is that if you are looking at an existing CL docket such a cause (e.g. https://www.courtlistener.com/docket/16606711/block-leviton-llp-v-federal-trade-commission/), the link that CL itself generates which you get by clicking on the cause field leads you to the broken search containing "of."

**Comment by mlissner** [comment]
Properly handling stopwords is landed for oral arguments, and will be deployed to the other search indexes next. I feel OK closing this.
