### ISSUE TITLE
Compile and triage features that recap.email could do

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1637]
This issue is a placeholder for ideas that recap.email could do. Each idea should be brief summary of the feature, and a proposal as to whether it's something that the recap.email Must do, Should do, Could do or Won't do (for features that are interesting, but not worth the effort, or otherwise problematic).

**Comment by mlissner** [comment]
1. The system **Should** have a catch-all address that anybody can use to anonymously subscribe us to emails. Imagine it being funnel@recap.email, say, and we could encourage people to subscribe their case to "The Funnel". When we get these emails, they will get associated with the existing `recap` account in CourtListener, which has no webhooks and forwards no emails.

2. The system **Won't** allow forwarding rules in the email addresses it supports. For example, you could put `mike-at-free.law@recap.law` as the email in PACER, and weird forwarding rules could be used. This is interesting, and is a design we've discussed but I'm not sure it solves many problems beyond allowing one email address per CL account.

**Comment by mlissner** [comment]
3. The system **Must** send emails from recap.email.

4. The system **Must** have high reliability and extensive automated monitoring.

**Comment by mlissner** [comment]
5. The system **Must** use threads when sending emails so that all emails from a case are threaded together.

**Comment by mlissner** [comment]
6. The system should trim old webhook events so that they don't pile up forever.

**Comment by mlissner** [comment]
Another oddball thought that doesn't fit elsewhere:

7. The system *should* include a field in the webhook content for `deprecation_date`. We can then document for our users that if there's ever a date in there, that means the version of the API is destined for removal on that date. Our webhook receivers can then set up a little alert in their code that can be triggered if a date ever appears.

**Comment by mlissner** [comment]
Let's chat about this soon, Alberto.

**Comment by albertisfu** [comment]
Of course, about 4 and 5, I'll write some ideas in a moment on #1636 that I've been checking how can we handle those.

**Comment by mlissner** [comment]
OK, funnel@recap.email is set up, and the rest of this ticket is moved elsewhere or resolved. Closing!
