### ISSUE TITLE
Update our websites and pages to advertise @recap.email; maybe make a homepage at https://recap.email?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1638]
A few items to include:

 - A link to the RECAP extension homepage
 - The funnel for anonymous donations
 - Why it's important and how it works
 - Info about webhooks and APIs
 - Info about sealed content

**Comment by albertisfu** [comment]
Create a new new issue to update

**Comment by mlissner** [comment]
I think we can just use this one, actually. The main thing is that we have a pretty good help page now, so we need to spend some time integrating @recap.email into other places, like:

1. The recap page on Free.law (https://free.law/recap/)
2. The [recap page on CourtListener](https://www.courtlistener.com/recap/)
3. The [coverage page](https://www.courtlistener.com/coverage/)
4. Maybe somewhere on the free.law homepage?

**Comment by mlissner** [comment]
I just want to make sure it gets enough attention. We could also create a website at https://recap.email, but I'm not sure if it's worth the effort.

**Comment by mlissner** [comment]
I'd really like to get social proof going on this page at some point. Right now I've got:

 - Glapion Law Firm: https://glapionlaw.com/ (@glap on twitter)
 - Sanford Law Firm

A few others are thinking about it, but I need to follow up. I'll post them above as I get them signed up, I think. It might be worth looking at our logs to see if we can see who's using it.

**Comment by albertisfu** [comment]
I've checked this briefly:

- The recap page on Free.law (https://free.law/recap/) and [Free.law](https://free.law) home page: 
  We don't have a mention to recap.email here yet, what information should we add it?

- The [recap page on CourtListener](https://www.courtlistener.com/recap/)
 We don't have either a mention to recap.email here yet, what information should we add it?

- The [coverage page](https://www.courtlistener.com/coverage/):
We do have a mention to recap.email here that says:
  ```
  @recap.email system: People that receive notification emails from PACER can use the [@recap.email system](https://www.courtlistener.com/help/recap/email/) to add documents to the RECAP Archive. Each time they get a notification from PACER, we get it too, and we use it to add content to the RECAP Archive.
  ```
  Should we add additional information here?

- Are we still considering building a page on `https://recap.email/`?

**Social proof:**
Where should we add the firms that are using recap.email? 

About looking at logs to find who's using recap.email, I could look through the files and check recap.email unique addresses from where we have received notifications, might that help to identify more firms?

**Comment by mlissner** [comment]
Thanks for the ideas, Alberto. I'll run with this one and I've taken it off your backlog.

**Comment by mlissner** [comment]
The homepage of free.law is now updated. I'll continue working on this next week too. I also think a post that says, "What's in the RECAP Suite" would be a useful one for people to share, so I'll get that put together too.

**Comment by mlissner** [comment]
Rather than making a website for recap.email, I set up a redirect to go to our help page: https://github.com/freelawproject/courtlistener/issues/2586

**Comment by mlissner** [comment]
I updated free.law/recap. I'm not going to bother with courtlistener.com/recap or with social proof, yet. We'll get there.
