### ISSUE TITLE
Give developer access to replicated DB

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1642]
This will help @flooie  immensely, so he can query the DB for various things. Ideally, we can set this up to protect user info and not allow inserts/updates/etc.

**Comment by flooie** [comment]
🎉

**Comment by mlissner** [comment]
To create the user, log into the replicated DB, and create a user:

    CREATE USER bill NOSUPERUSER;

Give him a password with:

    \password

(I have a utility for generating random passwords; use it.)

Grant select on all tables and sequences past and future:

```sql
courtlistener=> GRANT SELECT ON ALL TABLES IN SCHEMA public TO bill;
GRANT
courtlistener=> ALTER DEFAULT PRIVILEGES
courtlistener->     IN SCHEMA public -- omit this line to make a default across all schemas
courtlistener->     GRANT SELECT
courtlistener-> ON TABLES 
courtlistener-> TO bill;
ALTER DEFAULT PRIVILEGES
courtlistener=> GRANT SELECT, USAGE ON ALL SEQUENCES IN SCHEMA public TO bill;
GRANT
courtlistener=> ALTER DEFAULT PRIVILEGES
courtlistener->     IN SCHEMA public -- omit this line to make a default across all schemas
courtlistener->     GRANT SELECT, USAGE
courtlistener-> ON SEQUENCES 
courtlistener-> TO bill;
ALTER DEFAULT PRIVILEGES
courtlistener=> REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE
courtlistener=> revoke select on auth_user, auth_group from bill;
REVOKE
courtlistener=> revoke select on users_userprofile from bill;
REVOKE
```

Send the credentials using wormhole.

Then open the IP in our VPC.

**Comment by mlissner** [comment]
Some resources I used:

https://stackoverflow.com/a/8247052/64911

https://stackoverflow.com/a/762649/64911
