### ISSUE TITLE
Import Nomination Hearing Proceedings and Related Disclosures 

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1644]
Nomination Disclosures 

We may want to have the option to add nomination disclosures now and in the future.  It was suggested that we should be able to find nomination disclosures of judicial nominees in the senate records, and it is true ... to a point.  Below I've compiled the PDF or the main page on govinfo.gov that holds the judicial nomination hearing information.  

It seems that since at least the late 1980s the hearing records reflected the resumes, letters and financial records of all nominees.  These documents can be found below.  

It encompasses more than just judicial nominees but looks (reasonably) to be all senate nominees. Interestingly the financial records appear to be much more extensive than what is required for yearly filing under federal law providing breakdowns of bank accounts, cash on hand and exact share amount of investments and more.  

I've also been able to find older 1987 to 1999 hearing documents on Google Books as well, and I have downloaded many of the ones I've found so far.  These are all open, and copyright free documents which is nice.  They've also been OCRd by google which is also a nice bonus.  

The rub is that the these documents are just images attached to the documents in newer documents and just scanned pages in older ones.  The documents are also often 1000+ pages long and would require a good amount of time to go thru and find the disclosures we would want.

I personally think we could use a simple ML image classifier to find the start and end of each of these documents and extract them out.  But that's a project for another time.

114th Congress (2015 - 2016)
https://www.govinfo.gov/content/pkg/CHRG-114shrg27131/pdf/CHRG-114shrg27131.pdf

113th Congress (2013 - 2014)
https://www.govinfo.gov/app/details/CHRG-113shrg24286/CHRG-113shrg24286
https://www.govinfo.gov/app/details/CHRG-113shrg24285/CHRG-113shrg24285
https://www.govinfo.gov/app/details/CHRG-113shrg24284/CHRG-113shrg24284
https://www.govinfo.gov/app/details/CHRG-113shrg24007/CHRG-113shrg24007
https://www.govinfo.gov/app/details/CHRG-113shrg24006/CHRG-113shrg24006
https://www.govinfo.gov/app/details/CHRG-113shrg94843/CHRG-113shrg94843
https://www.govinfo.gov/app/details/CHRG-113shrg24005/CHRG-113shrg24005
https://www.govinfo.gov/app/details/CHRG-113shrg93801/CHRG-113shrg93801
https://www.govinfo.gov/app/details/CHRG-113shrg91101/CHRG-113shrg91101

112th Congress (2011 - 2012)
https://www.govinfo.gov/app/details/CHRG-112shrg67905/CHRG-112shrg67905
https://www.govinfo.gov/app/details/CHRG-112shrg75307/CHRG-112shrg75307
https://www.govinfo.gov/app/details/CHRG-112shrg76350/CHRG-112shrg76350
https://www.govinfo.gov/app/details/CHRG-112shrg74979/CHRG-112shrg74979
https://www.govinfo.gov/app/details/CHRG-112shrg74981/CHRG-112shrg74981
https://www.govinfo.gov/app/details/CHRG-112shrg76678/CHRG-112shrg76678
https://www.govinfo.gov/app/details/CHRG-112shrg76710/CHRG-112shrg76710
https://www.govinfo.gov/app/details/CHRG-112shrg76131/CHRG-112shrg76131
https://www.govinfo.gov/app/details/CHRG-112shrg77421/CHRG-112shrg77421
https://www.govinfo.gov/app/details/CHRG-112shrg93596/CHRG-112shrg93596

111th Congress (2009 - 2010)
https://www.govinfo.gov/app/details/CHRG-111shrg61992/CHRG-111shrg61992
https://www.govinfo.gov/app/details/CHRG-111shrg62198/CHRG-111shrg62198
https://www.govinfo.gov/app/details/CHRG-111shrg62345/CHRG-111shrg62345
https://www.govinfo.gov/app/details/CHRG-111shrg63004/CHRG-111shrg63004
https://www.govinfo.gov/app/details/CHRG-111shrg65688/CHRG-111shrg65688
https://www.govinfo.gov/app/details/CHRG-111shrg66693/CHRG-111shrg66693
https://www.govinfo.gov/app/details/CHRG-111shrg66720/CHRG-111shrg66720
https://www.govinfo.gov/app/details/CHRG-111shrg66817/CHRG-111shrg66817

110th Congress (2007 - 2008)
https://www.govinfo.gov/app/details/CHRG-110shrg37658/CHRG-110shrg37658
https://www.govinfo.gov/app/details/CHRG-110shrg47206/CHRG-110shrg47206
https://www.govinfo.gov/app/details/CHRG-110shrg47450/CHRG-110shrg47450
https://www.govinfo.gov/app/details/CHRG-110shrg48894/CHRG-110shrg48894

109th Congress (2005 - 2006)
https://www.govinfo.gov/app/details/CHRG-109shrg27745/CHRG-109shrg27745
https://www.govinfo.gov/app/details/CHRG-109shrg29838/CHRG-109shrg29838
https://www.govinfo.gov/app/details/CHRG-109shrg38736/CHRG-109shrg38736
https://www.govinfo.gov/app/details/CHRG-109shrg30256/CHRG-109shrg30256
https://www.govinfo.gov/app/details/CHRG-109shrg32199/CHRG-109shrg32199
https://www.govinfo.gov/app/details/CHRG-109shrg34698/CHRG-109shrg34698

108th Congress (2003 - 2004)
https://www.govinfo.gov/app/details/CHRG-108shrg89324/CHRG-108shrg89324
https://www.govinfo.gov/app/details/CHRG-108shrg90303/CHRG-108shrg90303
https://www.govinfo.gov/app/details/CHRG-108shrg92548/CHRG-108shrg92548
https://www.govinfo.gov/app/details/CHRG-108shrg92637/CHRG-108shrg92637
https://www.govinfo.gov/app/details/CHRG-108shrg93184/CHRG-108shrg93184
https://www.govinfo.gov/app/details/CHRG-108shrg99696/CHRG-108shrg99696
https://www.govinfo.gov/app/details/CHRG-108shrg95617/CHRG-108shrg95617
https://www.govinfo.gov/app/details/CHRG-108shrg96683/CHRG-108shrg96683

107th Congress (2001 - 2002)
https://www.govinfo.gov/content/pkg/CHRG-107shrg80212/pdf/CHRG-107shrg80212.pdf
https://www.govinfo.gov/content/pkg/CHRG-107shrg80915/pdf/CHRG-107shrg80915.pdf
https://www.govinfo.gov/content/pkg/CHRG-107shrg82503/pdf/CHRG-107shrg82503.pdf
https://www.govinfo.gov/content/pkg/CHRG-107shrg85707/pdf/CHRG-107shrg85707.pdf
https://www.govinfo.gov/content/pkg/CHRG-107shrg86939/pdf/CHRG-107shrg86939.pdf
https://www.govinfo.gov/content/pkg/CHRG-107shrg88116/pdf/CHRG-107shrg88116.pdf

106th Congress (1999 - 2000)
https://www.govinfo.gov/content/pkg/CHRG-106shrg73475/pdf/CHRG-106shrg73475.pdf
https://www.govinfo.gov/content/pkg/CHRG-106shrg73031/pdf/CHRG-106shrg73031.pdf
https://www.govinfo.gov/content/pkg/CHRG-106shrg62430/pdf/CHRG-106shrg62430.pdf
https://www.govinfo.gov/content/pkg/CHRG-106shrg98240/pdf/CHRG-106shrg98240.pdf

Also - just to note, these Senate documents appear to have stopped being shared with the Public.  This appears to have started in 2017 and coincides with Republican control.  Whether it resumes now that there is a Democratic administration is up in the air.

**Comment by mlissner** [comment]
We've got the data for this in a spreadsheet, as completed by volunteers, here: 

https://docs.google.com/spreadsheets/d/1-OI4oMXDjFdilNc0w30_nh5uvIp8KC4CficN2LLMIjY/edit#gid=0

This is ready to go, I think. When it's integrated, we should do a blog post to brag about it and include a thanks to whomever of the volunteers emailed to say they wanted their name included.

**Comment by mlissner** [comment]
I believe this is done. Any straggling tasks?

**Comment by flooie** [comment]
Nope
