### ISSUE TITLE
Determine if webhooks need authentication

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1650]
Over in #1632, @tewen asked if webhooks will need authentication. This is an important question and I'll do some research to try to figure out the answer.

**Comment by mlissner** [comment]
I had to step back a bit to think about why authentication would be needed here but not on normal interactions with websites, and the (perhaps obvious) answer is when you create a webhook, you open yourself up to requests from any IP, and you don't have the benefit of having the domain name system and HTTPS certs in the loop to help you verify things.

So on the one hand, having authentication is really important, if webhooks have the same threat model as POSTs do on the Web. The good news though, is that they do not. 

## Threat Model for Webhooks

The webhooks we have planned currently support the following:

1. Alerts for various things (search, dockets, etc)
2. Updates from new recap content, as when an recap.email receives an email

So what mischief could you come up with if you had access to a webhook? Not much. You could send fake alerts (but then people would get confused and figure out that it was faked). You could send fake emails. These would get integrated into systems, and I suppose you could cause some trouble that way, but it'd take a lot of effort and know-how. 

## Outside Review

I like how Stripe designs their APIs and their treat model is about as high as you can imagine. They have to deal with motivated insider threats, and motivated outsiders. 

So I looked at how they do this:

https://stripe.com/docs/webhooks/signatures

The first thing to notice is that it's optional and it's defaulted to off. We accept their webhook events, but don't verify them, for example. That, in itself, is enough to make me think we don't need this. But as you read on, they do have a clever way of doing timestamped HMAC of their events, so there's something of a standard here.


## Solutions

If we're going to do this, we could copy what stripe does. It'd require a secret key per webhook, and some clever code to add signatures in a header when sending webhook events. It's not *so* hard. 

But that sounds like a lot of work to create and maintain and if stripe isn't doing it by default, I don't think we need to either, especially if nobody is asking for it and we don't anticipate our threat model getting particularly worse. Knowing our clients, I suspect that if we had this feature, nobody would use it.

Therefore, I think obscurity is our best approach. Rather than engineering all of the above into the system, we just tell people:

1. To avoid drive-by nuisances, you might want a long, random URL for your endpoint.
2. If you really want to, you can whitelist our IP, and use a ping of our homepage to keep your whitelist up to date.

**Comment by tewen** [comment]
@mlissner I have no additional strong opinions. Our Webhook will still have an OAS3 spec which is pretty strict about the format. If we receive something really strange, logging should let us know. The stakes here are pretty low, as we would just delete any unwanted documents.

**Comment by mlissner** [comment]
Perfect. Design is set then.
