### ISSUE TITLE
API key based permission set for Recap Email & Lambda Functions

### ISSUE THREAD

**Issue by tewen** [freelawproject/courtlistener#1676]
The recap email Lambda functions will create Email Processing queues utilizing an API key based security. Right now, this is just an empty permission set. We would like this to authenticate against an actual Authorization header (Bearer or not).

**Comment by mlissner** [comment]
We just use a custom Django permission for this elsewhere. Check out `RECAPUploaders` if you haven't already. That makes it pretty easy to do. Did you have a different vision?

**Comment by tewen** [comment]
RCAPUploaders is what I had planned to base it on. This was just going to set the user based on an Authorization header.

**Comment by albertisfu** [comment]
Added endpoint authentication requirement based on recap_upload_access, I just set for POST request, other HTTP methods are not allowed

**Comment by mlissner** [comment]
Anything else here, @albertisfu ?

**Comment by albertisfu** [comment]
Seems is everything here, we should only set the Token as an environment variable in Lambda.
