### ISSUE TITLE
Running test suite with a personal AWS account

### ISSUE THREAD

**Issue by divergentdave** [freelawproject/courtlistener#1679]
I tried running the test suite locally, with my own AWS user's credentials in the settings, but it seems the permissions on the dev-com-courtlistener-storage bucket do not allow me to read from it. This is an issue because the test setup for most unit tests invokes `add_items_to_solr(audio_keys, "audio.Audio", force_commit=True)`, which eventually calls HeadObject on s3://dev-com-courtlistener-storage/test/audio/2.mp3, and fails with HTTP status code 403. I tried poking around with the AWS CLI and the S3 console, and it appears I can list the bucket's contents, but I cannot download this file. Is this intended to be readable by any user? What are the current settings of the file's ACLs, the bucket's policy, and the account-wide "block public access" option?

**Comment by mlissner** [comment]
Our use of S3 is very new. I'm really not sure the best way to handle this. It'd be nice if the tests didn't touch the network, but when I dug into that a bit it felt like mocking out the S3 was big, hard, and sort of defeated the tests. So I think where I landed was that it was best to have some sort of dev credential. Probably the best fix is to include such a credential into the private settings file. Do you have any idea how this is usually done?

**Comment by divergentdave** [comment]
You'll want to have each independent contributor use their own AWS account, so `05_private.example` should stay the same as it is right now. (If you were to include any kind of AWS access key in the file, that would invite opportunistic abuse, and would be an unbounded liability on your AWS bill)

There are ACLs at both the bucket and object levels, and buckets may have an IAM resource-based policy attached. (There is no bucket policy by default) Objects have the ACLs set to private by default when uploading. It looks like the two ways to address this are to change each object's ACL, or to attach a bucket policy to the bucket that grants read access to all objects in the bucket to any account principal. You may also want to enable the "Requester pays" option on the bucket; note that reading from a requester pays bucket requires opting in with a header/option on the client side.

It looks like there are a few mock servers available for S3. The bucket currently weighs in at 45GB, so such an approach would need some curation to be practical. Plus, the easiest way to distribute the data for such a mock server would probably be out of S3, which leads us back to the ACLs and bucket policy.

**Comment by mlissner** [comment]
OK, that's all kind of weird. The bucket itself is public, so I'd expect a HEAD request to work. But that aside, I don't think tests would work even if I tinkered with permissions because the tests also upload stuff. 

We don't get that many contributors that I don't trust. I think the easier thing to do is just give away credentials and monitor my S3 costs (which we do anyway). I'll send you creds via another channel. If you have other ideas, I'm happy to keep this open.

> The bucket currently weighs in at 45GB,

Weird. Not anymore. I had a deletion spree today.

**Comment by flooie** [comment]
This should be resolved too right @mlissner

**Comment by mlissner** [comment]
YEP! We use an in-memory fake S3 storage backend now during test. Woo!
