### ISSUE TITLE
How to Ingest new disclosures

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1687]
We just got another 10gb of disclosures from the AO. 

This issue is meant to document the process, problems and commentary on the process

- [x] Update coverage page with new stats
- [ ] Check for new judges
- [ ] Connect all field with correct judges
- [ ]  Search for any new document types -- unfortunately a thing

**Comment by mlissner** [comment]
The stats are updated.

**Comment by mlissner** [comment]
We should flesh this out, since we just did it for most of the 2019's. Once we have some good and thorough notes here, we can close the issue and just use it as a reference in the future.

**Comment by mlissner** [comment]
Not sure what task this issue represents. Closing.
