### ISSUE TITLE
Person search is too sensitive

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1692]
https://www.courtlistener.com/?q=Macdonald&type=p

https://www.courtlistener.com/?q=MacDonald&type=p

One of these two queries brings back results.  We should certainly make name searching for judges to be less finicky.

**Comment by flooie** [comment]
Unable to search for this judge ... im not sure why.

Thomas B. McCoun III

https://www.courtlistener.com/person/10239/thomas-mccoun-iii/

**Comment by flooie** [comment]
This judge A.F. MacKinnon is listed as Mackinnon in our system.  But the case sensitiveness works both ways.

**Comment by flooie** [comment]
I'm not sure why - but its basically impossible to get to the Chief Judge of Guam's page.  Name - Court etc all fail.

https://www.courtlistener.com/person/10097/this-is-a-judge-name/

**Comment by mlissner** [comment]
I think this is a dup of #824. Or at least partly so.

**Comment by mlissner** [comment]
Some of these just look like they're missing from the search engine (which isn't good, but is easily fixed): https://www.courtlistener.com/?q=id%3A10097&type=p&order_by=name_reverse%20asc

**Comment by mlissner** [comment]
Closing as a dup, as above.
