### ISSUE TITLE
Duplicate Judge in db.

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1693]
https://www.courtlistener.com/person/1810/colleen-kollar-kotelly/?q=Kotelly&type=p&order_by=name_reverse%20asc
https://www.courtlistener.com/person/6781/colleen-kollar-kotelly/?q=Kotelly&type=p&order_by=name_reverse%20asc

Unfortunately, it looks like a duplicate situation.

**Comment by mlissner** [comment]
Bleh. Happens. We can just merge by hand using the admin page, I think, and set up the second one 6781 as an alias to the first.

**Comment by mlissner** [comment]
Fixed.

**Comment by flooie** [comment]
Whoa!  thats ... a super strange one.

**Comment by flooie** [comment]
How did this one even happen.  the information was essentially identical.  and they both were matched to the same financial disclosures.

**Comment by mlissner** [comment]
I'm guessing that you're hitting the alias redirect. If you click the two links above, one will just redirect you to the other at this point. The one that redirects, if you hack the URL to pull it up in the admin, is and was a pretty bare stub. No idea how we got the duplicate though.
