### ISSUE TITLE
Getting error on JSON field in django manage.py

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1698]
@tewen, looks like your latest migration is throwing a deprecation warning. When I run things at the command line, I get this message:

> api.WebhookEvent.content: (fields.W904) django.contrib.postgres.fields.JSONField is deprecated. Support for it (except in historical migrations) will be removed in Django 4.0.
	HINT: Use django.db.models.JSONField instead.

Can you take a look? I'm guessing it should be straighfroward?

**Comment by mlissner** [comment]
I went ahead and fixed it. While it was broken cronjobs were sending the warning to stderr, which meant I got lots of emails. Easy fix, no worries.

**Comment by tewen** [comment]
Thanks @mlissner 

I should've told you. I took the day off to fly my kids home to NYC. The WiFi was out on the plane, so I didn't even get to do 3 hours of bonus work :(

**Comment by tewen** [comment]
Thanks for taking care of it.

**Comment by mlissner** [comment]
No worries!
