### ISSUE TITLE
Deleting account should disable donations

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1699]
Just got a message from somebody that deleted their account, but we were still charging them for donations. Not great. 

We should also update the deletion code to nuke tags.

**Comment by johnhawkinson** [comment]
Money is hard and benefits from strong redundancy.

Arguably there should be an explicit check and clear warning ("You are set
up to donate $5 million a month to FLP. Deleting your account will cancel
this recurring donation beginning next month. Your May 2021 donation has
already been processed.") if applicable.

--jhawk (mobile)

**Comment by mlissner** [comment]
Pint taken, but I think I'd worry more if we were *taking* money instead of *stopping* it and if this had happened more than once so far. I think the intersection of account deletions and donations is vanishingly small (we get few of both).
