### ISSUE TITLE
Huge `case_name_full` in docket with id 1447152

### ISSUE THREAD

**Issue by dduong42** [freelawproject/courtlistener#1718]
```
>>> import requests
>>> s = requests.get("https://www.courtlistener.com/api/rest/v3/dockets/1447152/").json()["case_name_full"]
>>> len(s)
103651
```

Most of it seems to be duplicated data:
```
>>> len(", ".join(set(s.split(", "))))
15491
```

**Comment by flooie** [comment]
Hey @dduong42 - 

That actually looks correct.  Check out the actual case name in the scan of the PDF below.

 [Iowa PDF](https://cite.case.law/pdf/224426/Iowa%20Utilities%20Board%20v.%20Federal%20Communications%20Commission,%20120%20F.3d%20753%20(1997).pdf)

Occasionally you have super long case names and super long dockets - usually when cases are consolidated from thousands of independent cases into class actions.

**Comment by mlissner** [comment]
Yes, I think the approach to take on these is that `case_name_full` is just that — a wildly long field that sometimes contains extremely long case names — and `case_name` is a better field that just contains pretty regular case names. `case_name_short` is usually just one word long, and tries to be an automated approach to making names suitable for pincites. A simple example would be:

`Roe v. Wade`

Which would have a short name of:

`Roe`

There's more about this here (including a recommendation for which field to actually *use*): https://www.courtlistener.com/api/rest-info/#field-details
