### ISSUE TITLE
Continue speeding up our tests

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1720]
I have made a lot of progress speeding up our tests lately, but reached a point where I didn't have time to continue. Here are my remaining todos. If somebody has time to do some open source contributions, this would be great stuff (all of this from @adamchainz's book, "Speed Up Your Django Tests"): 

```
Remaining todos: 
 - 4.5 Use an In-Memory File Storage Backend
 - 4.6.2 Fake Redis Caching
 - We need to break up big test classes: 6.6 Split Up Large Test Groups (can't
   do it on the plane because we can't profile them).
 - Look into moving to FactoryBoy, I guess, and removing fixtures.
 - Start using setupTestData()
 - Try blocking all network access by using requests-mock
```

Some of these should be pretty easy, while others will be a bit of a pain, but they should all make our test-world a bit faster and reliable.

**Comment by mlissner** [comment]
Oh, finally, as part of moving away from fixtures, we should also stop doing migrations during tests at least on CI. I tried doing this today, but it doesn't work because a lot of tests rely on data that comes from our data migrations. We could fix that and then disable migrations to save a bit more time.

**Comment by mlissner** [comment]
(I should be able to share the relevant bits of the book for these tasks as well, so they all make sense. It's a good book and explains these pretty clearly.)

**Comment by adamchainz** [comment]
Great to hear the book is helping!

**Comment by hut8** [comment]
On projects I've worked on before, there is a way to run the tests without really hitting any API endpoints. botocore has something built-in that can stub out requests to avoid hitting endpoints and thus spending time/money.
https://adamj.eu/tech/2019/04/22/testing-boto3-with-pytest-fixtures/
https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html
Is this something that this project would like? There could be a switch to "really test" API endpoints (i.e., an integration test) but, by default, just test that the expected requests are sent and then test that the expected response yields the expected result. That way, I could run the unit tests locally without actually setting up AWS keys, and the tests would run faster in most cases.

Is there a better place to ask these kinds of questions, @mlissner ?
