### ISSUE TITLE
Release the ci/lib/celery_utils.py module into a separated python package/repository

### ISSUE THREAD

**Issue by luzfcb** [freelawproject/courtlistener#1724]
Hello, I discovered this project from this comment https://stackoverflow.com/questions/29854102/celery-rate-limit-on-tasks-with-the-same-parameters/66161773#comment120428734_66161773 .

I have the same problem, and [its implementation makes sense](https://github.com/freelawproject/courtlistener/blob/34c340ef2415fd32921cd7e8dd3b8b118e2ea090/cl/lib/celery_utils.py#L123-L321), however, due to the license of this project, I cannot use it or contribute to it.

Since the global celery global worker's rate limit issue is still an open issue and keep celery tools is not the final objective of this project, would it make sense to extract the current implementation (all or almost all code of ci/lib/celery_utils.py) into a separated python package with a most permissive license (non-viral license) and so increase the number of people using, finding and fixing bugs?

If this makes sense to you, I would be available to do all the necessary work to create and distribute the python package.
You would only need to create the repository, import the code from "celery_utils.py" and re-license it to a non-viral license. As for me, I could implement everything else necessary to package the code, distribute and replace the current module of this project with the implementation in the new library.

**Comment by mlissner** [comment]
Yeah, I was afraid this would be useful enough that we'd want to spin it out. I'd be happy to share the code as you describe, in a fresh repo, as an installable Python package, and we have a nice template for making that happen: 

https://github.com/freelawproject/new-project-template/

I could make a repo called freelawproject/celery-utils, and you could file PRs on it. 

I'm very swamped right now though, so two other thoughts:

1. When we've spun out our work in the past, we haven't had the resources to actually pull in the new python packages that resulted, and so CourtListener continued using the baked in code while the forked code went its own way. Do you think you'd be able to do a PR for CourtListener to incorporate the new python package once it was ready? 

2. Can you say more about the product you want to use this in? I admit my willingness/ability to work on this could be affected by who and what I'm helping.

Thanks for reaching out. Despite my concerns above, I do think it'd be good to pull this stuff out into a fresh package. I'm just swamped and trying to guard my time a bit. 

(We just did a similar project like this to create freelawproject/eyecite, and it took a lot of time. In the end, we have a cool package, but our users probably have no clue of all the work that happened on it.)

**Comment by luzfcb** [comment]
@mlissner 

1 - When the new library is completed done, I can create the PR to replace the current code of this project.
2 - Is plant-based food online store.

> I'm just swamped and trying to guard my time a bit.

As a maintainer of a few open-source softwares, I understand completely. That's why I offered to be able to do (almost) all the work until at least the first release of the new library because I know that free time is a very precious asset.

**Comment by luzfcb** [comment]
@mlissner Can you create an empty `celery-utils` repository and add me as a contributor with write permission?

**Comment by mlissner** [comment]
Sounds great. If you can fork it and do PRs, that'll be easier than adding you as a contributor. That OK?

The repo is here: https://github.com/freelawproject/celery-utils
