### ISSUE TITLE
Citation Reporter - Volume pages should be sorted by page number

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1732]
See: [137 So-2d *](https://www.courtlistener.com/c/So.%202d/137/)

The reporters don't publish opinions chronologically so when we sort by date filed - the opinions are out of page order.  This should be adjusted.

**Comment by mlissner** [comment]
Wasn't this an issue b/c they're in the DB as strings, so if we sort by those we'll get:

```
1
10
11
12
13
14
15
16
17
18
19
2
...
```

**Comment by flooie** [comment]
I think I have a solution.  Adding an annotation and sorting that annotated field naturally gives me what I am asking.  

```
cases_in_volume = OpinionCluster.objects.filter(
        citations__reporter=reporter, citations__volume=volume
    ).annotate(
        cite_page=(F('citations__page'))
    ).order_by('cite_page')
    cases_in_volume = alphanumeric_sort(cases_in_volume, 'cite_page')
```

<img width="552" alt="Screen Shot 2021-08-16 at 11 59 22 AM" src="https://user-images.githubusercontent.com/6464529/129593614-be48c4c9-dae2-47d3-a7bf-c285526b798c.png">

**Comment by mlissner** [comment]
That is pretty interesting. Nice one.

**Comment by flooie** [comment]
This is resolved!
