### ISSUE TITLE
Florida Supplement Courts

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1733]
To add the first Florida Supplement case law we will need to add the following courts no in our system.

        # Bay County Circuit Court
        # Hendry County Circuit Court
        # Duval County Circuit Court
        # Palm Beach County Circuit Court
        # Palm Beach County Criminal Court of Record
        # Walton County Circuit Court
        # Broward County Small Claims Court
        # Flagler County Circuit Court
        # Dade County Court
        # Pinellas County Court
        # Florida Railroad & Public Utilities Commission
        # Orange County Judge's Court
        # Nassau County Circuit Court
        # Lee County Judge's Court
        # Escambia County Circuit Court
        # Dade County Metropolitan Court
        # Alachua County Circuit Court
        # Volusia County Judge's Court
        # Suwannee County Judge's Court
        # Okeechobee County Circuit Court
        # Indian River County Circuit Court
        # Suwanee County Circuit Court
        # Palm Beach County Small Claims Court
        # Florida Public Utilities Commission
        # Dade County Small Claims Court
        # Dade County Judges' Court
        # Lake County Judge's Court
        # Osceola County Circuit Court
        # Duval County Civil Court of Record
        # Columbia County Circuit Court
        # Florida Public Service Commission
        # Broward County Court
        # Sumter County Circuit Court
        # Orange County Circuit Court
        # Bradford County Circuit Court
        # Calhoun County Circuit Court
        # Highlands County Circuit Court
        # Pinellas County Civil Court of Record
        # De Soto County Circuit Court
        # Manatee County Circuit Court
        # Hillsborough County Court
        # Miami Beach Municipal Court
        # Pinellas County Civil and Criminal Court of Record
        # St. Lucie County Small Claims Court
        # Industrial Commission
        # Charlotte County Judge's Court
        # Pasco County Circuit Court
        # Dade County Judge's Court
        # Hamilton County Judges' Court
        # Escambia County Court of Record
        # Pinellas County Circuit Court
        # Santa Rosa County Circuit Court
        # Lee County Circuit Court
        # Levy County Circuit Court
        # Palm Beach County Court
        # Gadsden County Circuit Court
        # Duval County Ciruit Court
        # Broward County Circuit Court
        # Leon County Circuit Court
        # Orange County Court
        # Collier County Circuit Court
        # Broward County Judges' Court
        # Pinellas County Judge's Court
        # Polk County Circuit Court
        # Surfside Municipal Court
        # Railroad & Public Utilities Commission
        # Monroe County Court
        # Hamilton County Circuit Court
        # Palm Beach County Juvenile and Domestic Relations Court
        # Dade County Circuit Court
        # Martin County Circuit Court
        # Munroe County Circuit Court
        # Sarasota County Circuit Court
        # St. Lucie County Circuit Court
        # Brevard County Court of Record
        # Marion County Circuit Court
        # Monroe County Circuit Court
        # Volusia County Circuit Court
        # Monroe County Judge Court
        # Brevard County Court
        # Florida Industrial Commission
        # Florida County Court
        # Dade County Civil Court
        # Polk County Court
        # Charlotte County Circuit Court
        # Hillsborough County Circuit Court
        # Palm Beach County Judge’s Court
        # Florida Circuit Court
        # Miami Municipal Court
        # Dade County Civil Court of Record
        # Lake County Circuit Court
        # Florida Real Estate Commission
        # Seminole County Circuit Court
        # Duval County Judge's Court
        # Union County Circuit Court
        # Okaloosa County Circuit Court
        # Broward County Court Record
        # Glades County Circuit Court
        # Clay County Circuit Court
        # Sarasota County Judge's Court
        # Brevard County Circuit Court
        # Citrus County Circuit Court

This doesn't include the second Florida Supplement.  

So - most are entry courts but there are at least some commissions that I've never heard of.

**Comment by mlissner** [comment]
Jeez. Please make it so!

**Comment by flooie** [comment]
This - was closed prematurely.

This list represented only the new courts from the Fla. Supp.

Here is an updated list of the remaining Florida courts - not yet found in Courts-DB

Dade County Property Appraisal Adjustment Board
Dade County Property Appraisal Board
Florida Department of Health and Rehabilitative Services
Hardee County Circuit Court *(in courts-db. just needs regex)
Jacksonville Civil Service Board
State of Florida Department of Environmental Regulation
State of Florida Department of Revenue
State of Florida Division of Administrative Hearings
Superior Court, S. D. Florida

**Comment by flooie** [comment]
1. **Superior Court, S. D. Florida** -- (1) is not in the Florida reporters - but in F. Cas + an Admiralty reporter from 1840 (pre-statehood). [See case here](https://cite.case.law/f-cas/8/644/11977329/).
1. **Jacksonville Civil Service Board** - (1) is a board hearing cases on police misconduct.
1. **Dade County Property Appraisal (Adjustment) Board** (6 cases in total) in F. Supp. 2d
1. **The Florida department/divisons** (198) F. Supp. 2d cases

**Comment by flooie** [comment]
As expected.- we are missing one case from one pre-statehood court in Washington

```In re Preston. 1871
19 F. Cas. 1289, 5 N. B. R. (1871) 293
· Washington District Court
· Washington```
