### ISSUE TITLE
M1 Mac issues building docker images for linux

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1760]
We think we've had a downtime today because the docker images were built on Apple Silicon.  

According to the internet [see this blog post](https://blog.jaimyn.dev/how-to-build-multi-architecture-docker-images-on-an-m1-mac/#tldr;)

We should be able to 

1. Set docker to experimental.  Although this may be outdated now.
2. Set multiple docker platforms with `docker buildx create --use`
3. Run the command `docker buildx build --platform linux/amd64,linux/arm64`

**Comment by mlissner** [comment]
Some info here: https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images

I mostly read this page, but still don't understand how it works when you build for multiple architectures. Does it make multiple images that have to be uploaded? One image that somehow supports multiple architectures? If the latter, I imagine it'd be annoying, since it'd mean a bigger image for everybody. If the former, it'd be annoying since it'd be more for you to upload each time you push. Hm. Curious and weird area.

**Comment by flooie** [comment]
I've got a riddle for you @mlissner 

```
flooie/m1-test                          amd-arm  ...   2 hours ago     1.55GB
freelawproject/courtlistener-django     latest   ...   4 days ago      1.64GB
```

Other than the multi-platform image being smaller than the current latest, I think this should work out. 

I've successfully tested the amd-arm version on both a window surface and an M1 Mac mini.

**Comment by mlissner** [comment]
Is it a multi-platform one that's smaller or is it just a amd-arm one that doesn't support x86?

**Comment by flooie** [comment]
@mlissner I may be wrong about this - but I was under the assumption that x86 and amd64 were interchangeable.  

So to answer your question - I think the amd-arm tag is both x86 and apple m1

**Comment by flooie** [comment]
do you think you can inherit a multi-platform image (ie. courtlistener-django) into the task server without also building it as Multiplatform?

**Comment by mlissner** [comment]
> @mlissner I may be wrong about this - but I was under the assumption that x86 and amd64 were interchangeable.

Yeah, that makes sense, I think. 

> do you think you can inherit a multi-platform image (ie. courtlistener-django) into the task server without also building it as Multiplatform?

I have no idea. Only one way to find out...

**Comment by flooie** [comment]
I think I do have an answer at least to one more puzzle.

![image](https://user-images.githubusercontent.com/6464529/132593873-92e86133-a1cc-44ae-b0bc-056c53b24d3e.png)

It looks like it generates different images of different sizes for each individual platform identified in the command. Which seems obvious after the fact.
