### ISSUE TITLE
An ongoing list of failures in the Harvard Import

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1763]
This thread is meant to help keep track of failures in the Harvard import.  

This first thread is going to be a list a couple dozen failed citation parsers. Unfortunately this first group does not have an associated xml path or cluster.  This will be fixed in a future update to the Harvard importer.

**Comment by flooie** [comment]
As you can tell there are reasons some of these failed for the most part

- Judgment, of ouster awarded.
- 135 So, 839
- 239 La
- 239 La
- 195 La 1
- 195 La 1
- No. 5D14-2134.
- No. 5D14-2134.
- No. 5D14-2134.
- No. 5D14-2134.
- Within the record provided on appeal, which does not contain a transcript there is nothing to sufficiently indicate that the judgment of the trial court was in error. We assume that evidence was presented supporting the trial judge’s finding of unconscionability, and we assume the plaintiff had the opportunity to present evidence as required by
- Within the record provided on appeal, which does not contain a transcript there is nothing to sufficiently indicate that the judgment of the trial court was in error. We assume that evidence was presented supporting the trial judge’s finding of unconscionability, and we assume the plaintiff had the opportunity to present evidence as required by
- 274
- 260. S. W., 565
- 260. S. W., 1023
- — S. W., —
- 17 S, W., 2d Series, 766
- 70 S. Wv 2d Series, 394
- 113 S. W., Second Series, 515
- 180 S. W., 2d Seriees, 429
- 199. S. W., 2d Series, 486
- 215 S. W., 2d series, 862
- 289 S.W. Series 553
- 295 S.W. Series 408
- 300 S.W. Second Series 601
- 348 S. W. 2d Series. 17
- 60 S .W. (2d) 208

**Comment by flooie** [comment]
I have a more substantive question - that on stepping back for a while on this project makes me think we made a mistake.

https://cite.case.law/me/8/106/

This is a random opinion from Maine in 1831.  We correctly (according to our code) skipped the import.  Because there is no opinion... technically.  That being said it was the 1830s and the reporter summarized the opinion.  I assume there is some substantive precedent and value to it.  But Idk.  

Is it useful.  probably not.  But should we continue to skip these or should be import them in.  They shouldn't be much of an issue for duplications.

@mlissner

**Comment by mlissner** [comment]
Yeah, I guess if there's a summary and a citation, we should import it. Better to include these. I forget why we didn't want them before. Maybe we have a ticket discussing this?

**Comment by flooie** [comment]
This is no longer necessary and should probably more specific in the future, so im closing this.  

Also - we've completed the first import and are moving onto the next stage of importing.
