### ISSUE TITLE
Create new account in main server for @flooie

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1767]
So, OK, this isn't that hard, but also, our security is pretty tight, so it is kind of difficult. The main process is:

```bash
sudo su
adduser wpalin
usermod -aG sudo wpalin
```

That gets the user created with a password, but we have 2FA turned on, so if you try to log in with that account remotely, it'll fail and the server will block your IP address. As a matter of fact, my laptop is currently connected via my phone's hotspot, so ask me how this is going....

**Comment by mlissner** [comment]
I believe this is the fix for the IP address problem (from [here]()):

```
sudo iptables -D INPUT -s 135.180.50.146 -j DROP
```

Alas, when I ran it, it said: `iptables: Bad rule (does a matching rule exist in that chain?).`, which I think is because my IP was only temporarily blocked. It seems fine now, so onwards we go with setting up the account.

**Comment by mlissner** [comment]
Using the tutorial here, I set up 2FA auth for the account:

https://www.howtogeek.com/121650/how-to-secure-ssh-with-google-authenticators-two-factor-authentication/

It's as easy as:

```
sudo su - wpalin
google-authenticator
```

Then you share the password and QR code, and the rest is history.

**Comment by flooie** [comment]
💯
