### ISSUE TITLE
Volume A.3d appears incomplete

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1775]
https://cite.case.law/a3d/

I'm not sure we have the complete Atlantic reporter from Harvard.  

Volumes 176: 213 don't appear to be in IA.

**Comment by mlissner** [comment]
Shoot. We could try to get our OSX scraper going again. I wonder if it's easier to just use your and my creds to slowly crank something out like this. That's ~40 volumes, call it 100 cases each, should fit in our 1,000/day threshold pretty quickly?

**Comment by flooie** [comment]
I'm more curious about how this happened?  Where are other gaps?  And are these added after the fact?

**Comment by mlissner** [comment]
yeah, I don't know. There was some sloppiness around the very end of the downloader's progress, IIRC. It might be worth pulling their list of all cases and seeing which ones we lack.

**Comment by flooie** [comment]
I was going to try to compare against volumes.  but I can try to do cases instead.

**Comment by mlissner** [comment]
Either way, I suppose. Cases would be more accurate, but harder, of course.

**Comment by flooie** [comment]
I may just do a total cases comparison to start.

**Comment by flooie** [comment]
They added more volumes since, and we have collected them, but not uploaded them to IA yet.
