### ISSUE TITLE
Disclosure for Dorina Ramos is filed under Edgardo Ramos

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1782]
Unclear how this happened. Anyway, here's the errant doc:

https://storage.courtlistener.com/us/federal/judicial/financial-disclosures/2655/edgardo-ramos-disclosure.2011.pdf

You can see from the 2655 that it's in the wrong place.

Dorina Ramos appears to be a magistrate judge that's not in our system, so fixing this probably means:

1. Remove it from Edgardo
2. Add Dorina
3. Put it under her name

Some small amount of digging into how this happened might be useful. 

Also: Where are the rest of Dorina's disclosures?? She appears to be active:

https://www.txs.uscourts.gov/content/united-states-magistrate-judge-dorina-ramos

**Comment by flooie** [comment]
https://github.com/freelawproject/courtlistener/issues/1677  Should be here.

**Comment by flooie** [comment]
The disclosure has been shifted to the correct judge and is no longer with Edgardo
