### ISSUE TITLE
DEVELOPING.md misses Chokidar installation (why is Chokidar not a dependency?)

### ISSUE THREAD

**Issue by hut8** [freelawproject/courtlistener#1784]
Hey there. From a brand new installation of Ubuntu 20.04, I'm following along with the development instructions in DEVELOPING.md. I installed nvm and through that installed the stable version of node today. (v16.11.0). That comes with npm 8.0.0. 

In the instructions, I've gotten up to `npm install` and when I execute `npm run dev`, I get a message that chokidar isn't installed. Nowhere does it say to install chokidar. I would just add it to the dependencies, but I'm confused as to why it isn't there already. Once I install chokidar with `npm install chokidar`, it runs fine. Why isn't `chokidar` part of the dependencies already?

```
/home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/chokidar.js:17
throw new Error(
^

Error: No version of chokidar is available. Tried chokidar@2 and chokidar@3.
You could try to manually install any chokidar version.
chokidar@3: Error: Cannot find module 'chokidar'
Require stack:
- /home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/chokidar.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/watcherManager.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/watchpack.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/webpack/lib/webpack.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/webpack-dev-server/bin/webpack-dev-server.js
chokidar@2: Error: Cannot find module 'watchpack-chokidar2'
Require stack:
- /home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/chokidar.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/DirectoryWatcher.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/watcherManager.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/watchpack.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/webpack/lib/webpack.js
- /home/liam/freelawproject/courtlistener/cl/node_modules/webpack-dev-server/bin/webpack-dev-server.js

    at Object.<anonymous> (/home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/chokidar.js:17:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/liam/freelawproject/courtlistener/cl/node_modules/watchpack/lib/DirectoryWatcher.js:9:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by mlissner** [comment]
Never heard of that dependency. @flooie, is that part of the debounce or
something?

**Comment by flooie** [comment]
Stumps me. I also did a whats that when I saw this issue.  One new install looks pretty straightforward.

**Comment by hut8** [comment]
I also tried `npm install --include=dev` -- `chokidar` is actually listed in `package-lock.json` but it's listed as `dev` and `optional`.

**Comment by hut8** [comment]
Oh, here is a fun fact. If you run `npm update --legacy-peer-deps`, then it will work. So perhaps I could just check in a new `package-lock.json`. What versions of NPM/node are ya'll running? I don't know why the package installation isn't deterministic for us.

```
❯ npm update --legacy-peer-deps                                 4s liam@hut8 23:12:45
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.                                                                                                                       npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
                                                                                                                        added 181 packages, removed 73 packages, changed 306 packages, and audited 1092 packages in 49s

92 packages are looking for funding
  run `npm fund` for details

30 vulnerabilities (8 moderate, 22 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

**Comment by mlissner** [comment]
Nice, well, this is a bit of a mess. We haven't standardized on a version of npm because, well, naively I guess we assumed that version locks depended more on the dang dependencies and less on the installer. How naive. 

I guess we should standardize on a version of npm, which I suppose probably means we should all be using nvm. Would you be interested in bringing that into our processes by figuring out how that would work and updating the readme? (I can broadcast to the team to make sure everybody updates the way they do things if you figure out and document how to do it.)

> Will tests actually make sure this all works?

Atm, we haven't written tests for our react-related stuff because it's very new. There's only one feature using it, and we haven't committed to a test framework. They seem to change a lot, and we are so new to this it seemed to make more sense to hang back and add tests once checking things by hand became too annoying. Sooooo....if we want to update a bunch of dependencies, I think we just need to make sure that the tagging feature works properly afterwards. 

There's one other consideration here, which is that pull #1780 has a bunch of dependencies that it adds/upgrades, so I know we're going to have merge conflicts if we don't order these properly. I'm sure git has some answer to this, but I'm not sure what it is aside from, "Redo one branch or the other once the first one is landed." I suppose you could branch off of that branch and we'll merge it and then this?

**Comment by hut8** [comment]
Cool. Things seem to work now, although Node 17 gives a different error (having to do with the OpenSSL provider, but I've ran into that on several projects on Linux). Maybe it should be documented that Node 16 should be used, or maybe a .nvmrc or something like this: https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json

**Comment by mlissner** [comment]
Thanks for that. Yeah, I agree, setting the node version would be a good thing.
