### ISSUE TITLE
Harvard Import Cleanup generating lots of edge case issues

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1795]
Starting with citation edge cases.

Florida, has 49 failing citation (edge cases) that come in ... 40 different flavors.  

```
1        239 La
2        No. 5D14-2134.
3        195 La 1
4        746 So. 2d.
5        779 So. 2d15.
6        Within the record provided on appeal, which does not contain a transcript there is nothing to sufficiently indicate that the judgment of the trial court was in error. We assume that evidence was presented supporting the trial judge’s finding of unconscionability, and we assume the plaintiff had the opportunity to present evidence as required by
7        95 Fla. 736a.
8        Judgment, of ouster awarded.
9        135 So, 839
10       146- So. 98
11       146 S. 660
12       146 S. 900
13       147 SO. 463
14       147 S. 254
15       149.So. 331
16       149 So, 574
17       149. So. 573
18       149 S. 582
19       ISO So. 133
20       152. So. 429
21       154 So, 206
22       1S4 So. 833
23       159 S. 46
24       163 S. 486
25       183 So, 15
26       180 Sol 625
27       Division A
28       1 So. (2nd Series) 183
29       8 So. (2nd)) 279
30       9. So. (2nd) 170
31       10 So. (2nd)) 431
32       17'So. (2nd) 78
33       17 So .(2nd) 125
34       20. So. (2nd) 484
35       20 So. (2nd 695
36       2i So. (2nd) 356
37       21- So. (2nd). 211
38       22 So, (2nd) 154
39       24th So. (2nd) 51
40       26 So. So. (2nd) 667
41       27 (2nd) 609
42       28 S. (2nd) 836
43       30 (2nd) 100
44       30 (2nd) 101
45       30 (2nd) 100
46       32 (So. 2nd) 593
47       32 So. 2nd) 738
48       37 St. (2nd) 538
49       37 S. (2nd) 369
```

I say the issues here are 

1. Poor OCR: see Nos. 19, 37, 26, 36.
2. Incomplete data: No. 1, 41, 43 - 45, 48.
3. Typos that could be fixed in eye cite but would make it worse: Nos. 38, 25 and lots of others.
4. Wrong data: Nos 6, 8, 27.

I'm not sure the best approach to these.  In some cases, I think tweaking the json we download could be the right approach and then re-importing.  In this case - the original stays on IA and our file can always reference back.  

For Typos, lack of spacing, errant hyphens commas and periods - these could be tackled in eye cite and reporters db - but...It bloats those up.  And in other cases - we could infer the correct volume Ala 47-49 but thats not really reasonable long term... or maybe it is. 

For incomplete data, we may just have to check the PDFs, same for OCR that isn't obvious.  

And for the ones with wrong fields, it seems like fixing the json is the only approach.

@mlissner Thoughts on this would be appreciated.

**Comment by mlissner** [comment]
And so the mighty issues close! I guess we should dig around for anything mentioning Harvard and see what's lingering — or perhaps you're doing just that.
