### ISSUE TITLE
Add comment for the Illinois Courts' about withdrawal of opinions

### ISSUE THREAD

**Issue by satsuki-chan** [freelawproject/courtlistener#1800]
The **Illinois Supreme Court** and **Illinois Appellate Court** give a party 21 days to request a rehering, which, if allowed, will result in the nullification of the opinion or ruling. The courts' system is not inmediatly updated after this nullification takes place.

A warning must be added to inform users of this practice and to advice to check the Illinois Courts' system for the most updated version of an opinion or a ruling, or if the document was withdrawn.

> A Caution on Court Opinions
> 
> Some opinions on this system represent only the respective court's initial slip opinion. Under Supreme Court Rule 367, a party has 21 days after the filing of an opinion to request a rehearing, which, if allowed, will act to nullify the previously filed opinion. Also, opinions are subject to modification, correction, or withdrawal at any time prior to issuance of the mandate by the clerk of the court. Therefore, because the slip opinions on this system are being made available prior to the court's final action in these matters, they cannot and should not be considered the final decisions of the court. However, following final action by the court, the slip opinion will be replaced on this system with the final, Official Reports version of the opinion and an Official Reports link will replace the "not released" (NRel) indicator.

https://www.illinoiscourts.gov/top-level-opinions/#opinionCaution

Related issue from Juriscraper:
https://github.com/freelawproject/juriscraper/issues/405

**Comment by mlissner** [comment]
@flooie can you chime in with some good language to add, please?

**Comment by flooie** [comment]
A Note on Illinois Opinions: 

Illinois opinions may be withdrawn after publication. Although this is rarely done, we recommend reviewing the court website if you need to verify that this opinion has not been withdrawn.

@mlissner @satsuki-chan How about something like this?

**Comment by satsuki-chan** [comment]
I like it. It's short and to the point.
Should I add a link to the note from the Illinois Court for more details? Like:

> For more information see:
> https://www.illinoiscourts.gov/top-level-opinions/#opinionCaution

@mlissner

**Comment by mlissner** [comment]
Yep. That all seems good to me. 

I think a bootstrap alert box should be good?

**Comment by satsuki-chan** [comment]
Comment for **Illinois Supreme Court**:
![Screenshot from 2021-11-04 10-18-18](https://user-images.githubusercontent.com/8507838/140386394-41c5b7f0-8062-4ad5-94f3-3bb7428cf67a.png)

Comment for **Illinois Appellate Court**:
![Screenshot from 2021-11-04 10-18-06](https://user-images.githubusercontent.com/8507838/140386398-5f8f8840-94d9-4ead-9e5b-73ae8551d444.png)

Opinions from other courts:
![Screenshot from 2021-11-04 10-17-49](https://user-images.githubusercontent.com/8507838/140386402-dd987f35-97b9-45ca-b46d-4044fb7fa0c9.png)
