### ISSUE TITLE
Whitelist mojeekbot

### ISSUE THREAD

**Issue by ricardoscotia** [freelawproject/courtlistener#1807]
Mojeek respects robots.txt and rate limiting crawling of sites, it is a general purpose search engine that has been in service since 2004.

More details about us here:
https://blog.mojeek.com/2021/03/to-track-or-not-to-track.html
https://blog.mojeek.com/2021/05/no-tracking-search-how-does-it-work.html

and details of our Bot here: https://www.mojeek.com/bot.html

**Comment by mlissner** [comment]
Thank you.
