### ISSUE TITLE
New Judges 2019 Edition 

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1809]
In reviewing the 2019 (and 2018 PDFs) from the AO, I think I have identified 75 new judges.

This is my tentative list of missing judges. - of which I have 75 new ones to create.

2019
--------------------------------------------------------------------------------
| New  | First | middle | Last | Suffix  | Filename  | PDF | 
| ------------- | ------------- |--|---|--|---|--|
x|    Lisa      |    A.    |       Jensen      |        |         Jensen-L. M3. 07. ILN _SR_19.pdf        |  √  |
x|    Allen     |    C.    |       Winsor      |        |        Winsor-AC. J3. 11. FLM _SR_19.pdf        |  √  |
x|    David     |    S.    |      Morales      |        |        Morales-DS J3. 05. TXS _SR_19.pdf        |  √  |
x|  Christine   |    D.    |       Little      |        |    Little-CD. M. 10. OKN_Ini_ Resp_SR_19.pdf    |  √  |
x|   Michael    |    H.    |        Park       |        |          Park-MH J3. 02. -- _SR_19.pdf          |  √  |
x|    Sally     |    J.    |       Berens      |        |     Berens-SJ. M. 06. MIW_Resp_SPE_SR_19.pdf    |  √  |
x|   Thomas     |    S.    |       Kleeh       |        |         Kleeh-TS. J3. 04. WVN _SR_19.pdf        |  √  |
x|  Stephanie   |    L.    |       Haines      |        |        Haines-SL. J3. 03. PAW _SR_19.pdf        |  √  |
x|  Patricia    |    M.    |       Mayer       |        |        Mayer-PM B. 03. PAE Ini_SR_19.pdf        |  √  |
x|    Susan     |    J.    |     Hightower     |        |       Hightower-SJ. M. 05. TXW _SR_19.pdf       |  √  |
x|    James     |    D.    |        Cain       |  Jr,   |        Cain,Jr-JD. J3. 05. LAW _SR_19.pdf       |  √  |
x|     Zia      |    M.    |      Faruqui      |        |       Faruqui-ZM. M. DC. DC _Ini_SR_19.pdf      |  √  |
x|   Andrew     |    L.    |      Brasher      |        |        Brasher-AL. J3. 11. ALM _SR_19.pdf       |  √  |
x|   Stephen    |    D.    |      Wheelis      |        |         Wheelis-SD B. 05. LAW _SR_19.pdf        |  √  |
x|    Sean      |    D.    |       Jordan      |        |        Jordan-SD. J3. 05. TXE. SR_19.pdf        |  √  |
x| Christopher  |    C.    |        Bly        |        |          Bly-CC. M. 11. GAN _SR_19.pdf          |  √  |
x|   Allison    |    J.    |      Rushing      |        |         Rushing-AJ J3. 04. SIA_SR_19.pdf        |  √  |
x|   William    |    J.    |      Nardini      |        |         Nardini-WJ J3. 02. -- _SR_19.pdf        |  √  |
x|    Neomi     |    J.    |        Rao        |        |         Rao-NJ. J3. DC. --SPE_SR_19.pdf         |  √  |
x|   Stephen    |    C.    |       Dries       |        |          Dries-SC M. 07. WIE _SR_19.pdf         |  √  |
x|  Nicholas    |    P.    |       Mizell      |        |       Mizell-NP. M. 11. FLM Resp_SR_19.pdf      |  √  |
x|   Andrew     |    E.    |       Krause      |        |      Krause-AE M. 02. NYS_SPE_SR_INI_19.pdf     |  √  |
x|   Richard    |    A.    |      Hertling     |        |        Hertling-RA. J1. --. CC _SR_19.pdf       |  √  |
x|  Patricia    |    A.    |      Donahue      |        |     Donahue-PA M. 09. CAC SIA_Ini_SR_19.pdf     |  √  |
x|    JOHN      |    F.    |  KLEIN-ROBBENHAAR |        |   Klein-Robbenhaar-JF. M. 10. NM SIA_SR_19.pdf  |  √  |
x|    Carla     |    L.    |      Baldwin      |        |         Baldwin-CL. M. 09. NV_SR_19.pdf         |  √  |
x|   Jeffrey    |    P.    |       Norman      |        |         Norman-JP. B. 05. LAW _SR_19.pdf        |  √  |
x|    Jared     |    C.    |      Bennett      |        |     Bennett-JC. M. 10.0UT Ini_Resp_SR_19.pdf    |  √  |
x|     Jon      |    A.    |        York       |        |        York-JA M. 06. TNW. Resp_SR_19.pdf       |  √  |
x|    Mark      |    T.    |      Pittman      |        |          Pittman-MT. J3. 05. _SR_19.pdf         |  √  |
x|    Wendy     |    W.    |       Berger      |        |      Berger-WW. J3. 11. FLM Resp_SR_19.pdf      |  √  |
x|    John      |    S.    |       Hodge       |        |         Hodge-JS. B. 05. LAW _SR_19.pdf         |  √  |
x|    JAMES     |    R.    |       SICKEL      |        |       Sickel-JR  MP.07.WIE Resp_SR_19.pdf       |  √  |
x|   Michael    |    J.    |      Bordallo     |        |         Bordallo-MJ. M. 09. GU_SR_19.pdf        |  √  |
x|  Rachelle    |    D.    |        Dick       |        |          Dick-RD M. 05. LAM _SR_19.pdf          |  √  |
x|   Selene     |    D.    |       Maddox      |        |        Maddox-SD. M. 05. MSN. _SR_19.pdf        |  √  |
x|    Loren     |    A.    |       Smith       |        |       Smith-LA. J1. --. CC _Resp_SR_19.pdf      |  √  |
x|   Angela     |    D.    |      Mitchell     |        |       Mitchell-AD. M. 10. KS Ini_SR_19.pdf      |  √  |
x|    Brian     |    C.    |      Buescher     |        |        Buescher-BC. J3. 08. NE_SR_19.pdf        |  √  |
x|    Raul      |    M.    |   Arias-Marxuach  |        |    Arias-Marxuach-RM J3. 01 PR SIA_SR_19.pdf    |  √  |
x|   Patrick    |    R.    |       Wyrick      |        |        Wyrick-PR. J3. 10. OKW _SR_19.pdf        |  √  |
x|    John      |    M.    |       Younge      |        |        Younge-JM. J3. 03. PAE _SR_19.pdf        |  √  |
x|   Edward     |    S.    |        Kiel       |        |          Kiel-ES. M. 03. NJ _SR_19.pdf          |  √  |
x|  Jonathan    |    A.    |       Kobes       |        |            Kobes-JA. J3. 08_SR_19.pdf           |  √  |
x|    David     |    L.    |      Bissett      |        |         Bissett-D. B. 04. WVN_SR_19.pdf         |  √  |
x|   Robert     |    L.    |       Jones       |        |         Jones-RL. B. 05. TXN  _SR_19.pdf        |  √  |
x|     Joel     |          |       Gerber      |        |           Gerber-J. J1. TAX _SR_19.pdf          |  √  |
x|   Robert     |    P.    |       Myers       | Jr.,   |        Myers-RP. M. 05. MSS Ini_SR_19.pdf       |  √  |
x|   Steven     |    D.    |      Grimberg     |        |        Grimberg-SD. J3. 11. GAN_SR_19.pdf       |  √  |
x|   Martha     |    M.    |       Pacold      |        |         Pacold-MM. J3. 07. ILN_SR_19.pdf        |  √  |
x|   Miroslav   |          |       Lovric      |        |          Lovric-M. M. 02. NYN_SR_19.pdf         |  √  |
x|    Scott     |    M.    |      Grossman     |        |          Grossman-SM. B. 11. _SR_19.pdf         |  √  |
x|    Jagan     |    N.    |       Ranjan      |        |        Ranjan-JN. J3. 03. PAW _SR_19.pdf        |  √  |
x|   Justin     |    R.    |       Walker      |        |       Walker-JR J3. DC. KYW_SPE_SR_19.pdf       |  √  |
x|    Billy     |    G.    |       Parker      |        |         Parker-BG. B. 05. TXE _SR_19.pdf        |  √  |
x|   Jerusha    |    T.    |       Adams       |        |       Adams-JT. M. 11. ALM _Ini_SR_19.pdf       |  √  |
x|    John      |    S.    |       Hodge       |        |        Hodge-JS B. 05. LAW. Ini_SR_19.pdf       |  √  |
x|   Martin     |    A.    |    Fitzpatrick    |        |  Fitzpatrick-MA. M. 11. FLN _Resp_Ini_SR_19.pdf |  √  |
x|    Mark      |    A.    |       Beatty      |        |         Beatty-MA. M. 07. ILS _SR_19.pdf        |  √  |
x|    Greg      |    G.    |       Guidry      |        |        Guidry-GG. J3. 05. LAE _SR_19.pdf        |  √  |
x|    Chad      |    A.    |      Readler      |        |         Readler-CA. J3. 06. --_SR_19.pdf        |  √  |
x|    Damon     |    R.    |      Leichty      |        |         Leichty-D. J3. 07. INN_SR_19.pdf        |  √  |
x|    Scott     |    M.    |      Grossman     |        |        Grossman-SM. B. 11. Ini_SR_19.pdf        |  √  |
x|   Thomas     |    K.    |     Wetherell     |  II,   |     Wetherell II-TK. J3. 11. FLN __SR_19.pdf    |  √  |
x|   Daniel     |    E.    |      Butcher      |        |         Butcher-DE. M. 09. CAS_SR_19.pdf        |  √  |
x|    Joel      |    D.    |     Applebaum     |        |       Applebaum-JD. B. 06. MIE _SR_19.pdf       |  √  |
x|   Thomas     |    O.    |      Farrish      |        |         Farrish-TO. M. 02. CT_SR_19.pdf         |  √  |

2018 - not in 2019 list
--------------------------------------------------------------------------------
| New  | First | middle | Last | Suffix  | Filename  | PDF | 
| ------------- | ------------- |--|---|--|---|--|
x|   Mustafa    |    T.    |      Kasubhai     |        |        Kasubhai-MT. M. 09. OR Resp_SR_18.pdf        |  √  |
x|    Sunil     |    R.    |      Harjani      |        |         Harjani-SR. M. 07. ILN Ini_SR_18.pdf        |  √  |
x|   Dennis     |    M.    |        Cota       |        |            Cota-DM. M. 09. CAE _SR_18.pdf           |  √  |
x|   Gilbert    |    C.    |       Sison       |        |       Sison-GC. M. 07. ILS Resp_Ini_SR_18.pdf       |  √  |
x|  Jacqueline  |          |      Becerra      |        |         Becerra-J  M. 11. FLS _Ini_SR_18.pdf        |  √  |
x|    Carla     |    B.    |       Carry       |        |       Carry-CB. M. 09. NV_SR_17 and 18 Ini.pdf      |  √  |

**Comment by mlissner** [comment]
Nice work. Would it make sense to pull these folks from the FJC data? We must have code somewhere for importing it, and there's a good chance the data is in there (except for magistrates and bankr. judges, I suppose).

**Comment by flooie** [comment]
I think its worth looking into.

**Comment by flooie** [comment]
FJC Data should be able to add in about ~30 of the J3 Judges no problem - I tested them directly.  That leaves a lot of data collection that is on going now.  

Ive had to go through the remaining ~300 judges by hand that had image PDFs to extract out names and have identified one more judge to add to the list 


Christopher A. dos Santos, Magistrate TXSD

**Comment by mlissner** [comment]
Ready to close this mofo?

**Comment by flooie** [comment]
Done
