### ISSUE TITLE
Duplicate Judges discovered in 2019 Judge list

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1810]
| IDs | First | Middle | Last | Suffix  | Filename | PDF |
|-|-|-|-|-|-|-|
1238 & 5480  | Alfred   |      T.   |    Goodwin    |      |   Goodwin-AT. J3. 09. -- _SR_19.pdf       | √   |
1609 & 6779  |  Ketanji   |     B.  |    Jackson    |      |     Jackson-KB. J3. DC. DC_SR_19.pdf     |  √   |

**Comment by mlissner** [comment]
These still need to be de-duped. It looks like they happened b/c we lacked middle names for some of them. We should merge the metadata, create aliases if needed, and delete the more recently created judges.

**Comment by flooie** [comment]
this is half done - yay 

Alfred is particularly poorly bifurcated

**Comment by mlissner** [comment]
Alfred is cleaned up. I just did it all server-side.
