### ISSUE TITLE
Harvard Importer Bug

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1846]
I thought this date-obj bug would never get called but apparently I was wrong.

INFO Processing opinion at /storage/harvard_corpus/law.free.cap.me.110/260.6057053.json
This file crashes the importer.  Further investigation is needed

**Comment by mlissner** [comment]
This bug could use a lot more context. Can you explain what you're talking about, please?

**Comment by flooie** [comment]
Apologies, I drafted the issue before I had a diagnosis.  

the date obj generator/parser in Harvard imports worked fine except would fail when given a fake date.  

We assumed that the dates would be correct but we keep getting February 29th on non-leap year years.  

The plan is to check for an error on generation on date parsing and if the date is specifically leap-day to adjust it back to February 28.

**Comment by flooie** [comment]
Resolved
