### ISSUE TITLE
Scraping Opinions too narrow for citation type

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1851]
We have 8 different citation types, but we only allow for three citation types in the scraper.  

We should leverage eyecite to choose the correct citation type.

**Comment by mlissner** [comment]
Noting our discussion today, this will be a big change to Juriscraper that will make it simply return a list of citations for each case (or something similar), and we will have to do a big version bump to accompany the change.

**Comment by flooie** [comment]
For posterity... we switched from `neutral`, `west` and `west_state` citations - to just 
`citation` and `parallel_citation`.  

We decided that adding a list inside was probably too confusing of an issue.
