### ISSUE TITLE
Date mismatch between search results page and opinion page

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#1852]
If one does a search on CourtListener that brings up the non-precedential Kihn v. Bill Graham Archives (9th Cir.) opinion issued on January 3, 2022, then the search results page will show it as "Date Filed: January 2nd, 2022" but once you click on the link and get to the opinion page one sees it reported as "Filed: January 3rd, 2022" (which is correct, or which at least matches the PDF from the court). Why would the search results page provide a different filing date? Are there other instances of this sort of mismatch? Is the opinion page always correct or is sometimes the search results page correct and the opinion page wrong? Are we translating time zones from UTC or something in different ways in different places?

**Comment by mlissner** [comment]
This looks like a dup of https://github.com/freelawproject/courtlistener/issues/864, but that one is marked as fixed, which it clearly isn't. I'll reopen that and we can keep it going there. I think it was a timezone thing, but it's weird that it's still floating around.
