### ISSUE TITLE
Notes on New disclosures

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1864]
We received a new batch of financial disclosures for 2019.  
The thumb drive contained 340 new disclosures, but 44 of them appear to be duplicates.  
So the total number of disclosures is actually 296 new disclosures.

**Comment by flooie** [comment]
We ended up needing to add a handful of new magistrate judges, and at least one judge has a new last name from Georgia. 

Other oddities,

Hawaii Magistrate Judge Kenneth Mansfield continues his long stretch of returning empty disclosures.  No investments no positions nothing. 
https://www.courtlistener.com/person/9207/disclosure/31869/kenneth-mansfield/

Judge Van Tatenhove of Kentucky decided that this year was the year to redact his positions 
https://www.courtlistener.com/person/3306/disclosure/32076/gregory-frederick-van-tatenhove/

He clearly is redacting the same material on the previous filings - and I can't think of a justification for those redactions.

**Comment by flooie** [comment]
Disclosures have been successfully imported and processed.

**Comment by mlissner** [comment]
Wow, that is a record pace. What made it so fast this time? Well done!
