### ISSUE TITLE
BIA decisions need gentle cleanup

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1868]
We need to cleanup a few things for the DOJ Immigration opinions

- [x] An update to Juriscraper to change the status
- [x] Update the decisions in CL to precedential
- [x] Backscraped opinions do not appear in search results (update solr)
- [x] Add citations for volume 28 that failed because of non standard citation
- [x] Add variations of citations in reporters-db to fix future failing citations
- [x] Fix the rare extract date failure that occurred a few times.

**Comment by mlissner** [comment]
Another stray, half-finished ticket.
