### ISSUE TITLE
Update containers for Docker Compose V2

### ISSUE THREAD

**Issue by satsuki-chan** [freelawproject/courtlistener#1875]
There are changes between the commands for **docker-compose** V1 and V2. According to the release logs for docker-compose:

> Docker Compose V2 is a major version bump release of Docker Compose. It has been completely rewritten from scratch in Golang (V1 was in Python). The installation instructions for Compose V2 differ from V1. V2 is not a standalone binary anymore, and installation scripts will have to be adjusted. Some commands are different.
> For a smooth transition from legacy docker-compose 1.xx, please consider installing compose-switch to translate `docker-compose ...` commands into Compose V2's `docker compose ....` . Also check V2's --compatibility flag.
> 
[https://github.com/docker/compose#about-update-and-backward-compatibility](https://github.com/docker/compose#about-update-and-backward-compatibility)

Tha last version for V1, [**1.29.2**](https://github.com/docker/compose/releases/tag/1.29.2), was released in May 2021, and V2 is in its second stable release, [**2.2.3**](https://github.com/docker/compose/releases/tag/v2.2.3). It's recomended to update all containers' Docker files to be compatible with Docker Compose V2 and ask all developers to switch to V2.

Among the differences, for example, in V2 there is a change in the keywords accepted for the `deploy.restart_policy` parameter. The current configuration in the containers for **V1**:
```
    deploy:
      restart_policy:
        condition: none
```
fails when run with V2 and returned this error:
`Error response from daemon: invalid restart policy 'none'`

The `restart_policy` keyword must be changed to `"no"` to compatible with **V2**:
```
    deploy:
      restart_policy:
        condition: "no"
```

Currently, this difference affects containers **cl-judge-pics** and **cl-seal-rookery**.

For reference, see:
- [https://github.com/docker/compose#docker-compose-v2](https://github.com/docker/compose#docker-compose-v2)

About the differences between **Docker Compose** and **Docker CLI** keywords for `restart_policy`:
- [https://stackoverflow.com/questions/51089549/docker-stack-deploy-with-restart-policy-throws-error-response-from-daemon-inva](https://stackoverflow.com/questions/51089549/docker-stack-deploy-with-restart-policy-throws-error-response-from-daemon-inva)

**Comment by mlissner** [comment]
Here's the upstream issue: https://github.com/docker/compose/issues/8756

**Comment by mlissner** [comment]
We'll do this someday, but it doesn't matter when anymore because we removed seal rookery and judge pics. I'm going to close this and we can get to it when it becomes necessary.
