### ISSUE TITLE
IA directory limits bumping into uploader

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1889]
There appears to be a soft cap for number of items in a directory on the internet archive.  Unfortunately, one of the new volumes collected from case.law has roughly 5k opinions.  Which would upload roughly 10k files, meta and opinion files.  

I reached out to the IA and they said they dont recommend over 1k items in a directory of 500 gb.

It looks like we will need to split this volume 571 U.S. XXX into multiple directories on the IA.

cc @mlissner

**Comment by mlissner** [comment]
Bummer. I presume you asked them if some kind of exception could be made? That's a wimpy limitation.

**Comment by flooie** [comment]
they say its not really a cap - its just not recommended.  And it certainly seems not recommended because I can't access the directory.

**Comment by mlissner** [comment]
Jeez. What do you mean that you can't access the directory? Timeouts?

**Comment by flooie** [comment]
504

**Comment by mlissner** [comment]
Well, OK. Nothing we can do about that. Suggestions on handling the split?

**Comment by flooie** [comment]
law.free.cap.[reporter].volume[optional _1,_2]....? right that just truncates _XXX seems easy to fix

**Comment by mlissner** [comment]
Sounds about right to me, thanks.

**Comment by flooie** [comment]
Yes this should be just noted for future changes we might make to the IA uploader.
