### ISSUE TITLE
Library for fake S3 storage for dev/test in CL

### ISSUE THREAD

**Issue by satsuki-chan** [freelawproject/courtlistener#1891]
Alternatives for libraries for testing functions that require to upload and download content from S3 storage. All must include support for _**Python**_ and for current _**CI deployment**_ in Github.

- [moto](https://github.com/spulec/moto)
- [localstack](https://github.com/localstack/localstack)

#### References:
- https://www.sanjaysiddhanti.com/2020/04/08/s3testing/
- https://itnext.io/mocking-aws-services-f80d1fd114c1

**Comment by satsuki-chan** [comment]
[moto](https://github.com/spulec/moto)

# Advantages
- Supports Python
- Easy to implement. It's almost a substitute for the original boto3 library
- Its [documentation](https://docs.getmoto.org/en/latest/docs/getting_started.html) includes instructions and examples on how to setup the library in a test class, including **unittest**.
    - Includes instructions to avoid known issues with the boto3 library.
    - Additional guides and articles to configure moto are easy to find.
- Detailed list of [implemented functions](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md) with examples, besides [S3](https://docs.getmoto.org/en/latest/docs/services/s3.html).
- Includes a stand-alone server to execute local tests.
- Can be integrated in Tox, Travis CI, and other build systems. Setup explained in the [getting started guide](https://docs.getmoto.org/en/latest/docs/services/s3.html).

# Disavantages
- Integration with CI systems requieres to set up a file with the [mock credentials](https://docs.getmoto.org/en/latest/docs/services/s3.html) before execution. 
- Some specific AWS functions we might need might not be [implemented yet](https://github.com/spulec/moto/blob/master/IMPLEMENTATION_COVERAGE.md).

#### References:
- https://docs.getmoto.org/en/latest/index.html
- https://muhannad0.github.io/post/using-moto-to-mock-test-aws-a-dynamodb-example/

**Comment by satsuki-chan** [comment]
# [LocalStack: A fully functional local cloud stack Develop and test your cloud and serverless apps offline!](https://github.com/localstack/localstack)

## Advantages
- Supports [Python and the boto3 library](https://docs.localstack.cloud/integrations/sdks/python/).
    - Optionally, has a library to access additional [LocalStack functions](https://github.com/localstack/localstack-python-client) from the.
- **_Mocks a AWS cloud service stack_** locally and has a detailed list of supported [AWS functions](https://docs.localstack.cloud/aws/feature-coverage/).
    - It's [Open Source](https://localstack.cloud/features/) version includes suport for [S3](https://docs.localstack.cloud/aws/s3/).
- Easy to install and configure it's [CLI](https://docs.localstack.cloud/get-started/#localstack-cli)
    - Can be installed from a [docker container](https://docs.localstack.cloud/get-started/#docker)
    - Detailed configuration for all [install options](https://docs.localstack.cloud/localstack/configuration/)
- Doesn't require to change or modify existing tests classes.
- Includes instructions to setup [GitHub Actions](https://docs.localstack.cloud/ci/github-actions/)

## Disadvantages
- Setting it up as a docker container to run tests on local and on a CI pipeline consumes additional resources.
    - Might require additional computer resources on local development equipment.
- Has limited functionality for some [implementations (DynamoDB and Lambda) and integrations](https://docs.localstack.cloud/localstack/limitations/).
- Requires additional documentation to standardize the configuration for all developers and testers.
    - Tests that require a heavy use of computer resources (processor and RAM) might take longer or return different results, depending on the local equipment of each developer.


#### References
- https://localstack.cloud/
- https://github.com/localstack/localstack-python-client

**Comment by mlissner** [comment]
These feel like pretty big solutions. Did you look at [dj-inmemorystorage](https://github.com/waveaccounting/dj-inmemorystorage)? There's a stackoverflow about it [here](https://stackoverflow.com/a/17066553/64911), and it's mentioned in Speed Up Your Django Tests, a book about this kind of thing that I read a bit ago ([relevant pages here](https://github.com/freelawproject/courtlistener/files/7962422/suypt.snippet.pdf)).

**Comment by satsuki-chan** [comment]
Looks interesting. I like it that it's simple to implement.
But, it only supports Python **3.8** and it hasn't been updated since 2020.

> These feel like pretty big solutions. Did you look at [dj-inmemorystorage](https://github.com/waveaccounting/dj-inmemorystorage)? There's a stackoverflow about it [here](https://stackoverflow.com/a/17066553/64911), and it's mentioned in Speed Up Your Django Tests, a book about this kind of thing that I read a bit ago ([relevant pages here](https://github.com/freelawproject/courtlistener/files/7962422/suypt.snippet.pdf)).

**Comment by mlissner** [comment]
I think the support seems fine. They say they're supporting the supported versions of Python and Django. We're on Python 3.8 which it supports, and we're on Django 3.1, which they support.

**Comment by satsuki-chan** [comment]
# [dj-inmemorystorage](https://github.com/waveaccounting/dj-inmemorystorage#dj-inmemorystorage)

## Advantages
- It supports Python 3.8 and Django 3.1.
- It's simple to implement. Can be used in place of Django's `FileSystemStorage`.
- There are examples online that explain how to configure and change current test cases to use dj-inmemorystorage:
  - https://stackoverflow.com/questions/67605691/how-to-test-image-upload-on-django-rest-framework
  - (with Pytest) https://flowfx.de/blog/use-django-in-memory-file-storage-with-pytest/
  - (patch for `S3Boto3Storage`) https://cscheng.info/2018/08/21/mocking-a-file-storage-backend-in-django-tests.html

## Disadvantages
- It doesn't support newer versions of Python and Django.
  - The library hasn't been updated since March, 2020
- Not many guides or detailed examples in case of implementation errors. Many use examples are a bit old.


### References
- https://github.com/waveaccounting/dj-inmemorystorage
- https://github.com/freelawproject/courtlistener/files/7962422/suypt.snippet.pdf
- https://github.com/guettli/programming-guidelines#hermetic-testing

**Comment by mlissner** [comment]
Cool. Let's do dj-inmemorystroage. Want to do a draft PR that patches it in for our tests and see what bumps you run into along the way? (Don't forget I linked to a recent book demoing this too in my earlier comment.)

Keeping it light seems best for now. If it doesn't work or isn't enough, we won't have invested too much.

Django and Python are also pretty stable these days. I expect it won't be a big problem for us, even if we have to patch it ourselves.
