### ISSUE TITLE
Develop a data entry page for enhancing judges

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1892]
We're going to hire a data researcher at any moment, and we need to have a website for them to actually use to input data. 

The data we're currently planning to collect is:

 - DOB
 - DOB city & state
 - Gender
 - Race
 - Political affiliation
 - Education

The goal here is to be fast. I think the best way to do that is to make really small, really simple site that just asks for a couple pieces of data at a time and allows you to chunk through the data as rapidly as possible. 

So I could see a page that just asks for the race and DOB info, then when you submit (assuming no errors), it takes you to the next judge, where you repeat the process. Onwards until you're done.

A couple other easy features would be:

 - Wikipedia link searching for the judge by name
 - A ballotpedia link searching for the judge by name

@samaramas, @flooie, what do you guys think?

**Comment by mlissner** [comment]
Oh, and the idea would be that after race and DOB are done, there's a new page where you iterate over all the judges one by one doing their education data. The idea is that you'd focus on a couple pieces of data at a time, rather than going deep and having to think about each piece of data for each judge.

**Comment by mlissner** [comment]
More features:
 - It'll be paginated, so the user will need to keep track of where they are, but let's put a hidden feature that allows you to do `&name=bean` and find judges with that name to paginate over just those. That'll let people return places they previously were.
 - After completing a record, it should add a row to the `source` table.
 - The page should show the `date_updated` field at the top (and maybe allow filtering by it via a `&updated_after=` field.

**Comment by samaramas** [comment]
I think it would be a good idea to have a field for source(s) included as well.  If someone is going to vet this data it would be good to know where the researcher found it.

I also think the more times you iterate over the judges the longer it takes.  I appreciate the simplicity of doing one variable at a time but this can also be frustrating if you stumble on a good source for someone that has fully flushed out biographical data and you have to wait to enter it (and remember the source - which is unlikely with thousands of judges).

As for set up it seems like a Google Sheet would work as well for this as a simple Django site where the researcher just works off of an admin page.
