### ISSUE TITLE
Blank pages when searching by citations

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1911]
[Courtlistener lets you search by citation](https://courtlistener.com/c/)

But I noticed if you put in gibberish for the three fields, or if we just dont have the citation, you get a blank page.

[See https://www.courtlistener.com/c/adsfa/1231/](https://www.courtlistener.com/c/adsfa/1231/ )

**Comment by flooie** [comment]
This is almost certainly a bug in 
```
def citation_redirector(
    request: HttpRequest,
    reporter: Optional[str] = None,
    volume: Optional[str] = None,
    page: Optional[str] = None,
) -> HttpResponse:
```
in the opinion_page/views.py file.

**Comment by satsuki-chan** [comment]
It's a verification error when the **reporter** is not found in `reporters_db`:

https://www.courtlistener.com/c/jhgf/
![Screenshot from 2022-02-17 17-58-16](https://user-images.githubusercontent.com/8507838/154591739-4f46c727-2379-4f27-a07d-25da220be3fb.png)

When the **reporter** exist, any gibberish is redirected to the default page: 
https://www.courtlistener.com/c/haw/5214/54/
![Screenshot from 2022-02-17 18-02-35](https://user-images.githubusercontent.com/8507838/154592125-17347e1b-36fe-41ab-930d-d77edce1468c.png)

https://www.courtlistener.com/c/haw/5214/hgfd/
![Screenshot from 2022-02-17 18-05-49](https://user-images.githubusercontent.com/8507838/154592442-51045e12-79fd-4431-aa35-571fc01f746a.png)
