### ISSUE TITLE
Emails should come from uscourts.gov

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1915]
Right now, our lambda for recap.email checks for SPAM, viruses, etc, but we don't actually check that an email is coming from the uscourts.gov domain. We should make sure they do. 

I'm not sure which header to check for this, but I'll follow up if I learn more. It appears it's not as simple as it may seem though.

**Comment by albertisfu** [comment]
Sure, I've seen that in headers we have `"name": "From"` that match with the email in `"source":` property, so I'm wondering if this is the right header to look for it

**Comment by mlissner** [comment]
So, talking to a friend that does a lot of work with email, he assures me that if SPF and DKIM both pass, we can trust the From header of the message or the Return-Path header of the envelope. He suggests using the Return-Path should be easier since the From header sometimes will say something like, "Michael Lissner <mike@free.law>" whereas the Return-Path will usually just be an email address. 

So I think the way forward here is to check the Return-Path header that it's coming from uscourts.gov, and go with that.

**Comment by albertisfu** [comment]
Perfect, so I'll do the verification by using `Return-Path` header

**Comment by albertisfu** [comment]
Yes, it sounds good to me! so now I'll check for all `Return-Path` headers

**Comment by albertisfu** [comment]
I've added the domain validation function beside the auth token thing in lambda here: https://github.com/freelawproject/awscloud/pull/4

**Comment by mlissner** [comment]
Looks like this one is resolved, @albertisfu ?

**Comment by albertisfu** [comment]
This feature is already implemented in the lambda function, however, is not tested yet because right now the lambda function is failing before in the SPAM validation, I'm debugging the lambda to check what's the origin of the error, seems that the email receipt has changed or it might have something do to with this change.

**Comment by mlissner** [comment]
OK, *now* this one is resolved, I think?

**Comment by albertisfu** [comment]
Yes! I can confirm this is working properly, today we receive two emails from the user that is forwarding us the messages so those emails don't have a `Return-Path` from a `uscourts.gov` domain, so they weren't processed.

**Comment by mlissner** [comment]
What user is forwarding us messages?
