### ISSUE TITLE
Pennsylvania Import Notes

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1921]
I am beginning to import Pennsylvania, and I think a series of notes here may be instructive.

I downloaded the volumes on Internet Archive to the server, but having learned my lesson, I went to check 
if the volumes are in fact all downloaded.  

By my calculations, there is a difference of 83 volumes, +84  &  -1  

|      Reporter     |          Reporter API endpoint         | Vol. # (H) |           Reporter Frontend            |   Harvard slug  | Vol. # (IA) | Diff | Notes |
|:-----------------:|:--------------------------------------:|:----------:|:--------------------------------------:|:---------------:|:-----------:|:----:|-------|
|        A.2d       | https://api.case.law/v1/reporters/210/ |     970    |       https://cite.case.law/a2d/       |       a2d       |     967     |   3  |       |
|        Pa.        | https://api.case.law/v1/reporters/409/ |     640    |        https://cite.case.law/pa/       |        pa       |     639     |   1  |       |
|     Pa. Super.    | https://api.case.law/v1/reporters/357/ |     456    |     https://cite.case.law/pa-super/    |     pa-super    |     444     |  12  |       |
|        A.3d       | https://api.case.law/v1/reporters/964/ |     254    |       https://cite.case.law/a3d/       |       a3d       |     212     |  42  |       |
|     Pa. Commw.    | https://api.case.law/v1/reporters/538/ |     168    |     https://cite.case.law/pa-commw/    |     pa-commw    |     168     |   0  |       |
|    Pa. D. & C.    | https://api.case.law/v1/reporters/385/ |     89     |      https://cite.case.law/pa-d-c/     |      pa-d-c     |      89     |   0  |       |
|   Pa. D. & C.4th  | https://api.case.law/v1/reporters/392/ |     83     |    https://cite.case.law/pa-d-c4th/    |    pa-d-c4th    |      82     |   1  |       |
|   Pa. D. & C.2d   | https://api.case.law/v1/reporters/389/ |     75     |     https://cite.case.law/pa-d-c2d/    |     pa-d-c2d    |      74     |   1  |       |
|   Pa. D. & C.3d   | https://api.case.law/v1/reporters/390/ |     50     |     https://cite.case.law/pa-d-c3d/    |     pa-d-c3d    |      50     |   0  |       |
|   Pa. D. & C.5th  | https://api.case.law/v1/reporters/794/ |     48     |    https://cite.case.law/pa-d-c5th/    |    pa-d-c5th    |      45     |   3  |       |
|   Serg. & Rawl.   | https://api.case.law/v1/reporters/836/ |     17     |    https://cite.case.law/serg-rawl/    |    serg-rawl    |      1      |  16  |       |
|       Sadler      | https://api.case.law/v1/reporters/803/ |     10     |      https://cite.case.law/sadler/     |      sadler     |      10     |   0  |       |
|       Watts       | https://api.case.law/v1/reporters/842/ |     10     |      https://cite.case.law/watts/      |      watts      |      10     |   0  |       |
|   Watts & Serg.   | https://api.case.law/v1/reporters/837/ |      9     |    https://cite.case.law/watts-serg/   |    watts-serg   |      9      |   0  |       |
|       Binn.       | https://api.case.law/v1/reporters/835/ |      6     |       https://cite.case.law/binn/      |       binn      |      6      |   0  |       |
|       Whart.      | https://api.case.law/v1/reporters/840/ |      6     |      https://cite.case.law/whart/      |      whart      |      6      |   0  |       |
|       Rawle       | https://api.case.law/v1/reporters/838/ |      5     |      https://cite.case.law/rawle/      |      rawle      |      5      |   0  |       |
|      Pennyp.      | https://api.case.law/v1/reporters/828/ |      4     |      https://cite.case.law/pennyp/     |      pennyp     |      4      |   0  |       |
|       Yeates      | https://api.case.law/v1/reporters/834/ |      4     |      https://cite.case.law/yeates/     |      yeates     |      4      |   0  |       |
|       Walker      | https://api.case.law/v1/reporters/844/ |      4     |      https://cite.case.law/walker/     |      walker     |      1      |   3  |       |
|       Foster      | https://api.case.law/v1/reporters/955/ |      3     |      https://cite.case.law/foster/     |      foster     |      3      |   0  |       |
|     Pen. & W.     | https://api.case.law/v1/reporters/839/ |      3     |      https://cite.case.law/pen-w/      |      pen-w      |      3      |   0  |       |
|       Grant       | https://api.case.law/v1/reporters/841/ |      3     |      https://cite.case.law/grant/      |      grant      |      3      |   0  |       |
|      Monaghan     | https://api.case.law/v1/reporters/790/ |      2     |     https://cite.case.law/monaghan/    |     monag    |      2      |   0  |    The slug here we used is monag - changed from monaghan    |
|       Miles       | https://api.case.law/v1/reporters/846/ |      2     |      https://cite.case.law/miles/      |      miles      |      2      |   0  |       |
|        Add.       | https://api.case.law/v1/reporters/188/ |      1     |       https://cite.case.law/add/       |       add       |      1      |   0  |       |
|       Dall.       | https://api.case.law/v1/reporters/187/ |      1     |       https://cite.case.law/dall/      |       dall      |      1      |   0  |       |
|       Pears.      | https://api.case.law/v1/reporters/808/ |      1     |      https://cite.case.law/pears/      |      pears      |      1      |   0  |       |
|  Pa. (Admiralty)  | https://api.case.law/v1/reporters/813/ |      1     |   https://cite.case.law/pa-admiralty/  |   pa-admiralty  |      1      |   0  |       |
|  Law Times (N.S.) | https://api.case.law/v1/reporters/956/ |      1     |   https://cite.case.law/law-times-ns/  |   law-times-ns  |      1      |   0  |       |
|      Pa. Fid.     | https://api.case.law/v1/reporters/823/ |      1     |      https://cite.case.law/pa-fid/     |      pa-fid     |      1      |   0  |       |
| Pa. Just. L. Rep. | https://api.case.law/v1/reporters/825/ |      1     |  https://cite.case.law/pa-just-l-rep/  |  pa-just-l-rep  |      1      |   0  |       |
|      Brightly     | https://api.case.law/v1/reporters/843/ |      1     |     https://cite.case.law/brightly/    |     brightly    |      1      |   0  |       |
|        Vaux       | https://api.case.law/v1/reporters/959/ |      1     |       https://cite.case.law/vaux/      |       vaux      |      1      |   0  |       |
|      Parsons      | https://api.case.law/v1/reporters/960/ |      1     |     https://cite.case.law/parsons/     |     parsons     |      1      |   0  |       |
|                   |                                        |            |                                        |                 |             |  84  |       |
| Blair Co. L.R. 2d | https://api.case.law/v1/reporters/787/ |      0     |  https://cite.case.law/blair-co-lr-2d/ |  blair-co-lr-2d |      0      |      |       |
| Bradford Co. L.J. | https://api.case.law/v1/reporters/799/ |      0     |  https://cite.case.law/bradford-co-lj/ |  bradford-co-lj |      0      |      |       |
|   Bucks Co. L.R.  | https://api.case.law/v1/reporters/800/ |      0     |   https://cite.case.law/bucks-co-lr/   |   bucks-co-lr   |      0      |      |       |
|  Cambria Co. Rep. | https://api.case.law/v1/reporters/802/ |      0     |  https://cite.case.law/cambria-co-rep/ |  cambria-co-rep |      0      |      |       |
|  Carbon Co. L.J.  | https://api.case.law/v1/reporters/861/ |      0     |   https://cite.case.law/carbon-co-lj/  |   carbon-co-lj  |      0      |      |       |
|   Dau. Co. Rep.   | https://api.case.law/v1/reporters/862/ |      0     |    https://cite.case.law/dau-co-rep/   |    dau-co-rep   |      0      |      |       |
|   Erie. Co. L.J.  | https://api.case.law/v1/reporters/810/ |      0     |    https://cite.case.law/erie-co-lj/   |    erie-co-lj   |      0      |      |       |
|   Leg. Rec. Rep.  | https://api.case.law/v1/reporters/869/ |      0     |   https://cite.case.law/leg-rec-rep/   |   leg-rec-rep   |      0      |      |       |
|     Luz. L.O.     | https://api.case.law/v1/reporters/873/ |      0     |      https://cite.case.law/luz-lo/     |      luz-lo     |      0      |      |       |
|    Monroe L.R.    | https://api.case.law/v1/reporters/850/ |      0     |    https://cite.case.law/monroe-lr/    |    monroe-lr    |      0      |      |       |
| Mont. Co. L. Rep. | https://api.case.law/v1/reporters/851/ |      0     |  https://cite.case.law/mont-co-l-rep/  |  mont-co-l-rep  |      0      |      |       |
| Northam. Law Rep. | https://api.case.law/v1/reporters/852/ |      0     | https://cite.case.law/northam-law-rep/ | northam-law-rep |      0      |      |       |
|    Pa. L. Rec.    | https://api.case.law/v1/reporters/827/ |      0     |     https://cite.case.law/pa-l-rec/    |     pa-l-rec    |      0      |      |       |
|    Pa. Co. Ct.    | https://api.case.law/v1/reporters/821/ |      0     |     https://cite.case.law/pa-co-ct/    |     pa-co-ct    |      0      |      |       |
|   Pa. L.J. Rep.   | https://api.case.law/v1/reporters/826/ |      0     |    https://cite.case.law/pa-lj-rep/    |    pa-lj-rep    |      0      |      |       |
|    Pittsb. L.J.   | https://api.case.law/v1/reporters/857/ |      0     |    https://cite.case.law/pittsb-lj/    |    pittsb-lj    |      0      |      |       |
|    Bro. Com. P.   | https://api.case.law/v1/reporters/832/ |      0     |    https://cite.case.law/bro-com-p/    |    bro-com-p    |      0      |      |       |
|    Schuy. Reg.    | https://api.case.law/v1/reporters/876/ |      0     |    https://cite.case.law/schuy-reg/    |    schuy-reg    |      1      |  -1  | ????  |
|   Com. Pl. Rep.   | https://api.case.law/v1/reporters/961/ |      0     |    https://cite.case.law/com-pl-rep/   |    com-pl-rep   |      0      |      |       |
|   York Leg. Rec.  | https://api.case.law/v1/reporters/878/ |      0     |   https://cite.case.law/york-leg-rec/  |   york-leg-rec  |      0      |      |       |

**Comment by flooie** [comment]
Immediate research needed 

- [ ] Where are the missing volumes 
- [ ] Why is there an extra volume

**Comment by flooie** [comment]
We have a mysterious volume of 1, `Schuylkill Register` with one opinion, that doesn't seem to be in Harvard anymore.  

[IA json link](https://ia801906.us.archive.org/4/items/law.free.cap.schuy-reg.1/40.6757699.json)
[Harvard Case Link](https://api.case.law/v1/cases/6757699/) *broken
[Harvard Link Link](https://cite.case.law/schuy-reg/1/40/) *also broken

Searching for the opinion on Harvard does provide a case that appears to be what I presume is a subsequent appeal. 

Perhaps @jcushman knows what happened to this case and reporter?

**Comment by flooie** [comment]
A first batch got 100% complete today.  

|    Reporter   |          Reporter API endpoint         | Volume count in case.law |         Reporter Frontend         | Harvard slug | Volume count in IA | Diff | STATUS   |
|:-------------:|:--------------------------------------:|:------------------------:|:---------------------------------:|:------------:|:------------------:|:----:|----------|
|     Sadler    | https://api.case.law/v1/reporters/803/ |            10            |   https://cite.case.law/sadler/   |    sadler    |         10         |   0  | COMPLETE |
|     Watts     | https://api.case.law/v1/reporters/842/ |            10            |    https://cite.case.law/watts/   |     watts    |         10         |   0  | COMPLETE |
| Watts & Serg. | https://api.case.law/v1/reporters/837/ |             9            | https://cite.case.law/watts-serg/ |  watts-serg  |          9         |   0  | COMPLETE |
|     Whart.    | https://api.case.law/v1/reporters/840/ |             6            |    https://cite.case.law/whart/   |     whart    |          6         |   0  | COMPLETE |
|     Rawle     | https://api.case.law/v1/reporters/838/ |             5            |    https://cite.case.law/rawle/   |     rawle    |          5         |   0  | COMPLETE |
|     Yeates    | https://api.case.law/v1/reporters/834/ |             4            |   https://cite.case.law/yeates/   |    yeates    |          4         |   0  | COMPLETE |
|   Pen. & W.   | https://api.case.law/v1/reporters/839/ |             3            |    https://cite.case.law/pen-w/   |     pen-w    |          3         |   0  | COMPLETE |
|     Grant     | https://api.case.law/v1/reporters/841/ |             3            |    https://cite.case.law/grant/   |     grant    |          3         |   0  | COMPLETE |
|    Monaghan   | https://api.case.law/v1/reporters/790/ |             2            |  https://cite.case.law/monaghan/  |     monag    |          2         |   0  | COMPLETE |

**Comment by mlissner** [comment]
We're just going to do this nationally, so we can close this out.
