### ISSUE TITLE
Financial Disclosures Rest of 2019 and 2020

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1922]
Creating an issue for each major import of financial disclosures. We received the latest batch from the courts 

2019 • 128
2020 • 802

Steps
------

- [x] Scan letters for @mlissner and safe keeping
- [x] Upload to AWS
- [x] Match disclosures to individual judges (ugh why can't they standardize this)
- [x] Identify new judges not yet in our system
- [x] Add said new judges in CL
- [x] Import all disclosures into CL
- [x] Cleanup, find any missing 2019 judges
- [x] Follow up with AO for missing judges in 2019 dataset or corrupt PDFs

Invariably there are new shoes to drop during this and I'll add to them here.

**Comment by flooie** [comment]
Notes
------

0 completely corrupted PDFs 🥳 


**JEFS**
---------
9 JEF PDFs in the 2020 disclosures
Trenga-AJ. J3. 04. VAE_SR_20.pdf
Senechal-AR. M. 08. ND_SR_20.pdf
Rice-DE. B. 04. MD_SR_20.pdf
Bucklo-EE. J3. 07. ILN_SR_20.pdf
Pearson-BY. J3. 06. OHN_SR_20.pdf
Bunning-DL. J3. 06. KYE_SR_20.pdf
Phillips-ME. J3. 08. MOW_SR_20.pdf
Benitez-RT. J3. 09. CAS_SR_20.pdf
Stoll-KF. J3. FC.--_SR_20.pdf


8 JEF PDFs in the 2019 disclosures
Trenga-AJ. J3. 04. VAE_SR_19.pdf
Hicks-SM. J3. 05. LAW_SR_19.pdf
Smith-MD. J3. 09.--_SR_19.pdf
Steele-WH. J3. 11. ALS_SR_19.pdf
Phillips-ME. J3. 08. MOW_SR_19.pdf
Pearson-BY. J3. 06. OHN_SR_19.pdf
Zobel-RW. J3. 01. MA_SR_19.pdf
Stoll-KF. J3. FC.--_SR_19.pdf


OCR Needed
-------------
**No machine readable text**  (thanks for nothing)
Kocoras-CP. J3. 07. ILN SIA_SR_19.pdf
Arterton-JB. J3. 02. CT_SR_20.pdf
Davis-D. B. 02. NYN _SR_20.pdf
Grosjean-EP. M. 09. CAE_SR_20.pdf
Greer-JR. J3. 06. TNE _SR_20.pdf
Drozd-DA. J3. 09. CA _SR_20.pdf
Garaufis-NG. J3. 02. NYE SIA_SR_20.pdf
Donald-BB. J3. 06. --_SR_20.pdf
Metcalf-WC. M. 04. NCW. _SR_20.pdf

**Scanned first page only** Some of these files have this weird tendency to be OCR page one the rest machine readable
Either way these all need extra love from our system.
Newman-KJ. M. 09. CAE Resp_SR_19.pdf
McDonough-TR. J3. 06. TNE_SR_19.pdf
Pallmeyer-RR. J3. 07. ILN _SR_20.pdf
Burris-HE. B. 04. SC _SR_20.pdf
Bruggink-EG. J1. --. CC _SR_20.pdf
Carlson-MC. M. 03. PAM_SR_20.pdf
Wyrick-CR. M. 06. TNE_SR_20.pdf

**Comment by flooie** [comment]
After some starts and stops we have imported all of the disclosures (save 9) from the list of judges we previously had in the system.  

```
Found: not extracted 8903 2019 https://www.courtlistener.com/person/8903/go
Found: not extracted 300 2019 https://www.courtlistener.com/person/300/go
Not Found 9627 2020 https://www.courtlistener.com/person/9627/go
Found: not extracted 8573 2020 https://www.courtlistener.com/person/8573/go
Not Found 9544 2020 https://www.courtlistener.com/person/9544/go
Not Found 8852 2020 https://www.courtlistener.com/person/8852/go
Found: not extracted 8903 2020 https://www.courtlistener.com/person/8903/go
Not Found 9550 2020 https://www.courtlistener.com/person/9550/go
Found: not extracted 2830 2020 https://www.courtlistener.com/person/2830/go
```

Unfortunately, It's not clear what is stopping these nine disclosures from either extracting or generally being added to the system.  Further research is needed.

**Comment by flooie** [comment]
√ Found: not extracted 8903 2019 https://www.courtlistener.com/person/8903/go
√ Found: not extracted 300 2019 https://www.courtlistener.com/person/300/go
√ Not Found 9627 2020 https://www.courtlistener.com/person/9627/go
√ Found: not extracted 8573 2020 https://www.courtlistener.com/person/8573/go
√ Found: not extracted 8903 2020 https://www.courtlistener.com/person/8903/go
√ Found: not extracted 2830 2020 https://www.courtlistener.com/person/2830/go

This one is a duplicate of 2019  Not Found 9544 2020 https://www.courtlistener.com/person/9544/go
This is also a duplicate of 2019 Not Found 9550 2020 https://www.courtlistener.com/person/9550/go
This is also a duplicate of the 2019 Not Found 8852 2020 https://www.courtlistener.com/person/8852/go

**Comment by mlissner** [comment]
I think your note above explains it in a sense, but do we know which 2019's we're still lacking? Seems like it's time to send them another detailed email? And maybe a summary of the 2020 status?

**Comment by flooie** [comment]
Yes it does.  I'm running a deep check for all the judges missing from our system first. Especially for newsworthy judges in recent news ala [Judge Mizelle](https://en.wikipedia.org/wiki/Kathryn_Kimball_Mizelle) who does not appear in our database.

**Comment by flooie** [comment]
I think we have sent a follow up on these missing opinions to the AO - and so I will tentatively close this

**Comment by mlissner** [comment]
An issue to plug the gaps is in #2032.
