### ISSUE TITLE
Financial Disclosures Search Unexpected Behavior

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1925]
When you enter or copy paste a judge into the financial disclosures without results and hit enter, it does a search

`https://www.courtlistener.com/?disclosures-filter=random-judge-input`

It throws it into an opinions search.  This is weird and unexpected behavior.  Its also probably pretty confusing for users.

**Comment by mlissner** [comment]
Weird, yeah, we should probably fix this!

**Comment by flooie** [comment]
this still exists.

**Comment by flooie** [comment]
Should I tackle this tomorrow? @mlissner

**Comment by mlissner** [comment]
See if it's a quick fix?

**Comment by flooie** [comment]
Fixed in  #2057
