### ISSUE TITLE
Financial Disclosures: Value Undefined

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#1927]
I noticed $undefined (None) showing up on a disclosure extract and thought ... oh thats not good.  

Looks like a Judge decided to just put None down for Debts but list them?  

https://www.courtlistener.com/person/8623/disclosure/32331/peter-joseph-phipps/

https://storage.courtlistener.com/us/federal/judicial/financial-disclosures/8623/peter-joseph-phipps-disclosure.2020.pdf
<img width="1246" alt="Screen Shot 2022-02-23 at 9 47 01 AM" src="https://user-images.githubusercontent.com/6464529/155342792-fc9e11b4-fa57-4d03-9411-42f53229a7b9.png">
<img width="903" alt="Screen Shot 2022-02-23 at 9 47 31 AM" src="https://user-images.githubusercontent.com/6464529/155342844-efaf1d47-9d19-4f0d-9d93-85d5a4e0c90f.png">

@mlissner is this worth asking the AO about?  Also we need to adjust something to avoid this undefined fiasco.

**Comment by mlissner** [comment]
I assume these should be coded as `J`, "$15,000 or less"? I'm not sure I really care about one judge's sloppy work enough to pick up a phone or write an email. 

In earlier disclosures, these were mostly J's and K's. I suppose on our end, we just treat a None as a J?

**Comment by flooie** [comment]
I dont think so.  I think the judge just decided not to use the drop down or make a choice.

**Comment by flooie** [comment]
I suppose I understand coding None to the credit cards. You are acknowledging you have monthly debt but that it is paid off every month so you dont carry it over?  But if the student loan is none - why add it to the list of debts?

**Comment by mlissner** [comment]
Yeah, the student loan was a `J` before. I can only imagine it went downward....

**Comment by flooie** [comment]
thats a fair point.

**Comment by mlissner** [comment]
Can you please confirm whether this is still an issue, @flooie?

**Comment by flooie** [comment]
@mlissner 

I checked.. we had 149 disclosures in which the judge filled out a debt but listed it as None for value code.  This ... isn't a value but was being correctly parsed by disclosure extractor.  In actuality we should just set the value to blank or "" in the import.  

I've update the 149 debts see below and a PR to modify the importer is coming shortly.


> 8953: Suzanne H. Bauknight 2019
> 8857: Cynthia A. Norton 2019
> 8857: Cynthia A. Norton 2019
> 8857: Cynthia A. Norton 2019
> 8857: Cynthia A. Norton 2019
> 9465: Jonathan D. Greenberg 2019
> 9465: Jonathan D. Greenberg 2019
> 807: Edward John Davila 2019
> 807: Edward John Davila 2019
> 807: Edward John Davila 2019
> 2218: Salvador Mendoza Jr. 2019
> 8906: Sean H. Lane 2019
> 8791: Carol A. Doyle 2019
> 1446: Susan Owens Hickey 2019
> 1446: Susan Owens Hickey 2019
> 1446: Susan Owens Hickey 2019
> 8901: Robert E. Littlefield Jr. 2019
> 9155: Monte C. Richardson 2019
> 9155: Monte C. Richardson 2019
> 8751: Karen K. Specie 2019
> 8751: Karen K. Specie 2019
> 8764: Paul M. Baisier 2019
> 8589: Timothy James Kelly 2019
> 8651: Allen Cothrel Winsor 2019
> 14427: Patricia A. Donahue 2019
> 14427: Patricia A. Donahue 2019
> 8764: Paul M. Baisier 2018
> 706: Robert James Conrad Jr. 2019
> 9132: Robert M. Spector 2018
> 701: Christopher C. Conner 2018
> 701: Christopher C. Conner 2018
> 701: Christopher C. Conner 2018
> 8740: Christopher Sontchi 2019
> 9115: James M. Candelaria 2019
> 9612: Brooke C. Wells 2020
> 9612: Brooke C. Wells 2020
> 9612: Brooke C. Wells 2020
> 9379: Ann Marie Donio 2019
> 9523: Marcos E. Lopez 2019
> 9401: Kevin R. Sweazea 2020
> 8753: Scott M. Grossman 2020
> 8753: Scott M. Grossman 2020
> 44: Leslie Joyce Abrams 2020
> 9334: David D. Noce 2019
> 9334: David D. Noce 2019
> 9334: David D. Noce 2019
> 9334: David D. Noce 2019
> 9334: David D. Noce 2019
> 9635: Michelle L. Peterson 2019
> 1323: Madeline Hughes Haikala 2019
> 8937: Patricia M. Mayer 2020
> 9086: Jacquelyn Scott Corley 2019
> 9086: Jacquelyn Scott Corley 2019
> 1518: Mark Raymond Hornak 2019
> 553: David O. Carter 2020
> 553: David O. Carter 2020
> 553: David O. Carter 2020
> 553: David O. Carter 2020
> 9122: Scott T. Varholak 2019
> 9257: Angel D. Mitchell 2020
> 1577: Andrew David Hurwitz 2019
> 208: Deborah A. Batts 2018
> 2403: Jacqueline Hong-Ngoc Nguyen 2019
> 706: Robert James Conrad Jr. 2020
> 9648: Peter A. Oppeneer 2020
> 349: Christopher A. Boyko 2019
> 9334: David D. Noce 2020
> 9334: David D. Noce 2020
> 9334: David D. Noce 2020
> 9334: David D. Noce 2020
> 9334: David D. Noce 2020
> 8623: Peter Joseph Phipps 2020
> 8623: Peter Joseph Phipps 2020
> 8623: Peter Joseph Phipps 2020
> 8623: Peter Joseph Phipps 2020
> 8623: Peter Joseph Phipps 2020
> 9600: Ronald C. Griffin 2019
> 9465: Jonathan D. Greenberg 2020
> 9465: Jonathan D. Greenberg 2020
> 9465: Jonathan D. Greenberg 2020
> 9269: Dana Marie Douglas 2019
> 8843: Thomas J. Tucker 2020
> 8953: Suzanne H. Bauknight 2018
> 14415: Steven Daniel Grimberg 2019
> 9148: Embry J. Kidd 2020
> 8634: Tilman Eugene Self III 2019
> 8634: Tilman Eugene Self III 2019
> 8634: Tilman Eugene Self III 2019
> 8634: Tilman Eugene Self III 2019
> 8634: Tilman Eugene Self III 2019
> 2686: Carlton Wayne Reeves 2018
> 3473: Robert Leon Wilkins 2019
> 3473: Robert Leon Wilkins 2019
> 8620: Michael Hun Park 2020
> 9631: David W. Christel 2019
> 9631: David W. Christel 2019
> 9631: David W. Christel 2019
> 9011: Scott Oravec 2019
> 8840: Maria L. Oxholm 2019
> 9612: Brooke C. Wells 2019
> 9612: Brooke C. Wells 2019
> 9612: Brooke C. Wells 2019
> 8811: Tracey N. Wise 2019
> 9587: Dena Palermo 2019
> 8953: Suzanne H. Bauknight 2020
> 9359: Kimberly A. Swank 2019
> 2090: Haldane Robert Mayer 2020
> 2090: Haldane Robert Mayer 2020
> 2090: Haldane Robert Mayer 2020
> 2090: Haldane Robert Mayer 2019
> 2090: Haldane Robert Mayer 2019
> 9257: Angel D. Mitchell 2019
> 9257: Angel D. Mitchell 2019
> 9257: Angel D. Mitchell 2019
> 9257: Angel D. Mitchell 2019
> 2635: Jill Anne Pryor 2019
> 2635: Jill Anne Pryor 2019
> 1150: Marina Garcia Marmolejo 2020
> 1150: Marina Garcia Marmolejo 2020
> 8751: Karen K. Specie 2018
> 9038: Bruce Gordon MacDonald 2019
> 2766: Yvonne Gonzalez Rogers 2019
> 8753: Scott M. Grossman 2019
> 8753: Scott M. Grossman 2019
> 8753: Scott M. Grossman 2019
> 8609: Ryan Douglas Nelson 2019
> 8609: Ryan Douglas Nelson 2019
> 8609: Ryan Douglas Nelson 2019
> 9358: Robert T. Numbers II 2019
> 9358: Robert T. Numbers II 2019
> 9132: Robert M. Spector 2020
> 181: Mark Allen Barnett 2019
> 9386: Zahid Nisar Quraishi 2020
> 2872: Robert William Schroeder III 2019
> 1150: Marina Garcia Marmolejo 2019
> 1150: Marina Garcia Marmolejo 2019
> 9732: Travis A. Greaves 2020
> 2484: Halil Suleyman Ozerden 2019
> 2484: Halil Suleyman Ozerden 2019
> 9167: Elizabeth Timothy 2019
> 9167: Elizabeth Timothy 2019
> 9439: James L. Cott 2019
> 9132: Robert M. Spector 2019
> 553: David O. Carter 2019
> 553: David O. Carter 2019
> 553: David O. Carter 2019
> 553: David O. Carter 2019
> 9589: Sam S. Sheldon 2019
> 701: Christopher C. Conner 2019
