### ISSUE TITLE
Develop a help page for adding recap.email address to PACER accounts

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1928]
This one shouldn't be too hard, I think, but we'll need help to get it right since we don't have a filing account. Right now the best instructions we have for setting up @recap.email is actually from the AO:

https://www.dcd.uscourts.gov/sites/dcd/files/2016_Utilities_Menu.pdf#page=4

I'll take a stab at rewriting those into a Google doc (eventually), and then we can convert that to an HTML page once we're happy with it.

**Comment by mlissner** [comment]
The help page should live at `/help/recap/email/`, I think.

**Comment by albertisfu** [comment]
Perfect, I'll starting creating this new page based on other existing Courtlistener help pages, once we have the content we can replace it.

**Comment by mlissner** [comment]
OK, here's a first draft! 

https://docs.google.com/document/d/1CXlFnrft-NM7A9Skn7he6-q4wLocFv2uq9tsJ_Z_i0o/edit?usp=sharing

Thank you, Alberto! Let me know what questions you have.

**Comment by albertisfu** [comment]
@mlissner here is the first version of the page, let me know if there are any changes
