### ISSUE TITLE
Group similar parentheticals for the same case

### ISSUE THREAD

**Issue by ProbablyFaiz** [freelawproject/courtlistener#1931]
## The problem
Parenthetical summaries in CourtListener have recently entered beta. One of the major observations thus far has been that for opinions with many summaries (see, e.g., [*Twombly*](https://www.courtlistener.com/opinion/145730/bell-atlantic-corp-v-twombly/summaries/)), many are either identical or extremely similar to each other. This is natural; many important cases are used repeatedly for similar purposes. But from a user's standpoint, it doesn't help much to show her functionally the same thing over and over, particularly on the opinion sidebar display, where we're space-limited.

So we're presented with the following questions: how do we (a) avoid showing the user repetitive parentheticals and (b) identify those parentheticals that are the most representative of the full set for a given case?

## Proposed algorithm
To address these issues, I propose the following performant algorithm. This approach has two major benefits: it will allow us to group similar parentheticals for each case, and it will allow us to identify those parentheticals that best represent a consensus "general summary" of the case.

1. Tokenize each parenthetical, stemming words and removing stop words. The list of tokens for each parenthetical will act as its representation for purposes of similarity, so that we are able to capture not just overlap in words between parentheticals but also that the ordering of said words are roughly similar.
2.  Use a [locality-sensitive hashing algorithm](https://www.pinecone.io/learn/locality-sensitive-hashing/) to create an efficient index of these bigram lists.
3. For each parenthetical, use the LSH index to query other parentheticals above a certain minimum similarity threshold. Treat these similarity relationships as edges of a graph.
4. Compute all of the [connected components](https://en.wikipedia.org/wiki/Component_(graph_theory)) of our graph. These will be our clusters, or "groups".

    (This assumes similarity is a transitive property such that if A is similar to B and B is similar to C, then A is similar to C. That should be close enough to the truth, but if we want to be stricter, we can instead compute the graph's [cliques](https://en.wikipedia.org/wiki/Clique_(graph_theory)), such that all nodes in a cluster must be connected directly to every other node. This will be less efficient though, and will probably lead to more fragmentation than we want.)

5. Assign each cluster a score equal to the maximum descriptiveness score among the parentheticals contained therein. Multiply this score by. the proportion of total parentheticals contained within the cluster. This gives extra credence to statements of the case that are repeated in similar form many times over, because that would tend to indicate that that text is the best general summary of a case.

6. From the top 20% highest-scored parentheticals in a cluster, choose the parenthetical with the most neighbors in the similarity graph as the "representative" of the cluster. This ensures we pick a parenthetical to display first for the cluster that is both high quality and an accurate depiction of the cluster as a whole.

## Dependencies
- [datasketch](https://github.com/ekzhu/datasketch) - This library is fairly popular and contains an efficient implementation of the LSH index that will make this whole thing work
- [nltk](https://www.nltk.org/) (optional) - For tokenizing parenthetical text and creating bigrams for it. We can hand-roll this functionality if we need to but the nltk implementations would be much more robust and give us greater flexibility down the line to tinker with this algorithm

## Discussion questions
- What is the best time and place to compute these?
    - Should we store these groupings in the database and update them each time parentheticals for a case are added or updated?
    - Should we compute them for a given case when a user requests them (most likely using caching to avoid doing this over and over)?
- What does the user interface for these groupings look like?
    - On the sidebar of the opinion page?
    - On the standalone summaries page?
- Does this provide sufficient value to users to be worth the effort?

**Comment by ProbablyFaiz** [comment]
```
Holding that an ineffective assistance claim requires establishing (1) “that counsel’s performance was deficient” and (2) “that the deficient performance prejudiced the defense” - 74
Requiring courts to make “every effort . . . to eliminate the distorting effects of hindsight” - 5
“[A] verdict or conclusion only weakly supported by the record is more likely to have been affected by errors than one with overwhelming record support.” - 4
Holding that the defendant must overcome strong presumption that failure to object might be considered sound trial strategy - 3
Distinguishing errors that have an “isolated, trivial” effect and do not affect factual findings from those that have a pervasive effect that therefore result in a “breakdown in the adversarial process” - 2
```

**Comment by mlissner** [comment]
Very interesting. I was thinking that simple highest-ranked parenthetical in a cluster would probably be OK, but I'm guessing you're experimenting to see what comes out best. Love it.

**Comment by ProbablyFaiz** [comment]
> Expounding on ideas for how to make the adjustments to scores based on the clustering results:

Approaches we settled on ended up being slightly different. Steps 5 and 6 of the original issue have been updated to reflect them
