### ISSUE TITLE
Remove seal rookery from CourtListener

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1943]
As we're working on the AWS migration, we're finding that seal rookery and judge pics add a lot of dumb complication. The product benefit from judge-pics is real, but as discussed in #1940, we dont' get much value from the seals at all. 

Let's remove it completely from CourtListener. I think that means:

1. Yanking it from Docker
2. Yanking it from BTE where we use it to put seals into the metadata for mp3s.
3. That's it?

With that done, we can never think about seals again, which is good.

**Comment by mlissner** [comment]
Here's a fun one to think about: If you look in cl.audio.feeds, you'll see that we reference the seals. That one got away from us! 

I think we could easily fix this once it launches by tweaking the links to point to seals.free.law/whatever.

**Comment by flooie** [comment]
Completed.

**Comment by mlissner** [comment]
Not quite. It's still in `cl.audio.feeds`, but I'm working on that.

**Comment by mlissner** [comment]
I was wrong, the feeds didn't use the seals, they use custom images stored in static files in CL. Great. Done.

**Comment by flooie** [comment]
√.
