### ISSUE TITLE
Study how to thread messages in various clients

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#1972]
As part of SES migration we want to check if it's possible to thread email notifications for similar content,  for example, thread docket alerts that belong to the same case e.g:

0 New Docket Entries for Town of Greece v. Galloway (24-fg-05473)
1  New Docket Entries for Town of Greece v. Galloway (24-fg-05473)

We want them to be part of the same thread.

Doing some tests about this I've found the following:

- Right now docket alert messages even with the same Subject are not getting threaded because we are using `X-Entity-Ref-ID` header that prevents messages to get threaded, so is necessary to eliminate this header as the first step to thread messages with the same subject e.g:
12 New Docket Entries for Town of Greece v. Galloway (24-fg-05473)
12  New Docket Entries for Town of Greece v. Galloway (24-fg-05473)

With this change in Gmail messages get threaded:
![screen_1](https://user-images.githubusercontent.com/486004/158848518-aabf7e90-38a9-427d-8f99-68408949e898.png)

However, in Outlook this is not enough, messages with the same subject and  without `X-Entity-Ref-ID` header are not getting threaded:
![screen_2](https://user-images.githubusercontent.com/486004/158848908-25667c35-d2f6-4fbb-b5ea-4f496241ca0f.png)

To thread messages in Outlook additionally is necessary to add `References` and `In-Reply-To` headers referring to a previous email and it works as long as the subject is the same if not the new email starts a new thread:

![screen_3](https://user-images.githubusercontent.com/486004/158849920-0d6092bc-095a-41d8-8b5b-3359e1518a32.png)

- The problem in a Docket alert is the subject, when counter changes it’s considered a new thread, for example:
14 New Docket Entries for Town of Greece v. Galloway (24-fg-05473)
15  New Docket Entries for Town of Greece v. Galloway (24-fg-05473)

![screen_4](https://user-images.githubusercontent.com/486004/158850287-36c0bd56-2727-4d14-823d-8bd00ee508ba.png)

- I tried adding `References` and `In-Reply-To` headers referring to a previous email to force thread emails with different subjects and it doesn't work if the subject is not the same, this applies for Gmail and Outlook:

![screen_5](https://user-images.githubusercontent.com/486004/158851231-6bbe26b2-95df-401f-9ab0-9a286417e26e.png)

![screen_6](https://user-images.githubusercontent.com/486004/158851340-46dbd3f5-254d-4e2a-a7be-3a3d12f78675.png)

- There are some prefixes like Fwd: that are allowed in the subject and message is still considered part of the same thread e.g:
18 New Docket Entries for Town of Greece v. Galloway (24-fg-05473)
Fwd: 18 New Docket Entries for Town of Greece v. Galloway (24-fg-05473)

However, if any content after the prefix changes is considered a new thread.

Summary of findings so far:
- As long as we use different subjects e.g. when the counter changes in a docket alert we aren’t going to be able to thread messages for a Case.
- In Gmail is not necessary to add additional headers to thread messages, as long as subjects are the same.
- In Outlook we need to add `References` and `In-Reply-To` headers referring to a previous email to force to get messages threaded, as long as subjects are the same, if we took this approach we would need to store the message-id (that SES returns when we send the message) for the first case alert we sent to a user and then when we need to send another case alert for that specific case and user we should use that message-id to add in headers.

**Comment by mlissner** [comment]
This is great analysis and good to know what's actually happening out there, thanks Alberto. One question:

> if we took this approach we would need to store the message-id (that SES returns when we send the message) for the first case alert we sent to a user and then when we need to send another case alert for that specific case and user we should use that message-id to add in headers.

Why do we need to capture the message-id of the original message? Can't we just set the message-id to something we like? For example:

    docket-alert-$docket_id

Couldn't we do that on the first message and then every message after that?

**Comment by albertisfu** [comment]
I did this test, the problem seems to be that we can't set the `Message-ID` because this is set directly by SES.

I tried to set with the `docket_id`:
![screen_1](https://user-images.githubusercontent.com/486004/158891749-dd40222d-a022-417d-a758-b5c65d4db689.png)

Inspecting the received email we can see that this header is overwritten by SES:
![screen_2](https://user-images.githubusercontent.com/486004/158891844-a5f64665-edce-4440-98cf-ae2eb9ed6918.png)

**Comment by mlissner** [comment]
OK, right, but now that we know SES sets the message ID, we still can't send it on the second message, right? So there's no point in storing it?

**Comment by albertisfu** [comment]
I think we could store the message-ID that we receive from SES for a case message to append to `References` and `In-Reply-To` headers in future emails for the same case and email address because we can set these headers, this would be useful when we send messages to Outlook/Office 365 addresses since we need to set them in order to get messages threaded even if they have the same subject in counterpart with Gmail where is not needed set these headers if subjects are the same.

It seems there is another problem to consider, there is a limit with the number of messages in a thread, this limit in [Gmail are 100 messages ](https://support.google.com/mail/answer/5900?hl=en&co=GENIE.Platform%3DDesktop), I couldn't find this limit for Outlook/Office 365, so we also should consider storing a counter for each case/email address in order to update the Message-ID  in `References` and `In-Reply-To` headers in order to start a new thread.

**Comment by mlissner** [comment]
Oh, I get it. You need to get the message-id from the first message and then reply with that in the references and in-reply-to headers of the next ones. Bummer, that does add a bit of complication. Do you think it's worth it just to support Outlook?

>  There is a limit with the number of messages in a thread

I've actually hit this before. It's fine. It just means you get a fresh thread when the 101st email comes in. It doesn't get dropped or something.

**Comment by albertisfu** [comment]
oh well, if we are going to change email subjects to be the same in every case message I think it could be worth it in order to support also threads in Outlook and maybe other email clients that also need those headers to get messages threaded.

Or we can also add this feature later.

**Comment by mlissner** [comment]
> Or we can also add this feature later.

I think you'll know better if this makes sense to do now or later. I've lost the thread a bit on how complicated this feature is. What do you think?

**Comment by mlissner** [comment]
Thinking about this again, I think we should prioritize other tasks. I'm afraid that if we thread messages, Gmail will do that thing where it hides the parts of the message that are repeated, which would be pretty annoying. Maybe it's worth experimenting with this later, but for now I think it's best to wait until after launch.

**Comment by mlissner** [comment]
I'm going to close this. The two reasons this won't work are:
 - We want to tweak the subject lines so they're different. That breaks threading.
 - Google hides parts of emails when they're threaded, which sucks.
