### ISSUE TITLE
Create an admin action to seal RECAP Documents

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1973]
I do this manually now, but it's a real pain. It'd be much better to do it automatically with an admin action. They're really easy to write and we should use them more, probably:

https://docs.djangoproject.com/en/4.0/ref/contrib/admin/actions/

The general process is to delete the PDF from S3, yank it from Internet Archive, and zero-out a bunch of fields.

**Comment by nemobis** [comment]
> yank it from Internet Archive

Do you use make_dark or actually delete the files?

**Comment by nemobis** [comment]
Il 24/03/22 19:08, Mike Lissner ha scritto:
> We actually delete them. I didn't think that we had permissions to mark them as dark.

You should have, or at least it should not be too hard to get the 
permission.

**Comment by mlissner** [comment]
What's the advantage? I'm not sure I care too much one way or another. I definitely don't care enough to do the work of figuring it out, but if there was an advantage and somebody wanted to implement it, I wouldn't oppose.
