### ISSUE TITLE
Avoid downloading PACER documents if they don't have a non-zero price tag on the receipt page.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#1975]
When retrieving PACER documents from RECAP email we have to consider that if we land on a receipt page we need to check that price is zero before trying to download the document in order to avoid purchasing documents.

To do this we a scraper in Juriscraper to scraper receipt pages.

**Comment by mlissner** [comment]
If we use magic links, there's no login and it's safe. We dont' need to do this after all. Great.
