### ISSUE TITLE
Update Dockerfiles of Court Listener services

### ISSUE THREAD

**Issue by kalki-e-datamatics** [freelawproject/courtlistener#1979]
# Goal
* The python code required for the container to run should be packed within the container image
* Optimizing the instructions in Dockerfile such that the caching can be leveraged during build

# Services
## Django
 [Dockerfile](https://github.com/freelawproject/courtlistener/blob/main/docker/django/Dockerfile)
* The source code is mounted [here](https://github.com/freelawproject/courtlistener/blob/main/docker/django/Dockerfile#L77) rather than copying it into the image during the build process
  * After L77 would be the best place to copy the source code into the image
* [This line](https://github.com/freelawproject/courtlistener/blob/main/docker/django/Dockerfile#L71) does not reduce the image size because those packages are already there in the underlying docker layers.
  * A tradeoff between the image size and build duration should be done here.
  * `poetry install` needs poetry.lock files & gcc to be available in image.
  * To reduce image size
    * L64 can be moved to L36 and L37 to L74 can be merged to one single docker run instruction
    * Build duration will be increased when the poetry.lock / pyproject.toml file is changed i.e., whenever these files are changed, the following installation instructions would be ran again and again and thereby increasing the time to complete the build
    * One option is, all packages excpet the ones that are uninstalled at L72 & L73 can be kept before copying the poetry.lock files can reduce the build duration to some extent
  * To reduce build duration
    * Remove L71 since it has no benefit
    * Merge L67 & L68
* Having a separate stage just for ENVs does not make sense. So better to remove L35
* Rather than passing the following large CMDs while creating containers, they can be put in a simple script file which accepts arguments. Based on the arguments, the appropriate command will be executed. 
  * [cl-python](https://github.com/freelawproject/courtlistener/blob/main/docker/nginx/docker-compose.yml#L27) e.g., `./run.sh --web` 
  * [cl-scrape-rss](https://github.com/freelawproject/courtlistener/blob/main/docker/nginx/docker-compose.yml#L54) e.g., `./run.sh --scrape-rss`
  * [cl-ia-recap-uploader](https://github.com/freelawproject/courtlistener/blob/main/docker/nginx/docker-compose.yml#L70) e.g., `./run.sh --ia-recap-uploader`

## Celery
[Dockerfile](https://github.com/freelawproject/courtlistener/blob/main/docker/task-server/Dockerfile)
* Like Django, the large CMDs can be put in a simple script file which accepts arguments. Based on the arguments, the appropriate command will be executed. 
  * [celery_prefork](https://github.com/freelawproject/courtlistener/blob/main/docker/task-server/docker-compose.yml#L32) e.g., `./run.sh --celery`
  * [celery_prefork_bulk](https://github.com/freelawproject/courtlistener/blob/main/docker/task-server/docker-compose.yml#L65) e.g., `./run.sh --celery-bulk`

## Disclosures
[Dockerfile](https://github.com/freelawproject/disclosures/blob/main/docker/Dockerfile)
* L3 to L28 can be combined into one single RUN statement
* wget, unzip & bc on L4 are does not seem to be used anywhere since they are uninstalled at L28
* Is nginx needed here?

## Doctor
[Dockerfile](https://github.com/freelawproject/doctor/blob/main/docker/Dockerfile)
* L3 to L28 can be combined into one single RUN statement
* Is nginx needed here?

**Comment by flooie** [comment]
Nginx is needed for disclosure and doctor.

**Comment by kalki-e-datamatics** [comment]
I see that Nginx is just used to proxy the Gunicorn servers.
Also I assume they are only consumed by other services running locally, not the users from the internet.

So adding this additional package and a proxy layer, Is it beneficial?

**Comment by flooie** [comment]
I'm sure it'll be easy as 1..2..3.

**Comment by kalki-e-datamatics** [comment]
@mlissner 
Gunicorn is called as application server and Nginx is called as Web server.
For typical web applications with 3-tier architecture, both would be needed.
A quick reference [here](https://www.nginx.com/resources/glossary/application-server-vs-web-server/).

The role of application server is to
* understand the parse the incoming HTTP request,
* pass on the context to the programming runtime,*
* let the business logic run,
* construct the response
* and send it back from where the request came.

Whereas the web servers are
* optimized to serve static content such as images, media, etc. more efficiently
* optionally can compress the response like gzip, deflate, etc
* good at proxying, routing and load balancing
* has security layers built-in to it
* provides SSL termination
* able to serve handle thousands of requests

More on Nginx,
> Nginx uses the [Reactor](http://en.wikipedia.org/wiki/Reactor_pattern) pattern. Basically, it's single-threaded (but can fork several processes to utilize multiple cores). The main event loop waits for the OS to signal a readiness event - e.g. that data is available to read from a socket, at which point it is read into a buffer and processed. The single thread can very efficiently serve tens of thousands of simultaneous connections (the thread-per-connection model would fail at this because of the huge context-switching overhead, as well as the large memory consumption, as each thread needs its own stack).

Due to its [non-blocking asynchronous nature](https://www.nginx.com/blog/thread-pools-boost-performance-9x/), Nginx can accept & send the requests to backend and still do its work instead of being idle while the backend is still processing.


**In our scenario, I assume Doctor and Disclosures are just exposing RESTful APIs (not any heavy static content) to the other microservices running within the cluster (not exposed to the users on the internet). So if my above assumption is right, I suggest to remove the Nginx from the stack.**

**Similarly, the Nginx is not needed for Django web app with Gunicorn since AWS Application Load Balancer is going to reverse proxy them and the Django static assets are served from S3. Please confirm this.**

**Comment by mlissner** [comment]
Fantastic analysis, Kalki, thank you. Yes, @flooie is going to remove nginx from the Doctor and Disclosure images. That'll be great, thanks.

For the Django image, it runs using the following command in the DockerFile:

    CMD python /opt/courtlistener/manage.py runserver 0.0.0.0:8000

That doesn't perform and isn't secure, but it's what's used for development. For production, the docker compose overwrites that command to run gunicorn:

```txt
    command: >
      bash -c "gunicorn cl_wsgi:application \
        --chdir /opt/courtlistener/docker/nginx/wsgi-configs/ \
        --user www-data \
        --group www-data \
        `# Set high number of workers. Docs recommend 2-4× core count` \
        --workers ${NUM_WORKERS:-48} \
        `# Allow longer queries to solr.` \
        --limit-request-line 6000 \
        `# Reset each worker once in a while` \
        --max-requests 10000 \
        --max-requests-jitter 100 \
        --timeout 180 \
        --bind 0.0.0.0:8000"
```

There's a separate nginx image that we maintain that is an optimized nginx installation. It has a config file [here](https://github.com/freelawproject/courtlistener/blob/c7a1eb544cabbc86ec50779a9c6a4e8e0de08737/docker/nginx/nginx.conf). The particularly important settings I see in there are:

We need this because we get big uploads from users:

```
    # This is the max upload size, default is 1M.
    client_max_body_size 256M;
```

Our SSL is highly optimized for security (we get [an A+ rating](https://www.ssllabs.com/ssltest/analyze.html?d=www.courtlistener.com&hideResults=on):
```
    # Diffie-Hellman parameter for DHE ciphersuites. Downloaded from Mozilla
    # configurator (according to their instructions).
    ssl_dhparam          /etc/nginx/includes/dhparam2048.pem;

    # Mozilla Intermediate configuration
    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_ciphers          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

    # OCSP Stapling
    ssl_stapling         on;
    ssl_stapling_verify  on;
    resolver             1.1.1.1 1.0.0.1 8.8.8.8 8.8.4.4 208.67.222.222 208.67.220.220 valid=60s;
    resolver_timeout     2s
```

And:

```
# security headers
add_header Referrer-Policy         "same-origin" always;
add_header X-XSS-Protection        "1; mode=block" always;
add_header X-Content-Type-Options  "nosniff" always;

# HSTS
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
```

----

There's also a "sites-enabled" [configuration file](https://github.com/freelawproject/courtlistener/blob/e8afee31435016eecbe9e94c57023465f81d2b43/docker/nginx/sites-available/courtlistener.com.conf) for CourtListener.com. It's worth going through it and making sure we still support what's in there, if necessary. I made an annotated version of it here, with some notes on which features are important:

https://gist.github.com/mlissner/cbd98a2baf87532c5d713e124fbfaee9

**Comment by mlissner** [comment]
@flooie, when you get back to this, we'll want to address all of Kalki's suggestions, but summarizing a bunch of conversation that I minimized above, and in priority order:

 - [ ] The top priority is to get django and celery images released with the latest commit in them. Talking to Kalki today, I confirmed that the way to do this is to put the latest commit in the usual place we mount it. Then, when we deploy, the code is there. When we do dev, we just mount on top of that location (like we do now).
 - [ ] Remove nginx from doctor and disclosures
 - [ ] Optimize the django image per Kalki's suggestions above

**Comment by flooie** [comment]
@mlissner @kalki-e-datamatics 

So I've removed nginx from them and I think I have combined the lines together.  wget etc is used in the shell script in the Mac specific install-pdf script.

**Comment by flooie** [comment]
@mlissner I'll get back to you on the top priority.

**Comment by flooie** [comment]
@kalki-e-datamatics 

How do we architect our private settings here with Kubernetes?

**Comment by mlissner** [comment]
> How do we architect our private settings here with Kubernetes?

I'll expand a bit on that. 

Right now, all of our systems have two or more files, like:

- 05-private.py
- 10-public.py
- 11-private.py

The idea is that these files have all of our Django settings in them, and they're read in numerical order, with each file overriding the one before. In production, this means that we put private settings in 05-private.py (which is not in git), and we have public settings in 10-public.py. Normally that's all we need, but sometimes you have to override 10-public.py, so you can make an 11-private.py or 50-private.py or whatever, and that'll be read last and override the 10-public.py file.

Where we are lost is that currently we mount these files into the docker image. This works really well, but if we're packaging the code into the docker image, we won't be mounting it anymore. So how do we get these settings into the docker image? 

I think the answer is probably to use environment variables that get passed from an `.env` file to the kubernetes manifest to the docker image, but we're not sure. 

Can you give advice about the best way to get private and public settings into an image in the k8s world?

**Comment by kalki-e-datamatics** [comment]
Though the most preferred way to pass on the configuration is through environment variables, I do understand that the environment variables can have only key-value pairs and this is limiting.

With these Django settings files like 10-public.py & 11-private.py, we can have complex nested Data types in python to store and retrieve the configuration as needed.

In Kubernetes, we can make use of "config map" resources to contain all the Django settings file and this config map can be mounted as a volume in your application containers.

* [This is](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume) how the config map would look like. In your case
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: court-listener-config
data:
  10-public.py: |
    PLAUSIBLE_API_URL = "https://plausible.io/api/v1/stats/breakdown"
  11-private.py: |
    PLAUSIBLE_API_URL = "https://plausible.io/api/v2/stats/breakdown"
```
* Such yaml file can be easily created with [a kubectl command](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#create-configmaps-from-directories).
* Once created, they can be mounted inside the container [like this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap).
* A important point to note is that all the files in the directory where we mount the config map will be cleared. So, any configuration file we need, should be part of the config map.

**Comment by mlissner** [comment]
This is done enough for now, with new docker files and compose files deployed last night. 

I think there's optimization that could be done here. For example, poetry installs the dependencies just about every time, but I'm not sure how to get that fixed and it's not the end of the world.

If anybody wants to take a look, the consolidated docker file for django and celery is here: https://github.com/freelawproject/courtlistener/blob/main/docker/django/Dockerfile
