### ISSUE TITLE
Figure out future of bulk data files

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#1983]
Right now they're generated on disk as millions of JSON files, then zipped up, and finally, the zip file is swapped in for the old one that used to be in nginx. It'd be nice to serve these from S3 instead, but the "zipped up" part is hard if you do that.

S3 is pretty easy to copy from using lots of simple tools, and I think it's reasonable to ask people to download millions of JSON files from S3 instead of bundled zip files. At the end of the day, they want JSON files anyway, not zips. It also makes it a LOT easier for us to generate bulk data. Instead of doing things like making zips and swapping old zips for new ones, we just send the JSON to S3 and replace the version that was there before. 

The other thing to do with this is to make sure we make our generation process resumable. If it crashes, it needs to know where it last was and pick up from that point.

**Comment by mlissner** [comment]
I don't think we'll get this done before moving to AWS, and I think our bulk data may be down until it's done. We'll see if people gripe, I suppose.

**Comment by mlissner** [comment]
@flooie, could you put a small warning on the bulk data page pointing to this issue and apologizing for the outage, so we get fewer questions?

**Comment by flooie** [comment]
Is this harder than it looks

**Comment by mlissner** [comment]
Putting the warning or doing the bulk files?

**Comment by mlissner** [comment]
Nothing hard about the warning that I can imagine. I want to redo the bulk generation though.

**Comment by mlissner** [comment]
Thinking of using this to dump tables instead of generating json: https://www.postgresql.org/docs/current/sql-copy.html

**Comment by flooie** [comment]
I meant dumping.

**Comment by eltrompetero** [comment]
Hi, I was asking about the bulk data dump in another duplicate thread. Glad to see that this is in the works.

In the meantime, would it be possible to get a copy of the old scotus bulk dump linked somewhere? I'm trying to get an intern started on a project.

Much appreciated.

**Comment by flooie** [comment]
I tested something locally, (and consider this an abbreviated version), but assuming someone just needs a JSON export of the search table for all scotus opinions we could do something like this 

```
import logging

from django.core.management import BaseCommand, call_command

from cl.search.models import Docket, OpinionCluster, Opinion

logger = logging.getLogger(__name__)

class Command(BaseCommand):
    def __init__(self, stdout=None, stderr=None, no_color=False):
        super().__init__(stdout, stderr, no_color)
        self.settings = None

    @property
    def tmp_dir(self):
        return '/storage'

    def handle(self, *args, **options):
        self.settings = options.get('settings')

        docket_ids = Docket.objects.filter(court='scotus').values_list('pk', flat=True)
        docket_ids = [str(id) for id in docket_ids]
        self.dump_objects('search.Docket', pks=docket_ids)

        cluster_ids = OpinionCluster.objects.filter(docket__id__in=docket_ids).values_list('pk', flat=True)
        cluster_ids = [str(id) for id in cluster_ids]
        self.dump_objects('search.OpinionCluster', pks=cluster_ids)

        opinion_ids = Opinion.objects.filter(cluster__id__in=cluster_ids).values_list('pk', flat=True)
        opinion_ids = [str(id) for id in opinion_ids]
        self.dump_objects('search.Opinion', pks=opinion_ids)

    def dump_objects(self, model_name: str, pks: list):
        if pks:
            print(",".join(pks))
            call_command('dumpdata', model_name,
                         '--pks', ','.join(pks),
                         '--indent', '2',
                         '-o', f'{self.tmp_dir}/{model_name}.json',
                         '--settings', self.settings)
        else:
            logger.warning('No objects for model {} found'.format(model_name))
```

It's relatively easy to do a dump with the PKs, but I'm somewhat concerned about it generating huge files for a court like scotus.

**Comment by flooie** [comment]
What are you looking for at a minimum @eltrompetero ?

**Comment by eltrompetero** [comment]
Thanks for the quick response. 

I was hoping to get the texts of all SCOTUS opinions from 1946 onwards with sufficient case info to merge with SCDB, which is something you have but we can also do that separately easily.

**Comment by mlissner** [comment]
As of Django 3.2, jsonl is a valid serialization format, so that could
solve the big file problem:

https://docs.djangoproject.com/en/3.2/topics/serialization/#serialization-formats

Those queries might be nasty is prod, but hopefully they'll be ok. Instead
of checking this in, I'd suggest just copy/pasting it to the maintenance
node.

If you make this file, you should be able to put it in our public bucket.

Let's just not make a habit of making files this way. It can become a very
big distraction based on the number of people looking at bulk data this
week. I don't want to disappoint people, but if we spend our time doing
one-offs, we don't have time to fix underlying problems.

The API serves the same data as the old bulk data files, so we can just
direct people there until we have a solution we like.

**Comment by KutsOleksii** [comment]
Hi guys. Is it possible to change default settings of Django REST framework in your API section? For now I'm able to get only 100 first pages with 20 records per page. It is very hard to get needed data from dockets and opinions section with such limitation (only 2000 records for the request with certain parameters).
I guess 100 records per page and 1000 pages paginating will be enough for most needs until bulk data comes back.

**Comment by mlissner** [comment]
The trick is to use filters to do your own pagination. For example, filter to everything this month, then paginate through it. Filter to last month and pagnate, etc.

**Comment by knverbeek** [comment]
Are there any updates as to when it's expected that the bulk data will be available again? Thanks for this resource!

**Comment by mlissner** [comment]
> Can you, please, show me an example of API request using range of date

Maybe something like this? The important part is the `__gt`, which is two underscores and then `gt`, for "Greater than":

https://www.courtlistener.com/api/rest/v3/dockets/?date_created__gt=2022-07-14T00:00:00&date_created__lt=2022-07-15T23:59:59

> Are there any updates as to when it's expected that the bulk data will be available again? Thanks for this resource!

We're really resource constrained right now, so I can't really provide an estimate. It pretty much has to get done by me (everybody else is pinned down for the moment), but I'm swamped with a lot of other projects that are launching. 

The only other option is if a volunteer wanted to take a stab at it. If so, the skills are scripting, postgresql, Django, and AWS, I think.

I'm hoping to get to it soon, but if you look at my Backlog column here, you can see what's ahead (not counting day-to-day stuff): https://github.com/orgs/freelawproject/projects/29/views/1

**Comment by mlissner** [comment]
Hi all, I have a question about this project. Please chime in as soon as possible with your opinion in replies.

The new system I am planning will use the postgresql COPY command to dump SQL files into AWS S3. This will give you a simple link to download SQL for a complete table. Something like:

https://storage.courtlistener.com/bulk/courts.sql.gz

You'd download that file, COPY it into your DB and be on your way. 

## Here's the question

Before this all broke, we generated many bulk data files, by jurisdiction. For example, we generated a file for each court and then a combined file for all the courts. As you can imagine, this takes a LOT of time because there's a lot of duplicated work being done. It's one of the reasons bulk files have been hard to fix. That's not great! 

On the other hand, the bulk data is pretty big, so not providing smaller files might be hard for folks:

 - The opinions table (`search_opinion`) is [about 150GB and growing](https://github.com/freelawproject/courtlistener/issues/1406#issuecomment-846291711)
 - The docket table (`search_docket`) is about 17GB without any indexes (but growing rapidly)
 - `search_opinionscited` is 13GB

Here's the question: How important is it to break up the opinions and docket tables into smaller pieces by jurisdiction? I'm leaning towards "it's not worth it," because it's not easy to do (and we're adding a LOT of jurisdictions lately, which would result in many, many files). 

Anyhow, please chime in quickly so I can weigh your thoughts. Read on if you care about the architecture of how I'm building this.


## Some notes on the design (for techies and myself)

I currently have no fewer than 30 tabs open analyzing options for this feature. The general idea is that the COPY command can stream its results, so ideally we don't write them to a temporary file at all, and we instead stream them directly to S3, with a compression step in the middle somewhere.

Something like:

    psql COPY yada yada | bz | s3cmd

Reaching in my tool bag, my usual hammer is Python. Here's where that analysis is at:

What | Notes
-- | --
Stream the COPY command | Seems to [require psycopg3](https://www.psycopg.org/articles/2020/11/15/psycopg3-copy/), which [Django doesn’t yet support](https://github.com/django/django/pull/15687)
Stream compress | Pretty sure I’ve done this at some point
Stream to S3 | Seems doable [using smart_open](https://github.com/RaRe-Technologies/smart_open), which looks neat

So, I think if I use Python, it'll mean writing to disk then uploading, which kind of sucks. Python also isn't that great at streaming things — the ergonomics suck.

The next tool I sometimes reach for is bash. I ~kind of hate~ *really hate* bash, but one thing it's good at is streaming things. We do have our DB connection ENVs these days, so I think in theory I could make this work. Here's where that's at:

Task | Notes
-- | --
Stream COPY command | Yeah, psql will do this and we have it installed.
Stream compress | Sure, probably just sent it as stdin to the `bz` or tar command? Not sure how to set the compression level yet, but that’s probably easy.
Stream to S3 | Can be done with the awscli tools, but installing those takes 250MB of space and is a huge download. Ugh. Looking around, I found some community options: `s3cmd`, `s4cmd`, and yes, `s5cmd`.<br><br> `s5cmd` seems to be the most promising of these (excellent speed; easy install), but it doesn’t support streaming a file to S3 ([yet](https://github.com/peak/s5cmd/issues/182)). That might be something I can [work around](https://unix.stackexchange.com/questions/63923/pseudo-files-for-temporary-data/63933#63933), but I’m not sure.
Monitor errors | If we’re going to use bash, we better have something like Sentry watching for errors. Sure enough, [Sentry works with Bash](https://docs.sentry.io/product/cli/send-event/).

So I think my next steps are to get something streamed from the DB to S3 using bash. If that works, then I'll get it set up as a cronjob using k8s.

**Comment by mlissner** [comment]
Well, here's some timely news. We just got this project sponsored. That'll help finally get it across the finish line. Amazing!

**Comment by mlissner** [comment]
Pull request #1983 has a draft of our new bulk data feature up for review. Hopefully we'll land it soon and without fuss, but we'll see. If anybody wants to take a look at the documentation (and is comfy reading HTML), that'd be great.

**Comment by mlissner** [comment]
This feature is now complete and up and running again. Thank you all for your patience. 

The latest bulk files are now generating. In the future, they'll be re-generated according to the scheduled mentioned in the documentation: 

https://www.courtlistener.com/api/bulk-info/

I suggest reading that documentation if you have been waiting for this feature. 

You can monitor the files that are available here: https://com-courtlistener-storage.s3-us-west-2.amazonaws.com/list.html?prefix=bulk-data/

Sorry again to unceremoniously break this! I'm glad it's finally fixed.

**Comment by yauheni-semashka** [comment]
Hello!
Thank you for the work on moving the data on s3 bucket and making it more accessible!

I've spotted, that new dumps are missing the FJC Integrated Database data, even when it presented in Schema Diagrams and only idb_data_id is presented.

Even this data is accessbe at https://www.fjc.gov/research/idb do you have any plans to include IDB to the bulk-data dumps?

Thanks for the response!

**Comment by mlissner** [comment]
It's not currently planned, no, but I'd welcome a contribution to make it happen. I think it should be easy. Just take a look at #2227 for where to begin and the table to export is:

```

courtlistener=> \d recap_fjcintegrateddatabase
                                                     Table "public.recap_fjcintegrateddatabase"
                 Column                 |           Type           | Collation | Nullable |                         Default                         
----------------------------------------+--------------------------+-----------+----------+---------------------------------------------------------
 id                                     | integer                  |           | not null | nextval('recap_fjcintegrateddatabase_id_seq'::regclass)
 dataset_source                         | smallint                 |           | not null | 
 date_created                           | timestamp with time zone |           | not null | 
 date_modified                          | timestamp with time zone |           | not null | 
 office                                 | character varying(3)     |           | not null | 
 docket_number                          | character varying(7)     |           | not null | 
 origin                                 | smallint                 |           |          | 
 date_filed                             | date                     |           |          | 
 jurisdiction                           | smallint                 |           |          | 
 nature_of_suit                         | integer                  |           |          | 
 title                                  | text                     |           | not null | 
 section                                | character varying(200)   |           | not null | 
 subsection                             | character varying(200)   |           | not null | 
 diversity_of_residence                 | smallint                 |           |          | 
 class_action                           | boolean                  |           |          | 
 monetary_demand                        | integer                  |           |          | 
 county_of_residence                    | integer                  |           |          | 
 arbitration_at_filing                  | character varying(1)     |           | not null | 
 arbitration_at_termination             | character varying(1)     |           | not null | 
 multidistrict_litigation_docket_number | text                     |           | not null | 
 plaintiff                              | text                     |           | not null | 
 defendant                              | text                     |           | not null | 
 date_transfer                          | date                     |           |          | 
 transfer_office                        | character varying(3)     |           | not null | 
 transfer_docket_number                 | text                     |           | not null | 
 transfer_origin                        | text                     |           | not null | 
 date_terminated                        | date                     |           |          | 
 termination_class_action_status        | smallint                 |           |          | 
 procedural_progress                    | smallint                 |           |          | 
 disposition                            | smallint                 |           |          | 
 nature_of_judgement                    | smallint                 |           |          | 
 amount_received                        | integer                  |           |          | 
 judgment                               | smallint                 |           |          | 
 pro_se                                 | smallint                 |           |          | 
 year_of_tape                           | integer                  |           |          | 
 circuit_id                             | character varying(15)    |           |          | 
 district_id                            | character varying(15)    |           |          | 
 nature_of_offense                      | character varying(4)     |           | not null | 
 version                                | integer                  |           |          | 
```

Want to take a stab at it? 

Somebody else also emailed about the financial disclosure tables. If you wanted to go above and beyond, it'd be great to include those too. I could grab the table descriptions if so?

**Comment by yauheni-semashka** [comment]
@mlissner I will be happy to take part when will have some free time during the next week.
I haven't taken a chance to dive into the codebase to check the financial disclosure model. If it's presented in code - I will use it as a reference. If not - could you please provide the table description as well?

**Comment by mlissner** [comment]
Phenomenal! The data models are in the code, yes. See disclosures/models.py for details. The one missing piece is how to convert django models into SQL tables, but that's not too hard. If the model name is `Disclosure()`, and it's in the django disclosure app (as above), then you just lower case it, and it becomes:

    disclosures_disclosure

In other words, it's:

    appname_lowercasedmodelname

e.g.: 

```
search.models.RECAPDocument --> search_recapdocument
alert.models.DocketAlert --> alert_docketalert
```

And so forth. You can see lots of examples in the bash script that generates the bulk data files too. Reopening!

**Comment by Shogun7711** [comment]
> Right now they're generated on disk as millions of JSON files, then zipped up, and finally, the zip file is swapped in for the old one that used to be in nginx. It'd be nice to serve these from S3 instead, but the "zipped up" part is hard if you do that.
> 
> S3 is pretty easy to copy from using lots of simple tools, and I think it's reasonable to ask people to download millions of JSON files from S3 instead of bundled zip files. At the end of the day, they want JSON files anyway, not zips. It also makes it a LOT easier for us to generate bulk data. Instead of doing things like making zips and swapping old zips for new ones, we just send the JSON to S3 and replace the version that was there before.
> 
> The other thing to do with this is to make sure we make our generation process resumable. If it crashes, it needs to know where it last was and pick up from that point.

Spam
