### ISSUE TITLE
Add missing NY County Courts to Courtlistener database

### ISSUE THREAD

**Issue by purselane** [freelawproject/courtlistener#1988]
We currently have 51/62 NY county courts in the DB.
We're missing 11/62 CCs.
There is a lot of overlap and ambiguity between the CCs and SCs. Most courts judges are multi-hatted between CCs and SCs. They seem to use CC and SC interchangeably often.
It might be okay to add the missing 10 CCs in the DB, and then take all the county courts in counties that don't have SCs  yet in the DB and change their names to "X Supreme & County Court." 
See spreadsheet of NY County and Supreme Courts [https://docs.google.com/spreadsheets/d/137j1A4e3JXsyEt-0zTVfyO5ZaH_jUKqcKz8N5VcLxQE/edit?usp=sharing](url)

**Comment by flooie** [comment]
@purselane I think the markdown Is reversed on the URL.

**Comment by flooie** [comment]
Completed.
