### ISSUE TITLE
Remove BCC from alert emails

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2008]
It turns out that adding a BCC to each of our alert emails double the price. Since we're storing emails in our database now, we don't really need to do this anymore. If there's still some value in it, perhaps we should make it configurable:

 - It only affects a percentage of outbound?
 - It can be turned off and on?

But I don't see much use for it...at least not that I can think of.

The only other good (?) thing about it is it keeps a longer-term record than our DB will, if we decide to truncate our DB table that contains the sent emails (which we are currently planning to do).

**Comment by albertisfu** [comment]
Currently seems the BCC is assigned only to the first message of a docket alert.

So, should we avoid adding a BCC to all docket alerts and consider one of the following options or a combination of both?

- Add a BCC to only a percentage of docket alerts, for this option I have some ideas, using a counter to add a BCC for every "100" alert or messages, another option could be using a random function to decide when to add a BCC or not.

- To turn off and on, in this option we should be able to decide when to add a BCC to the first message of all docket alerts or not add a BCC to any message, right? where we should be able to turn this option off and on, in the settings file?

Yes, we are planning to delete messages that are older than a defined period of time (e.g: one month), so yes with this in mind we could lose the register of Docket alerts sent.

**Comment by mlissner** [comment]
Hm, I think the easiest is a random variable that uses some percentage in the settings file, but since we have our own email backend now, maybe it's easiest to do this in the backend so it's not just alerts. 

Could we have a new setting, for example, `EMAIL_BCC_COPY_RATE` that could be a value between 0 and 1:

 - 1: Every message is BCC'ed in the email backend
 - 0.5: Half of messages are BCC'ed
 - 0: No messages are BCC'ed

That'd get us the best of all worlds, I think:

 - We get some messages
 - It's not just the docket alerts anymore, it's all messages
 - We get some messages that stick around
 - Most messages are deleted after a month (which is better for privacy)
 - It uses random instead of a counter, so it's easy to code

**Comment by albertisfu** [comment]
Thanks!  working on it.
