### ISSUE TITLE
Building docker image shouldn't re-install python deps every danged time

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2021]
Somehow we should sort this out so that the layer containing the python dependencies isn't installed every time. I suspect the answer is to install them in a build stage and to then copy them from the layer to a later one, but I'm not sure. 

Anyway, it's annoying now that our images take five minutes to build and 95% of that is waiting for poetry.

**Comment by flooie** [comment]
I'm not seeing this.  Unless I'm mistaken, the images build in seconds after the first one build is finished.

**Comment by mlissner** [comment]
Lots of Slack conversation on this. The caching wasn't happening when there were changes to the files, so the trick is to grab the poetry-related files first, build using those, and then add the rest of the files.
