### ISSUE TITLE
Remove people_db.Person.cl_id field due to disuse

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2026]
I came across a number of incorrect CL IDs for a judge while adding a new judge to our DB.

| CLID | PERSON ID | PERSON SLUG |
| ---- | ---------- | ------------ |
| n-judge-422  | 15046  | julia-i-rodriguez |
| ny-jude-398  | 14923  | robert-a-mcdonald |
| ny-judge--297  | 14843  | richard-c-kloch-sr |
| cal-judge-11  | 14546  | dana-walton |
| cal-jud-5  | 14540  | virginia-keeny |
| 14534  | 14534  | barbara-jean-johnson |
| 14540  | 14533  | barbara-r-johnson |
| 14532  | 14532  | larry-yellin |
| 14531  | 14531  | bill-wood |
| 14530  | 14530  | nathan-vu |
| 14529  | 14529  | robert-tice-raskin |
| 14528  | 14528  | tyler-tharpe |
| 14527  | 14527  | chet-taylor |
| 14526  | 14526  | raymond-swope |
| 14525  | 14525  | steven-e-stone |
| 14524  | 14524  | william-d-stewart |
| 14523  | 14523  | christopher-smith |
| 14522  | 14522  | joseph-christopher-smith |
| 14521  | 14521  | joseph-craig-scott |
| 14520  | 14520  | tim-schmal |
| 14519  | 14519  | penny-scanlon |
| 14518  | 14518  | a-veronica-sauceda |
| 14517  | 14517  | sonny-sandhu |
| 14516  | 14516  | thomas-edward-rogers-iii |
| 14515  | 14515  | omar-rodriguez |
| 14514  | 14514  | jesus-a-rodriguez |
| 14513  | 14513  | jesse-i-rodriguez |
| 14512  | 14512  | jesus-i-rodriguez |
| 14511  | 14511  | jesse-rodriguez |
| 14510  | 14510  | alex-ricciardulli |
| 14509  | 14509  | mel-recana |
| 14508  | 14508  | tony-raphael |
| 14507  | 14507  | joseph-martin-quinn |
| 14506  | 14506  | chuck-poochigian |
| 14505  | 14505  | charles-f-adams |
| 14504  | 14504  | stephen-m-murphy |
| 14503  | 14503  | john-devlon-molloy |
| 14502  | 14502  | rosie-mcguire |
| 14501  | 14501  | briye-mccann |
| 14500  | 14500  | george-marlette |
| 14499  | 14499  | andy-mannsourian |
| 14498  | 14498  | steve-malone |
| 14497  | 14497  | tony-mallery |
| 14496  | 14496  | og-magno |
| 14495  | 14495  | jackson-lucky |
| 14494  | 14494  | jd-lord |
| 14493  | 14493  | bert-levy |
| 14492  | 14492  | jim-latting |
| 14491  | 14491  | steven-lapham |
| 14490  | 14490  | anthony-kline |
| 14489  | 14489  | marc-kelly |
| 14488  | 14488  | jim-kelley |
| 14487  | 14487  | clay-jacke |
| 14486  | 14486  | steve-hermanson |
| 14485  | 14485  | dino-inumerable |
| 14484  | 14484  | patti-hunter |
| 14483  | 14483  | ted-howard |
| 14482  | 14482  | chester-horn-jr |
| 14481  | 14481  | patti-garcia |
| 14480  | 14480  | annie-t-christoff |
| 14479  | 14479  | kelly-fitzgerald-pate |
| 14478  | 14478  | molly-h-cherry |
| 14477  | 14477  | rebecca-t-christoff |
| 14476  | 14476  | kimberly-g-altman |
| 14475  | 14475  | brian-scott-meyers |
| 14474  | 14474  | wendy-a-kinsella |
| 14473  | 14473  | curtis-ivy-jr |
| 14472  | 14472  | carmen-e-henderson |
| 14471  | 14471  | joshua-michael-kindred |
| 14470  | 14470  | cory-todd-wilson |
| 14469  | 14469  | wendy-williams-berger |
| 14468  | 14468  | mark-christopher-scarsi |
| 14467  | 14467  | franklin-ulyses-valderrama |
| 14466  | 14466  | philip-morgan-halpern |
| 14465  | 14465  | john-leonard-sinatra-jr |
| 14464  | 14464  | cheryl-allen-lydon |
| 14463  | 14463  | maryellen-noreika |
| 14462  | 14462  | rachel-peter-kovner |
| 14461  | 14461  | lewis-jeffrey-liman |
| 14460  | 14460  | todd-wallace-robinson |
| 14459  | 14459  | daniel-aaron-bress |
| 14458  | 14458  | jeffrey-vincent-brown |
| 14457  | 14457  | peter-david-welte |
| 14456  | 14456  | eleni-m-roumel |
| 14455  | 14455  | david-austin-tapp |
| 14454  | 14454  | michael-patrick-allen |
| 14453  | 14453  | christian-n-weiler |
| 14452  | 14452  | edward-hulvey-meyers |
| 14451  | 14451  | lisa-g-beckerman |
| 14450  | 14450  | jennifer-e-niemann |
| 14449  | 14449  | tiiara-na-patton |
| 14448  | 14448  | rachel-m-blise |
| 14447  | 14447  | mitchell-l-herren |
| 14446  | 14446  | jil-mazer-marino |
| 14445  | 14445  | martha-ruthie-hagan |
| 14444  | 14444  | michelle-vonsenden-larson |

**Comment by purselane** [comment]
Will work on these this week. Noting that for CA, I was initially numbering judges in accord with their person ID. Near the end, I spoke with Mike who recommended switching over to cal-judge-X+. So there are currently two numbering patterns for CA judges, but the vast majority were numbered with the person ID.

**Comment by mlissner** [comment]
Sorry, sounds like I was wrong here. Let me know if you need further clarification and I'll be happy to chime in. I think Bill said y'all chatted about this though, so I'll stay out for now at least. (He's off the rest of the week though.)

**Comment by mlissner** [comment]
Heliya and I talked about this a bit today, and I have to say I'm not sure the `cl_id` field has much value. She could spend some time working on it and making it better, but my observation is:

 - It was created to provide a more useful ID than our regular ID. Its description is:

    > A unique identifier for judge, also indicating source of data.

    But we have the joined `sources` table for that, and a single source field is less useful than the `sources` table.

 - It has confused many people and caused many questions. For example, when Nick imported the judges, I had to explain to him what the field was and we had to come up with a plan for populating it. When Jon did work on this, I had to explain it. Now I'm anticipating explaining it to Heliya, and, while that'd be fine (I explain lots of things lots of times)...

 - Most importantly: I don't really know how it's useful. I don't think anybody is using it for much of anything.

So, I propose that unless somebody opposes and explains how it's actually useful, we should just get rid of it and never think of it again. There's a small/medium/large question with getting rid of it:

1. Small: Just continue putting unique values in it, but remember that it's not useful.
2. Medium: Make it a nullable, non-unique field and stop putting values in it (requires DB migration)
3. Large: Remove it. Would have to migrate the DB and talk to all our replication customers, but we could do it.

Thoughts? Opposing positions?

**Comment by flooie** [comment]
I think it’s of no use.  I would just junk it.  Or make it automated based on judge type and court

**Comment by mlissner** [comment]
OK, I've sent out a tweet asking for feedback about this topic. A second tweet will go out in a week. I will contact our replicated DB folks as well: https://twitter.com/FreeLawProject/status/1517269811209728000

**Comment by mlissner** [comment]
This is largely done. One of our replication clients is currently running pg_dump, which locks tables against ALTER statements, so our query is hanging with that client, but hopefully we can get it to go through soon. I'll stay on it.
