### ISSUE TITLE
Verify if PACER magic links require a login to download sealed documents

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2041]
Trying to download documents via magic links seems to fail when the document is sealed because it redirects to a login page:

`Unable to download PDF. PDF not served as binary data and unable to find iframe src attribute.`

Since we don't log in to download magic link documents, we need to confirm that all sealed content requires a login so we can rely on this fact to be sure we don't get sealed content.

We need to gather more data to confirm that all notifications that trigger this `Unable to download PDF` error are sealed content.

**Comment by johnhawkinson** [comment]
Note that there are restricted documents (e.g. documents limited to case participants and public terminal users, such as immigration and social-security filings under FRCP 5.2) and sealed documents and although they are not the same things, the login requirement applies to both. So it's best to avoid saying "sealed" when we may mean a lower level of security.

But also, you should be preserving and reporting the actual error message reporting by CMECF in the HTML. It's usually something about how a login is required to view this document. "Unable to download PDF" sounds like a library error which suggests something isn't properly parsing MIME types and soforth.

**Comment by albertisfu** [comment]
Got it, right now it seems when is not possible to download the document directly with the magic link it redirects to a login page where there isn't a specific message that indicates whether it's restricted or sealed content and a login is required:

![Screen Shot 2022-04-28 at 10 23 26](https://user-images.githubusercontent.com/486004/165787572-d283e0d4-9c50-4b5a-8eef-ab47029efc6c.png)

So seems it's necessary to log in to get an error message, in this case, it only says "This document is not available":

![Screen Shot 2022-04-28 at 9 57 36](https://user-images.githubusercontent.com/486004/165787720-47d11e62-c8b6-4e5c-8e14-f558f72dcb8e.png)

Yes the "Unable to download PDF" is a Juriscraper error that it's triggered because of the redirection to the login page, so I think the question we want to answer is if all restricted or sealed content requires a login, if not we might need to use another strategy to avoid getting this kind of documents.

**Comment by mlissner** [comment]
Can you chime in on where we're at with this, @albertisfu? I think we might be able to close it out?

**Comment by albertisfu** [comment]
Sure, now we have more data I'll check related errors on sentry and also check if we've downloaded sealed documents via magic links to be sure this is not happening.

**Comment by albertisfu** [comment]
@mlissner I've made a review of all the emails we've received from recap.email.

I looked for `seal` and `sealed` keywords within all of those emails in order to identify possible sealed documents and check their status on RECAP, these are the results:

13 emails explicitly say are sealed documents with the tag `[SEALED] `. All of those documents are from the same case:
https://www.courtlistener.com/docket/60651262/cbv-inc-v-chanbond-llc/

105: https://www.courtlistener.com/docket/60651262/105/cbv-inc-v-chanbond-llc/
41: https://www.courtlistener.com/docket/60651262/41/cbv-inc-v-chanbond-llc/
114: https://www.courtlistener.com/docket/60651262/114/cbv-inc-v-chanbond-llc/
107: https://www.courtlistener.com/docket/60651262/107/cbv-inc-v-chanbond-llc/
71: https://www.courtlistener.com/docket/60651262/71/cbv-inc-v-chanbond-llc/
54: https://www.courtlistener.com/docket/60651262/54/cbv-inc-v-chanbond-llc/
65: https://www.courtlistener.com/docket/60651262/65/cbv-inc-v-chanbond-llc/
49: https://www.courtlistener.com/docket/60651262/49/cbv-inc-v-chanbond-llc/
123: https://www.courtlistener.com/docket/60651262/123/cbv-inc-v-chanbond-llc/
48: https://www.courtlistener.com/docket/60651262/48/cbv-inc-v-chanbond-llc/
94: https://www.courtlistener.com/docket/60651262/94/cbv-inc-v-chanbond-llc/
79: https://www.courtlistener.com/docket/60651262/79/cbv-inc-v-chanbond-llc/
51: https://www.courtlistener.com/docket/60651262/51/cbv-inc-v-chanbond-llc/

None of these documents were downloaded, even though the emails have magic links.


However, there are more emails that within their descriptions don't explicitly say they're sealed but they contain the `seal` or `sealed` words. Some of them were downloaded and others were not. But I'm not sure if their download status is appropriate or not (due to legal terms).

Here are some data from those emails that might help to identify if they should have been downloaded or not.

```
Download status: Not Downloaded
Date received: 27 April 2022, 16:15
Document: 102
URL: https://www.courtlistener.com/docket/14931431/102/rudler-v-mla-law-offices-ltd/
Description: Letter  MOTION for Leave to Electronically 
File Document under Seal <i>(and, to the extent necessary, to supplement 
the motion/objection record)</i>  by Britney Rudler.  (Attachments:  # (1) 
Exhibit Exhibit 1 - Rider to So Ordered Settlement) (Green, Remy)
```

```
Download status: Downloaded
Date received: May 24th, 2022, 13:42
Document: 103
URL: https://www.courtlistener.com/docket/60651262/103/cbv-inc-v-chanbond-llc/
Date uploaded: May 24th, 2022
Description: UNOPPOSED MOTION To File Under Seal - filed by IPNAV, LLC, Deirdre Leane. (Attachments: # 1 Text of Proposed Order)(Levine, James Harry) Modified on 5/24/2022 (dlw).
```

```
Download status: Downloaded
Date received:  31 May 2022, 11:25
Document: 30
URL: https://www.courtlistener.com/docket/61586457/30/vergara-v-town-of-babylon-ny/
Date uploaded: May 31st, 2022
Description: RESPONSE to Motion re [29] Letter MOTION to Seal Exhibit to Plaintiff's Declaration in support of motion for summary judgment filed by All Defendants. (Wexler, William)
```

```
Download status: Downloaded
Date received: 12 July 2022, 17:36
Document: 33
URL: https://www.courtlistener.com/docket/62633965/33/curran-groome-v-city-of-new-york/
Date uploaded: July 12th, 2022
Description: LETTER MOTION to Seal addressed to Judge John P. Cronan from Remy Green dated 2022-07-12. Document filed by Elizabeth Curran-Groome..(Green, Remy)
```

```
Download status: Not Downloaded
Date received: 12 July 2022, 17:39
Document: 34
URL: https://www.courtlistener.com/docket/62633965/34/curran-groome-v-city-of-new-york/
Date filed: July 12th, 2022
Description: SELECTED PARTIES LETTER MOTION for Discovery seeking to Excuse Parties from 1983 Plan Mediation addressed to Judge John P. Cronan from Remy Green. Document filed by Elizabeth Curran-Groome, City of New York, John and Jane Does 1-2(Individually), John and Jane Does 1-2(as Police Officers), Scott Haldeman(Individually), Scott Haldeman(as a police officer), Kenneth Lehr, Terence Monahan(Commander of NYPD Patrol Borough Bronx, as a Police Officer), Terence Monahan(Commander of NYPD Patrol Borough Bronx, Individually), Dermot Shea, Katherine Tejada(Shield 6752, Tax ID 953474, Individually), Katherine Tejada(Shield 6752, Tax ID 953474, as a Police Officer).Motion or Order to File Under Seal: [33].(Green, Remy)
```

```
Download status: Downloaded
Date received: 5 April 2022, 22:49
Document: 59
URL: https://www.courtlistener.com/docket/60651262/59/cbv-inc-v-chanbond-llc/
Date uploaded: April 5th, 2022
Description: Letter to the Honorable Maryellen Noreika from Stephen B. Brauerman regarding Emergency Request to Protect Confidentiality of Chanbond, LLC's Under Seal Filing. (Attachments: # 1 Exhibit A)(Brauerman, Stephen)
```

```
Download status: Downloaded
Date received: March 22nd, 2022
Document: 38
URL: https://www.courtlistener.com/docket/60651262/38/cbv-inc-v-chanbond-llc/
Date uploaded: March 22nd, 2022
Description: UNOPPOSED MOTION for Leave to File Under Seal - filed by IPNAV, LLC, Deirdre Leane. (Attachments: # 1 Rule 7.1.1 Certification, # 2 Text of Proposed Order)(Levine, James Harry)
```

```
Download status: Downloaded
Date received: March 22nd, 2022
Document: 39
URL: https://www.courtlistener.com/docket/60651262/39/cbv-inc-v-chanbond-llc/
Date uploaded: March 22nd, 2022
Description: ORDER GRANTING 38 Unopposed Motion to File Under Seal. Signed by Judge Maryellen Noreika on 3/22/2022. (dlw)
```

```
Download status: Downloaded
Date received: 10 May 2022
Document: 22
URL: https://www.courtlistener.com/docket/63020994/22/doe-v-regents-of-the-university-of-colorado-the/
Date uploaded: 10 May 2022
Description: ORDER ON PLAINTIFF'S MOTION TO PROCEED UNDER PSEUDONYM "JANE DOE" AND SEAL COMPLAINT (Dkt. # 3 ) by Magistrate Judge N. Reid Neureiter on 9 May 2022. It is hereby ORDERED that Plaintiff's Motion for Leave to Restrict (Dkt. #3) is DENIED. This case shall not be sealed, and the Complaint must comply with Fed. R. Civ. P. 10(a) by including the names of all the parties. The Complaint and Demand for Trial by Jury (Dkt. # 2 ) should be unrestricted, and Plaintiff shall file forthwi th another version of the Complaint reflecting her identity. It is further ORDERED that this Order is stayed for 14 days to allow for Plaintiff to file any objection with the Judge Raymond Moore, who is the Article III judge presiding over this matter. If no objection is filed, this Order shall become effective. If an objection is filed, this Order shall not become effective until after Judge Moore's ruling on the objection.
```
```
Download status: Not Downloaded
Date received: February 25th, 2022
Document: 93
URL: https://www.courtlistener.com/docket/17302643/93/wsou-investments-llc-v-google-llc/
Date filed: February 25th, 2022
Description: DEFENDANT GOOGLE LLCS OPPOSITION TO 85 Plaintiff's Opposed Motion to Extend Pretrial Deadlines (Attachments: # 1 Exhibit 1, # 2 Exhibit 2, # 3 Exhibit 5, # 4 Exhibit 6, # 5 Exhibit 8, # 6 Exhibit 9, # 7 Exhibit 12, # 8 Exhibit 13, # 9 Exhibit 21, # 10 Exhibit 23, # 11 Exhibit 24, # 12 Exhibit 25, # 13 Exhibit 27)
```
```
Download status: Downloaded
Date received: 25 May 2022, 13:02
Document: 29
URL: https://www.courtlistener.com/docket/61586457/29/vergara-v-town-of-babylon-ny/
Date uploaded: 25 May 2022, 13:02
Description: Letter MOTION to Seal Exhibit to Plaintiff's Declaration in support of motion for summary judgment by Bella 77 Corp., Nicole Vergara. (Attachments: (1) Exhibit Exhibit 1 - Links to video sought to be sealed)
```
```
Download status: Downloaded
Date received: June 1st, 2022
Document: 112
URL: https://www.courtlistener.com/docket/60651262/112/cbv-inc-v-chanbond-llc/
Date uploaded: June 1st, 2022
Description: Unopposed MOTION TO FILE UNDER SEAL Response to 110 Motion - filed by IPNAV, LLC, Deirdre Leane. (Attachments: # 1 Text of Proposed Order)(Levine, James Harry) Modified on 6/1/2022 (mdb).
```
```
Download status: Downloaded
Date received: May 5th, 2022
Document: 103
URL: https://www.courtlistener.com/docket/14931431/103/rudler-v-mla-law-offices-ltd/
Date uploaded: May 5th, 2022
Description: Letter providing the Rider to the So-Ordered Settlement, per the Court's Order by Britney Rudler (Attachments: (1) Exhibit Rider to So Ordered Settlement, (2) Exhibit Letter Motion Seeking Permission to File Under Seal and In the Alternative, an Order Directing Plaintiff to file the Rider) (Green, Remy)
```

**Comment by mlissner** [comment]
This sounds good, thanks Alberto. I went through each of the items above to see if they were all good. This one looks problematic: 

https://www.courtlistener.com/docket/61586457/29/vergara-v-town-of-babylon-ny/

It comes up as sealed in PACER, but somehow we have it. I called the judge's chambers and talked to a clerk that said it was sealed upon filing, not after filing, so if she's right, that means it's a bug in our code. I sort of doubt that she's right, but can you take a look, Alberto? Once you've looked, let me know and I'll take the doc off CourtListener.

**Comment by albertisfu** [comment]
I've done a new revision through the emails we've received since the last revision (August 9).

I looked for seal, and sealed words, here are my findings.


- "case_name": "CSX Transportation, Inc. v. Norfolk Southern Railway Company"
  CL URL:  [https://www.courtlistener.com/docket/8507590/csx-transportation-inc-v-norfolk-southern-railway-company/?page=3](https://www.courtlistener.com/docket/8507590/csx-transportation-inc-v-norfolk-southern-railway-company/?page=3)

  We have received many emails from this case and all the entries whose descriptions start with "Sealed" were not downloaded like 417, 422, 428, 433, 448, 452, 457, 469,  474, 487, 493, 497, 515, 531

  There are some documents whose descriptions mention "Filed Under Seal" but it only refers to one or more attachments, seems that the main document shouldn't be sealed, e.g: 424, 419, 475 
  If you look at the attachments that say "Filed Under Seal", the PDF was downloaded but the PDF only contains a page that says it's sealed, so I think that's ok.


- "case_name": "United States v. Swiencinski"
  CL URL: [https://www.courtlistener.com/docket/7307480/united-states-v-swiencinski/?page=2](https://www.courtlistener.com/docket/7307480/united-states-v-swiencinski/?page=2)

  Documents that whose descriptions explicitly say are sealed were not downloaded, e.g:
368, 370, 326, 327, 378, 385, 386

  But I found one here that looks bad: 
  [387](https://www.courtlistener.com/docket/7307480/387/united-states-v-swiencinski/)
  However, I think this was sealed after we received the email because it has the RD description "Seal". So this description must have been added afterward since from recap.email we don't add descriptions to the RD.
  The docket entry description in the email says:
  ```
  <FONT  FACE="arial,helvetica" COLOR="#0000cc" SIZE=3><b>
  MOTION to Seal <i></i>  by Brian Swiencinski, 
  Scott Breimeister, Ronnie Mcada, Jr as to Brian Swiencinski, Scott Breimeister, 
  Vladimir Redko, Christopher Ince, MD, Ronnie Mcada, Jr, filed.  (McCarthy, 
  Brandon)
  </b></Font>
  ```
  I believe this was not sealed when the email was received and the document was available for download, similar to the other problematic case that you found in the previous comment.

- "case_name": "In re Google Assistant Privacy Litigation"
  CL URL: [ https://www.courtlistener.com/docket/15971537/in-re-google-assistant-privacy-litigation/?page=2]( https://www.courtlistener.com/docket/15971537/in-re-google-assistant-privacy-litigation/?page=2)
  Documents that whose descriptions explicitly say are sealed were not downloaded, e.g:
  297, 278

  There are others that mention `Motion to File Under Seal` but if I'm not wrong these not necessarily should be sealed? e.g:
 347, 345


- "case_name": "CBV, Inc. v. ChanBond, LLC"
  CL URL: [https://www.courtlistener.com/docket/60651262/cbv-inc-v-chanbond-llc/?page=2](https://www.courtlistener.com/docket/60651262/cbv-inc-v-chanbond-llc/?page=2)
 Documents that whose descriptions explicitly say are sealed were not downloaded, e.g:
 179, 157, 192, 194, 191, 164, 151

- "case_name": "United States v. Pierre"
  CL URL: [https://www.courtlistener.com/docket/7085299/united-states-v-pierre/?page=2](https://www.courtlistener.com/docket/7085299/united-states-v-pierre/?page=2)
  We haven't downloaded any documents from this case seems all of them are sealed.

- "case_name": "Appliance Computing III, Inc. v. Redfin Corporation"
  CL URL: [https://www.courtlistener.com/docket/17147446/appliance-computing-iii-inc-v-redfin-corporation/?page=2](https://www.courtlistener.com/docket/17147446/appliance-computing-iii-inc-v-redfin-corporation/?page=2)
  Documents whose descriptions explicitly say are sealed were not downloaded, e.g:
  249, 248, 270, 261


- "case_name": "Negron v. CIGNA Corporation"
  CL URL: [https://www.courtlistener.com/docket/4552511/negron-v-cigna-corporation/?page=3](https://www.courtlistener.com/docket/4552511/negron-v-cigna-corporation/?page=3)
  Documents whose descriptions explicitly say are sealed were not downloaded, e.g: 463

- "case_name": "Russo v. Walgreen Co."
  CL URL: [https://www.courtlistener.com/docket/6061146/russo-v-walgreen-co/?page=3](https://www.courtlistener.com/docket/6061146/russo-v-walgreen-co/?page=3)
  Documents whose descriptions explicitly say are sealed were not downloaded, e.g:
  552,553 

- "case_name": "In Re: Sonic Corp. Customer Data Security Breach"
   CL URL: [https://www.courtlistener.com/docket/6240170/in-re-sonic-corp-customer-data-security-breach/?page=5](https://www.courtlistener.com/docket/6240170/in-re-sonic-corp-customer-data-security-breach/?page=5)
  Documents whose descriptions explicitly say are sealed were not downloaded, e.g:
  525, 523

The following ones belong to a muti-docket NEF:
- "case_name": "Cypress Holdings, III, L.P. v. Sport-BLX, Inc."
  CL URL: [https://www.courtlistener.com/docket/63000461/cypress-holdings-iii-lp-v-sport-blx-inc/](https://www.courtlistener.com/docket/63000461/cypress-holdings-iii-lp-v-sport-blx-inc/)
  Document number: 67

- "case_name": "SPORT-BLX, Inc. v. Salerno"
  CL URL: [https://www.courtlistener.com/docket/65369591/sport-blx-inc-v-salerno/](https://www.courtlistener.com/docket/65369591/sport-blx-inc-v-salerno/)
  Document number: 24
  These documents were downloaded but I think they are not sealed, I put them here just to be sure since they say something like: "documents may be filed under seal only as provided" within their description.


So in general, I think we're not downloading sealed content via recap.email, and the problematic ones like [387 united-states-v-swiencinski](https://www.courtlistener.com/docket/7307480/387/united-states-v-swiencinski/) seems to be sealed after we receive it.

**Comment by mlissner** [comment]
OK, the best way to know if we're doing this correctly is to check if something can be downloaded from PACER, so I went through pretty much all of your examples and tried to download things with the word 'sealed' that you highlighted and I didn't find a single problem. I think we're good here. I'm glad to have checked, double checked, and triple checked.

**Comment by johnhawkinson** [comment]
> * But I found one here that looks bad:
>       [387](https://www.courtlistener.com/docket/7307480/387/united-states-v-swiencinski/)
>       However, I think this was sealed after we received the email because it has the RD description "Seal". So this description must have been added afterward since from recap.email we don't add descriptions to the RD.
>       The docket entry description in the email says:
>       ```
>       <FONT  FACE="arial,helvetica" COLOR="#0000cc" SIZE=3><b>
>       MOTION to Seal <i></i>  by Brian Swiencinski, 
>       Scott Breimeister, Ronnie Mcada, Jr as to Brian Swiencinski, Scott Breimeister, 
>       Vladimir Redko, Christopher Ince, MD, Ronnie Mcada, Jr, filed.  (McCarthy, 
>       Brandon)
>       </b></Font>
>       ```

For the record, a motion to seal is not necessarily (or even usually) itself sealed. Just like your later example of  `Motion to File Under Seal`.

Also, perhaps recap.email will never encounter it, but there are documents that sealed and then unsealed (e.g. case-initiating documents in criminal cases prior to arrest) and the descriptions continue to say SEALED after they are unsealed. But only Court personnel and prosecutors would be receiving NEFs for these during the pendancy of the seal.
