### ISSUE TITLE
Opinions by Judges links only to CL, not RECAP

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#2065]
For a District Court judge, e.g., [Alsup](https://www.courtlistener.com/person/89/william-haskell-alsup/), the link at the bottom "[Search for All Opinions Authored by Alsup](https://www.courtlistener.com/?type=o&q=author_id%3A89+OR+panel_ids%3A89)" links out to a page of that judge's opinions in the CL database. (125 at the time of this issue filing). 

But if we go to the RECAP archive tab and search for cases "Assigned to" and enter "Alsup" we'll get [5,528 cases](https://www.courtlistener.com/?type=r&q=&type=r&order_by=score%20desc&assigned_to=Alsup) that are in RECAP, the vast majority of which one assumes he authored one or more opinions in.

Until everything is in a single database to rule them all, I suggest the Judge page, for federal judges, needs two links:

1. "Search for All Opinions Authored by Alsup in CourtListener" (existing link)
2. "Search for All Cases Assigned to Alsup in RECAP" (new proposed link)

While this is sort of an enhancement / feature request, I think the phrase "for All Opinions" makes this more of a bug because it is so misleading for users, who might not realize they're missing thousands of cases by not searching in the RECAP tab.

**Comment by mlissner** [comment]
This is a good one, and probably pretty easy to fix too.

**Comment by flooie** [comment]
I followed your link on Judge Alsup and and was like oh ill go look at his page on courtlistener, great I can just click on William H Alsup in the below image.  I kept clicking it over and over until I realized that that link doesn't go to the Judge's page but to search for him.  @mlissner I found that confusing and wonder if that's confusing UI.

<img width="764" alt="Screen Shot 2022-05-21 at 3 38 19 PM" src="https://user-images.githubusercontent.com/6464529/169666789-5cfbd9aa-379e-4a6b-bb72-a0482176c0d4.png">

@brianwc does it make more sense to give an entire new list for recap.  Something like 

Most recent Cases Assigned to J. Alsup.  We already have multiple sections that follow the same pattern.  See attached image.  I think it would be more interesting to separate recap cases assigned as a separate list and add Search all Recap Cases Assigned to? 

<img width="503" alt="Screen Shot 2022-05-21 at 3 43 36 PM" src="https://user-images.githubusercontent.com/6464529/169666870-c6c149ac-0df9-4019-9f78-2b20dfeb5fe4.png">

 @quinnr

**Comment by quinnr** [comment]
@flooie I agree that is inconsistent behavior in the search results page. The oral arguments search results treats it entirely differently, and does not link judges in the results page (the actual argument page links to the associated /person/ page):
![image](https://user-images.githubusercontent.com/1690399/169667387-46cc13ff-f82a-4a7c-b3a6-f58e00779746.png)

Having two sections would add functionality to the judge pages. 

Only concern I can think of is if it would potentially be duplicative for some judges / end up showing similar lists of results frequently?

**Comment by mlissner** [comment]
> Only concern I can think of is if it would potentially be duplicative for some judges / end up showing similar lists of results frequently?

I think that should be OK, b/c the content is so different, but it's a good point. We'll have to watch for that. 

> I realized that that link doesn't go to the Judge's page but to search for him. @mlissner I found that confusing and wonder if that's confusing UI.

Well, it makes sense to me, but that's the problem of making things, and I could see how it'd be confusing to 100% of the rest of the world. 

I think this is a *bit* of a hack because we don't always have the judge information when we show search results. Like, we know their name, but not their ID. I guess something else we could do is search for them in the people search engine, by name, and go with that. Or maybe we do have the IDs. I'm not completely sure.

**Comment by mlissner** [comment]
Done.
