### ISSUE TITLE
Add links to PacerDash for any RECAP doc that we don't have

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2071]
PacerDash came up with a nice idea to make it possible for people to purchase items via their website and then feed them back into ours. Here's an example:

https://www.pacerdash.com/court-listener-checkouts/181127929787

All we need to do is link to these from our dockets when we don't have the item. Right now we have simple download buttons that lead to PACER. We can just add a little drop down to the button that leads to PacerDash, probably with a link that says, "Buy on PacerDash"

**Comment by johnhawkinson** [comment]
I do think if we do this, we need to make it clear that pushing the button will incur a substantial (well, as a fraction of the document cost) surcharge.

The point of doing this is to make it easier for people to get a document instantly without having to sign up for a PACER account. It strikes me that the mockup of the UI is particularly important to look at.

I don't think a simple "buy on PacerDash" is sufficient.  Maybe if we include the $ figure with it (just as we do for PACER) that will be meaningful mitigation.

**Comment by mlissner** [comment]
Oh, and if there's an easy way to do so, we should track how many times these links are clicked. Maybe the Plausible API has something, or perhaps it's easy to build something ourselves. I wouldn't want to spend more than a little time adding click tracking, but there's the possibility that this becomes popular and it might be wise to keep track of whether that happens.

**Comment by mlissner** [comment]
Did you click through to the link, @johnhawkinson ? It shows the price and the service fee and everything in pretty good detail, I think?

**Comment by johnhawkinson** [comment]
I did click the link.
I think it's important what we present on our page prior to clicking the link.

I'm imagining a user who doesn't know what PACERdash is being presented with "buy on PACER" and "Buy on PacerDash" and choosing the latter arbitrarily, and not understanding that had they clicked the other link, they would pay 10¢ instead of $1.00.

So I think we need to make that decision point clear.

The fee breakdown on the PacerDash page is only understandable if you know that the service fee and transaction fees would not otherwise be charged. And I don't think it's reasonable to expect a neophyte (to whom this feature is targetted) to understand that.

**Comment by mlissner** [comment]
Hm, I see what you're saying. You suggested adding a dollar sign, which is fine. A more extreme version might be to make the link say something like:

> $ Buy on PACER via PacerDash

Or:

> Use PacerDash to buy on PACER

A simpler version could be:

> Buy via PacerDash

Which sort of hint that there's an extra middle-person here. 

We can tweak the PacerDash page too, though I'm not sure what you'd advocate for on that page to make it clearer without bashing people over the head with it.

**Comment by johnhawkinson** [comment]
> Hm, I see what you're saying. You suggested adding a dollar sign, which is fine. 

**No I am not!**

By "$ figure" I meant "the dollar figure," i.e.:


<img width="999" alt="Screen Shot 2022-05-19 at 19 41 copy" src="https://user-images.githubusercontent.com/1270718/169421837-820f8ab7-aae5-47b8-b31b-f26f44130180.png">
(Sorry for the extra white box, I was sloppy.)


> A more extreme version might be to make the link say something like:
> 
> > $ Buy on PACER via PacerDash
> 
> Or:
> 
> > Use PacerDash to buy on PACER
> 
> A simpler version could be:
> 
> > Buy via PacerDash
> 
> Which sort of hint that there's an extra middle-person here.

None of these make it clear that PacerDash is more expensive with extra fees. They don't address the problem I raised.
 
> We can tweak the PacerDash page too, though I'm not sure what you'd advocate for on that page to make it clearer without bashing people over the head with it.

Given that it's for neophytes, I think bashing people over the head is probably justified.

**Comment by mlissner** [comment]
Ah, I see. OK, yes, that makes sense and would certainly be helpful. The only catch is we don't always show the dollar figure because we don't always know the page length, but I think your idea would be good in most cases.

**Comment by quinnr** [comment]
I am not clear on what the value add is from purchasing the PDF from this service with a surcharge. Scanning through the website it seems like most of their services are around keeping track of new filings. 

Would it not make more sense for PacerDash to link to CourtListener when documents are freely available? 

Would PacerDash upload documents not requested via CourtListener? 

I agree that it should be clear to the user both (1) that there is a separate third-party surcharge; and (2) what the consumer or CourtListener is getting for the additional fee that a regular PACER download w/ Recap does not achieve.

**Comment by mlissner** [comment]
I feel like it's pretty analogous to online shopping, actually:

Buy from Publisher
Buy on Barnes & Noble
Buy on Amazon
Buy on Walmart

Yeah, they have different prices, but sometimes you might have an account at one or the other. I've heard a fair bit over the years from people that want to buy something without having a PACER account.

**Comment by mlissner** [comment]
I took a quick look at [how plausible event tracking works](https://plausible.io/docs/custom-event-goals). It's very easy, technically, but to save money on Plausible, we only load their tracker on every tenth page load on CourtListener.

I opened a discussion with them to see if it's possible to log events on a page without logging that the page loaded: https://github.com/plausible/analytics/discussions/1917

**Comment by johnhawkinson** [comment]
Some ideas that I don't love, but may generation discussion:

```
Buy on PACER ($0.50)
Buy on PacerDash ($1.41)
```

```
Buy on PACER ($, reg. req'd)
Buy on PacerDash ($$, instant)
```

```
$  Buy on PACER ($0.50)
$$ Buy on PacerDash ($1.41)
```

with the case where we don't know pricing:

```
$  Buy on PACER
$$ Buy on PacerDash
```

also

```
Buy on PACER (exact $)
Buy on PacerDash ($+2.9%+$0.90) (no account needed)
```


Do these ideas suggest other, hopefully better, ideas?

**Comment by quinnr** [comment]
I could see getting files without an account is helpful to some. If I recall correctly, PACER requires an active payment method to register/keep on file. My main thought was just that it should be transparent to users what they're paying for. 

Also worth noting that a user who's just viewing a few files in a case may not have to pay any fees if they do not hit the quarterly free download cap on PACER. 

```
Buy on PACER ($0.50)
Buy on PacerDash ($1.41)
```
This is the only option I don't dislike, the others are a bit cluttered. 

I think it's fine to link to both without an extra notation on the buttons, just was not clear to me at first what the value was that was worth recommending users send funds to a third party.

**Comment by mlissner** [comment]
@albertisfu is going to start work on this soon, so I'm going to play the [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life) card and sand declare that the buttons should simply say:

 - Buy on PACER ($0.50)
 - In a drop down (like the download link has): Buy on PacerDash ($1.41)

Alberto, the price on PacerDash is the cost of the document × 1.029% + 90¢.

For example, if the document is five pages, it costs $0.50. That × 1.029 = $0.5145

Add 90¢ = $1.41.

If we get feedback that this is confusing, we can refine it, but I'm not sure there's enough space in a button to fully educate our users about PACER pricing. I think that the difference in price will be enough to prompt folks to figure out how to lower their bills, if they're buying more than a few things, so I'm not too worried about confusing people with this.

**Comment by johnhawkinson** [comment]
OK, but what do we do for the case where we lack pagecount?

**Comment by mlissner** [comment]
Just gotta drop the pricing, like we do now:

 - Buy on PACER
 - Buy on PacerDash

People will figure it out. We're prioritizing the gov't over PacerDash. Should be OK, I think.

**Comment by johnhawkinson** [comment]
I'm gonna offer one last pitch for 

```
$  Buy on PACER
$$ Buy on PacerDash
```

in that case (or similar).

**Comment by mlissner** [comment]
We can try some screenshots of that, if you don't mind, Alberto.

**Comment by albertisfu** [comment]
Sure, I'll add some screenshots of these two button options!

**Comment by quinnr** [comment]
I think those are all valid points and interesting design questions, but as long as the price delta is clear through some kind of label I would expect the average consumer to prioritize the cheaper option unless they have a reason not to?

Adding a click where there isn't one now is a good point—but buying a document on Pacer already requires an account and multiple clicks so a drop-down is feasibly going to save at least a subset of users time in either case.

**Comment by mlissner** [comment]
It'll be something like this:

![Screenshot from 2022-05-24 12-32-35](https://user-images.githubusercontent.com/236970/170117496-c7e41cdf-35f1-4ba7-9f0f-1441ff4f0412.png)

So: One click for "Buy on PACER" and two clicks for "Buy on PacerDash", which you don't even see if unless you open the drop down.

**Comment by quinnr** [comment]
That seems like the best of both worlds to me. Gives extra options for access to those who want it without necessarily endorsing a third party over the cheaper primary source. I assumed they'd be together based on the discussion.

**Comment by albertisfu** [comment]
Here are some screenshots with the new PacerDash button with different options:

Document available in CL, prices available: 
![document_available_prices](https://user-images.githubusercontent.com/486004/170301694-d03bf3ec-7e0d-4e77-b6d2-ee83da195142.png)

Document available in CL, no prices available: 
![document_available_no_prices](https://user-images.githubusercontent.com/486004/170301765-9aa265cf-9c25-4927-976e-7ac3875af9d1.png)

Document not available in CL, prices available: 
![no_document_prices_normal](https://user-images.githubusercontent.com/486004/170300897-ac5305c3-4197-4770-ade3-6fe3c97c0464.png)

Document not available in CL, no prices available: 
![no_document_no_prices_normal](https://user-images.githubusercontent.com/486004/170301403-741e4fb7-fdad-46b8-b65e-69cd41690f68.png)

Document not available in CL, no prices available with dollar signs: 
![no_document_no_prices_dollar_normal](https://user-images.githubusercontent.com/486004/170301519-38bfc55c-9a04-4364-9dd4-66f208055130.png)

**Some variations:**
In the previous buttons the `Buy on PACER` has the default white color, it's also possible to use a different color:
![Screen Shot 2022-05-25 at 2 22 49](https://user-images.githubusercontent.com/486004/170302831-7fb90ebb-1d7b-4a53-8e25-3b1c8bf3df91.png)

The default bootstrap size for dropdown buttons is slightly bigger than the main button as you could see in the previous screenshots, so it's also possible to reduce it a bit to be the same size as the main button:
![no_document_no_prices_reduced](https://user-images.githubusercontent.com/486004/170303070-76dc8031-29f1-4a3a-9b4c-ab69455635d2.png)

For mobile, currently, we down show text for the "Buy on PACER" button, it's only an icon, so we could add the dropdown to the icon and open the `Buy on PacerDash` button underneath:
![mobile_version](https://user-images.githubusercontent.com/486004/170303801-1ad27246-1384-462d-945e-dfa7480b86e1.png)

Let me know what you think.

@mlissner a couple of questions about the price calculation that emerged when creating the PacerDash price method:

- If the document is free on PACER, the PacerDash price should be only 90¢ or it should be also $0?

- I noticed that the current price function takes the minimum number between the price calculated based on the number of pages and $3, so the max price is $3.
Should this work similarly for the PacerDash price? if a document price is over 3, should we take 3 x  1.029% + 90¢? so the max price on PacerDash will be $3.99?

**Comment by richleenyc** [comment]
Hi everyone - Rich here (PacerDash)

> If the document is free on PACER, the PacerDash price should be only 90¢ or it should be also $0?

It should be zero.  My apologies.  I am pushing an update right now to fix this.

Regarding pricing:  The service fee we charge is a flat $0.60 / document, regardless of the page count.  As discussed with Mike, this is to cover things like chargeback risk, refunds, disputes (for which we bear the full cost) and other service-related overhead.

The Stripe fee is $0.30 + 2.9% of the purchase price.  If we don't have the page count, we need to make a request to  PACER to retrieve data about the document (page count, whether it is available or sealed, etc.).

**Comment by richleenyc** [comment]
The free document bug is fixed.  Examples:

Free Document:
https://www.pacerdash.com/court-listener-checkouts/04519239808/

Regular Document for Purchase:
https://www.pacerdash.com/court-listener-checkouts/04519239849/

Just a monkey patch for now.  Eventually I'll get rid of this extra click for free docs.

**Comment by albertisfu** [comment]
Thanks you all!

I'll work on those changes.

Just one more question @mlissner:
> We currently show the Buy on Pacer links for free docs, but let's remove those and not show such links for PacerDash either, assuming this is easy. If it's hard, let's just show both.

Right now for a free document if we don't have the document, it's shown like this:
![Screen Shot 2022-05-25 at 12 03 43](https://user-images.githubusercontent.com/486004/170320597-e9fd15cd-f4df-4815-b907-add83969fd2d.png)

So, shouldn't we show any button to buy, like this?
![Screen Shot 2022-05-25 at 12 06 24](https://user-images.githubusercontent.com/486004/170320709-7ff14496-4cae-4b75-893e-25a180b92c89.png)  so there wouldn't be a way to get the free document if we don't have it?

**Comment by mlissner** [comment]
Sorry, I meant on docs that we already had. On docs we don't, we need those links, like you say.
