### ISSUE TITLE
cl-django will not build - Cannot locate "ipware" module

### ISSUE THREAD

**Issue by quinnr** [freelawproject/courtlistener#2075]
While attempting to build a development environment on an Amazon Linux 2 image, I ran into some interesting issues. 

In particular, I think there's some kind of bug with the "_ipware_" dependency which is called by [utils.py](https://github.com/freelawproject/courtlistener/blob/main/cl/api/utils.py). Running docker-compose up on a new cloned directory according to the Developer guide threw me the error log below: 

> cl-django       | Traceback (most recent call last):
> cl-django       |   File "/opt/courtlistener/manage.py", line 15, in <module>
> cl-django       |     main()
> cl-django       |   File "/opt/courtlistener/manage.py", line 11, in main
> cl-django       |     execute_from_command_line(sys.argv)
> cl-django       |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
> cl-django       |     utility.execute()
> cl-django       |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
> cl-django       |     django.setup()
> cl-django       |   File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
> cl-django       |     apps.populate(settings.INSTALLED_APPS)
> cl-django       |   File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 114, in populate
> cl-django       |     app_config.import_models()
> cl-django       |   File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 301, in import_models
> cl-django       |     self.models_module = import_module(models_module_name)
> cl-django       |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
> cl-django       |     return _bootstrap._gcd_import(name[level:], package, level)
> cl-django       |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
> cl-django       |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
> cl-django       |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
> cl-django       |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
> cl-django       |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
> cl-django       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> cl-django       |   File "/opt/courtlistener/cl/users/models.py", line 17, in <module>
> cl-django       |     from cl.api.utils import invert_user_logs
> cl-django       |   File "/opt/courtlistener/cl/api/utils.py", line 20, in <module>
> cl-django       |     from ipware import get_client_ip
> cl-django       | ModuleNotFoundError: No module named 'ipware'

**I was able to successfully get django and the to launch by:** 
1.) Commenting out the _ipware_ module import in [line 20 of utils.py](https://github.com/freelawproject/courtlistener/blob/37c88e46a2ef2f2fd81f0fe44e1d98d9d42ded0d/cl/api/utils.py#L20)

2.) Replacing [line 239](https://github.com/freelawproject/courtlistener/blob/37c88e46a2ef2f2fd81f0fe44e1d98d9d42ded0d/cl/api/utils.py#L239) as follows: 
From: 
`        client_ip, is_routable = get_client_ip(request)
`
To: 
`        client_ip, is_routable = 1,1
`

Not sure what this fix breaks but without making that change I was not able to get the development docker-compose cluster up and running, as Django would crash after dumping the error above.

**Comment by quinnr** [comment]
I tried all sorts of changing of the dependencies to get the module to import but had no luck.

**Comment by flooie** [comment]
You need to build the development image.  Check make file in docker folder.

**Comment by flooie** [comment]
Did you also pull the latest images for task server.

**Comment by flooie** [comment]
Closing this because I am confident this is from a recent update to main.

**Comment by quinnr** [comment]
> You need to build the development image. Check make file in docker folder.

That was the issue, should have read the guide closer!

**Comment by mlissner** [comment]
Something ain't right here. I just pulled an image from docker hub and got this error. Everybody else seems to be working around it too.

**Comment by flooie** [comment]
@mlissner did you run the development docker-compose ?

**Comment by mlissner** [comment]
What do you mean? I ran `docker-compose up`. That should work, right? I shouldn't have to build.

**Comment by flooie** [comment]
Yes -  I just want to replicate everything

**Comment by mlissner** [comment]
Yeah, I deleted everything with `docker-compose rm`, then ran `up`, and got the error. I wonder if you won't be able to replicate because of arm. Maybe you pull a different image because of that.

**Comment by flooie** [comment]
Can you share your docker image tag.?

**Comment by flooie** [comment]
@mlissner ... how old is your `latest-web-dev` image?

**Comment by flooie** [comment]
Okay, @mlissner  I think you are right.  it appears that the django-web-dev version built and pushed to docker hub ~a month ago simply doesnt have the most recent changes to the poetry files.

**Comment by mlissner** [comment]
What's the best fix? Would it make sense to auto build that image, along with the prod ones?

**Comment by flooie** [comment]
I think so - but my test push last night didnt seem to work, but Im working to iron out the kink and then Ill submit a PR with changes to the makefile.

**Comment by mlissner** [comment]
I'm going to hijack this thread a bit. Before we close this, we should fix the make file so it works properly (as is in progress in #2143). Another thing I've noticed in our automated deploy is:

 - [ ] Images are built twice by automatic deploy pipeline

We need to make sure that doesn't happen, b/c it means they're twice as slow. Or we need to pull it into a separate job or something, so it happens in parallel. Not sure, but we should do something so it's not in the critical path to deployment.

**Comment by flooie** [comment]
This should be resolved in PR #2143
