### ISSUE TITLE
Figure out how to get shell access on the new servers

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2079]
Yes, I can do it using k9s, but maybe there are better ways? Probably. I should figure this out and document it along with the stuff I do in #2078.

**Comment by mlissner** [comment]
Nodes are not terminated if they have a pod that was manually created. As such, we created one manually today called `maintenance` that *[should](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node)* prevent the node from getting nuked:

```
k apply -f 12_maintenance.yaml
```

From now on, to run maintenance work, just do:

```
k attach -it maintenance 
```

CTRL+P, CTRL+Q to detach from that. If you do `exit` instead, the pod gets restarted (for better or worse).

---

If this pod *does* get nuked, annotate it according to documentation here: https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md

**Comment by flooie** [comment]
so no need to have a permanent node.  just manually create a pod for cl-python and nuke it after its completed... and let Kubernetes do its thing?

**Comment by mlissner** [comment]
The pod now exists and will continue existing. No need to make new pods to do maintenance. Just attach to the "maintenance" pod as above.

Because of the way the pod was created, the node should stay up until we remove it manually (which we might do, for example, if we *wanted* the node to be restarted).

**Comment by flooie** [comment]
great.

**Comment by mlissner** [comment]
This is seeming OK to me lately. Going to close until we run into a problem here.
