### ISSUE TITLE
Pennsylvania Import

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2086]
Notes and thoughts for importing Pennsylvania

Before I jump into Pennsylvania, its worth revisiting things we've learned.
We just wrapped up importing New York opinions and we have learned a few things.
 
One, we may or may not have multiple slugs for individual reporters.  This means we can't automate the whole process.  Each reporter needs to be checked by hand. 

We also now peruse through all the courts in a state to add them all in order to Courts-DB before we even think about importing opinions.  Currently Ohio and Pennsylvania were done ahead of time.

**Comment by mlissner** [comment]
This done, @flooie?

**Comment by flooie** [comment]
This is done
