### ISSUE TITLE
Analyze if our celery retries are working at all

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2089]
@albertisfu is working to reproduce something and it looks like it *could* be possible that our celery retries aren't doing much of anything at all.

Tonight, I was trying to reproduce something else and noticed similar behavior, now that he put it on my radar. It's certainly weird. 

Alberto, if you haven't already, can you please take a deeper look at this and if it's true that none of our retries are working, can you please fix them? [It looks like](https://docs.celeryq.dev/en/v4.3.0/userguide/tasks.html#automatic-retry-for-known-exceptions) if you want to do automatic retry for any exception, you'd want to do something like:

```
@app.task(autoretry_for=(Exception,))
def x():
    ...
```

I think we should try to be more granular than that, but since `autoretry_for` doesn't appear anywhere in our code, I suspect none of our retries are doing anything. This is a bit shocking, but we've had worse bugs, I guess.

**Comment by albertisfu** [comment]
Sure! I've been checking our tasks and yes it seems that only some of them are retrying the ones that are retrying manually using:
`raise self.retry(exc=exc)`

Tasks that use the decorator with the `max_retries` param e.g. `@app.task(bind=True, max_retries=5, ignore_result=True)` but do not call the retry manually are not retrying.

As you mentioned it's necessary to use `autoretry_for ` e.g:
`@app.task(autoretry_for=(requests.ConnectionError,), bind=True, max_retries=2, retry_backoff = 10)`

Adding the exceptions we do want to catch to retry when they occur.

I think we can add  `autoretry_for ` to our task that needs to retry, we only need to be careful about which exceptions we'll catch and retry, for example for microservices tasks they could be `ConnectionError, RequestException, Timeout`.

We also need to be careful that our tasks do not write to the DB before a possible exception or make them atomic.

Also was thinking of an alternative of only retrying the function that could fail, for example in the case of microservices make the `microservice()` function a task with a retry policy, so we can avoid retrying the main tasks and only retry the microservice task, in my test it works, however, I'm not sure about the implications of calling and waiting for a task inside of the main task.

I'll be glad of hearing your opinion about this.

**Comment by mlissner** [comment]
Did you see the @retry decorator that lives in decorators.py? It could do some retries automatically for things like microservices. 

If those retries are inside celery though, they could block celery from making progress. If you imagine that one of our microservices goes down, you could see all of the celery workers getting stuck waiting and retrying it. I think that means that it's better to retry entire tasks. 

I think most of our tasks are retryable in any case. They should be either atomic or idempotent, but it's worth checking as we fix this, to make sure nothing breaks along the way.

**Comment by mlissner** [comment]
Perfect, thanks.

**Comment by albertisfu** [comment]
I've looked for all of our tasks that have `max_retries` in their task decorator, assuming that those tasks are the ones that we need to retry, we could also search if some tasks that don't have this param `max_retries` need to be retried.

These are the tasks that we are currently retrying manually on those exceptions:

`def download_pdf:` `RequestException`

`def find_citations_and_parentheticals_for_opinion_by_pks`: `ResponseNotReady`

`def download_recap_item`: `requests.Timeout`, `ReadTimeoutError`

`def get_and_save_free_document_report`: `TypeError`, `RequestException`, `ReadTimeoutError`, `PacerLoginException`, `ParsingException`, `SoftTimeLimitExceeded`, `ValueError`, `IndexError,` `HTTPError`

`def process_free_opinion_result`: `IntegrityError`, 

`def get_and_process_free_pdf`: `PacerLoginException`, `ReadTimeoutError, requests.RequestException`

`def get_pacer_case_id_and_title`: `RequestException, ReadTimeoutError, PacerLoginException`

`def make_docket_by_iquery`: `requests.Timeout, requests.RequestException`

`def get_docket_by_pacer_case_id`: `RequestException, ReadTimeoutError`

`def get_appellate_docket_by_docket_number`: `requests.RequestException`

`def get_attachment_page_by_rd`: `HTTPError`, `requests.RequestException`

`def get_bankr_claims_registry:` `RequestException, ReadTimeoutError`

`def download_pacer_pdf_by_rd`: `HTTPError`, `RequestException`

`def get_pacer_doc_id_with_show_case_doc_url`: `RequestException, ReadTimeoutError`,  `HTTPError`

`def make_financial_disclosure_thumbnail_from_pdf`:   `not response.ok`

`def download_pdf`: `RequestException`

`def add_or_update_case_db`: `RequestException`

`def fetch_date_range`: `RequestException`

`def process_recap_pdf`: `Docket.DoesNotExist`, `DocketEntry.DoesNotExist`, `IOError`

`def process_recap_docket`:  `IOError`, 

`def process_recap_attachment`: `IOError`, `RECAPDocument.DoesNotExist`

`def process_recap_claims_register`: `IOError`, `IntegrityError`

`def process_recap_docket_history_report`: `IOError`, `IntegrityError`

`def process_recap_appellate_docket`: `IOError`

`def fetch_docket`: `requests.RequestException, ReadTimeoutError`, `PacerLoginException`

`def merge_rss_feed_contents`:  `IntegrityError`

`def update_docket_info_iquery`:  `requests.Timeout, requests.RequestException`

`def subscribe_to_mailchimp`: `requests.RequestException`

`def update_mailchimp`: `requests.RequestException` 

`def get_title`:  `HTTPError`, `Exception`


**These are the tasks that have the `max_retries` param but they are not retrying manually, so we need to retry them or not as proposed:**

[`def upload_pdf_to_ia`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L612):  Retry manually if response is None

[`def do_case_query_by_pacer_case_id`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L944):  Retry if `CaseQuery` Fails

[`def make_attachment_pq_object`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L1451): I'm not sure if it would be necessary to retry if `filepath_local.save` fails?

[`def get_pacer_doc_by_rd`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L1650): Retry if `download_pacer_pdf_by_rd` fails with `RequestException`

[`def get_pacer_doc_by_rd_and_description`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L1702):  This task calls `get_attachment_page_by_rd` and `download_pacer_pdf_by_rd` task as a function, so seems it’s necessary to retry here if one of them fails.

[`def import_disclosure`](https://github.com/freelawproject/courtlistener/blob/601faedf3a200c24e8675f7ba4a6187fb34a0659/cl/disclosures/tasks.py#L364): Retry if get `requests` fails or `save_and_upload_disclosure` fails

[`def add_case_from_filepath`](https://github.com/freelawproject/courtlistener/blob/06731ff61777ca6649b5e585d7854df2b69e1ef7/cl/lasc/tasks.py#L308):  Retry if `LASCSearch` Fails

[`def process_recap_zip`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L361):  Seems that doesn’t  make an external request or something that could be solved by retrying

[`def process_recap_appellate_attachment`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L903): Seems that doesn’t make an external request or something that could be solved by retrying.

[`def fetch_pacer_doc_by_rd`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L1103): Retry if `download_pacer_pdf_by_rd fails with RequestException`

[`def process_recap_email`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L1495):  Retry if open file from S3 fails

[`def send_docket_to_webhook`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L1447): Retry manually if response is not ok

[`def extract_doc_content`](https://github.com/freelawproject/courtlistener/blob/4c7bd15ad1804dd9b3791a71b12ebe6ef82ad528/cl/scrapers/tasks.py#L74): Retry if request to doctor fails

[`def extract_recap_pdf`](https://github.com/freelawproject/courtlistener/blob/4c7bd15ad1804dd9b3791a71b12ebe6ef82ad528/cl/scrapers/tasks.py#L156): Retry if request to doctor fails

[`def process_audio_file`](https://github.com/freelawproject/courtlistener/blob/4c7bd15ad1804dd9b3791a71b12ebe6ef82ad528/cl/scrapers/tasks.py#L216): Retry if request to doctor fails

[`def fetch_attachment_page`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L1188): currently retry for: `RECAPDocument.DoesNotExist`, we might need to add retry also on `RequestException`

Let me know what do you think about this approach?

**Comment by mlissner** [comment]
A few replies below. Other thoughts: 

 - It might be worth looking up these tasks in Sentry and seeing what exceptions are currently being raised. It'd be nice if, like Java, we actually *knew* which exceptions each function could throw, but in Python-land, it's a mess, so I think Sentry is the best we can do. (There, I said something nice about Java. Been a while since I've done that!)

 - A lot of these interact with Redis, so we should make sure those get retried if needed too.

> **These are the tasks that have the `max_retries` param but they are not retrying manually, so we need to retry them or not as proposed:**
> 
> [`def upload_pdf_to_ia`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L612):  Retry manually if response is None

This one will get retried automatically the next day, and has no urgency, so it's OK to just remove retries here.

> [`def do_case_query_by_pacer_case_id`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L944):  Retry if `CaseQuery` Fails

Seems right. Or if we get a PacerLoginException.

> [`def make_attachment_pq_object`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L1451): I'm not sure if it would be necessary to retry if `filepath_local.save` fails?

Yeah, seems like we can remove retries here, and see what happens.

> [`def get_pacer_doc_by_rd`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L1650): Retry if `download_pacer_pdf_by_rd` fails with `RequestException`

For any of these that are doing stuff with PACER, we need to catch the PacerLoginException too.
 
> [`def get_pacer_doc_by_rd_and_description`](https://github.com/freelawproject/courtlistener/blob/d408f7c3e3eecf18e73be352d7bbd2e523ff3c50/cl/corpus_importer/tasks.py#L1702):  This task calls `get_attachment_page_by_rd` and `download_pacer_pdf_by_rd` task as a function, so seems it’s necessary to retry here if one of them fails.

Yes, please.
 
> [`def import_disclosure`](https://github.com/freelawproject/courtlistener/blob/601faedf3a200c24e8675f7ba4a6187fb34a0659/cl/disclosures/tasks.py#L364): Retry if get `requests` fails or `save_and_upload_disclosure` fails

Seems about right, I guess.

> [`def add_case_from_filepath`](https://github.com/freelawproject/courtlistener/blob/06731ff61777ca6649b5e585d7854df2b69e1ef7/cl/lasc/tasks.py#L308):  Retry if `LASCSearch` Fails

This code isn't used much, so it's OK to just add a catch for generic `Exception`

> [`def process_recap_zip`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L361):  Seems that doesn’t  make an external request or something that could be solved by retrying

Excellent; let's remove retries here (they were never here to begin with)

> [`def process_recap_appellate_attachment`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L903): Seems that doesn’t make an external request or something that could be solved by retrying.

Agreed, let's remove retries.

> [`def fetch_pacer_doc_by_rd`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L1103): Retry if `download_pacer_pdf_by_rd fails with RequestException`

Sounds good.
 
> [`def process_recap_email`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L1495):  Retry if open file from S3 fails

Seems good.


> [`def send_docket_to_webhook`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L1447): Retry manually if response is not ok

Sure + if the request fails, I assume.

> [`def extract_doc_content`](https://github.com/freelawproject/courtlistener/blob/4c7bd15ad1804dd9b3791a71b12ebe6ef82ad528/cl/scrapers/tasks.py#L74): Retry if request to doctor fails

Yep. Can we check for all calls to microservice and make sure they're all retrying somehow?

> [`def extract_recap_pdf`](https://github.com/freelawproject/courtlistener/blob/4c7bd15ad1804dd9b3791a71b12ebe6ef82ad528/cl/scrapers/tasks.py#L156): Retry if request to doctor fails

Yep.

> [`def process_audio_file`](https://github.com/freelawproject/courtlistener/blob/4c7bd15ad1804dd9b3791a71b12ebe6ef82ad528/cl/scrapers/tasks.py#L216): Retry if request to doctor fails

Yes.

> [`def fetch_attachment_page`](https://github.com/freelawproject/courtlistener/blob/3e6b524f2f2734416ed19cd87af9ed0a4dc227d2/cl/recap/tasks.py#L1188): currently retry for: `RECAPDocument.DoesNotExist`, we might need to add retry also on `RequestException`

yes, `get_pacer_cookie_from_cache` hits Redis, so we'll need to handle that. 

`get_attachment_page_by_rd` also hits PACER, so we'll need to catch PACER-related exceptions too.

> Let me know what do you think about this approach? 

Looks good, thank you.
