### ISSUE TITLE
Collect patent cases from WDTX and D. Del going back ten years for client

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2096]
Process:
 - [x] get the FJC data and filter it to dockets in WDTX and D.Del in the last decade; make that a CSV
 - [ ] import that FJC data using the FJC import script
 - [x] copy the file everything_project.py to a new file, then tweak it so:
    - is has a new tag for this data pull
    - focuses on patent cases in WDTX or D.Del from the past ten years
    - doesn't have all the cruft it currently does
- [ ] Check the client's PACER fees before beginning
- [ ] Run the new file to do the import (USE CLIENT'S PACER INFO)
- [ ] Check the client's PACER fees while running and after
- [ ] Update the coverage page to note this new data set
- [ ] Monitor things
- [x] Notify client of completion, noting the new tag

**Comment by mlissner** [comment]
jackson_project.py is probably another good (and slightly simpler and newer) example to go by.

**Comment by flooie** [comment]
First part of this is done.  Merged and should be ready to go soon.
