### ISSUE TITLE
Oral Argument "Duration" Offset from Actual Duration

### ISSUE THREAD

**Issue by quinnr** [freelawproject/courtlistener#2109]
At least on recently posted Oral Argument audio, it looks like the "Duration" value that appears in the Search Results and on the Oral Argument page is consistently off by a few minutes. See, e.g.: 

- [Bartlett v. Tribeca Lending Corp](https://www.courtlistener.com/audio/81513/bartlett-v-tribeca-lending-corp/?type=oa&q=&type=oa&order_by=dateArgued%20desc) - Displays 5:21, actual duration 6:14, 2nd Cir.
- [Rucker v. Kijakazi](https://www.courtlistener.com/audio/81511/rucker-v-kijakazi/) - Displays 19:51, actual duration 23:07, 2nd Cir.
- [United States v. Rivera](https://www.courtlistener.com/audio/81521/united-states-v-rivera/) - Displays 26:14, actual duration 30:33, 3rd Cir.

**Comment by mlissner** [comment]
This is one of those weird things about variable bitrate mp3s, which I believe are what we use.

One would think that the Mp3 standard would include a field indicating how long a file was, but no. Instead, what you do is sample the first chunks of the file to see how much data it takes per second. You then use that and the total file size to determine the duration. I'm probably mangling some details.

Anyhow, we're not alone in this issue. Watch a mp3 player closely, and you'll see that it suffers too, towards the end of songs. At least, iTunes did, when I researched this maybe six years ago...

The worse news is that sampling works worse and worse the longer the file. So itunes will probably be fine, but with long oral arguments, the sampling error has a bigger impact.

**Comment by mlissner** [comment]
Looks like it was more like eight years: https://stackoverflow.com/a/6037997/64911

Perhaps things have changed. We could try using a couple of the answers there and see if they do better than eyeD3. I'd worry a bit about performance though if they did.

**Comment by mlissner** [comment]
I don't see us doing this any time soon. It's annoying, but it's something most people *never* notice. MP3's are weird.
