### ISSUE TITLE
Redo alerts and API profile pages to use sub-tabs

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2110]
A few things are bugging me:

1. The profile/alerts page sucks, particularly if you have a lot of alerts. If you do, it's difficult to even notice that your docket alerts are down below.

2. The auto-subscribe setting for recap.email doesn't belong on the proifle page. It belongs on the docket alerts page. But we don't have a page just for docket alerts yet. 

3. The API page now has sections for information about the API, your usage, and your API token, and webhooks (creating and listing). This isn't great.

To fix this, let's:

1. Add sub-tabs to the alerts page. One for search alerts, the other for docket alerts.

2. Add a toggle for enabling auto-subscribe to the docket alerts page. The toggle for "Enable Uploads" in the RECAP Extension window might be a good one to use as an example.

3. Break the API page into sub-tabs too for the various sections. 

I'm still not sure how creating and listing webhooks will work. Maybe it just has a separate page creating, and a button at the top to make one. That'd be simple enough, but other ideas welcome.

**Comment by albertisfu** [comment]
Great, these changes sound good to me, I'll work on it.
