### ISSUE TITLE
Add docker build and push to GitHub actions

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2116]
@mlissner 

I may be wrong but I think we already push docker images (occasionally to docker hub from GitHub actions).  

I think we should be able to add a tag v0.0.0 trigger to a GitHub CI and push our production images.

**Comment by mlissner** [comment]
I don't think we push currently. We run a docker hub clone in the CI and we push to that, I think.

**Comment by flooie** [comment]
Yeah, I just remembered that, but we can still do the build and push for everything still

**Comment by mlissner** [comment]
Yes. I think we can also ask docker hub to do the build. I'm not sure the pros/cons of the different approaches. If pushing from CI takes time, it's probably not worth doing it, though it might not take much time if I remember correctly. I forget how docker hub works.

**Comment by flooie** [comment]
You have a web-dev build 

https://hub.docker.com/layers/courtlistener/freelawproject/courtlistener/latest-web-dev/images/sha256-67755d54b03aaffff857e355774f8c6e65d2d3dbeb92b67b5fb0ddc89ac7f781?context=repo

on docker hub that made me think that these images were actually pushing

**Comment by flooie** [comment]
I assumed that since the image built on GitHub ci is web-dev and its labeled push it might be us pushing it every time.   or atleast every time you push to main.

**Comment by mlissner** [comment]
Ah, I see. No, the makefile pushes those now because new devs were having to build an image just to get started, or else they pulled an ancient image and suffered.

**Comment by flooie** [comment]
Re-opening this image because GitHub actions for building developer images and pushing to docker hub is failing.

**Comment by mlissner** [comment]
I saw that. Looked ARM related, I'm sorry to say. I was hoping it'd fix itself in a day or two when debian folks fix whatever sub-dependency broke.

**Comment by mlissner** [comment]
Alas, this problem still keeps happening. Shoot.

Some clues here, but it seems like it's a buildx issue related to arm:

https://github.com/docker/buildx/issues/495

Bleh. I kind of still hope it fixes itself, but we don't have dev images in the meantime.

**Comment by mlissner** [comment]
Seems to be fixed via https://github.com/docker/buildx/issues/495#issuecomment-761562905

Disappointing stuff, Docker.
