### ISSUE TITLE
Scrambled Dockets

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2126]
I've been trying to unwind some scrambled RECAP dockets and think we should have an issue for them.

**Comment by mlissner** [comment]
We do have the HTML that's behind dockets and we even have a way to reparse it as needed. What we don't have is an easy way to do that for the RSS entries, but that's not the end of the world when these issues come up. I think you're right that if we removed the most recent HTML file that formed the docket, then reparsed, we'd wind up in a pretty good place. 

Anyway, this is resolved for now. We can reopen this issue if we like next time.
