### ISSUE TITLE
Monitoring PACER scraping

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2160]
After releasing #2123 seems that we continue receiving many `PacerLoginException` errors on Sentry.

We should continue monitoring those errors to understand what's happening. It would be helpful to review logs on redis to check if we have some data about blocked courts.

It also might be possible that the origin of these errors is not related to a court block. So we also should consider other possibilities and assess them to find the root issue.

I'll put on this issue all the findings.

**Comment by mlissner** [comment]
We made all these great logs. We should definitely check in again here. We are still getting a fair number of PacerLoginExceptions in sentry. More than I'd like.

**Comment by albertisfu** [comment]
After merging #2447 the number of `PacerLoginExceptions` on sentry is much lower, now only tasks that failed after running out of retries are logged to sentry.

So I gave a look at why these tasks are still failing. 

In a Juriscraper dev branch, I added a logger to inspect the HTML that PACER returns within `check_if_logged_in_page` method.

The HTML is the following, it actually contains a redirect to a PACER login page.
```
<html><head><link rel="shortcut icon"  href="/favicon.ico"/><title>CAND-ECF</title><script type="text/javascript">var default_base_path = "/"; </script><script type="text/javascript">if (top!=self) {top.location.replace(location.href);}</script><link rel="stylesheet" type="text/css" href="/css/default.css"><script type="text/javascript" src="/lib/core.js"></script></head><body><style type="text/css">body { overflow:auto;}</style><SCRIPT LANGUAGE="JavaScript"> document.cookie="FilingStatus=; path=/; expires=Thu, 01-Jan-1970 00:00:01 GMT"; document.cookie="PacerFirm=; path=/; domain=.uscourts.gov; expires=Thu, 01-Jan-1970 00:00:01 GMT"; document.cookie="KEY=; path=/; domain=.uscourts.gov; expires=Thu, 01-Jan-1970 00:00:01 GMT"; document.cookie="KEY=; path=/; expires=Thu, 01-Jan-1970 00:00:01 GMT"; document.cookie="PublicTerminal=; path=/; domain=.uscourts.gov; expires=Thu, 01-Jan-1970 00:00:01 GMT"; if ("https://pacer.login.uscourts.gov/csologin/login.jsf?pscCourtId=CANDC&appurl=https://ecf.cand.uscourts.gov/doc1/035022713727".length > 0) {                                                location.assign("https://pacer.login.uscourts.gov/csologin/login.jsf?pscCourtId=CANDC&appurl=https://ecf.cand.uscourts.gov/doc1/035022713727");                                        }                                     </SCRIPT></div></body></html>
```
The redirect link sends to this page:
![Screen Shot 2023-01-06 at 14 15 45](https://user-images.githubusercontent.com/486004/211096962-c2cf772e-c80c-4ebd-8ebd-67a1c3a9a476.png)

When checking a document or Docket manually on PACER sometimes I run into this page, since I don't have a client code I just click on submit or refresh the page, and I'm redirected to the document or docket, the thing is that sometimes it doesn't work properly at the first try, even though cookies are still valid.

So I thought that maybe something similar is happening when querying an attachment page using the fetch API.

So I ran a test requesting an attachment page via the fetch API until I got a retry, it was not difficult after two successful fetch requests I got the retry (internal `PacerLoginException`) then I just let retries do their work and on the second retry the task was successfully completed, no need to renew cookies.

So maybe this is a PACER bug that sometimes asks users for their client code even if they're authenticated, and it seems that's pretty common.

So I think that tasks that fail after retries are not too lucky to sort out this page.

It's weird that we're only running into this issue when fetching attachment pages, maybe the bug on PACER is more frequent when querying attachment pages or just the volume of fetch attachment requests is greater than fetch docket or PDF requests?

- Something that I think might work to solve this problem is to do one additional request even if `check_if_logged_in_page` returns "False", luckily after that second request, the content is properly returned without waiting/wasting a retry.

Let me know what you think about this approach.

**Comment by mlissner** [comment]
Yeah, that's wacky, but it's a good solution. Let's go for it.

**Comment by mlissner** [comment]
By the way, Alberto, you said:

> since I don't have a client code I just click on submit or refresh the page,

Just so you know, client codes aren't anything special. They're just codes that attorneys use for billing. So if you're working on an IBM lawsuit your client code might be IBM. If an Apple lawsuit, it might be "Fruit", etc.

**Comment by mlissner** [comment]
I think this is pretty much all set. I rarely see this error anymore.
