### ISSUE TITLE
Create new API for search alert objects

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2161]
In #854 we're creating webhooks for search alert responses. In those responses, we want a serialized version of the search alert object. 

The best way to do this is to create an API for alerts, and to then serialize that API into the webhook response. This way, when we upgrade the API, the webhook responses remain a mirrored copy of the API endpoint, and they get versioned together. 

As for how that API should work:

 - You only see your alerts, just like with Tags (except tags have a concept of being public we can ignore)
 - You can do a POST, PUT, GET, or DELETE to do CRUD operations on your alerts
 - They serialize the alert.Alert model
 - Rate should show the FREQUENCY ids, not their values
 - We should show both the ID of the alert and the REST API URL
 - We shouldn't show the search_type, since we don't know that

**Comment by albertisfu** [comment]
Great, yeah this solves the questions I had, I'll be working on this.
Thank you.
