### ISSUE TITLE
Harvard Opinions Import duplicates with some case names

### ISSUE THREAD

**Issue by quevon24** [freelawproject/courtlistener#2204]
Working in #2191  issue, I found a possible bug that could cause duplicate cases with case names contianing only abbreviations or acronyms.

How did I come to that conclusion?

When analyzing the code to find the bug in #2191  issue, I decided to remove the check that if the opinion is already on the system based on Harvard opinion JSON path.  Here: https://github.com/freelawproject/courtlistener/blob/ed59ae5fe2b192d51f86a96e49d8ce38540587f4/cl/corpus_importer/management/commands/harvard_opinions.py#L290

After I removed that, I ran the importer with the cases from “law.free.cap.sw3d.134” from the first time with no problem. And then I ran it again and found that the only case that has been duplicated was “134 S.W.3d 673”. Tried again and again and still creates duplicates.

I started digging into that issue and I found that the problem lies specifically with the winnow_case_name function here: https://github.com/freelawproject/courtlistener/blob/ed59ae5fe2b192d51f86a96e49d8ce38540587f4/cl/corpus_importer/management/commands/harvard_opinions.py#L944

Which is called in the function case_names_dont_overlap, this function is used to check that case names do not overlap, it returns True if there is no overlap between two sets of words and false in otherwise.

This function uses the shortened case name from OpinionCluster found in possible cases, uses the full case name from Harvard opinion JSON and the case name abbreviation from Harvard opinion JSON.

Basically, winnow_case_name function reduces a title case to a set of words to compare in case_names_dont_overlap function.
To reduce the case names with the function, the name is converter to lowercase, then runs a first regex that removes chars like dots and at the end a regex removes one-letter words, initials, etc.

The problem happens when there’s a case name like “D.L.M. v. T.J.S.” because the process removes everything, leaving an empty string, causing a malfunction that leads to creating duplicates with this type of case names.

For example, we have the full case name from Harvard “Appeal of HAMILTON & CHAMBERS CO., INC.” and the case name abbreviation: “Appeal of Hamilton & Chambers Co.”, and the shortened name from the case in OpinionCluster: “Appeal of Hamilton & Chambers Co.”
There’s a function that reduces each case title to a set of words (in winnow_case_name function).
You pass the shortened case name from the opinion cluster to the function, and you get:
{'co', 'chambers', 'hamilton', 'appeal'}

Then you pass the Harvard case name + the case name abbreviation, for these purposes, is: “Appeal of HAMILTON & CHAMBERS CO., INC. Appeal of Hamilton & Chambers Co.”

The winnow_case_name function outputs: {'chambers', 'co', 'hamilton', 'appeal'}

If you perform and & operation between both dict of course there’s an overlap, so the case_names_dont_overlap returns a False

But what happen when you have a full case name from Harvard: “In the matter of S.J.S., a minor child. D.L.M. and D.E.M., Petitioners/Respondents v. T.J.S.”, a case name abbreviation: “D.L.M. v. T.J.S.” and the shortened OpinionCluster name: “D.L.M. v. T.J.S.”

Then you pass “D.L.M. v. T.J.S.” to the function that reduces the title to a set of words, and as result you get an empty set because of one of the regex.

And if you pass “In the matter of S.J.S., a minor child. D.L.M. and D.E.M., Petitioners/Respondents v. T.J.S. D.L.M. v. T.J.S.” to the function, you get: {'respondents', 'minor', 'child', 'petitioners'}

The regex removed the important stuff, I think.

So, when you compare both sets of words, of course there’s no overlap, because one set is empty and the other only have a few words.

After this, the case_names_dont_overlap function returns a True so ignore the possible case that it’s already on courtlistener, and then return a None because couldn’t find the case even if it’s in the system.

**Comment by flooie** [comment]
so... is the solution to check if the case name still exists at all and to bail?

**Comment by quevon24** [comment]
> so... is the solution to check if the case name still exists at all and to bail?

I was thinking of using a regex to match all abbreviations/acronyms before removing all non-alphanumeric characters.

So before you remove the dots from the string, convert the abbreviations/acronyms to a single word.

For example:

If you pass "D.L.M. v. T.J.S." to the function that reduces the case name to a set of words, the first thing to do after fixing the case name to make it cleaner would be converted those abbreviations/acronyms to a single word.

"D.L.M." -> "DLM"
"T.J.S." -> "TJS"

This way, the last regex won't remove one-letter words, initial, etc. Because originally "D.L.M." turns "d l m" and is removed by the regex. With the solution I propose, "D.L.M." becomes "dlm" and causes the word not to be removed.
