### ISSUE TITLE
Add a deprecation_date field to webhook events

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2219]
It'd be nice if we can warn our users that webhook events are getting deprecated in the future. If we put a simple field in the events called `deprecation_date`, our users could watch for that in their code.

For now, let's just stub it into every response and set it to None. When we need to actually deprecate something, we can figure out how to populate it more carefully. This way we'll be able to include the feature in part of our documentation right when we launch. In other words, it's a fake for now, but just having the key in the response will let people start looking for it when they implement their webhook listener.

**Comment by albertisfu** [comment]
Sure, it sounds good to me! I'll be working on this!
