### ISSUE TITLE
Add a Webhook testing feature

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2234]
It would be helpful to add a feature that users can use to test its webhook integration.
It might be something simple as allowing users to trigger an example webhook request for each event type.

**Comment by mlissner** [comment]
Would it be crazy as a part of this to include a curl command that showed them how to send it locally as well? 

I've set up a few webhook endpoints and it's pretty rough. I always wished the site would give me a "test this locally with the following command" kind of thing, that then would show something like:

```
curl -X POST http://localhost:8000/$whatever-their-endpoint-is/ --data $the-data-for-an-event
```

It might be nice to provide this for failed webhook events too, now that I think about it (but feature creep).

I guess if we do something like that (or even if we keep it simple), we'll need to come up with some dummy data to send. Not sure how to do that for things like docket updates.

**Comment by albertisfu** [comment]
Yeah! I agree it would be helpful to show the curl command to send it locally with an event example.

For failed events also it's possible since we store the webhook content, so we can use it to generate the curl command.

About dummy data. won't it be enough to use fake data or something like that?

What would be the problem with things docket updates?

**Comment by mlissner** [comment]
> About dummy data. won't it be enough to use fake data or something like that?

Yeah, this should be fine. :)

**Comment by albertisfu** [comment]
@mlissner  Here are some ideas about how this feature might be implemented:

The Test button could be next to the Edit button of each user's configured webhooks. So the test will be sent to the URL that is set in the webhook.

![Screen Shot 2022-11-09 at 12 27 35](https://user-images.githubusercontent.com/486004/200911487-832e9bb9-c8e7-4ced-b6f0-be6ad542041e.png)

When the user presses the Test button a modal will be shown.

I have in mind 3 different options for the testing modal, each one with different scopes.

**Option 1:**
This might be the easiest one to implement, it just shows the URL where the POST will be sent and the static dummy content according to the Webhook event type to test.

Then a "Send Webhook Event Test" button, when the user clicks this button we'll only send the POST request to the URL that is set in the webhook. In this option, we won't create a WebhookEvent in DB and won't show any response/error for the test.

![Screen Shot 2022-11-09 at 12 34 42](https://user-images.githubusercontent.com/486004/200912844-061983ee-dfb9-424a-aec4-53d85ed09578.png)

**Option 2:**
This option is similar to Option 1, the difference is that here we'll create WebhookEvent for the test (we'll need to add a debug field in the model) so once the Test is sent the user might be able to monitor its response in a kind of "Test Logs" panel, similar to normal logs where the user will be able to see the Response/Error for the test. We won't retry "Debug" Webhook events.
 
![Screen Shot 2022-11-09 at 12 42 22](https://user-images.githubusercontent.com/486004/200914291-92e32840-2d18-49a3-ab39-fde9b738f981.png)


**Option 3**
I think this might be the more complex option to implement. 
In this option when the user clicks the "Send Webhook Event Test" we'll send the Webhook test in real-time (no celery task enqueued), wait for the response, and show in the same place the response/error for that request.

We'll have the option to create a debug  WebhookEvent for this test like option 2 or not create it at all like Option 1.

![Screen Shot 2022-11-09 at 12 47 06](https://user-images.githubusercontent.com/486004/200915169-3dde5fef-3ab0-421d-ab3f-d2cd7eb4e2f4.png)

In the 3 options, I added the `Test this Webhook event locally with the following command` feature to show the CURL command the user can use to trigger the Webhook event locally.

Please let me know your opinion about these proposals or suggestions, so we can decide which one to implement.

**Comment by mlissner** [comment]
Option 2 looks best to me. I'm guessing it wouldn't take much extra work. 

The curl command is a good idea too. Can you hide it somehow though? Like, make the user expand it or something? The UX isn't very nice as is.

**Comment by albertisfu** [comment]
Perfect! yeah so I'll implement Option 2 and yes, I can hide the CURL command by default so the user expand it when needs to copy.

Thanks.
