### ISSUE TITLE
Reorder docket alerts header content

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2246]
Right now a docket alert looks like this:
![Screen Shot 2022-08-08 at 15 43 02](https://user-images.githubusercontent.com/486004/183511129-15a7fe22-6f50-4107-a177-b87c1293a82b.png)

After switching the content header it'll look like this:

![Screen Shot 2022-08-08 at 15 43 22](https://user-images.githubusercontent.com/486004/183511153-c13076f8-4eca-48ee-b113-54489a398205.png)

@mlissner I have a question for the text version, should it look like this?

```
Your account on CourtListener just received its first email from PACER related to the case below.
Your account has auto-subscribe turned off, so this is the only alert you will get for this case.
Subscribe to this case to get ongoing updates:
https://www.courtlistener.com/alert/docket/subscribe/hBypixhfjdZD0KP4nIs8WTornWzToLt20Bkberxd/
**************************
CourtListener Docket Alert
**************************
1 New Entry in WSOU Investments LLC v. Google LLC (6:20-cv-00580)
District Court, E.D. New York
...
```

**Comment by mlissner** [comment]
Yes, but please add a newline before and after the link. Thank you.
