### ISSUE TITLE
fetch_docket should send docket alerts/webhooks 

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2277]
Seems that `fetch_docket` is not sending docket alerts/webhooks right now. 
We should fix it and make it triggers docket alerts and webhooks as `process_recap_docket` does.

**Comment by mlissner** [comment]
One other thing is we need to update the items that didn't get extracted so far. Can you give me a small snippet of code to run that'll do that? I guess we need to do extraction + add to solr?

**Comment by albertisfu** [comment]
Of course, I think that code needs to look for all recap documents that were downloaded via `recap.email` and then pass them to the `extraction` and `add to solr` task, right?

So that means that we also need to add the `add_items_to_solr` task after extracting the PDF content for `recap.email` right?
Because seems that we don't do it right now.

**Comment by mlissner** [comment]
Oh, sorry, yes, we need to add to Solr too! 

I don't know that we need to only focus this on docs that we got from recap.email. If there are a few others that aren't extracted, we could do them too. They might have failed the first time, and might fail again, but that seems fine to me if it makes our code easier.

**Comment by albertisfu** [comment]
Great, I'll add `add_items_to_solr` after extracting the PDF for `recap.email` documents.

Perfect, so I think we can do something like look for documents that are available and check if they haven't been extracted, extract them and then add to solr.

Might it be worth doing a Django command for it? or just a code snippet that can be run on Django console?

**Comment by mlissner** [comment]
> Might it be worth doing a Django command for it? or just a code snippet that can be run on Django console?

Wouldn't hurt. You might be able to just add it as additional functionality on the `cl_update_index` command (it might already do this?).
