### ISSUE TITLE
Avoid sending a notification to admins when a webhook is failing.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2287]
Right now we send a notification to admins when a webhook is created or updated but seems the notification is also sent when the webhook failure count is updated.

We should avoid sending notifications to admins when the webhook fails.

**Comment by mlissner** [comment]
This appears to be fixed?

**Comment by albertisfu** [comment]
yeah, this is fixed, no more notifications for admins when a webhook fails or when is automatically disabled.

**Comment by mlissner** [comment]
Yee haw!
