### ISSUE TITLE
Selenium version breaking lint and tests

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2288]
Seems that the current Selenium (4.0.0a6.post2) is no longer available. 

Selenium updated is needed but newer versions are breaking tests.

**Comment by flooie** [comment]
this is probably not (but possibly) related.  I still get hung up running the tests locally at 

`<frozen importlib._bootstrap>:914: ImportWarning: _SixMetaPathImporter.find_spec() not found; falling back to find_module()`

**Comment by flooie** [comment]
only for tag selenium

**Comment by albertisfu** [comment]
yeah, I've confirmed that this error is the same that happened to me when running selenium tests on my M1 machine. Are you also using an M1 machine?

 I hadn't run tests for selenium locally before working on this issue. So in order to confirm is not an issue due to the last selenium update I rolled back the selenium and juriscraper versions to the previous ones and the error is the same running selenium tests.  So I think it's a compatibility problem on M1 machines.

When I was checking the selenium versions compatibility I had to run tests in a ubuntu virtual machine and it worked well. 

If you run tests using --failfast you might see something like this:

![Screen Shot 2022-09-06 at 21 28 35](https://user-images.githubusercontent.com/486004/188722154-3b489df4-c1b2-41fb-8d32-452372ce0145.png)

Maybe we would need a cl-selenium built for M1?

**Comment by albertisfu** [comment]
@quevon24 helped me to confirm that the problem also happens on windows: 

![Screen Shot 2022-09-06 at 21 55 35](https://user-images.githubusercontent.com/486004/188726767-d683d054-c76f-4ca9-9915-aa503957cdc1.png)

I ran selenium tests on my old mac (not m1) and they passed. So seems that it's not related to the last selenium update, might be worth a new issue for this?

**Comment by flooie** [comment]
Yes I am running on my `M1 Mac` ... great. ill make a new issue.

**Comment by flooie** [comment]
I'm actually not sure it's the same issue I'm seeing.

**Comment by mlissner** [comment]
> When I was checking the selenium versions compatibility I had to run tests in a ubuntu virtual machine and it worked well.

We probably shouldn't make a habit of this. We don't want to wind up with tests that don't pass on Macs.

> @quevon24 helped me to confirm that the problem also happens on windows:

Kevin, is your machine arm or amd64?

Really not loving the M1 Macs. I guess they make y'all happy, but they sure do create problems and complexity on a regular basis that we didn't have to think about before.

**Comment by flooie** [comment]
@mlissner ooph

**Comment by quevon24** [comment]
> > When I was checking the selenium versions compatibility I had to run tests in a ubuntu virtual machine and it worked well.
> 
> We probably shouldn't make a habit of this. We don't want to wind up with tests that don't pass on Macs.
> 
> > @quevon24 helped me to confirm that the problem also happens on windows:
> 
> Kevin, is your machine arm or amd64?
> 
> Really not loving the M1 Macs. I guess they make y'all happy, but they sure do create problems and complexity on a regular basis that we didn't have to think about before.

Is amd64, windows 10.

**Comment by mlissner** [comment]
That's interesting, Kevin, so it's `(Windows and Mac) vs Linux`, not `arm vs x86` — maybe.

**Comment by albertisfu** [comment]
> We probably shouldn't make a habit of this. We don't want to wind up with tests that don't pass on Macs.

Got it, I'll report it when I found something broken on M1. I'm starting to get disappointed about M1. For example, there is a test in Juriscraper that doesn't work on my M1 related to `lxml` built for M1, I've tried many things and no one worked so I gave up and when I need to run that test I do it in a ubuntu (ARM) virtual machine or in my old (x86) mac. So I thought in this case was something similar.

> That's interesting, Kevin, so it's (Windows and Mac) vs Linux, not arm vs x86 — maybe.

Yeah, this is weird because selenium tests also run well on my old Mac (x86).

**Comment by mlissner** [comment]
I don't think we got a fresh issue open, so I'm just reopening this one so we can figure out how to make selenium work properly...

**Comment by mlissner** [comment]
We're done here, right?

**Comment by flooie** [comment]
I’m not sure yet.  Let me check if this works locally.

**Comment by mlissner** [comment]
Heads up that selenium should work on M1 Macs now. I'm going to close this for good housekeeping, but please reopen it if anybody can't get selenium working with the latest CourtListener/Juriscraper.
