### ISSUE TITLE
Territorial Courts and the Court Picker

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2292]
How do we want to handle for example 

High Court of American Samoa
American Samoa District Court
District of Columbia Court of Appeals
Superior Court Of The District Of Columbia
Tribunal De Apelaciones De Puerto Rico/Court of Appeals of Puerto Rico
Supreme Court of Puerto Rico

etc.

@mlissner 

In general, I think we could start putting territories and DC into the state category.

**Comment by mlissner** [comment]
Well, the picker needs a big overhaul, and we aren't ready to do that atm, so I think we just need to call this a dup of the much bigger issue and get to it when we do the overhaul. If we add all the harvard courts now, we're going to be in a big mess, I think.

**Comment by flooie** [comment]
Well.. we need to add a bunch of courts - to complete opinions.  So whether we move them later or not is fine but we need to insert them into the system.

**Comment by mlissner** [comment]
Probably best to add the new categories to the `JURISDICTIONS` variable:

```
    JURISDICTIONS = (
        (FEDERAL_APPELLATE, "Federal Appellate"),
        (FEDERAL_DISTRICT, "Federal District"),
        (FEDERAL_BANKRUPTCY, "Federal Bankruptcy"),
        (FEDERAL_BANKRUPTCY_PANEL, "Federal Bankruptcy Panel"),
        (FEDERAL_SPECIAL, "Federal Special"),
        (STATE_SUPREME, "State Supreme"),
        (STATE_APPELLATE, "State Appellate"),
        (STATE_TRIAL, "State Trial"),
        (STATE_SPECIAL, "State Special"),
        (STATE_ATTORNEY_GENERAL, "State Attorney General"),
        (COMMITTEE, "Committee"),
        (INTERNATIONAL, "International"),
        (TESTING_COURT, "Testing"),
    )
```

More granularity is usually the answer rather than incorrect categories, I'd say.

**Comment by flooie** [comment]
Great.  Makes sense.  

I would suggest

Off the top of my head

Do you think `Historical` `US Territories` ... `Tribal`?

**Comment by mlissner** [comment]
OK, so we capture historical vs active by putting a value in date_terminated. We don't want to conflate that with this field. And we don't need to mention `US`, I don't think, since that's implied in the others. 

Would: `Territories` and `Tribal` suffice?

**Comment by flooie** [comment]
Where do you put DC?

**Comment by mlissner** [comment]
I think we have them listed as "state" courts now, don't we? That's how they show up in the current court picker anyway. Feels close enough to true to go for it.

**Comment by flooie** [comment]
Yes of course that should go into state.

**Comment by flooie** [comment]
This has been updated in the model.  I think this is resolved.  We will need a new issue for when the full court picker is updated.
