### ISSUE TITLE
Improve court handling in Harvard import

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2296]
We should update our code to use and handle dates during the import.  

We have functionality to use dates in choosing a court and that would be useful to differentiate between `Alaska district court` being used as a pre-statehood federal district court and the current local state trial court.  

Currently we just take the first court found and that is ... not great.  

Instead of how we are currently handling multiple courts found we really should throw an error if we cant find the court.  And we should be using dates to filter our courts down.

**Comment by flooie** [comment]
```
found_court = find_court(
                data["court"]["name"],
                bankruptcy=False,
                location=options["location"],
            )
            if len(found_court) != 1:
                logging.warning(
                    f"Court not found for {data['court']['name']} at {file_path}"
                )
                continue
```

we have code to handle court dates so why we choose to just bail here is beyond me.  @quevon24

**Comment by flooie** [comment]
```
import courts_db
import datetime

print(courts_db.find_court("Alaska District Court", date_found=datetime.datetime.strptime("1783-09-01", "%Y-%m-%d"), ))
```

This is some rudimentary sample code that I think illustrates what we should do.

**Comment by mlissner** [comment]
We used to have all these court regexes in CourtListener itself before splitting them off into the courts_db. Did we ever finish that integration so that the regexes in CourtListener are removed and we *only* rely on courts_db?

**Comment by flooie** [comment]
Just to be clear those court regexes wouldnt have solved this issue.  But I don't think we full integrated courts-db yet.

**Comment by mlissner** [comment]
> those court regexes wouldnt have solved this issue

Right, so we should just yank 'em if we can. My recollection is that courts_db should fully replace those bad boys, right?

**Comment by flooie** [comment]
yes I think so.

**Comment by flooie** [comment]
While im adding quick fixes to the harvard importer, we should allow either some smart bankruptcy parsing, currently we have the flag off for bankruptcy to avoid collisions, but thats clearly not working for the bankruptcy reporter.  Where nothing is found.

**Comment by quevon24** [comment]
I tested all 66418 IA bankruptcy cases, the results are:

- 27 courts couldn't be found in courts-db
- 3 wrong citations
- 15 empty opinions
