### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources' when bumping dependencies

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2318]
When bumping dependencies this strange error arises. 

`ModuleNotFoundError: No module named 'pkg_resources'`

So it's not related to Ipython version so once this issue is solved we need to update it and remove it from dependabot ignore.

**Comment by mlissner** [comment]
This must be fixed, right?

**Comment by albertisfu** [comment]
I think might be closed since it was solved in #2318
