### ISSUE TITLE
Two cases unexpectedly merged

### ISSUE THREAD

**Issue by harlanyu** [freelawproject/courtlistener#2341]
I receive docket alerts for `Floyd v. The City of New York` (1:08-cv-01034) in SDNY. However, this morning, I received an unexpected alert for `No More Deaths v. United States Customs and Border Protection` (1:21-cv-00954), also in SDNY.

When I look at the [docket](https://www.courtlistener.com/docket/4339720/no-more-deaths-v-united-states-customs-and-border-protection/?order_by=desc) on CourtListener, it appears that the "Floyd" case title and heading has been overwritten by the "No More Deaths" title and heading — and the docket entries themselves are unexpectedly merged (this is sorted by Descending). See image.

![image](https://user-images.githubusercontent.com/55959/198079849-63dc0bfa-f759-43b9-b49e-870056610214.png)

Also, this docket `https://www.courtlistener.com/docket/4339720/floyd-v-the-city-of-new-york/` (with `floyd...` in the URL) and the above docket link (with `no-more-deaths...` in the URL) share the same docket ID and page contents.

**Comment by mlissner** [comment]
Thanks Harlan. This is one of those issues that comes up every now and then and we can't figure out where it comes from. My best theory is that there's some kind of race condition in either the extension or a browser that allows our metadata to get screwy when it's uploaded to the API from the extension, but I've never been able to reproduce it.

Instead, it's a bit of whak-a-mole as this kind of thing comes up. It's not great, I'm afraid. 

Anyhow, I've fixed this one. If this comes up again, do let me know, or if you want to spend some time getting back into extension development, you know where to begin. :)

**Comment by harlanyu** [comment]
Haha, thanks Mike!
