### ISSUE TITLE
Need to identify v|Lex blurb timeframe

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2378]
We need to identify a way to identify when a v|Lex sponsored blurb should leave the page.  

Currently we can identify when a blurb should go on to an opinion more or less, but the blurb is not indefinite and we have no mechanism right now to decide when that time has lapsed.

**Comment by mlissner** [comment]
I forget what's in the contract, but couldn't we just do something like:

```
three_year_span = opinion.date_created + timedelta(years=3)
three_year_span > opinion.date_created > datetime(2022-6-01)
```

In other words, X years from when it was created if it was created after the start of the contract?

**Comment by flooie** [comment]
It’s three years. But I was thinking about merged data

**Comment by mlissner** [comment]
Got it. Let's chat tomorrow.
