### ISSUE TITLE
Create new API for DocketAlerts 

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2385]
We don't have an API to allow users to subscribe to Cases and receive docket alerts.

- User should list their own docket alerts.
- Users should be able to POST, PUT, GET, or DELETE to do CRUD operations.

**Comment by mlissner** [comment]
Probably also worth using this in the front end and yanking the code in `toggle_docket_alert`, if that's not too much trouble.

**Comment by albertisfu** [comment]
Yeah, of course, I'll check it out in order to remove `toggle_docket_alert`

**Comment by mlissner** [comment]
If it's more than a bit of work, we can just put comments in the code that tell future devs to yank it the next time they're working on it.
