### ISSUE TITLE
XXX being used as a placeholder page value in Nebraska

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2399]
@mlissner @quevon24 

This one is new to me 

https://www.courtlistener.com/c/neb/293/xxx/

While investigating the Nebraska issue, or more accurately a method to clean it up, I stumbled onto something new. We currently have citations in the system for placeholder values provided by the Supreme Court of Nebraska that I had not seen before.  

This is obviously something we need to clean up, but more research should be done to see if this is an uncommon practice or not.

**Comment by quevon24** [comment]
I might have an idea of what happened here, but i need your knowledge @flooie , if i remember correctly sometimes the opinions are published but there could be the case that the opinion has not been assigned a citation yet, right?

Inspecting the pdf from https://www.courtlistener.com/opinion/3194674/state-v-duncan/ and inspecting the opinion in the Nebraska Appelate Courts Online Library i saw that the pdf formats are not exactly the same, this is the one from CL: https://storage.courtlistener.com/pdf/2016/04/15/state_v._duncan.pdf and this is the one from court site: https://www.nebraska.gov/apps-courts-epub/public/viewAdvanced?docId=N00002996PUB

The pdf from the court site already has the citation in the document (293 Neb. 359) , but the one in CL don't have it.

I inspected the code from cl_scrape_opinions.py command and if the opinion is in CL then is skipped, it doesn't perform an update in the object, in this case specifically it doesn't update the citation.

Maybe when the court site was scrapped the opinion did not yet have a citation and the XXX is a placeholder that they put into the citation? 

I'll keep digging to see if I can find anything else

**Comment by flooie** [comment]
there are only 11, all from Nebraska citations with placeholder XXXs  

I removed them.
