### ISSUE TITLE
Link in webhooks docs to example Docket Entry object yields 403 Forbidden error

### ISSUE THREAD

**Issue by anseljh** [freelawproject/courtlistener#2401]
[Here in the webhooks documentation](https://www.courtlistener.com/help/api/webhooks/#docket-alerts) (😎), there is this link: "[Click here to see an example Docket Entry object](https://www.courtlistener.com/api/rest/v3/docket-entries/20615503/)."

If I click it, I get a 403 Forbidden error. I am logged in.

This is actually [documented elsewhere](https://www.courtlistener.com/help/api/rest/#docket-entry-endpoint), but it's surprising if you haven't read that part of the documentation yet.

> These endpoints are only available to select users. Please [get in touch](https://www.courtlistener.com/contact/) to access these endpoints.

I recommend providing an example another way, perhaps just the test JSON from the webhooks interface, assuming you don't want to open up the Docket Entry Instance endpoint.

**Comment by mlissner** [comment]
I'll do the easy thing and just point people to the testing tool. The first step of the Getting Started doc is also get in touch about gaining this access, but obviously people (ie, you) can arrive there without getting the access first.

**Comment by mlissner** [comment]
This is set for auto merge and deploy. Expect it in about 25 minutes, after tests have passed, the code has merged, the build has built, and the deployment has deployed. Thank you.
