### ISSUE TITLE
Disable Maine Supreme Court scraper

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2448]
Once we're confident we're getting their content directly, we should turn off the scraper so we're not getting it twice. I think we can turn it off via a flag on the Court model. 

We should also put a comment in the scraper that says something like:

> This scrape is not maintained. Future work to gather this data should be done by scraping the CourtListener API [link].

**Comment by flooie** [comment]
Turned off.

**Comment by flooie** [comment]
This is finished
