### ISSUE TITLE
Refactor webhooks code into cl/api/webhooks.py?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2454]
We have a lot of webhooks code now that's kind of spread around. I think we should take a minute to centralize it. I'm thinking of functions like:

 - send_webhook_event
 - send_docket_alert_webhooks
 - send_search_alert_webhook
 - send_old_alerts_webhook_event
 - send_test_webhook_event
 - send_recap_fetch_webhook_event(

And probably some other stuff. There's a bunch of these now that are probably worth centralizing, since they kind of live all over the place. 

What do you think, Alberto?

**Comment by albertisfu** [comment]
Yeah! I agree it would be better to centralize these functions in a single file cl/api/webhooks.py

Working on it...
