### ISSUE TITLE
Fix duplicated appellate docket entries after courts add numbers to entries

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2461]
Since some appellate courts currently don't use document numbers on docket entries, we have dockets that either use the `pacer_doc_id` or the docket entry number is blank. 

Once courts move to add numbers on docket entries and start receiving uploads containing entries with numbers, docket entries will be duplicated.

See: https://www.courtlistener.com/docket/66707696/burback-v-brock/

We should fix duplicated docket entries. Maybe removing docket entries with a long document number (`pacer_doc_id`).

I believe we have also to consider if we should delete all docket entries that use the `pacer_doc_id` as a number or only the ones that are duplicated when a new upload arrives since not all the docket uploads contain all the docket entries.

**Comment by albertisfu** [comment]
I reviewed some cases with duplicated entries due to the switch to numbers from courts.

I don't believe it's a good idea to clean all the entries that have a long number (`pacer_doc_id`) as document numbers in courts that recently switched to numbers because we'll lose entries if nobody uploads those entries again in the future.

So I think we can do the following:

- Create a command that looks for duplicate entries in dockets from courts that recently switched to numbers so we can do a clean-up looking by `pacer_doc_id` entries that are already duplicated.
- When adding new entries from an appellate court that recently switched to numbers, we can look for duplicated entries by 'pacer_doc_id'. If the entry already exists, we could update its metadata, including the new number.
- On docket entries that don't have a `pacer_doc_id`, we could look for duplicates using the date and long description.

@mlissner What do you think about this approach?

**Comment by mlissner** [comment]
That all sounds good to me, but I think we could skip the second step. We already have so much complicated stuff in the merger, it'd be nice not to add something extra. Maybe instead, we can just re-run the management command every now and then.
