### ISSUE TITLE
Update Homepage Search Results Order

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2468]
Order for search results on the Maine page is reverse date filed - but when an opinion is filed on the same day
the order reverts to citation.  This is weird and requires probably a template tag

**Comment by mlissner** [comment]
Hm, well, @albertisfu is researching making `date_filed` into a datetime field in RECAP. I guess if we do the same here, that'd fix this issue, but it'll take a while. See #1790.

**Comment by flooie** [comment]
That won't necessarily fix the date filed + citation issue no?

**Comment by flooie** [comment]
I can deploy a simple fix that filters and sorts by cluster_id and just tell Maine to make sure they put them in order?

**Comment by mlissner** [comment]
It would fix it if they were input in order, yeah, but otherwise no.

Sorting by cluster ID seems reasonable to me. Or don't even tell them, and if it's out of order and they complain you can say that's why. If they still complain we can do the hard thing and sort by citation.

**Comment by flooie** [comment]
I have another easy but annoying solution

**Comment by mlissner** [comment]
Did this get fixed or is it still on your backlog?

**Comment by flooie** [comment]
Resolved.
