### ISSUE TITLE
Fix/Update Docket Sources for Harvard Merge

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2473]
We currently have the wrong number assigned to  the docket source

 SCRAPER_AND_HARVARD = 17  # This should be 18; 17 s/b HARVARD_AND_RECAP.

This needs to be fixed and we should assign the remaining Sources that we are going to come across.

**Comment by flooie** [comment]
0 - just writing down little things to do.

**Comment by mlissner** [comment]
Well that does make it easier!
