### ISSUE TITLE
Complete follow ups to favorites --> Notes rename

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2478]
There are a few remaining issues listed here that we need to wrap up: 

https://github.com/freelawproject/courtlistener/pull/2466#issuecomment-1397813325

**Comment by mlissner** [comment]
This is a bit funky too. We should do:

 - Add note (green)
 - Search (green)
 - Download (blue)



![Image](https://user-images.githubusercontent.com/236970/213601429-869e2e56-299f-4ecf-a670-4363b9877e89.png)

**Comment by flooie** [comment]
No third color?

**Comment by mlissner** [comment]
The icon goes yellow when it has a note, but for now that's as complicated as I think it should be.

**Comment by mlissner** [comment]
An upset user doesn't know where their favorites went because they had the old link to their favorites in their profile and it doesn't work anymore. We need a redirect for that as soon as possible to help our users.
