### ISSUE TITLE
Different authors/opinions totals merger issue

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2494]
I originally was going to group merger issues in one thread but this one atleast appears to be worth its own issue.  

I started checking opinions in our system against the one's in Harvard to compare how common it was to have a different number of opinions between the two.  There appear to be plenty.  

Here is a tricky one. I'm going to layout the issue.

https://www.courtlistener.com/opinion/3307264/harper-v-sloan/
https://ia903102.us.archive.org/34/items/law.free.cap.cal.177/174.2016600.json

-----
In our system we have `four` opinions in the cluster,

| Opinion Type  | Author | Correct | Note|
| ------------- | ------------- | ----- | ---- |
| lead opinion  | Sloss  | √  | |
| concurrence  | Henshaw  | X | There is no concurrence it simply states who concurred |
| dissent  | Melvin  | √ | |
| addendum  | Melvin  | √ | |

----
Harvard has `two` opinions in its cluster. but has three author four author tags- one an error
A majority - authored by SLOSS √
A dissent - authored by Melvin

| Opinion Type  | Author | Correct | Note|
| ------------- | ------------- | ----- | ---- |
| Majority  | Sloss  | √  | |
| dissent  | Melvin  | √+X |  But has two back to back author tags with one having incorrect data |
| addendum  | Melvin  | X | Not identified as an addendum but has some tag id=AET  |

Additionally, the Harvard opinion incorrect identifies four authors, with a bad author tag in the dissent.  

So, the problem here is the errors on both sides of the equation.  I was hoping to use author tags to identify the addendums with the AET tag (or some pattern of it) but I'm not sure yet if that is feasible.  The problem though is that we have an extra opinion on the top and an extra missing one of the bottom.  Perhaps this is just an addendum issue but this would be difficult to just iterate over and compare authors.  

We need to figure out how to ignore the concurrence, ignore the busted author tag, identify the addendums correctly and merge the opinions seamlessly.

1. Ignore busted author 
2. Ignore incorrect concurrence
3. Identify addendums correctly

**Comment by flooie** [comment]
Order is not consistent, Atleast with regard to how things are displayed on Courtlistener.  

In Pyle, see above.  

CL has
---
  Majority -- Dissent -- Dissent -- Addendum

Harvard has 
Majority -- Concurrence (x) -- Dissent -- Addendum -- Dissent

I think this won't be too much of an issue - we will have to most likely do text comparison to identify opinions as opposed to order - or judge names.  Neither combination is going to get us over the goal line every time.

**Comment by flooie** [comment]
This issue - will be resolved - by essentially ignoring it. 

The big picture for this issue is that we have 1) an ordering issue for opinions imported from Columbia that displays them out of order.  And 2) Columbia and Harvard identified opinions differently.  This isn't so much and issue with merging but one that will just rely on the first one introduced.  

In many cases they're maybe a final ruling - that was included in the harvard opinion and separated out in the Columbia dateset.  As you can see from the above that the dataset almost always has an extra opinion in Columbia not Harvard.  

There is a long-ish comment in the harvard merger code explaining this and logging these opinions.

**Comment by mlissner** [comment]
Sorry, one belated thought. Is it always better to just go with whichever has more sub-opinions? So if Harvard has two, go with that, if columbia has two, go with that? I'm thinking more sub-opinions indicates a slightly higher fidelity?

**Comment by flooie** [comment]
We do not want to do that.

**Comment by flooie** [comment]
Offline @mlissner and I spoke about this. 

The complexity/time vs reward here leans toward not defaulting to the longer the better.  
1) Most of the Columbia cluster have more opinions.  This is a bit of a wash because we are going to be adding harvard and then adding more Columbia to them.  

2) the data isn't necessarily better.  In many examples the extra opinion is the final - en banc denial ruling - identified as its own opinion.  These aren't necessarily correct to us.

3) This becomes a very complicated math problem though - if we went down this route because we would need to parse out the missing opinion from the other opinions already in the system.  Then split them apart and merge.
