### ISSUE TITLE
Judges is displayed inside opinion tabs

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2498]
Judges and author both appear inside the tabs.  Judges is not specific to an opinion - but the cluster while author is.  I think the way things are current set up (setting aside the bad html in the judges field) this could certainly lead to confusion by a user about who is the author of an opinion.

<img width="549" alt="Screenshot 2023-01-26 at 2 32 43 PM" src="https://user-images.githubusercontent.com/6464529/214932452-237be31d-e1c8-4e00-ba28-bbba4a26bd8a.png">

-----

<img width="517" alt="Screenshot 2023-01-26 at 2 32 46 PM" src="https://user-images.githubusercontent.com/6464529/214932454-efce5ae9-94ad-46e7-811e-cd0c191e2da6.png">

As is author 
<img width="519" alt="Screenshot 2023-01-26 at 2 34 01 PM" src="https://user-images.githubusercontent.com/6464529/214932566-6eea767f-30b9-48bc-a098-511f3b7c1c81.png">

I would suggest that JUDGES be placed above the tabbed opinions.

**Comment by mlissner** [comment]
Yeah, we should fix this.

**Comment by quevon24** [comment]
I think the judges should go here:
![image](https://user-images.githubusercontent.com/6474994/215206741-a0d28c17-1f80-4f22-a1cc-6a45c014d0c6.png)

Panel is displayed in the same place

About the page number inside the judges field i'm inspecting the json file(https://ia803102.us.archive.org/20/items/law.free.cap.tex-crim.147/114.5300831.json) but seems to be related to incorrect parsing

**Comment by quevon24** [comment]
That case was imported from a columbia case, probably the problem is inside the columbia importer because page number is inside opinion_byline tag, if you load the opinion from harvard json file, the judge is populated correctly.
