### ISSUE TITLE
Opinions presented out of order

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2499]
We have another fantastically fun bug to fix.  

[Daubert-v-Western-Meat-Co](https://www.courtlistener.com/opinion/3306830/Daubert-v-Western-Meat-Co/)

Unfortunately, the order presented by us is not the order it is presented in the book.  We clearly have an order that we present - but the addendums dont actually come at the end.  

In the following view the actual order should be as far as I can tell ....

------

**Lead Opinion** | Dissenting Opinion | **Concurrence** | Addendum Listed Last | **Addendum Listed First**

----
<img width="754" alt="Screenshot 2023-01-27 at 11 03 30 AM" src="https://user-images.githubusercontent.com/6464529/215132585-dafa50e6-2bf1-4222-9f58-e83cb55ca382.png">

**Comment by flooie** [comment]
This feels like a rather bad bug - but im not sure how to fix it.

**Comment by flooie** [comment]
I was hopeful that they were added to the system in the correct order --- but 

'https://www.courtlistener.com/api/rest/v3/opinions/3306610/',  - the lead opinion
'https://www.courtlistener.com/api/rest/v3/opinions/3306611/',  - the final addendum
'https://www.courtlistener.com/api/rest/v3/opinions/3306612/', - the first addendum 'https://www.courtlistener.com/api/rest/v3/opinions/3306613/', - the dissent
'https://www.courtlistener.com/api/rest/v3/opinions/3306614/ - the concurrence 

I wonder why the order was imported in this way, or if this is the correct order in a different book.

**Comment by flooie** [comment]
There are two issues presented here.  one is order - the other is whether something counts as an opinion or not.  I'm going to let this issue stay with the first issue and the one addressed as order.  

The order issue was created by defaulting to order by type during the Columbia import.  

We need to now create an order in the opinion model.

**Comment by mlissner** [comment]
Seems like this *might* be all good now? Want to review and respond, @flooie?
