### ISSUE TITLE
Add support for All Attorney General Opinions

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2509]
Should we add a new tab for attorney general decisions/opinions

**Comment by mlissner** [comment]
This is very much not a priority at the moment. We can get to it when we redo the modal in https://github.com/freelawproject/courtlistener/issues/1243

**Comment by flooie** [comment]
Easiest issue ever.

**Comment by mlissner** [comment]
The easiest way to solve a problem is to...not solve it. :(
