### ISSUE TITLE
We should detect and flag sealed content coming from @recap.email

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2536]
In #2041 we confirmed we're not able to download sealed documents via `@recap.email` notifications.

Now we should be able to detect when a document we get from @recap.email is sealed and mark it as sealed.

- So that we can add a flag in the email saying the document is sealed.
- For the webhook, no further changes will be needed since it already shows the `is_sealed` key

Some options we could use to detect when a document is sealed are:
- The magic link doesn't return a PDF (probably sealed).
- Look for sealed words within the email body.

**Comment by albertisfu** [comment]
To find a reliable method for detecting and flagging sealed content, I searched for every `recap.email` file in our corpus that contained the words "seal" or "sealed". Then, I ran a script to check the status of each of those documents in CL using the RECAP API and then I check every  not available document in PACER to confirm if they are sealed or not.

So that I can find a pattern that indicates whether a document should be sealed or not, this took me a while but I think it was worth it, so here are some findings:

I split the results into two files:

**Main documents that contained seal or sealed words but they are available in CL, findings:**
[main_doc_available.txt](https://github.com/freelawproject/courtlistener/files/10829899/main_doc_available.txt)

Here, the main document is available in CL, which is okay because it's not sealed in PACER.
```
      "docket_number":"3:16-cv-01702",
      "pacer_case_id":"114347",
      "pacer_doc_id":"04107953422",
      "pacer_url":"https://ecf.ctd.uscourts.gov/doc1/04107953422?caseid=114347&de_seq_num=1446&magic_num=49841664",
      "description":"RESPONSE re [459] Order on Motion to Seal, Defendant Cigna Health and Life Insurance Company's Response to the Court's August 30 Memorandum of Order filed by Cigna Health and Life Insurance Company. (Attachments: (1) Exhibit A (Sealed Document))(Shaffer, Brian)",
      "document_available":true,
      "cl_url":"https://courtlistener.com/docket/4552511/462/negron-v-cigna-corporation/",
      "attachments":[
         {
            "attachment_number":1,
            "description":"Exhibit A (Sealed Document)",
            "pacer_doc_id":"04107953423",
            "document_available":true,
            "cl_url":"https://courtlistener.com/docket/4552511/462/1/negron-v-cigna-corporation/"
         }
      ]
   },
```



The attachment is available in both CL and PACER, but the description says  “Sealed Document”. Also, if you look at the document, it only has one page that says it's sealed.

Therefore, I think the solution to flag this kind of document that is available for download is to look at the attachment description on the attachment page. If it contains the words **Sealed** or **Seal** , we should mark it as sealed.

As in the case above, there is another variation where the main document is not sealed, but one of the attachments is sealed. However, the document is available as a PDF with a page saying that it is sealed.

https://courtlistener.com/docket/8507590/419/2/csx-transportation-inc-v-norfolk-southern-railway-company/

The variation here is the the attachment description says:

Exhibit 2 (Filed Under Seal)

Another variation for sealed attachments is when they have a description “*Restricted*”.

https://courtlistener.com/docket/15971537/345/in-re-google-assistant-privacy-litigation/
![Screenshot 2023-02-24 at 19 17 22](https://user-images.githubusercontent.com/486004/221331842-8a5e2d87-2e1f-463c-984a-4471529f132c.png)


- However, we don't have these *Restricted* attachments merged in CL because we have a `sanity_check` that verifies the attachment's `page_count`. If it doesn't have a `page_count`, the attachment is not merged. Therefore, I'm not sure if we should continue omitting these types of sealed attachments or if we should merge them and mark them as sealed?

- Another variation of attachments that should be sealed are the ones that say:
"Exhibit 3 (Filed Under Seal)"

https://courtlistener.com/docket/8507590/424/3/csx-transportation-inc-v-norfolk-southern-railway-company/
The document is available but it only contains a page that says is sealed.

- There is this one that's possibly problematic or a mistake from PACER:
https://courtlistener.com/docket/8507590/424/2/csx-transportation-inc-v-norfolk-southern-railway-company/
Because the document is available and the first page says it's sealed, but then it has some content.

**Main documents that contained seal or sealed words but they are not available in CL, findings:**
[main_doc_not_available.txt](https://github.com/freelawproject/courtlistener/files/10829900/main_doc_not_available.txt)

Checking the list of documents, a document may not be available in CL due to the following reasons:

- The document is sealed
- The magic link was not valid, e.g:

```
{
      "docket_number":"1:20-cv-03010",
      "pacer_case_id":"223205",
      "pacer_doc_id":"04509754186",
      "pacer_url":"https://ecf.dcd.uscourts.gov/doc1/04509754186?caseid=223205&de_seq_num=1695&magic_num=",
      "description":"MOTION for Extension of Time to File Response/Reply as to [495] SEALED MOTION filed by UNITED STATES OF AMERICA, [496] SEALED MOTION filed by STATE OF COLORADO by GOOGLE LLC. (Attachments: (1) Text of Proposed Order)(Schmidtlein, John)",
      "document_available":false,
      "cl_url":"https://courtlistener.com/docket/18552824/497/united-states-of-america-v-google-llc/",
      "attachments":[
         {
            "attachment_number":1,
            "description":"Text of Proposed Order",
            "pacer_doc_id":"04509754187",
            "document_available":false,
            "cl_url":"https://courtlistener.com/docket/18552824/497/1/united-states-of-america-v-google-llc/"
         }
      ]
   },
```

- Document is not sealed but it’s not available in PACER, e.g:

```
{
      "docket_number":"6:21-cv-01269",
      "pacer_case_id":"1155667",
      "pacer_doc_id":"181027895860",
      "pacer_url":"https://ecf.txwd.uscourts.gov/doc1/181127895860?caseid=1155667&de_seq_num=203&magic_num=39433288",
      "description":"Minute Entry for proceedings held before Judge Alan D Albright: Miscellaneous Hearing held on 3/21/2022. Court heard information regarding motion to compel on this and 2 companion cases by zoom. (Minute entry documents are not available electronically.) (Court Reporter Kristie Davis.)(sv)",
      "document_available":false,
			"sealed_on_pacer": true,
      "cl_url":"https://courtlistener.com/docket/61600396/47/google-llc-v-terrier-ssc-llc/"
   },
```

So, based on the fact that not all documents that can't be downloaded are sealed, we need to use a different method to decide when to flag a document as sealed.

In general, I have detected a pattern that can be reliable in detecting when a main document is sealed. The first or second word is often "Sealed". For example, here are some variations in descriptions where the main documents are not available and are sealed on PACER.

```
"[SEALED] DECLARATION re [48] Answering Brief in Opposition...
"Sealed Event, filed. (With attachments)"...
"SEALED MOTION for Leave to File Witness and Exhibit List Under Seal Under...
"[SEALED] REPLY BRIEF re [164] MOTION for..
"Sealed Event, filed...
"SEALED OPPOSITION filed by GOOGLE LLC. re...
"Sealed Consolidated Opposition re [485] MOTION to Seal...
"Sealed Exhibit F re [598] Revised Final...
"UNREDACTED SEALED Declaration of James Barker...
"Sealed Motion :Plaintiffs Renewed Motion...
"Sealed Reply re [455] MOTION to Seal ...
"[SEALED] ANSWERING BRIEF in Opposition re...
"[SEALED] RESPONSE to Order re [152] Order...
"[SEALED] MEMORANDUM OPINION re pending motions...
"Monthly SEALED Document:Financial Institution Plaintiffs...
"Sealed Response/Reply/Opposition re [465] MOTION...
"SELECTED PARTIESDECLARATION of Rob Rickner in Support re:...
"SEALED DOCUMENT filed by UNITED STATES OF AMERICA...
"[SEALED] ANSWER to [41] Answer to Complaint...
"[SEALED] OPENING BRIEF in Support re [104] MOTION...
"[SEALED] RESPONSE to Motion re [93] MOTION...
"SEALED EXHIBIT by Plaintiffs Lisa Bullard...
"SEALED LODGED Proposed Document re: [202] MOTION...
"Document sealed. ORDER RE JOINT DISCOVERY SUBMISSION...
"[SEALED] Letter to The Honorable Gregory B. Williams...
"Sealed Consolidate Opposition re [618] ...
"[SEALED] DECLARATION re [48] Answering Brief...
"[SEALED] STIPULATION Stipulation and [Proposed]...
```
This one "sealed" is not the first or second word but it's within (), so that can be a pattern to.
`"Sentencing Memorandum (Sealed) by USA as to James...`

There are some cases that seem problematic, like this one. The document is not available on CL, which is good because the document is sealed on PACER: `This document is currently under seal and not available to the general public.`

However, the description doesn't follow any of the patterns described above to decide if it's sealed or not. It contains the word "sealed," but we can't just flag everything that has the word "seal" or "sealed" in their descriptions.

```
{
      "docket_number":"3:17-cv-06748",
      "pacer_case_id":"319709",
      "pacer_doc_id":"035022805882",
      "pacer_url":"https://ecf.cand.uscourts.gov/doc1/035022805882?caseid=319709&de_seq_num=1055&magic_num=",
      "description":"Administrative Motion to Consider Whether Another Party's Material Should Be Sealed filed by Tesla, Inc.. (Attachments: (1) Declaration, (2) Exhibit, (3) Proposed Order)(Posner, Daniel) (Filed on 2/4/2023)",
      "document_available":false,
      "sealed_on_pacer": true,
      "cl_url":"https://courtlistener.com/docket/6230785/383/diaz-v-tesla-inc/",
      "attachments":[
         
      ]
   },
{
      "docket_number":"1:19-cv-02170",
      "pacer_case_id":"431918",
      "pacer_doc_id":"123018831097",
      "pacer_url":"https://ecf.nyed.uscourts.gov/doc1/123018831097?caseid=431918&de_seq_num=356&magic_num=11336713",
      "description":"Letter MOTION for Leave to Electronically File Document under Seal (and, to the extent necessary, to supplement the motion/objection record) by Britney Rudler. (Attachments: (1) Exhibit Exhibit 1 - Rider to So Ordered Settlement) (Green, Remy)",
      "document_available":false,
			"sealed_on_pacer": true,
      "cl_url":"https://courtlistener.com/docket/14931431/102/rudler-v-mla-law-offices-ltd/",
      "attachments":[
         
      ]
   },
```

Since not all documents containing the words "seal" or "sealed" in their descriptions should be sealed, for example the following descriptions their documents are not sealed on PACER:

`Memorandum in Support re [618] MOTION to Seal filed by CSX Transportation, Inc.. (McFarland, Robert)`
`Notice of Filing Sealing Motion LCvR5(C) by Norfolk Southern Railway Company re [467] MOTION to Seal (Wingfield, Alan)`


In short:

- To detect and flag attachments as sealed we can look at the description in the attachment page and if it contains the words seal or sealed, we should mark as sealed.
- To detect and flag main documents, we can look at the document descriptions and mark as sealed the ones where the word “Sealed” is the first of second word in the description.
- Or if the word sealed is within (), (Sealed) no matter the position in the description.
- We cannot rely on the availability of the PDF to detect if the document should be sealed since sometimes there is a PDF but it contains a page saying it is sealed. While we could check the PDF content with OCR, the notification/webhook is usually sent before the OCR is completed.
- It appears that in some cases, we may not be able to flag a sealed document. For example, some of the documents mentioned above are not available in CL, and their descriptions do not follow a consistent pattern that would allow us to determine whether they should be sealed or not. However, these documents are sealed on PACER.

@mlissner Please let me know your thoughts on these conclusions, or if you have any suggestions.

**Comment by mlissner** [comment]
OK, I think you probably learned a lot of useful stuff from this, but unfortunately one of your big (and entirely reasonable) assumptions is wrong, sorry. You assume that if a document says it's sealed, then it is. That would make sense, but it's not true. Many documents _start off_ sealed, and then are unsealed. When that happens, they still contain many of the markings of being sealed even though they're not. 

So even [the example you gave of this document](https://www.courtlistener.com/docket/8507590/419/2/csx-transportation-inc-v-norfolk-southern-railway-company/):

![image](https://user-images.githubusercontent.com/236970/221690705-ed8fb889-4014-4fee-8e20-d14acdebaffe.png)

Is not actually sealed. I literally says five words, but those words aren't true anymore.

With that in mind, I think your analysis does help us though. I was hoping that we could just use the ability to download via the magic links as a boolean of whether it's sealed:

```
if can_download_with_magic_link:
   sealed = True
```

But it sounds like you don't think that's right? Or do you think differently now that you've read my message? 

If that doesn't work, then we could use the attachment pages, but they're unreliable too. So maybe the approach is:

 - Attempt with magic link. 
 - If that fails, attempt to buy the document with our account.
 - If we get the receipt page, DON'T buy the document, but we know it's not sealed.
 - If we get an error ("Unavailable document" or something) then we know it's sealed.

That's *if* you still think magic links aren't good enough, and relies on my belief that:

```
if doc_is_available_by_magic_link:
    sealed = False
else:
    # It's unclear if doc is sealed, do further investigation
    ...
```

What do you think?

**Comment by mlissner** [comment]
(I updated my last message a bit to make it more clear.)

**Comment by albertisfu** [comment]
At first, I thought that the magic link would be enough to determine if a document is sealed or not. However, when checking the examples, I found some counterexamples that indicate that it is not enough.

```
"pacer_url":"https://ecf.txwd.uscourts.gov/doc1/181127895860?caseid=1155667&de_seq_num=203&magic_num=39433288",
"description":"Minute Entry for proceedings held before Judge Alan D Albright: Miscellaneous Hearing held on 3/21/2022. Court heard information regarding motion to compel on this and 2 companion cases by zoom. (Minute entry documents are not available electronically.) (Court Reporter Kristie Davis.)(sv)",
"document_available":false,
"available_on_pacer": false,
"cl_url":"https://courtlistener.com/docket/61600396/47/google-llc-v-terrier-ssc-llc/"
```

This is a document that contains a magic link, but it couldn't be downloaded because the document is not available. It literally says on PACER `You do not have permission to view this document.`. However I think this is not sealed, it simply doesn't exist due to being a `Minute entry`, right?

Or like the example above that says: `Exhibit 2 (Filed Under Seal)` where we could download the document. However, it's possible that the document was sealed at the time it was filed?  Also, I checked this document on PACER and it's available to buy (it shows the download confirmation page) if you download it right now it's the same PDF saying is sealed. So that if this is not sealed I think we could rely on the download confirmation page.

So, yes. Based on these examples, I believe it's not enough to rely on whether we could download the document or not to decide if we should mark it as sealed or not.


I agree this approach might work:

```
if can_download_with_magic_link:
    sealed = False
else:
    # It's unclear if doc is sealed, do further investigation
    ...
```

I'm only worried about docs like the example above where the PDF is available but has a page saying is sealed, here is another similar example: https://www.courtlistener.com/docket/4552511/462/1/negron-v-cigna-corporation/
The document is available to buy on PACER but if you download it, it's the same PDF with only one page saying is sealed.

So in case files like these ones are in fact sealed, we'll be able to download them using the magic link and they won't be marked as sealed.

When we can't download a document from the magic link, we can certainly try to download the document and check if there is a download page confirmation or an error message saying the document is not available.

In this case, it worries me that we could mark as sealed documents that are not available but not sealed like minute entries and I think we can not rely on the error message that's shown on PACER (can we?), seems there are different ones like: 

```
This document is sealed.
This document is not available.
This document is SEALED.
You do not have permission to view this document. (This is the one I found on the minute entries.)
```

Let me know what you think about those concerns.
Thank you

**Comment by mlissner** [comment]
> However I think this is not sealed, it simply doesn't exist due to being a Minute entry, right?

Honestly, this one is really weird. I just called the court to learn more about it. They say that they use the document itself to hold notes about the case. My definition of a minute entry is one without a PDF, and my definition of a sealed document is one that you can't download without the right permissions. By those definitions this is NOT a minute entry (even though it says it is), and it IS sealed.

> [For] the example above that says: Exhibit 2 (Filed Under Seal)...was possible that the document was sealed at the time it was filed?

Yes, definitely. Things get unsealed all the time in criminal cases, especially. 

> So, yes. Based on these examples, I believe it's not enough to rely on whether we could download the document or not to decide if we should mark it as sealed or not.

Hm, so the one that says it's "Filed Under Seal" is not sealed and the one that says it's a minute entry IS sealed. Seems like being able to download with the magic link might be enough?

> here is another similar example: https://www.courtlistener.com/docket/4552511/462/1/negron-v-cigna-corporation/
> 
> So in case files like these ones are in fact sealed, we'll be able to download them using the magic link and they won't be marked as sealed.

This one says it's sealed, but again, it's not. If you can download it from PACER, it's not sealed, no matter what the text of the document says. 

> In this case, it worries me that we could mark as sealed documents that are not available but not sealed like minute entries 

But I think those are technically sealed if you ask me.

> and I think we can not rely on the error message that's shown on PACER (can we?),

I think I'm repeating myself, but just to be thorough, no, we can't rely on the text of the documents. No matter what the PDF says, the core question is whether you can download it. PDFs will say "Sealed" when they're originally filed under seal, and then later when they're unsealed, they still say they're sealed (since that's what they said).

**Comment by mlissner** [comment]
Hey, fun, the court confirms that the weird minute entry is in fact sealed. They say:

> The entry does have a document attached, however, it is sealed to the public. 

Good!

**Comment by albertisfu** [comment]
Understood. Since the court has confirmed that the minute entry is sealed, and those with a PDF that says they are sealed are not actually sealed. We can rely on the fact of not being able to download a document with the magic link is enough to mark a document as sealed.

So that we can do something simple like:

```
if can_download_with_magic_link:
    sealed = False
else:
   sealed = True
```

So there won't be necessary to do further investigation trying to buy the document, right?

**Comment by mlissner** [comment]
I think that's right, yes!

**Comment by albertisfu** [comment]
Great, working on that, thanks!

**Comment by albertisfu** [comment]
@mlissner  your post on slack made me look for `Minute Entry` in our `recap.email` corpus, yeah there are minute entries with attached documents (document link) and there are some without document links, these are not being added by recap.email since we have a validation that only adds content with a `pacer_doc_id`, so no risk to mark these as sealed.

But I found others like:

```
<table border=0 cellspacing=0>
<tr><td><strong>Case Name:</strong>
</td><td>In re Tesla Inc. Securities 
Litigation</td></tr>
<tr><td><strong>Case Number:</strong></td><td><A 
HREF=https://ecf.cand.uscourts.gov/cgi-bin/DktRpt.pl?330489>3:18-cv-04865-EMC</A></td></tr>

<tr><td><strong>Filer:</strong></td><td></td></tr>

<tr><td><strong>Document Number:</strong></td>
<td>
<a href="https://ecf.cand.uscourts.gov/doc1/035022812318?caseid=330489&de_seq_num=2369&magic_num=" 
>670</a> 
</td></tr>
<tr><td><strong></strong></td><td></td></tr>
</table>
<p>
<strong>Docket Text:</strong>
<BR>
<FONT  FACE="arial,helvetica" COLOR="#0000cc" SIZE=3><b>
<b>Minute Entry  for proceedings held 
before Judge Edward M Chen: Jury Trial  held on 2/3/2023. <p>
Total Time in Court: 4 hours, 56 minutes. <p>
Court Reporter: Belle Ball.  (Attachments:  # (1) Trial Log)(vla, COURT STAFF) 
(Date Filed: 2/3/2023)
</b></Font>
</p>
```
Entries like these are not going to be downloaded due to they don't have a `magic_number` so following our logic this will be marked as sealed. However, on PACER it's available, so I think this is not sealed right?

We have other similar cases where there is no `magic_number` but the document is available on PACER, like this one: https://www.courtlistener.com/docket/18735353/233/federal-trade-commission-v-meta-platforms-inc/  (I confirmed it was uploaded via RECAP extension)

So that if the documents above are not sealed I think we could change our logic to say something like:

```
if can_download_with_magic_link:
    sealed = False
elif not magic_number:
   # It's unclear if doc is sealed, do further investigation checking if there is a download confirmation page when trying to buy 
   # the document.
else:
   sealed = True
```

What do you think?

**Comment by mlissner** [comment]
Your approach sounds right to me. It's weird that these don't have magic numbers. Any theories why?

It sounds like a bug that we're not adding minute entries, right?

**Comment by albertisfu** [comment]
I checked many of the files that don't have a magic number and I didn't find a pattern that might indicate why they don't have a magic number, it happens o sealed documents, not sealed, minutes entries, not minutes entries, so might be an error from the courts? for now, I think the approach of confirming its seal status on PACER might work.

 yeah, not adding minutes entries without an attachment is a bug, I'll open an issue to fix it.
