### ISSUE TITLE
Clean up mis-matched dockets and re-do docket_number_core

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2549]
Now that #2472 is merged. We need to find all the mis-matched cases and fix them.

@mlissner I believe your query described in [#2472](https://github.com/freelawproject/courtlistener/issues/2472#issuecomment-1406869349)  is correct to find mis-matched dockets.
`ds = Docket.objects.filter(source=16, pacer_case_id__isnull=False)`

However, not all the cases returned by this query are incorrect. So I'll add add some additional code to filter the mis-matched ones. I think comparing the cleaned docket_number might work.

Once we have compiled a list of the affected cases, we must consider the following actions:

- Should we update the affected docket by restoring its data from the opinion and re-doing the docket number core?
- Alternatively, should we retain the mismatched docket and create a new docket using the original opinion, then replace its relation to the opinion?
- Check if the mis-matched is duplicated or not in order to keep it or delete it.

**Comment by mlissner** [comment]
When you start working on this, some examples would be helpful. It might be good just to chat through your questions once you're a bit further along.
