### ISSUE TITLE
Dockets without documents can't be searched

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2572]
The RECAP Archive is a document-centered search engine, and only searches RECAP Documents (whether they have PDFs or not). This means that for the ~50M dockets we have from PACER that don't have entries, they don't show up in the search engine at all. That's a real bummer.

Two other problems with RECAP search are:

1. Solr is sad, dying, and old. It should really be replaced.
2. The performance isn't great because of how it groups responses. 

We should look into replacing it with Elastic search and figure out how to solve these three problems at the same time.

**Comment by albertisfu** [comment]
When working on this and moving RECAP to ES we need to consider making documents searchable by `pacer_doc_id`.

**Comment by mlissner** [comment]
> When working on this and moving RECAP to ES we need to consider making documents searchable by pacer_doc_id.

I'm not sure that we have an issue for this, but we should go through all the metadata on RECAP dockets and decide which of it should be searchable that isn't already. I forget if we have an issue for this, but let's make one if needed.

**Comment by mlissner** [comment]
I'm confident dockets will soon be searchable. Closing.
