### ISSUE TITLE
opinions csv file - texts with commas makes the file unusable

### ISSUE THREAD

**Issue by ramnavan** [freelawproject/courtlistener#2588]
Opinions CSV file from [here](https://com-courtlistener-storage.s3-us-west-2.amazonaws.com/list.html?prefix=bulk-data/) (example file name: opinions-2023-02-28.csv.bz2) has xml and full text stored as one of the columns. These texts have commas, which makes the CSV file not appropriately rendered. 

Has any faced similar challenges? Curious to see if there is a workaround.

**Comment by flooie** [comment]
hmm... 

@ramnavan I don't have the same issue.  You should able to read the csv file with the CSV module.

**Comment by warrenronsiek** [comment]
Took me a second to figure out that I needed to read the `bz2` file directly and not uncompress it first. If you uncompress, you start running into a whole host of issues.

**Comment by ramnavan** [comment]
I see. I did uncompress and that why ran into issues. Thanks a lot!
