### ISSUE TITLE
Figure out why our poor DB suffers from huge CPU spikes every night at 1am PST, and fix it

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2597]
We have a script called `scrape_pacer_free_opinions`. It runs every day at 08:00UTC each day and scrapes about 1,000 PDFs from PACER. After it scrapes them, it extracts their contents and adds those contents to the DB. This is *easily* the heaviest lift our poor DB does:

![image](https://user-images.githubusercontent.com/236970/226709950-64f909a1-dc54-4915-8137-391d1fe3566f.png)

Let's find a way to spread this out. We can introduce delays, send things to celery more slowly...it doesn't really matter. We just want to make sure not to hammer the DB with 1,000 new documents like we do currently.

**Comment by mlissner** [comment]
Hmmm, the DB doesn't look much happier last night: 

![image](https://user-images.githubusercontent.com/236970/234338417-ecc3af02-4afe-4fd8-bc4d-6a5757b02971.png)

I admit I'm a bit stumped. It should have deployed yesterday, so this should have been fixed, but it looks unchanged.

**Comment by albertisfu** [comment]
Got it. Hopefully, that solves the problem!

**Comment by mlissner** [comment]
Cool. The latest is deployed. I'll monitor tomorrow or the next day.

**Comment by mlissner** [comment]
I'm sorry to say that this was deployed successfully, but seemed to make no difference at all:

![image](https://user-images.githubusercontent.com/236970/236600816-f42f5338-e493-4178-b6f5-f7ca6d670972.png)

Thoughts?

**Comment by albertisfu** [comment]
@mlissner I have a theory of why this didn't improve.

The problem might be processing the OCR for documents that needed it. 

Could you confirm if the command is run with the `--do-everything` param?  

If so, the command first run: `get_and_save_free_document_reports` and then `get_pdfs`.

After `get_pdfs` finishes scheduling all the tasks `ocr_available` is called. But that only happens for all the `RECAPDocument` that have been downloaded/processed so `ocr_available` might be not processing all the PDFs of the day.

The next day when `ocr_available` is executed it processes many PDFs from the previous day, since `ocr_available` is not throttled this might be consuming a lot of CPU. 

I also suspect that there might be some documents that might be timing out so they never get processed and every day they are retried, could we run the following query? So I can check the returned results and confirm we're processing RDS from the previous day and also if there are PDFs with conflicts from a long time ago.

```
from cl.search.models import RECAPDocument

ocr_needed_rds = RECAPDocument.objects.filter(ocr_status=RECAPDocument.OCR_NEEDED).values_list("pk", flat=True).order_by()
print("OCR Needed: ", list(ocr_needed_rds))
```

According to the results, the solution might vary:

- Wait until all the rows are processed before executing `ocr_available` or processing the OCR within the same `get_pdfs` task.
- Throttling `ocr_available`
- Omit old recurrent failing documents.

**Comment by mlissner** [comment]
Hm:

```
In [2]: ocr_needed_rds = RECAPDocument.objects.filter(ocr_status=RECAPDocument.OCR_NEEDED).values_list("pk", flat=True).order_by()
   ...: print("OCR Needed: ", list(ocr_needed_rds))
OCR Needed:  [16693057, 200892240, 16749755]
```

**Comment by mlissner** [comment]
Here's the logs from this morning (Monday):

```
│ scrape-free-opinions-28058880-sbckj INFO Getting PDFs from free document reports                                                                                                   
│ scrape-free-opinions-28058880-sbckj INFO downloading and indexing 3261 items from PACER.                                                                                           
│ scrape-free-opinions-28058880-sbckj INFO Sent 1000/3261 tasks to celery for downloading and indexing so far.                                                                       
│ scrape-free-opinions-28058880-sbckj INFO Sent 2000/3261 tasks to celery for downloading and indexing so far.                                                                       
│ scrape-free-opinions-28058880-sbckj INFO Sent 3000/3261 tasks to celery for downloading and indexing so far.                                                                       
│ scrape-free-opinions-28058880-sbckj INFO Doing OCR and saving items to Solr.                                                                                                       
│ scrape-free-opinions-28058880-sbckj INFO Sent 1/3 tasks to celery so far.   
```

It's kind of interesting that we get the CPU spike whether or not it's the weekend.

**Comment by albertisfu** [comment]
Thanks, interesting, these are just a few of the elements that require OCR so I don't think the CPU spike has a relation to OCR.

These logs from today can be considered from the weekend or a weekday? I assume fewer documents are available over the weekend.

- On average how many documents are downloaded on weekends vs weekdays?

- In my tests, the throttling is working and it spread the tasks properly using the `court_id` as a throttling key but I just test it downloading documents from a single court, I'll do some tests for multiple courts as in the real process and check if throttling is working as expected or it might need a lower rate.

- Might be any other process that is run at the same time?

**Comment by mlissner** [comment]
I think it's about 1000 docs that we add with this script per weekday. 

This was run this morning, Monday, which would make it a correspond with yesterday's content (a weekend). That means it shouldn't have had much content to download.

I don't think it's another script, but I can disable this cronjob for a day and see if it helps. Why not?

**Comment by albertisfu** [comment]
Interesting, yeah the `ping_google` sounds probable since the cache of partial sitemaps last for 24 hours if Google downloads them immediately every day, the generation of fresh sitemaps might be hammering the DB. 
Let's confirm if that's the problem and we think about how to solve it, maybe spreading the generation of partials sitemap during the day so they're not generated at the same time and all of them are available once Google downloads them.

**Comment by mlissner** [comment]
I'm going to be sad if it's sitemaps. They've sucked up so much time over the years. It turns out it's really hard to generate a list of millions of URLs on a site like ours....

**Comment by mlissner** [comment]
Huh, too bad. Got the CPU spike last night too. I guess it's time to check the API logs?

**Comment by albertisfu** [comment]
@mlissner here is some code that can help us get the users doing the most requests to the API in a given day.

So you could check the top N users across different days and then we could see if there is a pattern where a user is requesting the API a lot on different days.

The method also returns the user IP on that day if available.

```
from cl.lib.redis_utils import make_redis_interface

def get_top_users_and_ips(r, date_str, top_n=10):
    # Get the key for the user counts and ip map for the specific day
    user_count_key = f"api:v3.user.d:{date_str}.counts"
    ip_map_key = f"api:v3.d:{date_str}.ip_map"

    # Get the top N users and their query counts
    top_users_with_scores = r.zrevrange(user_count_key, 0, top_n - 1, withscores=True)

    # Get all the IP to user mappings for that day
    ip_user_map = r.hgetall(ip_map_key)
    user_ip_map = {user: ip for ip, user in ip_user_map.items()}

    top_users_ips = []
    for user, count in top_users_with_scores:
        # Get the IP for the user
        ip = user_ip_map.get(user, None)
        top_users_ips.append((user, count, ip))

    return top_users_ips


r = make_redis_interface("STATS")
date_str = "2023-05-11" # Day to check
top_n = 10 # Number of top users to return
top_users_ips = get_top_users_and_ips(r, date_str, top_n)


for user, count, ip in top_users_ips:
    print(f"User {user} made {count} queries on {date_str} from IP {ip}.")
```

**Comment by mlissner** [comment]
I ran the following across about ten dates to find users that spiked on each of the ten days:

```
    ...:for date_str in dates:
    ...:     top_users_ips =get_top_users_and_ips(r, date_str, top_n)
    ...:     new_users = set([i[0] for i in top_users_ips])
    ...:     if users:
    ...:         users &= new_users
    ...:     else:
    ...:         users = new_users
```

There are three likely candidates. I'll discuss via Slack since they're clients.

**Comment by mlissner** [comment]
Here's a more accurate view of last night: 

![Image](https://github.com/freelawproject/courtlistener/assets/236970/f89915e4-54f3-41ee-ae77-ea10bd6842f4)

It starts right at 8UTC, and goes for about 17 minutes.

**Comment by mlissner** [comment]
Well, I think I nailed this down and contacted the client that was making meddlesome API requests. The problem was that they were making requests like: 

https://www.courtlistener.com/api/rest/v3/docket-entries?docket__id=&order_by=-date_created

Those don't filter anything and they order 300M items by date. Not great! I think this might have been OK when we had fewer items and the real problem is that we keep adding more content via the Troller import. 

In any case, the way to identify this in the future is to get the CloudFront logs from S3 for the hour when there's the outage, and then search them for troubling patterns. Once you've got the requests causing trouble, you can grab the IP address and put it some code like this:

```
In [4]: from cl.lib.redis_utils import make_redis_interface
   ...: def get_user_by_ip(r, date_str, ip_address):
   ...:     # Get the key for the specific day
   ...:     key = f"api:v3.d:{date_str}.ip_map"
   ...: 
   ...:     # Get the user_id associated with the IP address
   ...:     user_id = r.hget(key, ip_address)
   ...:     return user_id
   ...: 
   ...: r = make_redis_interface("STATS")
   ...: date_str = "2023-05-25"
   ...: ip_address = "xxx.xxx.xxx.xxx"
   ...: user_id = get_user_by_ip(r, date_str, ip_address)
   ...: if user_id:
   ...:     print(f"User {user_id} associated with IP address {ip_address}.")
   ...: else:
   ...:     print(f"No user ID found for IP address {ip_address} on {date_str}.")
```

That'll return:

```
User N associated with IP address xxx.xxx.xxx.xxx.
```

And then you write an email. I'm going to go disable this user's API access and we'll see if that fixes things for tomorrow.

**Comment by mlissner** [comment]
This. Is. Fixed.

**Comment by mlissner** [comment]
While fixing it last time, I encouraged one of our clients to use the API more. Well, they did, and now they're a problem. Last night they took out the server by making a number of queries like this:

https://www.courtlistener.com/api/rest/v3/docket-entries/?court__id=njch&court__date_modified__gt=2023-05-31T00:00:00Z&order_by=-date_modified

That query isn't great and asks for the entire docket_entries data set ordered by date_modified. 

Understanding logs is a big pain the way I was doing it before, so I got AWS Athena figured out and played with it a bunch. My process was:

1. Go into RDS monitoring and identify when the issue started and ended. 

2. Using those numbers, [query the logs][1] for top users. I have a saved query for this purpose, but it looks something like this:

```sql
SELECT request_ip, COUNT(request_ip) requests
FROM cloudfront_logs
WHERE 
  "date" BETWEEN DATE '2023-06-02' AND DATE '2023-06-02' 
  AND "time" BETWEEN '08:15' and '10:30' 
  AND "uri" like '/api/%'
  -- request_ip = 'xxx.xxx.xxx.xxx'
GROUP BY request_ip
ORDER BY requests desc
LIMIT 50;
```

Then, using the top IPs, see what the kinds of queries are. In today's example, the top IP was for a bing server, and number three was the troublesome client. To query the URLs for a particular IP, you can do:

```sql
SELECT 
  request_ip, 
  date,
  time,
  SUBSTR(user_agent, 1, 15),
  method,
  uri, 
  query_string
FROM cloudfront_logs 
--TABLESAMPLE BERNOULLI(10) -- 10% sample
WHERE 
  "date" BETWEEN DATE '2023-06-02' AND DATE '2023-06-02' 
  AND "time" BETWEEN '07:30' and '10:45' 
  --AND "uri" like '/api/%'
  AND request_ip = 'x.x.x.x'
--ORDER BY RANDOM()
ORDER BY date desc, time desc
LIMIT 500;
```

(Note a few tricks in there for getting samples or random data orders.)

Finally, once you're convinced you've got the bad IP address in hand, look up the user:

```python
from cl.lib.redis_utils import make_redis_interface
def get_user_by_ip(r, date_str, ip_address):
    # Get the key for the specific day
    key = f"api:v3.d:{date_str}.ip_map"

    # Get the user_id associated with the IP address
    user_id = r.hget(key, ip_address)
    return user_id

get_user_by_ip(r, '2023-06-01', 'x.x.x.x')
```

Still not particularly easy, but it's getting there...

[1]: https://us-west-2.console.aws.amazon.com/athena/home?region=us-west-2#/query-editor/history/6353fe59-d348-4c3a-9c4b-ad40838ab2e8
