### ISSUE TITLE
Add Sort ordering to docket-alerts page

### ISSUE THREAD

**Issue by troglodite2** [freelawproject/courtlistener#2637]
It would be nice to have the ability to order RECAP Docket Alerts

**Comment by mlissner** [comment]
Nice! I think that's the right idea, but I'd suggest using the Angle Up/Down icons from Font Awesome: 

https://fontawesome.com/icons/angle-up?f=classic&s=solid

Also:
 - Maybe don't make the headers blue? 
 - Maybe use the `gray` class from our CSS on the icons?

Thanks. Nice little enhancement. We need about a hundred of these.

**Comment by troglodite2** [comment]
![image](https://user-images.githubusercontent.com/82225842/231289005-4f2ec257-7203-49c4-8830-a55d8471f850.png)

**Comment by mlissner** [comment]
The header should still be black like it is now. Just the icons get the gray?

**Comment by troglodite2** [comment]
The headers, "Case Name ^" is an anchor. I put `class="gray"` on the <a> element.  I think I would need to put a <span> around italics to get it to be gray and the rest of the anchor black.  The cheat uses a template tag to figure out which direction the caret should be.

```
<tr>
              <th><a class="gray" href="[?order_by=name](view-source:http://127.0.0.1:18000/profile/docket-alerts/?order_by=name)">Case Name&nbsp;<i class="fa fa-angle-up"></i></a></th>
              <th><a class="gray" href="[?order_by=court](view-source:http://127.0.0.1:18000/profile/docket-alerts/?order_by=court)">Court&nbsp;<i class="fa fa-angle-down"></i></a></th>
              <th colspan="2"><a class="gray" href="[order_by=hit](view-source:http://127.0.0.1:18000/profile/docket-alerts/order_by=hit)"> Last&nbsp;Hit&nbsp;<i class="fa fa-angle-up"></i></a></th>
          </tr>
```
Let me know what class(es) you want for the `<a>` and `<i>` elements and I'll put them in there.
I couldn't find a class for "black" easily.

**Comment by mlissner** [comment]
Try:

```
class="no-underline black-link"
```
With the gray on the icon?

**Comment by troglodite2** [comment]
![image](https://user-images.githubusercontent.com/82225842/231293350-c3f55a6c-255d-4c11-baea-5ba80e266eb5.png)

**Comment by mlissner** [comment]
Nice! Thanks!
