### ISSUE TITLE
Get the short description from recap.email NEFs

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2638]
We have a client that needs to get short descriptions for their use case. Sure enough, we can get these from the subject line of the NEFs even though we're not presently. 

Let's:

1. Take a look at a couple dozen random subject lines from different cases, and...
2. Make a parser for them in Juriscraper, and...
3. Get that parser working, so...
4. The short_description field is populated in our DB and webhooks.

**Comment by mlissner** [comment]
Seems like this one is done and we should tell our client?

**Comment by mlissner** [comment]
Can you confirm if this is completed, Alberto?

**Comment by mlissner** [comment]
@albertisfu, can you confirm if this is done? Or maybe Gianfranco knows?

**Comment by albertisfu** [comment]
Yes, this was done via [#675](https://github.com/freelawproject/juriscraper/pull/675) for courts had examples.

Also I think Gianfranco has been working on adding support for more courts.

I believe we still need to add support for multi-docket NEFs, as described in [#914](https://github.com/freelawproject/juriscraper/issues/914), and for other courts for which now we have examples in [#912](https://github.com/freelawproject/juriscraper/issues/912).

So, I think @grossir could give us a better status update on this. However, I believe we can  close this one and focus on the other issues.

**Comment by mlissner** [comment]
Right. I wasn't sure if this was that same project he's working on. Since it is, I'm comfy closing this. We get notifications from Sentry when new courts pop up, and he's been fixing them bit by bit (though we should really move towards heuristics now that we have so many examples).

Thanks!
