### ISSUE TITLE
Flynt Fails on PR

### ISSUE THREAD

**Issue by troglodite2** [freelawproject/courtlistener#2642]
The lint workflow runs Flynt as part of the PR processing.  Even though Flynt passes when run with pre-commit locally it fails in the workflow.  In addition the error message given by Flynt does not identify what, if anything, the issue is with the code being pushed.

**Comment by mlissner** [comment]
I have a strong feeling this is Github having some intermittent failures, but I haven't had time to check if people are complaining on Twitter or if the Github Status pages knows anything. It seems to work if you re-run it, I think?

**Comment by troglodite2** [comment]
I haven't had a single success with flynt on github in the last two days.  I don't think I can just rerun it.

**Comment by mlissner** [comment]
This issue seems to be affecting other repos too. @ERosendo is having some trouble over in freelawproject/bigcases2 also.

**Comment by mlissner** [comment]
@albertisfu slipped a fix into one of his PRs. Some of your code was failing flynt. I'm not sure why the error wasn't better, but his fix was to make your code use an f-string instead of `"xxx" + "xxx"`-style string concatenation.
