### ISSUE TITLE
Docket Alert Sort order on last hit puts "Never" as newest

### ISSUE THREAD

**Issue by troglodite2** [freelawproject/courtlistener#2648]
The recently added code did not account for never correctly.  It puts the "Never" as more recent than any given date.
This can be fixed by putting using the correct `.desc(nulls_last=True)` or `.desc(nulls_first=True)` on the queryset.

**Comment by mlissner** [comment]
Nice one. Did you do a PR for this too?

**Comment by troglodite2** [comment]
Not yet
