### ISSUE TITLE
manage.py make_dev_data aborts with duplicate key

### ISSUE THREAD

**Issue by troglodite2** [freelawproject/courtlistener#2662]
By default, certain objects make other objects. In this case, make_dev_data --make-objects 104 creates docket entries.  We want lots of docket entries.  Each docket entry creates a fake court.

The CourtFactory creates a fake position via Faker.  Since this is a random number, there is a chance of a collision.  The position field is unique in the database.  When the random numbers happen to match up, the command fails.

**Comment by mlissner** [comment]
I've run into this too. The good news is if you just re-run things, it'll probably be fine, but it'd be nice to fix it, for sure.

**Comment by troglodite2** [comment]
I'm looking for the "right way" to fix this.  It will be a bit, I just didn't want to lose it.

**Comment by troglodite2** [comment]
It looks like there are two possible ways to move forward with this.  The first is to not use the `Subfactory()` factory and instead use the `Iterator()` factory.  `Iterator()` will take a list and select from that list in order.  So we go from
```
class DocketParentMixin(DjangoModelFactory):
    docket = SubFactory(
        "cl.search.factories.DocketFactory",
        # Set the case names on the docket to the ones on this object
        # if it has them. Else generate the case name values.
        case_name=LazyAttribute(
            lambda self: getattr(
                self.factory_parent,
                "case_name",
                str(Faker("case_name")),
            )
        ),
```
To: 
```
class DocketReuseParentMixin(DjangoModelFactory):
    docket = Iterator(Docket.objects.all())
```
The other option, which I've not explored yet, is to somehow pass in a docket id.  Then we can use the `django_get_or_create` metadata so that we only create a docket when it doesn't already exist and all the DocketEntries being created are attached to the named docket.
