### ISSUE TITLE
tests fail after cloning test database

### ISSUE THREAD

**Issue by troglodite2** [freelawproject/courtlistener#2667]
```
docker exec -e SELENIUM_DEBUG=1 -e SELENIUM_TIMEOUT=30 cl-django python /opt/courtlistener/manage.py test cl --verbosity=2 --tag selenium --parallel
...
 Applying waffle.0004_update_everyone_nullbooleanfield... OK
Cloning test database for alias 'default' ('test_courtlistener')...
Cloning test database for alias 'default' ('test_courtlistener')...
Cloning test database for alias 'default' ('test_courtlistener')...
Cloning test database for alias 'default' ('test_courtlistener')...
Cloning test database for alias 'default' ('test_courtlistener')...
Cloning test database for alias 'default' ('test_courtlistener')...
Cloning test database for alias 'default' ('test_courtlistener')...
Cloning test database for alias 'default' ('test_courtlistener')...
Cloning test database for alias 'default' ('test_courtlistener')...
Cloning test database for alias 'default' ('test_courtlistener')...
System check identified no issues (2 silenced).
ERROR
```
At this point, everything stops.  I've let this run for over 4 hours, and it hasn't moved forward.

This test was run on a `docker-compose -f courtlistner/docker-compose.yml up -d` No tmpfs involved.  So there was no old database.  All the docker images were fresh.  `git checkout -f main` was performed just before the tests were run.

The error occurred locally and in the workflow test on a PR push.  Finally, this does run when we have the --exclude-tag selenium

**Comment by troglodite2** [comment]
This is the command that shows the error without hanging
`./manage.py test -v 3 --parallel=1 cl.alerts.tests.AlertSeleniumTest`

**Comment by mlissner** [comment]
Have you read the dev notes about testing with selenium? Give that a try, sometimes it can shake something loose, but Selenium is not fun.

**Comment by troglodite2** [comment]
Yes, I have.  I've also switched to "main" with only docker-compose changes to expose ports where there is no conflict.  This does not seem to be an issue directly with my code.

**Comment by troglodite2** [comment]
On the 21st of April, version 112.0 of selenium/standalone-chrome was released.  My development process includes a full build with fresh pulls of all images.  Version 112 failed.
Today, the 24th, I changed my local development environment to pull version 111.0 and all tests passed.

**Comment by mlissner** [comment]
Great. Do we have version 111 pinned or do we just pull the most recent?

**Comment by troglodite2** [comment]
The workflow uses docker/courtlistener/docker-compose.yml to build the test environment.

```
  cl-selenium:
    container_name: cl-selenium
    image: seleniarm/standalone-chromium
```
Selenium can be pinned by adding `:111.0` to the image command.
I can do this but want feedback before I do.

**Comment by mlissner** [comment]
Yep, let's pin it.
