### ISSUE TITLE
Documents in RECAP not showing in Docket list

### ISSUE THREAD

**Issue by troglodite2** [freelawproject/courtlistener#2668]
https://www.courtlistener.com/docket/59726366/united-states-v-ervin

Document Number 258 originally showed 
![image](https://user-images.githubusercontent.com/82225842/234040588-630db126-02b8-46e9-b738-5b172d808282.png)

When I clicked on buy on PACER and was logged in, PACER showed:
![image](https://user-images.githubusercontent.com/82225842/234040897-3e51f1ba-3bbe-49e4-a2bd-b85a36c2a7eb.png)

When I reloaded the Docket on RECAP, it now shows:
![image](https://user-images.githubusercontent.com/82225842/234041088-5bbcae5d-a932-4b4f-a29e-cd278774c2ac.png)

But you can see that Attachment 1 is marked in PACER as having a copy in RECAP, but it only shows a purchase link in RECAP

In a similar vain, Document Number 257 shows only the purchase option, but the PACER page shows it already exists in RECAP.

**Comment by mlissner** [comment]
This is a manifestation of the doppellganger bug: https://github.com/freelawproject/courtlistener/issues/2185. Thanks for filing, but we'll want to just close this one and maybe someday deal with that one.
