### ISSUE TITLE
Add signals to add oral argument data to Elastic Search as it's changed/created

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2676]
Once we've got the index ready and our fields in a good place, we'll start ingesting the live data in parallel with the data going to Solr. We'll probably use Signals for this.

**Comment by mlissner** [comment]
`cl_update_index` is mostly used as a one-time thing to get the data into Solr in the first place, and years ago I used it for more maintenance tasks before sort of giving up on keeping Solr in perfect sync. 

I think it's worth it to send every update to ES that we can, automatically, so that it is always as well-synced as possible. It bugs me that Solr falls behind the DB and maybe we can do better with ES.

**Comment by albertisfu** [comment]
Got it. So I'll add signals to update the index also when related objects are updated in the database. So we can have everything in sync.

About `cl_update_index`, seems it can be replaced by the Django elasticsearch built-in commands.

**Comment by mlissner** [comment]
> About cl_update_index, seems it can be replaced by the Django elasticsearch built-in commands.

I think so. It just depends on performance, I think. If the ES commands don't perform well enough for our huge collection, we might have to either upgrade those (if possible?) or write our own again. I think we'll find out about this soon...
