### ISSUE TITLE
Migrate oral argument API to use Elastic Search

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2680]
It's unclear if we'll need to launch API v4 for this or if we'll be able to silently migrate people. It'll depend on search queries and how hard it is to move people over. If we can shut down Solr though, without having to have a long deprecation period, that'd be real nice!

**Comment by albertisfu** [comment]
This one is completed, but I'm not sure if we should close it until we document everything and inform users how to migrate to the new ES V3 version or V4.

**Comment by mlissner** [comment]
I think we have other issues for the overall migration, no?

**Comment by albertisfu** [comment]
Yeah this one: https://github.com/freelawproject/courtlistener/issues/3874
