### ISSUE TITLE
Switch oral argument front end interface to use Elastic Search

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2681]
I think this will be the last piece of the switch to Elastic Search for oral arguments: Switching the front end. We could just do a swap and keep the HTML kind of how it is. I'm also open to making this better by using HTMX if that's a good idea. We'll see how we feel when we get to this step!

**Comment by albertisfu** [comment]
The HTML for the front-end interface for OA arguments barely changed. It just required renaming some variables according to the Elasticsearch response. Let me know if you would like to add any additional features, such as using HTMX to update results without reloading the page.

**Comment by mlissner** [comment]
I'm very interested in making the front end better using HTMX, but not at this moment.

**Comment by mlissner** [comment]
Pretty sure this is done. If it's not, it will be when we flip the right waffles. Closing.
