### ISSUE TITLE
Document our redirection APIs

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2714]
We have two APIs that work by redirection. You look something up, and it gives you a redirection to a good URL on CourtListener. We should document these:

1. **Citation Redirector**

    This lets you look up a citation and get redirected to a case. There's some documentation about it as [a blog post](https://free.law/2015/11/30/our-new-citation-finder), but that's not very good. We should do better.

3. **PACER ID Redirector**

    This lets you look up a case by pacer court and ID and get a CL docket. It's not documented at all, but you can give it a URL like:

    ```
    storage.cl.com/recap/gov.uscourts.njd.284693 (with or without a trailing slash)
    ```
    When you do, a lambda will redirect you to the WWW version of the URL:
    ```
    www.cl.com/recap/gov.uscourts.njd.284693
    ```
    And if you hit that, a very simple lookup and redirection will happen (or 404 if it can't be found). People should use the www to avoid the lambda and extra redirect, but it's not a big deal if they don't, and we plan on not doing so in bots.law. 

Both of these redirectors should be documented in the API docs, including clear notation of the HTTP status codes to expect when things work/fail/are ambiguous.

**Comment by troglodite2** [comment]
I'm looking into this.

**Comment by troglodite2** [comment]
![image](https://user-images.githubusercontent.com/82225842/236928483-e0fcb4e9-2e53-4df9-aaa8-280e20927a4d.png)

This warning message is badly worded.  The curl instruction above does not fail with an authentication error.  It works.  It might be better to move this message later in the documentation and to replace it with a NOTE instead of an ALERT.

**Comment by mlissner** [comment]
Maybe it should just say:

> You didn't authenticate to the API, but it worked anyway. This is deliberate to encourage experimentation, but the biggest gotcha people run into is that the forget to enable authentication before deploying their code. Unauthenticated requests are quickly throttled, then things break. Don't let this happen to you! Remember to [add authentication].

People make this mistake all the time, so I want this early in the docs so people actually read it.

**Comment by mlissner** [comment]
We have a new citation API and so the old one is no longer worth documenting. Closing.
