### ISSUE TITLE
Revamp Citation Lookup

### ISSUE THREAD

**Issue by troglodite2** [freelawproject/courtlistener#2735]
Two issues, one is that in the Opinions drop down the text is "look up" and on the actual page it is "lookup tool"
![image](https://user-images.githubusercontent.com/82225842/236576368-afc309c8-a039-41b2-9c44-273b98353749.png)
![image](https://user-images.githubusercontent.com/82225842/236576332-d63e3eb1-3ed1-4206-8b0b-592a8121cef1.png)

The current Citation Lookup tool requires the user to parse a citation and input volume, reporter, and page.  We have the tools to do for the user using eyecite.

Change from using 3 input fields on the Citation Lookup home page to just one field.
![image](https://user-images.githubusercontent.com/82225842/236576597-29f536d7-6ccb-4bfc-96dc-182b1f19a6ee.png)
Becomes:
![image](https://user-images.githubusercontent.com/82225842/236576794-9d17ccb1-7305-47c1-8ef7-161ca229fb54.png)

![image](https://user-images.githubusercontent.com/82225842/236576879-6c036b79-2115-4a3b-89d4-cb82a9f103d0.png)

360px:
![image](https://user-images.githubusercontent.com/82225842/236577017-bb2a227f-ab75-465e-997a-05bf22ad0818.png)

767px:
![image](https://user-images.githubusercontent.com/82225842/236577102-04a5c504-cace-44b6-b001-ecef23ea5c5a.png)

768px:
![image](https://user-images.githubusercontent.com/82225842/236577179-33cc784f-4872-4668-bb0c-066a2200739a.png)

**Comment by mlissner** [comment]
Looks like a nice improvement. I think bootstrap makes it pretty easy to do a combined lookup button. Want to try something like on the homepage? 

![image](https://user-images.githubusercontent.com/236970/236581635-d82532c2-543a-4a6b-b2f6-27dace52ee3f.png)

It'd be nice if it weren't full width as well, kind of like the homepage, since full width just looks sort of out of control.

**Comment by troglodite2** [comment]
Desktop:
![image](https://user-images.githubusercontent.com/82225842/236646635-3c053af6-89c4-4abe-88af-51298493687d.png)

Mini:
![image](https://user-images.githubusercontent.com/82225842/236646664-4a5fe150-ee92-4651-9c38-be9416412606.png)

xs:
![image](https://user-images.githubusercontent.com/82225842/236646676-8b23b4e5-6018-4f0e-b950-0e9f05211b56.png)

xs+1:
![image](https://user-images.githubusercontent.com/82225842/236646686-20ad6bea-71c3-473e-a066-9ea368d9018c.png)

sm:
![image](https://user-images.githubusercontent.com/82225842/236646696-99ca8a5c-b36d-4353-b7c0-62ce8e3ecc45.png)

sm+1:
![image](https://user-images.githubusercontent.com/82225842/236646717-63204c52-1983-4fc1-b9a5-46f41e96dd35.png)

**Comment by mlissner** [comment]
Sure, looks good. On the small sizes, it'd be nice if you could see the reference instead of just:

> District of Columbia v....

You could shorten it to `D.C. v. Heller`, and that might help?

**Comment by troglodite2** [comment]
The citation in the input box was my copy paste to show it with input.
There is no placeholder.

**Comment by mlissner** [comment]
Great, thank you.
