### ISSUE TITLE
DB connection issue after libpq upgrade

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2827]
I'm opening this issue to describe my findings about the DB connection issue we experienced today, so we can solve it before doing new deploys.

- This issue was not caught in dev because the default `sslmode` in dev is `prefer` which doesn't use an SSL connection.
- I replicated the issue locally by changing the `sslmode` to `require` and using an RDS `PostgreSQL` instance for testing (since `cl-postgres` doesn't support SSL).
- The issue is the one described here: https://github.com/nginx/unit/issues/834 . From `libpq 15.1`, it consults the `HOME` environment variable to find the user's home directory. If it's not set, it falls back to the previous method of checking the `<pwd.h>` database, which in our case appears to be `/root`.
- So in the last build `libpq` and `postgresql-client` were upgraded from `13.11-0+deb11u1` to `15.3-0+deb12u1`. However, it's peculiar that they were updated just now when version 15 has been available since `2022-10-13`. I suspect previous versions might have already been removed from the repositories.
- In order to reproduce the issue locally I had to create the file `/root/.postgresql/postgresql.crt`. If this file doesn't exist, it's ignored and the connection is performed without using a client-side certificate. It doesn't seem to be required in `require` mode, as it doesn't authenticate the client, but encrypts the connection.
- Are we using this certificate in production? Otherwise, the issue seems to be that even if `postgresql.crt` doesn't exist in production, access to `/root` is denied, which triggers the issue.

- Therefore, the solution is to set an environment variable `HOME` to a folder that is accessible (with sufficient permissions). This folder can be read, and since `postgresql.crt` won't exist there, it can be ignored and a one-way SSL connection can be performed.

**Comment by mlissner** [comment]
This all sounds good and more or less makes sense, thanks. I don't know why this is affecting us now, as opposed to back in 2022 when the 15.1 libpq came out. Maybe it didn't make its way to ubuntu's repositories?

Anyhow,

> Are we using this certificate in production?

In prod, we have it set to 'prefer', but it was set to 'require' before yesterday. It'd be nice to get it back to `require` again, but no, we're not using a certificate in prod that I'm aware of.

This comment seems to indicate that if you just point postgresql at a dummy location, it works fine:

https://github.com/nginx/unit/issues/834#issuecomment-1410297997

I assume you're working on a fix though either of this sort or setting HOME?

**Comment by albertisfu** [comment]
> This all sounds good and more or less makes sense, thanks. I don't know why this is affecting us now, as opposed to back in 2022 when the 15.1 libpq came out. Maybe it didn't make its way to ubuntu's repositories?

Yeah, that's pretty strange I also suspect it was an issue related to ubuntu's repositories.

> This comment seems to indicate that if you just point postgresql at a dummy location, it works fine:

Yeah, I also tested this approach of setting `PGSSLCERT` env var to `/tmp/postgresql.crt` and it also works.

> I assume you're working on a fix though either of this sort or setting HOME?

Well, I tested both approaches in my local env using an RDS PostgreSQL instance using `require` mode and it worked.

I added:
```
environment:
      - PGSSLCERT=/tmp/postgresql.crt
```

To `docker-compose.yml `. It also works setting this var in `.env.dev`

However, for development, this is useless since the dev `cl-postgres` instance doesn't use an encrypted connection. 
Maybe,  it would be a good idea to give `cl-postgres` SSL support so we can catch issues like this in the future, let me know if I should work on it and see if it's viable to use SSL in dev.

For production, I think I can't set the env var due to permissions,  but it'll be enough to set `PGSSLCERT=/tmp/postgresql.crt` before doing a new deployment that will update `libpq` and `postgresql-client`.

**Comment by mlissner** [comment]
Yeah, let's see if we can use encryption in dev too, thanks.

**Comment by mlissner** [comment]
> For production, I think I can't set the env var due to permissions, but it'll be enough to set PGSSLCERT=/tmp/postgresql.crt before doing a new deployment that will update libpq and postgresql-client.

I can set a variable like this via k8s, but I think we usually reserve the k8s env files for settings that need to be configured (like a DB password). 

Would it make more sense to set this via `ENV` in our dockerfile? Either way, we should make sure to have a comment pointing back here.
