### ISSUE TITLE
Bad data caused false citation count

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#283]
The unusual case name for this case got parsed wrong at r.org and we didn't notice it either. Then the citator matched "U.S. v." too often and it thinks this non-case has been cited hundreds of times, which it hasn't. I've corrected the citation, case name, etc., and am just filing this to ask that the citation count for this thing be unwound, as it's wrong. See: https://www.courtlistener.com/ca11/4HPy/us-v/

**Comment by mlissner** [comment]
This will get fixed next time we run the citator, which we'll do very soon. Marking as done.
