### ISSUE TITLE
@recap.email does not avoid sealed docket entries (it only does sealed documents)

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2835]
Right now, when @recap.email gets a NEF about a sealed document, we can identify that by trying to download the document. If we successfully get it, we know it's not sealed, and if we can't get it, it is. Simple enough.

In [this docket](https://www.courtlistener.com/docket/6923200/mwk-recruiting-inc-v-jowers/?order_by=desc), you can see that there is no public entry for number 399. This is *not* because the entry doesn't exist. It's because the entry *itself* is sealed, as well as the document. 

When this is the case:

1. There is a gap in the numbering of the public docket. For example, if docket entry 3 is sealed, the docket will show numbers 1 and 2, skip number 3, and immediately show number 4.

2. The attachment page will fail as well.

Our error in this instance was to parse the NEF and to add the entry to CL while marking the document as sealed. Instead, we should have figured out that the entry was sealed, and added nothing to the site.

To fix this issue:

1. When we identify that a document is sealed...
2. We should check if the attachment page for it is available.
    - If so, we should not add anything to our DB.
    - If not, then we should do what we do now (add the entry, but mark the doc as sealed)

What else?

**Comment by albertisfu** [comment]
Reviewing this one I got a couple of questions:

- I found the recap.email for 399 but I don't see the 399 entry in the docket, I'm assuming you removed it after noticing this issue? Was it sealed before removing it?

Checking the docket right now there are only two entries querying entries between 395 and 400.

![Screenshot 2023-06-27 at 10 33 49](https://github.com/freelawproject/courtlistener/assets/486004/c605313e-90be-469c-9fce-a05bc90d5778)

So yeah 399 is not public.

- Currently, we don't log in when checking if a document is sealed. If there is a magic link available and the document can't directly be retrieved we assume it's sealed.
- When checking this document on PACER it returns the following error message:
![Screenshot 2023-06-27 at 10 21 31](https://github.com/freelawproject/courtlistener/assets/486004/5946b670-2ea4-4a5a-a629-4abd24e2d6af)
 I'm wondering if the message `could not retrieve dktentry for...` it's a hint to assume the entry is not public, if we are not sure it will be helpful to have more examples of not public docket entries to confirm this is a pattern.
- For example when a document it's just sealed but the entry is available we get a message like this:
![Screenshot 2023-06-27 at 10 24 54](https://github.com/freelawproject/courtlistener/assets/486004/94653da5-a062-44fd-a11e-93ba39ba9024)
- To detect these not public entries I'm afraid we'll need to authenticate when the document is not available to confirm the error message.

Let me know what do you think.

**Comment by mlissner** [comment]
> I found the recap.email for 399 but I don't see the 399 entry in the docket, I'm assuming you removed it after noticing this issue?

Yes.

> Was it sealed before removing it?

It was always sealed. If you look at the email we sent, you'll even see that our email said the doc was sealed, but we failed to notice that the docket entry was sealed.

> I'm wondering if the message could not retrieve dktentry for... it's a hint to assume the entry is not public, if we are not sure it will be helpful to have more examples of not public docket entries to confirm this is a pattern.

That's a really good theory. I don't know, but @johnhawkinson *might*, though he doesn't deal with a lot of sealed content either.

> if we are not sure it will be helpful to have more examples of not public docket entries to confirm this is a pattern.

Yeah. I guess we could find those by looking for gaps in dockets, but that's a pretty tough approach...

I'm not sure otherwise though.

> To detect these not public entries I'm afraid we'll need to authenticate when the document is not available to confirm the error message.

Yep. So we'll try to get the document without logging in, then if that detects it's sealed, we'll log in and try to get the entry.

**Comment by johnhawkinson** [comment]
> > I'm wondering if the message could not retrieve dktentry for... it's a hint to assume the entry is not public, if we are not sure it will be helpful to have more examples of not public docket entries to confirm this is a pattern.
> 
> That's a really good theory. I don't know, but @johnhawkinson _might_, though he doesn't deal with a lot of sealed content either.

Well, I don't know what "hint" means.

There are various messages that you get when you try to retrieve entries that are sealed, restricted, or nonexistent, and it is not always obvious from the outside which ones are which. But you can certainly poke around any sealed case or partially sealed case and explore the patterns. And there are sometimes `de_seqno`s or even actual docket sequence numbers that give different messages, sometimes the same as a too-high number and sometimes not. That's because there are internal court entries that are not, per se, sealed.  I would not assume that the messages are necessarily consistent from ECF instance to ECF instance (but they might be).

So, I guess…you gotta do some tests. I guess Mike is right that I've done some in the past but I do not recall the results ;)

**Comment by albertisfu** [comment]
Understood, thank you.

Well, I believe I could begin by reviewing the recap.email corpus since we started marking sealed documents, so I can try to find within these documents if there are any others whose docket entry is not public on PACER, which could help us identify a pattern in the error messages.

The data from the email doesn't appear to be useful in helping us identify whether the entry is not public on PACER. For example:

396 (public)
https://ecf.txwd.uscourts.gov/doc1/181130184849?caseid=946427&de_seq_num=1510&magic_num=82307386

399 (not public)
https://ecf.txwd.uscourts.gov/doc1/181030413635?caseid=946427&de_seq_num=1517&magic_num=10454147

They're pretty similar.

**Comment by johnhawkinson** [comment]
FYI, I don't think it is a wise practice to publicly post `&magic_num=` URL fragments here on Github, even if they are theoretically "exhausted."

I think you'll find that the text of the document description from the email may give you some reasonable heuristics.
I don't know what 399 said, though.

**Comment by albertisfu** [comment]
Got it, I removed magic_num from links.


This is 399
![Screenshot 2023-06-27 at 17 06 36](https://github.com/freelawproject/courtlistener/assets/486004/16514756-ed1d-4304-8551-4c39fbed9532)

And 396
![Screenshot 2023-06-27 at 17 07 00](https://github.com/freelawproject/courtlistener/assets/486004/175c7f45-72b7-4627-90e3-37a42a2b959c)

**Comment by johnhawkinson** [comment]
If you were foolish enough to go down this rabbit hole, I think you'll find the rules about _ex parte_ filings are super confusing, and they are not in fact technically sealed, but they are often treated like they are. (I filed one once and I came away very confused, although nobody complained).

Anyhow, though, I think you'll find any item with an `EX PARTE` prefix will be by default restricted, at least in W.D. Tex.
So, too, for `SEALED`. Probably several other things.

**Comment by albertisfu** [comment]
Yes, I don't think it's a good idea to try to figure it out from the description. I'll try to find a pattern based on the error message when attempting to download the document.

**Comment by johnhawkinson** [comment]
Just to be clear, I disagree, and think you should use the text as a heuristic. Especially if you look at the HTML and avoid the "free text."

**Comment by albertisfu** [comment]
> Especially if you look at the HTML and avoid the "free text."

Do you mean the email HTML or the HTML page when opening the document link?

I'll review examples and see if we can do something with the text hopefully there is a pattern on `EX PARTE` or related in order to detect sealed docket entries.

**Comment by johnhawkinson** [comment]
I mean the HTML associated with the docket text, which is in the email, and is also available if you were to run the docket report (costs money), but not available in the HTML page opening the document link.

**Comment by johnhawkinson** [comment]
For instance, C.D. Cal. does it like this, labeling the prefix more clearly as `SEALED EX PARTE` rather than merely `EX PARTE`:

<img width="1375" alt="Screen Shot 2023-06-27 at 20 49 14" src="https://github.com/freelawproject/courtlistener/assets/1270718/7d37f1e4-6bdf-4904-a2f6-241ab5b3a1ae">

with HTML like this:

```HTML
<strong>Docket Text:</strong>
<BR>
<FONT  FACE="arial,helvetica" COLOR="#0000cc" SIZE=3><b>
  SEALED EX PARTE APPLICATION <i>RESPONDENTS 
EX PARTE APPLICATION FOR LEAVE TO SEEK REDETENTION OF CLASS MEMBER ANDRE 
LUIZ COSTA SOARES</i>  re  Order,,,,,,,,,,,,,,,,,,,,,,,, [686],  Protective 
Order[122],  Order,, [1685]   filed by Respondents Matthew T. Albence, James 
Janecka, David Marin, Chad F. Wolf. (Attachments:  # (1) Declaration Mercado 
Decl., # (2) Exhibit Mercado Decl. Ex. A, # (3) Exhibit Mercado Decl. Ex. 
B, # (4) Declaration Peterson Decl., # (5) Exhibit Peterson Decl. Ex. 1, 
# (6) Exhibit Peterson Decl. Ex. 2, # (7) Exhibit Peterson Decl. Ex. 3, # 
(8) Exhibit Peterson Decl. Ex. 4, # (9) Exhibit Peterson Decl. Ex. 5, # (10) 
Exhibit Peterson Decl. Ex. 6, # (11) Exhibit Peterson Decl. Ex.7, # (12) 
Exhibit Peterson Decl. Ex. 8, # (13) Exhibit Peterson Decl. Ex. 9, # (14) 
Exhibit Peterson Decl. Ex. 10, # (15) Exhibit Peterson Decl. Ex. 11, # (16) 
Exhibit Peterson Decl. Ex. 12, # (17) Proposed Order, # (18) Certificate 
of Service)(Mercado-Santana, Victor)

</b></Font>
```

And the "free text" is the text within the `<i>…</i>` tags.

**Comment by mlissner** [comment]
Why bother with buying the docket or trying to be clever with the text of the email when you can just check the attachment page for free and be certain?

**Comment by johnhawkinson** [comment]
I think Alberto was trying to avoid authenticating.
Also, there may not be an attachment page as there may not be attachments.

**Comment by mlissner** [comment]
I don't mind authenticating and checking that way, but...yeah, not having an attachment page is a bummer. I guess in that case, we could just go and buy the entry for a dime. 

My assumption is the HTML won't ever be trustworthy, so we just have to do this extra check sometimes and suck it up.

**Comment by johnhawkinson** [comment]
Well, I mean, it's apparent from the receipt page whether the document is available, no need to pay for it.

**Comment by johnhawkinson** [comment]
> Yes, it seems that checking the docket entry text in the email isn't useful for determining if the entry is sealed. I looked for emails containing the `EX PARTE` prefix, such as in `399`, but the entries or documents weren't sealed.

You're saying 399 was the only one? (!)

Another confounding factor is that things that are initially (or provisionally) sealed don't always stay that way. Good luck. Certainty may be hard to come by.

**Comment by ERosendo** [comment]
I reviewed this issue and followed @albertisfu's suggestion to check if the message in the attachment/receipt page is a  reliable indicator for sealed docket entries. 

While our initial investigation (focusing on entry 399) wasn't enough to prove Alberto's theory, we decided to go through all sealed documents in the [development database](https://github.com/freelawproject/courtlistener/wiki/The-CourtListener-Development-Database), focusing on loading receipt pages, hoping to uncover more evidence and build a more comprehensive sample set to re-evaluate the hypothesis.

I found **2,338 sealed record**s from **75 different** courts in the development database. You can find a detailed breakdown of the courts and record count in the following CSV file.

[courts.csv](https://github.com/freelawproject/courtlistener/files/14216353/court-distribution.csv) 

After running the script to analyze the receipt pages of these documents, I discovered **57 instances** of the "could not retrieve dktentry..." message. Upon manual verification, I confirmed that all 57 records correspond to sealed docket entries.

This finding aligns with Alberto's theory that we can use this specific message to efficiently identify sealed entries. Moving forward, we can implement this approach to avoid adding these entries to the docket report.

The list of all identified sealed docket entries is provided in the following .csv file:

[sealed-entries-full.csv](https://github.com/freelawproject/courtlistener/files/14216733/sealed-entries-full.csv)
