### ISSUE TITLE
"Rap Stats" for the law

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#286]
See http://genius.com/rapstats . This is cool. (And very responsive!) We should allow people to do similar searches on our entire corpus. The ability to compare multiple terms via comma-separation is particularly nice. We'd want to allow people to select jurisdictions as well.

Bonus: make it easy to screenshot, tweet your results, or even contribute your result to some sort of public repository.

**Comment by mlissner** [comment]
I'm going to close this one in lieu of #622, which has the terminology correct.
