### ISSUE TITLE
Bulk data empty for Courts

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2863]
<img width="483" alt="Screenshot 2023-07-05 at 2 48 22 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/7ddb4a0d-d89a-49d6-a001-6f47f3f80162">

**Comment by flooie** [comment]
For the most recent bulk export for courts - appears to be empty

**Comment by mlissner** [comment]
What's inside? I suspect this is related to the error we had with postgresql needing an upgrade?

**Comment by flooie** [comment]
it errors when trying to unzip ... there are a few other that are like this. 

people-db-retention - whatever this is -- doesnt have any working data.

<img width="901" alt="Screenshot 2023-07-06 at 7 20 38 AM" src="https://github.com/freelawproject/courtlistener/assets/6464529/b3214f35-e328-49c2-b765-7fa8ef938d5b">

**Comment by mlissner** [comment]
Hm, it's a bz2 file, and it opens OK for me. Were you trying to unzip it as if it's a zip? Inside there's one file and it's blank, but I don't think the bz2 is corrupted. 

I think retention events is empty b/c we don't have any.

I don't know why courts failed, but I think it'll be back next month. I'm not *super* worried about it, at least not yet.

**Comment by flooie** [comment]
I get an error message - that states the file is empty.

**Comment by mlissner** [comment]
Looks like the bulk data was fine this month. Closing, but if this happens more or again, let's dig deeper.
