### ISSUE TITLE
Fla. Dist. Ct. App. cases from 1018 A.D.

### ISSUE THREAD

**Issue by cweider** [freelawproject/courtlistener#2873]
A [batch of cases in Fla. Dist. Ct. App.](https://www.courtlistener.com/?q=&type=o&order_by=dateFiled%20asc) are recored as filed January 22nd, 1018:

<img width="1217" alt="Screenshot 2023-07-10 at 12 02 14 PM" src="https://github.com/freelawproject/courtlistener/assets/45040/90aee962-47ae-473d-9b2e-fadfcee2b16c">

I can only guess what happened during ingestion. Chances are good that it was an issue on the court’s side (all Fifth District). Probably a candidate for manual correction.

What’s might be more interesting for CourtListener is that the information from the opinion page does not match the information on the search results page:

<img width="562" alt="Screenshot 2023-07-10 at 12 02 56 PM" src="https://github.com/freelawproject/courtlistener/assets/45040/e12c484c-6328-41e9-becb-821d60210136">

Maybe there an issue with the index not getting updated?

**Comment by mlissner** [comment]
Yeah, that's wonky. Alberto is re-doing our search engine now, so I think we can close this if the data itself is correct. I know he's being a lot more thorough about getting updates from the DB to the search engine than I was when I did this (he's using signals, whereas I just had things going from the Django save routine). 

I think in general if we see errors in search we should file those things in case they haven't been fixed, but this one at least I feel pretty good about.
