### ISSUE TITLE
Faster site means more people getting ID'ed as bots

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2876]
All the work we've done to move the site to async seems to be having an amusing (?) result: More people being I.D.'ed as bots. I need to loosen the Web Application Firewall in AWS (WAF).

cc: @ttys0dev

**Comment by mlissner** [comment]
Actually, it could be other ratelimiters, not the WAF. I asked the user experiencing this to send a screenshot.

**Comment by ttys0dev** [comment]
> All the work we've done to move the site to async seems to be having an amusing (?) result: More people being I.D.'ed as bots.

Maybe the site was just too slow to respond requests to even trigger a rate limit previously?

**Comment by mlissner** [comment]
Yep. That's my theory.

**Comment by mlissner** [comment]
Hm, fewer complaints about this. Maybe it's fine. Setting this aside for now.
