### ISSUE TITLE
"Cases Citing" page should link to the original case

### ISSUE THREAD

**Issue by morninj** [freelawproject/courtlistener#289]
E.g., https://www.courtlistener.com/ca2/3y9U/brandir-international-inc-v-cascade-pacific-lumber/cited-by/ should include a link to https://www.courtlistener.com/ca2/3y9U/brandir-international-inc-v-cascade-pacific-lumber/

**Comment by mlissner** [comment]
@morninj, thanks for this one, but I'm closing it. This page is now [handled via the search results][1].

**Comment by mlissner** [comment]
Thanks again for pushing on it though. I sort of wish we had done something here, but I think the current outcome is even better.
