### ISSUE TITLE
Locate haikus in corpus

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#290]
Use https://github.com/jdf/haikufinder to locate haikus in the corpus. Use API to link haikus back to their case of origin. Optionally, follow FastCase's lead and allow people to upvote and downvote the better/worse haikus, see: http://haiku.legalgeekery.com/ (This is just for fun.)

**Comment by mlissner** [comment]
This is fun but useless. Sorry. We've gotten too serious and will never get to this. Harvard did it already, anyway.
