### ISSUE TITLE
Is it time to stop reporting CSP errors?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2911]
I think after a week of false positives, there seems to be little sign of it slowing down. Should we disable CSP violation reports? 

I wish we could filter these better, and I just put in a request with Sentry to see if they have any advice. Failing that, should we just turn it off?

**Comment by cweider** [comment]
If the reports aren’t slowing down, probably. The decision about whether or not to enforce, I think, comes down to whether or not we’re satisfied that the reports heretofore are _not_ bugs in CourtListener, but, instead, unexpected (arguably undesirable) behavior from browsers (via extensions).

In the situation that we enforced, but that we don’t report, future CL changes that violate the CSP will bugs like any other that we don‘t have visibility to (all frontend changes?) and which ideally are caught during development/prior to deployment.
