### ISSUE TITLE
Figure it out node group affinity when mounting EBS volumes.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2949]
Following up #2946  we need to figure it out how to add node-group affinity or something similar in order to avoid volumes to be attached to other node-groups that we don't want, I'll perform a couple of tests to check it this out.

This can also be related: 
What would happen if in some moment we need to move the nodes to a new node-group (e.g in case we need to increase resources), the process that we currently followed to do that is to create the new node-group, change it in the `yaml` file and deploy. New pods will be generated within these new nodes and the older ones terminated. But what would happen with volumes? We'll want that volumes are detached from old nodes and attached to the new ones, without generating new ones.  I can also do a experiment for this.

**Comment by mlissner** [comment]
> But what would happen with volumes? 

This is a good question. Assuming it doesn't work seamlessly, I guess we could do it by hand. I'd expect the new nodes would have their own storage attached, and we'd "just" have to move the storage from the old nodes. I think I saw at some point that Elastic has an API for moving shards, so I guess that'd be the approach:

 - Load the new nodes with empty disks.
 - Migrate the shards from the old nodes.
 - Kill the old nodes.

Doesn't sound fun and who knows how it works under production load...

**Comment by mlissner** [comment]
Relates to #2867

**Comment by albertisfu** [comment]
I've reproduced the resize process, increasing the `Persistentvolumes` size in the manifests and applying the changes.

The EBS volumes resized properly. I couldn't reproduce the issue relating to volumes being attached to a different node group than the Elasticsearch one. Maybe those extra volumes were also related to a previous test? Since Kibana manifest doesn't mount an extra EBS volume; it uses the volume that is mounted by default to the EC2 instance.

Regarding the other question:

I read [documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html#k8s-upgrading) and performed some tests to confirm how the node-group migration process works.

The process to migrate the elastic-search instances to new node-group is the following.

1.- Create a new node group, selecting instances with the same or more resources/nodes than the current node group.
2.- Wait until the new EC2 instances are created.
3.- Modify the Elasticsearch manifest:
  - Change the nodeSet name to a different one.
  - Change the node-group
4.- Apply the manifest. New Elasticsearch pods will be created one by one. ECK will move shards and replicas from the old nodes to the new ones. The old pods will be terminated as the new ones are created.
5.- Confirm that the data was properly migrated to the new nodes (Kibana can be used for this).

After migration, all documents and shards should be identical.

![Screenshot 2023-07-26 at 1 40 41](https://github.com/freelawproject/courtlistener/assets/486004/44b0d43a-6755-4cab-a4df-da35facd7dc0)

![Screenshot 2023-07-26 at 9 20 13](https://github.com/freelawproject/courtlistener/assets/486004/da5c51b1-371e-4348-8576-c3f34a1a56a4)


6.- Released 'persistent volumes' can be removed from Kubernetes and from EC2.
7.- Remove the old node group so that EC2 instances are also removed.

There is a [recommendation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-storage-recommendations.html#k8s_reclaim_policy) in documentation  to use the `Delete` `reclaimPolicy` on the storage class. By default ECK removes the `Persistentvolumeclaims` when nodes are removed, but Persistentvolumes are not removed. That's why released volumes need to be removed manually as described in step 6.

Therefore, if we want the volumes to be automatically removed, we can change the `reclaimPolicy` to `Delete`. However, we'll need to create a new `StorageClass` with a different name (since they're immutable), create a new `NodeSet` with a different name, update the `StorageClass`, and deploy the elastic manifest file. New pods will be created and the data will be migrated, while the old pods are terminated.

In a brief ECK will take care of data migration when creating a new `NodeSet` or perform pods maintenance tasks. However there are some limitations that should be considered as described in [documentation](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-orchestration.html#k8s-orchestration-limitations), maintenance tasks with no down time can't be guaranteed while working on:

- Single-node clusters
- Clusters containing indices with no replicas
