### ISSUE TITLE
Some documents in RECAP are the wrong ones

### ISSUE THREAD

**Issue by epicfaace** [freelawproject/courtlistener#2956]
For example, https://www.courtlistener.com/docket/63290154/306/missouri-v-biden/. I'm not sure if there's a form to report these or take these down (or why they happen in the first place -- misconfigured / bugs in the RECAP extension?)

**Comment by mlissner** [comment]
Thanks for reporting this. It used to happen pretty regularly, but we found the bug, finally, that was causing it. 

@ERosendo can you put analyzing this on top of your list for today? @albertisfu should be able to help with the CL-side of things, if needed, but it'd be great to just spend a few minutes to make some notes. Once you've got that, I can delete the document to clean up the mess, and we can actually fix the issue later, using your notes.

**Comment by ERosendo** [comment]
Sure thing! I'll take a look at it.

**Comment by ERosendo** [comment]
My efforts to recreate this issue have unfortunately been unsuccessful but here are my findings about it:

- After checking the CL records, I found that the document was uploaded using the processing queue `9221988`.

- According to the processing queue, the file was uploaded by the RECAP extension.

- The data in the processing queue `9221988`, which includes the `pacer_case_id`, `pacer_doc_id`, and `court information`, corresponds with the data we collect from the [download page](https://ecf.lawd.uscourts.gov/doc1/08907398060?caseid=189520).

- The mixed-up document belongs to entry 20 of [case 23-1116](https://www.courtlistener.com/docket/67263515/blueprint-capital-advisors-llc-v-state-of-new-jersey-division-of/) from the Court of Appeals for the Third Circuit. We didn't have the document in case 23-1116 when I reviewed the issue.

- I used the extension to upload the document from the Court of Appeals for the Third Circuit and it worked fine. The document is available [here](https://www.courtlistener.com/docket/67263515/20/blueprint-capital-advisors-llc-v-state-of-new-jersey-division-of/).

- After comparing the two document records, I noticed that they have a different hash value.

**Comment by mlissner** [comment]
> After comparing the two document records, I noticed that they have a different hash value.

This can happen. I'm not sure why. Sometimes the court modifies a document to fix a typo, but I wouldn't think this is related to this issue.

The rest of your notes are great, thanks. I'm going to close this, tweak the title, and if it happens again, we can analyze again. I'm not sure what else to do (aside from fixing the doc, which I'll do in a sec).

**Comment by epicfaace** [comment]
Thanks for the quick fix!! I've seen it happen for one other doc in the past (don't recall which one it was though), but will note when I see it again.

**Comment by mlissner** [comment]
You bet. It used to happen a lot, but I really thought we got it fixed. Keep us posted if you see any more, we'll need to figure out the trend...
