### ISSUE TITLE
Fix user's search query when proximity search has a space

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2965]
If a user does this: 

`"my phrase" ~7`

They meant to do this:

`"my phrase"~7`

Fix that for them. This could be done on the back end only, but I'm a fan of fixing queries and returning the fixed query to the user.

**Comment by albertisfu** [comment]
Should we fix the query here and only display the corrected version in the search box. Or should we preserve the original query in the search box and simply notify users about the corrected query used to return results, similar to how we handle missing citations?

**Comment by mlissner** [comment]
We should just fix it for them and we don't even need to tell them we did.
