### ISSUE TITLE
Update Opinion Coverage Page for Clarity

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#2985]
As we wrap up the Harvard merger - and the Columbia, it is time to update our coverage page with regard to opinions.  

The goal is to move the opinion coverage from the general coverage page to its own stand out page.  Detailing and explaining what we have and what we don't.  The case.law website has a nice starting point for what I think we should do.  

1. Harvard - has a streamlined and neat coverage page here.
[Harvard Coverage Page](https://cite.case.law)

2. CL - has a nice list of reporters in [citation page](https://www.courtlistener.com/c/) that should not go unnoticed or unused.

We want to capture our reporters, timeline (maybe?) and include our ongoing scraped opinions to the total.  

This page should really highlight the numbers, the work and the collections built up and being built.  This should also highlight gaps I think if we have any - and really help spur us to keep our scrapers in better repair.

**Comment by flooie** [comment]
We need to update our coverage page for opinions to reflect our ongoing and serious investment in the space.  

With the ingestion of the complete precedential datasets from various universities we have an opportunity to show how good our data is - but also allow us to see where it may be lacking.  

This means we will probably siphon off the opinion data from the general coverage page and create a new one.  This includes

1. A new coverage page for opinions.
2. A new API for querying individual state data.
3. Adding in a new javascript library to visualize and utilize that API.
4. Highlighting neutral citations.  
5. Highlight reporters.
6. Highlight our ongoing scraper/scraping efforts and how those integrate with our other datasets.

An initial review of the options for visualization turned up [this gem](https://github.com/vasturiano/timelines-chart) of a project.

While it is missing a few features or lack thereof that I prefer, (for example not showing legends or turning off zooming) it takes a nice JSON object and generates a visualization that can be sorted by chronology to really provide great looking data.

For example the following screen grab of New York shows how each reporter works together to create the complete historical record for the State.  It is both helpful to understand the data and a window into libraries and how it all came together. 

<img width="1643" alt="Screenshot 2023-08-25 at 2 06 26 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/d8a6e9cd-8619-4d0f-b922-7832fcd9250e">

Additionally, here is a rough example of how I originally thought we could incorporate multiple datasets.

<img width="1626" alt="Screenshot 2023-08-25 at 2 06 38 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/92da3581-73ec-4cbf-ae7c-4aa7dc9df8d4">

In this example, Alabama is combined with the reporters used to ingest the data along with the ongoing and current scraper data.  Here the static data took the OpinionClusters that had been scraped from court websites to show when that particular court started and ended.

After discussions with @mlissner on this topic, (I think) we agreed that since the data is showing different things, perhaps they should be slightly separated so that we group Alabama into multiple categories.

Either REPORTERS, Individual Courts and/or Scrapers that are on going. 

Although the final shape isn't quite clear, I am hoping to post a number of permutations of semi real data in here to continue that discussion.

Finally a simple visualization of the page started with this.

<img width="1199" alt="Screenshot 2023-08-25 at 2 12 10 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/3938c5e3-749d-4f90-8549-9277d29b395d">

With a basic show more button to trigger the API to pull back real or cached data.  Here something like this would be envisioned.

<img width="1475" alt="Screenshot 2023-08-25 at 2 19 07 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/397ec280-e02d-42a8-9999-0fd850d8438c">

Which after a bit of tweaking to the javascript now looks a little bit cleaner.

<img width="1136" alt="Screenshot 2023-08-25 at 2 32 47 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/e0796ac8-08b4-4419-94b6-6cec58c2c8d7">

I think we should include courts-  but perhaps limit it to only appellate courts so we aren't drowned out by New York and Ohio and Pennsylvania - but I could be convinced otherwise.  The only issue I see with some of these approaches is the API query to find the number and years for volumes that we might want to chart could be quite intensive.  Although the datasets are relatively manageable. 

Also -

I propose that the links to each volume that you see in blue - link to the courtlistener/c/citation page of volumes but I could be convinced that it could be linked to a query.

**Comment by mlissner** [comment]
Looking great. @brianwc might have thoughts on this.

Two of mine:

> I think we should include courts- but perhaps limit it to only appellate courts so we aren't drowned out by New York and Ohio and Pennsylvania

I think the point is to include full details, so if we add courts, I'd say we should add all of them, even if it's a bit intense in some places. 

Maybe could we have two buttons? One for "Show reporter timeline" and one for "Show court timeline" or something like that? 

> I propose that the links to each volume that you see in blue - link to the courtlistener/c/citation page of volumes

I think that makes total sense.

**Comment by mlissner** [comment]
The follow ups for this are in #3230. Closing here.
