### ISSUE TITLE
Update open ES PRs to use the new ESSignalProcessor

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#2987]
As part of our plan to get open ES PRs ready to merge into main. We need to update those PRs in order to replace custom signals for ESSignalProcessor.

Some considerations we should follow:

- When running on merge conflicts related to the test file split. In order to solve the conflicts, we should keep the new `tests_es_parenthetical` file as currently is in main. Then, only remove `ElasticSearchTest` test class and `is_es_online` method from `test.py`  and then move the file to the `tests` directory. 
- At this stage I don’t think is possible to split the other ES tests for OA since they changed in different PRs. We can do it on the latests OA PR.
- Also I created a new test case that should be used on ES test classes: `ESIndexTestCase`  it should replace ESIndexMixin when solving conflicts.
- Indices definition should be moved to `es_indices.py`
- When fixing conflicts related to `cl.search.signals` related OA signals should be removed and replaced for a mapping definition similar to `pa_field_mapping`  but for `AudioDocument` I added some comments to explain how it works and how the mapping should be created, basically we need to consider the fields mapping described in `AudioDocumentBase`  and also add fields that need to be tracked on `Audio` parent objects  for OA it'll easy since indexed fields only relies on  `Docket` this definition should be similar to `es_pa_field_tracker`  but it needs to be a different one, like: `es_oa_field_tracker`.
- We might need to tweak some methods on `es_signal_processor.py` so it uses the `es_pa_field_tracker`  or `es_oa_field_tracker` according to the main document `ParentheticalGroupDocument` or `AudioDocument `.
- Current save signals for `Audio `are a bit different from the save method in `ESSsignalProcessor`.  Since it requires to get the ES response and then call the `send_or_schedule_alerts` method, so that might need an additional tweak to the `save_document_in_es` method in `es_signal_processor`  so if the ES document support search alerts (like OA, Parenthetical doesn’t) it should call `send_or_schedule_alerts.`

Finally we'll need to call a new instance of `ESSsignalProcessor`, something like:

```
_oa_signal_processor = ESSignalProcessor(
    Audio,
    AudioDocument,
    oa_field_mapping,
)
```

**Comment by mlissner** [comment]
Is this pretty much done, Alberto?

**Comment by albertisfu** [comment]
Yeah, now we're using the ESSignalProcessor in all the search types.
