### ISSUE TITLE
Cases with thousands of parties fail to load and process

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#2992]
Yesterday, somebody started uploading immense numbers of documents to the [J&J Talcum Powder case](https://www.courtlistener.com/docket/6245245/johnson-johnson-talcum-powder-products-marketing-sales-practices-and/). As they're doing so, we attempted to add each document to Solr. That's normally fine, but each time we add an item to Solr, it has to flatten all docket and party information for the case and document. 

Well, it turns out that the J&J Talcum Powder case has about 42k parties, so when we flatten that, a chain of bad things happens:

1. The database churns, hard, disk queue builds up, and it fails.
2. Celery logs the failed task.
3. Celery's memory starts climbing.
4. If unchecked, all hell breaks loose.

When this happened yesterday, I got an alert from ElastiCache that it was running out of memory. Alberto pointed out that there was a spike in OperationalErrors in Sentry, see:

 - COURTLISTENER-3TE
 - COURTLISTENER-3TS

After some time figuring out the problem, I did [a little PR](https://github.com/freelawproject/courtlistener/pull/2990) that simply blocks adding the party information for these documents to Solr. Since then, things have been returning to normal, slowly but surely.

This morning, the iquery scraper also failed on a mega case, this time "Ashton v. Kingdom of Saudi Arabia](https://www.courtlistener.com/docket/6071899/asdf/), which has about 9k parties. 

----

The fix we need here is:

1. Revert the PR mentioned above.

3. Figure out how to pull party info more quickly. This probably requires analyzing the query in prod to see what indexes are needed, or perhaps breaking the query into pieces.

4. The Party page for the J&J case times out before loading via the website. If it's using different code than the Solr indexer, it needs to be made more efficient too. It wouldn't be crazy to add pagination to this URL. We don't usually want people to pull 40k items from our DB via a URL.

**Comment by mlissner** [comment]
Once Elastic is launched, we should see how this performs. I think we'll be able to unblock this and call it fixed.

**Comment by albertisfu** [comment]
Well, we have fixed the query for indexing parties into ES. So now, it's not an issue anymore.

Regarding loading parties on the frontend, the solution applied was pagination. Now, we only show 1,000 parties per page. It no longer times out: https://www.courtlistener.com/docket/6245245/parties/johnson-johnson-talcum-powder-products-marketing-sales-practices-and/

If the speed of loading the 1,000 parties per page seems reasonable to you, I think we can close this one. Otherwise, we could try reducing the number of parties per page.
