### ISSUE TITLE
Cited By Page Should Have Filtering Options

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#302]
We used to have something like this but removed it for performance reasons, so this issue would amount to finding the least-resource intensive way to allow users to better navigate the large lists of citations that some of our documents have. For example,

https://www.courtlistener.com/opinion/108101/goldberg-v-kelly/cited-by/

is a list of more than 1,000 citations. Legal research requires one studying an area of law where this precedent is relevant to narrow those subsequent cases to:

1. Those within a relevant jurisdiction (need jurisdiction filter)
2. Those likely to be important (citation count filter could help here)
3. Those that are more recent and potentially unknown to the user (date filter could help here)

There should be a way to treat these 1,000+ citations as a new universe and just apply some metadata filters to them in a way that wouldn't be a major drag on the database(s). One can accomplish much here without filtering on the full-text of these 1,000+ docs, but if that could also be done in a low-intensity way, that's very helpful too.

**Comment by mlissner** [comment]
This is now working in dev, but I haven't get updated the /cited-by/ pages, only gotten it working in Solr. Still, it's nearing completion.

**Comment by mlissner** [comment]
Done. Will be in the next version.
