### ISSUE TITLE
CSP Violation in Django REST Framework

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3020]
I found one! 

If you load this page:

https://www.courtlistener.com/api/rest/v3/

You'll see that there's a CSP violation: 

```
10:31:38.723 Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). v3:284:14
```

Drat. We'll want to fix this. I've noticed on the page, for example, that the OPTIONS button no longer works.

**Comment by cweider** [comment]
Good news: `django-rest-framework` has the fixes already. Bad news: the latest release is a year old and these fixes didn’t make it in. Probable solution is a switch of the dependency from the PyPI package to a (pinned) git ref.

The key changes are: encode/django-rest-framework#7016, encode/django-rest-framework#8783, and encode/django-rest-framework#8784.

**Comment by mlissner** [comment]
Think it's worth asking for a release? I kind of hate pinned versions.

**Comment by cweider** [comment]
Yup, exactly. Lurking in their discussion group, it doesn’t look like a release will be forthcoming. From a [recent discussion in Django REST framework](https://groups.google.com/g/django-rest-framework/c/j-TkbRyiQ1o/m/ZQXaVr2PAQAJ):

> > > > Hello group!
> > > > Does anybody know when the new version of DRF which would support Django 4.2 is expected?
> > >
> > > Hi, i think DRF now support D4.2 https://github.com/encode/django-rest-framework#requirements
> >
> > Master supports it, but the latest tagged version is 3.14 and it doesn't. So my question is when we can expect a new tag (3.15 maybe?)
>
> Hi, if you need install the master/main branch you try this
> pip install https://github.com/encode/django-rest-framework/archive/refs/heads/master.zip
> if you do not want to wait for the tag 3.15
>

**Comment by mlissner** [comment]
Wait, so their readme says it's supported, but the only way to get support is to use `master`??

**Comment by cweider** [comment]
Evidently. I mean the readme _is_ drawn from `master` so it is consistent. 10 months and counting from last release is a problem though. In other news, the built-in schema generation has been deprecated for about as long, but, being unreleased, the deprecation notice has yet to be published!

**Comment by mlissner** [comment]
OK, well, let's do it, I guess.
