### ISSUE TITLE
Upgrade input elements to use HTML type= (date, number)

### ISSUE THREAD

**Issue by jraller** [freelawproject/courtlistener#303]
For the four fields in the search form 

Filed After
Filed Before
Min Cites
Max Cites

This will let us use min and max for the citation numbers, which can then be pulled by the JavaScript when deciding to remove those from the search string, but then instead of hard coded max cites of 20,000 the backend would have to pass the actual value.

**Comment by mlissner** [comment]
This is wildly obsolete, but the idea is good. I've started a new issues to discuss this properly, here: #1097.
