### ISSUE TITLE
Define RECAP document mapping for Elasticsearch

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3031]
Following comment in https://github.com/freelawproject/courtlistener/issues/2572 , now we're working on moving RECAP search to Elastic. We need to define a document mapping for RECAP considering current searchable fields and including new ones that are currently not searchable like: `pacer_doc_id` or [short_description](https://github.com/freelawproject/courtlistener/issues/730)

**Comment by mlissner** [comment]
I think it's safe to close this one!
