### ISSUE TITLE
Hyperlinks not being added to opinion text

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#310]
See, for example, https://www.courtlistener.com/opinion/625710/mayo-collaborative-services-v-prometheus-laborator/

The TOA shows that we know this opinion cites at least 11 other opinions, but the only hyperlink we created was for the O'Reilly v. Morse case. No hyperlinks are present for the 10 other opinions we know it cites (and that's ignoring any cites we may have missed).

We could identify the scope of this problem by, for each document, doing a count of the opinion_ids in the cases_cited field and then counting how many instances of "href" occur in the html_with_citations field. They ought to be equal. If a document comes back with fewer "href"s in html_with_citations than it has opinion_ids in cases_cited, then it is an example of this issue.

Here's another example: https://www.courtlistener.com/opinion/2679558/alice-corp-v-cls-bank-intl/ The TOA shows we know about six citations within the document, but we only hyperlink one of them.

**Comment by brianwc** [comment]
Here is another example of this problem I just came across (I think it is widespread). From our TOA it is obvious we know that the opinion cites nine other opinions we have, but none of the hyperlinks get created:
https://www.courtlistener.com/opinion/2806207/jackson-v-city-and-county-of-san-francisco/

**Comment by mlissner** [comment]
I just looked at these three examples. I think this problem is fixed, or was fixed when I last re-ran the citator. Closing for now, but @brianwc please re-open if you run into this again. It's a weird one.
