### ISSUE TITLE
Block Chrome's new "privacy" sandbox

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3126]
Mozilla and Apple have come out against it:
 - https://github.com/mozilla/standards-positions/issues/622#issuecomment-1372979100
 - https://github.com/WebKit/standards-positions/issues/111#issuecomment-1359609317

From what I can tell, this new thing just tracks you around the web, and then builds up a model of what you like so that advertisers can learn about you. Super, freaking creepy, and makes me really glad I don't use Chrome.

The good news is, I think we can block it by setting a header on every page, so we should do so:

https://developer.chrome.com/docs/privacy-sandbox/topics/#site-opt-out

That says we have to set:

```
Permissions-Policy: browsing-topics=()
```

Gross and annoying. I'm not sure what tools we have in Django for setting this header. If it requires a middleware, I guess we could provide that to the community as a library folks can install.

**Comment by mlissner** [comment]
If we wind up needing to create our own package for this, and if some other solution doesn't already exist, I suggest `django-privacy-sandblox`.

**Comment by ERosendo** [comment]
I've found a promising package called [django-permissions-policy](https://github.com/adamchainz/django-permissions-policy) that offers fine-grained control over browser capabilities by setting `Permissions-Policy` headers and I think it could allow us to disable the browsing-topics tracking feature.

**Comment by mlissner** [comment]
His stuff is usually very good!
