### ISSUE TITLE
Add `AsyncioIntegration` to `sentry_sdk`

### ISSUE THREAD

**Issue by cweider** [freelawproject/courtlistener#3129]
Sentry has an [integration for `asyncio`](https://docs.sentry.io/platforms/python/guides/django/configuration/integrations/asyncio) and promises that:

* All unhandled exceptions in tasks will be captured
* Every executed Task will be instrumented and show up in the performance waterfall on Sentry.io

Given growing use of `asyncio` within the project adding to our existing set of integrations for Celery, Django, and Redis, may be worthwhile.

**Comment by mlissner** [comment]
Great find! Yes, we should really do this. Some of the Sentry results have been pretty weak since making things async.

**Comment by ttys0dev** [comment]
FYI there also appears to be an [ASGI integration](https://docs.sentry.io/platforms/python/guides/django/configuration/integrations/asgi/) not sure if we would want to use that instead of or in addition to the asyncio integration.
