### ISSUE TITLE
Financial Disclosure Table Extraction Broken

### ISSUE THREAD

**Issue by m-nolan** [freelawproject/courtlistener#3141]
Hello,

I was playing around with the financial disclosure search and found that the pdf->table conversion tool is broken sometimes. Here are some example yearly disclosures for Amy Coney Barrett. Some work, some don't:
- 2016 (not working) https://www.courtlistener.com/person/8543/disclosure/34178/amy-coney-barrett/
- 2018 (working) https://www.courtlistener.com/person/8543/disclosure/18341/amy-coney-barrett/
- 2019 (working) https://www.courtlistener.com/person/8543/disclosure/33289/amy-coney-barrett/
- 2020 (working) https://www.courtlistener.com/person/8543/disclosure/30679/amy-coney-barrett/
- 2021 (not working) https://www.courtlistener.com/person/8543/disclosure/34194/amy-coney-barrett/
- 2022 (not working) https://www.courtlistener.com/person/8543/disclosure/34199/amy-coney-barrett/

More information: I'm viewing the page on Mozilla Firefox from mac OS 10.15.7

I wasn't able to find an open issue for this. Has this been an issue for other justices/years?

**Comment by mlissner** [comment]
Heya. Yeah, some of the extraction doesn't work. We should do a better job showing an error that implies:

> We know this didn't work, sorry, please download

Instead of:

> !!! EXTRACTION FAILED. DOWNLOAD INSTEAD !!

It would be nice to try to debug these though and see if our extractor could be enhanced.

**Comment by m-nolan** [comment]
OK, thanks! Where in the courtlistener code is that error message sent to the view? I see that doctor is used to extract data from the pdfs, but where is that code called within courtlistener?

**Comment by mlissner** [comment]
You should be able to grep for the code. I suspect it's in a react file somewhere?

**Comment by m-nolan** [comment]
I've cloned the repo and have the local docker container running. I'd like to copy down some of the `people_db.Person` data to my local database to debug the pdf rendering. How do I go about getting the auth tokens I need to pull from the database? I see it alluded to but not described here: https://github.com/freelawproject/courtlistener/wiki/Getting-Started-Developing-CourtListener

**Comment by mlissner** [comment]
Cool. Closing this, but please open a new issue or discussion topic if needed.
