### ISSUE TITLE
Migrate existing recurring donors in CL to members in Neon

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3148]
This is not so much a technical project as a human one. We need to figure out who our monthly donors are, and convince them — somehow — to sign up with Neon instead of CL. I imagine this will mean emailing these folks a few times.

It could be that v2 membership levels described in https://github.com/freelawproject/free.law/issues/130 could be used as a carrot :carrot: to get these people to move.

When somebody signs up for a membership, all of their recurring donations should be cancelled. See: https://github.com/freelawproject/courtlistener/issues/3147

Some people won't act on our emails and we've decided that this is OK. We'll just keep billing them as we do now and one fine day, their credit card will expire. We don't need to keep these donations synced with Neon. It's OK. They don't respond email anyway. Maybe in a year we get to just stop charging these folks?

**Comment by jeniferw** [comment]
Natalie (implementation coordinator with Neon) will reach out to Joe Meyer who will manage the process of moving our current donations to Neon.

**Comment by jeniferw** [comment]
Notes from Joe Meyer

- form in Stripe to start migration https://support.stripe.com/contact/email?topic=migrations (Mike started form during meeting)
- we need to do our webhook first
- We pick the date to make Neon live

- we send schedule to Joe/Neon & cc # from Stripe (sent directly to Neon)

**Comment by mlissner** [comment]
Here's the full process, as I see it:

 - Get the Neon forms done via #https://github.com/freelawproject/free.law/issues/130
 - Get the webhook done via https://github.com/freelawproject/courtlistener/issues/3147
 - Update CL, Bots.law, and free.law to point to the forms via https://github.com/freelawproject/courtlistener/issues/3150
 - Forms and memberships are now in place and CL will know when somebody becomes a member.
 - New memberships are now in Neon and no new ones are in CL.

Next:
 - Decide on a date to move existing members over.
 - Contact Stripe to introduce Joe and his email address, via the link above.
 - Give Joe a CSV with:

    | CL ID of Donor | Stripe ID of Monthly Donation | Monthly Donation Date / Etc | Membership Tier ID |
    |--------|--------|--------|--------|--------|

 - Stripe will send an encrypted file with donor CC info and stripe ID to Joe.
 - Joe does the import, sets everybody up as members.
 - We stop charging people on the correct date.

**Comment by mlissner** [comment]
I contacted Stripe and asked them to send everything to Neon since that was the only reasonable option their contact form provided. Joe says that usually takes less than a week.

We won't be getting any new donors into CL (it's impossible), so I exported the data and sent it to Joe with some details. Hopefully it'll be enough for him. The other issue we may have is that we may not have every user in Neon when he goes to do his import. We should probably fix that by finishing https://github.com/freelawproject/free.law/issues/128 before he does his thing. Perhaps tomorrow or Monday.

Here's the data file I exported:

[monthly_donation_data.csv](https://github.com/freelawproject/courtlistener/files/14059196/monthly_donation_data.csv)

And the code to do so:

```
from cl.donate.models import MonthlyDonation
ds = MonthlyDonation.objects.filter(enabled=True, payment_provider="cc")
for d in ds:
     print(f"{d.donor_id},{d.stripe_customer_id},{d.monthly_donation_day},{d.monthly_donation_amount}")
```

**Comment by mlissner** [comment]
Joe's team is scheduled to do this on Sunday. I just updated our cronjob to [only trigger](https://crontab.guru/#0_12_*_*_3,4,5,6) on Wed-Sat. On Monday or Tuesday of next week, we can disable it entirely, but this will ensure that it doesn't trigger on the days that Joe does his work.

**Comment by mlissner** [comment]
@jeniferw, with Neon confirming things just now, is there anything more to do here? I'm also looking at closing down the Neon Membership board, if it's done:

https://github.com/orgs/freelawproject/projects/44/views/1

**Comment by jeniferw** [comment]
The only thing that we need to figure out is how to make sure that the
monthly donors who were migrated over receive their membership benefits.

I don't think we need to do anything to address the 18 expired credit cards
- that should trigger emails in Neon to have people update their cards.

And then thinking through how to & timing of moving people from their
recurring donation (especially at the $5 level), into the membership
structure.

Not sure we need a whole board for this, I can make a membership tab on my
backlog.

Jenifer





Jenifer Whiston, Director of Philanthropy
***@***.***  | 970-331-6194
Book a meeting - https://calendly.com/flp-jenifer
Make a Donation <https://www.courtlistener.com/donate/> to support Free Law
Project

**Comment by mlissner** [comment]
Cool. I closed the board. Let's talk if you think it'd be helpful. :)

**Comment by jeniferw** [comment]
Reached out to Joe Meyer - we are getting an abnormal number of failed transactions from the migrated recurring donations. Need to figure out problem & address retrying these donations.

**Comment by jeniferw** [comment]
Finally got in touch with Joe:
- up to 20% of failed transactions is common (we have about 10%)
- often due to either missing CVV or something with the card issuer

I need to email everyone with failed transactions and let them know we moved payment processors, we appreciate their donations - and to either log in to update their payment method, or to become members.
Just need to decide if we want to offer the grandfathered rate of $5 per month - or have them move to the $10 per month

Also need to email the group of 17 donors who were not migrated over due to expiring cards.

**Comment by mlissner** [comment]
> Just need to decide if we want to offer the grandfathered rate of $5 per month - or have them move to the $10 per month

Let's move 'em. $5/month barely qualifies as money.

Thank you!

**Comment by jeniferw** [comment]
from Joe:
   

> It is not unusual for between 1 to 5% of migrated recurring transactions to fail after a migration. These cardholders will need to be contacted to provide new payment information. Unfortunately it’s impossible to predict this ahead of time. We’ve seen many migrations with a 0% failure rate, but we’ve also seen a few with a failure rate up to 20% (that’s higher than usual).
> Technical explanations of failures: In some cases, a bank will decline a scheduled payment if it is moved to a new processor and there is no CVV included. Recurring transactions cannot contain a CVV as this violates PCI compliance regulations. The bank may not recognize the new merchant account the charge is being attempted on, and without a CVV to confirm the charge attempt is legitimate, they may decline the charge.

So, I am going to update the email that is sent to people when their donation fails - explaining that if they previously had a recurring donation in CL, we have switched to a new payment processor and the bank may be declining the charge due to the CVV code not being saved.
We are also upgrading our membership program to add additional levels. If they would like to maintain their membership benefits, then they should become a member (include link to form) or if they would like to continue to make a tax deductible donation to support Free Law Project, please renew your recurring donation either by logging into their Neon account (LINK) or filling out a donation form (LINK).

We may lose some of these donations in the switch - about $200 per month.

I will need to start disabling recurring donations that fail more than once - I don't think there is a way to automate this - but I will ask

**Comment by mlissner** [comment]
> We may lose some of these donations in the switch - about $200 per month.

Yikes. This is bad math, but that just made Neon twice the price. :open_mouth: 

> I will need to start disabling recurring donations that fail more than once - I don't think there is a way to automate this - but I will ask

That's weird. If you don't do that by hand, what, the recurring donations keep trying the card over and and over each month forever?? :open_mouth:

**Comment by jeniferw** [comment]
Updated the Neon email sent when donations failed.
Sent email to 14 people who's donations were not migrated due to expiring CCs
Still need to send individual emails to 4 people - 3 .edu emails & 1 Justia badge donor

**Comment by jeniferw** [comment]
@mlissner we have one final migration of donations to do from CL to neon - 2/9/24 to 2/22/24 to do
If you can run the CSV, I can do the import into Neon.

**Comment by mlissner** [comment]
At your service:

```
id,donor_id,clearing_date,send_annual_reminder,amount,payment_provider,status,referrer
16101,22364,02-21-2024,False,25.00,Credit Card,Processed,monthly_donation
16100,17412,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16099,8802,02-21-2024,False,10.00,Credit Card,Processed,monthly_donation
16098,24453,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16097,18778,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16096,33181,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16095,38476,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16094,40643,02-21-2024,False,50.00,Credit Card,Processed,monthly_donation
16093,40698,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16092,35577,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16091,51020,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16090,28217,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16089,62920,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16088,30335,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16087,26820,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16086,44206,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16085,154982,02-21-2024,False,5.00,Credit Card,Processed,monthly_donation
16084,10451,02-17-2024,False,5.00,Credit Card,Processed,monthly_donation
16083,36114,02-17-2024,False,25.00,Credit Card,Processed,monthly_donation
16082,37404,02-17-2024,False,5.00,Credit Card,Processed,monthly_donation
16081,43586,02-17-2024,False,10.00,Credit Card,Processed,monthly_donation
16080,56595,02-17-2024,False,5.00,Credit Card,Processed,monthly_donation
16079,82834,02-17-2024,False,5.00,Credit Card,Processed,monthly_donation
16078,40442,02-17-2024,False,5.00,Credit Card,Processed,monthly_donation
16077,158947,02-17-2024,False,5.00,Credit Card,Processed,monthly_donation
16076,27848,02-16-2024,False,5.00,Credit Card,Processed,monthly_donation
16075,32163,02-16-2024,False,5.00,Credit Card,Processed,monthly_donation
16074,32234,02-16-2024,False,15.00,Credit Card,Processed,monthly_donation
16073,39481,02-16-2024,False,10.00,Credit Card,Processed,monthly_donation
16072,39497,02-16-2024,False,25.00,Credit Card,Processed,monthly_donation
16071,39503,02-16-2024,False,10.00,Credit Card,Processed,monthly_donation
16070,7823,02-16-2024,False,5.00,Credit Card,Processed,monthly_donation
16069,40580,02-16-2024,False,10.00,Credit Card,Processed,monthly_donation
16068,36516,02-16-2024,False,5.00,Credit Card,Processed,monthly_donation
16067,32767,02-16-2024,False,5.00,Credit Card,Processed,monthly_donation
16066,25389,02-16-2024,False,5.00,Credit Card,Processed,monthly_donation
16065,29851,02-16-2024,False,5.00,Credit Card,Processed,monthly_donation
16064,52047,02-16-2024,False,5.00,Credit Card,Processed,monthly_donation
16063,57161,02-16-2024,False,100.00,Credit Card,Processed,monthly_donation
16062,155439,02-16-2024,False,10.00,Credit Card,Processed,monthly_donation
16061,154796,02-16-2024,False,12.50,Credit Card,Processed,monthly_donation
16057,12203,02-15-2024,False,5.00,Credit Card,Processed,monthly_donation
16056,10644,02-15-2024,False,5.00,Credit Card,Processed,monthly_donation
16055,28768,02-15-2024,False,5.00,Credit Card,Processed,monthly_donation
16054,24077,02-15-2024,False,5.00,Credit Card,Processed,monthly_donation
16053,14029,02-15-2024,False,5.00,Credit Card,Processed,monthly_donation
16052,35321,02-15-2024,False,10.00,Credit Card,Processed,monthly_donation
16051,39469,02-15-2024,False,100.00,Credit Card,Processed,monthly_donation
16050,36955,02-15-2024,False,5.00,Credit Card,Processed,monthly_donation
16049,36450,02-15-2024,False,5.00,Credit Card,Processed,monthly_donation
16048,26437,02-15-2024,False,10.00,Credit Card,Processed,monthly_donation
16047,90287,02-15-2024,False,25.00,Credit Card,Processed,monthly_donation
16046,82532,02-15-2024,False,10.00,Credit Card,Processed,monthly_donation
16041,11415,02-14-2024,False,5.00,Credit Card,Processed,monthly_donation
16040,67631,02-14-2024,False,25.00,Credit Card,Processed,monthly_donation
16039,66324,02-14-2024,False,10.00,Credit Card,Processed,monthly_donation
16038,39347,02-14-2024,False,10.00,Credit Card,Processed,monthly_donation
16037,153741,02-14-2024,False,5.00,Credit Card,Processed,monthly_donation
16036,156157,02-14-2024,False,5.00,Credit Card,Processed,monthly_donation
16035,156199,02-14-2024,False,5.00,Credit Card,Processed,monthly_donation
16034,157263,02-14-2024,False,5.00,Credit Card,Processed,monthly_donation
16033,158077,02-14-2024,False,10.00,Credit Card,Processed,monthly_donation
16032,161285,02-14-2024,False,20.00,Credit Card,Processed,monthly_donation
16031,18322,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16030,26476,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16029,24626,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16028,32051,02-13-2024,False,10.00,Credit Card,Processed,monthly_donation
16027,36972,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16026,10401,02-13-2024,False,10.00,Credit Card,Processed,monthly_donation
16025,23973,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16024,42693,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16023,26687,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16022,59577,02-13-2024,False,10.00,Credit Card,Processed,monthly_donation
16021,88014,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16020,156130,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16019,156133,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16018,156138,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16017,156141,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16016,156142,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16015,156143,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16014,156145,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16013,40110,02-13-2024,False,25.00,Credit Card,Processed,monthly_donation
16012,156967,02-13-2024,False,6.00,Credit Card,Processed,monthly_donation
16011,38638,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16010,155936,02-13-2024,False,5.00,Credit Card,Processed,monthly_donation
16009,159768,02-13-2024,False,10.00,Credit Card,Processed,monthly_donation
16008,25589,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
16007,29525,02-12-2024,False,50.00,Credit Card,Processed,monthly_donation
16006,32001,02-12-2024,False,10.00,Credit Card,Processed,monthly_donation
16005,31223,02-12-2024,False,10.00,Credit Card,Processed,monthly_donation
16004,34746,02-12-2024,False,25.00,Credit Card,Processed,monthly_donation
16003,19419,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
16002,38921,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
16001,36766,02-12-2024,False,15.00,Credit Card,Processed,monthly_donation
16000,16388,02-12-2024,False,10.00,Credit Card,Processed,monthly_donation
15999,38381,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15998,43799,02-12-2024,False,10.00,Credit Card,Processed,monthly_donation
15997,30362,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15996,56696,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15995,15098,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15994,40778,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15993,47154,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15992,156412,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15991,59517,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15990,23836,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15989,30529,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15988,26242,02-12-2024,False,5.00,Credit Card,Processed,monthly_donation
15987,31969,02-11-2024,False,5.00,Credit Card,Processed,monthly_donation
15986,34085,02-11-2024,False,5.00,Credit Card,Processed,monthly_donation
15985,36464,02-11-2024,False,50.00,Credit Card,Processed,monthly_donation
15984,31592,02-11-2024,False,10.00,Credit Card,Processed,monthly_donation
15983,35609,02-11-2024,False,10.00,Credit Card,Processed,monthly_donation
15982,59999,02-11-2024,False,10.00,Credit Card,Processed,monthly_donation
15981,46553,02-11-2024,False,5.00,Credit Card,Processed,monthly_donation
15980,22546,02-11-2024,False,200.00,Credit Card,Processed,monthly_donation
15979,43118,02-11-2024,False,5.00,Credit Card,Processed,monthly_donation
15978,42911,02-11-2024,False,5.00,Credit Card,Processed,monthly_donation
15977,161185,02-11-2024,False,25.00,Credit Card,Processed,monthly_donation
15976,10169,02-10-2024,False,25.00,Credit Card,Processed,monthly_donation
15975,19085,02-10-2024,False,5.00,Credit Card,Processed,monthly_donation
15974,37690,02-10-2024,False,5.00,Credit Card,Processed,monthly_donation
15973,45457,02-10-2024,False,10.00,Credit Card,Processed,monthly_donation
15972,49181,02-10-2024,False,50.00,Credit Card,Processed,monthly_donation
15971,28925,02-10-2024,False,10.00,Credit Card,Processed,monthly_donation
15970,67091,02-10-2024,False,5.00,Credit Card,Processed,monthly_donation
15969,39033,02-10-2024,False,5.00,Credit Card,Processed,monthly_donation
15968,44600,02-10-2024,False,5.00,Credit Card,Processed,monthly_donation
15967,41894,02-10-2024,False,5.00,Credit Card,Processed,monthly_donation
15966,38503,02-10-2024,False,5.00,Credit Card,Processed,monthly_donation
15965,9745,02-10-2024,False,5.00,Credit Card,Processed,monthly_donation
15963,17898,02-09-2024,False,5.00,Credit Card,Processed,monthly_donation
15962,40249,02-09-2024,False,5.00,Credit Card,Processed,monthly_donation
15961,36491,02-09-2024,False,5.00,Credit Card,Processed,monthly_donation
15960,22608,02-09-2024,False,10.00,Credit Card,Processed,monthly_donation
15959,81010,02-09-2024,False,5.00,Credit Card,Processed,monthly_donation
15958,59933,02-09-2024,False,5.00,Credit Card,Processed,monthly_donation
15957,155968,02-09-2024,False,10.00,Credit Card,Processed,monthly_donation
15956,153697,02-09-2024,False,5.00,Credit Card,Processed,monthly_donation
15955,65946,02-09-2024,False,5.00,Credit Card,Processed,monthly_donation
15954,161050,02-09-2024,False,5.00,Credit Card,Processed,monthly_donation
```

**Comment by jeniferw** [comment]
For some reason over 100 of these wouldn't match - can you try exporting
again, but include either the First and last names or emails?

The 2nd number in the file above is their CL ID - correct?
I've tried to spot check & can't figure out where the issue is, except
maybe there?

This is one of the donations that should have been in the export -
https://www.courtlistener.com/admin/auth/user/29965/change/
I can match it by name to Neon - but the CL ID that is in Neon, isn't in
the list above ( 29965)

Only 6 matched.

Jenifer




Jenifer Whiston, Director of Philanthropy
***@***.***  | 970-331-6194
Book a meeting - https://calendly.com/flp-jenifer
Make a Donation <https://www.courtlistener.com/donate/> to support Free Law
Project

**Comment by mlissner** [comment]
Yes, the second column is the CL ID. Maybe we need to do another import of those for the same time period?

**Comment by jeniferw** [comment]
They don't seem to be new donors - so I don't think we need to import the
donors - their previous transactions were migrated successfully. And I made
sure that the matching of fields was the same as previous. I'm just not
sure why they aren't migrating?

Jenifer




Jenifer Whiston, Director of Philanthropy
***@***.***  | 970-331-6194
Book a meeting - https://calendly.com/flp-jenifer
Make a Donation <https://www.courtlistener.com/donate/> to support Free Law
Project

**Comment by mlissner** [comment]
How do you know they're not new donors?

**Comment by jeniferw** [comment]
because I can connect them from the admin panel to Neon manually.





Jenifer Whiston, Director of Philanthropy
***@***.***  | 970-331-6194
Book a meeting - https://calendly.com/flp-jenifer
Make a Donation <https://www.courtlistener.com/donate/> to support Free Law
Project

**Comment by mlissner** [comment]
I see. Well, that's a stumper!

**Comment by jeniferw** [comment]
I'll grab something next week so we can look closer at this.

Jenifer





Jenifer Whiston, Director of Philanthropy
***@***.***  | 970-331-6194
Book a meeting - https://calendly.com/flp-jenifer
Make a Donation <https://www.courtlistener.com/donate/> to support Free Law
Project

**Comment by mlissner** [comment]
I think this is done. @jeniferw, can you please confirm? If so, let's delete this issue since there's kind of too much data here (even though I think all of it is fine, there's no reason to keep it).
