### ISSUE TITLE
Cross link Oral arguments to Decisions

### ISSUE THREAD

**Issue by jraller** [freelawproject/courtlistener#316]
When the database contains the decision for an oral arguments, show a link to the corresponding entry. This feature could wait until dockets, but could also be implemented ahead of that.

See:

https://www.courtlistener.com/opinion/2758569/integrity-staffing-solutions-inc-v-busk

and

https://www.courtlistener.com/audio/670/integrity-staffing-solutions-inc-v-busk for an example.

Key on court and docket number?

**Comment by mlissner** [comment]
This is done. :)
