### ISSUE TITLE
Missing data in search_opinion

### ISSUE THREAD

**Issue by taylorkangbeck** [freelawproject/courtlistener#3162]
I noticed some data integrity issues I thought I'd share. When loading search_opinionscited into a database with the courtlistener schema, it fails on a foreign key constraint with search_opinion. Some ids referenced in search_opinionscited do not exist in search_opinion.

I am using the data dump from 08-31-2023.

Upon closer inspection there are two groups of ids missing from search_opinion, but are referenced in search_opinionscited:
* ids > `9802389`
  * these are larger than the largest id in search_opinion and I'm guessing they are missing due to a race condition between each table being exported while new data is added
* ids  `4342547, 4342552, 4342554, 4342556`
  * I'm not sure why these are missing. Maybe they were deleted without cascade from search_opinion?

There are additional ids missing from search_opinion that are not referenced in search_opinionscited (assuming sequential ids), but don't impact data integrity.

**Comment by mlissner** [comment]
Thanks for reporting this. I think your diagnoses are probably correct, but I'm not sure how to handle this. We export the data table by table, and what almost certainly happened is that we did some deletions in between table exports. I suspect postgres has a way of doing this, but the general process looks like this:

```
echo "Streaming search_court to S3"
PGPASSWORD=$DB_PASSWORD psql \
	--command \
	  'set statement_timeout to 0;
	   COPY search_court (
	       id, pacer_court_id, pacer_has_rss_feed, pacer_rss_entry_types, fjc_court_id,
	       date_modified, in_use, has_opinion_scraper, has_oral_argument_scraper, position,
	       citation_string, short_name, full_name, url, start_date, end_date,
	       jurisdiction, notes
	   ) TO STDOUT WITH (FORMAT csv, ENCODING utf8, HEADER, FORCE_QUOTE *)' \
	--quiet \
	--host $DB_HOST \
	--username $DB_USER \
	--dbname courtlistener | \
	bzip2 | \
	aws s3 cp - s3://com-courtlistener-storage/bulk-data/courts-`date -I`.csv.bz2 --acl public-read

echo "Streaming search_docket to S3"
PGPASSWORD=$DB_PASSWORD psql \
	--command \
	  'set statement_timeout to 0;
	   COPY search_docket (
	       id, date_created, date_modified, source, appeal_from_str,
	       assigned_to_str, referred_to_str, panel_str, date_last_index, date_cert_granted,
	       date_cert_denied, date_argued, date_reargued,
	       date_reargument_denied, date_filed, date_terminated,
	       date_last_filing, case_name_short, case_name, case_name_full, slug,
	       docket_number, docket_number_core, pacer_case_id, cause,
	       nature_of_suit, jury_demand, jurisdiction_type,
	       appellate_fee_status, appellate_case_type_information, mdl_status,
	       filepath_local, filepath_ia, filepath_ia_json, ia_upload_failure_count, ia_needs_upload,
	       ia_date_first_change, view_count, date_blocked, blocked, appeal_from_id, assigned_to_id,
	       court_id, idb_data_id, originating_court_information_id, referred_to_id
	   ) TO STDOUT WITH (FORMAT csv, ENCODING utf8, HEADER, FORCE_QUOTE *)' \
	--quiet \
	--host $DB_HOST \
	--username $DB_USER \
	--dbname courtlistener | \
	bzip2 | \
	aws s3 cp - s3://com-courtlistener-storage/bulk-data/dockets-`date -I`.csv.bz2 --acl public-read
```

(See make_bulk_data.sh for the script.)

I think if we did it in a transaction, that'd probably work. I suppose that'd be possible by running multiple COPY commands inside a single connection to `psql`, but that'd make a single bulk data file per month, which would probably frustrate some uses. 

I'm open to solutions here if people have them. It also sounds like you found a workaround for this. Would you mind sharing that?

Finally:

> There are additional ids missing from search_opinion that are not referenced in search_opinionscited (assuming sequential ids), but don't impact data integrity.

Yes, there are a lot of deleted items. Definitely do not expect sequential IDs in any of our tables.

**Comment by taylorkangbeck** [comment]
Maybe you could set up a replica database specifically for data dumping, and then pause replication before starting the export. Then the replica can catch up afterward.

As for a workaround, I manually disabled foreign key constraints (and all other triggers), did my COPY FROM operations, then re-enabled the constraints (not that I'm going to be adding additional data myself that should be constrained anyway...). I did so with `SET session_replication_role = 'replica';` -> `COPY ... FROM ... ;`  -> `SET session_replication_role = 'origin';`

**Comment by taylorkangbeck** [comment]
Just curious, in what situations do you delete items from the database?

**Comment by mlissner** [comment]
> Maybe you could set up a replica database specifically for data dumping, and then pause replication before starting the export. Then the replica can catch up afterward.

That's not a bad idea, but replicas are pretty expensive. Hm. Creative solution though.

> Just curious, in what situations do you delete items from the database?

There are a couple:

 - When we detect duplicates, sometimes we'll clear out the newer duplicate
 - When we add parties and attorneys to PACER dockets, we just nuke the old data and replace it instead of trying to merge the two.
 - When things are sealed, we'll delete it
