### ISSUE TITLE
person_db.People cloning bug in `clone_from_cl`

### ISSUE THREAD

**Issue by m-nolan** [freelawproject/courtlistener#3167]
I was trying to clone `person_db.People` data from the website to my local docker instance using the `clone_from_cl` method. The code threw an error here:

https://github.com/freelawproject/courtlistener/blob/e84878ae73a40496bde1066f8e4fb3668dc5e1b1/cl/scrapers/management/commands/clone_from_cl.py#L615

The `get_or_create` method would not accept the `"religion"` value within the `person_data` dict, which in this case was `"Catholic"`. Within the debugger, the `get_or_create` call worked after replacing this value with the corresponding `"ca"` string.

It looks like the `clone_from_cl` tool is incomplete, so I don't know how fixing this bug impacts its overall development, but I've written a fix for this that converts the human-readable religion string with the shorter code string required by the create method. I'm not sure how to write tests within this codebase, maybe someone else can help me with that?

I've written a working fix for this, it's only a few lines. I don't have push permissions, but I'm happy to share the gist if someone else wants to make a PR.

**Comment by quevon24** [comment]
Thanks for reporting this, do you have the person id? There is a pending PR with some fixes for the command, I can integrate a fix for this too

**Comment by m-nolan** [comment]
Sure - this was to get person ID 8543, Justice Amy Coney Barrett. 

The fix I wrote was to add the following lines of code before the `person, created = model.objects.get_or_create(**person_data)` call on [line 615 of `clone_from_cl`](https://github.com/freelawproject/courtlistener/blob/e84878ae73a40496bde1066f8e4fb3668dc5e1b1/cl/scrapers/management/commands/clone_from_cl.py#L615) I linked to up above: 
```
# correct religion designation if necessary
        religion_reverse_dict = dict((v,k) for k, v in dict(model.religion.field.choices).items())
        if person_data["religion"] and person_data["religion"] in religion_reverse_dict.keys():
            person_data["religion"] = religion_reverse_dict[person_data["religion"]]
```
