### ISSUE TITLE
Set up ClamAV to scan incoming PDFs

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#318]
Not sure why this didn't occur to me before, but we should scan each incoming PDF for malware. ClamAV can be set up to scan a specific doc on demand (clamscan). We wouldn't want to redistribute an infected pdf and we could notify the courts if we ever identify a problem. 

I guess logically speaking, we'd want this first in the pipeline because we wouldn't want to do any other processing with a potentially infected pdf.

**Comment by anseljh** [comment]
VirusTotal has an API. Looks like CourtListener would qualify for using it, and could get a boost on their rate limit.

https://www.virustotal.com/en/documentation/public-api/

**Comment by mlissner** [comment]
I have clamav running against the entire recap corpus. I'll report back when it finishes (probably on Monday). It'll be interesting to see what it produces.

@anseljh I don't know about using an API for this. Seems like more of a headache than just using clamav.

**Comment by anseljh** [comment]
Right, I don't think you'd want to submit everything through an API. But if ClamAV gives a positive on a file, then it might be a good idea to send that file to VirusTotal for more details, and to get the file signature out there.

**Comment by saizai** [comment]
ClamAV is not as comprehensive as VirusTotal. I've gotten non-hits on Clam
that something in VT flagged.

**Comment by mlissner** [comment]
> It might be a good idea...to get the file signature out there.

That's a good point I hadn't considered. I suppose we'll want to look into that more.

In the meantime, Clamav is still running. It looks like it just uses one core for this (which is at 100% for the past several days). For next time, there's another approach that uses the clamav daemon and [a tool][1] to send things to it in multiple threads..

[1]: https://linux.die.net/man/1/clamdscan

**Comment by anseljh** [comment]
VirusTotal has an API, and there's [a Python library for it](https://pypi.python.org/pypi/virustotal-api) already, so this shouldn't be too hard. I'd be happy to look into it once I have my CL dev environment fully squared away.

**Comment by mlissner** [comment]
Excellent, yeah, that'd be pretty great to do something here. I think the new ansible/vagrant dev environment is very close to ready. @voutilad has been working hard on it lately.

**Comment by mlissner** [comment]
OK, this finally finished. Things look pretty darned good:

```↪ sudo clamscan -r /sata/recap/ -i && bush "Clamscan done."

----------- SCAN SUMMARY -----------
Known viruses: 4858044
Engine version: 0.99.2
Scanned directories: 1
Scanned files: 4046762
Infected files: 0
Data scanned: 1693530.64 MB
Data read: 963200.21 MB (ratio 1.76:1)
Time: 336282.074 sec (5604 m 42 s)
```

That's the results for the bulk of the RECAP archive. With these results, I still think there's value in getting this set up, because it's just a good, sane thing to do, but I'm encouraged that nothing at all came from the first big scan.

There are some decent Python libraries for clamav, so I think we should just do a simple scan of everything we get as we get it.

**Comment by mlissner** [comment]
For python bindings, we'll want to use [clamd](https://github.com/graingert/python-clamd). All the other bindings either lack documentation or are more or less unmaintained. 

I wrapped up creating a scraper for RECAP content earlier today, so the time is ripe for this to get merged in.

I think the basic features could be:

 - A celery task that checks if a path is a virus.
 - If yes:
    - Send an email to alert us (this might be very interesting).
    - Flag it as such in the DB.
    - Show a warning to users and make it undownloadable.
 - If no: Do nothing.

**Comment by mlissner** [comment]
I don't imagine we'll ever get to this, particularly since the initial scan was so clean.
