### ISSUE TITLE
originating court 

### ISSUE THREAD

**Issue by text2sql** [freelawproject/courtlistener#3213]
for this command `COPY search_originatingcourtinformation (id, date_created, date_modified, docket_number, assigned_to_str, ordering_judge_str, court_reporter, date_disposed, date_filed, date_judgment, date_judgment_eod, date_filed_noa, date_received_coa, assigned_to_id, ordering_judge_id) FROM '/opt/bulk/originating-court-information-2023-09-22.csv'` where can i find this file? it's not on the bulk data page.

**Comment by mlissner** [comment]
That file doesn't exist yet. The PR you're looking at will introduce it when it runs.
