### ISSUE TITLE
Coverage page follow up tasks

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3222]
A few things I"m seeing and thinking about wrt to the new coverage page:

 - [x] **Performnace**: Right now loading the page itself seems to be solved, but loading the graphs is bad. I don't think we can fix it using the database, but fear not, there are solutions:
    - [x] We need to provide a spinner in the button.
    - [x] We can switch to using Solr/Elastic for the queries. I think it can do a court in about half a second, which should be a lot better than the DB.
    - [x] We can cache each court or each API response. Even though Solr will be faster, caches will still help.

 - [x] **Mobile**: The sidebar is missing on mobile, which is too bad, and the graphs don't work. I think we can just hide the graph buttons on mobile (sorry), and maybe we can do a mini-TOC that only shows up on mobile. It could just have State, Federal, etc. headings.

 - [x] **Architecture**: I didn't catch it before now, but the API shouldn't take the name of the court as a parameter. It should use IDs. Names shouldn't be used for this kind of thing.

 - [x] **Content**: We need to add the text from the Google doc.

What else?

**Comment by flooie** [comment]
Performance performance performance -

**Comment by mlissner** [comment]
The latest list:
 - [ ] The API needs to be done as `?courts=abc,foo,bar` (right now it returns 413 responses b/c the requests are too big.
    - [ ] Check performance again after this
 - [ ] Let's collapse the sidebar by default, so it's better on mobile.
 - [ ] The main content should have a margin at right, like other help pages.
 - [ ] Add `class="lead"` to the first paragraph
 - [ ] Remove `if query_parameters` from the view.
 - [ ] Fix links from charts to search results (they do links like: https://www.courtlistener.com/?court=248)

**Comment by mlissner** [comment]
- [ ] Nuke the purple line from the bottom of every chart.
 - [ ] Add scrapers back to the chart
 - [ ] Remove the current info from the coverage page, and replace it with a link (though there may be info on that page that's worth continuing to say?)

**Comment by mlissner** [comment]
- [ ] The X button is weird in Florida:

    ![image](https://github.com/freelawproject/courtlistener/assets/236970/f37f9690-f931-458c-b51a-4d91a870951e)

**Comment by flooie** [comment]
what is weird about the x button?

**Comment by mlissner** [comment]
It's all the way down by the line?

**Comment by mlissner** [comment]
- [ ] Add this to our help page: https://www.courtlistener.com/help/

**Comment by mlissner** [comment]
Making progress! Amazing how hard a single page can be, but I think this is an important one to get right, so here's what I hope is my last fine-tooth combing through it:

 - [ ] The TOC at `/coverage/` needs a tweak to remove updated stuff:

    ![image](https://github.com/freelawproject/courtlistener/assets/236970/b873e4a1-26f8-41f4-9a25-a8d7fd0facfa)

 - [ ] We can remove the old JS library that was building the old charts, right?
 - [ ] The coverage page has: 

    > We have over 9 million opinions for over 2000 courts. See our page on this topic for more details:

    Which ends with a colon. The same paragraph for the Financial Disclosures and Judges blurbs end with periods. Let's make it consistent with the period. Details, sorry! 

 - [ ] Can we remove this sentence:

    > Although the collection of legal opinions never stops, here is what we have and how we do it.

    And replace it with a newline, and then:

    > Scroll down or use the Table of Contents to inspect particular jurisdictions or read on to learn more about how we do it.

 - [ ] Let's switch the colons on the coverage page to m-dashes. So instead of "Diverse Sources: Our", let's do, "Diverse Sources — Our".

 - [ ] There are a bunch of links in [the coverage page google doc](https://docs.google.com/document/d/1gibdSKZ91kIN56c52lwc55c3nxrIOb9Vv6MfA_vmw_g/edit#heading=h.1gvx888rf11i). Can you move them to the live version, please? 

 - [ ] Tweaks: 
    - "extension collection of scraped opinions " --> "extensive collection of scraped opinions "
    - "Machine Learning" --> "machine learning"

 - [ ] The performance is....so-so. If it's cached, it's fast. NY just took 22s, which is waaaay longer than most users will wait. I think you can fix this by checking which courts we have scrapers for. 

    So instead of querying clusters to find out we have no scraped content, query the Court table, and only query clusters for dates if we have scrapers for that Court. Even North Dakota gets the :turtle: emoji in Firefox's network panel, since it takes over 1s. We can also make the cache a lot longer. 

    It's one day now. How about a week?

 - [ ] Ohio is intense! But it still has some layout problems: 

    ![image](https://github.com/freelawproject/courtlistener/assets/236970/6f3c811a-652e-4aa0-831c-2412dbff2607)

I think that's it. I think all of this is easy except, perhaps, the last item, which I'm not sure about. Hopefully we're on the final bit of this one, but not yet at the ends of our rope.

**Comment by flooie** [comment]
I dont have the layout issue but it's a width thing when you load the page.  The chart is surprisingly not dynamic.  I'll see what I can do 
<img width="1244" alt="Screenshot 2023-10-05 at 7 28 15 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/efa9b0d6-2562-4122-b5b5-a509498270d6">

**Comment by flooie** [comment]
I've got some updates for mobile - I think but I dont have enough data to validate the Ohio NY situation yet.  

Here is how mobile looks in safari in different form factors.  The only thing holding this up is the fact that we need to complete our court citation string to use as a shortened string to make it work across all mobile options.  

@mlissner 


<img width="759" alt="Screenshot 2023-10-06 at 3 52 34 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/7c7e8569-479e-410e-89b5-06cad732b6ce">
<img width="682" alt="Screenshot 2023-10-06 at 3 52 41 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/451fb13b-8471-4bbf-80d1-52a3cb63453c">
<img width="946" alt="Screenshot 2023-10-06 at 3 52 45 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/741bbdae-be14-4df7-b063-b741b6a277e4">

<img width="697" alt="Screenshot 2023-10-06 at 3 52 20 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/4036e9d7-7822-4fbb-a457-c8fc17271649">
<img width="735" alt="Screenshot 2023-10-06 at 3 52 24 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/e6274243-4a6a-45ff-b1f3-7dfda468578f">
<img width="704" alt="Screenshot 2023-10-06 at 3 52 29 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/d6aee7de-98f1-4a4e-87ca-2beb56c6f843">

<img width="659" alt="Screenshot 2023-10-06 at 3 52 15 PM" src="https://github.com/freelawproject/courtlistener/assets/6464529/d9637dcb-4330-4bd0-8086-427f708e536b">

**Comment by mlissner** [comment]
That's cool. I'm not sure the FB, F, etc. mean much to anybody though. Could we just remove those?

**Comment by flooie** [comment]
I was going to add a legend ?  but we could easily remove them

**Comment by mlissner** [comment]
I'd suggest removing them on xs, sm, and md, but leave them on lg?

**Comment by mlissner** [comment]
I guess if we wanted to do a legend (and it's easy), we could use color of the bars instead and drop the left sidebar completely.

**Comment by flooie** [comment]
We need to update all citation string but otherwise it's great

**Comment by flooie** [comment]
To be clear it says federal appellate etc on big screens.

**Comment by mlissner** [comment]
I mean, if you're doing a legend, is it easier to just ditch the left sidebar completely on all screensizes?

**Comment by flooie** [comment]
@mlissner the PR is ready for your review - ditched the legend - but made some other choices

**Comment by mlissner** [comment]
OK, we're certainly getting there. I checked off a bunch of the boxes on this issue. 

Ohio is still a little weird:

![image](https://github.com/freelawproject/courtlistener/assets/236970/6299d47e-d2b8-4b22-bb2f-70ae50ebed0f)

It's readable now, so it's probably fine to leave well enough alone, but I thought I'd raise it, since I know you were calculating widths and it surprised me that it had such a large margin on the right.

This is also really hard to understand. Why are there black and purpose boxes? What could it mean? 

![image](https://github.com/freelawproject/courtlistener/assets/236970/0233c898-624b-4e09-8bb4-4d3f46ee1d01)

I'm not sure we can do much more about performance, so I guess that's done. 

So, summarizing:
 - If we can do better with the margins, yeah, let's.
 - If we can do something about the black vs. purple, we should (but please propose something before beginning work on it).
 - We still need to remove D3.js

**Comment by flooie** [comment]
Whoa - Ohio is super weird and not seeing that result on any device.

**Comment by ERosendo** [comment]
I just checked the coverage page and I'm not seeing that result. 🤔

**Comment by ERosendo** [comment]
I'm getting this chart for Ohio:

<img width="1736" alt="Screenshot 2023-10-13 at 2 30 14 PM" src="https://github.com/freelawproject/courtlistener/assets/55959657/d4018366-422a-4ef2-9736-3e7e0db04f28">

**Comment by flooie** [comment]
@mlissner I've tested this on Safari, Firefox, Mobile Safari and Chrome - and do not see those results.

**Comment by mlissner** [comment]
Hm, it works for me on Chrome, but not Firefox. I did a SHIFT+R refresh, but that didn't change anything (nor did I expect it to with our cache-busting approach). I don't know why it'd do that, but if it's just a me on Firefox/Linux thing, I think we can leave it be and focus on the rest.

**Comment by mlissner** [comment]
OK, but if every line is black, how will you know that lines 3 and 4 of my screenshot above are for scrapers and lines 1 and 2 are not?

**Comment by flooie** [comment]
You won't on mobile - but they will be listed as such on larger screen sizes.  Alternatively we could add a (Scrp) or something to the label on the right?

**Comment by flooie** [comment]
Additionally 

```
    <script type="text/javascript" nonce="{{ request.csp_nonce }}">
        var precedentTypes = [
            {% for status in precedential_statuses %}
                '{{ status }}'{% if not forloop.last %},{% endif %}
            {% endfor %}
        ];
        var sorted_courts = {{ sorted_courts|safe}};
    </script>
```
I believe this can be removed as well - as it creates variables that were used in the coverage.js file that was removed

**Comment by mlissner** [comment]
> Alternatively we could add a (Scrp) or something to the label on the right?

Easy enough and better than nothing. Sure.

**Comment by mlissner** [comment]
OK, I think we can close this one with #3254
