### ISSUE TITLE
5 opinions register in solr in they year 1018 

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#3229]
https://www.courtlistener.com/?q=&type=o&order_by=dateFiled%20asc&stat_Precedential=on&filed_before=10%2F05%2F1050&court=fladistctapp

The data is fixed - apparently an artifact of scraping - but it throws off the chart we now use on the data coverage page for Florida.

**Comment by mlissner** [comment]
What makes you think that?

**Comment by flooie** [comment]
Well... just wondering - what other anomalies we've fixed that we will discover.

**Comment by mlissner** [comment]
Ah. Well the good news is that when we move to elastic we'll begin doing a much better job keeping things synced (there's a lot of new code dedicated to this). Hopefully we can avoid having to re-index until then.
