### ISSUE TITLE
Remove "Send Alert Anyway" feature from front end or completely

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#323]
We have a feature on alerts that allows people to ask CL to "Send me an email even if there are no new hits". The original idea for this was to remind people that the system was working, and interestingly about 10% of our alerts have this turned on, but I don't think this is doing anybody any favors and two devs have wondered why this is even a feature. 

For people that have Real Time alerts, they'll get an email every ten minutes if they check this box -- that's pretty disastrous.

Two solutions here. Need feedback as to the better one to pursue:

1. Remove the feature completely. This is the cleaner solution, but the irreversible one.
2. Remove the feature only from the front end and see if anybody complains. If not, remove it everywhere at some later undefined time. 

I welcome thoughts, but will probably do number 2 soon unless people think I should just nuke the darned thing.

cc/ @konklone, @jraller

**Comment by konklone** [comment]
Option 3: You could leave the database in place, but disable the feature and see if anyone complains. That way it's reversible, but also a lot less work.

**Comment by mlissner** [comment]
You mean disable it in the alert sender, but leave the rest alone for a while?

**Comment by konklone** [comment]
I guess hide it in the front-end too. I just meant, nuke it logically but don't remove the database column, making it reversible if people complain.

**Comment by brianwc** [comment]
Yeah, we probably have this because lawyers/paralegals are paranoid. If they rely on a service, then knowing that it is working is paramount. For something that's important to someone, there's no such thing as too many emails. I agree though that some sort of quiet gradual death of this feature would probably be OK and not cause any squawking.
Brian

On January 8, 2015 4:54:31 PM PST, Eric Mill <notifications@github.com> wrote:
>I guess hide it in the front-end too. I just meant, nuke it logically
>but don't remove the database column, making it reversible if people
>complain.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/freelawproject/courtlistener/issues/323#issuecomment-69277672

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
I'm going to turn this off logically and in the front end. If we get a complaint, we'll consider changing it back. The thing that convinced me is this feature combined with real time alerts.

**Comment by mlissner** [comment]
I've removed this from the backend as well. Will be pushed out soon.
