### ISSUE TITLE
Count of parent documents in Search page header results is limited to 10,000 documents.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3251]
This issue is affecting ES documents that use parent-child approach (RECAP and Judges).

It seems related to the max number of results that an ES query can return by default.

<img width="670" alt="Screenshot 2023-10-13 at 12 11 41" src="https://github.com/freelawproject/courtlistener/assets/486004/54255dfe-cf55-456d-a34e-1d9c7d0a0f70">

**Comment by mlissner** [comment]
Bad news: We didn't fix this in the HTML title tag. Reopening, I'm afraid.
