### ISSUE TITLE
Filter Connecticut out of New Opinions List on Front Page

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#327]
Connecticut has messed up dates on their opinions. They provide the date it will go into some reporter. This date is in the future. Therefore, ever since we started retrieving their opinions, they have always appeared on the front page as the most recent, even when they're not really the latest ones we've retrieved.

Two potential fixes:
1. See if there is a way to get a more accurate date on each of these opinions. I'm not sure this is even the right thing to do. We'd need to investiage Connecticut practice and figure out which date really matters to them (the date it appears on the website/is released or the date it appears in the reporter).
2. Just hack the front page to not include them. Penalize them for being weird. I'm sort of leaning towards this.

**Comment by mlissner** [comment]
Option 2 is pretty easy. Just have to tweak the query appropriately.

**Comment by mlissner** [comment]
Only took a couple years. Done.
