### ISSUE TITLE
The recap index has more documents than the results — why?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3271]
Looking at the RECAP index, there are currently about 70 million items in it:

![image](https://github.com/freelawproject/courtlistener/assets/236970/297fdb8b-74fb-4dfa-9ff5-0ba676c45101)

But in the front end, there are 66M. 

![image](https://github.com/freelawproject/courtlistener/assets/236970/700370ea-b359-4baf-b94d-68c6d3751dd8)

This smells like a bug of some kind and we should figure out why it's happening.

**Comment by albertisfu** [comment]
I was thinking about the discrepancy in document counts, and I believe the answer may be that the count in Kibana includes both Dockets and RECAPDocuments, while the count on the frontend only considers RECAPDocuments. Once we correct the count for the Cases, we can determine whether it matches the count in Kibana.

**Comment by mlissner** [comment]
I was theorizing that too! 4M cases feels low at this point, but it could be.

**Comment by mlissner** [comment]
OK, yeah, the math works. Kibana says 8M, the front end says 7.5M dockets and 100.5M entries. 

Great.
