### ISSUE TITLE
Webhook logs need timezones

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3274]
I'm looking at this and wondering what it means: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/5e6a9a56-c4e5-46c5-a6c1-33c162c65b39)

And this isn't helping, unfortunately: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/3360f015-daae-4c64-8cfd-694aa3da795d)

I literally don't know how to make sense of this, and, oh boy, if I can't, nobody can!

**Comment by elisa-a-v** [comment]
@mlissner do we have a preference for the timezone used to display times? we briefly talked about this with @albertisfu and he made some good points in keeping it aligned with other platforms like sentry which uses UTC, but I wanted to know what you think.

In general I'm more inclined to use local time when showing info to humans, [which is django's default behavior](https://docs.djangoproject.com/en/5.1/topics/i18n/timezones/#time-zone-aware-output-in-templates), but if the users are expecting UTC, then that seems like the best bet... who are the main users of these views?

**Comment by elisa-a-v** [comment]
I just added the display for the timezone for now, but I noticed that it always switches to PST so it's neither UTC nor my local time 😅 I'm not sure how important this is for the users tbh? we could easily add a custom filter I guess.

**Comment by mlissner** [comment]
I think just doing UTC is easiest. IIRC, getting the user's timezone is hard with browsers?

**Comment by albertisfu** [comment]
> I think just doing UTC is easiest. IIRC, getting the user's timezone is hard with browsers?

Yeah, another point that Elisa and I were discussing is that using the user's browser time zone might not be helpful if the user's webhook server is in a different time zone. For instance, the user might be located in CST, but their servers could be in PT, requiring a time zone conversion for debugging purposes

**Comment by elisa-a-v** [comment]
Got it, I just updated the PR so it now always displays datetimes in UTC in these views 👌🏽
