### ISSUE TITLE
Add Update Date to bulk data meta data

### ISSUE THREAD

**Issue by garvincasimir** [freelawproject/courtlistener#331]
I am working on a project which intends to automatically import data using the bulk api and I was wondering if the last updated date of the dataset can be accessed by automated tools.

    GET /bulk-data/info/
    {
         LastUpdated: 1/2/2015,
         TotalDocuments: 3828438383,
         ........
    }

I don't mind contributing this myself if there isn't already a way to get this information. Please point me in the right direction.

**Comment by mlissner** [comment]
That's a good idea. Right now the bulk data is organized in directories like:

/api/bulk-data/document/
/api/bulk-data/audio/

If you go to those locations you can see the file mod date, so you could just use that and be done. But it would be nice to have a file in there called something like `info.json`:

    {
      LastUpdated: "2015-03-31 13:33:33 UTC",
      Count: 23434829,
      Items: {
        "acca.tar.gz": {
          "totalCount": 33
        }
      }
    }

The place to add this functionality would be in [the script that makes the bulk data](https://github.com/freelawproject/courtlistener/blob/master/alert/api/management/commands/cl_make_bulk_data.py#L21-L31)

**Comment by garvincasimir** [comment]
Thanks @mlissner I will take a look. I will start using the modified date in the header and work towards adding the info.json file. I intend to use the count to help report the progress of imports by comparing the total processed to the count provided by the api.

**Comment by garvincasimir** [comment]
What do you think about adding the count as a custom header? That way both bits of information can be accessed in the header of any bulk api request.

**Comment by mlissner** [comment]
Doing it as a header will probably be harder. These files are served
directly by Apache, so we'd have to re-work the system to serve them from
Django, where we can do dynamic things like headers.

**Comment by mlissner** [comment]
Hi, @garvincasimir. Some news for you today. I have been working on v3 of the API and I got this feature in. There's a new file called `info.json` that will be created in any directory where we store bulk data. It will have the date of creation and the duration of the generation process.

Thanks for the great idea. It took a while, but it'll be deployed soon.

**Comment by garvincasimir** [comment]
This is great news. Thank you @mlissner!
