### ISSUE TITLE
Add replicas after indexing is complete

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3316]
One tip to make indexing faster during bulk indexing is to slow down the refresh_interval of the index. This means results are slower, but it lets things index faster. So I just ran this:

```
PUT /recap/_settings/
{
  "index" : {
    "refresh_interval" : "300s"
  }
}
```

That means that refreshes will only happen every five minutes. Once everything is indexed, we need to reset this to the default by running:

```
PUT /recap/_settings/
{
  "index" : {
    "refresh_interval" : null
  }
}
```

**Comment by mlissner** [comment]
I also just set the number of replicas to zero. It seems like it should be fine, but once we're done we need to reset it to 1. This is what I ran:

```
PUT /recap/_settings
{
  "index" : {
    "number_of_replicas" : 0
  }
}
```

**Comment by albertisfu** [comment]
After disabling the replicas, did the speed improve?

**Comment by mlissner** [comment]
A little, but kind of a disappointing amount. Maybe 15-20%, but we're still at around 2-300/s, whereas we were much higher before.

**Comment by mlissner** [comment]
I just set the refresh interval back to the default with:

```
PUT /recap/_settings/
{
  "index" : {
    "refresh_interval" : null  }
}
```

I don't think it made much difference, and it was definitely creating more trouble. 

We still need to create replicas though.

**Comment by mlissner** [comment]
We just added a replica to the recap index, as above. Kibana was down earlier today, so we did it with:

```
curl -X PUT -k --user xxx:xxx 'https://localhost:9200/recap/_settings' --header 'Content-Type: application/json' --data '{"index" : {"number_of_replicas" : 1 }}' | jq
```

It took about an hour to complete.
