### ISSUE TITLE
Search should prioritize citations

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#334]
If someone types something that we can recognize as a citation into the regular search bar AND we have exactly one perfect match to that citation, then we should just ignore everything else they type and give them the cited result. I say this because extensive use of the Free Law Ferret has taught me that currently, even when the Ferret feeds CL the correct citation, and even when we have one exact match for that citation, if the source web page has some variation in the case name such as a strange abbreviation then we return NO results when we actually have the document and have simply been given too much information. Example:
A search for: New Era Publ’ns Int’l, ApS v. Carol Publ’g Grp., 904 F.2d 152 (2d Cir. , 1990)
will not lead you to
https://www.courtlistener.com/opinion/542305/new-era-publications-international-aps-plaintiff-a/
whereas a search on: citation:"904 F.2d 152" 
(with quotation marks) will yield precisely the correct result. So, the proposal is to intercept all searches, check them for citations, and if a citation is found, convert the search to a quoted citation search instead. 

That's pretty extreme, and we could give users a warning that this is happening "Interpreting this as a citation search..." or something, but we need some means of allowing people to find documents we have, that they know how to cite, when they just happen to use abbreviations we don't like.

**Comment by mlissner** [comment]
Good idea, fairly easy to do.

**Comment by mlissner** [comment]
Implementing this is hard and it breaks boolean results in a really nasty way. Maybe a better option would be to try to identify citations and if we find one, return the results we'd normally return, but include a "Did you mean" blurb that says something like:

> We identified a citation to 904 F.2d 152. [Search only for this citation][1].

The API could (probably) also be set up to have a "Did you mean" section that implementations like Free Law Ferret could use to repeat a query.

[1]: #

**Comment by mlissner** [comment]
This is all set, and working marvelously. Behold an example for searching for a citation from Roe v. Wade. Note that there's a new little blue warning thing, and that the first result isn't Roe. Totally a helpful feature.

![screenshot from 2016-06-24 13-52-35](https://cloud.githubusercontent.com/assets/236970/16350316/f29ce0ec-3a12-11e6-8482-ab9a0634f177.png)
