### ISSUE TITLE
Phrase search on RECAP does not match the document's plain_text

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3347]
@johnhawkinson reported to us a bug related to searching for a phrase in the new RECAP search. The phrase should match the document's `plain_text`, but it doesn't.

https://www.courtlistener.com/?type=r&q=%22Dr.%20Israel%20also%20demonstrated%20a%20misunderstanding%20and%20misapplication%20of%20antitrust%20concepts%22

We can confirm the document is indexed:
https://www.courtlistener.com/?q=docket_id%3A60400918&type=r&order_by=score%20desc&document_number=344

**Comment by mlissner** [comment]
Yeah, I did some experiments. I think it has to do with phrase search and stopwords, though I thought we got rid of stopwords. 

But, like, if I disable phrase search, we get results. This is for the document id + John's phrase just as search terms and it gets one result:

https://www.courtlistener.com/?q=id%3A337817738%20It%20aims%20to%20preserve%20the%20free%20functioning%20of%20markets%20and%20foster%20participation&type=r&order_by=score%20desc

![image](https://github.com/freelawproject/courtlistener/assets/236970/02491c76-f331-4e72-9e77-6f8d366c3a12)

Interestingly though, the stopwords are not highlighted. 

I was playing with [the ultimate stopwords phrase](https://en.wikipedia.org/wiki/To_be%2C_or_not_to_be) yesterday too, and didn't get the results I'd hoped for:

https://www.courtlistener.com/?q=%22to%20be%20or%20not%20to%20be%22~10&type=r&order_by=score%20desc

![image](https://github.com/freelawproject/courtlistener/assets/236970/683b1d17-442e-4e99-b872-7bf9fed89211)

Look at that highlighting, and, plus, it's wrong.

**Comment by mlissner** [comment]
This is done at the schema level, but it needs a full reindex to be fixed, which we can't wait for. We'll go live with phrase search being broken on stopwords, and it will slowly get fixed as we reindex the entire corpus. See #3422 for that process.

**Comment by mlissner** [comment]
@johnhawkinson, just FYI, the issue you reported back in November related to repeated terms in phrases not working properly is now fixed. (We had to reindex the whole damned thing.)

Thanks for flagging this.

**Comment by mlissner** [comment]
And I just checked my "to be or not to be" query, and got back the results I'd expect. Great.
