### ISSUE TITLE
Decoding texts from specific sources

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#3397]
the following cluster IDs for Tenn Work Comp App have the same issue.  

```
4779899
4779890
4779716
4779718
4779719
4779732
4779686
4779704
4779515
4779481
4780119
4779918
```

We have a similar issue for Tenn Workers Comp CL but I havent been able to identify them yet. 

### Discussed in https://github.com/freelawproject/courtlistener/discussions/3372

<div type='discussions-op-text'>

<sup>Originally posted by **Eran-T** November 14, 2023</sup>
Hi,
I have a question regarding a specific opinion I ran into. (https://www.courtlistener.com/api/rest/v3/opinions/4560099/)
It seems that while extracting the contents of the opinion (seems to have went through OCR) the content was either decoded incorrectly or noise was added (as there does seem to be a proper utf-8/unicode section in there).

My question is whether you might have an assumption as to how it ended up this way and whether the non-coherent section is decodable. 

Thanks for the help!</div>

**Comment by flooie** [comment]
This is certainly a bug in the PDF - both pdfplumber, pypdf2 and simple GUI preview all have issues with the text.  The easiest options are ... 1) convert the pages to an image and OCR them or 2) reach out to the court for corrected and fixed PDFs to replace them with.

**Comment by mlissner** [comment]
Let's see if we can work this out with the court. That'd be much better than jumping through technical hoops.

**Comment by flooie** [comment]
Contacted the court today, will report back when I hear more.  Hopefully they'll have a good way to generate the new PDFs

**Comment by mlissner** [comment]
How did the contact go? Phone call, email, or something else? I'm trying to judge if they're going to respond, and if so, if that'll happen any time soon.

**Comment by flooie** [comment]
Emailed and called. But they're usually quite receptive.

**Comment by flooie** [comment]
Tennessee has kindly provided 12 fixed PDFs for the corrupted files.

**Comment by flooie** [comment]
- [ ] 4779899: McLaurin, Katlyn N. v. AT&T Services, LLC                          2017-03-1133         2019-01-31
- [ ] 4779890: Hollis, Aliceia v. Komyo America                                   2016-03-0298         2019-01-22
- [ ] 4779716: Jackson, Michael v. Transwood                                      2016-08-0937         2018-05-02
- [ ] 4779718: Ogden, Shawn v. McMInnville Tool and Die, Inc.                     2016-05-1093         2018-05-07
- [ ] 4779719: Andrews, Torey v. Yates Services, LLC                              2016-05-0854         2018-05-08
- [ ] 4779732: Watson, Robert v. Catlett Construction                             2017-05-0515         2018-05-18
- [ ] 4779686: Summers, Mary v. BrightSpace Senior Living, LLC                    2017-06-0811         2018-03-22
- [ ] 4779704: Creasman, Sherry v. Waves, Inc.                                    2017-05-0843         2018-04-16
- [ ] 4779515: Beecher, Carolyn v. McKesson Corporation                           2016-08-0279         2017-07-21
- [ ] 4779481: Lamm, Terry v. E. Miller Construction, Inc.                        2015-01-0429         2017-06-02
- [ ] 4780119: Caldwell , Ricky v. Federal Mogul Motorsports Corp.                2019-04-0074         2019-10-11
- [ ] 4779918: Glenn, Terrance Garcia v. Sears Outlet Stores, LLC                 2017-06-0584         2019-02-28

**Comment by flooie** [comment]
Completed

**Comment by flooie** [comment]
Found one more. 

https://www.courtlistener.com/opinion/4779752/wallisjeffrey-v-baptist-memorial-hospital/

Or more accurately, did not include the original issue starter.
