### ISSUE TITLE
Activate Elastic Waffles

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3409]
I think we've got some of these turned off, and I forget why. I've had an open tab in my browser for the `os-es-alerts-active` waffle for several weeks. 

I'm making this issue so we remember to get this fixed and enabled properly.

**Comment by albertisfu** [comment]
Yeah, [oa-es-alerts-active](https://www.courtlistener.com/admin/waffle/switch/2/change/)  is the switch used to enable OA alerts to work with ES. We disabled it when ES indexing signals were disabled, so OA Alerts continued working with Solr. Now that we have signals enabled, we can activate this one again.

**Comment by mlissner** [comment]
OK, it's now like this: 

![image](https://github.com/freelawproject/courtlistener/assets/236970/cf8b60b2-c900-41f9-9d70-ebe28a99e422)

Can we close this issue?

**Comment by albertisfu** [comment]
perfect, yeah it seems good.
This can be closed.
