### ISSUE TITLE
Apply the necessary changes to the index to resolve the 3347 phrase matching issue

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3422]
In #3383, we resolved the phrase-matching issue of #3347. However, the solution won't take effect until we apply the changes to the index.

- As part of the solution, there is a new search time analyzer, `search_analyzer_exact`. In theory, it doesn't require re-indexing the content since it only affects search time. Therefore, we should investigate a way to make this new analyzer available and operational.
Additionally, it might be necessary to update the index mapping to recognize the new search time analyzer.
It seems that this can be achieved by closing the index before updating the index settings and mapping and then opening it again.

- Regarding the avoidance of removing duplicates in the english_exact analyzer, since this is an index-time analyzer, it requires re-indexing the content. The [reindex API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html) or using the [Alias](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html) can help to do this faster.

**Comment by mlissner** [comment]
Great, thanks. Let me know how you want to proceed and we'll get this going.

**Comment by mlissner** [comment]
This is on the Elastic backlog. I set it to be completed after we figure out all the transport errors and other indexing issue, in case something else comes up, and so that when/if we copy the index, we can be sure we get everything into the new one.

**Comment by albertisfu** [comment]
Got it, yeah this sounds good. So I'll work on all the other issues at the top of Launch Blockers, so we can be sure to solve them before getting this one done.

**Comment by mlissner** [comment]
We're in good shape here. The last step is a full reindex as in #3629
