### ISSUE TITLE
Mark PacerFetchQueue tasks as failed on PacerLoginException errors

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3423]
We should mark `PacerFetchQueue` tasks as failed on `PacerLoginException` errors during the last retry and add a message indicating the reason for the failure.

We could also increase retries for these errors.

This way, we can stop sending these errors to Sentry.

**Comment by mlissner** [comment]
Thanks Alberto. I'm going to put this on Eduardo's backlog, so he can take care of it and you can stay focused on Elastic. 

Did we have an issue/Sentry thing this should/could reference?

**Comment by albertisfu** [comment]
great! yeah, the Sentry issue that can be referenced is this one:
https://freelawproject.sentry.io/issues/4237283204/?project=5257254

**Comment by albertisfu** [comment]
We knew this issue occurred occasionally, but strangely, in the last few days, the errors here have skyrocketed.

![Screenshot 2024-03-06 at 20 05 38](https://github.com/freelawproject/courtlistener/assets/486004/a29701a6-3e75-4ba6-81c8-823c032f207e)

This is problematic because it means all of these `PacerFetchQueue` attempts failed after all the retries. I'm wondering if the volume of `PacerFetchQueue` requests has increased proportionally, or if there is anything else on the PACER side causing this to fail more frequently.

**Comment by mlissner** [comment]
Nothing that I'm aware of, but it's probably worth looking into, yes. But let's hold off and stay focused on Elastic to get it over the line.
