### ISSUE TITLE
Incorrect citations in columbia dataset

### ISSUE THREAD

**Issue by quevon24** [freelawproject/courtlistener#3428]
@flooie is running the columbia merger and realized that there was a problem with the columbia xml file, specifically with the citation, in the xml we have "78 So.2d 646", but in the cluster we have "178 So. 2d 646" (https://www.courtlistener.com/opinion/6650122/x/) , verifying the scan of the book (https://cite.case.law/pdf/1710532/Town%20of%20Hammondville%20v.%20Chadwick,%2043%20Ala.%20App.%2012,%20178%20So.%202d%20646,%207%20Div.%20796%20(1965).pdf) it seems that the correct citation is "178 So. 2d 646".

![image](https://github.com/freelawproject/courtlistener/assets/6474994/a33bd5c5-d0be-4e7d-bc4b-c5ad6d569c5f)

We think that a good fix in the merger would be to add an additional check to avoid having two citations from the same reporter.

**Comment by mlissner** [comment]
Smart. I suppose the fix for this will wind up in the same repo we used for Harvard fixes?

**Comment by quevon24** [comment]
> Smart. I suppose the fix for this will wind up in the same repo we used for Harvard fixes?

Well in this specific situation we already have the correct citation from the harvard data, we don't need to fix it, we simply ignore it when we try to add the new citations in the columbia merger because we already have a citation with that reporter.

I'm not sure if we should fix the citations in the xml file as we did with harvard data. What do you think @flooie?

**Comment by mlissner** [comment]
Isn't the idea of the Github repo that it has fixes for all the various bulk imports that we do? Like, shouldn't fixes to the Columbia data go in there too?
