### ISSUE TITLE
date_decided vs. date_filed?

### ISSUE THREAD

**Issue by ariddell** [freelawproject/courtlistener#344]
Just noticing that date_filed in the .json is the decision date and (I assume) not the filing date. I found this a little confusing. SCDB uses "dateDecision".

Looking at ``795504.json``, 461 F.3d 181, Anthony Disimone, Petitioner-Appellee-Cross-Appellant v. William E. Phillips, Eliot L. Spitzer, Respondents-Appellants-Cross-Appellees

**Comment by mlissner** [comment]
Yeah, that's a great point. We're doing a big DB restructure soon and I'll see if I can slip this in. Thanks.

**Comment by mlissner** [comment]
@brianwc Any opposition to this change? I can definitely rename this field without *too* much trouble.

**Comment by brianwc** [comment]
I believe we've always meant "date the decision was filed" by "date_filed" so if date_decided makes that clearer, that's fine. However, I believe some courts "decide" a case on one day, perhaps noting the just of the decision briefly on the docket, and then "file" the full opinion on some later date, the date we would use. So, making this change could just confuse people the other way. They'll file a bug saying it wasn't "decided" on that date it was "filed" on that date! Whatever we call it, we've always meant the date the document became available.

**Comment by mlissner** [comment]
That sounds more like date filed to me. I think we can close this one then,
unless anybody is opposed.

**Comment by ariddell** [comment]
@brianwc, I think what you have recorded as date_filed is actually date_decided in the sense that you describe. It's not a nomenclature issue.

SCDB records "dateArgument","dateRearg", dateDecision; with Appellate cases I see Argued, and Decided dates (http://openjurist.org/461/f3d/181/anthony-disimone-cross-v-william-e-phillips-eliot-l-spitzer-cross). In my small sample, what others record as the decision date is recorded in court listener as date filed.

**Comment by mlissner** [comment]
Would be nice to be consistent.

**Comment by mlissner** [comment]
I'm closing this at least for now, but if you guys can reach consensus, please feel free to reopen. My thinking is that if two lawyers can't agree the status quo is fine.
