### ISSUE TITLE
Probably missing harvard data

### ISSUE THREAD

**Issue by quevon24** [freelawproject/courtlistener#3448]
While i was helping @flooie with some citations that were added incorrectly to some harvard cases i discovered that some cases were not imported with the harvard opinion importer.

If you search for this citation "143 A.D.3d 1297" in courtlistener, you will get two cases (and both are duplicated) but if you go to: https://archive.org/download/law.free.cap.ad3d.143/ there are 9 cases that matches that citation (page 1297) and you can also see it in the book scan: https://cite.case.law/pdf/12176865/in%20re%20Roberto,%20143%20A.D.3d%201297,%2038%20N.Y.S.3d%20507%20(2016).pdf

This happened because there were very specific circumstances:

- Cases share the same citation
- Opinions have the same content
- All cases include the "In re" in the name

I'm not sure how usual this is, but those circumstances broke the algorithm  we use to try to match the file data with cases, and decide if we should create a new cluster or just add the citations to an existing cluster.

We need to remove "in re" when we compare the case names, we already have code for that, we just need to add "in re" in the list of false positive strings.

The long explanation is in this pr: https://github.com/freelawproject/courtlistener/Pull/2360

After doing this we need to identify what cases we are missing and run the importer again for those files.

**Comment by mlissner** [comment]
Doesn't sound good. We better get this slotted in to our priorities....

**Comment by flooie** [comment]
This has been completed
