### ISSUE TITLE
recap.email is updating docket date_filed with the entry date_filed

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3449]
Continue monitoring ES **`ConflictErrors`**. The latest events are related to the docket **`date_filed`** update.

Upon checking, it appears that the affected dockets were updated by both the RSS feed and recap.email. The issue is that recap.email updates the docket's **`date_filed`** with every new entry, triggering an additional UBQ request, which triggers a `ConflictError`.

The root of the problem lies in the recap.email parser using the entry's **`date_filed`** as the docket's **`date_filed`**.

e.g:
```
"dockets": [
    {
      "case_name": "Cunningham v. The City of New York",
      "date_filed": "2022-08-01",
      "docket_entries": [
        {
          "date_filed": "2022-08-01",
       ...
        }
      ],
      "docket_number": "1:22-cv-00588"
    }
  ]
```
So, the docket **`date_filed`** is updated with every new recap.email entry.

It appears that the docket **`date_filed`** is not available in NEFs or NDAs. Therefore, we should consider stopping populating the docket **`date_filed`** from recap.email.

Let me know what you think.

**Comment by johnhawkinson** [comment]
This is a complicated issue and it is related to the issue of `date_filed` versus `date_entered` and how only one of these exists in the current RECAP schema.

However

> It appears that the docket **`date_filed`** is not available in NEFs or NDAs. Therefore, we should consider stopping populating the docket **`date_filed`** from recap.email.

That is not correct. A NEF typically looks like this:

> The following transaction was entered by Benon, Holden on 12/8/2023 at 3:10 PM                                                                                                                                            
PST and filed on 12/8/2023                                                                                                                                                                                                

With the date entered and the date filed both. What you don't get is the time of filing (which I do not think CM/ECF tracks?). Or here's an example where they differ, from USA v. Trump:

> The following transaction was entered on 11/27/2023 at 10:08 AM EDT and filed                                                                                                                                             
on 11/22/2023                                                                                                                                                                                                             

The same is true in NDAs:

>  The following transaction was entered on 12/08/2023 at 2:11:27 PM Eastern                                                                                                                                                 
Standard Time and filed on 12/08/2023                                                                                                                                                                                     

(note that the leading zero in the date is present in NDAs but is also present in "regenerated NEF"s from the district court. Err, and also the seconds.

**Comment by albertisfu** [comment]
Got it, yeah the entries `date_filed` and `date_entered` are available in the emails.

However, the field I'm referring to in this issue is the **Case** `date_filed`.

![Screenshot 2023-12-11 at 9 12 12](https://github.com/freelawproject/courtlistener/assets/486004/f9f7b005-00b6-4c9a-a869-f61f9445faee)

The problem is that we're overwriting the case `date_filed` with the entry `date_filed` every time we receive a new email, since the Case `date_filed` is not available in emails. Therefore, we're using the `entry date_filed` to populate this field.

**Comment by mlissner** [comment]
> It appears that the docket date_filed is not available in NEFs or NDAs. Therefore, we should consider stopping populating the docket date_filed from recap.email.

That makes sense to me. Looks like these `ConflictErrors` are going to do some good things for our data integrity.

**Comment by johnhawkinson** [comment]
Oh, gosh, terribly sorry for the confusion! Yes, the case's `date_filed` should not be populated from the NEF and is never available from the NEF (although you could probably make an assumption if you got a rare NEF for the case-initiating document, but those are quite rare and only some people ever get them.) Carry on!

**Comment by mlissner** [comment]
Seems like this might be done. Can you verify, Alberto?

**Comment by albertisfu** [comment]
Yeah, I've verified and this issue is solved.
