### ISSUE TITLE
Deadly Error on Mobile After Filtering and Ordering

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#345]
This happens consistently for me on Chrome 43.0.2357.93 on Android 5.1.1.

*Steps to reproduce*:
1. Select the jurisdiction picker.
2. Clear all selections.
3. Select Supreme Court of U.S.
4. (It returns you to advanced search) Select Order by "Newest First"
5. It now (should) automatically take you to the latest SCOTUS opinions, but instead produces a "deadly error."

**Comment by mlissner** [comment]
If you have the URL, that'll help.

**Comment by brianwc** [comment]
The same steps do not produce this error for me any more. Closing as elusive intermittent error.

**Comment by mlissner** [comment]
That's weird. I guess in the future a timestamp will help with these kinds of issues, but intermittent errors are the most elusive for sure.
