### ISSUE TITLE
Change headers from "Opinions" to "Case Law" 

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3472]
I was demoing CourtListener the other day and I realized that people think about things in terms of "Case Law," not "Opinions".

We should update CourtListener and free.law to say Case Law wherever possible.

@flooie, do you agree?

**Comment by flooie** [comment]
I think it's a very good decision

**Comment by mlissner** [comment]
Wildly annoying how long these kinds of things take to identify sometimes!

**Comment by mlissner** [comment]
We chatted about this on Slack. The biggest argument for "Caselaw" is that Harvard did it, but it seems like they liked the CAP acronym better than CLAP, so I think following their lead isn't necessarily right. I also did a poll which had unanimous support for "Case Law", and I like it better, so "Case Law" it shall be!
