### ISSUE TITLE
Lawbox import problem

### ISSUE THREAD

**Issue by brianwc** [freelawproject/courtlistener#353]
Here is an example:

https://www.courtlistener.com/opinion/2051624/cooper-v-state/

This document has data in the html_lawbox field but nothing in the html_with_citations field. Consequently the displayed version on the site has no citation hyperlinks. It seems like some part of the lawbox import must have had a problem. Oh, and this is not an isolated example. I'm fairly sure there are thousands. It's unclear whether simply running the citation finder anew would resolve this. Instead it seems like the citation finder could have a bug with respect to certain lawbox docs.

**Comment by mlissner** [comment]
It'd be good to get a feel for the scope of this problem, but my sense is that it's better to let it slide until the next big collection comes online. When that happens, we'll be re-running the citation finding script anyway. 

I could kick it off now, but it takes a ton of resources and also requires a bit of babying to make sure it's going smoothly, not hitting the server too hard, hasn't hit an exception, etc. In the past when I've run it, I've checked in on it a couple times daily to make sure all's well.

**Comment by brianwc** [comment]
A db query to find those with anything in lawbox_html and nothing in html_with_citations would probably identify the scope of the problem.

On August 12, 2015 8:40:00 AM PDT, Mike Lissner <notifications@github.com> wrote:
>It'd be good to get a feel for the scope of this problem, but my sense
>is that it's better to let it slide until the next big collection comes
>online. When that happens, we'll be re-running the citation finding
>script anyway. 
>
>I could kick it off now, but it takes a ton of resources and also
>requires a bit of babying to make sure it's going smoothly, not hitting
>the server too hard, hasn't hit an exception, etc. In the past when
>I've run it, I've checked in on it a couple times daily to make sure
>all's well.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/freelawproject/courtlistener/issues/353#issuecomment-130346449

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
Well:

```courtlistener=> select count(*) from "Document" where "html_with_citations" = '' and "source" = 'L';
  count  
---------
 1141778
```

Looks pretty bad, but I still recommend against dealing with it now. Running the citation finder is a big deal and we'll be running it soon enough with an even bigger collection.

**Comment by brianwc** [comment]
Source = L is 1,531,528 documents, so this affects right at 75% of this import. Agree that it should be handled all at once with big citation finding run coming soon. Just puzzling how so many of these never got properly processed.

**Comment by mlissner** [comment]
Closing: This is getting fixed by the current run of the citation parser. Thanks @brianwc for getting it filed.

BTW: We're up to 24M citations and counting.
