### ISSUE TITLE
Missing or duplicated document from nev (Nevada Supreme Court)

### ISSUE THREAD

**Issue by grossir** [freelawproject/courtlistener#3531]
Related to Taylor v. Brill (Nev. 2023) filed on December 21st, 2023. 

We have 2 opinions with that name and date on [courtlistener](https://www.courtlistener.com/?type=o&q=court_id%3Anev&type=o&order_by=dateFiled%20desc&stat_Precedential=on), but on the [source](https://publicaccess.nvsupremecourt.us/WebSupplementalAPI/api/AdvanceOpinions)  there are 3 records, with 3 different document urls:

```
[
    {
        "advanceNumber": 56,
        "caseNumber": "84492",
        "caseurl": "https://caseinfo.nvsupremecourt.us/public/caseView.do?csIID=63690",
        "caseTitle": "Taylor v. Brill, M.D.",
        "date": "2023-12-21T00:00:00",
        "docurl": "https://caseinfo.nvsupremecourt.us/document/view.do?csNameID=63690&csIID=63690&deLinkID=928050&onBaseDocumentNumber=23-41427"
    },
    {
        "advanceNumber": 56,
        "caseNumber": "84881",
        "caseurl": "https://caseinfo.nvsupremecourt.us/public/caseView.do?csIID=64215",
        "caseTitle": "Taylor v. Brill, M.D.",
        "date": "2023-12-21T00:00:00",
        "docurl": "https://caseinfo.nvsupremecourt.us/document/view.do?csNameID=64215&csIID=64215&deLinkID=928050&onBaseDocumentNumber=23-41427"
    },
    {
        "advanceNumber": 56,
        "caseNumber": "83847",
        "caseurl": "https://caseinfo.nvsupremecourt.us/public/caseView.do?csIID=62820",
        "caseTitle": "Taylor v. Brill, M.D.",
        "date": "2023-12-21T00:00:00",
        "docurl": "https://caseinfo.nvsupremecourt.us/document/view.do?csNameID=62820&csIID=62820&deLinkID=928049&onBaseDocumentNumber=23-41426"
    }
]
```

The first 2 docurls direct to the same document, other metadata like caseNumber andd caseurl are different

Are we missing an opinion or is it a duplicated record?

**Comment by flooie** [comment]
This case is a little strange - 

It looks like it was three separate cases - but that the Supreme Court may have just ruled on all three at the same time and issued the opinions as separate opinions but actually just post of the same opinion at the end of each docket and case.  

Very strange and not something I've seen before.  But because they do in fact list these as separate documents on their website, I'm inclined to leave them all in CL for now.
