### ISSUE TITLE
Need to deprecate the "type" GET argument. 

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#355]
Alas, it was a good argument, but the new system will allow people to make queries like:

    type:combined

Or:

    type:dissent

Once that happens, we might want to have an input box that allows people to set the type via a drop down or multi-select. 

If that happens, we'll have the problem that we already use `type` to determine if it's an oral argument page ("oa") or an opinion page ("o"). 

The solution here is probably to make the current GET parameter be `object_type` or `result_type` or maybe just `t`. Doing any of those will fix this problem.

We'll also have to update all the old alerts, but we won't be able to fix or redirect the queries people have in their browser history. Those will just break.

**Comment by brianwc** [comment]
Seems like the hierarchy we have (or could plan for) is something like:

media: {audio, video, document}
 doc_type: {opinion, complaint, brief, declaration...}
  opinion_type: {lead, concurrence, dissent, errata}

In lieu of 'media' we could instead have:
file_type: {mp3, mp4, PDF, html, txt, JSON}

This might enable a premium service: PDFs via API.
