### ISSUE TITLE
RECAPDocuments from RECAP.email are not being linked to their corresponding EPQs

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3555]
While reviewing #3553, I noticed that the RECAPDocuments created are not being linked to their corresponding EPQs.

We could modify `mark_pq_successful` to accept a list of `rd_ids` and assign them to the EPQ, considering that `recap_documents` is a many-to-many relation.

**Comment by mlissner** [comment]
Shoot! We should fix this, but I think it's better to keep the `mark_pq_successful` focused on that purpose, and maybe to have another function that is run first to link up the docs. Would that work better?

**Comment by albertisfu** [comment]
Oh yes, that sounds better. So, we can have `associate_related_instances` (or a similar name) first, which can be used in all the task uploads to link related instances, and then use `mark_pq_successful` exclusively for marking it as successful.

**Comment by mlissner** [comment]
Sounds good to me.

**Comment by albertisfu** [comment]
Great, I'll work on the fix!
