### ISSUE TITLE
Include child courts when searching parent courts

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#3586]
We need to update the way courts are filtered for now that we are loading `child_courts` on both the API and front end search.

Currently- if you want to pull back all the NY Supreme Court Opinions, you would need to query every court ID all 200 or so. 

Instead I propose automatically including any child courts for the API and search endpoints (etc)
```
selected_courts_string = get_selected_field_string(cd, "court_")
if len(selected_courts_string) > 0:
    courts = re.findall(r'"(.*?)"', selected_courts_string)
    courts += Court.objects.filter(parent_court__id__in=courts).values_list("id", flat=True)
    courts = [f'"{c}"' for c in courts]
    main_fq.append(f'court_exact:({" OR ".join(courts)})')
```

**Comment by mlissner** [comment]
OK, Bill and I chatted about this a bit, and he's right: It's pretty bad that our search engine makes it impossible to search child courts. A quick fix is to look for child courts whenever somebody does a court query and to include those child courts in the search engine's filtering. Eventually, we can do this better via the UI, but for now that's a simple and good fix.

@albertisfu if you can take care of this, that'd be great. I'll put it on your backlog for review.
