### ISSUE TITLE
Hit list for visualization backend

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#362]
Lots of features to build up. I'll be checking things off and adding them here as I go.

 - [x] Add new visualizations in last 10 days to homepage.
 - [x] Build up social network graph stuff (so it looks correct in Twitter previews and such)
 - [x] Add case_name_short to admin for Colin
 - [x] Develop the "in-beta" permissions:
     - [x] Add 'norobots' tags all over the place to keep Google at bay
     - [x] Hide the visualizations tab from the profile pages and other spots.
 - [x] Creation workflow
    - [x] Number of degrees is limited so people can't blow up the server
    - [x] Opinion selection typeahead and other options
        - [x] Ensure that we only get back the SCDB cases in the typeahead
        - [x] Add reporter citation and year to drop down (live demo day 1)
        - [x] Consider support for additional field searching (live demo day 1)
 - [x] Investigate depth first vs breadth first. It should be depth first, because that favors faster branch trimming.
 - [x] Reproduce and resolve `NetworkX Target Node not in Graph` error - _trim_branches()
 - [x] Performance optimizations:
    - [x] Make it so that things work properly while the user is waiting (the URL doesn't crash, the list of visualizations lists the item as in process, etc. (Add in progress field to DB). Investigate adding a sound.
 - [x] Fix profile page to do sane ordering, possibly pagination too -- how is it even ordered now?)
 - [x] Embed URL
    - [x] Remove ID
    - [x] Add something to the effect of "For case names, analysis &...see original"
    - [ ] Track the referrer in a new table so we can see where things are embedded.
    - [x] Make the button open in a new tab (regression)
 - [x] Draft mapper Homepage
    - [x] Sort out how to embed multiple maps in a page without using iframes.
 - [x] Map Gallery
 - [x] Deletion workflows
    - [x] Undeletion workflow (if bailed out on, the template needs to be updated b/c it currently directs people to their profile to undelete things).
    - [x] Deletion during user suicide (when they delete their entire account)
 - [x] Spaeth data import
    - Will do this after upgrade to new system. In the meantime the database migrations are in place.
 - [x] Automatic title generation
 - [x] View count support (ignoring bots)
 - [x] JSON validator for when users do crazy things?
    - [x] Needs to handle removal of nodes (Alpha1, @colinstarger)
 - [x] Markdown:
    - [x] Add link-pattern regex to the markdown processor so that other viz's can be referenced. I can't do this until we know what we're calling these, but once we know, I can make references like "Graph #22" automatically link to the correct place in the same way that Github just made that 22 link to bug 22!
    - [x] Create page/sidebar, etc explaining special markdown features like footnotes, tables, spoilers, and link patterns
    - [x] Make sure that embedded images don't have crazy borders.
    - [x] Update TOS, DMCA stuff, etc.
 - [x] Add the viz to the feature tour
 - [x] Add links to visualizations from the opinion pages
    - [x] Add these links to the sitemaps if possible. First approach did not work.
 - [x] Make the case table scroll if longer than X (Alpha1, @brianwc)
 - [x] Add the ID numbers in various places (probably to the title, the viz sidebar, the profile viz and the case page viz (Alpha1, @colinstarger)
 - [x] Make the viz taller (Alpha1, @colinstarger, @mlissner)
 - [x] Add copy viz and refresh viz functionality? (Alpha1, @everybody)

For @jraller, priority order:

 - [x] Cases with abstentions don't appear. For example, [this case has a 3-5 vote][2] and doesn't appear on graphs.
 - [x] Change axisType HTML label to X-Axis Spacing, and change drop downs to 'fixed' and 'proportional'. Remove height drop down.
 - [ ] Finish the genealogy view
    - [ ] Disable DOS drop down
    - [ ] And explain why disabled to user...somehow (FAQ, something else?)
 - [ ] Make it use case name short if available, falling back to case_name
 - [ ] Increase smallest circle size (on-site day one)
    - See line 340 sizeScale.range(5, 50)
 - [ ] Move circles near top layer, under labels, but above all line charts (so lines don't appear to go all the way to center of nodes) (@colinstarger, on-site day 2)
    - [ ] When labeling feature is updated, can labels move to top of nodes, with judge name below? Something to consider in later versions.
 - [x] Make the nodes clickable links (Alpha1, @colinstarger)
 - [x] Make most recent node a little bigger? (Alpha1, @darrenkumasawa)
 - [x] Use anchors to keep track of selected visualization and visualization state (see note below)
 - [x] Add categorical and chronological views (Alpha1, @colinstarger)
 - [x] Investigate making the case names visible at all times (Alpha1, @colinstarger), and make sure they're on the top layer (Alpha1, @mlissner)
    - [ ] Add a `text-shadow` to the labels to make them stand out against backgrounds  (Alpha2, @mlissner)
    - [ ] Tweak labels to work regardless of length (somehow) (Alpha2, @colinstarger)
 - [x] Make nodes open in new tabs when embedded, and when CTRL + clicked, if possible (Alpha2, @mlissner, @colinstarger)
 - [x] Remove y-axis numbering on random axis (Alpha2, @mlissner).
 - [ ] Add degree of dissent
    - [x] Update algo to match colin's (dissenting count * 0.25)
    - [x] Add visual bar thing
    - [ ] Eventually: Investigate histogram on/near right side y-axis
 - [x] Remove case number from case table (the first column) (Alpha2, @jraller)
 - [x] Make the legend dynamic according to DoS (Alpha1, @brianwc)
 - [x] Add dynamic case count to the tab header (Alpha2, @colinstarger)
 - [ ] Investigate making the lines curved with arrow heads (Alpha1, @colinstarger)
 - [x] Make case table sortable (Alpha1, @colinstarger)
 - [x] Tweak dates to be 0, 45, and then 90 degrees only if necessary (Alpha1, @darrenkumasawa)
 - [ ] Fix Y distribution to be adaptive again (this is very low priority under the assumption that the system can work adequately with hard-coded distribution attributes)
 - [x] Redraw chart on screen resize, if not too difficult.
    - [ ] Issue: Dates don't go horizontal when making the screen wider again (alph2, @mlissner)

For discussion/resolution (@mlissner, @cstarger):

- [ ] Drop down labels and values. (What is better wording for chart type? Can we simplify?)

Ideas:

 - [ ] markdown preview pane, like github or live preview, like Stackoverflow
 - [ ] Public user page where their visualizations and profile info is displayed
 - [ ] Add an API for chart generation or for the data generation

Spec for anchors
----------
At the end of the day, anchors need to save key value pairs and the JavaScript needs to load those values. I think the best way to do this is to just mimic GET parameters like so (this is rough):

    #type={spread|spaeth|gene}&dos={1,6}&xaxis={cat|time}

When a page with that anchor was loaded, it'd show a random Y distribution, two degrees of separation would be shown, and the X axis would be chronological. Note this should not affect the browser history even though it's tweaking the URL.

There's at least [one other person that's done this before][1], but I couldn't find very much other prior art. I think this should work well because it allows all of the viz's state to be shared/bookmarked with a link, and it isolates the front end settings from the backend, where they'd be ignored anyway.

[1]: http://stackoverflow.com/questions/23481979/function-to-convert-url-hash-parameters-into-object-key-value-pairs
[2]: http://courtlistener2.com:81/opinion/111258/allen-v-wright/

**Comment by mlissner** [comment]
Automatic title generation is done. We'll automatically select the shortest available case name and make a title like:

> X to Y (N degrees)

**Comment by jraller** [comment]
The long term solution for labels on the scatter plot should be revisited when this issue is closed: https://github.com/palantir/plottable/issues/2617

**Comment by mlissner** [comment]
Not sure I follow what problem palantir/pottable#2617 would resolve? Is there a hack tying the labels to the points presently?

**Comment by jraller** [comment]
To add case names to the scatter plots I can do it in a hackish way, but when that issue gets fixed I'll be able to do it in a way that will continue to be supported by the library and likely have many more features.

**Comment by mlissner** [comment]
:+1:

**Comment by jraller** [comment]
I found a solution for case name labels that is only slightly hackish, working on it now.

**Comment by mlissner** [comment]
So I coded up Degree of Dissent in a way that we could calculate server-side whenever needed, but I realized all too late that DoD should be recalculated whenever the degrees of separation are changed.

Here's the algorithm I wrote up (in Python), as a `property` of the viz object:

    @property
    def degree_of_dissent(self):
        """Calculate the average between all the cases included in the viz.

        The method is to calculate the average of 

            1 - (difference between votes / total votes)
        
        So in a 5-4 decision, that'd be:

            1 - ((5-4) / (5 + 4)) --> 1 - 1/9 --> 0.89

        And then you'd just average these values for every case that's displayed.
        """
        dods = []
        for cluster in self.clusters.all():
            majority = cluster.scdb_votes_majority
            minority = cluster.scdb_votes_minority
            dods.append(1 - float(
                abs(majority - minority) /
                sum([majority, minority])
            ))
        return sum(dods) / len(dods)

@colinstarger has another way he implements this (`num_dissents × 0.25`), but that method doesn't account for recusals, when you might only have eight or even seven votes. 

I put the following HTML into the page to capture the value:

    <div class="sidebar-section col-md-12 hidden-sm hidden-xs">
        <h4 class="caps gray"><span id="dod"></span> Degree of Dissent</h4>
    </div>

@jraller, can I hand this off to you to implement the algo above client-side then populate the HTML?

**Comment by jraller** [comment]
Degree of Dissent has been moved client side as:

		var dods = [];

		cases.forEach(function (c) {
			var majority = c.votes_majority,
				minority = c.votes_minority;

			if (majority !== -1 && minority !== -1) {
				dods.push(1 - (Math.abs(majority - minority) / (majority + minority)));
			}
		});

		return (d3.sum(dods) / dods.length) * 100;

**Comment by mlissner** [comment]
The count is now on the homepage if greater than 0, with the phrasing:

> New Supreme Court doctrinal networks published in the last ten days.

This required a new field in the DB that tracks original publication date, but now we have that too -- a good thing.

**Comment by mlissner** [comment]
Beta testing system is now in place. Unless somebody with admin privileges opts you in as a beta user, you don't see anything new. When we're ready, I'll tweak the code to disable the permission.

**Comment by mlissner** [comment]
I'm closing out this issue, finally, and moving things over to a Google spreadsheet. Will email with more details, but hopefully it'll help us get some prioritization so we can see what stays/goes/needs to be done, etc. I'm feeling a bit lost, and this should help, hopefully!
