### ISSUE TITLE
test `test_new_recap_email_alerts_integration` randomly failing

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#3664]
Some change, presumably the `async` one is causing this test to fail occasionally.

**Comment by mlissner** [comment]
Are you working on this already?

**Comment by mlissner** [comment]
@albertisfu, can you take a look at this? It seems this test is passing sometimes and failing others? https://github.com/freelawproject/courtlistener/actions/runs/7662090551/job/20882727119

**Comment by albertisfu** [comment]
This test `test_new_recap_email_alerts_integration` has failed again. It's failing on a different line, suggesting it might be a distinct issue from the `enqueue_docket_alert` that caused it to fail when sending the Docket Alert.

Now, it's related to an assertion failure after unsubscribing from the alert via `toggle_docket_alert_confirmation`, possibly indicating a problem related to the async client.

**Comment by albertisfu** [comment]
Closed by #3735
