### ISSUE TITLE
Merge RECAP opinions into our Case Law database

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3701]
This a medium size project we need to do to shore up our district court coverage. We have millions of district court opinions that we scraped from PACER, but they're not in the case law database. We should fix this. 

This ticket serves to ask questions. @flooie will be answering them and then working on this issue (or delegating it).

# Question 1: Models

We currently have models like this:

 - Dockets
    - Clusters
       - Opinions
    - Docket entries
       - RECAP Documents

How do we adapt this so that the RECAP documents are included in case law data? There is one major choice here: Do we adapt our models so that RECAP docs can be included directly in the case law data, or do we simply copy the recap docs into the case law data, making fresh dockets/clusters/opinions as needed?

# Question 2: Search

How does this affect search results if we have multiple clusters under a single docket? Would it create a lot of junk? Can we handle that? In new search (which isn't quite launched, I think), we have clusters and nested opinions on the result page, but we don't group dockets. Should we? Will this make the results junky? 

# Question 3: Docket page

On the docket page, we currently have weird sections at the top where we say something like, "Opinions outside the RECAP collection" and "Oral arguments outside the RECAP collection." 

What happens with these when we make our choice in question 1 to either copy the data or to somehow rejigger our models? 

# Question 4: Cluster and docket source fields?

Dockets and clusters have source fields. Can they adapt properly to the choice we make in question 1?

# Question 5: What's the norm in other data sources?

What does west do with district cases? Do they wind up in a book? Do they wind up in search results? What about Lexis? 

# Question 6: Circuit data?

Do we need to pull the circuit court data into the case law dataset, or can we leave it behind since we're scraping it anyway? Should we merge the dockets, perhaps so they're consistent?

**Comment by flooie** [comment]
Thanks @mlissner 

I've started researching this fuller and the second thing (not the first) that I discovered is that we essentially unified recap and opinions search accidentally two weeks ago.  

https://github.com/freelawproject/courtlistener/issues/3702

**Comment by mlissner** [comment]
This is getting done in #3790. Closing, but @flooie, please review the above and make sure we're not missing anything. Thank you!
