### ISSUE TITLE
test_api_logged_correctly randomly failing

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3749]
I noticed this test `test_api_logged_correctly` failed twice today.

Specifically, the assertion failed:
`self.assertAlmostEqual(int(self.r.get("api:Test.timing")), 10, delta=500)`
`AssertionError: 1431 != 10 within 500 delta (1421 difference)`

This indicates the test fails when the API request takes longer than expected. It has a threshold of 500 ms, but sometimes it exceeds 1000 ms. Wondering if we should increase the delta here or doing some kind of optimization.

**Comment by mlissner** [comment]
This test isn't to verify performance, it's to make sure the value is sane. Seems fine to me to allow it a larger range to work in.

**Comment by albertisfu** [comment]
got it, I've increased the delta in #3748
