### ISSUE TITLE
Use connection pooling in Redis (and maybe do async?)

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3762]
In https://github.com/freelawproject/courtlistener/issues/3741, we're having difficulty doing DNS look-ups. The reason appears to be that AWS only lets you use so much DNS before they cut you off, and we've reached some level of scale where we hit that threshold. Greeeeat. 

I already took one step towards fixing this by lengthening how long we connect to the DB, but we can do the same for Redis too. 

I really don't like redis-py's documentation around this. Most of their documentation is on this site:

 - https://redis-py.readthedocs.io/en/stable/index.html

And it has lots of information about connections, connectionpools, async connections, cluster connections, etc: 

 - https://redis-py.readthedocs.io/en/stable/connections.html

But somehow it doesn't mention this, which is over on the [pypi website](https://pypi.org/project/redis/):

> By default, redis-py uses a connection pool to manage connections. Each instance of a Redis class receives its own connection pool. You can however define your own [redis.ConnectionPool](https://redis.readthedocs.io/en/stable/connections.html#connection-pools).

So, OK, whenever you connect to Redis, you're creating a pool, but we never actually use the pool, and we just throw it away when we're done with our view or whatever. 

We can do better. [One way](https://stackoverflow.com/a/12973514/64911) is like this:

```python

POOL = redis.ConnectionPool(host='10.0.0.1', port=6379, db=0)

def do_stuff():
    my_server = redis.Redis(connection_pool=POOL)
    response = my_server.get(variable_name)
    return response
```

That'd be very easy as an upgrade to our existing code, but it also feels like we could do better by just establishing one redis interface, once, and then reusing that. Something like:

```python
r = redis.Redis(...)

def do_stuff():
    response = r.get(foo)
    ...
```

That should work because, remember, "by default redis-py uses a connection pool," and I guess it'd make sense for that connection to be established at module import, maybe in `cl.lib.redis`? 

I don't know. It's worth a bit more research and thinking than I've done so far.

## Async

While researching the above, I also noticed (and mentioned to @ttys0dev) that redis has an async connector as well. Maybe this is a good time to switch to that too.

----

So we should figure this out in a smart way. I haven't found what the best practice is, and I'm a bit scared of things like:

 - What happens if the redis server restarts — do we just have a mess of permanently broken connections until our pods restart??

But we should get more performance out of this and it should help with our DNS problem, so we should do it.

**Comment by mlissner** [comment]
Probably the place this will help the most is with celery, if we can trick it into using a connectionpool (maybe it is already?), but I guess see it using LOTs of connections if it was designed poorly.

**Comment by ERosendo** [comment]
Upon reviewing our codebase, I noticed the consistent use of the `make_redis_interface` helper for creating Redis client instances. Additionally, we use multiple Redis databases within the application.

I reviewed the redis-py's documentation and found the following suggestion: 

> If you use multiple Redis databases within the same application, you should create a separate client instance (and possibly a separate connection pool) for each database.

we can explore two potential approaches to implement pooling in our codebase

**1. Define Dedicated Pools:**

This approach minimizes code changes. We can keep the `make_redis_interface` helper function while creating dedicated pools for each Redis database. A selection mechanism will be implemented within the function to choose the appropriate pool based on the provided `db_name` and `decode_response` parameters. Here's a snippet of the potential code changes:

in `cl/settings/third_party/redis`

```py
from redis.connection import ConnectionPool
...
POOLS = {
    f"{name}-{decode}": ConnectionPool(
        host=REDIS_HOST,
        port=REDIS_PORT,
        db=db,
        decode_responses=decode,
    )
    for decode in [True, False]
    for name, db in REDIS_DATABASES.items()
}
```

in `cl/lib/redis_utils`:

```py
def make_redis_interface(
    db_name: str,
    decode_responses: bool = True,
) -> Redis:
    """Create a redis connection object

    :param db_name: The name of the database to use, as defined in our settings
    :param decode_responses: Whether to decode responses with utf-8. If you're
    putting binary data (like a picked object) into redis, don't try to decode
    it.
    :return Redis interface using django settings
    """
    return Redis(connection_pool=settings.POOLS[f"{db_name}-{decode_responses}"])
```

**2. Create a global object with all the clients**

In this approach, we will remove the `make_redis_interface` method and instead use a global object to store all Redis clients. However, this change will require updating all the files using the `make_redis_interface` method. Here's an example of what the update might look like:

in `cl/lib/redis_utils`:

```py
REDIS_CLIENTS = {
   f"{name}-{decode}": Redis(
        host=settings.REDIS_HOST,
        port=settings.REDIS_PORT,
        db=cast(int, settings.REDIS_DATABASES[db_name]), 
        decode_responses=decode_responses,
    )
    for decode in [True, False]
    for name, db in REDIS_DATABASES.items()
}
```

after implementing the global object, we need to remove the imports of the `make_redis_interface` method. This import is used in 27 files.

**Comment by mlissner** [comment]
I almost always prefer the better solution, which means I vote we get rid of `make_redis_interface`. :)
