### ISSUE TITLE
ncctapp records before 2022 have extra character `Â` on case name

### ISSUE THREAD

**Issue by grossir** [freelawproject/courtlistener#3797]
[Query](https://www.courtlistener.com/?q=court_id%3Ancctapp&type=o&order_by=dateFiled%20desc&stat_Precedential=on&stat_Non-Precedential=on&filed_before=12%2F31%2F2021) to find them. More current opinions don't have that problem. It [affects](https://www.courtlistener.com/api/rest/v3/clusters/4802830/) the short_case_name and the slug, so I don't know if it will be desirable to alter it

![image](https://github.com/freelawproject/courtlistener/assets/14970769/f64e43e1-048a-4cc5-bbd3-e4f672514fd2)

**Comment by mlissner** [comment]
It's OK to change slugs. Our URLs don't actually use them. Witness:

https://www.courtlistener.com/opinion/108713/roe-v-wade/

vs. 

https://www.courtlistener.com/opinion/108713/whatever/

Both work fine. :)

**Comment by mlissner** [comment]
@flooie, to you for prioritization.

**Comment by flooie** [comment]
Turns out there are a lot of these across a number of courts- but they are likely all from windows encoding issues in HTML.  

Thankfully this appears to have stopped in or around 2021.  So I think the most reasonable solution is to simply remove the bad encoding and move on with our days
