### ISSUE TITLE
UX: Add link to initial compaint to all RECAP search results

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3798]
Maybe it's just me, but as I'm doing legal research, I do a query for something and I get back a bunch of cases I know nothing about. Wouldn't it be nice if there was a link to the initial complaint for each of the cases right in the search results? 

This could be very easy from a technical side: Just add a link to:

https://cl.com/docket/{id}/1/{slug}/

From a UI perspective, we might want to try a few things. I'm not sure how to integrate this, but some sort of small button should do it.

**Comment by mlissner** [comment]
Before we build, it'd be great to have a little mock up, if you can, Alberto, but, again, no rush!

**Comment by albertisfu** [comment]
Ok, here some proposals so we can add the "Initial complaint" button to RECAP search results in the frontend:

Option 1:
![Screenshot 2024-08-13 at 2 33 37 p m](https://github.com/user-attachments/assets/77cb6d54-3444-4f38-bd12-cc1d9ca51da7)

Option 2:
![Screenshot 2024-08-13 at 2 25 40 p m](https://github.com/user-attachments/assets/8c2a69b6-bc2e-42a1-986b-f8ab852ec47a)

Option 3:
![Screenshot 2024-08-13 at 2 32 46 p m](https://github.com/user-attachments/assets/c3098571-3816-4f3b-b14f-75abea8cc6f2)

### Regarding technical details I got some questions:

- You mentioned we can just link to `https://cl.com/docket/{id}/1/{slug}/`:
    - What if we don't have entry 1? That link will raise a 404. 
    - What if we have entry 1 but don't have the document yet? Is it still okay to add the link?
  - To handle these cases, I think we'd need to perform an additional query to the database for all the cases on the page, so we can determine when to show the button or not.
- An additional issue I see is regarding appellate cases. Some courts don't use numbers, and the link to an entry looks like this:
`https://www.courtlistener.com/docket/6173210/00504194048/kimberly-meador-v-apple-incorporated/`
Is there a reliable way to identify the initial complaint in these cases?

**Comment by mlissner** [comment]
Option 1 looks great, thanks. 

If we don't have the docket entry, let's just not show anything. If we don't have the PDF, let's put a "Buy Initial Complaint" button instead. (Be careful with your queries not to pull the document text.)

For appellate cases that don't use docket entry numbers, we don't have any tricks, so let's just not show the button. Do we have an easy way to know which appellate courts use regular numbers and which don't?
