### ISSUE TITLE
SCOTUS opinion exists on API but does not show on search

### ISSUE THREAD

**Issue by grossir** [freelawproject/courtlistener#3804]
This issue comes from a question via email about a missing opinion from SCOTUS, "Joseph Kennedy v. Bremerton School District".

Indeed, it does not surface when searched via the interface, filtering by [docket number](https://www.courtlistener.com/?q=court_id%3Ascotus&type=o&order_by=dateFiled%20desc&stat_Precedential=on&stat_Relating-to%20orders=on&docket_number=21-418), nor by case name.

However, it exists on the DB / API
[Opinion](https://www.courtlistener.com/api/rest/v3/opinions/6495362/)
[Opinion Cluster](https://www.courtlistener.com/api/rest/v3/clusters/6619004/)
[Docket](https://www.courtlistener.com/api/rest/v3/dockets/63549791/)

It is even duplicated: [2nd OpinionCluster](https://www.courtlistener.com/api/rest/v3/clusters/6623460/) (Check #3803 about the duplication due to versioning)

The Opinion object seems corrupted, tough, because it has nothing inside the `plain_text` attribute, where the PDF text should be. The links to the document, both from CL backup and court backup work.

----
Related to this, I double checked all records available on the `scotus_slip` juriscraper source, and found that no opinion was missing. The only one that does not surface on the search is the one above.

I downloaded the data available in the source, and compared it against the development database, via antijoins against `download_url`, `case_name` and `docket_number`. In the end, I was left with 14 records which I had to manually check against CL, none were missing

Downloading everything
```
import requests
from lxml import html
import csv

cases = []
url = "https://www.supremecourt.gov/opinions/slipopinion/{}"

for i in range(17, 24):
    r = requests.get(url.format(i))
    tree = html.fromstring(r.text)
    
    for row in tree.xpath("//tr"):
        cells = row.xpath(".//td")
        if len(cells) != 6:
            continue
        
        a, date, docket, link, justice, citation = row.xpath(".//td")
        
        if not link.text_content():
            continue
        
        cases.append(
            {
                "citation": citation.text_content(),
                "date": date.text_content(),
                "url": link.xpath(".//a/@href")[0],
                "name": link.text_content(),
                "docket": docket.text_content(),
                "judge": justice.text_content(),
                "year": i,
            }
        )

with open("/tmp/scotus_scraped.csv", "w") as f:
    csv_file = csv.DictWriter(f, fieldnames=list(cases[0].keys()))
    csv_file.writeheader()
    csv_file.writerows(cases)
```

**Comment by flooie** [comment]
Any thoughts on what causes the failing extraction.  Corrupt PDFs?

**Comment by mlissner** [comment]
If I had to guess, I think the extraction failure is probably our microservice being unavailable. I know that happens from time to time. 

It would be smart to have some sort of sweeper that retries things, but first we need to get our ops person to figure out and fix the random failures.

**Comment by mlissner** [comment]
Let's do a little evaluation here and see if we need to do anything for v4 of the API.

**Comment by albertisfu** [comment]
I checked this one to confirm if we do need to do something in the V4 or V3 (ES) of the Search API.

The search mentioned by @grossir does now return results either in the ES or the Solr version:

**ES (Only staff logged users)**
https://www.courtlistener.com/?q=court_id%3Ascotus&type=o&order_by=dateFiled%20desc&stat_Published=on&stat_Relating-to=on&docket_number=21-418

![Screenshot 2024-06-05 at 5 07 25 p m](https://github.com/freelawproject/courtlistener/assets/486004/5ce3ac7c-8a33-4a64-a4c6-4e8f844c1520)


**Solr (Public):**
https://www.courtlistener.com/?q=court_id%3Ascotus&type=o&order_by=dateFiled%20desc&stat_Precedential=on&stat_Relating-to%20orders=on&docket_number=21-418

![Screenshot 2024-06-05 at 5 07 37 p m](https://github.com/freelawproject/courtlistener/assets/486004/6a533de3-00ee-47af-aa13-09fed8055a32)


In the V4 Opinions Search API as well, the query returns the same results:
https://www.courtlistener.com/api/rest/v4/search/?q=court_id%3Ascotus&type=o&order_by=dateFiled%20desc&stat_Published=on&stat_Relating-to=on&docket_number=21-418

Are these the expected results?

**Comment by mlissner** [comment]
Thanks. Seems fine to me, so I'll close, but @grossir, feel free to re-open if I'm missing something. :)
