### ISSUE TITLE
Use multi-value fields in Solr for citations

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#381]
Currently the `citation` field in Solr is one big string that concats all the different citations together. It works, more or less, but kind of sucks. 

@joshdata points out that we can use a multi-value field for this and that doing so would fix the issue where somebody searches for `410 U.S. 113` and gets back the item matching:

> 410 U.S. 257, 93 S. Ct. 880, 35 L. Ed. 2d 247, 1973 U.S. LEXIS 113

Because of the LEXIS 113 part. That sucks.

**Comment by mlissner** [comment]
Looks like there's [a very likely fix for this][1] (look for the values within 100 fields of each other), and that switching to multivalue fields was indeed a good decision. Still, this can't be a priority right now and will have to wait until the new version goes live.

cc: @joshdata

[1]: http://stackoverflow.com/a/33858649/64911

**Comment by mlissner** [comment]
@joshdata, this is now fixed properly. Internally we'll convert any query to the citation field so that it only searches against one element of the `citation` array at a time.

**Comment by mlissner** [comment]
This query now does what it should: https://www.courtlistener.com/?q=&type=o&stat_Precedential=on&citation=410+U.S.+113&order_by=score+desc

**Comment by JoshData** [comment]
You rock.
