### ISSUE TITLE
RECAP not uploading for bankruptcy courts

### ISSUE THREAD

**Issue by mikeweinberg** [freelawproject/courtlistener#3831]
I purchased a docket for a case in the United States Bankruptcy Court, W.D. North Carolina. This docket successfully uploaded to Courtlistener, using RECAP version 2.5.0 and Chrome Version 121.0.6167.185 (Official Build) (64-bit)

I then clicked "Buy on PACER, which took me to a "Multiple Documents" page on [US Courts](https://ecf.ncwb.uscourts.gov/) to display the main document plus exhibits for a docket entry.

I purchased the main document. It was not uploaded.

I also noticed that the names of the "Multiple Documents" were not uploaded to Courtlistener to update its docket. RECAP is doing something though, according to the debugger:
```
RECAP: Attaching links to all eligible documents (3 found)
RECAP: Item saved in storage at tabId: 1518719378
RECAP: Got results from API. Running callback on API results to attach links and icons where appropriate.
```

I was able to replicate this on another case in the same court (at least for the "Multiple Documents" pages):

[Case](https://www.courtlistener.com/docket/60052351/elizabeth-nmn-walker/) --> "Buy on PACER" for docket entry 6 -->[PACER Link](https://ecf.ncwb.uscourts.gov/doc1/134014109486?caseid=207621)

And I was able to replicate the problem in a [different bankruptcy court](https://www.courtlistener.com/docket/6848980/lent-christopher-carr-ii-and-deltarina-v-carr/):

However, all was fine on [this docket](https://www.courtlistener.com/docket/4792802/canada-v-american-airlines-inc-pilot-retirement-benefit-program/), which is not a bankruptcy court.

**Update:** It did work on [this](https://www.courtlistener.com/docket/6579725/h-tim-hoffman-adversary-proceeding/) Bankruptcy court case N.D. California and a [DC case](https://www.courtlistener.com/docket/7150060/william-haymore-brammer-jr/) but the problem still manifests in North Carolina.

I used a [search](https://www.courtlistener.com/?type=r&q=&type=r&order_by=score%20desc&description=Attachments%20AND%20exhibit) for document descriptions that contain the words attachments and exhibit.

**Update 2:** Now I [found one](https://www.courtlistener.com/docket/8447291/norris-gene-wright-and-sherry-lynn-wright/) in the Western District of NC where it did work correctly.

**Comment by mlissner** [comment]
Can you please take a look here, @ERosendo?

**Comment by ERosendo** [comment]
@mlissner Sure!

**Comment by mlissner** [comment]
Looks like this didn't make it onto a backlog properly, but I've re-prioritized it for review now.

**Comment by mikeweinberg** [comment]
I think this problem either went away or was a lot narrower in scope than I thought. The docket that I had trouble with seems to be working now. Also the documents that I purchased successfully uploaded.

So I think you can close this.

**Comment by mlissner** [comment]
Great! We've made a lot of little fixes to recap lately, so it's likely one of those did the trick.
