### ISSUE TITLE
Tweak es_signal_processor to avoid indexing Dockets that don't belong to the RECAP collection.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3875]
This is a follow-up to #3702. We need to tweak the signals to avoid the initial indexing of Dockets where their sources are not part of RECAP.

**Comment by mlissner** [comment]
Want to do a separate issue to remove existing items or just include it here?

**Comment by mlissner** [comment]
Oops, I see you want to do that as part of #3702. Great.
