### ISSUE TITLE
Do something with v3 of the search API — delete it?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3894]
Once v4 of the search API is launched in #3874, we need to do something to get rid of v3:

 - Track users and help them move to v4
 - If that fails, make v3 use Elastic as its backend
 - Disable v3

My overall goal here is to get rid of Solr as quickly as possible. It's expensive.

**Comment by mlissner** [comment]
@s-taube, I just found this old issue about v3->v4 migration. We can probably close it, but I wanted to send it your way in case anything here grabbed you.

**Comment by s-taube** [comment]
@mlissner thanks! I got what I need, feel free to close.
