### ISSUE TITLE
Issue updating the RECAPDocument absolute_url when the docket slug changes.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#3921]
In #3911 I found that the Opinion `absolute_url` was not being correctly updated in Elasticsearch (ES) by signals when the `OpinionCluster` `slug` changed. The solution was straightforward, as the `absolute_url` in Opinions is based solely on `OpinionCluster` fields.

I encountered a similar issue with updating the `absolute_url` for RECAPDocuments through signals. This does not affect search results because the `absolute_url` in a RECAPDocument is composed of the `"docket_id"` (which does not change), `"doc_num"` (which is properly updated), and the `"docket_slug"` (which is not being updated but is not required for looking up the document in the database, so the document can still be accessed correctly).
However, seeing the slug in `absolute_url` differ from the `docket_slug` in the API, especially as we work on the V4 API, can be confusing for users.

Attempting to fix this issue, I found that the solution is not as straightforward since the `absolute_url` in a RECAPDocument depends on both docket and document fields. Currently, to update `Docket` values in `RECAPDocuments`, we use the update_by_query method, since the values that change in the docket are the same across all their RECAPDocuments. However, in this case, we cannot use that approach because the `absolute_url` varies for each RECAPDocument due to the document number.

- One alternative to `update_by_query` is to update each RECAPDocument in ES independently by making an update request for each document belonging to the docket, which doesn't seem efficient.

- Another alternative is to stop using the `absolute_url` in the RECAPDocument mapping and instead index the `docket_slug` in RECAPDocuments. This allows us to have all the components of the `absolute_url` indexed in the document independently: `docket_id`, `document_number`, and `docket_slug`, which we can use to form the RECAPDocument absolute URL at rendering time. Then, in the API, we can create the `absolute_url` based on these three fields. This way, we can update the fields independently without having to modify the update signals. This alternative will require tweaking the RECAPDocument mapping in ES and a re index, which the timing is good since the sweep indexer is just starting with RECAPDocuments.

Let me know what do you think.

**Comment by mlissner** [comment]
Hm, I have to admit I sort of think we shouldn't bother with this. Things are working OK, slugs are rarely updated in practice, and it's basically working with the one issue being that they might be a bit different in the API vs reality. Your second solution is definitely the better one, but I don't see a need to do this now. 

Feels like a maybe someday kind of bug to me.
