### ISSUE TITLE
Use Ada to redirect users upon login

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#3933]
A while back, I removed redirect-on-login functionality from CourtListener because it was exposing a vulnerability in Python. I reported the Python vulnerability, and it was fixed:

https://bugs.python.org/issue43882

But it was kind of a mess, honestly. The volunteer that fixed it didn't check if the WHATWG test suite passed properly, and just focused on the small vuln that I reported. I'm pretty sure `urlparse` is still parsing things incorrectly and probably still vulnerable, so I didn't reinstate our redirect-on-login functionality even once Python was "fixed."

Now, when people login, they just go to the homepage, and bots.law inherited this functionality. Lame.

There is, however, hope. A new library called Ada actually passes the WHATWG test suite, is fast, has Python bindings, and seems really great: 

https://github.com/ada-url/ada?tab=readme-ov-file

Maybe we should use it and make it so redirect-on-login works again. 

But before we do that, I wanted to see if Django would integrate Ada directly, so I opened an discussion about that here:

https://groups.google.com/g/django-developers/c/Zp9mKpBn4u8

If we get a :+1: from them, we should just add it to Django, wait for that, and then fix our redirect system.

If it gets a :-1:, we should just use Ada ourselves to fix our redirect system.

**Comment by anonrig** [comment]
Hi @mlissner, Ada author here. Is there anything I can help with this?

**Comment by mlissner** [comment]
Hey @anonrig, thanks for offering! It sounds like getting Django to do this themselves isn't going to happen unless somebody demonstrates that the WHATHG test suite is still vulnerable in Python, and I don't think I'll have time to do that. 

So, I think what that means is we'd like to use Ada to do our redirects in CourtListener when people log in. 

I don't imagine you're familiar enough with Django (and interested enough) to take a stab at that, are you? 

I actually suspect your time would be better spent convincing Django devs they should worry about this more...

**Comment by anonrig** [comment]
@mlissner Happy to do my part. Can you reach me from any platform, so we can talk about this in detail?

**Comment by mlissner** [comment]
Related to this, I just got a SemGrep error: https://github.com/freelawproject/courtlistener/pull/4114#discussion_r1640003209

It says:

> Detected a unquoted template variable as an attribute. If unquoted, a malicious actor could inject custom JavaScript handlers. To fix this, add quotes around the template expression, like this: "{{ expr }}".

And the line it's highlighting is:

```
<a href="{% url "sign-in" %}?next={{ request.path }}"
```

I think it's right, that's not great. 

I'm bumping the priority of this issue and when we fix it, we should fix this as well.

**Comment by brianwc** [comment]
Would this fix the fact that I land on a RECAP docket. Notice that I'm not signed in. Click log in. Sign in... and then find myself on the homepage rather than back on the RECAP docket that I WANT to be on? I came here to file a bug on this, but perhaps this issue already covers my gripe.

**Comment by mlissner** [comment]
Yes, and it's high on Eduardo's list. It's a major annoyance (more for those that regularly delete cookies), and I yanked the functionality after realizing Python had a vulnerability relating to it. 

Python fixed the vuln I reported, but I don't trust it. Ada is trustworthy though, so now that it exists, we're back in business.

**Comment by mlissner** [comment]
Brian, your log-ins will now redirect. Thank you for your many years of patience!
