### ISSUE TITLE
All PA cases listed as precedential 

### ISSUE THREAD

**Issue by Acgreen56** [freelawproject/courtlistener#3956]
Even though the text of the opinions State that they are not precedential all cases currently post as Precedential.

**Comment by mlissner** [comment]
Thanks for the report. @flooie, can you please take a look when you get a moment and maybe we can fix the data and our scraper?

**Comment by flooie** [comment]
this is odd - 

I re-ran the scraper for a random case that was incorrectly labeled 

https://www.courtlistener.com/opinion/9824459/com-v-brice-w/?type=o&type=o&q=court_id%3Apasuperct&order_by=score+desc

and found that our scrapers correctly identify this as non-precedential or unpublished. 

```
Adding new item:
    case_dates: "2024-06-25"
    case_names: "Com. v. Brice, W."
    download_urls: "https://www.pacourts.us/assets/opinions/Superior/out/J-A01015-24m - 105981221271329306.pdf"
    precedential_statuses: "Unpublished"
    blocked_statuses: "False"
    date_filed_is_approximate: "False"
    docket_numbers: "2721 EDA 2022"
    judges: "Lazarus"
    case_name_shorts: "Com."
    per_curiam: "False"
```

setting aside the issue that the case name short is unfortunate, I dont see any changes between now and June when this was scraped that would have caused this to be any different.  

I think teh answer is to change them on the server though which should be easy enough as `NON-PRECEDENTIAL DECISION - SEE SUPERIOR COURT O.P. 65.37` is listed at the top of the opinion.

**Comment by grossir** [comment]
The fix was [merged](https://github.com/freelawproject/juriscraper/pull/968) on August and that opinion was [scraped](https://www.courtlistener.com/api/rest/v4/clusters/9824459/) in late June, that's why the status is wrong. 

But you are right the fix should be easy enough, but we do need to check if the headers for non precedential opinions vary between `pa`, `pasuperct` and `pacommwct`

**Comment by flooie** [comment]
yes - PaSUPER Ct should be easy as it says this is NON precedential at the top.  Ill check the other two courts now

**Comment by flooie** [comment]
this has been fixed on the server
