### ISSUE TITLE
The make_citation_data method in cl_make_bulk_data.py most likely looks for an old nonexistent table

### ISSUE THREAD

**Issue by voutilad** [freelawproject/courtlistener#396]
In working through debugging some test issues in the `api` module, I found that the `cl.api.cl_make_bulk_data.Command.make_citation_data` method runs some psql via the OS and tries to dump out data in the "Document_opinions_cited" table.

```python
os.system(
            '''psql -c "COPY \\"Document_opinions_cited\\" (from_document, to_document) to stdout DELIMITER ',' CSV HEADER" -d courtlistener --username django | gzip > /tmp/bulk/citation/all.csv.gz'''
        )
```

Looking at the schema while using branch `opinion-split`, I don't see that table, but I do see the potentially newly correct table: `search_opinionscited`. 

Any ideas what the correct table should be?

**Comment by mlissner** [comment]
That'd be the one, yep. The API (and subsequent bulk data) are the last areas of code (god willing) that are getting upgraded to the new schema.

**Comment by mlissner** [comment]
@voutilad, I'm going to close this one. Seems fixed to me.
