### ISSUE TITLE
Implement Upload Portal for Missouri & Mississippi Court Opinions

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#3996]
## Description:

Currently, our system cannot automatically collect legal opinions from Missouri and Mississippi Super Courts, including their appellate courts.

## Solution:

@mlissner and I discussed developing a secure upload portal to allow authorized volunteers to submit these opinions manually.

#### Features:

_Comprehensive Metadata Capture_: The portal should capture all relevant metadata for each opinion, potentially exceeding the data fields required for Tennessee and Maine.
_Streamlined Uploads_: Consider implementing a single upload portal that accommodates opinions from all six courts (two in Mississippi and four in Missouri) to minimize user burden (or 1 per state). This could involve:

1. A selection dropdown to specify the target court for each upload.
2. Dynamically adjusting the metadata fields based on the selected court.

@quevon24 Let's discuss the optimal design for the upload portal to ensure a user-friendly experience for volunteers.  I'm not convinced we should merge courts together or not.  Perhaps @mlissner can weigh in again on it.  

## Next Steps:

1. Discuss and finalize the upload portal design.
2. Develop and implement the upload portal.
3. Test and refine the portal functionality.
4. Train volunteers on using the new upload portal.
5. Update the documentation

**Comment by quevon24** [comment]
I think the first thing we need to do is define what fields are going to be required for each court, this will allow us to see if we only need to add a few more fields to CourtUploadForm and restrict what fields are seen based on the court_id.

Regarding how to upload the opinions, the page could be similar to tennworkcompcl page where you click on a court button and it takes you to an independent page to upload the file using a static page where you will only see the specific fields.

If you think about this further into the future, we should probably divide the forms by state or something similar. Although this would complicate other things.

**Comment by mlissner** [comment]
Just to avoid diffuse responsibility, I'd like to duck out of this one and let you guys come up with a plan/design that you like. Doesn't have to be perfect on the first go — just needs to be functional for a motivated engineer or volunteer. Thank you both!
