### ISSUE TITLE
Citation Lookup Failure

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4053]
I'm not sure what's going on here. The exception is an `InvalidError`, which is one I'm not familiar with. (I hope it's not an exception we created, because it's horribly named!).

The POST that somebody did to the citation lookup tool looks about as simple as I can imagine, so it seems worth looking into, to see what's up with it.

Here's the report from Sentry:

---

## Suspect Issues
This pull request was deployed and Sentry observed the following issues:

- ‼️ **InvalidError: error code -1** `/api/rest/{version}/citation-lookup/` [View Issue](https://freelawproject.sentry.io/issues/5357707894/?referrer=github-pr-bot)

_Originally posted by @sentry-io[bot] in https://github.com/freelawproject/courtlistener/issues/4025#issuecomment-2113959114_

**Comment by ERosendo** [comment]
It's a [hyperscan exception](https://github.com/darvid/python-hyperscan/blob/0103e2a3c4f17eb19b1164b871b31b1d5699f567/src/hyperscan/_ext.pyi#L127-L128). Based on the Sentry report, the exception appears to have been triggered during the hyperscan database loading process.

**Comment by mlissner** [comment]
Eww. We should offer to upgrade their exception for them so it's an "DatabaseNotLoadedException" or something.

In the meantime, do you know what the fix is?

**Comment by ERosendo** [comment]
> do you know what the fix is?

I don't have the answer right now 😅 , but I'll do some research and find a fix 😄
