### ISSUE TITLE
Case with bad opinion from Harvard

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4076]
A user reported this case is missing the beginning and end as compared to Google: 

> I encountered this case: https://www.courtlistener.com/opinion/6658574/myers-v-howton/. The text is missing several paragraphs at the beginning and the end. https://scholar.google.com/scholar_case?case=2858089755061678613&q=Myers+v.+Howton,+439+P.3d+472&hl=en&as_sdt=4,38

I found that the source document in Harvard is where the problem began: 

https://cite.case.law/p3d/439/472/

We should at least fix this one case, and if there's an underlying root cause, we should dig into that too.

**Comment by flooie** [comment]
I fixed this particular case.  It was caused like you diagnosed by bad data from CAP.  

I looked to see why and found that it was part of a bulk fix for bad opinions in 2023.  But the opinion was originally ingested in 2022.  Locally I ran the import which used our very nice and enhanced xml.  I dont know if we did an import before we realized things were broken and fixed everything and continued on.  Fortunately I havent come across any others like this but will keep an eye out in the future.
