### ISSUE TITLE
Missing District Opinions from RECAP

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#4095]
@mlissner 

I checked about nine months of reports for the `MAD` court - to see if the missing opinion was an anomaly. 

# `scrape_pacer_free_opinions` Command

| Date Range         | Missing/Total | Percentage Missing |
|--------------------|---------------|--------------------|
| 06/01/23 -> 07/01/23 |  9 / 115     | 7.83%              |
| 07/01/23 -> 08/01/23 |  8 / 111     | 7.21%              |
| 08/01/23 -> 09/01/23 | 11 / 95      | 11.58%             |
| 09/01/23 -> 10/01/23 | 11 / 142     | 7.75%              |
| 10/01/23 -> 11/01/23 | 28 / 136     | 20.59%             |
| 11/01/23 -> 12/01/23 | 12 / 110     | 10.91%             |
| 12/01/23 -> 01/01/24 |  8 / 97      | 8.25%              |
| 01/01/24 -> 02/01/24 | 15 / 124     | 12.10%             |
| 02/01/24 -> 03/01/24 | 17 / 119     | 14.29%             |
| **Total**           | **119 / 1049**| **11.34%**         |

A significant number of opinions that appear in the `scrape_pacer_free_opinions` command for at least `mad` appear to not be ingested into the RECAP db.  

A good number of these are civil cases - I would say the majority- and they often are cases that come from transferred cases but not exclusively.  A fuller examination will need to be completed.

**Comment by flooie** [comment]
we can certainly test it out for the last year in MAD and see if it catches everything.

**Comment by quevon24** [comment]
I already checked this and we already have all the opinions, in fact we have some extra opinions

| Date Range         | Total | New total |
|--------------------|---------------|--------------------|
| 12/01/23 -> 01/01/24 |  97      | 98              |
| 02/01/24 -> 03/01/24 | 119     | 121             |

The sweep should have collected everything until 2024-08-05

It is now just a matter of enabling cronjobs to perform monthly and weekly sweeps to avoid losing documents in case an error has occurred or new opinions have been marked as free opinions (I was able to identify that up to three days later they could have been marked as free opinions)

In case a gap is identified, the command can now be executed in the indicated date period and specific court.

**Comment by mlissner** [comment]
Fantastic!
