### ISSUE TITLE
Add admin-visible notice to various pages showing if they are blocked from search engines

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#412]
Most important are the case pages, but docket pages and audio pages could have it too.

**Comment by voutilad** [comment]
Does this exist in any form yet or is this a net-new user experience?

**Comment by mlissner** [comment]
Totally new. I've used a lock icon in other places (like the stats on the homepage) to indicate something that only admins can see, but otherwise, should be quick and easy one.

**Comment by voutilad** [comment]
Cool. If I have time over the weekend I'll assign myself and take a cut.

**Comment by voutilad** [comment]
I have a first cut. Here are the basic examples for an Admin user. (Tests verify non-admin don't see these.)

Obviously open to suggestions on UI styling/wording.

![docket - blocked](https://cloud.githubusercontent.com/assets/9891346/12219852/77caa6d8-b722-11e5-9ba1-e82b8e286bed.png)
![opinion - blocked](https://cloud.githubusercontent.com/assets/9891346/12219854/864fa06e-b722-11e5-928b-5f6a8aae607f.png)
![opinion - not blocked](https://cloud.githubusercontent.com/assets/9891346/12219853/864f47b8-b722-11e5-9189-9b9d37751af7.png)

**Comment by mlissner** [comment]
Looks good to me. Only change I'd suggest is to do nothing on pages that
aren't blocked.

**Comment by mlissner** [comment]
In dev, will be deployed fairly soon.
