### ISSUE TITLE
Case cites itself

### ISSUE THREAD

**Issue by JoshData** [freelawproject/courtlistener#417]
This case cites itself in "cited by":

https://www.courtlistener.com/opinion/784253/johann-breyer-v-john-ashcroft-us-immigration-and-n/

**Comment by mlissner** [comment]
Looks like it's valid both in opinion-split branch and master. Will want to double check it again after we've re-run the citator in a week or two.

**Comment by mlissner** [comment]
There was a check for this in the code, but it sucked. I've put a better one in its place and will be eliminating all self-citations shortly. (Well, in about two weeks, when the citator finishes running another complete pass.)

**Comment by mlissner** [comment]
I take it back. I was able to do this manually. All self-citations are gone and should not be reappearing.

**Comment by mlissner** [comment]
Validated. I just processed about 1M items with the new code and didn't get a single additional self-citation. Yay!

**Comment by JoshData** [comment]
Nice.
