### ISSUE TITLE
New Opinion Type (Admin?)

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#4198]
@mlissner @grossir 

I think we may need to expand our opinion type again. 

The Supreme Court of Arkansas publishes in their official reporter with citations things like this

- [IN RE AMENDED ADMINISTRATIVE PLAN FOR THE THIRD JUDICIAL CIRCUIT](https://opinions.arcourts.gov/ark/supremecourt/en/item/522891/index.do)
- [IN RE AMENDMENTS TO THE
ARKANSAS RULES FOR MINIMUM
CONTINUING LEGAL EDUCATION:
RULES 2(C), 4, AND 5(D)](https://opinions.arcourts.gov/ark/supremecourt/en/522894/1/document.do)

At first blush, I suggested to @grossir that we wouldnt want to collect these, but he correctly pointed out that they have official citations.  I did a check and they do get incorporated as Legal Opinions in the larger legal opinion databases.  That being said, these are not traditional legal opinions and I think call for a new type of Opinion Type.

Currently these are our opinion types (see below), but these type of documents do not seem to fall into these categories.  I think instead we should create a new type, perhaps (`ADMIN, Administrative Opinions)`, but I wanted to get any feedback around this.

```    
OPINION_TYPES = (
        (COMBINED, "Combined Opinion"),
        (UNANIMOUS, "Unanimous Opinion"),
        (LEAD, "Lead Opinion"),
        (PLURALITY, "Plurality Opinion"),
        (CONCURRENCE, "Concurrence Opinion"),
        (CONCUR_IN_PART, "In Part Opinion"),
        (DISSENT, "Dissent"),
        (ADDENDUM, "Addendum"),
        (REMITTUR, "Remittitur"),
        (REHEARING, "Rehearing"),
        (ON_THE_MERITS, "On the Merits"),
        (ON_MOTION_TO_STRIKE, "On Motion to Strike Cost Bill"),
        (TRIAL_COURT, "Trial Court Document"),
    )
```

**Comment by mlissner** [comment]
Closing this one, so conversation can happen in https://github.com/freelawproject/juriscraper/issues/1107
