### ISSUE TITLE
Make get_query_citation work with ES if the ES Opinions flag is enabled.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#4211]
Currently, `get_query_citation` continues working with Solr. We should make it use `es_search_db_for_full_citation` instead of `search_db_for_fullcitation` when the ES Opinions waffle flag is enabled.

**Comment by mlissner** [comment]
Hm, I thought this link would work now, but it doesn't? https://www.courtlistener.com/?q=just%20testing%20262%20F.3d%20590&type=o&order_by=score%20desc&stat_Published=on

**Comment by albertisfu** [comment]
I debugged the issue here:

The problem is that the query: `just testing 262 F.3d 590` matched two different Opinions with the same citation `262 F.3d 590`, as seen here:

https://www.courtlistener.com/?q=&type=o&order_by=score%20desc&stat_Published=on&citation=262%20F.3d%20590

The logic within `es_search_db_for_full_citation`, which works the same as in the Solr version, is that a matched case is returned only if it is possible to find a single match. In this case, there are two different opinions, so no alert is shown.

However, I noticed that this can also be an issue if there is only one cluster with the citation but it contains two or more sibling opinions, such as a `Lead Opinion` and a `Dissent`. The citation lookup will also match two opinions even though they belong to the same cluster, and no alert will be displayed. I wonder if this is the correct behavior because citations are added at the cluster level instead of the opinion level. But this is how it also worked in Solr, where opinions were indexed instead of clusters. 
Additionally, the `es_search_db_for_full_citation` method contains logic to avoid including the `citing_opinion` if it is included in the `FullCaseCitation` object. For instance:

`must_not.append(Q("match", id=full_citation.citing_opinion.pk))`

where `citing_opinion` is an Opinion instance. This makes me think there is a reason for considering opinions instead of clusters when looking up citations?

**Comment by mlissner** [comment]
I'm not sure I understand this part:

> Additionally, the es_search_db_for_full_citation method contains logic to avoid including the citing_opinion if it is included in the FullCaseCitation object. For instance:

Can you give me an example? 

> However, I noticed that this can also be an issue if there is only one cluster with the citation but it contains two or more sibling opinions,

This makes sense. I had trouble looking up other cases where that's the problem. I think the logic here should be tweaked to return the suggested case if only one *cluster* is returned. Otherwise, this fails on the most important cases (those that have more than one judge and more than one opinion).

**Comment by albertisfu** [comment]
> Can you give me an example?

Sure I think this test is a good example: [test_case_name_and_reverse_match_query](https://github.com/freelawproject/courtlistener/blob/main/cl/citations/tests.py#L506C9-L506C47)

I reviewed this example in detail. Here, the citation resolution is used to create `OpinionCited` instances used in `store_opinion_citations_and_update_parentheticals`. `OpinionCited` receives two `Opinion` instances: `citing_opinion` and `cited_opinion`, so it's correct that `es_search_db_for_full_citation` returns an `Opinion` instead of an `OpinionCluster`.
In this use case, matching more than one citation from the same cluster is not an issue because when a `citing_opinion` is provided, as it is in `store_opinion_citations_and_update_parentheticals`, the `es_search_db_for_full_citation` method can perform additional lookups to try to match a single citation. In this case, the method called `es_reverse_match` allows matching a single citation. It iterates over the multiple opinions found previously (which can belong to different or the same cluster) and performs an additional query by looking for each matched opinion's `caseName` in the citing_opinion's `plain_text` to confirm it's a match. The first Opinion that matches is returned.

Here, my only question is about matching the first result when multiple Opinions found belong to the same cluster. In this case, both Opinions would match (both have the same caseName), but the one returned is the first one in the results, which in this case will be the oldest Opinion created since it's using `id` for sorting. Is this method of selecting the oldest matching Opinion correct? Or would there be a better approach to select the matching opinion when more than two Opinions in the same cluster match during citation resolution? Maybe prioritizing the Opinion `type`?

> This makes sense. I had trouble looking up other cases where that's the problem. I think the logic here should be tweaked to return the suggested case if only one cluster is returned. Otherwise, this fails on the most important cases (those that have more than one judge and more than one opinion).

Got it. Yes, this seems better. When using the method to match Opinion to provide the helper alert in the search results, we could return an `OpinionCluster` instead, or just select one `Opinion` matched if both of them belong to the same cluster. This way, it can work properly on important cases while keeping the logic for citation resolution to avoid affecting them.

**Comment by mlissner** [comment]
Got it, yeah. We can do it either way: We can tweak the lookup to return clusters and if there's one cluster, use it, or we can keep it the way it is, and even if there are multiple opinions returned, we pick one and return it (so long as they're from the same cluster). 

I don't think it matters which opinion you pick if they're from the same cluster since all we need is the case name (which is on the cluster), and the URL (which is on the cluster). Right?

**Comment by albertisfu** [comment]
Thanks. I've applied the fix in #4317 at the end I found querying for clusters in this use case it's better. 


> I don't think it matters which opinion you pick if they're from the same cluster since all we need is the case name (which is on the cluster), and the URL (which is on the cluster). Right?

That's correct if all the opinions belong to the same cluster. However, since the query is limited to returning just two opinions, there could be others that don't belong to the same cluster. That's why it's better to query for clusters in this case.

In my question, though, I was referring more to the other use case, which involves resolving citations when ingesting opinions where the resolution results are used to create `OpinionCited` instances that accept opinions. Let's say the resolution method, specifically [es_reverse_match](https://github.com/freelawproject/courtlistener/blob/f7337f80d5f9182dfe044ba12bd14689bd24ed1e/cl/citations/match_citations_queries.py#L46C5-L46C21) (which checks if the opinion's case name can be found in the citing opinion), matches two opinions, and both belong to the same cluster. In this case, the first one that matches the reverse match will be selected. Is that OK? Or would it be better to select one of them based on other parameters like their opinion type?  I mean is there a main Opinion that should be referenced?

**Comment by mlissner** [comment]
>  I mean is there a main Opinion that should be referenced?

Got it, thanks for forcing me to understand. There are three answers:

1. In the past, we didn't have opinion ordering, so I guess either was fine. Not ideal, but it's what we did, I guess.

2. Now that we have opinion ordering, it makes sense to choose the first opinion by order.

3. But that could be improved because sometimes a citation will have what's called a pincite, which is a citation to a particular page. If we know the pincite, we should figure out which of the sub-opinions it refers to based on the page numbers for each citation, and use that sub-opinion. (But this is hard.)

**Comment by albertisfu** [comment]
Thanks for your answer.


So we could start by doing this easy tweak:
> Now that we have opinion ordering, it makes sense to choose the first opinion by order.

I just noticed that `ordering_key` can be null. If that's the case in a cluster where it's not possible to get the first option because none of them have an `ordering_key`, is it okay to select any of them in that case?

> But that could be improved because sometimes a citation will have what's called a pincite, which is a citation to a particular page. If we know the pincite, we should figure out which of the sub-opinions it refers to based on the page numbers for each citation, and use that sub-opinion. (But this is hard.)

Got it. Yeah, this sounds hard. Should we open an issue to consider this as a future improvement?

**Comment by mlissner** [comment]
The ordering_key is entirely null for now, because we haven't populated it yet, but yeah, I imagine it'll be null in some cases even after Kevin populates it. In that case, I'd use the `type` field, which has things like `010combined`, and was designed for ordering before we had the `ordering_key` field.

> Got it. Yeah, this sounds hard. Should we open an issue to consider this as a future improvement?

That'd be great, thanks, and if you can reference this issue, that'd be helpful too.
