### ISSUE TITLE
Cannot load seals images on Tenn. Workers' Comp. pages

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4220]
This is in Firefox: 

![image](https://github.com/user-attachments/assets/4c5b5ebc-ab4e-48a0-b81f-eccc47e0ebdc)

I get an error in the console that says: 

```
A resource is blocked by OpaqueResponseBlocking, please check browser console for details.
```

I don't know why it says to look in the console, b/c that message is from the console.

**Comment by quevon24** [comment]
We had not released the latest version of seal rookery, it is already in process but it seems that the actions are failing in that repository, I am checking what is happening

**Comment by quevon24** [comment]
A new version of seal rookery has been deployed, this should be solved by now (github actions are finally back). 

I still don't understand why the console gives that message, but Ramiro told me that if a file is not in s3 then it returns an AccessDenied

**Comment by mlissner** [comment]
Great, thanks for the quick fix.
