### ISSUE TITLE
Messaging for when people cancel their CL accounts 

### ISSUE THREAD

**Issue by jeniferw** [freelawproject/courtlistener#4224]
Needs to include link to have them cancel their membership too
Can be done in their Neon portal at https://donate.free.law/login
Or by emailing jenifer@free.law

**Comment by jeniferw** [comment]
They actually can't delete their account in Neon - but they can cancel
their donation or membership.


If you are a member of or monthly donor to Free Law Project and want to
make changes to either, you will need to head over to your donor portal <a
href="https://donate.free.law/login">.


Given the tone of the rest of the message it is hard to come up with
something that encourages them to continue donating. But I don't want to
say they need to do that as well.

Jenifer




Jenifer Whiston, Director of Philanthropy
***@***.***  | 970-331-6194
Book a meeting - https://calendly.com/flp-jenifer
Make a Donation <https://www.courtlistener.com/donate/> to support Free Law
Project

**Comment by jeniferw** [comment]
Only correction is the link to the Neon portal - it should be https://donate.free.law/login

**Comment by mlissner** [comment]
Looks like https://donate.free.law redirects OK?
