### ISSUE TITLE
Duplicate emails with Group Memberships

### ISSUE THREAD

**Issue by jeniferw** [freelawproject/courtlistener#4227]

**Comment by jeniferw** [comment]
When Group memberships are created they must be under the umbrella of a Company account, and then each individual account is linked to that company account. One email is identified as the contact for the account. If that email is also tied to an individual account, I am getting the notification from CL to merge the accounts. 
We need to figure out if this is an actual problem, or if it will be okay for the webhooks checking from CL.

**Comment by mlissner** [comment]
Do you need help from anybody on the dev team to figure this one out?

**Comment by jeniferw** [comment]
I was chatting with Eduardo on a different membership issue & that's when this one came up. I need to follow up with him to get this sorted.

**Comment by jeniferw** [comment]
And yes - this does seem to be an issue - 

> A new user signed up for CourtListener and we tried to match their email address
> to Neon. Alas, it didn't work because the email address '[lrosiak@dailywire.com](mailto:lrosiak@dailywire.com)' appears
> in Neon more than once.
> Please take the following actions to fix this situation:
> 1. Please review the "Partial Match Queue" in Neon, as documented here:
>  https://support.neonone.com/hc/en-us/articles/4407408776717-Account-Match-Queue
> In that queue, you should find this user and you should be able to merge their records.
> 2. Once that's completed, please add the Neon account ID of the merged record to
> CourtListener at the following link: https://www.courtlistener.com/admin/auth/user/8146/change/
> Thank you for keeping everything tidy and good!
> 
> The bots at CourtListener

One account is a company & the other is an individual - so they can't (and shouldn't) be merged.

Can we set the Webhook to only check individual accounts? And not company accounts?

**Comment by mlissner** [comment]
That's a good question. Do you know, @ERosendo ?
