### ISSUE TITLE
Store iquery crawl HTMLs 

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#4231]
We're going to crawl all PACER iquery pages so we need to save the HTML of each page before running the daemon so they can be reprocessed when https://github.com/freelawproject/courtlistener/issues/2185 is solved.

**Comment by mlissner** [comment]
Thanks. @quevon24, you just did this for the free docs crawler. How much time do you think it'd take to add it to the iquery crawler?

**Comment by quevon24** [comment]
> Thanks. @quevon24, you just did this for the free docs crawler. How much time do you think it'd take to add it to the iquery crawler?

It shouldn't take that long, we just need to add add a new upload type and an object to relate it to the file (uses a generic foreign key)

**Comment by albertisfu** [comment]
Sure, I could do it and Kevin could review it if that's ok

**Comment by mlissner** [comment]
Works for me.
