### ISSUE TITLE
Data issue (NJ Chancery Court)

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#4237]
A librarian pointed out that we had mistakenly identified NJ Chancery court with NY Chancery court.  This occurred due to a bug in courts-db tool for identifying courts when using the looser standard of allow_partial_matches.  

That bug has since been closed and roughly 7k cases have been updated to reflect the mistake.  Those 7k are likely the only cases with this mistake but a more thorough audit is under way to find any other stragglers or volumes this occurred in.  As of now this has only been found in the NJ Equity Cases reporter.  

I plan to compare case.law metadata without ours today to verify that we have corrected all of these mistakes.

**Comment by mlissner** [comment]
This approach sounds great. Glad to be fixing these kinds of things!

**Comment by flooie** [comment]
I'm glad you suggested or hinted that a more thorough check should be made.  

I ended up finding roughly 3.5k more spread across a number of states and chancery courts.  These were fixed on the backend and a new courts-db was released to account for these inaccuracies in the future.

**Comment by mlissner** [comment]
Great stuff, Bill! Fixing code + data is where it's at!
