### ISSUE TITLE
Modify Docket Model to Add New Fields and Parent-Child Relationship

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#4240]
Description

We need to update the Docket model to include several new fields and establish a parent-child relationship. The following changes are required:

New Fields to Add:

	1.	Office Code: The code of the district office where the case was located I believe only single integer
	2.	Court Judge Initials: A field to store the initials of the court judge. (usually three characters)
	3.	Defendant Number: A field to store the defendant number for including more information. - I think the plan to use 0 to indicate the parent docket

Relationship to Add:

	•	Parent-Child Relationship: Add a foreign key to the Docket model itself to enable a parent-child relationship between dockets.  Similar to what we have done with Court.

Court Object example
```    
parent_court = models.ForeignKey(
        "self",
        help_text="Parent court for subdivisions",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name="child_courts",
    )
```

**Comment by mlissner** [comment]
Looks right to me. Maybe you and @quevon24 can work on the ordering PR with this one so you don't have conflicts and we can do it all as part of one migration?
