### ISSUE TITLE
Show approximate counts in the search UI for performance boost

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4255]
Doing accurate result counts is slow and Elastic can provide approximate counts instead, as a performance boost.

Let's take advantage of this for any count above the same threshold we used in the API (I think it was 10k?).

The front end currently shows:

 - For case law: `8,025 Opinions`
 - For RECAP: `200,045 Cases — 900,021 Docket Entries`
 - For oral args: `90,587 Oral Arguments`
 - For judges: `15,010 Judges`

For numbers above the threshold, let's change these to:
 - `About 800,000 Opinions`
 - `About 200,000 Cases and 900,000 Docket Entries` (We can replace the emdash with "and" throughout.)
 - `About 90,000 Oral Arguments`
 - `About 15,000 Judges`

The algorithm for rounding the numbers is to take the first two digits, then pad the rest with zeroes. There's probably a clever math way to do this, but I think this isn't too horrible of a hack:

```
def simplify_amount(x):
    x = str(x)
    first_two = x[:2]
    zeroes = (len(x) - 2) * "0"
    return int(first_two + zeroes)
```

**Comment by albertisfu** [comment]
Great, this sounds good to me.

Regarding the cardinality precision threshold, we decided to set it to 2000, which corresponds to around page 100 on the API:
https://github.com/freelawproject/courtlistener/pull/3926#issuecomment-2033531224

However this setting is easily configurable so we can change it if required.

**Comment by mlissner** [comment]
OK, yeah, 2000 is great, thanks.
