### ISSUE TITLE
Update the CL data model to hold scanned PDFs from Harvard

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4258]
One of the cool things we can get from CAP is scans of the original content. We need to integrate these and the first step is to identify how they fit in with our OpinionClusters and Opinions. Once we have a plan, we'll need migrations per the wiki: 

https://github.com/freelawproject/courtlistener/wiki/Database-migrations

**Comment by legaltextai** [comment]
As I understand, CAP went by reporters. For example, this one is 1 Ala. 48 https://static.case.law/ala/1.pdf#page=48  
That's how they structured URLs 
If so, what about a script that would link each row in the CL 'citations' dataset to respective case.law URL?

**Comment by mlissner** [comment]
We're working with CAP (and others) to split the reporters into "clusters." Once that's done, we'll be importing all the PDFs and linking them from our Cluster objects.
