### ISSUE TITLE
Behavior of `count` field in `attorneys` API endpoint

### ISSUE THREAD

**Issue by noahblakesmith** [freelawproject/courtlistener#4264]
# Issue

The `count` field is higher with filters than without filters. I am not sure how/why that can be. Thanks in advance!

# MRE

The "root" page has a `count` of ~9.7 million:

```
https://www.courtlistener.com/api/rest/v3/attorneys/
```

If I add a filter for dates between 2010 and 2019, the `count` is ~17.2 million:

``` 
https://www.courtlistener.com/api/rest/v3/attorneys/?docket__date_filed__range=2010-01-01,2019-12-31
```

**Comment by mlissner** [comment]
Thanks Noah. @ERosendo, if you could take a look, that would be great. Please let us know if you need more context.

**Comment by ERosendo** [comment]
I'll take a look! 👀

**Comment by mlissner** [comment]
Hi all, the fix for this is deploying now: https://github.com/freelawproject/courtlistener/actions/runs/10201177110

Thanks for the report!
