### ISSUE TITLE
Provide better print version when printing

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4278]
A user from CAP shares that when they print case law, it includes a bunch of junk from our sidebars. We should do better, and it shouldn't be terribly hard. 

Let's take a look at what CAP does, and see if we can match or improve it.

**Comment by mlissner** [comment]
I note that a component-based architecture, as envisioned in https://github.com/freelawproject/bigcases2/issues/569, would help with this in the future.

**Comment by mlissner** [comment]
One more complaint here.

**Comment by mlissner** [comment]
@flooie want to do some simple stuff here as part of your revamp or perhaps as a second PR? I imagine your changes should make this a lot easier?

**Comment by tactipus** [comment]
do you guys still want help?

**Comment by mlissner** [comment]
This might get a lot better with https://github.com/freelawproject/courtlistener/pull/4595, which should land any day now. After that, @ashkonf will be doing a full front end redesign (which could probably use another set of hands), so it might be a pretty inopportune time to work on this, actually. 

Kind of a perfect volunteer contribution otherwise though!

**Comment by flooie** [comment]
@tactipus - this landed today but Im not sure the printing couldn't be improved slightly.
