### ISSUE TITLE
Move page numbers into margin in case law

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4279]
I don't think we're doing a great job of showing page numbers when we have them. They should be shown in the margin, probably the left one.

The way we do this is with a little red dot: 

![image](https://github.com/user-attachments/assets/17202413-2bde-49c0-9513-b0ad57601834)

But, as a user shares, we're out of sync with the norm:

![image](https://github.com/user-attachments/assets/07fcbda6-f63a-4bf7-afc8-6fb3f3537730)

(Read to the end of that for an explanation why this is important from a UX perspective.)

**Comment by mlissner** [comment]
@flooie looks like we have an issue for this. Moving it to your backlog for processing!

**Comment by flooie** [comment]
Wahoo
