### ISSUE TITLE
Migration Guide (Google Doc)

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4295]
Update the [Migration Guide](https://docs.google.com/document/d/1S0la1BqKzIa7-RdJ3sTqyVQ-kC4IBm1bLp2D267ZyiI/edit?pli=1#heading=h.e2hodipepanf) to incorporate the v4 API changes.

**Related issues:** 

- https://github.com/freelawproject/courtlistener/pull/4235
- https://github.com/freelawproject/courtlistener/pull/3890
- https://github.com/freelawproject/courtlistener/issues/3843
- https://github.com/freelawproject/courtlistener/issues/2680
- https://github.com/freelawproject/courtlistener/issues/3918
- https://github.com/freelawproject/courtlistener/issues/3033
- https://github.com/freelawproject/courtlistener/issues/3632

**To Do:**
- [x] Document all changes in one place
- [x] Get any missing documentation, fields, etc. from Alberto
- [x] Update migration guide (track changes)

**Note:**
- Some information needs to be tracked for internal purposes, but does not need to be in the user-facing guide. Information like that can be found in [v4 api changes](https://docs.google.com/document/d/1jOjiym2vfgcSSMkzPniJUUBUN7sVQ6BUB3KBwnNoIXQ/edit).

**Comment by mlissner** [comment]
Hoorah, your first issue. Love it! I just made the migration guide visible to the public as well, just to be fully transparent (and to make sure it wasn't editable by the world!).

Thanks for filing this.

**Comment by s-taube** [comment]
@albertisfu, [This document](https://docs.google.com/document/d/1jOjiym2vfgcSSMkzPniJUUBUN7sVQ6BUB3KBwnNoIXQ/edit) is an attempt to capture all the api and webhook changes in one place before organizing and adding to the migration guide.

- Anything obvious missing? Anything look inaccurate? 
- If the changes I missed are documented somewhere, you can point me there and I can make updates to this doc. And feel free to edit the doc if you like.

Thank you!!

**Comment by s-taube** [comment]
Ok, I made a bunch of updates and tagged you both in a few questions in the comments (in the google doc). Getting closer! Thanks for your time @albertisfu @mlissner

**Comment by s-taube** [comment]
@albertisfu , you suggested a few API changes to add to the doc that @mlissner you indicated users don't necessarily need. Would it be helpful to document these for internal purposes? Like, I could add a separate section (that wouldn't be shared with users) with info like "specifying the field used as a tiebreaker for each `search_type`." lmk if this could be useful to have in one place.

**Comment by s-taube** [comment]
@mlissner two questions for you in the doc on [invalid cursor error](https://docs.google.com/document/d/1jOjiym2vfgcSSMkzPniJUUBUN7sVQ6BUB3KBwnNoIXQ/edit?disco=AAABPi4mhlk), and list of [filter changes](https://docs.google.com/document/d/1jOjiym2vfgcSSMkzPniJUUBUN7sVQ6BUB3KBwnNoIXQ/edit?disco=AAABPi4mhgg).

@albertisfu one question for you on whether there are there any more [field dates that changed](https://docs.google.com/document/d/1jOjiym2vfgcSSMkzPniJUUBUN7sVQ6BUB3KBwnNoIXQ/edit?disco=AAABUTQNq_8) to add.

**Comment by albertisfu** [comment]
> @albertisfu , you suggested a few API changes to add to the doc that @mlissner you indicated users don't necessarily need. Would it be helpful to document these for internal purposes? Like, I could add a separate section (that wouldn't be shared with users) with info like "specifying the field used as a tiebreaker for each search_type." lmk if this could be useful to have in one place.

Yeah, I think documenting this for internal knowledge will be helpful so we can remember why the order in the frontend differs from the API.

> @albertisfu one question for you on whether there are there any more [date fields that changed](https://docs.google.com/document/d/1jOjiym2vfgcSSMkzPniJUUBUN7sVQ6BUB3KBwnNoIXQ/edit?disco=AAABUTQNq_8) to add

Sure, I've provided the full list of date fields.

**Comment by s-taube** [comment]
Thanks @albertisfu and @mlissner! I believe all questions have been resolved. I'll start moving this info to the Guide on Monday. 

@albertisfu I added "internal reference only" sections with the info you provided. I think I captured it all, but feel free to add and edit if needed.

**Comment by s-taube** [comment]
@mlissner @albertisfu I added all the changes to the [Migration Guide](https://docs.google.com/document/d/1S0la1BqKzIa7-RdJ3sTqyVQ-kC4IBm1bLp2D267ZyiI/edit). This should be close to final now.

@albertisfu I tagged you on some of the fields that I want to double-check.
@mlissner I wonder if you have thoughts on section headings. I added comments to those I'm unsure of.

Feel free to comment or edit directly. Nit-picking is encouraged! Any changes to wording, formatting, flow, etc. is helpful.

**Comment by mlissner** [comment]
Thanks Stephanie. I just spent a bunch of time on this and I think I made it better. I tried to draw out the distinction between DB APIs and Search APIs, so people can focus on each. In the shuffle, I think I dropped the changes to the webhooks, but I think we can lace those back into the appropriate search API changes sections.

I also noticed (and commented) on a few more things (yes, I'm afraid so!) that I noticed, but I think it's quite close and looking good!

**Comment by s-taube** [comment]
@mlissner I added stemming and synonyms (aka #4410) to the [list of all api changes](https://docs.google.com/document/d/1jOjiym2vfgcSSMkzPniJUUBUN7sVQ6BUB3KBwnNoIXQ/edit) (for the sake of comprehensiveness), and to the [migration guide](https://docs.google.com/document/d/1S0la1BqKzIa7-RdJ3sTqyVQ-kC4IBm1bLp2D267ZyiI/edit?disco=AAABU4DSH9s). Look right?

**Comment by s-taube** [comment]
@albertisfu I tagged you on a few more open questions in the [migration guide](https://docs.google.com/document/d/1S0la1BqKzIa7-RdJ3sTqyVQ-kC4IBm1bLp2D267ZyiI/edit).

**Comment by albertisfu** [comment]
Sure! I’ve answered the questions. Let me know if anything else is required.

**Comment by s-taube** [comment]
@mlissner I believe the guide is done! Do you want to review before I mark this issue as "done?"

**Comment by mlissner** [comment]
Hoorah! Wonderful news. The next step is to move this task from you over to Alberto, so he can add it to the v4 documentation PR as HTML. I'll slide this onto his backlog and take it off yours.

**Comment by mlissner** [comment]
Safe to close this one?
