### ISSUE TITLE
Optionally save response content and headers, to debug failing scrapers

### ISSUE THREAD

**Issue by grossir** [freelawproject/courtlistener#4308]
Some sites behave differently when scraped from the server or from local environments. It would be useful to have an optional feature to collect extra information about the failing request. For a start, the returned HTML or JSON and the response headers. To further reduce the friction, we would store these documents on a bucket accessible to the developer. 

The command should look something like:
`./manage.py cl_scrape_opinions --courts juriscraper.opinions.united_states.state.minn --verbosity 3 --save-responses`

To actually implement it we can just access the `site.request["response"]` object. Then, store what we need on AWS?

The most recent example is `minn`, which doesn't fail anymore due to SSL errors or a forbidden status response, but shows no results when ran on the server, in contrast to a local run.

@flooie

**Comment by mlissner** [comment]
This sounds great, thanks @grossir. I do wonder if just storing everything is the way to go though:

 - S3 Glacier Instant Retrieval pricing is $0.004 per GB/month. Even if we had 100GB of data, that'd be $4/month. 
 - We can set up [S3 Lifecycle Rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html) to delete content when it's a few months old. 
 - Lifecycle transitions cost 2¢/1000 items. 

So I think for pennies we could store it all and you'd always have it for debugging.

**Comment by grossir** [comment]
Some cost estimations confirm this would be cheap

- Number of scrapers in Juriscraper: 250
- Scrape frequency: every hour, every day
- Size of data stored: 30MB hourly   /  0.75 GB daily    /  22 GB per 30 days
- Number of objects stored: 250 per hour /  6000 per day / 180 000 per month
- Glacier Instant Retrieval minimum storage duration: 90 days

We could set a lifecycle rule for deleting the objects after the 90 days (minimum storage duration). If that's the case, we would be paying:

- 66 GB (3 months worth of data) of storage per month * 0.004 per GB = 0.26 USD
- 180 000 PUT per month * 0.02 per 1000 requests = 3.6 USD
- a few GET / LIST / etc * $0.01	per 1000 requests = ?
- a few retrievals * 0.003 per GB retrieved = ?
- 180k deletes per month, seem to be free

So, putting the objects in the bucket seems to be the most expensive part; we could actually keep them for more time for little relative cost.

--------------------------------------

I think the bucket creation; and the creation of it's lifecycle is done through python code? But I don't see similar code on the infrastructure repo, so maybe it's on the kubernetes repo (which I don't have access to)

Some implementation notes:
- using naming that makes manual search easier:  scraper_id / year / month / day / hour-level-timestamp
- storing the raw response only if the hash has changed or there was some error: this would reduce noise and cost
- embedding the response headers as JSON, inside the response HTML/JSON: this would reduce cost, since most of the cost is in PUTting the object

---------------------------------------

Some details for the estimations:

- Number of scrapers:

`ls juriscraper/opinions/united_states/*/*py | wc -l`; discount `__init__.py` files, some unused scrapers; add 20 oral argument scrapers

- Size of data stored:

The size of all the raw example test files in juriscraper is 30MB (some of these were manually trimmed, some sources have multiple files)

```python
import os
! cd juriscraper/tests/examples/opinions/united_states

# hourly
sum([os.path.getsize(i) for i in os.listdir(".") if re.search(r"_example\.(html|json)", i)]) / 1e6

# per 30 days
sum([os.path.getsize(i) for i in os.listdir(".") if re.search(r"_example\.(html|json)", i)]) * 24 * 30 / 1e9
```

**Comment by mlissner** [comment]
> I think the bucket creation; and the creation of it's lifecycle is done through python code? But I don't see similar code on the infrastructure repo, so maybe it's on the kubernetes repo (which I don't have access to)

So far we've usually just done that by hand, but I think we can use our usual private bucket for this, right? Just need to put it in an appropriate directory?

**Comment by grossir** [comment]
The PR is ready for review. 

>  but I think we can use our usual private bucket for this

We can, I was assuming that a bucket could have a single storage class, but the storage class can vary per object 
![Image](https://github.com/user-attachments/assets/90a575d8-ac9c-446c-979a-89eb618d23ea)


I don't have permission to create lifecycle rules, but it can be done on the bucket [menu](https://us-west-2.console.aws.amazon.com/s3/management/dev-com-courtlistener-private-storage/lifecycle/create?region=us-west-2&bucketType=general), and apply the lifecycle to a "folder" inside the bucket

![Image](https://github.com/user-attachments/assets/ccb71489-5a92-43c5-9e6e-9d3f85994456)
![Image](https://github.com/user-attachments/assets/4304d833-fb3d-4e5a-b8e6-847965ce3d82)
