### ISSUE TITLE
Add DMCA language to terms

### ISSUE THREAD

**Issue by anseljh** [freelawproject/courtlistener#432]
Terms are here: https://github.com/freelawproject/courtlistener/blob/master/cl/simple_pages/templates/terms/latest.html

`latest.html` then becomes `7.html`

Update date and link to prior version

**Comment by mlissner** [comment]
OK, I'm all set up as a DMCA agent, with the check for $105 in the mail. Yay?

**Comment by mlissner** [comment]
So, @anseljh, it's been a couple months and I haven't heard anything back from USPTO. I also don't see anything listed on their site under Free Law Project or CourtListener. Do you know if this is normal?

**Comment by anseljh** [comment]
It's available now: http://www.copyright.gov/onlinesp/agents/f/free_law_project.pdf
