### ISSUE TITLE
Initial complaint button should be "petition" for bankr cases

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4324]
In bankruptcy cases, you have an initial "petition", not a "complaint", so we should update our buttons to show that properly in bankruptcy cases.

**Comment by v-anne** [comment]
Similar issue for cases in the courts of appeals. Right now the buttons are labeling the notice of appeal (the first item on the docket) as a "complaint."

**Comment by mlissner** [comment]
Good point, thank you!

**Comment by mlissner** [comment]
Bah, this one is trickier than all that. See Slack discussion in #recap on 2024-8-23 that concludes that we should just call it "Initial Document".

On the plus side, that's easier and it works across all filing types. On the minus side, Alberto, I'm sorry. :(
