### ISSUE TITLE
Explore Product Management Options (Jira, Notion, etc.)

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4347]

**Comment by s-taube** [comment]
Github to Jira [automation](https://www.atlassian.com/software/jira/automation-template-library/bitbucket-github-gitlab#:~:text=Jira%20automation%20templates%20for%20Bitbucket%2C%20GitHub%20or%20GitLab&text=Using%20automation%2C%20you%20can%20now,at%20the%20most%20common%20uses.)

**Comment by mlissner** [comment]
I found that non-profits can get Jira for 75% off, so I applied for that just to get that started. 

I just wrote an email about the upcoming citator project to launch it week after next, so we'll want to have an opinion and direction about Jira by the end of this coming week.

**Comment by s-taube** [comment]
@mlissner sounds good. I set a meeting for Tuesday to discuss Jira and some other process stuff. As far as I can tell, Jira is still best in class for our purposes, but we can discuss more then.

**Comment by s-taube** [comment]
@mlissner It seems there used to be an importer function in Jira that was specifically for Github, but it’s no longer available. Atlassian now [recommends](https://confluence.atlassian.com/adminjiraserver/migrating-from-other-issue-trackers-938847532.html) importing from Github with csv or json.

However, Github doesn’t make it easy to export issues. I can get a [tsv download of my backlog](https://docs.google.com/spreadsheets/d/1m-ZNSzAF_QP7V5Rp3EVOgKYBY9ePIxXsI8V4orOysOc/edit?gid=0#gid=0), which includes fields and a url, but not the descriptions or comments. Exporting issues seems to be a commonly requested feature, and there are lots of discussions and suggestions for workarounds. Some alternatives include this [github csv exporter](https://github.com/gavinr/github-csv-tools?tab=readme-ov-file) and getting a [list of issues in json format](https://github.com/zachleat/github-issue-to-json-file).

I’m inclined to keep everything where it is for now, and I can play around some more with getting better views and tracking in github projects. What do you think?

**Comment by mlissner** [comment]
How disappointing and weird. I feel like if I was a PM for Jira, making a smooth migration path would be a huge priority. I wonder what went wrong with that, and, yeah, I agree, let's see how far we can get with Github. 

I imagine it might not be so bad anyway for you to get a strong handle on our current practices before we migrate somewhere new, in any case.

Thanks for investigating. I have a feeling we'll migrate someday anyway, but, yeah, feels like it's not worth it yet, I think.
