### ISSUE TITLE
Email Opinion Search Alert Webhook users

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4348]
Per a discussion in the API Changes [document](https://docs.google.com/document/d/1jOjiym2vfgcSSMkzPniJUUBUN7sVQ6BUB3KBwnNoIXQ/edit), we want a count of users currently using the opinion search alert webhook.

To "evaluate if we need to do a v2 or if we should just notify these people and make sure they'll be fine."

See the [discussion here](https://docs.google.com/document/d/1jOjiym2vfgcSSMkzPniJUUBUN7sVQ6BUB3KBwnNoIXQ/edit?disco=AAABPi4mhiY).

**To Do:**

- [x] Check current webhooks and ID users who need to be notified (ST)
- [x] Email users

**Relates To:**

- #3632 
- #4540

**Comment by s-taube** [comment]
As far as I can tell, it looks like there are 9 legit users. Webhook IDs 186, 171, 164, 143, 137, 125, 87, 36, 32. Invalid webhooks are 178 (google), 131 (ngrok), 100 (ngrok), 83 (CL), 35 (ngrok).

**Comment by mlissner** [comment]
Fantastic. We can get their email addresses from there once we're ready to launch the changes to the webhooks.

**Comment by s-taube** [comment]
Email draft is [here](https://docs.google.com/document/d/1I5zUf0WtElJx0Pf3ndA7k7Do9gGlJUPPGwsutdV_gec/edit?tab=t.0)
