### ISSUE TITLE
Improve PDF file download for pacer free documents command

### ISSUE THREAD

**Issue by quevon24** [freelawproject/courtlistener#4359]
Currently when we run the process to download the free documents pdf files we pull all the rows from the table, this was not a problem with the daily cron until now when the sweep is going to be executed, this will add many new rows to the table, and this causes a conflict with the current operation of the pdf download because when the download is executed in the daily cron, it will start to process the rows added by the sweep, not only those added by the daily cron. We have two scenarios here:

1. For the daily cron we need to limit the amount of rows we get from the PACERFreeDocumentRow table instead of getting all, it could be that only the records from the last 7 days are obtained. 
2. For the sweep we need to split all the dates into 7-day ranges so as not to get all the rows at once.

Another problem that occurs is that several documents are downloaded from the same court at the same time and this could cause a blockage on the part of the court, so we need to implement some technique to alternate the download of documents from each court.

Finally, in case we have old documents that have not been downloaded, these will be attempted to be downloaded with the sweep.

The sweep has stopped for now, so the daily cron is running normally.

**Comment by mlissner** [comment]
Thanks Kevin. Let's prioritize a feature so that it doesn't download PDFs older than X days, and let's set X to be 10 in our cronjob. Let's see if we can get that done as soon as possible so we can resume crawling the reports.

As the reports are crawled, we can work on the round-robin part and get that deployed.

Can you share the code where we get all the rows at once?

**Comment by quevon24** [comment]
Here we get all the rows: https://github.com/freelawproject/courtlistener/blob/main/cl/corpus_importer/management/commands/scrape_pacer_free_opinions.py#L288

The filters above that code are only applied when we pass the date-start and date-end argument (using the sweep), we still need to split that date range because it will get all the rows from a long period of time, we can process that in 7-day ranges, there is already something similar where we generate the report.
