### ISSUE TITLE
Run Word2Vec on the corpus and represent opinions in vector space

### ISSUE THREAD

**Issue by elliottash** [freelawproject/courtlistener#436]
Let's run word2vec on the corpus of cases:

https://radimrehurek.com/gensim/models/word2vec.html

And then represent each opinion in the vector space. This would provide a language-based similarity metric between opinions that could complement the citation-based metrics.

It might also be useful as an input into a more general "Related Cases" metric that could use data on language, citations, time, and jurisdiction.

**Comment by mlissner** [comment]
I'm not an expert on similarity algos, but I know Solr has one that they use to power the "More Like This" feature: https://wiki.apache.org/solr/MoreLikeThis

I get the impression that using the above would take a lot of processing/storage, but I think we already have the Solr data all generated and in memory. No idea what algo it uses though.

**Comment by ellliottt** [comment]
Do you have term vectors enabled? If so this looks pretty good:

http://cephas.net/blog/2008/03/30/how-morelikethis-works-in-lucene/

On the other hand, Word2Vec seems to be more well-known. You can train the model offline, and cases can be assigned a vector (which is just a ~300-dimensional floating-point array) as they are loaded into the DB.

**Comment by mlissner** [comment]
I'm pretty sure termVectors are on: 

https://github.com/freelawproject/courtlistener/blob/master/Solr/conf/schema.xml#L320-L322

If we do word2vec and store it in the DB, how would you query the DB for a related item?

**Comment by ellliottt** [comment]
The standard method is to just take the cosine similarity between the vectors for two documents, which is just a scalar.

**Comment by ellliottt** [comment]
Code for cosine similarity: http://stackoverflow.com/questions/17627219/whats-the-fastest-way-in-python-to-calculate-cosine-similarity-given-sparse-mat

**Comment by mlissner** [comment]
If we get this in place, we should look into if turning off `termVectors` makes sense in Solr. Seems like we might be storing a lot of data we don't need.

**Comment by ellliottt** [comment]
Another idea I had is to get paragraph vectors for the contexts around each citation, which could then be used to train a treatment analysis model, for example determining whether it is a positive or negative citation.

**Comment by mlissner** [comment]
I think it's reasonable to close this. We've had related cases on the site for a while now.
