### ISSUE TITLE
Include the year in the cited-by sidebar

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#437]
@ellliottt has another good suggestion: We should include the year of all the cases in the cited-by sidebar. The Authorities already has this, and it's good and useful, but it looks like when we switched to solr for the cited-by sidebar we must have dropped this value.

**Comment by ellliottt** [comment]
It could include the short citation as well, e.g. Brady v. Maryland, **373 U.S. 83** (1963), or just the court e.g. Brady v. Maryland, (**U.S.** 1963). I prefer the latter.

**Comment by mlissner** [comment]
See also issue #494 -- similar enhancement.

**Comment by mlissner** [comment]
The code for this will be roughly: `result.dateFiled|date:"Y"`. You can see this in search_result.html.
