### ISSUE TITLE
CourtListener emailer not sending encrypted email.

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#438]
A good friend sent us this screenshot in response to today's newsletter:

![no-ssl](https://cloud.githubusercontent.com/assets/236970/13235754/78b4bfce-d974-11e5-908e-bc7fde02c121.png)

He's right. It's shameful and I shall have to fix it. I don't know how at the moment, and I fear this will mean more HTTPS certificates to manage, but I'm not sure there's a way around that at the moment.

PS: Holy hi-dpi screenshot!

**Comment by anseljh** [comment]
I suspect @joshdata might have some ideas! He made [Mail-in-a-Box](https://github.com/mail-in-a-box/mailinabox).

**Comment by mlissner** [comment]
Good call. He's gone deeper into email than any mortal ever should.

**Comment by JoshData** [comment]
We have to go deeper!

How does CL send its outbound mail?

**Comment by mlissner** [comment]
@JoshData: postfix?

**Comment by JoshData** [comment]
Ah, you run your own server.

So, truly, the best way to fix this is to set up a Mail-in-a-Box. Playing with postfix configs is no fun. If you want to be hard core, you can copy the configs from Mail-in-a-Box and hope it helps:

https://github.com/mail-in-a-box/mailinabox/blob/master/setup/mail-postfix.sh

You shouldn't need a signed cert to make the lock go away - a self-signed one should do the trick.

**Comment by mlissner** [comment]
That's good news about self-signed being enough, and thanks for the settings reference.

We've dabbled in self-hosting our mail, like MIB can do, but it's been an abject failure. Just one more thing that can fail in the infrastructure, I'm afraid. We'll see...perhaps I'll eat these words when I try to get the cert working....

**Comment by mlissner** [comment]
Well, this was annoying, but I think it's all set. From what I gather, you need to configure encryption for `smtp_` in /etc/postfix/main.cf file, and then make sure it's turned on by sending the right flags to the postfix process when it starts. Those flags are in /etc/postfix/master.cf. 

I'm not going to document all the flags and settings I just tweaked, but they're all on the server.

### Testing

I tested this using:

https://www.checktls.com/perl/TestSender.pl

And using gmail (which gives a little broken lock icon when things are no good).

I haven't devised a test to ensure that unencrypted email still works. I assume it does -- I didn't monkey with it.

**Comment by mlissner** [comment]
I used this for the self-signed cert, btw: https://devcenter.heroku.com/articles/ssl-certificate-self

**Comment by mlissner** [comment]
I just re-did this today and used certbot to make it happen. Many notes over in #1574 .
