### ISSUE TITLE
Update v3 API documentation

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4402]
Update all v3 API documentation with v4 info. Relevant pages can be found [here](https://www.courtlistener.com/help/api/rest/), as well as on subpages (in table of contents, also via the "learn more" links). Additionally, some notes on reorganizing web pages can be found in [this issue](https://github.com/freelawproject/courtlistener/issues/3874#issuecomment-2087592059)

To update html: From [this page](https://github.com/freelawproject/courtlistener/pull/4235/files), select vlatest page to update in the left nav. Select "edit," make any edits, and then hit "commit."

**Updates Needed:**

[api page](https://www.courtlistener.com/help/api/rest/):
- [x] "v3" references should be updated to "v4" (heading, commands, etc.) (note: this had already been completed)
- [x] typo under “filtering”: “Again, one of the fitlers is the ID field”
- [x] typo with Jurisdiction count: “We currently have 0 jurisdictions that can be accessed with our APIs.” (looks like it should be 3351, and automatically updated.)
- [x] remove "performance tip" no. 1
- [x] add an explanation of CBP after "field selection"

individual API pages: 
- [x] update references of "v3" to  "v4" all pages.
- [x] remove "count" from the example results, since this field was removed. Relevant for pages: Case Law, PACER, Financial Disclosures.
- [x] on advanced field page, change "human editors" to "editors"
- [x] on advanced field page, fix typo: “within an document type.”

[search api page](https://www.courtlistener.com/help/api/rest/v3/search/):

- [x] update references of "v3" to  "v4" (note: this had already been completed)
- [x] update type r, add rd
- [x] A new example should be provided for the "basic usage" results, since many of the fields have been removed, changed, or added. This can be found by going to [this url](https://www.courtlistener.com/api/rest/v4/search/?q=foo).
- [x] some fields are in those results that should have been removed -- e.g. source, non_participating_judge_ids. Comment to Alberto.
- [x] explain highlight=on
- [x] add cardinality of query counts
- [x] add information on ordering: "If your sorting field has null values..."
- [x] add information on key in type=r: "If there are more than three matching documents, the more_docs field for the docket result will be true..."

[Search Operators page:](https://www.courtlistener.com/help/search-operators/)
- [x] Update fields (update: not needed)

Other decisions:
- don't need to add error codes. All the information users need is in the error message itself.

**Comment by s-taube** [comment]
@albertisfu Mike asked me to update API pages (like [this one](https://github.com/freelawproject/courtlistener/blob/main/cl/api/templates/rest-docs-vlatest.html)) by duplicating the page, making the updates in html, and having you double check for accuracy. 1) does that sound okay? 2) is it helpful if I flag the changes I'm making by adding `<! -- comments --> `? 3) anything else that might make this process smoother? Thank you!

**Comment by albertisfu** [comment]
Sure, this sounds good to me!

Regarding the comments and making the process smoother, the  `<!-- comments -->` would be useful if you want to flag me with actual comments. For the purpose of reviewing the changes, I suggest first duplicating the pages and submitting a commit with only that. Afterward, you can make one or multiple commits as you prefer. When I review your changes, I can simply compare your first and latest commits to check what has changed between the original and new versions.

**Comment by s-taube** [comment]
I'm unclear what changes to make to the example results on the search api page (since some fields have been removed, but still show up in a v4 api request). I tagged Alberto in a comment in PR #4235 to get more info.

**Comment by mlissner** [comment]
Congrats and thank you!
