### ISSUE TITLE
V4 API Social Media Announcements

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4404]
Announce v4 of the API on social media:

threads, linkedin, bluesky, twitter, newsletter

**Comment by mlissner** [comment]
This is all set, but I skipped the newsletter (Jenifer will pick it up), and LinkedIn (nobody wants API news there!). 

Here's the post on BS: 


<blockquote class="bluesky-embed" data-bluesky-uri="at://did:plc:p6yq6roev2vlkpgw2i5h5c4a/app.bsky.feed.post/3l4tjwjooxn2p" data-bluesky-cid="bafyreibdk4j65b42i2b4q65ibjapfte2jo7tjp32tgqn37iykl6ztyazxa"><p lang="en">We&#x27;re launching v4 of our APIs! Version four brings a number of enhancements like deep pagination and vast improvements to the search API. If you&#x27;re using our APIs, please read the post and our migration guide for changes you may need to make: free.law/2024/09/23/v...<br><br><a href="https://bsky.app/profile/did:plc:p6yq6roev2vlkpgw2i5h5c4a/post/3l4tjwjooxn2p?ref_src=embed">[image or embed]</a></p>&mdash; Free Law Project ⚖ (<a href="https://bsky.app/profile/did:plc:p6yq6roev2vlkpgw2i5h5c4a?ref_src=embed">@free.law</a>) <a href="https://bsky.app/profile/did:plc:p6yq6roev2vlkpgw2i5h5c4a/post/3l4tjwjooxn2p?ref_src=embed">September 23, 2024 at 9:35 AM</a></blockquote>
