### ISSUE TITLE
Migrate the remaining Solr functions to ES before shutting down Solr.

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#4407]
I saw this error on Sentry: https://freelawproject.sentry.io/issues/5777983605/ which is related to the `build_chart_data` function in `coverage_utils`. The error has stopped, but I noticed that this helper function has not been migrated to ES.

We'll need to migrate it before shutting down Solr.

I also checked other functions that seem to require migration:

- `court_count_query` in `api.views`
- `query_facets` in `api.views`
- `authored_opinions` in `people_db.views`
- `oral_arguments_heard` in `people_db.views`
- `recap_cases_assigned` in `people_db.views`
- `docket_pks_for_query` in `bulk_utils`

There are also other Solr methods that require migration, but they are related to management commands:

- `add_parallel_citations.py`
- `populate_opinions.py`
- `buried_alive_project.py`
- `invoice_project.py`
- `legal_robot.py`
- `cl_get_ftm_ids.py`

We should determine if all of these commands are still active and if their Solr queries require migration.

**Comment by mlissner** [comment]
Thanks, Alberto. Supremely helpful. We can ignore all of the management commands for now — none of those are used regularly, so they're not worth our time.

For the rest, here's what I've come up with:

| function | purpose | solution | difficulty |
|--------|--------|--------|--------|
| court_count_query |  powers: `help/api/jurisdictions/` | rewrite with elastic | easy |
| query_facets | powers the the opinions coverage page | rewrite with elastic | easy |
| authored_opinions<br>oral_arguments_heard<br>recap_cases_assigned | powers the person page | rewrite with elastic | easy |
| docket_pks_for_query | two bulk commands | Punt. These commands aren't used much. | N/A | 

I don't think any of these needs waffles. I think they can just be put into prod now and we can rip out the old code. 

Nice to see how close we are.
