### ISSUE TITLE
Process for Feature Ideas

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4429]
Process for sharing feature ideas.

- [Github discussions](https://github.com/freelawproject/feature-foresight/discussions) for ideas not fully scoped (shower thoughts, consensus building)
- Issue templates for submitting feature ideas - example templates: [here](https://github.com/freelawproject/crm/issues/new?assignees=&labels=&projects=&template=seo-interview.md&title=%5BComany+Name%5D+%28SEO%29) and [here](https://raw.githubusercontent.com/freelawproject/crm/main/.github/ISSUE_TEMPLATE/seo-interview.md?token=GHSAT0AAAAAACHJVNH5AUS2WMKZVT5G3QVUZW3MA7Q)
- FLP [Roadmap](https://github.com/orgs/freelawproject/projects/59/views/3)
- [Python PEPs](https://github.com/python/peps) - how to contribute to Python Enhancement Proposals

**To Do:**

- [x] Template for feature proposals
- [x] Discussion categories
- [x] Update issue template
- [x] Update readme
- [x] Add issue template url to readme

_______
### **Github Discussions**

Use Github Discussions to share ideas and build consensus on the highest priorities and best solutions. Ideas may be for front-end features, technical/backend enhancements, process improvements, etc. Ideally, many of these discussions will turn into github issues at some point, and added to the roadmap

Start with one "ideas" category, and add more categories if needed (announcements, polls, etc.).

**Examples:**

Backend and technology:
- How might we flag queries that take too long to load / that overload Elastic?

Process:
- What information should be included in issues assigned to volunteers to decrease miscommunication?
- Is there a better way for users to report bugs?

Front end:
- How might we help technical but non-legal users better understand the content and functions?
- Feature Idea: In Recap "Jurisdictions" selection, indicate "Check All" is selected by default (by making the button a different color, etc.)

___________
**Note:** If you don't have enough details for a Feature Request, consider adding your idea to Discussions.

Headline
As a [this type of user] I want to [do what] in order to [accomplish what goal].

### **Feature Request Template:**

**What is the Feature?**
- Brief description of the feature. What does it do?

**What Problem Might it Solve?**
- Briefly describe the problem the feature might solve.

**Describe a Scenario in Which the Feature Might be Used**
- Who would use it? Why would they use it? What do they want to accomplish? What is their goal?

**Any Additional Information?**
- add any other helpful information
- e.g. notes on a conversation with a user or partner, workarounds users currently use, links or screenshots of another product with a similar feature, etc.
- **IMPORTANT: don't add individual or company names!** If there are notes in the crm, you can link to them.

### **Example:**

**What is the Feature?**
- Classification of CL documents by domain, sector, or topic. This could be a new search filter.

**What Problem Might it Solve?**
- Users who work in specific industries can't easily understand the coverage of documents on CL by domain.

**Describe a Scenario in Which the Feature Might be Used**
- A tech company is considering using the API. They want to understand CL coverage for their sectors of interest before making the commitment. They might do an advanced search using a "topic" filter for "civil rights," "environmental," or "bankruptcy" (for example).

**Any Additional Information?**
- A tech company mentioned that this would be a useful function on [date]. They focus on specific sectors and categorize documents with their own models. It would be helpful for them to understand CL coverage by topic before committing to using the API.
- This could also be used by those who want to follow topic areas (alerts).

**Comment by s-taube** [comment]
Attempted a PR for the issue template [here](https://github.com/freelawproject/feature-foresight/pull/1)

**Comment by s-taube** [comment]
Submitted a PR to update [readme](https://github.com/freelawproject/feature-foresight) on when to share to "ideas discussion" vs. "project board"

**Comment by mlissner** [comment]
I think it's safe to say your part of this is done for now, right?
