### ISSUE TITLE
Visualization: Supreme Court DB (Clean) Error

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#443]
There appears to be a bug that occurs when moving from SPREAD view to SCDB (Clean View). To duplicate, open a map in spread view. Change "Degrees of Separation" to 2. Then switch to SCDB Clean View. You will notice that the 3-degree cases re-appear, but the the "Degrees of Separation" still reads 2.

Two possible fixes come to mind. First, when DOS is 2 on Spread or SCDB (Complete) view, it should not be possible to select SCDB (Clean) [i.e., it is greyed out in the drop-down box). Alternatively, when switching to SCDB (Clean), the DOS should revert to 3.

**Comment by mlissner** [comment]
Colin, I'm tidying up issues, and I don't think anybody is ever going to pick this one up to work on it. As a result, I'm sorry to say I'm going to close it. I think I see visualizations as maintenance-only now, with no fixes for things like this. I'm still open to enhancements, if we can drum up interest, of course.
