### ISSUE TITLE
Link v4 api pages back to v3 and vice versa

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4454]
On v3 API pages, we want to let people know v4 is now available. And on v4 pages, we want to link people back to v3 in case they didn’t migrate yet.

- [x] **Below the headings on each v4 api page** add the line: “V4 of the API is now live! We encourage you to use the latest version. You can view information on previous versions of the API here.” and link to the changelog (https://www.courtlistener.com/help/api/rest/changes/). This change should be made at help/api/rest/v4, as well each individual api page like api/rest/v3#case-law-apis, etc.

- [ ] **Below the headings on the v3 changelog** page, add the line, “These notes are for a version of the API that has been deprecated and will soon be disabled completely. Please use the latest version, as these notes are only maintained to help with migrations.”  This is what's provided already on help/api/rest/v2 and help/api/rest/v1. Link "latest version" to https://www.courtlistener.com/help/api/rest/v4.

**Comment by s-taube** [comment]
@mlissner I was about to add this to the PR for Alberto as you requested, but I think I can make these updates myself?

**Comment by mlissner** [comment]
Yes! You certainly can, but I was thinking an alert like this one would be best:

![image](https://github.com/user-attachments/assets/10658975-5be5-4f7c-8119-56db4da600bf)

Want to take a look at that HTML and see if you can replicate it?

**Comment by s-taube** [comment]
I made the update to v4, and commented in #4235 that v3 needs to be updated. (I figured it makes more sense for one person to make all updates to api/rest/v3 at once, rather than having to work around my one random change.)

**Comment by mlissner** [comment]
Great! Exciting to get these launched.
