### ISSUE TITLE
Assign authorship to opinions in existing DB

### ISSUE THREAD

**Issue by ellliottt** [freelawproject/courtlistener#447]
Now that the federal judges database is populated, we need a script to iterate through the opinions and assign them to judges. 

Ideally we can populate `panel` for each docket, and then `author` and `joining` for each opinion in a cluster.

Again I can probably assign this to an RA in the next week or two.

**Comment by ellliottt** [comment]
This should also designate per curiam opinions.

**Comment by ellliottt** [comment]
Add a command to this:
https://github.com/freelawproject/courtlistener/blob/bf0256f7f64a620ff00b988fb1d7de8d6af4eb18/cl/people_db/management/commands/cl_import_judges.py
Use a queryset generator:
https://github.com/freelawproject/courtlistener/blob/daca6ec1b27a05056a570d4515e7627da9e9d533/cl/lib/db_tools.py
Iterate over opinion clusters where courtid = []

**Comment by mlissner** [comment]
Done!

**Comment by mlissner** [comment]
This, I'm afraid, is not done afterall. We need to make sure that new content automatically gets judge information assigned. Else the RSS feeds won't work.
