### ISSUE TITLE
Assess Site Map

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4473]
Review [Site Map](https://www.figma.com/design/OEDp7KwNSpJDyJRiKrJmm4/Court-Listener?node-id=6104-5975&node-type=canvas&t=ZSOrUqMmOa55ncA8-0) from Magnet. Note any differences between map and actual site.

**Missing from Site Map:**

Home (https://www.courtlistener.com/...):

- [Feeds](https://www.courtlistener.com/feeds/)
- Contact
- Contribute
- Terms
- Profile (and subpages for Alerts, Notes, Tags, etc.)

Help (https://www.courtlistener.com/help/...):

- Pages linked from [Help](https://www.courtlistener.com/help/) page, such as: [Help with Alerts](https://www.courtlistener.com/help/alerts/)
- Pages linked from [API Help Repository](https://www.courtlistener.com/help/api/), such as: [Replication](https://www.courtlistener.com/help/api/replication/), [Bulk Data](https://www.courtlistener.com/help/api/bulk-data/), [Rest API v4.0](https://www.courtlistener.com/help/api/rest/), etc.
- Pages linked from [Coverage Help](https://www.courtlistener.com/help/coverage/) Repository, such as: [RECAP Archive Coverage](https://www.courtlistener.com/help/coverage/recap/).

Visualizations Gallery
- [Create your own map](https://www.courtlistener.com/visualizations/scotus-mapper/new/) (must be logged in)

**Question:**

- I'm not sure what "Blank Page" means under "Docket Number" (RECAP sub-section) on site map

**Comment by s-taube** [comment]
@mlissner there are some pages missing from the site map. Is there any reason to leave pages off the site map? e.g. do we need the "contact" and "terms and privacy" pages mapped?

**Comment by mlissner** [comment]
I think those should all be on there, yeah, though the Privacy page is just a link to the privacy section on the TOS page?

**Comment by s-taube** [comment]
Ah, in the footer, it is called "Terms & Privacy." But since the url is just /terms/ I will refer to it that way.

**Comment by s-taube** [comment]
I emailed the comments to Magnet.
