### ISSUE TITLE
Customer Service Portal setup

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4478]
Today, questions and issues come in via [email](https://free.law/contact/) and [form](https://www.courtlistener.com/contact/) on the site. When the form is used, browser data is automatically captured.

**Set up customer service portal in Jira.**

- Users should (still) be able to report issues via email that are automatically added to the jira board.
- Users should still be able to report issues on the CL site via a form. These issues should be automatically added to the jira board.
- Users should be able to see the status of their issues in jira without creating a jira account.
- Auto collecting browser data is ideal. If not, ask the user for browser and version.

**Widget v Issue Collector:**

- [Jira's "Issue Collector"](https://st-flp.atlassian.net/secure/ViewCollectors!default.jspa?projectKey=CS) allows users to submit issues via a form on our website. It will collect page and browser info if users give permission (check box in form). No login needed.
- Jira's Service Management widget allows anyone (no login) to report an issue without leaving the CL site 
- widget is less customizable than issue collector
- issue collector is better if you want issues for multiple apps to live in one place

**Test:**

- [x] Update workflow in jira
- [x] Add email address that receives contact form requests to [Jira](https://freelawproject.atlassian.net/jira/servicedesk/projects/CS/settings/email)
- [x] Fill out the form on cl to see how it shows up in jira
- [x] Fix "mailto" rule to accurately find email address
- [x] Look into API options

**When Portal is live**
- [x] Different auto message for case removal requests and sealing order (thank you, please attach order)
- [x] Add Eduardo as RECAP bug assignee
- [x] Add sealing request type to Jira -- should be addressed with more urgency than once per week -- do you have a court-issued sealing order?
- [x] Mike should get an email whenever a new issue is created
- [x] Choose [auto assignee](https://freelawproject.atlassian.net/jira/servicedesk/projects/CS/settings/details) (currently: unassigned) - leave as unassigned
- [x] Choose who should do Removal Requests this month - Stephanie
- [x] [Edit notifs](https://freelawproject.atlassian.net/jira/servicedesk/projects/CS/settings/customer-notifications) so customers get an email "we're working on it" after they are made the reporter.
- [x] Instead of full names appearing in JIra to users, is it possible for all to show up "CourtListener staff" etc. -- no, but every individual can edit their name in their Jira Profile. To first name, last initial, or something more anonymous.
- [x] Add `removals@free.law` as auto assignee for all removal requests (not sealing requests)
- [x] Manually assign and respond to removal request tickets that already came in
- [x] Share automations to manage tickets from email

**Comment by s-taube** [comment]
[Board](https://freelawproject.atlassian.net/jira/servicedesk/projects/CS/boards/6) in Jira
[External form](https://freelawproject.atlassian.net/servicedesk/customer/portal/5) to add ticket
[Notes and instructions](https://docs.google.com/document/d/1n-e_iYIdt2luyOFN-MD_Nmasy5tWNa8IjK3KLuZujpc/edit) on Jira set up
[Standard Plan](https://admin.atlassian.com/billing/a801c514-9b85-4c59-b5d5-f85e0a0df267/entitlement/a2b97fec-70a5-39c5-9307-d5759674f2c2) seems fine

**Comment by s-taube** [comment]
**Can we update ticket status from email?** - Yes, with rules. For example, the FLP staff member would include a particular phrase in the email e.g. "This issue is now completed." (We could create templated emails for this.) Then, following a rule we created in Jira, the ticket would automatically move to the "done" column.

**Can we send different auto responses for different request types?** - Yes, this is possible with upgraded (not free) plan. So, people who send case removal requests could get a different auto response ("we'll review this within one week") than those who report bugs.

**Can we add more details on a customer, like type of user (Power User)?**  - Yes, we can add new fields to customer details. We can also choose whether that information appears on the ticket itself. That information can be shown or hidden from end users.

@mlissner

**Comment by s-taube** [comment]
API info:

- [REST API ](https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-request/#api-rest-servicedeskapi-request-post)for creating customer requests
- And for [creating new customers](https://developer.atlassian.com/cloud/jira/service-desk/rest/api-group-customer/#api-rest-servicedeskapi-customer-post)

**Comment by mlissner** [comment]
Neat. Clarification: Can we add data about the requestor to the initial email and then *not* show that to the user?

**Comment by s-taube** [comment]
No, the content of the email will appear in the jira ticket as the "description." This field is always visible to the user.

**Comment by mlissner** [comment]
OK, that's what I thought. Kind of makes me think we should got into the API. Looks like it's pretty darned simple, and if we did it that way we could avoid the regex stuff, send ourselves whatever metadata we want, while not showing that to users. 

That said, it feels like v2 and we should get v1 out the door, particularly since all our devs are totally swamped as it is.

I think that means we need a format for the emails that you like and we can easily tweak the contact form to behave accordingly. Is that a good place to start?

**Comment by s-taube** [comment]
Here are the auto-messages we're sending. lmk if any changes requested @mlissner 

1. For RECAP Extension Bugs and other Support requests:

The CourtListener team has received your request. We'll reach out with an update as soon as possible. Thank you!

2. For Case Removal requests (not sealing requests):

The CourtListener team has received your request. We'll update you within the next week. Thank you!

3. For Sealing requests:

The CourtListener team has received your request. If you have a court-issued sealing order, please respond with an attachment of (or link to) the order for our review. We'll update you within the next week. Thank you!

**Comment by mlissner** [comment]
They're good. I made some tweaks by editing your message. Thanks!

**Comment by s-taube** [comment]
Done.
