### ISSUE TITLE
Issues with dates of oral argument audio for cases that are argued multiple times

### ISSUE THREAD

**Issue by v-anne** [freelawproject/courtlistener#4480]
This is a very niche and not that important bug, and I suspect it will be difficult to fix, but I want to flag it in case I'm wrong.

When cases are reargued at the courts of appeals (whether after rehearing en banc or panel rehearing or some other procedural posture), CourtListener seems to modify the date of the argument retroactively.

Here is an example:

[_Farhane v. United States_](https://www.courtlistener.com/docket/61402639/farhane-v-united-states/) was argued twice at the Second Circuit. Once was before a three-judge panel on [November 15, 2021](https://www.courtlistener.com/docket/61402639/farhane-v-united-states/#entry-141). The second was before the full court sitting en banc on [May 22, 2024](https://www.courtlistener.com/docket/61402639/farhane-v-united-states/#entry-271). However, both argument recordings available on the docket page list the date as May 22, 2024. I can confirm they are distinct audio files, with the shorter one being the 2021 argument and the longer one being the 2024 reargument. Therefore, the date of the shorter one is incorrect.

My suspicion is that CourtListener looks at the `Date Argued: May 22, 2024` parameter directly from PACER to determine the date of the file. If that's the case, this is probably very difficult to fix. And given that it affects <~1% of cases, it's not really worthwhile to do so, either. However, I wanted to flag it in case this is easy to change.

Happy to provide additional examples if necessary.

**Comment by mlissner** [comment]
We're actually already aware of this bug. @grossir, do you know where the other one of these is that you're working on?

**Comment by v-anne** [comment]
Oops, I should've checked.

**Comment by grossir** [comment]
I think a solution is proposed in this open issue: [date_argued is on docket, but should be on clusters and audio files](https://github.com/freelawproject/courtlistener/issues/4195)

A related [closed issue](https://github.com/freelawproject/courtlistener/issues/4150) that explains the overwritting of `Docket.date_argued` and more fields
