### ISSUE TITLE
Do email alerts for Pray and Pay project

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4486]
The back end is now in place for the Pray and Pay project, so I think the next step is to get the emails going. This should be fairly easy and fit nicely into a single PR. 

There are a lot of examples of how we do emails, but the general idea is to use Django's email tools: 

https://docs.djangoproject.com/en/5.1/topics/email/

So I think my suggestion here is that @v-anne:
 - Take a look for examples of other emails we send
 - Copy their approach to code
 - Draft suggest some email text that could work
 - And finally, do a little PR putting it all together

Does that sound good? Once that's in place, I think the last steps will all be in the UI and documentation?

**Comment by mlissner** [comment]
yeah, I guess we'll need the API anyway, so we can make the button work. It'd probably borrow heavily from the Tag API in terms of permissions, I imagine. 

So yeah, emails, then API, then front end?

**Comment by v-anne** [comment]
I'm thinking through the front end, my first thought was to have something like this where the prayer emoji is available in rows of documents that need to be bought, right next to the "Buy on PACER" button. If someone clicks it without being logged in, they'll be directed to the sign in page. If they've exhausted their daily quota, the emoji will be grayed out with CSS.
<img width="943" alt="image" src="https://github.com/user-attachments/assets/e5e13c72-5b8f-4d1b-a7d6-fccf832355c8">

Thoughts?

**Comment by mlissner** [comment]
I'm going to close this and split off your earlier comment into https://github.com/freelawproject/courtlistener/issues/4507

Thanks for the emails. Getting there!
