### ISSUE TITLE
test_docket_and_docket_entry_already_exist is randomly failing due to a change in Django's get_available_name

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#4490]
The test test_docket_and_docket_entry_already_exist is randomly failing:

`AssertionError: 'gov.uscourts.scotus.asdf.1.0' not found in 'recap/gov.uscourts.scotus.asdf/gov_aWMPDJD.uscourts.scotus.asdf.1.0.pdf'`

The issue here is due to a file name collision, so Django appends a random prefix to the file name. Previously, it was something like:

`gov.uscourts.scotus.asdf.1.0_aWMPDJD.pdf`

But now it’s:

`gov_aWMPDJD.uscourts.scotus.asdf.1.0.pdf`

After these changes:
https://github.com/django/django/commit/eb2d49b73408f1e60b8e1fa7fee822816945e1cd#diff-2f8524035203a28c596eb210d5b886a12d5a46215a649bee85f9987cc335d128

I’m wondering if we should just tweak the test to accept this new format, or if we should somehow preserve the old format for existing files?

**Comment by mlissner** [comment]
Hm, I feel like this is a bug in Django. Was this documented in 5.1?

**Comment by albertisfu** [comment]
> I feel like this is a bug in Django.

Yeah, but it seems they were aware of it:

> In general, I think a period is a valid character in a filename, so we cannot simply assume everything to the right of the first period is the file extension. Some different strategies for the issue are detailed on [​stackoverflow](http://stackoverflow.com/questions/6525334/getting-file-extension-using-pattern-matching-in-python). I am not sure its up to Django to pick one, but we could at least document the caveat and link how to write your own storage subclass so someone can implement the behavior they desire.

https://code.djangoproject.com/ticket/23759

> Was this documented in 5.1?

no this is not documented in [5.1](https://docs.djangoproject.com/en/5.1/releases/5.1/) changes

**Comment by mlissner** [comment]
Ah, OK, so Django did this on purpose. I guess I get it, but weird that it wasn't documented. 

In any case, we have `IncrementingAWSMediaStorage`. Can we just use that and be done here?

**Comment by albertisfu** [comment]
Yeah, you're right. RECAPDocument uploads currently use `IncrementingAWSMediaStorage`, and I confirmed that this is not an issue in production. So, I just tweaked the test to resolve it in https://github.com/freelawproject/courtlistener/pull/4500
