### ISSUE TITLE
Add count API or parameter

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4506]
Well, OK, I admit it, I miss the counts that we used to have in the API. Let's add them back, but with some tweaks to make them better. We have two ways we can do this:

1. A count API that just provides the count for a query.

3. A count parameter on the existing APIs that either:
    - adds the count to the results like v3
    - just returns the count instead of the results. 

The main reason we removed the count was performance and to enable deep pagination, but it makes it difficult to see if filters are working. 

Thinking about this a bit, I think the better ergonomics are option 2. Adding a whole new API for this seems really annoying, so a better trick is to add a new GET parameter to all of our database APIs that returns the count instead of the results. That'd prevent people from turning it on for all results like in v3, which caused problems.

So imagine taking a query:

`/api/rest/v3/opinions-cited/?cited_opinion=32239`

That'd return the items that cite 32239.

But if you wanted the count, you'd just do:

`/api/rest/v3/opinions-cited/?cited_opinion=32239&count=on`

Which would return something like:

`{"count": 3302}`

Easy enough? 

And we could guide our v4 users by providing a reference to the count URL in the normal response. So right now v3 returns:

```
{
    "count": 2287,
    "next": "https://www.courtlistener.com/api/rest/v3/opinions-cited/?cited_opinion=105221&page=2",
    "previous": null,
    "results": [
...
    ]
}
```

That's nice. v4 is the same, but without the count key. In v4 we could do:

```
{
    # Add the count here ⬇️ 
    "count": https://www.courtlistener.com/api/rest/v3/opinions-cited/?cited_opinion=105221&count=on,
    "next": "https://www.courtlistener.com/api/rest/v3/opinions-cited/?cited_opinion=105221&page=2",
    "previous": null,
    "results": [
...
    ]
}
```

Thoughts?

**Comment by elisa-a-v** [comment]
OK, I got the exact behavior you described working, but before committing and creating a PR I wanted to ask:

1. Do we want this behavior to be decoupled from the `VersionBasedPagination` or is it ok to have it there for all paginated endpoints?
2. Do we restrict the `count=on` behavior to v4 or do we want ppl using v3 to also get responses like `{"count": 3302}`?
3. I've only tested with small datasets so I don't know how this will behave with actual data, is it ok to get the count by simply using `queryset.count()` or are there better approaches for this?

**Comment by elisa-a-v** [comment]
Also! Where in the docs should I add this info? Would [this](https://www.courtlistener.com/help/api/rest/v4#pagination) be the right place?

**Comment by mlissner** [comment]
Great questions:

1 & 2. Ideally, this would only be available for v4, but it doesn't really matter if it's available to v3 people too. They won't notice, and if they do, fine. It's not worth your time to make it not work in v3, I think.

3. I don't think there's any better way than doing `.count()`.

4. I think I'd add a new section for `Counting` under the `Ordering` section, so it goes:

    - Filtering
    - Ordering
    - Counting
    - Field Selection
    - Pagination

    The new pagination is the reason we need this, but I don't think users will make that connection, so we should just put it in the most logical place, which I think is under the Ordering section?
