### ISSUE TITLE
Add V2 of Webhooks

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#4540]
Since we're migrating from API V3 to V4, it's also a good idea to update Webhooks payloads from V1 to V2. This way, we can inform users that they should migrate to V2 webhooks or prepare for changes in V1.

This update will especially impact Opinions Search Alert Webhooks. Once we move them to Elasticsearch, some fields will be removed from the V1 webhooks.

Additionally, V2 webhooks should use the new serializers in API V4. For Opinions, this involves using a nested approach, where search results match clusters and nested Opinions. This will require adjustments to the ES query used for triggering alerts in `cl_send_alerts` to query parent-child documents. These changes will also affect the email template for Opinions Search Alerts.

For OA Search Alerts, we only need to update the webhook version since we're already using the latest V4 serializers for webhooks.

Once we release RECAP Search Alerts, we will simply need to update the webhook version to V2.

A couple of questions:

1. Should Webhook version V2 be applied to all other endpoints as well?
    - Docket Alerts
    - RECAP Fetch
    - Old Docket Alerts Report
    
    It seems that for these endpoints, only the webhook version needs to be updated since the serializers didn’t change in V4.
    
2. For Opinions, where V1 and V2 of the Webhooks will differ, you mentioned that users who don't want to migrate to V2 should be prepared for changes in V1. Does this mean we need to implement a mechanism that allows users to select which webhook version they want to use for the Opinions Search Alert webhook endpoint?

**Comment by mlissner** [comment]
> Should Webhook version V2 be applied to all other endpoints as well?

It'd be nice to always keep them all on the same version, yes, even if there are no changes, just like we do with the API. 

> Does this mean we need to implement a mechanism that allows users to select which webhook version they want to use for the Opinions Search Alert webhook endpoint?

I think so, yes, unless you can think of a simpler way.

**Comment by mlissner** [comment]
I think this is just a parent issue, so I'm assigning to Alberto so we can close it out when the time comes.

**Comment by mlissner** [comment]
This is done, right? We should close it if so. All sub-issues appear to be resolved?

**Comment by mlissner** [comment]
Once this is done, we can land the 4.1 documentation.
