### ISSUE TITLE
Store queries from the Search API

### ISSUE THREAD

**Issue by albertisfu** [freelawproject/courtlistener#4576]
From https://github.com/freelawproject/courtlistener/pull/4479 queries from the frontend began being stored in `SearchQuery` table.

Now we also need to start storing queries from the Search API.

**Comment by albertisfu** [comment]
Also, as part of this issue, we should add `SearchQuery` to the admin and ensure we can filter queries by user.

**Comment by mlissner** [comment]
I actually don't think this is important to anybody right now. Let's punt on it and focus on bigger priorities.

**Comment by mlissner** [comment]
Actually, I take that back. We should just do this b/c it's easy and we'll have something done. :)
