### ISSUE TITLE
Get Alerts Button Bug

### ISSUE THREAD

**Issue by Carter4242** [freelawproject/courtlistener#4581]
When pressing the [Get Alerts](https://www.courtlistener.com/docket/36046107/v-asda/) button on any case while logged in causes a weird error. "Not an ajax POST request."
![Image](https://github.com/user-attachments/assets/479f053f-567c-4837-8cc0-1d7d7809145c)

However, pressing the dropdown on Get Alerts -> Share Alert Link (E.g. taking you [here as an example](https://www.courtlistener.com/alert/docket/new/?pacer_case_id=149891&court_id=txed)). Pressing Get Alerts on that page works just fine...

Looking in my Network tab, it appears that it is indeed not an Ajax POST request... **When on the Share Alert screen, it sends a POST request, and when on the main opinion screen, a GET request is sent instead.**

I've searched through the code base for a like 20 minutes now, and I can't find out why that is (I know very little about Ajax though...) It may be a bug on my end, but I tried it in 2 different browsers.

Both buttons appear to be created by https://github.com/freelawproject/courtlistener/blob/710ff4b3fe71bca4cd329544423d497e2ddc968a/cl/opinion_page/templates/includes/docket_alerts_button.html

Which calls https://github.com/freelawproject/courtlistener/blob/710ff4b3fe71bca4cd329544423d497e2ddc968a/cl/alerts/views.py#L201 However, one calls with GET, and one with POST, when requested with GET it leads to this line https://github.com/freelawproject/courtlistener/blob/710ff4b3fe71bca4cd329544423d497e2ddc968a/cl/alerts/views.py#L237 Which returns the response I'm getting.

Apologies if this has already been reported, or is an issue on my end.

**Comment by mlissner** [comment]
I'm seeing this too, so something is up. My guess is that it's being caused by https://github.com/freelawproject/courtlistener/pull/4519, which I just reverted in https://github.com/freelawproject/courtlistener/pull/4582. It's deploying now. We'll know in about 15 minutes if this fixes it.

**Comment by mlissner** [comment]
OK, that worked. We'll get this fixed and re-deploy the earlier PR. Thanks for the detailed report!
