### ISSUE TITLE
Update CL Contact Form for Customer Support Portal

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4585]
Update [contact us form](https://www.courtlistener.com/contact/) in CourtListener:

**Atlassian Email Address:**
- [ ] Submissions should be emailed to: support@freelawproject.atlassian.net

**Issue Type:**
- [ ] Add single-select for users to choose one "Issue Type": 1) Case Removal Request, 2) RECAP Extension Bug, 3) Support
- [ ] The body of the email should include `Issue Type: [selection]` (e.g. `Issue Type: RECAP Extension Bug`)

**User Email Address:**
- [ ] In the body of the email, the user email address should be listed as `User Email: <email address>` (e.g. `User Email: <stephanie@free.law>`)
- Surrounding the email address with `< >`made the regex easier in Jira, but am open to a more elegant solution

Note:
- The subject of the email becomes the name/title of the Jira card
- All content in the email will appear in the Jira card, and will be visible to users

**Comment by mlissner** [comment]
This is a good one for @elisa-a-v. I'll add it to her backlog, and Elisa if you have questions about this, please let us know! Thanks for the details, Stephanie.

**Comment by elisa-a-v** [comment]
@mlissner I do have some questions:

1. These emails are currently being sent to info@free.law (right?), does this mean they will now only be sent to support@freelawproject.atlassian.net? Or should they be sent to both?
2. About the issue types, what are the rules mentioned? It says "capitalize or don't", is this in reference to the issue type selection? Not sure what to do about it.
3. The body currently has a `From: {name} ({email})` section, should I switch that for the `User Email: <email address>`? If so, how do I include the name?
4. Anything I should do about the Jira issues using the email subject for a title? Or is that just to give some more context? If this is something I'll need to check, I guess I'll need access to Jira?

**Comment by s-taube** [comment]
Instead of handling these "contact form" requests via email, as we have been, we will be handling them via Jira going forward. The requested changes will allow these requests to automatically create a Jira ticket.

1. Going forward, only send to [support@freelawproject.atlassian.net](mailto:support@freelawproject.atlassian.net)
2. Sorry for the confusion, you can ignore this. I will remove it from the description.
3. Yes, use the new format for email. You can leave name as is (`From: {name}`) and add email (`User Email: <email address>`) to a new line
4. It's just more context. You don't need to do anything.

Thank you! Let me know if any more info is helpful. @elisa-a-v
