### ISSUE TITLE
Parse case prefixes and parentheticals

### ISSUE THREAD

**Issue by elliottash** [freelawproject/courtlistener#461]
We can parse the prefixes and parentheticals after a citation, e.g.:

```
See also In re Dyer, 322 F.3d 1178, 1191 (9th Cir. 2003) (holding that civil contempt requires the court’s order be “specific and definite”).
```

With this sentence, we want to pair the citation with the prefix (see also) and the parenthetical (holding that civil contempt requires the court’s order be “specific and definite).

These can be keyed to `OpinionsCited` or to `Docket` of cited case.

**Comment by mlissner** [comment]
This...is basically done. If you want to see an example, check this out: https://www.courtlistener.com/opinion/145730/bell-atlantic-corp-v-twombly/summaries/

There's a beta flag I could include you in too, if you care to poke around, but the highlight is that link. We'll be blogging this eventually...

Only took about six years. 

@ProbablyFaiz and @varun-iyer, you might appreciate seeing this!
