### ISSUE TITLE
Add "sealing order" to CL contact form

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4612]
On the CourtListener [contact form](https://www.courtlistener.com/contact/), when a user selects the Issue Type "Case Removal Request," they should be required to make an additional selection:

        Do you have a court-issued sealing order?
        - Yes (will we ask you for a copy)
        - No

In addition, updates need to be made to the email that is sent from the form:

- If the user selects "Yes," the email should include "Issue Type: Sealing Order"
- and if the user selects "No," the email can include "Issue Type: Case Removal Request"

No strong preference on UI, but an example is to add a single-select dropdown that is grayed-out, and only active when "Case Removal Request" is selected.

- "No" would be the default option.
- We would also want to change the default "Issue Type" to "Support." The default is currently "Case Removal Request," and asking for a sealing order by default could be confusing to many users.

![Image](https://github.com/user-attachments/assets/c0c3e6e1-7930-44ad-be37-5cab8fe275be)

![Image](https://github.com/user-attachments/assets/72579fb1-8409-41e6-8e56-91a6bca0dbf1)

**Comment by s-taube** [comment]
@mlissner look about right?

**Comment by mlissner** [comment]
I think that'd work, but I think there's an easier way. In my inbox, I have a rule that looks for any of these words to categorize a sealing request:

- "time-senstive" 
- urgent 
- seal 
- stricken 
- redacted 
- psuedonym 
- "press coverage" 
- anonymity

That's a bit overinclusive, but it works easily enough. 

Could we just do that and keep the contact form simple, @s-taube?

**Comment by s-taube** [comment]
Ok this is done. Requests containing these keywords will be categorized as a sealing request.

**Comment by mlissner** [comment]
Nice one!
