### ISSUE TITLE
Update CL Contact Us form with new "Issue Types"

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4615]
On the CL [Contact Us form](https://www.courtlistener.com/contact/), add three new Issue Types to the dropdown:

- Data or API Help
- Report Data Quality Problem
- Memberships or Donations

And I think we can tweak "Support" to say "General Support".

Issue Type selected should (continue to) appear in the body of the email that is automatically sent to Atlassian ([support@freelawproject.atlassian.net](mailto:support@freelawproject.atlassian.net)) after a form is submitted.

**Comment by s-taube** [comment]
CC @mlissner

**Comment by mlissner** [comment]
Great. I tweaked your message, Stephanie, but otherwise looks good. I'll put it on Elisa's backlog.

**Comment by elisa-a-v** [comment]
I just created [a PR](https://github.com/freelawproject/courtlistener/pull/4648) for this but @s-taube I'm wondering if there may be a preferred order for the choices?

Currently looks like this:

![Image](https://github.com/user-attachments/assets/1f0d3654-d426-4461-b1b4-83f20a618e32)

**Comment by s-taube** [comment]
Yes, good question. "General Support" as the first option makes the most sense to me.

How about:
- General Support
- Data or API Help
- Report Data Quality Problem
- RECAP Extension Bug
- Case Removal Request
- Memberships or Donations
