### ISSUE TITLE
Flaky tests: `test_multiple_alerts_email_hits_limit_per_alert`

### ISSUE THREAD

**Issue by cweider** [freelawproject/courtlistener#4624]
With #4596 merged, GitHub scrolls to the test failure logs (instead of selenium screenshot step) and apparent that 1-2 tests are accounting for sporadic errors. I’d estimate this is happening ~5%:

```
FAIL: test_multiple_alerts_email_hits_limit_per_alert (cl.alerts.tests.tests_recap_alerts.RECAPAlertsSweepIndexTest.test_multiple_alerts_email_hits_limit_per_alert)
AssertionError: 2 != 0 : Did not get the right number of child hits for the case SUBPOENAS SERVED CASE. Expected: 0 - Got: 2
```
```
FAIL: test_party_api_query_counts (cl.api.tests.ApiQueryCountTests.test_party_api_query_counts)
AssertionError: 0 != 9 : 0 queries executed, 9 expected
```

Example runs:
- https://github.com/freelawproject/courtlistener/actions/runs/11519999300/job/32070313165
- https://github.com/freelawproject/courtlistener/actions/runs/11509037628/job/32047739928
- https://github.com/freelawproject/courtlistener/actions/runs/11413326545/job/31760679189#step:18:3009
- https://github.com/freelawproject/courtlistener/actions/runs/11413711180/job/31761624702#step:18:2997
- https://github.com/freelawproject/courtlistener/actions/runs/11414606689/job/31763714209#step:18:2958

**Comment by cweider** [comment]
Doubtful that I’m in any position to address the failures – only filing the ticket.

**Comment by mlissner** [comment]
Thanks. We'll get it on the list.

**Comment by mlissner** [comment]
This one is now assigned and set for the current sprint. Please let me know if I got the size wrong. :)

**Comment by ERosendo** [comment]
I submitted two pull requests to address the reported issues:

- https://github.com/freelawproject/courtlistener/pull/4690 fixes the error in `test_multiple_alerts_email_hits_limit_per_alert`.
- https://github.com/freelawproject/courtlistener/pull/4695 fixes the error in `test_party_api_query_counts`.
