### ISSUE TITLE
Create a 10% sample of Oral Argument data

### ISSUE THREAD

**Issue by ERosendo** [freelawproject/courtlistener#4643]
We should create a representative sample set of our oral argument data suitable for sharing with interested organizations. This sample set will provide a concise overview of our data's quality, diversity, and potential applications.

We can use our existing folder of transcribed data as the source for the sample set. This approach will streamline the process by eliminating the need for additional database queries, formatting, or cleaning

**Comment by ERosendo** [comment]
@mlissner We can use the following command to create a manifest file with record IDs for the sample set:

``` bash

/manage.py make_aws_manifest_files --record-type oa  --random-sample-percentage 10.0 --bucket-name bulk-customer-data --file-name o_10_random_sample --use-replica

```

**Comment by mlissner** [comment]
Thanks. I'll get this prioritized on your backlog. Can you work with Gianfranco to run whatever commands are needed? Do we have the lambda functions we were using before, or might Ramiro have those still?

**Comment by ERosendo** [comment]
>  Can you work with Gianfranco to run whatever commands are needed?ç

Sure!

> Do we have the lambda functions we were using before, or might Ramiro have those still?

The code for the lambda function can be found here: https://github.com/freelawproject/infrastructure/blob/main/Pulumi/bulk-customer-data/bulk-customer-data-function.zip

**Comment by ERosendo** [comment]
We've successfully executed the command to generate the manifest file and it's now stored in S3.

Once this PR: https://github.com/freelawproject/infrastructure/pull/199 is merged, the Lambda function will be ready to start the batch job to create the sample dataset.

Once the new sample dataset is created, we'll need to adjust permissions to grant access to the interested organization.

**Comment by mlissner** [comment]
Permissions tweaked in https://github.com/freelawproject/infrastructure/pull/200. Eduardo just confirmed, so he'll email and that's that!
