### ISSUE TITLE
Missing Attachments for Docket Entry in Criminal Docket

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#4664]
Missing Attachments for Criminal Docket Entry 

Not sure if this is a one-off or affects all of Criminal court listener but a user reported the inability to download attachments and have them show.  

Case: [United States v. Springer](https://www.courtlistener.com/docket/4364206/united-states-v-springer/?page=5#entry-811)

This case has a “doppelgänger” structure. 

I checked PACER and verified that the attachment exists, and purchased the document but it doest not show up on any of the three dockets. The attachment metadata does not appear in the docket on CL.

**Comment by mlissner** [comment]
Almost certainly a doppel-bug, but can you share the steps to reproduce?

**Comment by mlissner** [comment]
This should be fixed.
