### ISSUE TITLE
Send final email reminders to v3 API users

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4668]
Email v3 API users one last time to remind them that they should make the upgrades before November 25.

Email [draft here](https://docs.google.com/document/d/1I5zUf0WtElJx0Pf3ndA7k7Do9gGlJUPPGwsutdV_gec/edit?tab=t.0).

**Comment by s-taube** [comment]
Planning to send Wednesday, Nov 20.

**Comment by mlissner** [comment]
Looks good to me!

**Comment by s-taube** [comment]
Sent.
