### ISSUE TITLE
Case name search bug?

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4707]
This query brings back 34 results including ones that mention `Collections` in the title: 

https://www.courtlistener.com/?q=Word%20Collections%20v.%20Pandora&type=r&order_by=score%20desc&case_name=Pandora

![Image](https://github.com/user-attachments/assets/d94ad7e3-1d94-4290-bf29-f6c365f0808c)

But when I copy/paste "Collections" to the case name field, it brings back zero results:

![Image](https://github.com/user-attachments/assets/536474ab-2622-43b9-9b50-d54e7f42e4b7)

Huh? Is this because we're doing some weird exact matching on the case name, maybe? I wouldn't expect it to do a phrase search in the case name unless I put it in quotes. Is that what's happening, maybe?

**Comment by albertisfu** [comment]
Closed by #4834
