### ISSUE TITLE
Final switch to ElasticSearch from Solr

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4713]
We promised that we'd deprecate the Solr version of v3 of the API and webhooks on November 25th. 

In #4650, we learned that a brown out strategy should be pretty easy, so this ticket is to discuss the full profess we need to do on Monday and through the end of the week. 

There are three waffle flags that we need to flip:

 - The first flag will make v1 of the webhooks use Elastcic. This can be flipped on the 25th.
 - The second flag will make the front end use Elastic. This can be flipped on the 25th.
 - The third flag will make v3 of the API use Elastic. This should be exponentially browned-out:
     - Monday: 5%
     - Tuesday: 10%
     - Wednesday: 25%
     - Thursday: 50%
     - Friday: 100%

By Friday when this is done, Solr can probably be turned off. We'll see. Alberto, can you please chime in with the details and pieces I've missed about this?

**Comment by mlissner** [comment]
I think this is done, right, Alberto?

**Comment by albertisfu** [comment]
Yeah this is done, we can close it.
