### ISSUE TITLE
Email reminder to v1 webhook users

### ISSUE THREAD

**Issue by s-taube** [freelawproject/courtlistener#4716]
Email v1 webhook users to remind them:

- Backwards incompat changes are coming
- Adapt for those changes or move to v2, which we just launched (hooray, we're excited, etc.)

When: After v2 is launched: see #4678

Email [draft here](https://docs.google.com/document/d/1I5zUf0WtElJx0Pf3ndA7k7Do9gGlJUPPGwsutdV_gec/edit?tab=t.0).

**Comment by mlissner** [comment]
I think we decided not to do this and to instead send them a v2 is available message.
