### ISSUE TITLE
Remove dead branches that used to run Solr code

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4727]
When you place a query as a user or into the API, it eventually hits a waffle to branch it into either Solr or Elastic. This coming week we're going to be making it so all of these queries go to Elastic, so we can begin removing the dead branches and code after that. 

We'll want to begin by investigating all the places these exist, then we can think about what actions to take. I think mostly we'll just nuke this stuff, but I'm not entirely sure what we'll find when we start digging in.

**Comment by ERosendo** [comment]
I've looked through our code to see if there are any Waffle flags that could still redirect queries to SOLR. It seems like #4793 removed those specific code sections.
