### ISSUE TITLE
Secret Settings are sent in error emails

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#474]
I never realized this before, but there is a list of keywords that make settings private when error emails are sent:

https://docs.djangoproject.com/en/dev/ref/settings/#debug

It's a pretty solid list, and we need to go through our settings files (private and public) and rename any variables so that they match this list. 

At present, the values of these settings are sent through the mail, which is no good.

**Comment by djeraseit** [comment]
The only "sensitive" variable I see is EIN in 05-private-example.

**Comment by mlissner** [comment]
Well. That's surprisingly not bad at all. Can you update the codebase to rename EIN as EIN_SECRET, putting a comment in the example file explaining the weird name and referencing this bug? 

Good first bug. Easy-peasy!
