### ISSUE TITLE
Remove Solr from the docker compose file and Wiki

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4749]
Once we've completed the removal of all Solr stuff from the code base, we need to nuke it from our compose file and wiki. 

Exciting!

**Comment by mlissner** [comment]
This can only be done once these are completed: https://github.com/freelawproject/courtlistener/issues/4407, https://github.com/freelawproject/courtlistener/issues/3080, https://github.com/freelawproject/courtlistener/issues/4727, and https://github.com/freelawproject/courtlistener/issues/4726

**Comment by mlissner** [comment]
Only the wiki remains.

**Comment by albertisfu** [comment]
Okay, this is done. I've updated the following wiki pages that mentioned Solr.

https://github.com/freelawproject/courtlistener/wiki/Getting-Started-Developing-CourtListener
https://github.com/freelawproject/courtlistener/wiki/Automated-tests-on-CourtListener
https://github.com/freelawproject/courtlistener/wiki/Handling-an-Outage-if-Things-Are-Down

Removed references to Solr and replaced them with Elasticsearch search documentation.

Let me know what do you think.
