### ISSUE TITLE
GivingTuesday banner on CourtListener.com

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4750]
Simple banner to run for one day at top of CourtListener.com:

**Today is GivingTuesday.** Your support of Free Law Project helps make the justice system more transparent and accessible to all. **[Donate Today!](https://donate.free.law/forms/givingtuesday)**

This should land on Tuesday, December 3, 2024

**Comment by ERosendo** [comment]
@mlissner Here's a mockup of the banner:

![Image](https://github.com/user-attachments/assets/34addcf6-256d-411e-b01d-ebb2a287840d)

What do you think about the design? 

OTOH, Should we add a setting to toggle the banner's visibility(something like `GIVING_TUESDAY_MODE`)? This would allow us to hide it after December 3rd.

**Comment by mlissner** [comment]
I forget what the banner code looks like, but I guess we'd only ever have one at a time, so maybe we just need a variable like BANNER_NAME, or something, which you set to `giving-tuesday` or whatever? 

Maybe make the link a button and send it over to the right? 

Thoughts, @jeniferw?

**Comment by jeniferw** [comment]
I think it looks great!

**Comment by mlissner** [comment]
I like the button. More likely to get donations. :)

**Comment by mlissner** [comment]
We'll need this ready for review by mid-day Monday, so we can review and merge before Tuesday.
