### ISSUE TITLE
Zillions of 404's on empty search

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4760]
If you just query everything:

https://www.courtlistener.com/?type=o&q=&type=o&order_by=score%20desc

And click links, you get 404's for (practically?) everything. Not sure why. Is the new search giving links to opinions instead of clusters or...what's going on here? 

I'm going to mark this as a P0, but if we need to, we can revert to Solr (though that'd be sad).

**Comment by flooie** [comment]
@mlissner - It is not matching opinion IDs to the clusters for the few I checked.

**Comment by albertisfu** [comment]
@mlissner I reviewed this and found that it's a duplicate of https://github.com/freelawproject/courtlistener/issues/4722 and https://github.com/freelawproject/courtlistener/issues/3967


If you look for a match-all query, you'll find that the first 7 pages display clusters that no longer exist in the database.

I noticed a pattern in these clusters and their opinions.

They have timestamps ranging from `2024-01-13` to `2024-01-18`.

This is the date when these clusters and their opinions were indexed.

What likely happened is that a bulk content removal occurred after `2024-01-18`, where the clusters and opinions were deleted from the database but not from Elasticsearch. This could have happened if a method that doesn't trigger signals was used for the removal.

In https://github.com/freelawproject/courtlistener/issues/3967#issuecomment-2052200858, I confirmed that using a `filter` or `get` queryset does trigger signals to remove content from Elasticsearch."

`OpinionCluster.objects.filter(pk__in=[20,19]).delete()`

```
opinion = OpinionCluster.objects.get(pk=18)
opinion.delete()
```

One possibility is that during this bulk content removal, the ES cluster was unresponsive, or there were issues with Celery, so the content was not removed from ES. However, in https://github.com/freelawproject/courtlistener/issues/3967, we also confirmed that this content was not removed from Solr either.

Another possibility is that a different method for removing the content was used, such as a raw SQL query.

The reason some of these missing clusters appear first when performing a search is that a match-all query doesn't assign scores, so content indexed earlier (with an older timestamp) is shown first.

In https://github.com/freelawproject/courtlistener/issues/3967, we discussed that the solution to remove this content would involve checking every indexed cluster and confirming whether it still exists in the database or removing it. However, this approach would be very slow and inefficient.

Instead, I found a better method to remove this content from ES by relying on the `timestamp`. The reason these clusters and opinions have timestamps between 2024-01-13 and 2024-01-18, while the next closest timestamp is 2024-06-20, is likely that we started a full re-index for opinions on `2024-06-20` via the sweep indexer. This process takes every cluster and opinion from the database and indexes or updates it, updating the `timestamp` in the process.

Therefore, all the content whose `timestamp` was not updated likely corresponds to clusters whose related content no longer exists in the database, so they were not proccesed.

To confirm this, I used the following query:

{
```
   "query":{
      "bool":{
         "filter":[
           
         ]
      }
   },
   "sort":[
      {
         "timestamp":{
            "order":"asc"
         }
      }
   ],
   "size":100,
   "from":6900,
   "track_total_hits":true,
   "_source":{
      "includes":[
         "dateFiled",
         "court_id",
         "cluster_id",
         "id",
         "timestamp"
      ]
   }
```
}

This sorts clusters and opinions by timestamp. On this page, you'll be able to see the transition from missing opinions/clusters to content that exists in the database.

![Image](https://github.com/user-attachments/assets/352c3bfc-1f69-4738-8988-7e2def53fdc8)


I believe we can clean up this content using a `delete_by_query` operation targeting documents with a timestamp earlier than `2024-01-19`.

The results of this query for clusters and opinions are as follows:

[clusters_to_remove.json](https://github.com/user-attachments/files/17981522/clusters_to_remove.json)
[opinions_to_remove.json](https://github.com/user-attachments/files/17981521/opinions_to_remove.json)

I checked some of them randomly, and indeed, all of the ones I checked no longer exist in the database.

By grouping the missing clusters by court, I found the following:

```
la:307
nj:99
pa:12
nyappdiv:1832
okla:1
nysupct:5
nyappterm:4
ga:1
nynyccityct:2
pasuperct:3
md:4
nm:1
orctapp:2
nc:7
ohio:299
ohioctapp:33
ohsd:1
nd:2
nycterr:345
mass:247
massappct:13
ala:9
scotus:152
vt:1
conn:33
sc:6
ohctcomplcuyaho:2
cc:39
mich:8
circtsdil:1
ohctcomplmontgo:1
```
In case this is useful to identify when the deletion occurred and the method used.


The simplest method to remove this content is to use a `delete_by_query` task:

Opinions targeted: 3484
First confirm the number of opinions to remove:
`GET opinion_index/_count`

Perform the removal task:
`POST opinion_index/_delete_by_query?wait_for_completion=false&requests_per_second=8`

Common body to use:
```
{
   "query":{
      "bool":{
         "filter":[
           {
               "match":{
                  "cluster_child":"opinion"
               }
            },
            {
              "range":{
                 "timestamp":{
                    "lte":"2024-01-19"
                 }
              }
           }
         ]
      }
   }
}
```

Clusters targeted: 3472
 First confirm the number of clusters to remove:
`GET opinion_index/_count`

Perform the removal task:
`POST opinion_index/_delete_by_query?wait_for_completion=false&requests_per_second=8`

Common body to use:
```
{
   "query":{
      "bool":{
         "filter":[
           {
               "match":{
                  "cluster_child":"opinion_cluster"
               }
            },
            {
              "range":{
                 "timestamp":{
                    "lte":"2024-01-19"
                 }
              }
           }
         ]
      }
   }
}
```


Each request will return a task ID that can be used to monitor the progress of each task

`GET /_tasks/task_ID`

Let me know what do you think.

**Comment by mlissner** [comment]
@flooie, if you or somebody on your team can give this a review, Alberto or I can run the command, once approved.

**Comment by flooie** [comment]
I am 100% on board with this.  Thank you @albertisfu

**Comment by albertisfu** [comment]
@mlissner I remember Ramiro setting only read-only permissions for my ES user. But I can try running the delete queries if you agree.

**Comment by mlissner** [comment]
Done! Tasks:

```
"sRr5leJqQTucQqYSh3lPDA:956461218": {
  "node": "sRr5leJqQTucQqYSh3lPDA",
  "id": 956461218,
  "type": "transport",
  "action": "indices:data/write/delete/byquery",
  "start_time_in_millis": 1733193549107,
  "running_time_in_nanos": 24958676345,
  "cancellable": true,
  "cancelled": false,
  "headers": {
    "trace.id": "83b5569553b7e3ab56684131c070b5cd"
  }
},


"nmLgdM-aSDCkZNmyVoOodg:1688656653": {
  "node": "nmLgdM-aSDCkZNmyVoOodg",
  "id": 1688656653,
  "type": "transport",
  "action": "indices:data/write/delete/byquery",
  "start_time_in_millis": 1733193453187,
  "running_time_in_nanos": 120878860814,
  "cancellable": true,
  "cancelled": false,
  "headers": {
    "trace.id": "89eee6a7ede7fffaff9a21c787c28c3c"
  }
},
```

**Comment by mlissner** [comment]
Both tasks are now complete. Thank you, Alberto! Magic.
