### ISSUE TITLE
Replace GivingTuesday banner with EOY banner on CourtListener

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4769]
When we take down the Giving Tuesday banner on Wednesday, let's replace it with something like this:

![Image](https://github.com/user-attachments/assets/304a15d7-9ed5-4118-97b3-8cc04b31b8ac)

Text: Your support has grown CourtListener to over 10 million opinions, with improved search and API functionality. Help us continue expanding and enhancing access to the law. Donate before the end of 2024 to power free and open legal information for everyone. 

[**Make your DONATION TODAY.**](https://donate.free.law/forms/supportflp)

**Comment by ERosendo** [comment]
@mlissner There seems to be an issue with the reference image :(

**Comment by mlissner** [comment]
How's this:

![image](https://github.com/user-attachments/assets/a8983f42-cc81-4e05-baa4-8c6a0d2afe73)
