### ISSUE TITLE
Send email to all v4 API users re version 4.1

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#4796]
Let's make a list of all our v4 API users and send them an email that version 4.1 is out. I think the headline features are:

1. Filtering nested results.
2. A new API for counting results.
3. Scores in the search API

The email should link to the change log here: 

https://www.courtlistener.com/help/api/rest/changes/

**Comment by s-taube** [comment]
@mlissner: 

- https://github.com/freelawproject/courtlistener/issues/4315 provides the script we used in Sept to email API users about the upcoming v4.
- Are there any emails I should remove from the list? Last time I removed internal email addresses and did not email people with fewer than 100 API calls.
- One person emailed me after the last API reminder asking me not to email them again. I can manually remove them, but I'm flagging this for you, in case there is a better way to do this in the future.
- Draft email is [here](https://docs.google.com/document/d/1I5zUf0WtElJx0Pf3ndA7k7Do9gGlJUPPGwsutdV_gec/edit?tab=t.0#heading=h.azdcd0gl5njb).

**Comment by mlissner** [comment]
Just sent the list by email. 

I can't think of any others you should remove, no. Not doing internal and < 100 sounds good to me.

For the email, it should take the tone of a blog post, not a "Oh, no, things changed" message. We just want people to know there are some new features. Want to take another run at it with that tone in mind?

**Comment by s-taube** [comment]
@mlissner email content is updated... closer to what you have in mind?

**Comment by mlissner** [comment]
I made some tweaks, but looks great, thank you!
