### ISSUE TITLE
Notes on PDF Page

### ISSUE THREAD

**Issue by flooie** [freelawproject/courtlistener#4799]
There should be a message on the PDF page explaining redactions - 

I can imagine people now coming to our page and being quite confused or upset why things (headnotes) are redacted.

**Comment by mlissner** [comment]
Proposed language?

**Comment by flooie** [comment]
Certain sections of this document, such as headnotes or other content, may be redacted to comply with copyright or privacy requirements.

**Comment by mlissner** [comment]
Great!
