### ISSUE TITLE
Per curiam: OpinionCluster --> Opinion

### ISSUE THREAD

**Issue by jeffgortmaker** [freelawproject/courtlistener#480]
The `OpinionCluster.per_curiam` field should be moved to `Opinion`, where it makes more sense. There are currently zero instances in which it has been set to its non-default value, so this change shouldn't affect anybody.

It'd be great if this were done within a week, but marking opinions as per curiam is relatively isolated from the rest of the opinion upload process, so it's not too important.

**Comment by ellliottt** [comment]
This is done, in branch columbia.
