### ISSUE TITLE
Add Tips & Tricks section to API docs explaining how to use Java with Let's Encrypt certs.

### ISSUE THREAD

**Issue by karlnicholas** [freelawproject/courtlistener#486]
The SSL certificate issued by identrust.com, or Let’s Encrypt, which is used by CourtListerner.com, has not been added to the Java JVM list of trusted providers as of version 8u74. This causes an error when using Java libraries to read the rest api. The error is `PKIX path 
building failed: sun.security.provider.certpath.SunCertPathBuilderException: 
unable to find valid certification path to requested target`. I have a workaround, and posted it on StackOverflow. A link to the stackoverflow answer in case anyone else needs it.

[telling java to accept self-signed ssl certificate](http://stackoverflow.com/questions/2893819/telling-java-to-accept-self-signed-ssl-certificate/36707080#36707080)

**Comment by mlissner** [comment]
Nice workaround. If you want to add a troubleshooting section to the bottom of the API docs, you could put this link there with a brief explanation -- might help others. If, so, let's turn this issue into a task to do that and I'm happy to provide whatever guidance you need to get that sorted.

If you're not inclined to make that change (and that's totally up to you, of course), let's close this issue unless there's an action item here that I'm not seeing.

(Changing away from Let's Encrypt probably isn't an option unless there are other problems that come up. I'm inclined to blame Java for this one. At least in my experience other programming languages seem to have libraries (e.g. [certifi][1]) that help to keep the language up to date with the browser trust store. I also assume that Java will have to learn to deal with Let's Encrypt pretty darned soon.)

[1]: https://pypi.python.org/pypi/certifi

**Comment by karlnicholas** [comment]
Oh, yea, Let's Encrypt has already submitted a request to Oracle so it will probably be added into the default trusted Certificate Authorities soon enough. I'm happy to add something to the API docs if you want, so it's fine if you make a task out of it.

**Comment by mlissner** [comment]
Sounds good. I'll change the name of this issue and see if I can't assign it to you. Thanks for adding to the docs!
