### ISSUE TITLE
How often is the scotus bulk data updated?

### ISSUE THREAD

**Issue by vlymar** [freelawproject/courtlistener#489]
First off - thank you so much for offering this incredible data.

I noticed that only the first opinion of the 2015 term is present in the bulk data (Maryland v. Kulbicki, 577 U.S.).

This opinion is present on the site however. How often is the bulk data regenerated?

**Comment by mlissner** [comment]
Hi @vlymar, I think the bulk data system is presently broken, but I intend to fix it this week (your timing is good). 

I'll use this ticket to post updates.

**Comment by t4777sd** [comment]
I saw this issue was a couple weeks old. Is it still broken or is it fixed?

**Comment by mlissner** [comment]
Got this fixed and the data is generating now. Depending on what kind of information you're after, it may take a little while to generate all the new content and swap it in. Best thing to do is watch for the info.json files documented here:

https://www.courtlistener.com/api/bulk-info/#bulk-data

For example, the last time opinions were generated it took about 76,000 seconds (~23 hours), as you can see here:

https://www.courtlistener.com/api/bulk-data/opinions/info.json

Most of the objects are faster than that though, and should be done well before. They're all generating in parallel.

Thanks for your patience, and terribly sorry for this delay. It's been very busy!

**Comment by vlymar** [comment]
No worries, thanks for fixing it!

**Comment by vlymar** [comment]
https://www.courtlistener.com/api/bulk-data/opinions/?C=M;O=A

are opinions still generating?

**Comment by mlissner** [comment]
Looks like something went wrong in the generation and somehow we didn't get a warning or anything. I'm looking into it now. These long running processes are tricky.

**Comment by mlissner** [comment]
This is still going, FYI.

**Comment by mlissner** [comment]
And it's done! Next time should be faster, assuming the incremental updater works as designed! Sorry for the major delays. Enjoy the data.

**Comment by t4777sd** [comment]
This issues still seems a problem. Court data has not updated since May. Other data has not updated in a couple months: https://www.courtlistener.com/api/bulk-data/
