### ISSUE TITLE
Judge data: Pres. Obama listed as "Barack Hussein Obama Obama II"

### ISSUE THREAD

**Issue by anseljh** [freelawproject/courtlistener#493]
I noticed this when viewing a judge that President Obama appointed. Why is his last name repeated?

URL: https://www.courtlistener.com/person/43/barack-hussein-obama-obama-ii/

![2016-04-20-obama-obama](https://cloud.githubusercontent.com/assets/2075772/14692839/dde64292-070e-11e6-975f-e5ed633adde5.png)

**Comment by mlissner** [comment]
That'd be my fault. I was manually putting his middle name earlier today...screwed it up. Fixed, thanks.
