### ISSUE TITLE
Add Save button to "Now editing Alert foo" notification

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#499]
When you're editing an alert, there's a thing at the top of the search results that says:

![screenshot from 2016-05-02 09 14 38](https://cloud.githubusercontent.com/assets/236970/14959867/6eab1c2c-1046-11e6-8267-88dc32e84c74.png)

To the left of the Cancel button, there should be a little save button as well. That'll have to use JavaScript to submit the form in the sidebar (sigh).

**Comment by djeraseit** [comment]
This code could go after the Cancel <a> link.
<button type="submit" class="btn btn-danger" name="alertSave" id="alertSaveNotify">
                    Save Changes
                </button>

**Comment by mlissner** [comment]
If we create the button, I think we can just update this line to grab it, and we should be in business without needing an onclick:

https://github.com/freelawproject/courtlistener/blob/07f4804e77ab71cececd532e8a74cc9e4eb2dd2a/cl/assets/static-global/js/base.js#L96

Also, as a general thing, we avoid using paths like forms[2], since that might break if we ever added another form to the page (FYI). Alas, our codebase is too big and our QA too poor to get away with things like that.
