### ISSUE TITLE
Judge sorting and 1970/01/01

### ISSUE THREAD

**Issue by jraller** [freelawproject/courtlistener#500]
When sorting judges by Most Recently Born it shows them in the following order:

recent dates going back to 1970
unknown
dates prior to 1970 going further back

It appears as if unknown is being treated like a zero and being sorted as if it were the Unix epoch of 1970/01/01

**Comment by jraller** [comment]
It also looks like that sort order could benefit from an alpha by last name tie breaker for same date values.

**Comment by jraller** [comment]
The good news is that this doesn't impact the search: https://www.courtlistener.com/?q=&type=p&born_after=1969-12-30&born_before=1970-01-01&order_by=dob+desc as this returns only 7 judges for whom only the year 1970 is known.

**Comment by mlissner** [comment]
OK, we're not alone. There's a bug: https://issues.apache.org/jira/browse/SOLR-6430, and it's even documented:

> For new date fields (i.e. those based on the TrieDateField class), the fieldvalue behavior is as follows: If the document has a value in that field, then the numeric field value is the number of milliseconds(?) between that date and the epoch. (This number can be negative for documents dated before the epoch.) If the document has no value in that field, then the numeric field value is 0. (That is, the default==0 convention still holds for dates. This has the side-effect of making undated documents act as if they were dated 1970-01-01T00:00:00Z.) 

Who in their right minds thought this was OK? I have no idea.

**Comment by mlissner** [comment]
This is a good query to expose the issue: https://www.courtlistener.com/?q=&type=p&order_by=dob+desc&court=ca3+ca5+ca6+ala

**Comment by mlissner** [comment]
OK, this is fixed by adding the sortMissingLast parameter to the schema. I'll get it pushed in a bit, but, alas, this will require an reindex.

**Comment by mlissner** [comment]
And closing. 

On a somewhat random note, I'm pleased that this is issue number 500. I should get a day off or something....
