### ISSUE TITLE
What is the opinion sha1 a signature of?

### ISSUE THREAD

**Issue by vlymar** [freelawproject/courtlistener#501]
```
> openssl sha1 opinions/100000.json
SHA1(opinions/100000.json)= 3a379fad0176ec0dc5f30a5264d7d839e863d272

> jq '.sha1' opinions/100000.json
"f966678c479af550803b000aecea9d1f16897a6a"
```

I'm trying to find a reliable way to detect when opinions are updated, and curious what the sha1 is a sig. of. Can I rely on it to change if the opinion metadata or content is updated, or should I compare the timestamps instead?

In general, are opinions changed over time? For example would a slip opinion get a new opinion object or just update the previous opinion object?

Thanks!

edit. - this is in reference to the bulk metadata specifically

**Comment by mlissner** [comment]
This probably needs better documentation, but the SHA1 is based on the best thing that we can identify at the time we acquire the content. So, if we're downloading PDFs, the SHA is a hash of the binary PDF. If we get the content as HTML, it's a hash of that, etc. 

Importantly, it doesn't to my knowledge ever incorporate the other metadata. By far the best thing for what you want to do is the date_modified field, which, if you're interested, you can monitor via the API.

**Comment by vlymar** [comment]
thanks, appreciate the prompt response as usual :)
