### ISSUE TITLE
 Make dockets great

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#506]
This is a tracking bug for making dockets great as we add the RECAP content to CourtListener. Lots of things to do here:

Beta Release:
- [x] Privacy rules in place (bankruptcy dockets with < 500 items are private, everything else is public; all documents are private by default)
- [x] Add the meta data to the dockets
- [x] Make sure that oral arguments and opinions display nicely alongside recap content
- [x] Work out the modal popup for selecting the documents associated with a docket entry
  - [x] What happens when we don't know anything about an entry?
- [x] Make downloading documents work

V1:
- [x] Links to Internet Archive are available somehow?
- [x] Ensure that dockets are added to the sitemaps
- [x] OCR under way as in issue #546.

V2:
- [x] Sortable dockets (reverse chron)
- [x] Add recap content to the API

Later:
- [x] Favorites integration
- [x] Citation extraction, linkification, etc.
- [x] Party information (note that this should be behind a ajax request with noindex protecting the info from getting into search engines -- fun)

I'll be adding and checking items on this list for the next month or so, I suspect, but I do want to get this feature out the door.

**Comment by janderse** [comment]
How about some sort of simple indicator as to whether the linked item is available in the archive?

**Comment by mlissner** [comment]
> How about some sort of simple indicator as to whether the linked item is available in the archive?

Yeah, I think we need something like that, but I'm trying to figure out exactly what form it would take. One problem is that you have to click on each row in the table to know whether the item is available, but I'm hoping that won't matter as much once we have a site that can query PACER and get documents on your behalf.

**Comment by janderse** [comment]
You could use a small download icon - one of those down arrows like:
https://commons.wikimedia.org/wiki/File:Download_alt_font_awesome.svg

**Comment by mlissner** [comment]
We use Font Awesome, so we have all of those  available. Something like: http://fontawesome.io/icon/download/, maybe. Same idea....

**Comment by mlissner** [comment]
This issue got sidelined back in June, but I'm finally picking it up again. Alas, I completely forget the status of it, so brace yourselves while I start noting issues that need resolution:

 - [ ] On [this page][1] you can see that sometimes item one says Unknown Description, but if you click the modal, it says "Description Unknown."
 - [ ] Add RECAP to the navbar and highlight it on docket pages.
 - [x] Investigate the `make_recap_path` function, which currently throws a `NotImplementedError`. What was it supposed to do exactly?

[1]: https://www.courtlistener.com/docket/3071659/russell-a-shangin/

**Comment by mlissner** [comment]
Make the various metadata (cause, nos) clickable for search results.

**Comment by mlissner** [comment]
I've spun all the items in this ticket into their own ticket. You can see them all (in rough priority order) [in Project 1](https://github.com/freelawproject/courtlistener/projects/1)
