### ISSUE TITLE
California missing opinions.

### ISSUE THREAD

**Issue by karlnicholas** [freelawproject/courtlistener#512]
I downloaded the bulk California files (April 2016) and extracted all the published opinions and the content, which was HTML-lawbox. I parsed the opinions to find citations in them. In the bulk files I found 74,544 unique published opinions. _Within_ those opinions I found 422,427 citations, of which 71,197 were unique. Of the 71,197 unique citations found within the opinions, 19,724 were not found in the list of published opinions from the bulk files. Hope this makes sense.

Most of these 19,724 opinions are (\* Cal. *) opinions, meaning they are old Supreme Court decisions. The breakdown is as follows:

Cal.= 15227 
Cal.2d=1079
Cal.3d=305
Cal.4th=190 

Cal.App=67
Cal.App.2d=2100 
Cal.App.3d=110 
Cal.App.4th=646 

I don't know if anything can be done about the (\* Cal. *) opinions because they are so old. I don't find a way to get them from http://findlaw.com for example.

The rest represent a total of 4,497 opinions. Not a particularly large number in the scheme of things, but enough to ask about.

Is there anyway, given a list, these can be found and loaded?

Thanks.

**Comment by brianwc** [comment]
We have been working for months on a large import of state cases that is getting closer to being ready every day. We expect this import will have everything you're looking for, as it includes not only California but  all 50 states.

**Comment by karlnicholas** [comment]
Some pretty serious work there! I look forward to it.

**Comment by rkiddy** [comment]
So, how has this worked out? Since 2016? :--)

**Comment by mlissner** [comment]
You can see our coverage here: https://www.courtlistener.com/help/coverage/opinions/

We're still doing big imports!
