### ISSUE TITLE
Redesign nav bars to better promote features

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#529]
This is an important issue that will have deep changes on a lot of areas of the site, and I'm writing it up to get a feel for how it would work. The idea is to add a second navbar to CourtListener.

There's a few problems with the status quo that this would ideally solve:

 - The path to search is very bad, and is especially bad for oral arguments and judges.
    - Currently, to place an opinion search, your best bet is to go to the homepage. If you want to do an oral arg search or a judge search, you have to go to the homepage, search for something -- anything -- and then switch over to show oral arg or judge results.

 - There are search input boxes on different pages in the site, and they do different things depending on your "context". For example, on a judge page, if you do a search, you'll get judge results, ditto for opinions. 

 - There's no landing page for judges or oral arguments where we offer an advanced search interface, like the one we have for opinions on the homepage.

 - In a similar vein, there's no easy way to see the other related pages on a topic. For example, say we make an interface where you can look up a reporter, then select a volume and finally a page. Where would that currently live? Currently, that'd go in the footer...where it'd never be seen again. Not good.

Our current navbar has the following content, and we'd want the new one to support this too:

 - About
 - Visualizations
    - Gallery
    - SCOTUS Networks
    - New Network
 - FAQ
 - Tour (if you're not logged in)
 - Sign-in / Register (if you're not logged in), else:
 - Profile
    - Alerts
    - Visualizations
    - Favorites
    - Donations
    - Account
    - Sign Out
 - Query box (sometimes)

Of the above, I think we can move Visualizations to the second nav bar, and move the query box into the search results page itself. That should clean it up significantly, but moving the query box to the search results page means that it's not on every page -- that might be a change for some people.

So...if we do that, I think the final version of the second nav bar would be:

 - Opinions
    - Citation Lookup (I'm not sure how to integrate this here without using a drop down. I want people to be able to click on Opinions and have it go straight to the search page for opinions, so making it a drop down isn't ideal. Ideas welcome, but this does feel like it needs to be integrated here.)
 - Oral Arguments
 - Judges
 - RECAP (eventually)
 - Visualizations
    - Gallery
    - SCOTUS Networks
    - New Network
 - Donate (in red, floated right)

And we should have plenty of room to add more stuff if we need to. 

I think this should/could work, and as always, I'm eager for feedback or help!

**Comment by mlissner** [comment]
I think the breakdown here, semantically is that the top navbar is for site- and profile-related stuff (FAQ, Tour, About), and the second is for features. I like it.

**Comment by mlissner** [comment]
Hm, fun question: What happens on the mobile version of the site when you have two nav bars? Currently this creates a hamburger thing that you can click, but I can't imagine having two hamburgers. Maybe we ditch the second navbar on small screens, and put all its content into the hamburger? Seems less than optimal.

**Comment by arderyp** [comment]
I think this is a great idea.  Considering the mobile perspective is wise, IMO, and I agree that dual hamburgers is a not the best approach as it could cause confusion.  I think the validity of merging the two navs into one hamburger depends on how it looks/feels.  I could be over crowded, and if it isn't now, it could become overcrowded in time.  It's an interesting problem. I'll think about it more and pipe up if I have any alternate ideas.

**Comment by mlissner** [comment]
I don't know if the double hamburger with descriptive text is going to help people -- people are really bad at reading words and worse at understanding them. I consistently over estimate people.

Right now I'm thinking we should probably do a survey of popular mobile sites to see what the best of breed are doing. My bet is they're collapsing everything into one burger.

So far, I've looked at Github, and their solution is terrible. They basically just drop about 60% of the sites features if you're on mobile. What Github does offer that's interesting though, is the use of a horizontal rule inside the menu to separate the parts. That might not be a bad solution -- on desktop, we have two nav bars and on mobile we have a menu with two sections.

More surveying would probably yield other useful ideas, I bet.

**Comment by mlissner** [comment]
Another vote for nested menu:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/mlissner">@mlissner</a> 1) don&#39;t ever have double navbars 2) if you do, one should be a child of the other, so you nest the lists in the hamburger.</p>&mdash; Bill Hunt (@krues8dr) <a href="https://twitter.com/krues8dr/status/747817026182352896">June 28, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by mlissner** [comment]
> I don't know if the double hamburger with descriptive text is going to help people -- people are really bad at reading words and worse at understanding them. I consistently over estimate people.

Counter point: This is basically what Facebook does, just not with burgers. But they totally use icons + one word, even on their desktop site:

![screenshot from 2016-06-28 09-51-29](https://cloud.githubusercontent.com/assets/236970/16424672/fde1c390-3d15-11e6-8a45-498f4e12ac61.png)

**Comment by arderyp** [comment]
I agree that GitHub's mobile solution is lackluster.  I always use the desktop version on mobile because I often find it difficult/impossible to find what I need with the mobile interface.  Maybe I'm just too used to the full version of the site, but I'm glad to hear I'm not the only one frustrated with the desktop version.

**Comment by mlissner** [comment]
Started work on this today. Some early notes and todos:

 - [ ] Move the search bar from the various places it hangs out to appear only on search pages.
 - [ ] Make new advanced search/product pages for judges, opinions, and oral arguments to live at /judge/, /opinion/ and /audio/
    - [ ] Relink the advanced search link on the homepage to go to the advanced search page.
 - [ ] Update the hamburger menu's contents and make the secondary nav disappear on mobile (though it's possible it can just stay there regardless of screen size).
 - [ ] Update all pages to have the new paradigm.

**Comment by mlissner** [comment]
Oh, and here's an early screenshot:
![screenshot from 2016-08-12 16-52-45](https://cloud.githubusercontent.com/assets/236970/17639970/370e4bc4-60ad-11e6-96a9-997e40d1d9e5.png)

**Comment by mlissner** [comment]
Solved the question of the double hamburger -- turns out that the secondary nav is small enough that it doesn't need a hamburger even down to 480px. If we add another item to it, we'll have to redo the hamburger, but until then, this is what it will look like:

(collapsed)
![screen shot 2016-08-15 at 22 26 43](https://cloud.githubusercontent.com/assets/236970/17688795/66f2ad12-6337-11e6-91f5-55a2a4518430.png)

(expanded)
![screen shot 2016-08-15 at 22 26 55](https://cloud.githubusercontent.com/assets/236970/17688800/787f003a-6337-11e6-8150-b02e35e77959.png)

**Comment by arderyp** [comment]
Looking good

**Comment by mlissner** [comment]
Launched! Closing this issue!
