### ISSUE TITLE
Migrate Courtlistener to Python 3.x

### ISSUE THREAD

**Issue by voutilad** [freelawproject/courtlistener#530]
Didn't see one to track a possibly migration, so I figured I'd create the issue.

Sometime in the next 3 years it would be a good idea to migrate to Python 3.x as the Python 2.7 doomsday clock is ticking: https://pythonclock.org

I'd suggest:
1. Integrate Tox for running tests under multiple Python environments (2.7 and 3.5 at the moment).
2. Identify 3rd party libs that don't have 3.x support and migrate to alternatives. (Probably not many at the moment.)
3. Migrate 2.x-specific code (like print statements) using 2.7's [**future**](https://docs.python.org/2/library/__future__.html).
4. If and when tests are all passing for 3.5, migrate production environment.

**Comment by mlissner** [comment]
At some point I looked into this, but the problem was dependencies. At some point we could also integrate [Unicode Nazi][un]. I have a feeling this upgrade will find a bunch of unicode-related bugs -- I've been bad about it for a long time.

[un]: https://pypi.python.org/pypi/unicode-nazi

**Comment by mlissner** [comment]
Another idea for making this easy is to use type annotations. That'll guarantee that the ins and outs of all our functions are the right types, and should make all the unicode vs. str issues safer.

**Comment by mlissner** [comment]
Another todo:
 - [ ] Remove dependency on `mock`; replace it with `unittest.mock`

**Comment by mlissner** [comment]
I'm closing this. Seems like it's getting done elsewhere (much to my chagrin). Thanks for raising this though, @voutilad.
