### ISSUE TITLE
Make Determination about Cases without Dates

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#533]
There are about 15k cases that we're about to import that lack dates. Right now, we require dates at the database level and this makes our lives very easy, because we can always count on them being there.

When we import these cases, we need to do something. Options:
1. Allow null date fields. This will break a lot of things in the site that expect dates to exist. For example, search results can be ordered by date...well, what happens when there's no date?
2. Make good guesses about the dates. Most of these items have citations, so one option is to look up the item that came before/after it in the reporter, and use the average of those dates. This isn't as bad as it sounds, because it will at least give it an approximate value -- that's _something_! If we do this, we could also add a field to the database called `approximate_date`, which would be `True` if we guessed the date.
   
   I'm leaning towards this option.
3. We could leave theses cases out. Nah.
4. Something else? 

This issue is here for discussion. We'll need to make a decision pretty quickly so we can get this stuff imported.

**Comment by esbranson** [comment]
The case citations within will give an earliest_date and if the earliest of any other case citing it will give a latest_date. These can be used not only for unknown dates but also for any conflicting info about dates. NULL them or whatever if they're not used. Use one, the other, or the average for sorting.

For sorting completely unknown dates, you could use a NULL date value and treat it as an arbitrary date at or before "time immemorial" (given by the Statute of Westminster 1275, ch. 39, as the reign of King Richard I).

**Comment by t10nbaum** [comment]
I agree with approach 2. As long as it is clear that the date is approximate people can make the appropriate assumptions. There can also be a project later on to try and clean up the dates for good.

**Comment by mlissner** [comment]
@esbranson, I like where you're going with using the citation network. I'll see if that's feasible when we get to this, but I have a sinking feeling that the date of the opinion is used in the code to figure out the citations in the text. That might be tweakable though. The thing that comes to mind with this approach is that we won't know what cites an item we're importing, because (1) a lot of these items we're importing don't have citations at all, and (2) if they *do* have a citation, it won't be part of our citation network until *after* it's been imported and the entire network re-processed.

@t10nbaum I think you're right about people being able to make the right assumptions if we show this in our UI somehow. That's a totally good call.

So, I think the final solution will be:

1. Add a boolean field for `date_filed_is_approximate` or something like that.
2. Estimate the dates using a combination of the citation network (as much as possible) and the date of the case before/after the current one in the reporter.
3. Update the UI to display the date as approximate, and add an FAQ explaining what that means.

**Comment by ellliottt** [comment]
What we discussed today:
1) search for date. if you find one, great. if you dont, add to log,
2) when everything is done, we form some predictions based on volume and page.
3) import cases that dont have date using the approximator, and set `approximate_date=True`.

**Comment by mlissner** [comment]
I've added a new field on the clusters called "date_filed_is_approximate".
