### ISSUE TITLE
Add data from Follow the Money to the Judge Database

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#534]
There's a short timeline for this, so I'm hoping to wrap it up quickly. The goal here is to provide a basic link between a judge's profile and the money they've accepted during various campaigns.

There are a few ways to go about this that I've considered, in increasing order of deepness of integration:

 - Simply provide a link to FTM on every judge page.
    - Pros: Easiest. Doesn't add data to our database. Information won't go stale. Requires least knowledge of the FTM APIs (which are complicated). Can serves as a fairly simple first step to gauge interest. Shows all of FTM's information, without us having to decide what's important.
    - Cons: Data is almost impossible for academics to consume -- researchers will need to iterate over the CL Judge DB and then pull data from FTM in a second step, using the FTM APIs.

 - Use the FTM API to pull data into CourtListener for judges, and display it on their pages. Use a cache (probably Redis) to store the data for a period of time.
    - Pros: Information will only be as stale as the cache. Fairly simple way of setting things up that requires very few tweaks to our DB.
    - Cons: Will make judge pages slower when there's a cache miss, since we'll need to hit an external API when it loads. Alternately, this will need to be done in JavaScript, which will make caching (and coding) harder. Data will again be difficult for researchers to consume. Will need to do the front end display work for this information.

 - Use FTM bulk data to have all the information in the CourtListener DB to begin with.
    - Pros: We do the heavy lifting of figuring out the FTM database and APIs for our users. They simply need to understand our API, which should provide a simplified version of the information.
    - Cons: Information will go stale and need to be updated. All of the complication of the above and also the complication of adding a REST API endpoint, and database schemas.

Right now, I'm leaning towards the first option. The simplicity is alluring, and it will allow us to gauge interest. Open to other pros/cons/thoughts.

**Comment by mlissner** [comment]
Some proto-notes:

1. Documentation is [here][1].

2. There's no documented way to look up candidates by name. However, by poking around with the network monitor, I've found these queries that should work fairly well:

    ```text

# Find a candidate in a specific state:
curl 'http://beta.followthemoney.org/metaselect/json/entity.php?t%5B%5D=Candidate&s%5B%5D=MI&y%5B%5D=&name=stephens%2C%20cynthia'
[{"id":"13010085","name":"STEPHENS, CYNTHIA DIANE"},{"id":":stephens cynthia","name":"See All Results..."}]

# Find a candidate by name only:
curl 'http://beta.followthemoney.org/metaselect/json/entity.php?t=Candidate&name=stephens%2C%20cynthia'
[{"id":"13010085","name":"STEPHENS, CYNTHIA DIANE"},{"id":"6513964","name":"STEPHENS WILLIAMS, CYNTHIA (CINDY)"},{"id":":stephens cynthia","name":"See All Results..."}]
```

3. I haven't found any good way to handle ambiguous names. Using the front end, you can pull up a disambiguation screen like this:

    ![screenshot from 2016-07-19 12-13-58](https://cloud.githubusercontent.com/assets/236970/16957453/5e07d7c4-4daa-11e6-8f42-ab4bba4b3384.png)

    But...that screen doesn't have a useful URL.

[1]: http://www.followthemoney.org/assets/FollowTheMoney-API.pdf

**Comment by ellliottt** [comment]
Here is a note on the fields in the bulk dataset I downloaded in May. This list has the field, and then a few examples of the field.

We can match judges on Election_Jurisdiction (the state), General_Office (which gives the type of court), and Candidate (which is "Last, First Middle"). Matching challengers will be trickier, but you can see in the Office_Sought field that sometimes it names the incumbent in the seat they are going for.

I uploaded this data as a zipped CSV in the slack in #courtlistener channel

- Filing_Jurisdiction      ['WV' 'PA' 'IL' 'AL' 'MI']
Filer    ['CHAFIN, LETITIA (TISH)' 'BRODY, ANITA B' 'KARMEIER, LLOYD A', 'INGRAM, KENNETH' 'WORKMAN, MARGARET L']
- Original_Name    ['CHAFIN, LETITIA' 'COMBINED TOTAL OF ALL1988-1989 REPORTS',  'ILLINOIS REPUBLICAN PARTY' 'XXX, AL DEMOCRATIC PARTY' 'WORKMAN, MARGARET']
- Contributor      ['CHAFIN, LETITIA (TISH)' 'COMBINED TOTAL OF ALL1988-1989 REPORTS',  'ILLINOIS REPUBLICAN PARTY' 'ALABAMA DEMOCRATIC PARTY',  'WORKMAN, MARGARET L']
- Type_of_Contributor      ['Individual' 'Non-Individual' 'Other' '407']
- Specific_Business        ['Candidate Contribution' 'No employer listed or discovered',  'Republican Party committees' 'Democratic Party committees',  'Securities, commodities & investment']
- General_Industry         ['Candidate Contributions' 'No Employer Listed or Found' 'Party Committees',  'Securities & Investment' 'Lawyers & Lobbyists']
- Broad_Sector     ['Candidate Contributions' 'Uncoded' 'Party',  'Finance, Insurance & Real Estate' 'Lawyers & Lobbyists']
- Amount   ['1000000.00' '999754.54' '911282.00' '900648.00' '700000.00']
- Date     ['2012-02-01' '1987-12-31', '2004-10-21' '1996-10-24', '2004-10-04']
- Last_Updated     ['2013-10-22' '2012-03-08' '2013-03-19' '2014-05-08' '2012-03-07']
- Type_of_Transaction      ['L' 'DIR' 'I' 'PUB' 'CC']
- Purpose          ['EXISTING LOAN FROM CANDIDATE',  'MONETARY, DIRECT, CANDIDATE DEBT ASSUMPTION' 'LOAN' 'Forgiven Loan']
- City     ['CHARLESTON' nan 'SPRINGFIELD' 'BIRMINGHAM' 'MONTGOMERY']
- State    ['WV' 'UN' 'IL' 'AL' 'MI']
- Zip      [ 25314.     nan  62701.  35203.  36101.]
- In-Jurisdiction          [     1      0      2 181517]
- Candidate        ['CHAFIN, LETITIA (TISH)' 'BRODY, ANITA B' 'KARMEIER, LLOYD A', 'INGRAM, KENNETH' 'WORKMAN, MARGARET L']
- Specific_Party   ['DEMOCRATIC' 'REPUBLICAN' 'NONPARTISAN' 'REPUBLICAN DEMOCRATIC', 'DEMOCRATIC REPUBLICAN']
- General_Party    ['Democratic' 'Republican' 'Nonpartisan' 'Third-Party' 'Unknown']
- Election_Jurisdiction    ['WV' 'PA' 'IL' 'AL' 'MI']
- Election_Year    [2012 1989 2004 1996 2008]
- Election_Type    ['Standard' 'Special' '12106']
- Office_Sought    ['SUPREME COURT-DAVIS SEAT & OPEN SEAT' 'SUPREME COURT-OPEN SEAT', 'SUPREME COURT DISTRICT 005' 'SUPREME COURT-INGRAM SEAT',  'SUPREME COURT-OPEN SEAT & MAYNARD SEAT']
- Election_Status          ['Lost-General' 'Won-General' 'Lost-Primary' 'Won-Retention', 'Won-General Runoff']
- Incumbency_Status        ['Challenger' 'Open' 'Incumbent' 'Unknown' 'J']
- General_Office   ['State Supreme Court' 'Lower Court' 'Appellate Court' '1']
- Status_of_Candidate      ['Lost' 'Won' 'Withdrew' 'Default Winner' 'Unknown']
- Employer         [nan 'SAM BERNSTEIN LAW FIRM PLLC' "MOUNT ST. MARY'S UNIVERSITY", 'STATE OF WEST VIRGINIA' 'BLANK']
- Occupation       [nan 'ATTORNEY' 'TEACHER' 'CANDIDATE' 'PAC']

**Comment by ellliottt** [comment]
we can use the election year in the match of course.

**Comment by mlissner** [comment]
@ellliottt if you don't mind, I'm going to close this one out. If we want to create a new one for adding bulk data, that sounds great to me, but I think having a fresh issue for that is probably good.
