### ISSUE TITLE
Add microdata to person pages

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#541]
There's a newish format for microdata called json-ld that we should start using on the people pages at least. Basically, you take metadata from schema.org, and you make it into JSON objects, which you embed in a `<script type="application/ld+json">`. 

Here's the schema for a person: https://schema.org/Person

If we autogenerate json-ld microdata for all the people in the judge db, I expect Google will like us a whole lot.

There's an example of json-ld on the homepage, though it's not for a Person object.

**Comment by davidxia** [comment]
Working on this now.
