### ISSUE TITLE
Do OCR for RECAP content

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#546]
This should be straightforward, but we need to get it going as soon as possible. All RECAP content needs to have OCR run on it.

**Comment by mlissner** [comment]
OK, this is now running, but speed is going to be a big issue. as anticipated. We're currently getting about 200/hour. We need to get this number pumped much higher.

**Comment by mlissner** [comment]
Current status:

    RECAPDocument.objects.values('ocr_status').order_by().annotate(Count('ocr_status'))
    [{'ocr_status__count': 0, 'ocr_status': None}, 
     {'ocr_status__count': 562580, 'ocr_status': 1},   # Complete
     {'ocr_status__count': 1269139, 'ocr_status': 2},  # Not Necessary
     {'ocr_status__count': 60853, 'ocr_status': 3},    # Failed
     {'ocr_status__count': 334628, 'ocr_status': 4}]   # Needed

**Comment by mlissner** [comment]
It's been 47 hours since the last check in. New numbers:

    RECAPDocument.objects.values('ocr_status').order_by().annotate(Count('ocr_status'))
    [{'ocr_status__count': 0, 'ocr_status': None}, 
     {'ocr_status__count': 609480, 'ocr_status': 1},
     {'ocr_status__count': 1269139, 'ocr_status': 2},
     {'ocr_status__count': 60876, 'ocr_status': 3},
     {'ocr_status__count': 287705, 'ocr_status': 4}]

So, in 47 hours the number needing processing (`4`) has reduced by 46923. That's conveniently 1,000/hour.

There are 287705 remaining to do. At 1,000/hour it should take 12 days. I expect these to get slower and slower though, since we're doing them from shortest to longest.

**Comment by mlissner** [comment]
Another 100 hours, and new numbers:

    [{'ocr_status__count': 0, 'ocr_status': None}, 
     {'ocr_status__count': 705166, 'ocr_status': 1}, 
     {'ocr_status__count': 1269139, 'ocr_status': 2},
     {'ocr_status__count': 60907, 'ocr_status': 3},
     {'ocr_status__count': 191988, 'ocr_status': 4}]

So, another 95k done. Still doing about 1,000/hour. Not bad. Another 9 days or so.

**Comment by mlissner** [comment]
New rate is 642/hour. We're getting into the longer ones, apparently. 164,000 to go.

**Comment by mlissner** [comment]
60k to go! 

    [{'ocr_status__count': 0, 'ocr_status': None}, 
     {'ocr_status__count': 750762, 'ocr_status': 1}, 
     {'ocr_status__count': 1269139, 'ocr_status': 2}, 
     {'ocr_status__count': 146386, 'ocr_status': 4}, 
     {'ocr_status__count': 60913, 'ocr_status': 3}]

**Comment by mlissner** [comment]
122k to go. Things are definitely slowing down. Only 24k in the last 40 hours or so.

    [{'ocr_status__count': 0, 'ocr_status': None},
     {'ocr_status__count': 775089, 'ocr_status': 1},
     {'ocr_status__count': 1269139, 'ocr_status': 2},
     {'ocr_status__count': 60915, 'ocr_status': 3}, 
     {'ocr_status__count': 122057, 'ocr_status': 4}, ]

**Comment by mlissner** [comment]
Another 25k done in the last 45 hours. Rate continues to decline and not much we can do about it.

```
[{'ocr_status__count': 0, 'ocr_status': None}, 
 {'ocr_status__count': 799912, 'ocr_status': 1}, 
 {'ocr_status__count': 1269139, 'ocr_status': 2}, 
 {'ocr_status__count': 60915, 'ocr_status': 3}
 {'ocr_status__count': 97234, 'ocr_status': 4}, ]
```

**Comment by mlissner** [comment]
Another 27k in the last 53 hours:

    [{'ocr_status__count': 0, 'ocr_status': None}, 
     {'ocr_status__count': 826157, 'ocr_status': 1}, 
     {'ocr_status__count': 1269139, 'ocr_status': 2},
     {'ocr_status__count': 60915, 'ocr_status': 3},
     {'ocr_status__count': 70989, 'ocr_status': 4}, ]

**Comment by mlissner** [comment]
47k left to go. Did 23k in the last 45 hours. Estimated date of finishing: 11th or 12th.

**Comment by mlissner** [comment]
12k to go. Did 35k in the last 70 hours. Should finish tomorrow around 11PST!

**Comment by mlissner** [comment]
This appears to be done!

**Comment by brianwc** [comment]
Wow.

**Comment by mlissner** [comment]
For the record, we did OCR on 7,287,501 pages of text in 897,145 documents. Less than I would have guessed.
