### ISSUE TITLE
Pages in OCR output are sorted alphabetically, not numerically

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#548]
Boy, this is a nasty one. When we do OCR, we convert PDF's into one image per page, and number them in `/tmp` like so:

```'/tmp/tess_z82WLN-0.png',
 '/tmp/tess_z82WLN-1.png',
```

Next, we run Tesseract on each image, creating txt files like so:

```
 '/tmp/tess_z82WLN-0.txt',
 '/tmp/tess_z82WLN-1.txt',
```

With that done, we cat all the txt files back together in the proper order with some code like:

```
            for txt_file in sorted(glob.glob('%s*' % tmp_file_prefix)):
                if 'txt' in txt_file:
                    content += open(txt_file).read()
```

Works great, right? Except when we have ten pages or more, the sorted txt files are sorted alphabetically, not numerically, like so:

```
 '/tmp/tess_z82WLN-0.txt',
 '/tmp/tess_z82WLN-1.txt',
 '/tmp/tess_z82WLN-10.txt',
```

This means that any PDF with more than nine pages has OCR output that's out of order. We have an open issue ( #547) to get the page counts of all PDFs, so if we do that, we'll know which need to be fixed. Fixing can only be done by re-running the OCR on these documents.

I have regrets about code written by past @mlissner.

**Comment by ellliottt** [comment]
You could solve this by adding a large number of digits, say 5 digits (up to 10,000 pages) to  the number in the first step -- e.g. `/tmp/tess_z82WLN-00001.png`.

**Comment by mlissner** [comment]
This is now fixed, but the old collection needs to be redone if page count > 9. Looking into that next.

**Comment by mlissner** [comment]
All old opinions with more than 9 pages have been re-processed. (There were about 650 of them.)
