### ISSUE TITLE
Fix HTML/fonts/etc in judge names

### ISSUE THREAD

**Issue by ellliottt** [freelawproject/courtlistener#563]
The judges name slug has HTML encodings that shows up in raw format. The formatting tags should be used or removed. Also, "J." should not be included. Also, colons and other unnecessary punctuation should be removed.

For example, see the italics tags in the judge name here:

https://www.courtlistener.com/opinion/3382084/booths-exr-v-stocktons-exr/

Or the ampersand code here:

https://www.courtlistener.com/opinion/4130786/caldwell-and-wife-v-maxwell-and-wife/

"J." and a colon are included here:

https://www.courtlistener.com/opinion/4064279/cameron-superintendent-v-parker/

See also here:

https://www.courtlistener.com/opinion/4051160/lawson-v-territory-of-oklahoma

**Comment by mlissner** [comment]
This should now be fixed for import-side, and issue #587 will fix it for old stuff.
