### ISSUE TITLE
Resolve Ansible issues discovered during upgrade

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#572]
Our first Ansible upgrade was a disaster on Friday. It was significantly worse than the usual upgrade processes. Ten things went wrong and needed to be resolved and in the end I gave up on Ansible and finished the upgrade manually. 

These things need to be addressed before our next Ansible upgrade:

- [x] The get_vars.sh script couldn't be found by Ansible because Ansible seems to have no concept of relative paths. During the upgrade I fixed this using absolute paths to the script, but this only works if everybody always installs CourtListener in `/var/www/courtlistener`. I think I can live with that as a solution, if we simply tell everybody to use symlinks, but I'd rather have Ansible know where it was, and somehow find the scripts that way.

    (See also: Issue 5)

- [x] Upgrading git using Ansible wasn't possible because of locally modified files on each server:
    - On the main server, the file that was changed was `urls.py`, which I tweaked at the beginning of the upgrade to enable maintenance mode. Solution here is probably to find a better way of doing maintenance mode based on a setting instead of a global URL that blocks all the other URLs. 
    - On the celery task server, the change that created a problem was the celery init.d script, which was symlinked into /etc/init.d. The change in there was to tweak the number of processes it could run since the machine has a lot of horsepower. The fix I put in place here was to copy the celery init script to /etc/init.d, and then revert the file, but I try to use symlinks for these things in general.

- [x] VIRTUALENV_ROOT wasn't configured in the /etc/courtlistener files. Not sure anything needs to be done about this in the future, though I'd enjoy getting rid of the /etc/courtlistener file if possible.

- [x] Seal Rookery was returning an error code instead of returning 0 creating the impression that `update-seals` was failing. I think this is fixed.

- [x] Another relative file was `apache/django.wsgi`. This can probably be fixed same as issue 1.

- [x] Can't start Celery due to what appears to be a permissions error. Need to dig into this further.

- [x] Scorched didn't work to optimize the cores because scorched doesn't work on the old version of Solr, and that's what needed to be optimized. This is fixed by nature of the upgrade being complete.

- [x] The unarchive module didn't have the permissions it needed. I think this is because the `become_user` param from the hosts file was overriding the one from the task itself.

- [x] The `delegate_to` argument to `syncrhonize` froze things up. I think it's because in the hosts file I used `courtlistener.com` as the name of the host, so it was trying to get things from outside the network rather than on the local machine. Need to investigate further.

- [x] $INSTALL_ROOT was still in the solrconfig.xml file. This is weird and surprising b/c it should have been purged and thrown errors during testing. I think this sneaked by because systemd doesn't allow symlinks to startup scripts, so the one I thought I was editing in my code wasn't the one that was being tested. This meant that things that should have broken in testing didn't break until deployment. I think newer systemd now supports symlinks even though they were against it philosophically when I set this up.

All in all: A comedy of crap. I'll be working through these until we have a smooth update process. What a pain.

**Comment by mlissner** [comment]
Another: 

11. Pip wasn't upgrading the modules in the requirements.txt file and needed a tweak to have the `--upgrade` flag.

**Comment by smiller171** [comment]
Found looking for open source Ansible bugs to work on. Ansible does understand relative paths, but in the context of what you are doing, the `get_vars.sh` script isn't being copied to where you expect. I'm going to submit a PR that copies the script to the remote machine first.

**Comment by mlissner** [comment]
I've begun working on these more deligently, including writing a brief spec (subject to change) on the Wiki. 

So far:

 - getvars.yml and related code is purged, replaced by a file called defaults.yml, which contains the default values. If you don't want to use those, you can override them with the `-e` flag to Ansible.

- Seal Rookery is fixed.

- Re Git:
    - In the future init scripts will be copied and tweaked instead of symlinked. This solves the issue with the celery init script.
     - Maintenance mode has been moved to a middleware with settings.

- The apache file is now touched via the new default.yml file.

- I think the celery error is fixed via the addition of a `become` statement.

- I'm ignoring the issue with scorched not working. It didn't prevent the script from moving forward, and I'm fairly certain it's not necessary until after the upgrade is complete (when it will work properly). Chalk this up as a lesson learned.

**Comment by mlissner** [comment]
I'm going to call this done for the moment. I fixed the sync issue by just replacing it with cp. Simple is better, right?
