### ISSUE TITLE
Audit duplicates and dates

### ISSUE THREAD

**Issue by elliottash** [freelawproject/courtlistener#588]
This issue is a synthesis of a range of previous issues:

https://github.com/freelawproject/courtlistener/issues/533 Make Determination about Cases without Dates

https://github.com/freelawproject/courtlistener/issues/552 Evaluate and Fix Opinions with very early dates

https://github.com/freelawproject/courtlistener/issues/570 Imported cases with bad dates use the date of import for month and year

After the columbia corpus is imported, we can audit the whole corpus for potential duplicates and bad dates. In particular, we can compare dates to the reporter volumes and page numbers.

**Comment by mlissner** [comment]
We're going about this another way. Closing.
