### ISSUE TITLE
Make date approximator for cases with uncertain dates in their XML

### ISSUE THREAD

**Issue by elliottash** [freelawproject/courtlistener#590]
We should form a predictor for a case's approximate date based on the volume and page in the caption.

1) Make a big dictionary mapping captions (e.g. 10 U.S. 10) to dates.

2) Check for chronological ordering and flag/fix errors in the data.

3) Form predicted approximate dates for newly imported cases that don't have dates based on the volume and page numbers. For example, find closest pages (before and after) and split the difference.

**Comment by ellliottt** [comment]
The database fields we need to query are all on OpinionCluster. 

Citation fields:

https://github.com/freelawproject/courtlistener/blob/a8addd11ac626d942a6f7a3af322413f3fb7321e/cl/search/models.py#L717-L779

Date filed:

https://github.com/freelawproject/courtlistener/blob/a8addd11ac626d942a6f7a3af322413f3fb7321e/cl/search/models.py#L687

**Comment by ellliottt** [comment]
Here are the fields to select, from search.OpinionCluster:
  
    date_filed
    federal_cite_one 
    federal_cite_two 
    federal_cite_three 
    state_cite_one 
    state_cite_two 
    state_cite_three 
    state_cite_regional 
    specialty_cite_one 
    scotus_early_cite
    lexis_cite
    westlaw_cite
    neutral_cite

**Comment by mlissner** [comment]
This will be roughly:

    clusters = OpinionCluster.objects.only('date_filed', 'federal_cite_one', ...)

**Comment by mlissner** [comment]
This was a fun idea, but we solved it another way. Closing. :)
