### ISSUE TITLE
Normalize Nature of Suit Codes in RECAP Data

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#595]
This should be fairly straightforward. There's a list of all the NOS codes here:

https://www.pacer.gov/documents/natsuit.pdf

And they map neatly to the ones we've got too. These should be normalized.

**Comment by anseljh** [comment]
Maybe this should be a separate Issue, but...

Criminal cases don't have NOS codes. They do get "Cause" information, though, which it looks like is captured in the [RECAP Solr schema](https://github.com/freelawproject/courtlistener/blob/master/Solr/conf/recap_schema.xml#L248). Would be nice to do more with this info, for criminal cases especially.

**Comment by anseljh** [comment]
Well, it's a little more complicated... They're not displayed as "Cause" like on civil dockets, but there is information about "counts". Here's an example from one of my cases.

![image](https://cloud.githubusercontent.com/assets/2075772/20848962/400e8520-b889-11e6-9ef6-abdaae25669a.png)

It could certainly be parsed out, and is super valuable information. I would **love** to be able to search on this info.

**Comment by mlissner** [comment]
The RECAP data I'm working with are XML files on Internet Archive, so I don't know where they get cause information from the HTML. I think it  should be working though. If it's not, we should probably file that as a separate bug.

**Comment by mlissner** [comment]
I just took a look at this. It's pretty sloppy data with something like 1400 different entries in the DB. Lots of normalization would be needed in lots of different ways. Keeping this as a search field may be our best bet for now.

**Comment by mlissner** [comment]
Already I'm seeing the value in these codes being normalized. I bet most of the 1,400 values could be handled with a few simple regexes. Hm.

**Comment by anseljh** [comment]
Is there a way to get a peek at these values?

**Comment by mlissner** [comment]
Yep. Attached is the output from:

    Docket.objects.order_by().values_list('nature_of_suit', flat=True).distinct()

`sort`ed and `uniq`ed.
[nos_values_uniq.txt](https://github.com/freelawproject/courtlistener/files/960076/nos_values_uniq.txt)

Up to 1700 values now. Bah!
