### ISSUE TITLE
There are some edges where citing_case[year] < cited_case[year]

### ISSUE THREAD

**Issue by michaelkkim** [freelawproject/courtlistener#610]
**(citing_case_id, cited_case_id) , (citing_case_year, cited_case_year):**

Specific Example:
(109832, 110069), (1978, 1979)

_Elkins v. Moreno
1978-04-19
https://www.courtlistener.com/opinion/109832/elkins-v-moreno/_
**CITES**
_Toll v. Moreno
1979-04-30
https://www.courtlistener.com/opinion/110069/toll-v-moreno/_

Rest of Problematic Edges:
(1269289 127916), (2001 2003)
(1269289 137001), (2001 2004)
(1269289 137740), (2001 2005)
(1269289 137741), (2001 2005)
(1269289 137750), (2001 2005)
(1269289 145903), (2001 2009)
(1269289 149008), (2001 2010)
(1291060 145921), (2008 2009)
(1291423 205788), (2008 2011)
(1752435 95083), (1898 1899)
(1860073 145768), (2006 2007)
(1992930 145657), (2005 2006)
(1993060 145926), (2006 2008)
(1993275 145744), (2006 2007)
(1993275 145767), (2006 2007)

**Comment by mlissner** [comment]
Is this a dup of #557?

**Comment by michaelkkim** [comment]
Ah, yes it is!

**Comment by michaelkkim** [comment]
It seems like that's the case!

The bulk data might've been fixed since I last downloaded it, but it seems that this problem might still be present.

**Comment by mlissner** [comment]
Yeah, issue #557 isn't resolved. Closing here and we can focus on the other issue.
