### ISSUE TITLE
Upgrade Ubuntu to 16.04 for improved security and whatnot

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#616]
This issue keeps track of known issues and simplifications that a newer version of Ubuntu will bring us. 

Simplifications:

 - [ ] Our current version of OpenSSL (1.0.1f) is old, and doesn't support cross-signed SSL certificates. As a result, we have to do [weird gymnastics in Juriscraper][gym]. When we upgrade, we can remove the gymnastics.

Known Issues:

 - None yet!

[gym]: https://github.com/freelawproject/juriscraper/blob/1df70fa9cb5a4c03f670a7a17c7f1975d22b6325/juriscraper/pacer/utils.py#L116-L130

**Comment by voutilad** [comment]
We could easily cut a version of the FreeLawMachine based off 16.04 and see if the tests work. Would probably help illuminate initial issues.
