### ISSUE TITLE
SCDB link broken

### ISSUE THREAD

**Issue by idc9** [freelawproject/courtlistener#618]
the link to the SCDB is broken for these two cases

https://www.courtlistener.com/opinion/106398/hohensee-v-news-syndicate-inc/
https://www.courtlistener.com/opinion/219731/united-states-v-juvenile-male/

e.g. http://scdb.wustl.edu/analysisCaseDetail.php?cid=1961-079-01 does not pull up a case in SCDB

**Comment by mlissner** [comment]
Fixed. Thanks.
