### ISSUE TITLE
CourtListener N-Gram Viewer

### ISSUE THREAD

**Issue by ellliottt** [freelawproject/courtlistener#622]
We should do an analogue to Google N-grams for CourtListener. You could select jurisdictions and look at how relative frequencies of words and phrases have  evolved over time.

Here is an example I have done using state session laws and state supreme courts:
http://textlab.econ.columbia.edu:8081/plot/deterrence,rehabilitate,retribution

Here is Google N-grams:
https://books.google.com/ngrams/graph?content=deterrence%2C+retribution%2C+rehabilitation%2C+incapacitation&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Cdeterrence%3B%2Cc0%3B.t1%3B%2Cretribution%3B%2Cc0%3B.t1%3B%2Crehabilitation%3B%2Cc0%3B.t1%3B%2Cincapacitation%3B%2Cc0

**Comment by mlissner** [comment]
@ellliottt are you aware that we're working on a grant for this as of yesterday? Because @Colinstarger, @jraller and I are. This is too weird if not.

**Comment by mlissner** [comment]
Oh, also, see: #286

**Comment by ellliottt** [comment]
That's an amazing coincidence!

**Comment by ellliottt** [comment]
Mike and I discussed this project some more today, here are a few brief notes

- SOLR can compute quick document frequencies for words and phrases. We could have another table with the case lengths, and sum those to get the denominator to obtain relative frequencies. Then we could do something almost identical to the coverage visualizer (https://www.courtlistener.com/coverage). This would be easy to setup and would have fast querying.
- What do you get from adding n-grams? Part of speech tags is the obvious one, so you could filter on just noun phrases for example. You could represent a case as a sparse postgres arrays(with n-gram frequencies where they appear and NULL otherwise).
- More long-term: compute syntactic parses and extract subject-verb-object pairs.

**Comment by mlissner** [comment]
Well, we didn't get the grant for this. Back to the drawing board....

**Comment by mlissner** [comment]
This got done by the case.law folks: https://case.law/trends/?q=bear%20arms

**Comment by Colinstarger** [comment]
And they did a real nice job! Looks great.

This was fun (in a nerdy way)
https://case.law/trends/?q=criminal,%20plaintiff,%20state,%20judgment

This sort of shows that it works as expected
https://case.law/trends/?q=slave,%20fourteenth%20amendment

On Jul 8, 2019, at 5:05 PM, Mike Lissner <notifications@github.com<mailto:notifications@github.com>> wrote:

[EXTERNAL EMAIL]


This got done by the case.law folks: https://case.law/trends/?q=bear%20arms

**Comment by mlissner** [comment]
Yeah, I suppose we may as well close this one. Good idea. Too slow.
