### ISSUE TITLE
Load in bankrupcty-judges.csv data into people DB

### ISSUE THREAD

**Issue by elliottash** [freelawproject/courtlistener#627]
We received some biographical data on 155 bankrupcty judges (bankrupcty-judges.csv). We could load these guys into the people DB and match their opinions if possible.

**Comment by mlissner** [comment]
Excuse me?! That's killer news!

**Comment by mlissner** [comment]
Turns out the data in this CSV only has the last name of the judge. @ellliottt is going to try to get RAs to fill in the missing data, then we'll import.

**Comment by mlissner** [comment]
We got this data another way and now have bankruptcy judges in the DB.
