### ISSUE TITLE
Upgrade sorting algorithm to citerank or similar

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#643]
@idc9 has been doing some great work testing the relevancy of various algorithms and will be publishing a paper on the topic soon. We're currently using PageRank as one of our key methods, but his research is showing that other algos are better. 

We should:

 - Implement #642, so that we can measure if this is an actual improvement
 - Record some results for a week or so (baseline)
 - Swap in the change to the ranking code
 - Save old PR file
 - Calculate new results and swap them in
 - Wait a week or so 
 - Compare results

**Comment by idc9** [comment]
I'll post a draft of the paper as soon as the journal gives us the ok. The basic problem with PageRank is that it favors older cases in a directed acyclic network. Most citations, however, go to more recent cases (I think the median citation age is 14 years within SCOTUS).

There are a lot of vertex centrality metrics we could try, but we probably want to start with some of the most simple ones. Here are the first few I would consider.

- time truncated in-degree

in-degree = how many citations a case has received. Time truncated in-degree = how many citations a case has received in the past T years (e.g. T = 10, 20, etc). 

This is intuitive, easy to compute and takes care of the recency bias.

- [CiteRank](http://www.sciencedirect.com/science/article/pii/S1751157706000034)

CiteRank is a time biased version of [personalized PageRank](https://www.r-bloggers.com/from-random-walks-to-personalized-pagerank/). This is easy to compute and may fix the age bias in PageRank in a DAG. The original CiteRank paper uses an exponential decay for the jump probabilities -- I suggest using a polynomial decay (e.g. 1/(1 + age)^alpha).

- either total degree or PageRank on the undirected network

Our paper found that out-degree (number of cases a given case cites) may be an indicator of case importance. This effect might be related to stare decisis (e.g. see the discussion of the Warren court in [this paper](http://fowler.ucsd.edu/authority_of_supreme_court_precedent.pdf)).

Also PageRank on the undirected network would no longer be biased in favor of older cases.

- [Authorities scores](https://en.wikipedia.org/wiki/HITS_algorithm)

The paper mentioned above also found that the authorities scores was a good measure of legal importance (and are fast to compute). The possible downside of authorities is a) they don't take time into account and b) they don't take the aforementioned out-degree effect into account.

**Comment by mlissner** [comment]
I have more about this in Slack DMs, but also, this paper has a lot of research about which algo is best: https://scholarship.law.unc.edu/cgi/viewcontent.cgi?referer=&httpsredir=1&article=5717&context=nclr

**Comment by mlissner** [comment]
Closing for: #4436, which I believe is the spiritual successor to this one.
