### ISSUE TITLE
Add "A Free Law Project Initiative" or similar tagline to CourtListener's header

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#647]
We have something like this in the footer, but it's been pointed out to me that we need something in the header. We have a donate button — fine — but actual attribution would probably be good too. I see this as sitting directly below the CourtListener logo in all screen sizes where it fits (mobile might not have space for it).

A couple options (in every instance FLP is a link):

1. A Free Law Project initiative.
1. An initiative of Free Law Project, a 501(c)(3) non-profit.
1. By Free Law Project
1. By Free Law Project, a 501(c)(3) non-profit.
1. From Free Law Project
1. From Free Law Project, a 501(c)(3) non-profit.
1. Sponsored by the non-profit Free Law Project (this is in the footer currently)

I think I'm leaning towards numbers 2 and 6? Thoughts welcome.

**Comment by mlissner** [comment]
I like that 6 has FLP earlier in the sentence. Apparently that makes a difference to people.

**Comment by abagwell** [comment]
Do you mind if I give this one a try?

**Comment by mlissner** [comment]
Not at all, @abagwell! It'd be great if you did.

Something else that might be worth re-visiting while you're in this area is the logo itself. Right now when users load the page we send them both the [mobile img][m] and the [regular one][r]. It's only a small thing (they're cached after first page load), but there might be a way of doing this properly so that people only load the one their viewport would support. I think it was the HTML `<picture>` tag, maybe?

Anyway, that's all a bit outside of scope, but if you're able to just add the tagline, that'd be great too.

[m]: https://www.courtlistener.com/static/png/logo-initials-only.png
[r]: https://www.courtlistener.com/static/png/logo-large.png

**Comment by abagwell** [comment]
I can check that out too. 

I have a question about the base.html that's being extended. Where is that located?

**Comment by mlissner** [comment]
https://github.com/freelawproject/courtlistener/find/master

**Comment by abagwell** [comment]
ok thanks!

**Comment by mlissner** [comment]
Thanks for this, @abagwell. Great stuff.

I made a couple tweaks to this that you can see in the commit log, but this was very helpful! It'll go live in the next deployment, which usually happens every day or two.

The changes I made:
 - The text says "From Free Law Project." on tiny screens and says the full sentence on big screens.
 - Tweaked the CSS to make it a bit tighter.
