### ISSUE TITLE
Opinion Parse Hiccup

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#652]
In White v. Pauly (https://www.courtlistener.com/opinion/4374579/white-v-pauly/), the opinion parser did not pick up Ashcroft v. al-Kidd. This is strange because the citation looks fine -- nothing unusual -- in the text, to wit:

Today, it is again necessary to reiterate the longstand-
ing principle that “clearly established law” should not be
defined “at a high level of generality.” Ashcroft v. al-Kidd,
563 U.S. 731, 742 (2011). 

Worth checking? I am going to add in the cite by hand for now.

**Comment by mlissner** [comment]
Looks like Ashcroft didn't have 563 U.S. 731 as a citation somehow. I've updated it so it'll be fixed in the future.
