### ISSUE TITLE
Run and monitor PACER downloader

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#657]
This will be a big task, and I'm going to use this issue to track progress/journal the experience.

**Comment by mlissner** [comment]
So far, things are coming along *OK*. So far we've downloaded 21k items since we kicked it off yesterday. That's not bad, but if we assume there are 20M items, it will take another 1000 days to finish. That's not nearly fast enough, but I'm heartened by the fact that:

1. We're not using all of our available servers (I need to fix this).
2. The citator is running right now too. 

Ultimately though, I need an order of magnitude speed improvement to get all this, so I'm going to have to do some performance work. I was hoping that wouldn't be needed, but the odds of getting this right the first time were pretty low to be sure.

**Comment by mlissner** [comment]
Just heard from a PACER admin in NJ, who is concerned about us DDOS'ing them, but I don't think it's us.

**Comment by voutilad** [comment]
Do they need help identifying FLP traffic?

**Comment by mlissner** [comment]
I gave him our IP. He's looking into it and supposed to get back to me, but it sort of sounded like he was in "put out a fire" mode. Here's a funny theory: Somebody from another org that wanted to do a big scrape saw our blog post yesterday and is using us for cover. Nah.

**Comment by mlissner** [comment]
Now at 4k/hour to Internet Archive. I didn't change anything, so I don't know what to make of this, but it's welcome.

**Comment by mlissner** [comment]
I'm rearchitecting everything for better performance, reliability, and visibility in https://github.com/freelawproject/courtlistener/issues/662.

**Comment by mlissner** [comment]
So, stage one is claiming that it's done after finding about 3.3M items. I'm analyzing by making histograms for every court and will be sharing those here if possible. Here's a histogram across all courts:

![all_courts](https://cloud.githubusercontent.com/assets/236970/24682046/9ee9133e-194c-11e7-8b2e-e5f0e2cbd746.png)

**Comment by mlissner** [comment]
Stage two is underway and we're downloading PDFs at an insane rate. Right now there are 3,417,678 items to process. I'll post again in 30 minutes so we can see the rates we're getting.

**Comment by mlissner** [comment]
OK, about 30 minutes have passed and we're at 3,413,544. So that's about 8k/hour including me futzing around with some bits and pieces. That puts us at about 17 days for the download stage.

**Comment by mlissner** [comment]
This guy is up and running again after some additional debugging. Now at about 14k/hour running on two servers.

**Comment by mlissner** [comment]
OK, so first push of this is complete! What that means is that every item has attempted to run. The bad news, however, is that there are about 800k items that still need to be resolved in one way or another. A lot of these reflect items that we already have, so they can be ignored, but here's the best stats I've got so far:

```python

PACERFreeDocumentRow.objects.all().count()
880557

PACERFreeDocumentRow.objects.filter(error_msg__startswith='Found the item').count()
108439

PACERFreeDocumentRow.objects.filter(error_msg__contains='duplicate key value violates').count()
370

(PACERFreeDocumentRow.objects
     .exclude(error_msg__startswith='Found the item')
     .exclude(error_msg__contains='duplicate key value violates')
     .order_by().values('error_msg').annotate(c=Count('error_msg')))

[{'c': 745295, 'error_msg': u'Unable to get PDF for PACERFreeDocumentRow object'}, {'c': 3, 'error_msg': u''}, {'c': 26450, 'error_msg': u'Unable to create docket for PACERFreeDocumentRow object'}]
```

So big picture, we've got:
 
 - 745k items that say they were simple unable to download. I think these are from before the code was automatically getting a fresh login token on a regular basis. 

 - 108k that already appear to be in the DB ("Found the item already in the DB with document_number: 3 and docket_entry: <DocketEntry:173659...")

 - 26k unable to create docket. Don't know what these are.

 - 370 duplicate key violations.

 - 3 items without error messages.

I've also got errors in my inbox that need investigation. I'll get those sorted out next, before my inbox decides to delete them (this isn't ideal).

**Comment by mlissner** [comment]
I've taken care of the stuff in my inbox via a new repo that can parse celery emails (sort of). That was the first priority b/c I needed to get it done before Gmail auto-deleted the errors. Next up is getting the 745k items going again.

**Comment by mlissner** [comment]
The 745k items are now downloading as well.

**Comment by mlissner** [comment]
And....these are done! There are now 142k remaining, which, it appears, I'll be delving into today.

**Comment by mlissner** [comment]
I've been occupied working on PACER parsers for the past several weeks in anticipation of needing to download and parse some dockets for GSU, but I am returning to this task today. Time to get reacquainted with the system.

First of all, I've got $124.80 due from my account. I note this b/c I need to know if the Free Document downloader is causing any increases. All of the existing dues are from testing RECAP parsers.

Second of all, here are the latest numbers:

    PACERFreeDocumentRow.objects.all().count()
    142062

    PACERFreeDocumentRow.objects.filter(error_msg__startswith='Found the item').count()
    108530

    (PACERFreeDocumentRow.objects
     .exclude(error_msg__startswith='Found the item')
     .exclude(error_msg__contains='duplicate key value violates')
     .order_by().values('error_msg').annotate(c=Count('error_msg')))
    [{'c': 2267, 'error_msg': u'Unable to get PDF for PACERFreeDocumentRow object'}, {'c': 30894, 'error_msg': u'Unable to create docket for PACERFreeDocumentRow object'}]

So....

 - There are 142k that didn't work.
 - 109k were already in the DB
 - 2267 were unable to get a PDF for some reason
 - 31k were unable to create a docket

Let's dive in, starting with the ones that couldn't create a docket.

**Comment by mlissner** [comment]
It looks like at least one issue that's coming up is duplicate dockets. I don't know what caused these, but you can see them for example, if you look at PACERFreeDocumentRow number 599, which pulls back three dockets all with the same case name, pacer_case_id, and docket_number:

```
In [20]: three = Docket.objects.filter(Q(docket_number=example.docket_number), court=example.court_id)

In [21]: three
Out[21]: [<Docket: 4663840: United States v. Johnson>, <Docket: 4663839: United States v. Johnson>, <Docket: 4663838: United States v. Johnson>]

In [22]: for t in three:
   ....:     print "https://www.courtlistener.com%s" % t.get_absolute_url()
   ....:     
https://www.courtlistener.com/docket/4663840/united-states-v-johnson/
https://www.courtlistener.com/docket/4663839/united-states-v-johnson/
https://www.courtlistener.com/docket/4663838/united-states-v-johnson/
```

Looks like it's time to take care of the dups. Should be fairly easy, and then we can go and get these items again.

**Comment by mlissner** [comment]
The dups are resolved in #705. It was a pain, but data munging usually is. The database is much nicer though now. I think tomorrow we can kick off these downloaders again.

**Comment by mlissner** [comment]
OK, after another big run, we're down to about 11k errors:

```
In [69]: PACERFreeDocumentRow.objects.filter(error_msg__startswith="Unable to complete data").count()
Out[69]: 369

In [70]: PACERFreeDocumentRow.objects.filter(error_msg__startswith="Unable to get PDF").count()
Out[70]: 408

In [71]: PACERFreeDocumentRow.objects.filter(error_msg__startswith="Unable to create docket").count()
Out[71]: 11186
```

**Comment by mlissner** [comment]
All of these items are resolved in the other three tickets. CLOSING.
