### ISSUE TITLE
Duplicate SCOTUS case

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#667]
Nothing new here - another duplicate. Looks like the first one in this search is that one that is cited to.

https://www.courtlistener.com/?q=standing&type=o&order_by=score+desc&case_name=lexmark&stat_Precedential=on&court=scotus

**Comment by mlissner** [comment]
Thanks. Fixed in favor of the more popular case. It had a fixed hyphenation and a fixed citation. Was posted an hour after the other.
