### ISSUE TITLE
SCOTUS Case Appears to be Missing

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#682]
It seems that CL does not have Shaw v. Hunt, 517 U.S. 899 (1996) aka Shaw II. This search shows that the case is cited many times in other CL SCOTUS cases -- yet there is no hyperlink anywhere:

https://www.courtlistener.com/?q=%22517+U.S.+899%22&type=o&order_by=score+desc&stat_Precedential=on&court=scotus

I searched a number of different ways and was unable to find this case. Not sure why. It is out there... https://supreme.justia.com/cases/federal/us/517/899/case.html

**Comment by mlissner** [comment]
Alas, a duplicate of #336. I could really use help looking into that/addressing that.
