### ISSUE TITLE
Duplicate Alleyene

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#686]
There's another duplicate lurking. Looks like the first one in this search is the good one.
https://www.courtlistener.com/?q=&type=o&order_by=score+desc&case_name=Alleyne&stat_Precedential=on&court=scotus

**Comment by mlissner** [comment]
Fixed with the old PDF saved in our archives in case we need it. They fixed two typos.

This:

> TOMAYOR, and KAGAN, JJ., joined. SOTOMAYOR, J., filed a concurring in

Became:

> TOMAYOR , and KAGAN , JJ., joined. SOTOMAYOR , J., filed a concurring

...removing the word "in".

And this slightly more substantive change:

>   Accordingly, we vacate the Sixth Circuit’s judgment

Became:

>   Accordingly, we vacate the Fourth Circuit’s judgment

**Comment by mlissner** [comment]
On a different note, I like the idea of using Github issues for this. It keeps a record of the decision making process and observations.
