### ISSUE TITLE
CL Not Picking Up SCOTUS cases after 6/5/17

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#699]
It seems like the scrapers haven't picked up the 17 or so SCOTUS cases handed down since 6/5/17. I tried initially to access through the visualizer, but then checked for the names in the regular CL DB and came up blank. The scraper caught cases 1-47 on this page (https://www.supremecourt.gov/opinions/slipopinion/16) but I can't see 48-64. Note cases are listed with the latest on top on the SCOTUS site.

**Comment by mlissner** [comment]
This should be fixed in 1.4.25, which is now deployed.
