### ISSUE TITLE
Add webhooks to RECAP upload endpoints

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#703]
The RECAP fetch endpoints are nearly done, so that's great. What's missing now is a way for users of the API to learn when their item has been processed, and take action once it has. The right way to solve this problem is with webhooks.

A webhook could work as follows:

1. A user posts a new docket to the API.
2. The item is added to our queue.
3. We eventually process the item.
4. We send a POST request to a URL configured by the user, to notify them of the completion.
    - If this endpoint doesn't work, we retry X number of times, then send an email saying things are broken.
    - If the endpoint works, the user can parse the POST request, and parse the data they need.

Stripe is the best example of webhooks I've ever seen, including inspectable logs of failures, but I don't think we'll be able to achieve that level of quality. 

To do this right, we'll also want to add a configuration section to the API settings, and add documentation to the API docs.

Still, we can go live with these endpoints without having to have these webhooks ready.

**Comment by johnhawkinson** [comment]
> The right way to solve this problem is with webhooks.

Doing so means the user requires a persistent HTTP server capable of accepting the webhook. Is that really realistic? It doesn't seem like something most RECAP clients would have.

**Comment by mlissner** [comment]
The plan is that the API will be used by servers.

**Comment by albertisfu** [comment]
@mlissner What do you think about the following structure for this webhook event:

```
{
   "payload":{
      "id":803712,
      "court":null,
      "docket":null,
      "recap_document":221797284,
      "date_created":"2023-01-06T09:06:23.854208-08:00",
      "date_modified":"2023-01-06T09:06:24.760189-08:00",
      "date_completed":"2023-01-06T09:06:24.760078-08:00",
      "status":2,
      "request_type":2,
      "message":"Successfully completed fetch and save.",
      "pacer_case_id":"",
      "docket_number":"",
      "de_date_start":null,
      "de_date_end":null,
      "de_number_start":null,
      "de_number_end":null,
      "show_parties_and_counsel":true,
      "show_terminated_parties":true,
      "show_list_of_member_cases":false
   },
   "webhook":{
      "version":1,
      "event_type":3,
      "date_created":"2022-12-28T14:21:40.855097-07:00",
      "deprecation_date":null
   }
}
```

The `payload` key would be based on the `recap-fetch` API, since every fetch request is handled independently we'll also send one event for every fetch request completed.

**Comment by mlissner** [comment]
Yep! :shipit:
