### ISSUE TITLE
Visualizer Crashes Making This Map

### ISSUE THREAD

**Issue by Colinstarger** [freelawproject/courtlistener#706]
My RA reported this error two weeks ago. She duplicated it last week. And I duplicated it just now, so I don't think it is a passing thing. We get the "Woah. What happened? It appears the site is having an error. We've been automatically alerted, and we will work to resolve it as soon as possible." error when we:

(1) Create a new network. In "First Case", select Endrew F. v. Douglas County School. (Type "Endrew" and you're there).
(2) In "Second Case" chose from the "cases cited" dropdown "Board of Ed. v. Hendrick Hudson Central School"...
(3) Click "Make this Network" and error appears.

Not sure if I can help debug this on my end...

**Comment by mlissner** [comment]
I see the error:

> UnicodeEncodeError at /visualizations/scotus-mapper/new/

> 'ascii' codec can't encode character u'\u2013' in position 43: ordinal not in range(128)

This means that one of English words involved in making this viz (like the case name, for example) has a character other than those found on English keyboards, and I didn't handle it properly. 

The easy solution is sometimes to find and fix the word, but the right solution is to handle it properly in the code.

**Comment by mlissner** [comment]
I think this is fixed, @Colinstarger. Please reopen this issue if it is not.
