### ISSUE TITLE
Add new field called date_updated

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#735]
We have a gazillion dates on the Docket object, but none that says just when it was last updated via RECAP or a crawler. We should have that. The field we have now is date_last_filing, which we get from PACER's Docket History report, if anybody ever uses that page. 

The problem is that nobody seems to use that page, so the date_last_filing field is pretty useless. I *think* it can be removed, and replaced with a field that aims to represent when the docket was last uploaded.

So:

 - [ ] Add new date_last_upload field to the Docket
 - [ ] Populate it using the highest date filed value for the docket entries on that docket or with the date_last_filing field, whichever is higher. 
 - [ ] Delete the date_last_filing field, and replace it in places like the API and wherever else it appears in CourtListener.
 - [ ] Update the RECAP extensions to use the date_last_updated field instead of the date_last_filing field.

That *ought* to work. Note also that we *do* have a date_modified field, but it's not super useful because it's incremented every time the docket is viewed due to the view counter on the Docket.

**Comment by mlissner** [comment]
I took a different approach here. The main issue was that we couldn't trust the date_modified field because it was getting changed every time somebody incremented a view_count, which happened every time a page loaded. So...if somebody loaded a page, our date_modified field would get bumped. 

This wasn't ideal, so I just tweaked things so that no longer happened. I think this should solve the root issue without the complexity of the solution proposed above.

**Comment by johnhawkinson** [comment]
So, the result is the date_modified field is now ambiguous. Prior to the change, it means one thing (mostly useless), and after the change it means another (actual time of modification)?

So anyone interpreting the field needs to know that values prior to Sept. 29, 2017 are different and represent merely an upper bound?

**Comment by mlissner** [comment]
The final step is to iterate over any docket with a view_count > 0, and to reset their date_modified fields. We'll get a (very) close approximation of the correct value by iterating over the docket_entries associated with them, and finding the highest date_modified field on those.

So:

1. Load a docket
2. Find the highest date_modified field on any docket_entry object associated with it.
3. Update the docket with that value

I expect this will take some time to run. The only thing I can see this missing is if somebody ran a docket report, got *only* the party information, and uploaded that to RECAP. That's a pretty narrow corner case.

**Comment by mlissner** [comment]
It's done.
