### ISSUE TITLE
I'm not an attorney

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#736]
A CL party search for "John A. Hawkinson" (in quotes) returns 3 cases where I appear _pro se_. The first of which is [Lunn v. Smith](https://www.courtlistener.com/docket/6125037/lunn-v-smith/) (although that URL is kinda useless since the listing in question only appears in the search result, not on the docket page (presumably that's being worked on separately). It says:

```
Assigned To: Indira Talwani
Parties: Steven W. Tompkins, Secretary John F. Kelly, Sreynuon Lunn, Yolanda Smith, Christopher Cronen, John Hawkinson, John A. Hawkinson, Thomas D. Homan
Attorneys: Kim B. Nemirow, John Hawkinson, Kathleen A. Connolly, Adriana Lafaille, Shivan Sarin, John A. Hawkinson 
```

Ignoring the fact that I appear both with and without a middle initial, I appear in the party list and also in the attorney list. This is incorrect.

This is probably a longstanding issue. The [IA page for this docket](http://ia601509.us.archive.org/28/items/gov.uscourts.mad.189311/gov.uscourts.mad.189311.docket.html) has:

**Parties**

Represented Party | Attorney & Contact Info
-- | --
... | ...
Yolanda Smith / Defendant / Superintendent of Suffolk County House of Correction | Kathleen A. Connolly / U.S. Department of Justice, Civil Division, Office of Immigr / Ben Franklin Station / P.O. Box 868 Washington, DC 20044 / (202) 305-8627 / Email: kathleen.a.connolly@usdoj.gov / LEAD ATTORNEY / ATTORNEY TO BE NOTICED
… | …
John A. Hawkinson / Intervenor | John A. Hawkinson / Cambridge Day / Box 397103 / Cambridge, MA 02139 / 617-797-0250 / Email: jhawk@mit.edu / PRO SE

But this is wrong. I'm not an attorney and PACER never said I was. It does indeed distinguish. Here's the PACER party report (same as docket report party section):

**Parties**

 x  | x  |  x
-- | -- | --
**Christopher Cronen** / Director, United States Immigration and Customs Enforcement, Boston Field Office / / Added: 05/22/2017 (Defendant) | represented by | **Kathleen A. Connolly** / U.S. Department of Justice, Civil Division, Office of Immigr / Ben Franklin Station / P.O. Box 868 / Washington, DC 20044  / (202) 305-8627 / kathleen.a.connolly@usdoj.gov / Assigned: 05/26/2017 /  LEAD ATTORNEY / ATTORNEY TO BE NOTICED
**John A. Hawkinson** / Box 397103 / Cambridge, MA 02139 / 617-797-0250 / Added: 08/21/2017 / (Intervenor) / PRO SE

That is, I do not appear in the third column nor am I prefaced with "represented by."
So RECAP/IA/CL should not sugggest that I am. Flattering that it is :)

**Comment by johnhawkinson** [comment]
Oops. It turns out the Parties report and the Docket report handle this differently, and the Docket report suggests I am an attorney. CM/ECF bug (wart?) then. 

_"Let's make a github project for CM/ECF and start opening issues just for fun!"_

Specifically it has:


x | x | x
-- | -- | --
 
Defendant
Christopher Cronen Director, United States Immigration and Customs Enforcement, Boston Field Office | represented by | Kathleen             A.              Connolly                                           (See above for address) LEAD ATTORNEY ATTORNEY TO BE NOTICED
 
Intervenor
John Hawkinson | represented by | John Hawkinson P.O. Box 397103 Cambridge, MA 02139-7103 617-797-0250 Email: jhawk@mit.edu PRO SE
 

I suppose one could argue that CL should parse out ATTORNEY TO BE NOTICED and PRO SE, but maybe it's better just to change the heading to "Represented by:" instead of "Attorneys:"

I almost closed this issue but I'll let someone else do so instead. I won't be offended by summary closure, though, and chagrined at my error.

**Comment by mlissner** [comment]
Ever tricky, PACER is. I guess we could tweak things everywhere to use "represented by", but that doesn't really feel right. For example, then we end up with a table somewhere named `representers` or some junk. Attorney feels like the right semantics for the most part. 

Maybe the trick is to throw an asterisk or a explanation in somewhere that explains this?

**Comment by saizai** [comment]
@mlissner I think it's intractable. I know for certain that there are cases with attorneys acting pro se.

As far as I know there's nothing on the docket from which you could tell.

**Comment by mlissner** [comment]
Agreed. Closing.
