### ISSUE TITLE
8th Circuit docket report link busted?

### ISSUE THREAD

**Issue by anseljh** [freelawproject/courtlistener#741]
I'm on https://www.courtlistener.com/docket/4139062/united-states-v-kirk-cottom/ and click on the "View on PACER" button. This leads to https://ecf.ca8.uscourts.gov/cgi-bin/DktRpt.pl?16-1050, which gives a 404.

**Comment by mlissner** [comment]
Hm, this does not surprise me. The appellate data from RECAP was quite messy. I'll take a look and see if I can do anything better with this.

**Comment by mlissner** [comment]
This looks like it's probably a better link that we can use on appellate PACER:

https://ecf.ca8.uscourts.gov/n/beam/servlet/TransportRoom?servlet=CaseSummary.jsp&caseNum=16-1050&incOrigDkt=Y&incDktEntries=Y

It even gives you a "this link will cost money" warning that you have to click through before the page loads. I think we can probably generate those links.

**Comment by mlissner** [comment]
Just tested with U.S. v. Kirk Cotton. Looks good to me.
