### ISSUE TITLE
Replace google-cloud dependency with something more specific

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#743]
Right now we require the `google-cloud` package. It, in turn, requires a bunch of other google-cloud-* packages that we don't even use. Today one of those packages crashed Celery making me a bit insane for a bit. 

According to https://github.com/GoogleCloudPlatform/google-resumable-media-python/issues/42#issuecomment-339085731, it's strongly recommended not to install google-cloud, and to instead use more specific packages. I'm down with that, and it would have prevented yesterday's crash.

**Comment by dhermes** [comment]
> it would have prevented yesterday's crash

That's not likely true if you had still depended on `google-cloud-storage`.

**Comment by mlissner** [comment]
Ah, good point! Well, I can dream. Still, best to lower our profile for future issues.

**Comment by mlissner** [comment]
This one bit us again today, so I'm taking a stab at getting it fixed. Unfortunately, it's really quite a pain to remove all the dependencies that google-cloud pulled in. `pip` doesn't provide any sort of recursive uninstall utility, so the only way to recursively get a list of all the dependencies is to start with the `google-cloud` package and run:

    for dep in $(pip show somepackage | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done

That creates a newline delimited list of the dependencies for `google-cloud`. Using that and some regexes in my text editor, I'm able to create horrible commands like:

    for dep in $(pip show cachetools | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show dill | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show enum34 | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show future | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show futures | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show gapic-google-cloud-datastore-v1 | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show gapic-google-cloud-error-reporting-v1beta1 | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show gapic-google-cloud-logging-v2 | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-api-core | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show googleapis-common-protos | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-auth | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-bigquery | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-bigtable | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-core | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-datastore | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-dns | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-error-reporting | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-firestore | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-language | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-logging | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-monitoring | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-pubsub | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-resource-manager | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-runtimeconfig | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-spanner | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-speech | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-storage | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-trace | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-translate | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-videointelligence | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-cloud-vision | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-gax | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show google-resumable-media | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show grpc-google-iam-v1 | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show grpcio | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show oauth2client | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show ply | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show protobuf | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show proto-google-cloud-datastore-v1 | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show proto-google-cloud-error-reporting-v1beta1 | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show proto-google-cloud-logging-v2 | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show psutil | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show pyasn1 | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show pyasn1-modules | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show requests | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show rsa | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show setuptools | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done && for dep in $(pip show six  | grep Requires | sed 's/Requires: //g; s/,//g') ; do echo $dep ; done

Which...if you're still with me, generates a list of all the dependencies for google-cloud, three levels deep. I repeated this process as many times as it took to stop getting more dependencies. The final list is:

```
cachetools
dill
enum34
future
futures
gapic-google-cloud-datastore-v1
gapic-google-cloud-error-reporting-v1beta1
gapic-google-cloud-logging-v2
google-api-core
googleapis-common-protos
google-auth
google-cloud-bigquery
google-cloud-bigtable
google-cloud-core
google-cloud-datastore
google-cloud-dns
google-cloud-error-reporting
google-cloud-firestore
google-cloud-language
google-cloud-logging
google-cloud-monitoring
google-cloud-pubsub
google-cloud-resource-manager
google-cloud-runtimeconfig
google-cloud-spanner
google-cloud-speech
google-cloud-storage
google-cloud-trace
google-cloud-translate
google-cloud-videointelligence
google-cloud-vision
google-gax
google-resumable-media
grpc-google-iam-v1
grpcio
oauth2client
ply
protobuf
proto-google-cloud-datastore-v1
proto-google-cloud-error-reporting-v1beta1
proto-google-cloud-logging-v2
psutil
pyasn1
pyasn1-modules
requests
rsa
setuptools
six
```

I *could* use this to just do a mass uninstall BUT I also need to compare this against our requirements.txt file. (To be discussed in the next comment.)

I guess I could also create a new virtualenv and swap it in, but where's the fun in that?

**Comment by dhermes** [comment]
How about this instead:

```
$ python3.6 -m virtualenv venv-all
$ venv-all/bin/python -m pip install 'google-cloud==0.30.0'
$ venv-all/bin/python -m pip freeze > all.txt
$ rm -fr venv-all
$ python3.6 -m virtualenv venv-storage
$ venv-storage/bin/python -m pip install 'google-cloud-storage==1.6.0'
$ venv-storage/bin/python -m pip freeze > storage.txt
$ rm -fr venv-storage
```

then compare the two sets

```python
>>> with open('all.txt', 'r') as file_obj:
...     deps_all = set(file_obj.read().strip().split('\n'))
... 
>>> with open('storage.txt', 'r') as file_obj:
...     deps_storage = set(file_obj.read().strip().split('\n'))
... 
>>> deps_storage < deps_all
True
>>> extra_deps = sorted(deps_all - deps_storage)
>>> for dep in extra_deps:
...     print(dep)
... 
dill==0.2.7.1
future==0.16.0
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
google-cloud-bigquery==0.28.0
google-cloud-bigtable==0.28.1
google-cloud-datastore==1.4.0
google-cloud-dns==0.28.0
google-cloud-error-reporting==0.28.0
google-cloud-firestore==0.28.0
google-cloud-language==1.0.0
google-cloud-logging==1.4.0
google-cloud-monitoring==0.28.0
google-cloud-pubsub==0.29.1
google-cloud-resource-manager==0.28.0
google-cloud-runtimeconfig==0.28.0
google-cloud-spanner==0.29.0
google-cloud-speech==0.30.0
google-cloud-trace==0.16.0
google-cloud-translate==1.3.0
google-cloud-videointelligence==0.28.0
google-cloud-vision==0.28.0
google-cloud==0.30.0
google-gax==0.15.16
grpc-google-iam-v1==0.11.4
grpcio==1.7.0
httplib2==0.10.3
oauth2client==3.0.0
ply==3.8
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
psutil==5.4.1
```

**Comment by mlissner** [comment]
That matches my list almost exactly...but is a much smarter way to do it. Thanks for the help, it's nice to  have a solution to this.
