### ISSUE TITLE
On party page, some attorney and party names appear twice

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#755]
I suspect this is because our de-duping algo is a bit too strict. That's not the end of the world, but we can clearly do better. Here's an example:

https://www.courtlistener.com/docket/6158782/parties/devitri-v-cronen/

Atty Andrapalliyal's name appears twice for df. DUKE.

**Comment by mlissner** [comment]
I think this is a display issue, actually. It'd be weird for this to be a data issue.

**Comment by mlissner** [comment]
Hm, and some addresses are there many times too. Curious: https://www.courtlistener.com/docket/6311836/parties/junqueira-v-souza/ (see Mary Larakers)

**Comment by mlissner** [comment]
OK, so the old ago was:

 - Look for an attorney in the DB with the same `name AND (phone OR fax OR email OR address)`

The idea there was to link the attorney across dockets. The missing step, of course, that we didn't account for, was that attorney's contact info changes. So what we do now is:

 - Find the attorney *in the docket* using only their name. 

If that's found, we use that object. If not, then we look globally, as above. This should work nicely going forward.

For the old stuff, we tag every attorney with when their data was sourced, so we just need to look for duplicates on every docket, then merge them based on the most recent data.

**Comment by mlissner** [comment]
This ticket continues to get worse the more I look at it. At this point, I don't see how to make things better without doing a full parse of the latest data we have for every case. The problem is that now that we have duplicate attorneys assigned to some parties, there's no way to know which one is correct. I think I could live with that if only meant that the address info for the attorney suffered, but the bigger issue is that this affects the role the attorney played for the party too. 

So, we might have these two facts presented on the page:

> Lissner was represented by Kennedy (Lead Attorney)
> Lissner was represented by Kennedy (Terminated)

Which to believe? No way to know. 

So, if we've gotten an upload from RECAP that has party information, we should remove what's on the docket, and replace it with what's in the upload. If we haven't gotten a RECAP upload, we should remove what's on the docket, and replace it with what's in the Internet Archive XML.

Damn. I'll go through and see if there are other fixes we should do at the same time.

**Comment by mlissner** [comment]
So now the biggest issue with this is how to handle terminated parties. Sometimes they are there, sometimes they're not. So we've got a four-way thing:

1. Terminated parties currently in the DB; also in the JSON. **Update everything.**

1. Terminated parties currently in the DB; not in the JSON: **Only update non-terminated parties.**

1. No terminated parties in the DB; but they are in the JSON. **Update everything.**

1. No terminated parties in the DB; nor in the JSON. **Update everything.**

K. `</thinking-aloud>`

**Comment by johnhawkinson** [comment]
Correct.

**Comment by mlissner** [comment]
:point_up_2: Wherein I forget that we don't have party termination information normalized in the DB. Probably should do that before I do this: https://github.com/freelawproject/courtlistener/issues/802

**Comment by mlissner** [comment]
Hm, so we have nearly the same issue with parties as we do with attorneys, where they're de-duped across dockets. We'll need to unroll that mess too while we do this one. At least I caught it.

**Comment by mlissner** [comment]
Another issue. On our [search help page][sh] we encourage people to search by `attorney_id` and `party_id`. Those will be useless after this, and probably shouldn't even be indexed. Best case scenario when you search for them, you'll get one result. Searching by attorney/party *name* is the future.

**Comment by mlissner** [comment]
I just pushed the code for this. It's a rewrite of the tasks to ensure attorneys and parties don't reach across dockets, and a major change to merge existing attorneys and parties with updated ones. Altogether, it's about 110 new lines of code to do merging, and something like 50 more lines that were tweaked for the party/attorney bit. 

Tests are running now, which I expect will pass. Once they do, it's deployment time. Any issues that come up I'll be ready to deal with.

**Comment by mlissner** [comment]
Once any issues are resolved, the last piece is to re-parse every damned piece of source material we've got. Which is kind of insane.

**Comment by mlissner** [comment]
This is working, but with a kink: If a terminated party doesn't show up in the parsed JSON, but already exists in the database, we keep the party (great!), but we delete their lawyer (not great). This is because the lawyer doesn't show up in the new data, and also isn't listed as terminated (because their party *is*). 

So....we have to add one more catch, somewhere, which makes sure that if a terminated party is not deletes, neither is their attorney. Great.

**Comment by mlissner** [comment]
OK, I think this is all resolved at least with new data. I'll need to reparse everything in order to fix every party page, but that'll be taken care of in #800. 

The only remaining kink here is that if we do not receive terminated party info for the docket (the user didn't check the dumb box for terminated parties), and there's an extraneous attorney on a terminated party, we don't nuke it. For example, if the docket shows:

```

    Party                    Attorney
    John Grisham             Joseph Carpenter
    Terminated 01-01-1985    LEAD ATTORNEY
    
                             Henry Kissinger
                             TO BE NOTICED
```

We won't delete *any* of that information until somebody sends us the complete docket with the party information included. It could be that when that happens, Kissinger won't be listed as an attorney any more (say, the court never meant to add him there?). At that point, we'll nuke him. But until then, he sticks around.

In practice this should be a corner case, but if we find instances to the contrary, we can think about if there are ways to do something about this, (I'm not sure there are.)
