### ISSUE TITLE
Add new search facet to RECAP to filter to "opinions"

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#760]
The field in our database is `is_free_on_pacer`, but we can probably call this one `isOpinion`, `freeOpinion` or something like that (ideas welcome).

Alas, this will take a recrawl, so it won't be a super easy one.

**Comment by anseljh** [comment]
I would go with two separate fields. `is_free_on_pacer` does imply that it's an opinion, but it will be underinclusive of all opinions. We would also want a separate field to add on coding for opinions that weren't flagged as free. (Bonus: This gives us the ability to run a query and find things that should have been free but weren't.)

Why does it need a recrawl?

**Comment by mlissner** [comment]
> Why does it need a recrawl?

Gotta get this piece of data from the DB and into Solr.

**Comment by mlissner** [comment]
This data is getting moved to the case law side anyway, so closing.
