### ISSUE TITLE
Some parties missing from CourtListener

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#761]
I just uploaded the docket for this case: 

https://ecf.laed.uscourts.gov/cgi-bin/DktRpt.pl?127926

The parties look (in part) like this:

![screenshot from 2017-11-11 15-17-07](https://user-images.githubusercontent.com/236970/32694403-93203ac8-c6f3-11e7-99bd-4b86377a377a.png)

But on CourtListener:

https://www.courtlistener.com/docket/4953535/parties/dediol-v-best-chevrolet/

The parties look like this:

![screenshot from 2017-11-11 15-17-18](https://user-images.githubusercontent.com/236970/32694407-a9187732-c6f3-11e7-8267-fc7a466a12e0.png)

No attorneys and no firms. That's pretty far off the mark.

**Comment by johnhawkinson** [comment]
Another example of this. I ran the Docket Report with parties this afternoon in https://www.courtlistener.com/docket/6158333/parties/rodriguez-guardado-v-smith/, which was the first time the party report had been run.

The result is 2 attorneys for the petitioner and none for the other 5 parties.
But there are supposed to be 3 attorneys for petitioners, 2 for respondent, and 3 for amicus.

CL has (ugliness copy/pasting is CL's fault, so I'll leave it here as a reminder):

``` Petitioner
Francisco Rodriguez-Guardado

Represented by
Matthew S. Cameron

  (617) 567-0508

Matthew S. Cameron
256 Marginal St
East Boston, MA 02128

Attorney to be noticed 
Tiffiney F. Carney

  (202) 346-4000

Goodwin Procter LLP
901 New York Ave. N.W.
Washington, DC 20001

Attorney to be noticed 

Pro hac vice 
```

But PACER had:

<table width="100%" cellspacing="5" border="0">
<tr>
<td>
<b>
<u>Petitioner
</u>
</b>
</td>
</tr>
<tr>
<td width="40%" valign="top">
<b>Francisco Rodriguez-Guardado
</b>
</td>
<td width="20%" valign="top" align="right">represented&nbsp;by</td><td width="40%" valign="top"><b>John                 T.              Bennett                                           </b>
<br>Goodwin Procter LLP                                         
<br>100 Northern Avenue                                         
<br>Boston, MA 02210          
<br>617-570-1000             
<br>Fax: 617-523-1231        
<br>Email: jbennett@goodwinprocter.com
<br><i>ATTORNEY TO BE NOTICED</i><br><br>
<b>Matthew              S.              Cameron                                           </b>
<br>256 Marginal St                                             
<br>East Boston, MA 02128          
<br>617-567-0508             
<br>Email: matt@massimmigrationlaw.com
<br><i>ATTORNEY TO BE NOTICED</i><br><br>
<b>Tiffiney             F.              Carney                                            </b>
<br>Goodwin Procter LLP                                         
<br>901 New York Avenue, N.W.                                   
<br>Washington, DC 20001          
<br>(202) 346-4000           
<br>Email: tcarney@goodwinlaw.com
<br><i>PRO HAC VICE</i>
<br><i>ATTORNEY TO BE NOTICED</i></td></tr><tr><td></td></tr>
<tr><td valign="top"><br>V.<br></td></tr>
<tr>
<td>
<b>
<u>Respondent
</u>
</b>
</td>
</tr>
<tr>
<td width="40%" valign="top">
<b>Jeffrey Sessions
</b>
<br>
<i>Attorney General of the United States
</i>
<br>
<i>TERMINATED: 07/14/2017
</i>
</td>
</tr>
<tr>
<td>
</td>
</tr>
<tr>
<td>
<b>
<u>Respondent
</u>
</b>
</td>
</tr>
<tr>
<td width="40%" valign="top">
<b>John  Kelly
</b>
<br>
<i>Secretary, Department of Homeland Security
</i>
<br>
<i>TERMINATED: 07/14/2017
</i>
</td>
</tr>
<tr>
<td>
</td>
</tr>
<tr>
<td>
<b>
<u>Respondent
</u>
</b>
</td>
</tr>
<tr>
<td width="40%" valign="top">
<b>Chris M. Cronen
</b>
<br>
<i> New England Field Office Director for Enforcement and Removal Operations, Immigration and Customs Enforcement
</i>
<br>
<i>TERMINATED: 07/14/2017
</i>
</td>
</tr>
<tr>
<td>
</td>
</tr>
<tr>
<td>
<b>
<u>Respondent
</u>
</b>
</td>
</tr>
<tr>
<td width="40%" valign="top">
<b>Yolanda Smith
</b>
<br>
<i>Superintendent, Suffolk County House of Correction
</i>
</td> 
<td width="20%" valign="top" align="right">represented&nbsp;by</td><td width="40%" valign="top"><b>Annapurna            Balakrishna                                       </b>
<br>U.S. Attorney's Office                                 
<br>Civil Division                                              
<br>One Courthouse Way                                          
<br>Suite 9200                                                  
<br>Boston, MA 02110          
<br>617-748-3111             
<br>Email: annapurna.balakrishna@usdoj.gov
<br><i>LEAD ATTORNEY</i>
<br><i>ATTORNEY TO BE NOTICED</i><br><br>
<b>Michael              P.              Sady                                              </b>
<br>United States Attorney's Office                        
<br>John Joseph Moakley Federal Courthouse                      
<br>1 Courthouse Way                                            
<br>Suite 9200                                                  
<br>Boston, MA 02210          
<br>617-748-3362             
<br>Fax: 617-748-3971        
<br>Email: michael.sady@usdoj.gov
<br><i>ATTORNEY TO BE NOTICED</i></td></tr><tr><td></td></tr>
<tr>
<td>
<b>
<u>Amicus
</u>
</b>
</td>
</tr>
<tr>
<td width="40%" valign="top">
<b>American Civil Liberties Union of Massachusetts
</b>
</td>
<td width="20%" valign="top" align="right">represented&nbsp;by</td><td width="40%" valign="top"><b>Adriana              Lafaille                                          </b>
<br>American Civil Liberties Union                              
<br>211 Congress Street                                         
<br>Boston, MA 02110          
<br>617-482-3470             
<br>Email: alafaille@aclum.org
<br><i>LEAD ATTORNEY</i>
<br><i>ATTORNEY TO BE NOTICED</i><br><br>
<b>Julie                V.              Silva Palmer                                      </b>
<br>Morgan, Lewis &amp; Bockius LLP                                 
<br>One Federal Street                                          
<br>Boston, MA 02110          
<br>617-951-8417             
<br>Email: julie.palmer@morganlewis.com
<br><i>LEAD ATTORNEY</i>
<br><i>ATTORNEY TO BE NOTICED</i><br><br>
<b>Matthew              Segal                                             </b>
<br>American Civil Liberties Union                              
<br>211 Congress Street                                         
<br>Boston, MA 02110          
<br>617-482-3170             
<br>Fax: 617-451-0009        
<br>Email: msegal@aclum.org
<br><i>LEAD ATTORNEY</i>
<br><i>ATTORNEY TO BE NOTICED</i></td></tr><tr><td></td></tr>
</table>

**Processing queue object:**

```
{
    "id": 25481,
    "court": "mad",
    "docket": "https://www.courtlistener.com/api/rest/v3/dockets/6158333/",
    "docket_entry": null,
    "recap_document": null,
    "date_created": "2017-11-25T00:31:37.462044Z",
    "date_modified": "2017-11-25T00:31:37.883835Z",
    "pacer_case_id": "190610",
    "pacer_doc_id": "",
    "document_number": null,
    "attachment_number": null,
    "status": 2,
    "upload_type": 1,
    "error_message": "Successful upload! Nice work.",
    "debug": false
}
```

PS, who is "Jeffrey Sessions"?

**Comment by mlissner** [comment]
Thank you. This is useful to have more examples.

**Comment by johnhawkinson** [comment]
See also #754.
Note the title of this Issue mislead me. Mike's initial example is that not that the parties are missing, but rather than their attorneys and the attorney addresses are missing.

**Comment by mlissner** [comment]
OK, first, some good news: This isn't a juriscraper bug. Juriscraper parsing like gangbusters. So that means it's a CourtListener bug either in display (hopefully) or in merging.

**Comment by mlissner** [comment]
OK, this needed a really dumb fix as you can see in https://github.com/freelawproject/courtlistener/commit/9b7cc29413c911757a6dd3d0a8aa7256b3b17c18.

Tested that against the Chevrolet case and it's fixed. Tested against the Guardado case and it's fixed.

**Comment by johnhawkinson** [comment]
Unfortunately I don't think this is fixed.
The UI is problematic enough that I cannot completely tell, which is perhaps a problem on it's own.

In [Guardado](https://www.courtlistener.com/docket/6158333/parties/rodriguez-guardado-v-smith/), now, Mike Sady appears to be representing only Yolanda Smith, instead of all defendants from Cronen through Smith:

<img width="836" alt="screen shot 2018-02-20 at 22 39 34" src="https://user-images.githubusercontent.com/1270718/36463194-47fa6c1a-1696-11e8-82d3-1e40ebfbfd2b.png">

Either the display is grossly misleading or this is still broken.
Reviewing [Best Chevrolet ](https://www.courtlistener.com/docket/4953535/parties/dediol-v-best-chevrolet/), I conclude it's the former, because Myers and Carver are representing Best Chevrolet, Inc. and Donald Clay, and are listed twice for those representations. (This further suggests a bug that Best Chevrolet (not-Inc.) has no appearances, but I haven't checked the PACER docket).

And, of course, this fix highlights the reason why PACER dockets say `(see above for address)`; not implementing that or something similar makes this display hard to use. Of course, it was a lot less noticeable before because the multiply party case didn't display right. This should be filed as a separate issue, I realize.

**Comment by mlissner** [comment]
After talking about this a bunch just now on Slack, I think we're good here, though, naturally, we discovered more issues not covered here that I'll file shortly.
