### ISSUE TITLE
PACER parser doesn't get past certain docket entry

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#762]
Not sure what's going on here, but:

https://ecf.azb.uscourts.gov/cgi-bin/DktRpt.pl?610994

After docket entry 93, we can't seem to proceed:

https://www.courtlistener.com/docket/4983374/jesus-padilla/?filed_after=&filed_before=&entry_gte=&entry_lte=&order_by=asc

There seems to be some weird HTML going on here. Looks like a fun one.

**Comment by mlissner** [comment]
Found another one of these in our tests. For some reason, there are two HTML tables back to back containing docket entries. One ends, and the next begins:

```
</TABLE>
<TABLE BORDER=1 CELLPADDING=10 CELLSPACING=0>
```

It's particularly annoying because the second table has no headers or anything that would make it easy to identify. The only way to really identify it — I think — is going to be by looking for tables that come *after* the first table. Ugh.

This is what it looks like in practice:

![screenshot from 2017-11-21 16-58-10](https://user-images.githubusercontent.com/236970/33104472-30b41e08-cedd-11e7-827c-f64f332a3d30.png)

**Comment by mlissner** [comment]
Here's the test where this is failing: 

https://github.com/freelawproject/juriscraper/blob/d3d8914e4358bb2a01db30acbcd8892974dadab9/tests/examples/pacer/dockets/bankruptcy/ctb_1.html#L160-L164

**Comment by mlissner** [comment]
Another in the tests: 

https://github.com/freelawproject/juriscraper/blob/d3d8914e4358bb2a01db30acbcd8892974dadab9/tests/examples/pacer/dockets/bankruptcy/azb_29.html#L167-L170

**Comment by johnhawkinson** [comment]
At first when I saw this I was so sure it was going to be an instance of multiple dockets in a conslidated report ala https://github.com/freelawproject/recap/issues/208#issuecomment-345011622. But no.

> The only way to really identify it — I think — is going to be by looking for tables that come after the first table. Ugh.

Well, it sounds like a preprocessing step is in order. Iterate over all tables and check to see if any of them lack headers and are consecutive with the prior table with no intervening tags or text elements. If so, merge with the prior table?

**Comment by mlissner** [comment]
This was surprisingly common. In our tests, we currently have 450 dockets from a variety of jurisdictions that we parse. Of them, 24 were affected by this bug, so about 5%. The test dockets may or may not be representative of normal dockets, but it was more exposure than I expected, so I'll be re-running the parsers once the Juriscraper upgrade lands server-side. I imagine that'll add/update a LOT of content.

The reason our tests didn't catch this before now is because the tests came from the old recap server. The way they worked there is that if they parsed without crashing, they were good, so there was no "correct" output that we could import and compare our parsers against. In Juriscraper, we've got that as json fixtures, so that will prevent any regressions here. 

I haven't looked, but it's quite possible that this bug existed in the old server's parsers too. People were fairly often complaining about dockets not getting parsed past a certain point. Perhaps this is why, not sure.

Only thing left that I'm not sure of is why PACER does this in the first place. It's funky stuff — possibly related to sealed or hidden documents? Haven't been able to find a pattern yet.
