### ISSUE TITLE
RECAP docket number search doesn't allow suffixes

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#764]
At https://www.courtlistener.com/recap/ if I search in the docket number field for a suffixed docket number that includes the judge initials, it is not found. But if I remove the suffix it is found.

E.g. A search for "1:17-cv-11696-ADB" returns no documents but "1:17-cv-11696" does return them.

Because it's common to copy/paste the docket number from sources that have suffixed initials, it would be nice if this worked. (Also, sometimes we get multiple sets of initials, e.g. "1:12-cv-00763-ERK-VVP"; that should be handled as well.)

**Comment by mlissner** [comment]
Grr, docket numbers are a pain. We'll want to deal with this, I suppose, at least in the docket number search box. Thanks.

**Comment by johnhawkinson** [comment]
It's worse than I thought:

https://www.courtlistener.com/docket/4275782/parties/united-states-v-cadden/
is United States v. Cadden (1:14-cr-10363)

But https://www.courtlistener.com/docket/6145187/united-states-v-cadden/
is United States v. Cadden (1:14-cr-10363-RGS) 

Not sure what lead to that (but see https://github.com/freelawproject/recap/issues/208)
