### ISSUE TITLE
CL rejects RECAP uploads for multi-case dockets

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#767]
This should be high priority, and is a regression from the RECAP/IA server.
It could also be used to attack the CL server and prevent future uploads.

The CL server rejects uploads of docket information and documents for cases where there is more than one case per docket number. This phenomenon is quite common in criminal cases (that is, it's true for all of them AFAICT), and is discussed in https://github.com/freelawproject/recap/issues/208.

The RECAP server allowed upload of these items and treated the cases as separate unrelated cases, which was confusing but OK. That data was successfully imported in to CL, again, confusing but no data loss.

But it appears, now, that no matter which case is picked, the data won't be allowed.

Example:

I got a NEF for doc 1337 in _USA v. Cadden et al_'s subcase `-2`, `1:14-cr-10363-RGS-2 ` in `ecf.mad`, referencing https://ecf.mad.uscourts.gov/cgi-bin/DktRpt.pl?166116. I decided to retrieve the doc using the linked caseid rather than the master caseid.

The processing queue got these two entries:

```
{
           "id": 10785,
           "court": "mad",
           "docket": null,
           "docket_entry": null,
           "recap_document": null,
           "date_created": "2017-11-17T19:39:57.682069Z",
           "date_modified": "2017-11-17T19:39:57.798920Z",
           "pacer_case_id": "166116",
           "pacer_doc_id": "",
           "document_number": null,
           "attachment_number": null,
           "status": 3,
           "upload_type": 1,
           "error_message": "Too many dockets found when trying to look up 'ProcessingQueue 10785: mad case #166116 (HTML Docket)'",
           "debug": false
       },
{
           "id": 10787,
           "court": "mad",
           "docket": null,
           "docket_entry": null,
           "recap_document": null,
           "date_created": "2017-11-17T19:40:10.962609Z",
           "date_modified": "2017-11-17T19:43:12.323327Z",
           "pacer_case_id": "166116",
           "pacer_doc_id": "09508391830",
           "document_number": 1343,
           "attachment_number": null,
           "status": 5,
           "upload_type": 3,
           "error_message": "Unable to find docket entry for item.",
           "debug": false
       }
```

That's notably: **Too many dockets found when trying to look up 'ProcessingQueue 10785: mad case #166116 (HTML Docket)'**

This was kind of disappointing since I had gotten used to being able to tweet out a link asap.

**Comment by johnhawkinson** [comment]
The code in question being https://github.com/freelawproject/courtlistener/blob/be1505889e6ff6f9b1190b5676809819c335e7a1/cl/recap/tasks.py#L100-L119

**Comment by mlissner** [comment]
> This was kind of disappointing since I had gotten used to being able to tweet out a link asap.

Thanks John. We'll get this dialed in.

**Comment by mlissner** [comment]
The code snippet in https://github.com/freelawproject/courtlistener/issues/767#issuecomment-345378081 isn't right. It's a similar message and logic, but the right code is:

https://github.com/freelawproject/courtlistener/blob/be1505889e6ff6f9b1190b5676809819c335e7a1/cl/recap/tasks.py#L399-L424

**Comment by mlissner** [comment]
There were 85 items that needed this fixed. They've all been processed as of now. Thanks for filing this, @johnhawkinson.

**Comment by johnhawkinson** [comment]
W000-ha!!!
