### ISSUE TITLE
"Buy on PACER" button doesn't work with RECAP

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#768]
CL's "Buy on PACER" button goes to a bare `doc1` link, e.g
https://ecf.mad.uscourts.gov/doc1/09508381047
which doesn't give the RECAP extension a caseid, which means the purchased document doesn't upload back to CL.

"Oops."

**Comment by johnhawkinson** [comment]
This will be fixed by #774 item (2).

**Comment by mlissner** [comment]
Actually, just fixing #774 item (2) will just ensure that we have a pacer_doc_id value for every document. It won't fix the URL. To fix this, we also need to add the `caseid` param to the doc1 URLs we provide on the docket page (and we need to capture that value in RECAP, if we don't already).

**Comment by mlissner** [comment]
OK, the CL side of this is fixed. When https://github.com/freelawproject/recap-chrome/pull/34/ is fixed client-side, we should be in good shape.

**Comment by mlissner** [comment]
Just tested post freelawproject/recap-chrome#34, and it works! This will please a lot of people.

**Comment by mlissner** [comment]
Verified again using https://ecf.flsd.uscourts.gov/doc1/05101725347?caseid=303986, which was linked from: https://www.courtlistener.com/docket/4502059/katz-v-mrt-llc/.
