### ISSUE TITLE
Processing queue URLs should be visible

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#769]
The user who uploads a document should be able to figure out what happened to it, whether it threw an error, is being processed, or the RECAP server is down, or whatnot.

Currently the processing queue is locked down.

Given that processing queue IDs present as 16-bit integers, just opening them to queries would let anyone scrape the whole queue with ease, which seems to be desirable.

So server submissions should return a nonce along with the queue ID, and queue lookups should be permitted given the nonce and the queue ID together. 

This is most likely to be useful to people trying to do extension development.

**Comment by mlissner** [comment]
It's possible to change the data model to use a UUID instead of an integer for the ID field. That would probably do the trick.

**Comment by mlissner** [comment]
I think since we've not gotten this request again and since I can just open the queue to anybody doing RECAP work, I'm going to close this issue. I don't think we'll ever get to it, and it's mostly solved in other ways.
