### ISSUE TITLE
Create a /download endpoint for Archive filenames -> docket pages

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#771]
For feature parity with Internet Archve, please create
  `http://courtlistener.com/download/${archivedocket}`
as an endpoint, just like we have
  `http://archive.org/download/${archivedocket}`

This allows someone to take an Archive-style filename they have handy, e.g. `gov.uscourts.dcd.160370.63.0.pdf`, and construct the URL to the docket page as
http://archive.org/download/gov.uscourts.dcd.160370

But since the IA docket pages are (effectively) not being updated, there should be an easy alternative on CL:
http://courtlistener.com/download/gov.uscourts.dcd.160370

**Comment by johnhawkinson** [comment]
Also, given that CL offers PDF links like 
`https://www.courtlistener.com/recap/gov.uscourts.cand.308136/gov.uscourts.cand.308136.2237.0.pdf`
then CL should also offer a `courtlistener.com/recap/${archivedocket}` URL consistent with truncation. That is:

`https://www.courtlistener.com/recap/gov.uscourts.cand.308136/`

ought to work.

**Comment by mlissner** [comment]
The suggestion made in #778 is that we can use Solr to provide somewhat useful URLs of the form:

https://www.courtlistener.com/?q=pacerCaseId:xxxx

That's not what this bug is asking for, but it's a step in the right direction anyway.

**Comment by mlissner** [comment]
How much would you object to something as simple as:

https://www.courtlistener.com/lookup/pacer/docket/$court/$pacer_case_id/

Which would return a 302 to the usual:

https://www.courtlistener.com/docket/$some-id/$some-slug/

We could also do:

https://www.courtlistener.com/lookup/pacer/document/$court/$doc1/

I guess a simple form could also live at:

https://www.courtlistener.com/lookup/pacer/

That'd help you if you're not a URL hacker. This would follow in the design of the citation lookup tool that we already have:

https://www.courtlistener.com/c/

(which I guess could move to https://www.courtlistener.com/lookup/citation/)

I could bang that out in a few hours if that's all we're talking about here.

**Comment by mlissner** [comment]
How much would you object to something as simple as:

https://www.courtlistener.com/lookup/pacer/docket/$court/$pacer_case_id/

Which would return a 302 to the usual:

https://www.courtlistener.com/docket/$some-id/$some-slug/

We could also do:

https://www.courtlistener.com/lookup/pacer/document/$court/$doc1/

I guess a simple form could also live at:

https://www.courtlistener.com/lookup/pacer/

That'd help you if you're not a URL hacker. This would follow in the design of the citation lookup tool that we already have:

https://www.courtlistener.com/c/

(which I guess could move to https://www.courtlistener.com/lookup/citation/)

I could bang that out in a few hours if that's all we're talking about here.

**Comment by johnhawkinson** [comment]
> How much would you object to something as simple as:
https://www.courtlistener.com/lookup/pacer/docket/$court/$pacer_case_id/

This doesn't really solve my problem?
I see two important goals for this:

1. If you have a document URL in hand (be it from an external link, from the RECAP client, or from your browser's download history, etc.) which is of the form `https://www.courtlistener.com/recap/gov.uscourts.cand.308136/gov.uscourts.cand.308136.2237.0.pdf`, then you should be able to turn it into a docket URL by truncation, and this works for people who don't have special knowledge of CL -- it's the "obvious" thing to try. This does not meet that goal.

2. If you have a document saved on your hard drive named `gov.uscourts.cand.308136.2237.0.pdf`, you should be able to construct a URL that works. Doing so requires the special knowledge that what you prepend is `courtlistener.com/recap/` or `courtlistener.com/download/`. This implementation does not meet that goal, but comes closer -- the knowledge required is not as simple as a prefixed string, but is a relatively simple transformation. Still, prefixing a string is really copy-paste friendly, and transformation is not.

> Which would return a 302 to the usual:

Yes, that's an implementation mechanism I endorse. (And indeed, archive.org would `302` redirect the `/download` links as well, at least sometimes, e.g. to `http://ia800205.us.archive.org/1/items/gov.uscourts.dcd.160370/gov.uscourts.dcd.160370.docket.html`). 

> We could also do: https://www.courtlistener.com/lookup/pacer/document/$court/$doc1/
I guess a simple form could also live at:
https://www.courtlistener.com/lookup/pacer/

I have no objection to these, but I don't see an immediate use case for them.

**Comment by mlissner** [comment]
You're going to think this is crazy, but `/recap/` is a bit of a polluted namespace:

 - `/recap/` — advanced search for the RECAP Archive
 - `/recap/gov.uscourts.cand.30136.10.0.pdf — some documents
 - `/recap/gov.uscourts.cand.30136/gov.uscourts.cand.30136.10.0.pdf — more documents

Basically, anything other than `/recap/` is redirected to the file system to get a file. It's one of those things that could be fixed, and I think I've got a bug to do so, but for the moment, it's a messy place under `/recap/`.

I could probably hack around this to do the lookup like you're asking, but I'd rather have a series of lookup URLs like I described above, where they're tucked away neatly into their own namespace. They could be made to work with documents like you describe though. What if these worked too:

https://www.courtlistener.com/lookup/pacer/docket/gov.uscourts.cand.30136/

And:

https://www.courtlistener.com/lookup/pacer/document/gov.uscourts.cand.30136.10.0.pdf

?

**Comment by johnhawkinson** [comment]
> You're going to think this is crazy, but `/recap/` is a bit of a polluted namespace:

I'm a strong supporter of keeping legacy APIs and endpoints working and am willing to accept a relatively high programmer support and maintenance burden for that, so I don't think it is crazy. (Better luck next time.)

But I do think my proposed form, `/recap/gov.uscourts.cand.30136`, is easily distinguishable from the above, even though it is uncomfortably close to `/recap/gov.uscourts.cand.30136/gov.uscourts.cand.30136.10.0.pdf` (and recognizing that `/recap/gov.uscourts.cand.30136/` should probably go to the docket page, since you don't autoindex and the alternative is returning a 404 for the version of a URL with a terminal slash, which is bad practice).

I'd be happy to write the Apache rule for you.

>I  could probably hack around this to do the lookup like you're asking, but I'd rather have a series of lookup URLs like I described above, where they're tucked away neatly into their own namespace. They could be made to work with documents like you describe though. What if these worked *too*:

I have no objection to having those work "too." It's just that I think being able to truncate from the form you get returned is important.

> https://www.courtlistener.com/lookup/pacer/document/gov.uscourts.cand.30136.10.0.pdf

Err.... is there a good reason to do this in addition to `https://www.courtlistener.com/recap/gov.uscourts.cand.30136.10.0.pdf`? Do they return the same document? Is this two ways to get to the same thing? Are you thinking of changing what CL publishes from the short `/recap/` to the longer `/lookup/pacer/document/` form (not sure I'm on board).

Or is this a way to return the non-PDF HTML document page?

**Comment by mlissner** [comment]
> Err.... is there a good reason to do this in addition to [the regular links we already have] ? 

Not much, to be honest. Let's scratch that.

> I think being able to truncate from the form you get returned is important.

I think for some people, this is probably true (like you), but I think in general most people won't hack URLs and so I don't think it's worth the effort to further pollute the `/recap/` namespace. I think the only way I'm willing to do this kind of a lookup feature is to namespace it somewhere else. 

I think that's useful as an API (as discussed in johnhawkinson/recapupload#2), but I don't see it being very useful for actual users. I'm trying to think about the fact that most users have zero idea about pacer's internal ID numbers.

**Comment by johnhawkinson** [comment]
>  I'm trying to think about the fact that most users have zero idea about pacer's internal ID numbers.

I look at it differently. This is a true statement (users have no idea about internal ID numbers), but it's not relevant. They see the document name as an inscrutable blob. But they know that chopping the end off a blob (esp. if it's after a slash, which is sometimes true here but not always) is a handy thing to do.

And while I won't claim "most" users do, anyone who stops to think about it knows the last number in the filename is the docket entry number.

Plus, this restores feature parity with IA, which I think is important, both in practice and philosphically (two birds with one stone! One was a metaphorical bird. Does that make the stone dually metaphorical and physical?)

I'd really like to have a scheme that is discoverable and truncation-acessible. Oh, and also short.

**Do you think having a single RewriteRule is too much pain to pay for that?**

**Comment by mlissner** [comment]
> Do you think having a single RewriteRule is too much pain to pay for that?

No, but it's more than that because of the namespace being a mess. You'd have to do it in Django, which automatically redirects everything to the trailing-slash version of the page, so:

    /recap/gov.uscourts.cand.302300 

Would automatically go to:

    /recap/gov.usourts.cand.302300/

Now *that* looks like something that should just be an index file for all of the PDFs in a case, but assuming it's not, we could have Django capture that, but now we're asking Django to distinguish between that URL and each of these:

    /recap/
    /recap/gov.uscourts.cand.30136.10.0.pdf
    /recap/gov.uscourts.cand.30136/gov.uscourts.cand.30136.10.0.pdf

And of course that's possible, but the whole thing just feels...bad. If it were one RewriteRule, that'd be one thing, but this feels error prone and messy, and not like something I'd want to support forever (which we'd want to do if it were a URL).

**Comment by johnhawkinson** [comment]
I want to highlight what you just said:

> Now that looks like something that should just be an index file for all of the PDFs in a case

**_Exactly_**. That's what a docket page is, after all. An index of all the PDFs in the case. You look at the URL and it just seems like what it should be. (And that's why people like me construct such URLs). So we should make it work.

> No, but it's more than that because of the namespace being a mess. You'd have to do it in Django, which automatically redirects everything to the trailing-slash version of the page, so:

Maybe I'm missing something but I don't see why? Approximately (untested, notional):

```
RewriteRule ^/recap/gov.uscourts\.([^\.]+).([^\.+)/?$ /lookup/pacer/docket/$1/$2/
```

Apache rules take priority over Django rules, so this seems simple enough.

(Now, I can see an argument that perhaps it is better to do it at the Django level. I don't object to that either.)

> now we're asking Django to distinguish between that URL and each of these

It doesn't seem like asking Django to tell the difference between URLs that end in `.pdf` and URLs that don't (and the special case of `/recap` standing alone) is a tough job. You don't have to convince me you're right, but I do think there's maybe a more convincing argument than this one? `:)`

> If it were one RewriteRule, that'd be one thing, but this feels error prone and messy, and not like something I'd want to support forever (which we'd want to do if it were a URL).

See above. I agree on support in perpetuity!

**Comment by mlissner** [comment]
Anyway, this just bit me. Somebody shared this link with me:

https://www.courtlistener.com/recap/gov.uscourts.nysd.480522.1.0.pdf

And I was like, OK, how do I get to the docket? I've also been thinking about how people share so many PDFs on social networks and there's no good way to get to the docket from those either. 

Sometimes things just need to hit home to sink in. Anyway, we should fix this.

**Comment by mlissner** [comment]
OK, here's a spec, as we discussed:

`/recap/` --> Still the recap homepage. This is defined in the code, here:

https://github.com/freelawproject/courtlistener/blob/80ebf1bb36726b65809afd1d5b8bef09a6ada81e/cl/search/urls.py#L29-L33

`/recap/gov.uscourts.nysd.480522` --> Django automatically adds a trailing slash, then redirects to...

`/recap/gov.uscourts.nysd.480522/` --> Redirects (302) to the docket page. 

`/recap/gov.uscourts.nysd.480522.1.0.pdf` and `/recap/gov.uscourts.nysd.480522/gov.uscourts.nysd.1.0.pdf` --> Continues serving files as defined here:

https://github.com/freelawproject/courtlistener/blob/80ebf1bb36726b65809afd1d5b8bef09a6ada81e/cl/simple_pages/urls.py#L28-L30

All of this should be handled in Django. Pretty sure it has to be, since it will involve doing a DB lookup to identify the redirect. It would also be great to get a test written for this too, if that's possible (I know it's not always easy).

**Comment by mlissner** [comment]
Closed by https://github.com/freelawproject/courtlistener/commit/f0a5b0288c18ba6f1bdd745ee84e51e15eaa14f9
