### ISSUE TITLE
CL RECAP PDF downloads force attachment disposition overriding browser preferences

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#777]
A colleague who is hip-to-the-browser PDF world (antimatter to me) observes that PDF downloads from CourtListener do not open in his browser (Chrome under OSX) when his settings are set to do so. I can confirm.

That appears to because they're sent as `Content-Disposition: attachment`, which forces the browser to download externally:

```
pb3:tmp jhawk$ curl -I 'https://www.courtlistener.com/recap/gov.uscourts.cand.308136/gov.uscourts.cand.308136.2270.0.pdf'
HTTP/1.1 200 OK
Date: Mon, 27 Nov 2017 19:14:10 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Frame-Options: SAMEORIGIN
X-Robots-Tag: noindex, noodp, noarchive, noimageindex
Content-Disposition: attachment; filename="gov.uscourts.cand.308136.2270.0.pdf"
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-UA-Compatible: IE=Edge,chrome=1
Last-Modified: Sun, 26 Nov 2017 17:11:36 GMT
Content-Length: 41607
Content-Type: application/pdf
```

That is: `Content-Disposition: attachment; filename="gov.uscourts.cand.308136.2270.0.pdf"`.

It seems like this is inappropriate, absent a strong justification. The server shouldn't specify whether the client downloads or views, it should be agnostic. Let the users browser preferences rule.

I'm having trouble finding the code where this occurs. The only place in the CL sourcebase where I see this specified is:

https://github.com/freelawproject/courtlistener/blob/8402070fe99c12b39ecd052ac8fbbb051ad23f95/cl/api/views.py#L88-L101

but this doesn't seem to apply to `/recap/` urls. Perhaps this is an apache configuration that's not in this git repo.

(In any event, I don't know what a bulk pagerank file is or why it deserves attachment disposition either. Seems plausible that is separately wrong?)

In any event, is there a reason for this behavior and can we fix it?

**Comment by mlissner** [comment]
The code for this is here:

https://github.com/freelawproject/courtlistener/blob/8dc4119e316c1147c57bfd1fc4e59293c19cc75e/cl/simple_pages/views.py#L254-L297

I think the `Content-Disposition` was more necessary back before browsers had built in PDF readers, but I'll have to look into what the normal thing is to do these days.

**Comment by johnhawkinson** [comment]
> I think the Content-Disposition was more necessary back before browsers had built in PDF readers, but I'll have to look into what the normal thing is to do these days.

I…don't think that was ever true?
As long as we've had a content-type (HTTP/1.0 but not HTTP/0.9), Content-type `application/pdf` did the right thing and browser would do what they'd do. [I'm sure there were broken browsers...]

The "normal thing" is to do nothing special.

On the other hand, I'm sure of myself and feel like I'm missing something, so calm before the storm…

**Comment by mlissner** [comment]
I think its purpose was to set the filename? I honestly haven't looked at this in a long time.

**Comment by johnhawkinson** [comment]
I just had a colleague refuse to link to a CourtListener PDF, preferring to use a known-to-be-time-limited `mass.gov` link (expires in13 days), because of this behavior.
