### ISSUE TITLE
`pacer_case_id` should be Solr -searchable

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#778]
In the spirit of #771, it should also be possible to just do the search, even lacking the endpoint.

Indeed, why would there be any fields that are not searchable? Indexes are cheap!

**Comment by mlissner** [comment]
When we do this, we should be sure to use a multi-valued field because criminal cases have multiple pacer_case_id values. Our DB doesn't yet work that way, but we can hope that it will one day.

**Comment by johnhawkinson** [comment]
I'm not sure how the criminal cases should be modeled. I would tend to think we should track them all by the master case's `pacer_case_id` and have another table associating each sub-case with the parent case (query: how would this data get populated? `possible_case_ids` is free...).

But another choice would be to, similar to today, track the subcases as first class cases. If that route is chosen, then probably there should be a `master_pacer_case_id` field in each subcase that references the master case.

…

**Comment by albertisfu** [comment]
@mlissner a couple of questions about this issue.

- In Oral Arguments, there is no `pacer_case_id` directly into the model. I guess we should use the related Docket `pacer_case_id`, correct?
- In a comment above you mentioned:
> When we do this, we should be sure to use a multi-valued field because criminal cases have multiple pacer_case_id values. Our DB doesn't yet work that way, but we can hope that it will one day.

Dockets still have only a unique `pacer_case_id`. Therefore, I suppose we should also use a unique value for the ES index, right?

- Should this field be accessible as a filtering option, or should it be limited to advanced search functionality?

**Comment by mlissner** [comment]
You're right about everything: Yes, use pacer_case_id from dockets; Yes, just assume a unique value for ES.

> Should this field be accessible as a filtering option, or should it be limited to advanced search functionality?

Just as an advanced field. Most users have no idea this exists, so we wouldn't want to expose it to them in an obvious way.

Thank you!

**Comment by mlissner** [comment]
(And in case it's not obvious, we should get this field (and any other missing ones, probably?) into all our data types: RECAP, Opinions, OA, etc.)

**Comment by albertisfu** [comment]
Perfect, I've added the field for Oral Arguments in #2770

For Parentheticals does it makes to add it too?

When migrating other objects like RECAP and Opinions, I'll be adding it too.

**Comment by mlissner** [comment]
This is resolved.
