### ISSUE TITLE
Inconsistent docket/document state in English v. Trump

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#779]
Nothing like tweeting out links to a CL page to cause fatal bugs to appear.

All of the documents in English v. Trump appear to have been uploaded to CL via RECAP, yet some of them, such as docket entry 2, claim not to be there on the individual document page:
https://www.courtlistener.com/docket/6230478/2/english-v-trump/

Although download lins are shown and functional on the parent docket page:
https://www.courtlistener.com/docket/6230478/english-v-trump/

This seems like a "can't happen" scenario.

**Comment by mlissner** [comment]
Please see the commit message for the fix. Basically, our two ways of getting data were trammeling each other.
