### ISSUE TITLE
Manafort/Gates doppelgangers lead to bad PDF links from CL

### ISSUE THREAD

**Issue by johnhawkinson** [freelawproject/courtlistener#785]
This is related to our continual problem of multiple subcases in criminal cases and consequent doppelganger cases and soforth. https://github.com/freelawproject/courtlistener/issues/2185 https://github.com/freelawproject/recap/issues/61 &c.

https://www.courtlistener.com/docket/6183591/united-states-v-manafort/ 
links to
https://www.courtlistener.com/recap/gov.uscourts.dcd.190597.13.0.pdf
but returns `404 Not Found`.

But https://www.courtlistener.com/recap/gov.uscourts.dcd.190596.13.0.pdf exists and works, but is not linked.

**Comment by mlissner** [comment]
This was filed in 2018 and never commented on until now. 

We're not going to fix this case as a one-off. If we fix it, it'll get fixed as part of #2185.

Closing, but thank you for taking the time to file.
