### ISSUE TITLE
500 Errors on CourtListener when accessing certain documents

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#790]
I'm really not sure how this is happening, so it needs investigation. Here's a URL that throws a 500 error:

https://www.courtlistener.com/docket/4167880/52/wilson-v-compass-vision-inc/

Looking at the error logs, this is caused because:

    get() returned more than one RECAPDocument -- it returned 2!

Which is happening because we're doing the following query:

    item = get_object_or_404(
        RECAPDocument,
        docket_entry__docket__id=docket_id,
        document_number=doc_num,
        attachment_number=att_num,
    )

So somehow, we're getting multiple items with a given document number under a docket. This shouldn't happen, and when you look at the link above, you see some truly weird things. For example:

 - The docket_entry numbers are different for the two items:

        for rd in rds:
            print rd.docket_entry.docket, rd.description, rd.docket_entry.entry_number
 
        4167880: Wilson v. Compass Vision, Inc. Case Management Conference - Initial 71
        4167880: Wilson v. Compass Vision, Inc. Case Management Statement 51

 - The pacer_case_id numbers in the document links are different:

        for rd in rds:
            print rd.filepath_local.path

        /var/www/courtlistener/cl/assets/media/recap/gov.uscourts.cand.197501.51.0.pdf
        /var/www/courtlistener/cl/assets/media/recap/gov.uscourts.cand.193651.51.0.pdf

I'm not sure what's causing this, but I do have some ideas:

1. It's caused by the "combined dockets" in #711? 

1. It's caused by old RECAP data that's bad?

1. Something else. 

We should probably have a DB-level constraint preventing this, but we also need to go through and clean up all the weird data like above.

**Comment by alexkemp9** [comment]
HTTP 500 on URL for > 1 hour on https://www.courtlistener.com/docket/7457752/54/united-states-v-butina/

Searches OK, other URLs OK, so seems this old error may NOT be fixed.

**Comment by mlissner** [comment]
It looks like the link you posted is now fixed. We had some server errors earlier today that are now resolved. 

As for the rest, yes, we need to fix this, but it doesn't affect many pages. Like any system of our size, we have a lot of bugs and have to choose which to fix. I'd love to get this one fixed, I would, but it hasn't made it to the top of the list yet.

**Comment by mlissner** [comment]
Weirdly, this came up again today from a different client. They identified this on docket https://www.courtlistener.com/docket/8477899/asdf/, which has item 28 twice.

**Comment by mlissner** [comment]
All the links listed here now work.
