### ISSUE TITLE
Add financial disclosure reports to CourtListener

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#791]
In about a week, we should get several thousand of these from the AO. We also have about 9,000 of them from Judicial Watch. Below is a sketch of how this could all pan out. It's what comes to my mind, but my mind is limited by years of working on CourtListener, and so other approaches are welcome too.

### Design goals for this project are to:

1. Be findable. I want to be sure that if anybody is looking for judicial financial disclosures, they find this site. SEO is important.

1. Once found:

    - provide an explanation of the forms, get people educated about their content, shortcomings, etc.
    - make it easy to find a specific judge's forms

1. Integrate nicely into the rest of CourtListener

### Longer term / other goals:

1. Make recusal problems easier to spot?

1. Make investments searchable? "Who are the judges invested in IBM?"

1. Bulk files? (probably not needed at first if site easily parsed)

1. API?

1. Something else??

### I think the integration points are as follows:

1. Convert the "Judges" navbar link to be a drop down like the "Visualizations" button currently is. I think the two buttons would be "Search Judges" (where the "Judge" link currently goes) and "Financial Disclosures" or something like that.

1. The "Financial Disclosures" link takes you to a new page for financial disclosure reports that explains what they are, and which ones we currently have (and why that is). From that page, allow people to look up a specific judge. 

    It'd be nice to have a little JS filtering thing where people can type to filter by name, but it'd be fine just to have all of the judges listed that have financial disclosure reports, and let the user use `Crtl+F`. 

1. On the individual judge pages (like [RBG's here][rbg]) add a new section for financial disclosures, where we have a short explainer (one line or so) of the forms, and then provide links to them.

1. Sitemaps - We'll need these to help Google Et al find the forms.

### URL design becomes:

 - `/person/` --> This is currently the search homepage. Leave it be.
 - `/person/1213/ruth-bader-ginsburg/` --> An individual judge's URL (RBG's in this case)
 - `/financial-disclosures/` --> The new homepage for financial disclosures, as described above
 - `/person/1213/ruth-bader-ginsburg/financial-disclosures/` --> A simple page that lists all of the disclosures for Justice RBG
 - `/person/1213/ruth-bader-ginsburg/financial-disclosures/ao10-ruth-bader-ginsburg-2010.pdf` --> The PDF for RBG's financial disclosure form (which is form number ao10 with the AO). 
 - `sitemap-financial-disclosures.xml` --> One big sitemap file for all of the above.

### Other things to remember:

 - [ ] We want to provide an avenue for people to submit more of these forms to us. Because of the way they're only required to be kept for a short period of time, we're missing a ton of these for active judges. I want to crowdsource these if we can. 

    Do we want this to be a big part of our PR push? (Seems like a Yes.)

    Also remember we're seeking solicitors general reports.

 - [ ] Links and explanations of the Muckrock system for getting these keyed, if appropriate.

[rbg]: https://www.courtlistener.com/person/1213/ruth-bader-ginsburg/

**Comment by mlissner** [comment]
Note that subtasks for this are tracked in https://github.com/orgs/freelawproject/projects/5

**Comment by mlissner** [comment]
CC: @flooie

**Comment by flooie** [comment]
Thanks @mlissner; CC: @aekey1

**Comment by mlissner** [comment]
I believe our entire backlog of financial disclosures is now imported HOORAH! This is a HUUUUGE milestone.
