### ISSUE TITLE
PACER party termination data not stored or parsed

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#802]
We're doing a pretty good job at parsing the data from PACER, finding whatever junk is below a party's name and putting it into our `extra_info` field on the party object from Juriscraper. 

However, when we get to the incorporating that data into CourtListener, we don't save the termination data. 

A typical example of this might look like:

![screenshot from 2018-02-28 14-20-42](https://user-images.githubusercontent.com/236970/36816420-9204f080-1c92-11e8-8d9b-12cae7643ad9.png)

What we need to do, I guess, is parse whatever info is below somebody's name, and look to see if we can find a termination date. That feels like something Juriscraper should do, but CL could probably do it too.

On the CL side, termination data is associated with the party and the docket. Currently, such data is in the `PartyType` object, which currently just has three fields:

 - Docket
 - Party
 - Name (something like Defendant, Plaintiff, etc.)

I think we can just add `date_terminated` as a nullable field here, and we'll be OK. The object will have a bad name (`PartyType` instead of, `DocketParty` or something), and displaying this in the HTML might be hard, but I think it's all workable.

**Comment by johnhawkinson** [comment]
I think you should be saving whatever the heck CMECF puts in there and parsing it is something you might also do, but is not the baseline requirement.

**Comment by mlissner** [comment]
Yeah, it's...sort of getting saved. It gets added to the Party, but that's the wrong place for it, and it can get overwritten if the party is encountered again. It needs to move to the PartyType object instead, so it'd be associated with the Docket and the Party.

**Comment by mlissner** [comment]
This is fixed template side in 00f7a11a0dfb7b8145c7e5b91284c36671b3cf85. The only remaining missing piece is to remove the old field from the DB, but this is now showing up in newly parsed dockets:

![screenshot from 2018-03-21 16-11-06](https://user-images.githubusercontent.com/236970/37742422-c1cc0e2a-2d22-11e8-9df1-1c0307f259ef.png)

I think that field can just be nuked because I think it is pretty bad data in there (that'll get fixed in #800), but we should also check the API endpoints to make sure they're good too.

**Comment by mlissner** [comment]
Narrator: Little did he know, he had already nuked the field. 

But the API endpoints needed tweaking and that's done in: e37a51c60d464e2ad29df1d5938464422d16f4b0

I think we're done here.
