### ISSUE TITLE
Remove all usages of queryset_generator; replace with Django's Iterator method

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#803]
In #687, we are upgrading to the latest django, version 1.11. Ours is old, and supposedly insecure. 

When that is complete, we should remove all references to queryset_generator, since the Iterator class will do the same except correctly.

**Comment by cweider** [comment]
Evidently done. `queryset_generator` was removed in 5362fb8!

**Comment by mlissner** [comment]
Upgrading things really is a pain, but it's really nice when new versions let you delete code!
