### ISSUE TITLE
Import Bulk Data

### ISSUE THREAD

**Issue by mschwarzer** [freelawproject/courtlistener#810]
Hi all,

Is there any pre-defined method to import the [CL bulk data](https://www.courtlistener.com/api/) into a local setup (DB+Solr)? I'd like to use some toy data for my local development. 

Best,
Malte

**Comment by mlissner** [comment]
Surprisingly...no! Usually what folks do for local dev is run some of the scrapers. I think there's a note in the readme for https://github.com/courtlistener/freelawmachine that tells how to do that? 

I'm not opposed to this, but I'm also not sure how much maintenance it  might require (and scraping tends to work pretty well in most cases).

What do you think? Worth adding or are the scrapers good enough?

**Comment by mschwarzer** [comment]
Thanks for the response. I guess then I'll try to get the scrapers running. Or maybe you could provide some sample data in the future? A simple `manage.py dumpdata` would be a good starter even if it won't include Solr.

**Comment by mschwarzer** [comment]
OK. Thanks! I'll try to get the scrapers running.
