### ISSUE TITLE
Sort out unsubscribe / resubscribe flows for recap.email emails

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#825]
How do we want to handle subscriptions for recap.email?

**Comment by mlissner** [comment]
General concept is as follows:

1. Every email has an unsubscribe link. When clicked, it either automatically disables email forwarding for a case, or it requires login before doing the same. You have to be logged in for this to work b/c people forward emails around and we cannot allow somebody to unsubscribe somebody else from updates.

2. Users have a new admin page that allows them to:
    - **Auto-subscribe to new recap.email emails.** If this is on, when we get an email about a case, we'll start sending emails to the user for that case. If it is off, when we get the first email about a case from that user, we send them a note saying we aren't forwarding things, with a link to subscribe if they want to.
    - **Turn on/off email forwarding for a given case.**

**Comment by mlissner** [comment]
This is basically done. Yay!

**Comment by Jane199240** [comment]
```html

```
