### ISSUE TITLE
Set up an HTTP POST receiver on CourtListener website

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#826]
What can we get from AWS's SES and what does this API look like?

**Comment by spacewrench** [comment]
All SMTP conversation plus contents of email.

On April 24, 2018 10:34:25 AM PDT, Mike Lissner <notifications@github.com> wrote:
>What can we get from AWS's SES and what does this API look like?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/freelawproject/courtlistener/issues/826

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
We have it as JSON, don't we? Can you share a sample?

**Comment by spacewrench** [comment]
Yes, iirc the SMTP stuff comes as JSON. (The email itself just gets dumped on S3.) I can dunno the arguments that the JS lambda function receives. Right now, I've already converted JSON to JS and extracted the interesting things--it's a deep structure and the useful things are kinda spread around.

On April 24, 2018 2:05:51 PM PDT, Mike Lissner <notifications@github.com> wrote:
>We have it as JSON, don't we? Can you share a sample? 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/freelawproject/courtlistener/issues/826#issuecomment-384079848

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mlissner** [comment]
OK, how about we start simple and do a POST endpoint with the following fields:

 - recipient address
 - email contents

Is there more that recap.email should be sending?

**Comment by mlissner** [comment]
I'm going to close this out since it doesn't have too much useful info. We'll start a new issues to design and build this when we're ready to take this step (soon!). @spacewrench, thank you for your help with this project. We didn't successfully build it back in 2018, but the work you did truly helped suss out the scope and design of the project so that we can build it now.
