### ISSUE TITLE
Add RSS feeds on PACER dockets

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#834]
Should be fairly simple.

**Comment by johnhawkinson** [comment]
I suggest you use a different HTTP virtual server to make it easy to move the load (`https://rss.courtlistener.com/`...).

**Comment by mlissner** [comment]
Easier said than done, but it's an interesting point since RSS feeds aren't allowed to move (how is this possible, I don't understand?). 

Still, hard enough that it would be a blocker for getting this done, so sadly going to have to take my chances here unless you think that's particularly foolish.

**Comment by johnhawkinson** [comment]
They are allowed to move, and most of the modern clients support moving.
Why is this a hard thign to do? It should be pretty trivial.
Like 5 minutes of apache and DNS configuration.

**Comment by mlissner** [comment]
Oh, I guess the server itself isn't necessary, eh? We could set up the apache configs, that's true. Would also have to set up the letsencrypt bits, but that shouldn't be terribly difficult. I'll look into it, thanks.

**Comment by mlissner** [comment]
I did this on a whim a while back and forgot we had an issue for it. Closing.
