### ISSUE TITLE
Create documentation of what triggers RECAP alerts

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#836]
The big problem here is that we need to somehow keep track of what's in the RSS feeds. I think that just means recrawling all of them from time to time and keeping track of what their `description` tag says.

Is this worth having its own page or just having it be part of our coverage page?

**Comment by johnhawkinson** [comment]
Err, `"wutt?"`

Could you elucidate? It doesn't seem like a periodic task is the right thing here, but maybe I am misunderstanding you

**Comment by johnhawkinson** [comment]
Ah. You're referring to the `Docket entries of type:` characteristic:

```xml
<description>Docket entries of type: order,order-cr</description>
```

It seems like the rss scraper should update this every time it scrapes, yes.

**Comment by mlissner** [comment]
Dup of #860.
