### ISSUE TITLE
Add attachments to docket alert emails

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#843]
I'm not sure how hard this is, but it seems like a great feature. What if we could add attachments to docket alerts when they went out?

**Comment by johnhawkinson** [comment]
What does that mean? You mean sending PDFs to recipients? Or you mean something else?

**Comment by mlissner** [comment]
Yep. I don't think we'll have these PDFs most of the time, but once we get, for example, recap.email up and running, we will.

**Comment by johnhawkinson** [comment]
> Yep. I don't think we'll have these PDFs most of the time,

Err, well, you'll have it whenever somebody uploads a doc with the RECAP extension.
Of course until you fix the REALLY ANNOYING BUG you're dependent on the two-step dance of docket report + PDF upload, but still, that's quite common.

> once we get, for example, recap.email up and running, we will.

Err, for some cases where someone has agreed to donate their NEFs, sure. But that won't be "most of the time," unless I'm missing something?

**Comment by mlissner** [comment]
OK, sorry, no, we won't have these most of the time, and you're right that we *will* have these when a docket comes in after a PDF. 

So, anyway, point being, sometimes we have the PDF. When we do, maybe we should attach it.

**Comment by mlissner** [comment]
@albertisfu, I'm doing some clean up (as usual), and found this old issue. When we get attachments working, we should close this out. I moved to to the RECAP Email Handler project board so we don't lose it.

**Comment by mlissner** [comment]
I think we decided that doing attachments was too hard and not worth it. The main problem was that they make the emails big and some people can't receive big emails. We get errors from AWS SES when that happens, but we didn't want to deal with keeping track of who can/can't receive big emails. 

On top of this, even for regular people, there's a cutoff where attachments are too big, so we'd have to have two email templates, one for "the doc is attached" and one for "The doc was too big, please click here." 

We actually developed most of this system, but I had @albertisfu cut it out to make things simpler. Maybe someday, but it didn't seem worth the effort once we saw how much complexity it added.
