### ISSUE TITLE
Docket alert punch list (follow up items)

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#844]
- [x] Ditch ap styling in subject line
- [x] Fallback to short description when long is missing. Use "Main Description" if necessary.
- [x] Update "Buy on PACER" link when no CL document available to say, roughly:
    > Be the first to add this to RECAP: SOME_LINK
- [x] Make body font bigger.
- [x] Fix the To: field. Either make it `noreply@cl.com` or do it properly (preferred)

Add more if you can edit or just add more in comments.

**Comment by mlissner** [comment]
- [ ] Switch Alerts to Alert in title
- [ ] A user doesn't like the italics :)

**Comment by mlissner** [comment]
- [ ] Center the document number column.

**Comment by mlissner** [comment]
- [ ] Make the please donate LOUD — like unavoidably loud.

**Comment by mlissner** [comment]
- [ ] Performance: Don't attempt to send alerts for brand new dockets. Obvy, nobody has any alerts for those yet.

**Comment by anseljh** [comment]
Is this about fixing the "Unknown" description column in all the update emails I got today? Because that'd be great. :)

> Fallback to short description when long is missing. Use "Main Description" if necessary.

**Comment by mlissner** [comment]
Yes. That's less of a tweak and more of a fix!

**Comment by mlissner** [comment]
OK, most of these email tweaks are done in: 2144c0051e739adf3c90b9893c3f8d96df4ac912

Just gotta do the BCC fixes. That'll be done momentarily.

**Comment by mlissner** [comment]
And BCCs are fixed in: 51a0ba999d05124c5456dc9fb16fa2d009eb192a

I also added an email address that'll get copies of the emails. 

And in 028b5d606cf0b7cbf68564a439e6e97ea5f649f6, I added a trick to thread these together by docket ID even if the subject line is changing. That should help some people's inboxes stay manageable.

I think most of this is resolved for now, but I want to double check the emails before I close this out, so leaving it open for another bit.

**Comment by johnhawkinson** [comment]
The most important issue is what Ansel raised, to fix the persistent "Unknown docket entry description" which doesn't seem to be addressed in those commits?

Also, your bcc strategy is going to get you _N_ duplicate emails, one for each subscriber ,which seems undesirable.

**Comment by mlissner** [comment]
> The most important issue is what Ansel raised, to fix the persistent "Unknown docket entry description" which doesn't seem to be addressed in those commits?

That's in there: https://github.com/freelawproject/courtlistener/blob/2144c0051e739adf3c90b9893c3f8d96df4ac912/cl/alerts/templates/docket_alert_email.html#L45-L51

> your bcc strategy is going to get you N duplicate emails

Doh! Good thing I held off on deploying this!

**Comment by mlissner** [comment]
Closing here. I think the most important little alert fixes are in place.
