### ISSUE TITLE
Using the Search endpoint halts the entire site

### ISSUE THREAD

**Issue by AggressivelyMeows** [freelawproject/courtlistener#858]
I followed the documentation on the `/api/rest/v3/search` and i tried it out. It seems the data was returned by after several minutes of the entire site being locked. 

So far, the site has been down for 10 minutes and counting. Im really not sure what is going on.

**Comment by mlissner** [comment]
I'm going to go ahead and close this one. I think we've established that the performance was causing somewhere else. Please feel free to comment or re-open if you can and I'll be happy to continue the conversation.
