### ISSUE TITLE
Add better info about partial PACER RSS feeds and track it better

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#860]
On this page:

https://www.courtlistener.com/help/alerts/#coverage-gaps

We list "coverage gaps" for RSS, but we don't mention that lots of RSS feeds are partial. We should fix that by keeping some information in the DB about what's supported and then listing it on this page. This will be the dashboard that some people are looking for.

That information should be updated once/day, say.

If it changes, we should send an email to administrators so they're aware.

**Comment by mlissner** [comment]
Also: For courts with partial RSS or without RSS, we should provide a warning of some kind when people create alerts, near the button, say.

**Comment by mlissner** [comment]
Here's a spreadsheet with current support. It might be enough to provide warnings at the time of creation, and not have a dashboard, though maybe the page at https://www.courtlistener.com/api/jurisdictions/ could be updated to have this info too.

[rss-feed-support.xlsx](https://github.com/freelawproject/courtlistener/files/2320373/rss-feed-support.xlsx)

**Comment by mlissner** [comment]
Turns out that we can get a list of all of the possible document types from this page:

https://ecf.alnb.uscourts.gov/cgi-bin/DktActivityRpt.pl

And then doing something like:

    $('select[name="event_category"]').innerText.replace(/\s+/g,' ');

So that's something to consider. Really, it's more interesting what a court *doesn't* do than what it does, so, I guess we should ideally grab this and the RSS info every so often, compare the two, and display either the omitted info:

> This court won't send alerts for X, Y, or Z

Or display both:

> This court only supports alerts for A, B, C, and will not send alerts for X, Y, or Z.

**Comment by johnhawkinson** [comment]
(Where `$(foo)` is browser-console shorthand for `document.querySelector(foo)`).
And of course that query requires you to be logged in, but it is free.
And for BK courts, it's `name="category"` rather than `name="event_category"`.
Etc.

**Comment by mlissner** [comment]
I remember when this looked like it'd be a simple feature to implement..... :)

**Comment by mlissner** [comment]
OK, I just pushed some changes in ae3711ca9523e2532549835e0dab2e3cd3cacea5 that will store this info and alert if it changes. Next up is showing this on dockets and in documentation somewhere.

**Comment by mlissner** [comment]
When this goes live, it'll send me an email for every PACER court as it gathers the missing information. I guess I could avoid that if I cared.
