### ISSUE TITLE
Try to make the sitemap.xml files work again, and make them fast

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#869]
I've been at war with the sitemaps for about six years now. Today I ceded a battle by removing them for both opinions and RECAP data. I did this because the search engines were crawling very hard and making the site come to its knees (as they've done so many times before).

The issue with sitemaps is that if you want them to list *everything* then you have to sort everything, and when you sort millions of items, that takes time, whether it's the DB doing it or the search engine. I first ran into this with MySQL as our database (hint: MySQL is slow on deep offset/limit queries), and now with Solr (which is just slow at these queries, but not sure why, probably sorting).

So, some questions to sort through:

 - Do we really want *everything* in our sitemaps? Can we reduce this in order to better prioritize what's in there, for example only showing items with some number of docket entries or some number of views? 

    Maybe we can accomplish Google's content discovery via the Google HTML crawler instead of via the sitemaps? Is now a good time to implement citation-based HTML pages? We've talked about doing that many times, but haven't done it yet. That might solve part of the issue, but I'm not sure how to solve it for RECAP dockets.

    If we're going to think about not putting everything in the sitemaps, we need to figure out what we prioritize.

 - Is there a way to do this that performs? Maybe Postgres can handle this better than MySQL on an indexed field. I need to test that, but so far everything has fallen flat at a query like, "Give me 250 items with an offset of 4,450,750, sorted by primary key."

One last thing to mention: Part of the reason sitemaps are so important is because we need to *encourage* search engines to find items that we have blocked from appearing in search results. Without sitemaps, what can happen is:

1. Somebody links on their blog to "Your name v. Your employer"
2. Google discovers that link, crawls it
3. You get upset, ask us to remove the item.
4. We set it as blocked, which sets `meta` tags to `noindex` in the page's HTML
5. We all wait for Google to come crawl it again.
5. Google never decides to come back and thus never gets the signal to remove the item from its results.
6. You get even more upset.

This would all be easier if Google had an API for removing URLs, but they don't, so we have to rely on Google coming and crawling and have to use sitemaps to encourage Google to crawl. 

You might wonder: "Why not use robots.txt instead of `noindex` HTML tags?" Well, two reasons:

1. That doesn't remove items from search results. It just prevents Google/Bing from crawling them.
2. Making robots.txt have thousands of sensitive items on it is a generally bad thing.

These are the commits that remove the sitemaps:

  - Opinions: https://github.com/freelawproject/courtlistener/commit/d57ef3fe925557f8ba0ef395d5479b9e7bd84a28
  - RECAP: https://github.com/freelawproject/courtlistener/commit/5e3c9b6023057b7f580f90f05dfd649ffea95f9b

**Comment by mlissner** [comment]
One way forward...

## For opinions:

1. Make citation-based HTML pages

1. Make sitemaps with high-quality cases (SCOTUS + Appellate courts + Precedential only). This would make them faster.

## For RECAP Dockets

1. Make database-driven sitemaps for RECAP content, but only show items with more than so many views OR so many docket entries. Again, this reduces the problem space, I think.

## For both

1. Make sitemap.xml files for blocked opinions or blocked RECAP content so Google is encouraged to discover and crawl those.

**Comment by mlissner** [comment]
OK, one thing we can do better is have drastically bigger sitemaps. For a long time I've been making them smaller, thinking that *that* was the way to make them faster. I'm an idiot sometimes and the exact opposite is true. When you make sitemaps smaller, you still have to do the sorting, which takes 95% of the time. But instead of needing to do the sorting once for a large result set, you have to do it many times, because Google wants many sitemaps, not just the one big one.

Here's some fun proof. `params` is the solr params we use to generate sitemaps:

```txt
In [31]: params['rows']: 100000 

In [32]: t1 = time.time(); results = solr.query().add_extra(**params).execute(); t2=time.time(); print results.QTime; print t2-t1
16564
40.1681530476

In [35]: params['rows'] = 25000

In [36]: t1 = time.time(); results = solr.query().add_extra(**params).execute(); t2=time.time(); print results.QTime; print t2-t1
12852
17.0542151928

In [33]: params['rows'] = 1000

In [34]: t1 = time.time(); results = solr.query().add_extra(**params).execute(); t2=time.time(); print results.QTime; print t2-t1
9615
9.87752604485


```

So, [sitemaps can only have 50,000 items][1], but what's interesting here is that the Solr query takes 16s for 100,000 items, 12s for 25k items, and 10s for 1000 items. Converting from the Solr result to our Python object seems to take a while though (24s for 100,000 items, and 4s for 25k).

[1]: https://stackoverflow.com/a/34972582/64911

**Comment by mlissner** [comment]
OK, to fix the depth problem, you do a facet, and you're basically home. So instead of having a really long list of possible sitemap pages, we facet by court and that essentially divides the problem space by 200 or so. 

Thus, our sitemaps now live at something like:

 - sitemap.xml?p=1&court=cacd

This also seems to really help with performance, but I'm tired of this fight, so I also added a DB-backed cache, where we'll be caching these pages from now on. They will be cached in the DB for two weeks each. I had them in the regular memory-based cache previously, but they just take up space there. Why not put them in the DB cache instead? Forgot this was possible (and easy) in Django.

The one thing that gets worse in all of this is the sitemap index, which instead of just doing a count of every archive (RECAP, Opinions, Audio, People) now has to do a *facet* count of every court within each of those archives. Within the RECAP Archive, it has to do a faceted **group** query, which is...slow, about 40 seconds. But we'll cache this aggressively, and it's only one page, and I think we'll be OK.

**Comment by johnhawkinson** [comment]
I'm sorry I've been so distracted lately. I just want to state clearly my position: the idea that a sitemap should have individual items in it is wrong, wrong, wrong.

That's not how sitemaps work.

A sitemap should have the top-level URLs that lead to various sections of the site, but it should not be listing individual data resources. That is, no individual cases, dockets, oral arguments, people, APIs, anything like that.

Sitemaps should be small, they should notionally fit on one page.

However, maybe it is possible that some of this stuff belongs in subsidiary hierarchical sitemaps. I think that's probably wrong too, but I am cognizant of `curl -sL google.com/sitemap.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.google.com/schemas/sitemap/0.84">
  <sitemap>
    <loc>https://www.google.com/edu/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/gmail/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/forms/sitemaps.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/slides/sitemaps.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/sheets/sitemaps.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/drive/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/docs/sitemaps.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/get/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/flights/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/admob/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/business/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/analytics/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/services/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/partners/about/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/adwords/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/search/about/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/adsense/start/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/retail/sitemap.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/sitemap_search.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://www.google.com/webmasters/sitemap.xml</loc>
  </sitemap>
</sitemapindex>
pb3:~ jhawk$ 
```

**Comment by mlissner** [comment]
Can you share where you get this impression from? Sitemaps talk a lot about being able to support 50k items each. If the intent was that they only go to high-level areas of the site, then that'd never have been a part of the standard? 

I filed https://github.com/freelawproject/courtlistener/issues/870 to do a better job making at least opinions HTML-crawlable, but if you could provide something that backed up that this should only go to high-level areas of the site, that'd be super valuable. 

FWIW, the way these are implemented currently is that we have a sitemap index which points to paginated (and now faceted by court) sitemap pages, which list millions of pages on the site.

**Comment by mlissner** [comment]
Just did a big deployment that I think fixes the performance of this by:

 - faceting the sitemaps by court (so now they're paginated and faceted with `?court=ca1&p=2`)

 - making the items per page 10k instead of 250

 - caching all the sitemaps for two weeks and the sitemap index for one week

Leaving open for more discussion, but at least the thing that I thought was my goal is accomplished (fixing performance).

**Comment by mlissner** [comment]
@johnhawkinson waiting on your comment or lack thereof before closing this one. Do you know where you got the impression that sitemaps shouldn't have more than a few links? There's a blog post from Microsoft here that kind of gets into it:

https://blogs.bing.com/webmaster/2014/06/09/sitemaps-best-practices-including-large-web-sites/

The post kinda goes both ways. It talks about having a sitemap with 1.2 trillion entries, and about how billions of entries are relatively easy. But then it also talks about how you should only put your important content in the sitemap, which is a different tune. 

I think we could be choosier about which cases go in our sitemaps (maybe only bigger dockets and more important cases?), but I think in general having big ones is the right approach.

**Comment by mlissner** [comment]
OK, closing this out. You know where to find me.
