### ISSUE TITLE
Add sealed document support to the data model

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#897]
This should be fairly simple. We just need to add a field to the RECAP Document model for `is_sealed`. In the UI we can do nothing for now, but the sooner we start keeping track of this in the DB, the sooner we can start doing good things with this information.

**Comment by johnhawkinson** [comment]
Err. You need more than that.
Is the document sealed? Is the entire docket entry sealed? Is the entire *docket* sealed? All are possible.

What's the intended application for this? Free looks and other specially logged in users?

**Comment by mlissner** [comment]
For now, this can just handle whether documents are sealed. There's two times I see this coming up:

1. When we scrape documents en masse, some of the documents say, "No download for you, this is sealed" or whatever. When that happens currently, we just give up and move on. It'd be better to mark the document as undownloadable. 

2. When documents get retroactively sealed, I just remove them from RECAP, leaving behind a minimal stub. That's...OK, but I don't like how I am deleting info and not leaving any trace of the change. It'd be better to delete the document and then mark it as sealed. (Still better would be to keep the data somehow and to also mark it as sealed, but I don't want to think about how that'd work with the APIs and whatever else.)

I think for these use cases it should work well. I could also see this being important at the docket level though I can't think of a time that I had to remove an entire docket due to it being sealed. I'm not sure what purpose it'd serve at the docket entry level (I think we could just mark the individual documents as sealed and be done with it).

In any case, this is a "progress-not-perfection" bug. For now I really just want somewhere that I can flag things when I learn that they're sealed retroactively.

**Comment by mlissner** [comment]
This is now in place. You can see it in effect here:

https://www.courtlistener.com/docket/5338155/377/united-states-v-carpenter/

And here: 

https://www.courtlistener.com/docket/5338155/united-states-v-carpenter/?filed_after=&filed_before=&entry_gte=377&entry_lte=377&order_by=asc

**Comment by johnhawkinson** [comment]
It sounds like (1) and (2) are different cases, so should be recorded differently.
Not deciding to record them differnetly now may viewed as an annoyance later.


I worry a little bit that sometimes it's hard to tell from the "No download for you" message.
For instance:

<img width="767" alt="screen shot 2018-10-29 at 21 08 56" src="https://user-images.githubusercontent.com/1270718/47689186-2d4c1f00-dbbf-11e8-9c20-20b7dfbdfd19.png">
<img width="788" alt="screen shot 2018-10-29 at 21 09 10" src="https://user-images.githubusercontent.com/1270718/47689187-2d4c1f00-dbbf-11e8-807e-5521b97d0890.png">
<img width="805" alt="screen shot 2018-10-29 at 21 09 28" src="https://user-images.githubusercontent.com/1270718/47689188-2d4c1f00-dbbf-11e8-858b-1d3d81002332.png">
<img width="551" alt="screen shot 2018-10-29 at 21 10 09" src="https://user-images.githubusercontent.com/1270718/47689189-2d4c1f00-dbbf-11e8-93be-884806a1c7b2.png">
<img width="784" alt="screen shot 2018-10-29 at 21 10 17" src="https://user-images.githubusercontent.com/1270718/47689190-2d4c1f00-dbbf-11e8-9bd9-327005b7c55f.png">

Presumably also juriscraper should get an update to deal with this in relevant parsers (attachment page?), unless that already happened while my head was turned.

**Comment by mlissner** [comment]
I think the Juriscraper part will come later, yeah. I think we know how to identify these error strings pretty well with regexes already, so it shouldn't be terribly difficult, but it's not the priority just yet. I've filed this bug in the meantime though: https://github.com/freelawproject/juriscraper/issues/238
