### ISSUE TITLE
Docket report without parties included deletes parties from CourtListener

### ISSUE THREAD

**Issue by s-zeid** [freelawproject/courtlistener#929]
If I run a docket report with "Parties and counsel" and "Terminated parties" unchecked, then the "Parties and Attorneys" tab disappears from the CourtListener docket.

**Steps to reproduce:**

1.  View any docket on CourtListener _which has a non-empty parties list_, click "View on PACER", and log in if necessary.
2.  On the docket search form, uncheck "Parties and counsel" and "Terminated parties" and leave all other fields intact.
3.  Click "Run Report".
4.  Wait for RECAP to capture the report.

**Expected behavior:**  The list of parties in CourtListener is left intact.

**Actual behavior:**  The parties list in CourtListener is deleted.  A new docket report with with "Parties and counsel" and "Terminated parties" checked is required to restore the list.

**Use case:**  The list of parties alone can bring even a docket report with zero matching documents above one "page".  To save money, I want to run a docket report starting from the first document number not listed in CourtListener and without the list of parties.

**Comment by johnhawkinson** [comment]
This seems like a new(ish) bug. Certainly running the DR without Parties is a very common case and historically did't delete parties.

**Comment by mlissner** [comment]
I'll take a look. Haven't touched this code though, so a bit surprising to see a change here.

**Comment by mlissner** [comment]
Seems this must not be an issue. Closing.
