### ISSUE TITLE
Investigate using CursorPagination for big (or all) tables in the API

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#930]
We have two problems with our API right now performance wise (that I want to investigate here):

1. Looking briefly at our performance highlights in AWS, it looks like our API requests spend a lot of time doing `SELECT Count(*)` queries. These queries are needed to do pagination of the API so you can know how many pages there are. 

2. Doing deep pagination (onto page 1,000, say) causes performance degradation. We currently have a warning about this in the docs:

    > When doing deep crawls of the data, going to very high page numbers will incur increasingly bad performance. This is common in databases because to go to a high page number means sorting the entire data set, then counting to the correct location. Page 50 isn't a big deal. Page 2,000 starts getting slower. 

The solution to both of these issues appears to be to use cursor-based pagination, as described here:

https://www.django-rest-framework.org/api-guide/pagination/#cursorpagination

There are a few non-backwards compatible limitations though:

1. It only supports fields that don't change and are unique, so some of our ordering fields won't be possible. 

2. You can't go to an arbitrary page number of the results, and can only go to the next or previous page.

3. Obviously, perhaps: Our current page numbering scheme (`&page=xx`) won't work anymore.

So I think this is probably worth doing, but probably worth calling API version 4.0 (we're at 3.7 now). I want to do some more investigation to see if there's a way we could enable more than one pagination type for an endpoint, as a way of phasing out the old version, but I'm not sure how that'd work.

**Comment by mlissner** [comment]
OK, turns out this *doesn't* use DB cursors, but uses DRF "cursors", that work like this: https://use-the-index-luke.com/no-offset

**Comment by mlissner** [comment]
@albertisfu, when we do the API v4, I think this is probably important to do as well.

**Comment by mlissner** [comment]
Well, the `docket-entries` and `recap-documents` API endpoints are now so slow you can't query their root URLs and they only work when filtered. Good thing we're working on API v4.

**Comment by mlissner** [comment]
Hm, well, all of these solutions aren't that great. Two thoughts:

1. Is it possible to add a second sort parameter to the pagination so that when it's null it uses the second one? We could use `id` for that, right?

2. If that's not possible, what about just using cursor pagination on some of the fields while maintaining the current ones? Does DRF allow multiple types of pagination on a view? 

I like the idea of a middleware. Nice idea.

**Comment by mlissner** [comment]
That sounds like a decent solution to me. I think filtering and deep pagination are more important than sorting, so if only some of our fields can be used to do deep pagination, we can just document that and that should work well for folks.

**Comment by mlissner** [comment]
Fair to close this now, @albertisfu?

**Comment by albertisfu** [comment]
Yeah, closing it!
