### ISSUE TITLE
Updates seen in RSS feeds don't seem to be creating alerts

### ISSUE THREAD

**Issue by csnardi** [freelawproject/courtlistener#934]
Not sure if this is court-specific, but a case I have an alert set for in the Southern District of Indiana had new docket entries. The entries show up on the Court's RSS feed, but the docket on CourtListener has not been updated, nor have I gotten any messages from the alert.

**Comment by johnhawkinson** [comment]
Can you give a specific example, please, e.g. docket number and specific RSS entries?

I think we don't currently support non-document docket events, which may likely be the issue here?

**Comment by csnardi** [comment]
https://www.courtlistener.com/docket/8120845/ is the case, currently in the RSS feed:

```rss
<item>
<title>
1:18-cv-03368 MCCALLEY et al v. CARMEL CLAY SCHOOL CORPORATION et al
</title>
<link>
https://ecf.insd.uscourts.gov/cgi-bin/DktRpt.pl?88860
</link>
<description>
[Notice of Service of Initial Disclosures] (<a href="https://ecf.insd.uscourts.gov/doc1/07317106546?caseid=88860&de_seq_num=65" >19</a>)
</description>
<guid isPermaLink="true">
https://ecf.insd.uscourts.gov/cgi-bin/DktRpt.pl?88860&65
</guid>
<pubDate>Fri, 01 Mar 2019 20:33:48 GMT</pubDate>
</item>
```

**Comment by johnhawkinson** [comment]
Well. It does not appear to be the problem I referred to.
Furthermore, the parser finds this properly:

```
(juriscraper) pb3:juriscraper jhawk$ python -m juriscraper.pacer.rss_feeds -v insd | less
Querying RSS feed at: https://ecf.insd.uscourts.gov/cgi-bin/rss_outside.pl
Parsing RSS feed for insd
Got 347 items
Here they are:
```
…
```js
  { u'assigned_to_str': u'',
    u'case_name': u'MCCALLEY v. CARMEL CLAY SCHOOL CORPORATION',
    u'cause': u'',
    u'court_id': u'insd',
    u'date_converted': None,
    u'date_discharged': None,
    u'date_filed': None,
    u'date_terminated': None,
    u'demand': u'',
    u'docket_entries': [ { u'date_filed': datetime.date(2019, 3, 1),
                           u'description': u'',
                           u'document_number': u'19',
                           u'pacer_doc_id': u'07307106546',
                           u'pacer_seq_no': u'65',
                           u'short_description': u'Notice of Service of Initial Disclosures'}],
    u'docket_number': u'1:18-cv-03368',
    u'jurisdiction': u'',
    u'jury_demand': u'',
    u'nature_of_suit': u'',
    u'pacer_case_id': u'88860',
    u'parties': None,
    u'referred_to_str': u''},
```

So, some kind of issue when CourtListener integrates the parsing results, or a server operational concern. Those are for Mike, I think; Mike?

**Comment by mlissner** [comment]
I believe this is now fixed. Thanks for bringing this to my attention. Unfortunately, we won't send an alert for the things we missed (because they've scrolled off the bottom of the feed), but we should get alerts going forward. So sorry about this!
