### ISSUE TITLE
Some PDFs use symbol fonts

### ISSUE THREAD

**Issue by willglynn** [freelawproject/courtlistener#937]
One such [example opinion](https://www.courtlistener.com/opinion/3135330/people-v-allen/) illustrates the issue:

```
remanded for a new trial, holding that defendant had Aadequately
alleged plain error@ where the trial court abused its discretion in
…
442, 446. We granted the State=s petition for leave to appeal under
```

Open double quotes are `A`, closing double quotes are `@`, curly apostrophes are `=`. Ideally these would be transcribed using their Unicode counterparts.

The upstream PDF, both [the original](http://www.illinoiscourts.gov/Opinions/SupremeCourt/2006/June/99977.pdf) and [the CL copy](https://www.courtlistener.com/pdf/2006/06/02/people_v._allen.pdf), display correctly:

<img width="706" alt="" src="https://user-images.githubusercontent.com/118362/54286588-1efd0f00-4572-11e9-8d57-5a69fc45b0c3.png">

But they don't copy-paste correctly! The highlighted section pastes as `Aadequately alleged plain error@`, exactly as described. So what's going on?

Those incorrect characters are rendered using a font named `ABCGOP+WPTypographicSymbols`, which is as the name indicates is in fact a symbol font:

<img width="240" alt="" src="https://user-images.githubusercontent.com/118362/54286757-7307f380-4572-11e9-91f9-595fc0e2b648.png">

Some component inside CL converts PDFs to plain text. That component should be extended to recognize this font, and then to apply a translation table mapping the symbols in this font to their Unicode equivalents.

**Comment by willglynn** [comment]
This took a lot of staring at Unicode charts to make, but I'm pretty happy with this map from "WP TypographicSymbols" symbol characters to UTF-8:

```json
{
  " ": " ",
  "!": "•",
  "\"": "◦",
  "#": "◼︎",
  "$": "・",
  "%": "⁎",
  "&": "¶",
  "'": "§",
  "(": "¡",
  ")": "¿",
  "*": "«",
  "+": "»",
  ",": "£",
  "-": "¥",
  ".": "₧",
  "/": "ƒ",
  "0": "ª",
  "1": "º",
  "2": "½",
  "3": "¼",
  "4": "¢",
  "5": "²",
  "6": "ⁿ",
  "7": "®",
  "8": "©",
  "9": "¤",
  ":": "¾",
  ";": "³",
  "<": "‛",
  "=": "’",
  ">": "‘",
  "?": "‟",
  "@": "”",
  "A": "“",
  "B": "–",
  "C": "—",
  "D": "‹",
  "E": "›",
  "F": "○",
  "G": "□",
  "H": "†",
  "I": "‡",
  "J": "™",
  "K": "℠",
  "L": "℞",
  "M": "●",
  "N": "◦",
  "O": "■",
  "P": "◼︎",
  "Q": "☐",
  "R": "◻︎",
  "S": "‒",
  "T": "ﬀ",
  "U": "ﬃ",
  "V": "ﬄ",
  "W": "ﬁ",
  "X": "ﬂ",
  "Y": "…",
  "Z": "$",
  "[": "₣",
  "\\": "₢",
  "]": "₠",
  "^": "₤",
  "_": "‚",
  "`": "„",
  "a": "⅓",
  "b": "⅔",
  "c": "⅛",
  "d": "⅜",
  "e": "⅝",
  "f": "⅞",
  "g": "Ⓜ",
  "h": "℗",
  "i": "€",
  "j": "℅",
  "k": "℆",
  "l": "‰",
  "m": "№",
  "n": "‐",
  "o": "¹",
  "p": "🄷🅃",
  "q": "🄵🄵",
  "r": "🄲🅁",
  "s": "🄻🄵",
  "t": "🄽🄻",
  "u": "🅅🅃",
  "v": "♼",
  "w": "₩",
  "x": "₦",
  "y": "₨",
  "z": "🅫",
  "{": "🅪",
  "|": "▶️",
  "}": "⏹",
  "~": "⏸",
  "\u0080": "⏪︎",
  "\u0081": "⏩︎",
  "ƒ": "⏮",
  "ˆ": "Ǌ",
  "‐": "¥",
  "‚": "⏺",
  "„": "⏭",
  "†": "𝄞",
  "‡": "𝄢",
  "…": "⏏️"
}
```

I'm not 100% confident in the last two hyphens, but even if they're backwards, at least this map makes them _some kind_ of hyphen instead of leaving them as `S` or `n`. Likewise `p`-`u` are printable representations of various control characters for which I was unable to find Unicode counterparts, but `🄽🄻` is still more meaningful than `t`.

Looks like the conversion pipeline uses `pdftotext` (with alternatives contemplated in #123) so fixing this would have to happen there. Is the `pdftotext` currently in use the one from the Xpdf package? Which version should I look to patch?

**Comment by mlissner** [comment]
Here's the version info from the server:

```
↪ pdftotext -v
pdftotext version 0.24.5
Copyright 2005-2013 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
```

I have to say though, we don't usually compile our own versions of things. Is it crazy to patch it and also provide a PR for CL to fix this? 

You might also take a look at the Mojibake converter we have if you didn't bump into that already. It was years ago that I made a similar mapping to the one above, but I have a feeling you'll do a better job of it.

**Comment by willglynn** [comment]
Yeah, my intent would be to land a changeset upstream. There's a few different `pdftotext`s floating around though, so I wanted to know which one 😄 

As for mojibake: `pdftotext` is correctly translating the `WinAnsi` character set to UTF-8. It's just that, in this font, `A` renders as `“`, and anyone who wrote `A` really means `“`. The font almost works like a different character set, which needs a separate conversion to UTF-8, but only for the parts of the PDF which use that font. The argument for performing this conversion inside `pdftotext` is that `pdftotext` has this information and is discarding it.

An alternative approach would be a PDF to PDF converter which performed this translation ahead of time, substituting all characters written in this font into their UTF-8 equivalents per the table above. `pdftotext` could then do a naïve conversion on this rewritten PDF and we'd get the right output. That's probably more difficult, it's definitely less useful (no one _wants_ `pdftotext` to output `A` instead of `“` in this context), but it seems like a viable alternative.

**Comment by willglynn** [comment]
Poppler's `pdftotext` special cases Zapf Dingbats, another symbol font. I was able to add the WPTypographicSymbols translation I seek in much the same way. [This patch](https://gist.github.com/willglynn/3986f6508e07fae01130b78dba2b6d37) needs some cleanup, but it takes us from:

```
    The court Areject[s] the dissent=s attempt@ (slip op. at 11) to
distinguish Estelle. The court=s rejection is made without any real
discussion of the salient points of the United States Supreme Court=s
analysis as it fails to discuss the importance the invited-error doctrine
had on the United State Supreme Court=s analysis in refusing to
excuse the defendant=s procedural default.
```

to:

```
    The court “reject[s] the dissent’s attempt” (slip op. at 11) to
distinguish Estelle. The court’s rejection is made without any real
discussion of the salient points of the United States Supreme Court’s
analysis as it fails to discuss the importance the invited-error doctrine
had on the United State Supreme Court’s analysis in refusing to
excuse the defendant’s procedural default.
```

**Comment by willglynn** [comment]
I opened an upstream issue: https://gitlab.freedesktop.org/poppler/poppler/issues/740

**Comment by mlissner** [comment]
That looks great. I was trying to refer you to this bit of code:

https://github.com/freelawproject/courtlistener/blob/3febc8d5e318f2c420f49fce8b077c60a3172a57/cl/lib/mojibake.py

It's old code, so apologies for its crappiness, but the point was that it'd be nice to fix this in CourtListener too because otherwise, it could be years until we get the upstream fix.

**Comment by willglynn** [comment]
Thing is, the correct interpretation of "A" depends on which font was in use. Sometimes "A" means "A", other times "A" means "double quote". All `pdftotext` tells us is "A", and while we could replace A with double quotes, we don't know which need replacing and which don't. This leaves us with:

1. Making `pdftotext` distinguish these cases, or
2. Creating an entirely new tool and running it before `pdftotext` (the [alternative approach](
https://github.com/freelawproject/courtlistener/issues/937#issuecomment-472669932) above)

I favor landing a changeset upstream, and then either waiting for the usual channels to do their thing or backporting it and having CL deploy that modified `pdftotext` package.

**Comment by mlissner** [comment]
Yeah, makes sense. Well, let's push upstream and then we'll see how hard it is to get it backported. Thanks for catching and working on this. I have a feeling you'll be discovering our unicode bug soon...:(

**Comment by willglynn** [comment]
Would `docker run` be out of the question? https://github.com/willglynn/wordperfect-pdftotext is a minimal repo consisting of my patch and a `Dockerfile`. The resulting image weighs <100 MB, and it fully encapsulates a WordPerfect-aware `pdftotext` and all its dependencies.

**Comment by mlissner** [comment]
Oh docker, what a world. We're not using Docker yet unfortunately, nor are we using microservices. 

I guess we could start using docker for this purpose, but it seems like trouble, even though I appreciate you throwing this together. Just seems...kind of like a lot for something so minor. I don't think I'd want to support this for years.

**Comment by willglynn** [comment]
Fair enough, just a thing I thought about in light of discussion in the upstream issue and in #936. I'll continue discussion of deployment strategies over there.

**Comment by mlissner** [comment]
I really appreciate your comment over there!

**Comment by mlissner** [comment]
We won't be upgrading pdftotext any time soon, I don't think, so I'm going to close this. Thank you though!
