### ISSUE TITLE
Dockerize solr on new server

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#939]
This is part of issue #936. I'm not sure how this will shake out, but there's a lot going on here:

1. Solr is currently overtaxing the system its on and needs to get moved quickly.

1. Our version of solr is very old and a replacement would probably do wonders. Currently version upgrades are very hard.

1. Solr has containerized packages now! But I have no idea how to use them. Still check this out: https://lucidworks.com/2015/11/03/solr-on-docker-2/. Oof, 2015, still, the latest versions are ready to roll. Alas, the version we need is not in there.

1. We need to get KVM or Xen sorted out for the new server. Having read the Xen docs (which are exhaustive and exhausting) and the KVM docs (which are slim but simple), I am strongly leaning towards KVM. Seems the performance is nearly the same, and AWS is using both, so it's just a question of simplicity. Still, I'm baffled at the paucity of good docs in this area.

So here's the process I have in mind:

1. Create a new VM for Solr and give it an ungodly number of cores and memory. For the moment we don't have anything else on the new server, so let's see what Solr can do when it has too much hardware. 128 cores? Sure.

1. Once the new VM guest is ready, see how hard it is to create an ansible script getting solr installed. I think we have this roughly ready to go already in various places. Pull it out and give it a new repo. At the same time, this will move things like the solr configs out of CourtListener (helping issue #936). 

1. Deploy Solr using Ansible on the new Solr server.

1. Great, but now you need the indexes. There's two approaches here. Either, we can rebuild them or we can copy them from the old server. Copying is easier and faster, but it involves downtime. I think it's worth it, so I think I'll get this scheduled with our API users.

1. Once the indexes are moved, it's time to start re-routing traffic via our settings files in Django.

**Comment by mlissner** [comment]
Welp, this is currently chugging along:

```
sudo virt-install --virt-type kvm --name solr-2019-03-19 --memory 131072 --cdrom ubuntu-18.04.2-live-server-amd64.iso --disk path=/dev/vg2/lv2-search,format=raw --os-variant=ubuntu18.04 --vcpus=64 --console pty,target_type=serial
WARNING  Graphics requested but DISPLAY is not set. Not running virt-viewer.
WARNING  No console to launch for the guest, defaulting to --wait -1

Starting install...
Domain installation still in progress. Waiting for installation to complete.
```

Seems like it'll run until I tell it to stop. I have no idea what it's doing though because it doesn't give me a console. This seems needlessly complicated. From what I can tell the solution is to use virt-viewer with x11 forwarding to my laptop, but...huh? There's such a thing as command line installs, so why doesn't it just do that for me? I'm confused and annoyed.

**Comment by mlissner** [comment]
So eight days later and what do I have to show for this project? A lot of frustration and very little progress. It turns out that Xen has terrible docs and KVM has bad docs. Figuring out even the most basic things with either of them is just a huge PITA and I've wasted a lot of time trying to figure this out. One of the biggest issues is that all of the documentation I've been able to find is terribly outdated. I think either:

1. All the action moved somewhere else (like docker), or
2. The remaining expertise has moved entirely in-house at places like Amazon and Rackspace, leaving the public docs to moulder. 

Whatever the case, I can't make VMs work without decent documentation, so screw that. I'm pivoting to docker, where I think the action went, and the documentation is wonderful and the tools powerful and I'm generally enjoying it. Hell, even Intellij has a docker integration. 

Lots of things to figure out, but I'll be working through it over the next couple days.

**Comment by mlissner** [comment]
@davidxia, @voutilad, @umeboshi2, this ticket was previously about putting Solr in a VM, but that proved impossible, so I'm now focused on dockerizing it. This is my first time doing much with docker, so if any of you have time to watch my rantings on this ticket and perhaps have time to chime in, I'm sure you'd have a lot of contribute. For now I'm just ramping up dockerization (I read docs for about eight hours today), but I'm sure I'll be posting a lot here tomorrow and over the next couple days.

Thanks for any input you have time to share as I figure this all out.

**Comment by mlissner** [comment]
For posterity:

 - The command that seems to create VMs for KVM is:

        sudo virt-install --virt-type kvm \
            --name solr-`date -I` \
            --memory 131072 \
            --location http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/ \
            --disk path=/dev/vg2/lv2-search,format=raw \
            --os-variant=ubuntu18.04 \
            --vcpus=64 \
            --nographics \
            --extra-args='console=ttyS0' \
            --network bridge=br0

 - The thing that got us finally too stuck to proceed and too frustrated to breathe was getting a bridged and bonded network connection. Should be simple; isn't.

**Comment by mlissner** [comment]
And cc @willglynn too, in case he has input to add. It's wonderful to have so many knowledgeable people around.

**Comment by mlissner** [comment]
Cool, so as of https://github.com/freelawproject/courtlistener-solr-server/commit/4aaa39bb8fd5551276c855a3e2644d62d6341940, we have a functional solr docker image with somewhat decent documentation. 

A couple pieces left:

 - Get logging set up properly with the correct retention policies
 - Formalize according to https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
 - Deploy to server?

What else should I be thinking about? This feels pretty good to me.

**Comment by willglynn** [comment]
@mlissner One thing that's easy to overlook is that you now have another userland to maintain. That container has a separate `glibc`, a separate `openssl`, a separate set of root certificates that it trusts, etc. Patching a container is straightforward – it's just a deploy like any other, you build and test and start running the new image – but keeping a container up to date likely requires adapting existing procedures or creating new ones.

Small organizations usually settle on one or more "blessed" base images, and then rebuild downstream images as needed. Large organizations with compliance needs usually employ [image scanning services](https://anchore.com) or [image scanning tools](https://github.com/coreos/clair). No matter how you identify that you need to make a change though, it always comes down to building and deploying a new image, so focus on operationalizing a process for that first. Rolling out a new image should be entirely un-scary, and making that easy is the foundation for everything else.

As for logging, I imagine you've found them already, but do [check out the logging drivers](https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers) and consider which best fits your needs. Docker lets me run arbitrary programs and connect them to whichever logging infrastructure I'm using today, and for that it has my appreciation 😃

**Comment by mlissner** [comment]
For the moment it's just Solr which has really low security risks. I'm also somewhat satisfied that these aren't really accessible to the public except through one port typically. Like, I'm not too stressed about a solr machine that's only accessible on our local network. 

Good to think about though for sure. Still a little scary, but rolling out a new image seems simple enough. Stop one, pull the latest, relaunch the latest.

Haven't figured out logging drivers yet. That's on deck.

**Comment by mlissner** [comment]
Huh. Logging is much (*much*) easier than I expected, considering how loathe docker usually is to touch the host file system. Awesome. For now I'm just going to use the `--log-driver` command flag, and in #943 we'll ensure we abide by our privacy policy (delete logs after 12 weeks or before).

I forgot I also have to figure out networking, but the rest is basically there. Time to deploy this thing.

**Comment by mlissner** [comment]
So a couple things to mention:

1. I have this command I'm using to move indexes from one machine to the other:

        rsync -av --progress --delete /sata/solr-data/ 192.168.0.243:/home/mlissner/solr/recap

    It seems to work. The plan is to run it with the index live to get the bulk of data across, then to run it again to do a diff with the index momentarily stopped. Seems to work nicely.

1. After the index is stopped, I'm having to run: `sudo chown -R 101:101 my-index` on the transferred files to make them accessible by docker. This makes me uncomfortable. I'll be researching this further.

**Comment by mlissner** [comment]
Got a good fix for item 2 above. It's in the docs. Basically, we create a new group in the container for Solr, give the volume access to that group's gid, and then set the sticky bit (I think?) so that future files and directories in that volume continue having good access for that group.

**Comment by mlissner** [comment]
Remaining todos:

 - [ ] figure out auto-start for docker images after server reboot

 - [ ] get the RAID controller fixed over in #946. 

 - [ ] Launch

**Comment by mlissner** [comment]
This is the process I did for the RECAP core:

```
# Set up the directory in advance:
rsync -av --progress --delete /sata/solr-data/ 192.168.0.243:/search/recap
sudo chown -R :1024 /search/recap
sudo find /search/recap -type d -exec chmod g+s {} \;
sudo find /search/recap -type d -exec chmod 775 {} \;
sudo find /search/recap -type f -exec chmod 664 {} \;

# Stop solr, copy over the clean files
sudo service solr stop
rsync -av --progress --delete /sata/solr-data/ 192.168.0.243:/search/recap

# Set the permissions again
sudo chown -R :1024 /search/recap && \
sudo find /search/recap -type d -exec chmod g+s {} \; && \
sudo find /search/recap -type d -exec chmod 775 {} \; && \
sudo find /search/recap -type f -exec chmod 664 {} \; && \

# Start docker
sudo docker run --memory 100g --cpus 32 --volume /opt/solr/solr/cores:/etc/opt/solr:ro --volume /search/:/var/opt/solr/indices  -p 8983:8983 --log-driver journald --name solr --network cl_net_overlay --restart unless-stopped -d freelawproject/solr

sudo chown -R :1024 /search/recap && sudo find /search/recap -type d -exec chmod g+s {} \; && sudo find /search/recap -type d -exec chmod 775 {} \; && sudo find /search/recap -type f -exec chmod 664 {} \; && sudo docker run --memory 100g --cpus 32 --volume /opt/solr/solr/cores:/etc/opt/solr:ro --volume /search/:/var/opt/solr/indices  -p 8983:8983 --log-driver journald --name solr --network cl_net_overlay --restart unless-stopped -d freelawproject/solr


# Test things
curl '192.168.0.243:8983/solr/recap/select?q=turkey&wt=json&indent=true'

# If this fails, restart solr
sudo service solr start

# Swap in the new config file
:w
cl && sudo touch apache/django.wsgi
```

This needs to be repeated for all the other cores, though they don't have individual settings for their host server, since I've never needed to split them up.

**Comment by mlissner** [comment]
OK, so this is now done for the other cores as well. A couple tweaks from the first time through:

1. I tried restarting docker using the `docker restart` command. It failed with:

    ```
    ↪ sudo docker restart solr
    Error response from daemon: Cannot restart container solr: failed to get network during 
    CreateEndpoint: network ozziu0w6zglgyusdnwkwkixdx not found
    ```

    Who knows what's up with that. I just stopped docker, rm'ed the old `solr` container and started a new one with:

    sudo docker run --memory 100g --cpus 32 --volume /opt/solr/solr/cores:/etc/opt/solr:ro --volume /search/:/var/opt/solr/indices  -p 8983:8983 --log-driver journald --name solr --network cl_net_overlay --restart unless-stopped -d freelawproject/solr:0.3.3

    That worked.

1. I stopped celery before this one and started it afterwards.

1. I checked search via the front end and the homepage before and after running this.

I think we're in business with the exception of #951, which looks to be annoying.
