### ISSUE TITLE
SolrTestCase trys to copy index from hard-coded location

### ISSUE THREAD

**Issue by malteos** [freelawproject/courtlistener#950]
Hi Mike,

I'm writing a unit test for my MoreLikeThis-based recommender system. However, all Solr-related unit test fail on my machine because `create_temp_solr_core` trys to copy a Solr Index from a hard-coded location `/usr/local/solr/example/solr/collection1`.

```python
# cl/lib/solr_core_admin.py: create_temp_solr_core
    # Copy collection1 directory to core_name directory
    shutil.copytree(
        os.path.join(os.sep, 'usr', 'local', 'solr', 'example', 'solr', 'collection1'),
        core_path,
        symlinks=True,
    )
```

I'm using the Docker container to run Solr and therefore the location does not exist. Can this be rewrite such that the tests work as well without installing Solr locally?

Best,
Malte

**Comment by mlissner** [comment]
Hm, yeah, that's not ideal, eh? I'm not sure the best way to solve this. Are you using the new docker image that I created over in https://github.com/freelawproject/courtlistener-solr-server?

**Comment by malteos** [comment]
I'm currently using `freelawproject/solr:0.2`. With my PR I'm able to run the test on dockerized Solr.

**Comment by mlissner** [comment]
Holy cow! That's great to hear. I'll check this out shortly. I'd be thrilled to drop my locally installed copy of Solr in order to switch to freelawproject/solr. I'm so happy you're paying attention to the dockerization process.

**Comment by mlissner** [comment]
Holy cow! That's great to hear. I'll check this out shortly. I'd be thrilled to drop my locally installed copy of Solr in order to switch to freelawproject/solr. I'm so happy you're paying attention to the dockerization process.

**Comment by malteos** [comment]
PR merged.
