### ISSUE TITLE
Get Matomo going again

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#952]
We currently don't have piwik running because it's on the server that went down. It's probably a good idea to get it going again, probably in docker, since it requires MySQL. There appears to be an image for it that we could probably use:

https://hub.docker.com/_/matomo/?tab=description

Also worth doing:

 - [ ] Check through old Github tickets and see what problems have been resolved with the old Piwik install.

**Comment by malteos** [comment]
You can find several `docker-compose` files In the official Matomo repository:

- https://github.com/matomo-org/docker/tree/master/.examples

There are examples for Apache + Nginx + Helm available.

**Comment by mlissner** [comment]
I'm also looking at the one here, which looks like it solves a lot of problems (and adds some complexity): https://github.com/crazy-max/docker-matomo

**Comment by mlissner** [comment]
Spent some time on this today. Some notes:

1. We currently use the `proxypass` argument to Apache to set it up as a reverse proxy. That's sort of OK, but it requires that we map a path from www.courtlistener.com/piwik to a server. Previously, it mapped to piwik.courtlistener.com, a DNS entry that didn't exist, but that we faked using `/etc/hosts` on that particular server.

    The better way to do this is to actually set up a DNS entry for matomo.courtlistener.com, tweak our front end django code to use that instead of courtlistener.com/piwik/, and then set up a virtual host to proxy requests to that domain so they go to the correct server.

    One additional benefit is that if we do it this way, we get proper SSL for matomo.courtlistener.com

2. I played with the docker compose file I mentioned yesterday. It looks pretty darned good, but it definitely has some complicated bits. I trimmed it down a bit to remove redis and traefik at first, got it working, and now I think I have an understanding of it. I think with the proper proxy and DNS settings, it should just work.

So steps moving forward:

1. Get the DNS entry in place. I'm so bad at DNS I forget if this is a CNAME or something else. I suppose I'll figure it out and set it with a lot TTL so that I can handle the mess if I get it wrong.

1. Create and deploy a new virtualhost config file.

Also: Does our HSTS configuration make this whole thing harder? We'll soon find out.

**Comment by mlissner** [comment]
OK, created an A record for matomo.courtlistener.com to point to our server.

**Comment by mlissner** [comment]
So I set up what I thought was the proxy rule in our Apache server, but it definitely did not do what I wanted it to. Instead of proxying traffic, it crashed Apache. Apparently if this is your architecture:

Apache Proxy --> Matomo

And if you want the proxy to have a secure connection (which we have to have due to being on the HSTS list), then the certificate configuration has to be done at Apache, not at Matomo, making Apache your HTTPS termination. 

So I think that adds a layer of complexity. The next layer, of course, is that if you want the connection between Apache and Matomo to be secure, you are going to have a problem because Let's Encrypt won't be able to work properly from the Matomo server. 

Upshots:

1. I plan to set up let's encrypt for matomo.cl.com on the apache server.
2. I plan to not encrypt the traffic between that server and Matomo. I suppose I could do this with a self-signed cert that has a really long expiration date, but that just seems difficult, especially if it's dockerized. (Plus, the benefit is small.)

**Comment by mlissner** [comment]
OK, I was able to add matomo.cl.com to our certificate:

```
↪ sudo certbot --expand -d matomo.courtlistener.com,courtlistener.com,www.courtlistener.com
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator apache, Installer apache
Renewing an existing certificate
Performing the following challenges:
http-01 challenge for matomo.courtlistener.com
Waiting for verification...
Cleaning up challenges

We were unable to find a vhost with a ServerName or Address of matomo.courtlistener.com.
Which virtual host would you like to choose?
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1: www.courtlistener.com.conf     | www.courtlistener.com |       | Enabled
2: ssl-www.courtlistener.com.conf | www.courtlistener.com | HTTPS | Enabled
3: courtlistener.com.conf         | courtlistener.com     |       | Enabled
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Select the appropriate number [1-3] then [enter] (press 'c' to cancel): c
No vhost exists with servername or alias of matomo.courtlistener.com. No vhost was selected. Please specify ServerName or ServerAlias in the Apache config.
No vhost selected

IMPORTANT NOTES:
 - Unable to install the certificate
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/courtlistener.com/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/courtlistener.com/privkey.pem
   Your cert will expire on 2019-10-15. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"
10:49:42::mlissner@new-courtlistener::~ 
↪ sudo certbot certificates
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Found the following certs:
  Certificate Name: courtlistener.com
    Domains: matomo.courtlistener.com courtlistener.com www.courtlistener.com
    Expiry Date: 2019-10-15 16:49:18+00:00 (VALID: 89 days)
    Certificate Path: /etc/letsencrypt/live/courtlistener.com/fullchain.pem
    Private Key Path: /etc/letsencrypt/live/courtlistener.com/privkey.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

So that's good. Now onwards to adding a virtualhost for it that does the proxying and I think we should be off to the races.

**Comment by mlissner** [comment]
OK, getting apache configured properly was a pain, but you can see the history of that in the commit logs. Onwards to bringing up Matomo.

**Comment by mlissner** [comment]
So, I think this is working. Once I got apache working properly, I relaunched the compose file with a MySQL env variable set. Some results are coming in now, and I did a first-pass through the settings, but I want to check a few things to make sure they're working:

1. Traffic seems really low, some traffic must be missing.
2. I haven't gotten any stats yet for PDF downloads.
3. GeoIP might not be working yet?
4. Are report archives working?

I'll poke around a little more later, but this is nearly done.

**Comment by mlissner** [comment]
~Traffic seems really low, some traffic must be missing.~

Seems fine now that it's been running for a few minutes. 

~I haven't gotten any stats yet for PDF downloads.~

They're here.

~GeoIP might not be working yet?~

It is, more or less. The realtime map isn't working, but I don't much care. It never has.


~Are report archives working?~

Yep.

I think this is good enough for now.

**Comment by mlissner** [comment]
For future reference, this is how matomo was launched:

    sudo MYSQL_PASSWORD='XXX' docker stack rm --compose-file /opt/matomo/examples/compose/docker-compose.yml matomo

The password is in my vault.

**Comment by mlissner** [comment]
Well, re the previous comment, apparently that's correct, but note that the network needs to be set to `host` on the open port or else forget about it.
