### ISSUE TITLE
Update judge db with latest federal appointments (Trump and Obama, as appropriate)

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#959]
Not sure how much overlap this has with #958, but we should make sure that after we get the latest data from FJC, we also have all the latest judges. 

Probably the easiest canonical source for this is the senate judiciary committee's website: https://www.judiciary.senate.gov/nominations/judicial

But there are likely other sources too.

**Comment by jonashleyo** [comment]
Here's the file that was used.  The FJC provides a CSV with data on all Article III judges and from this list the judges that were already in CourtListner were subtracted to generate the attached file.

[missing.txt](https://github.com/freelawproject/courtlistener/files/3741617/missing.txt)
