### ISSUE TITLE
Bulk data contains invalid API urls

### ISSUE THREAD

**Issue by malteos** [freelawproject/courtlistener#969]
The bulk data for opinions (e.g. [ca1](https://www.courtlistener.com/api/bulk-data/opinions/ca1.tar.gz)) contains the invalid resource URLs (port 80 vs https):

```
{
  "resource_uri": "https://www.courtlistener.com:80/api/rest/v3/opinions/11/",
  "id": 11,
  "absolute_url": "/opinion/11/cianbro-corp-v-george-h-dean-inc/",
  "cluster": "https://www.courtlistener.com:80/api/rest/v3/clusters/11/",
  "author": null,
  "joined_by": [],
```

**Comment by mlissner** [comment]
I think this is actually solved already, just the data needs to be regenerated. I'm regenerating the dockets data now and will check it once complete. If it's good, I'll regenerate the opinions data as well. (Probably all of it wouldn't hurt, but that's a bigger job.)

**Comment by mlissner** [comment]
OK, dockets are complete. Onwards to the opinions!

**Comment by mlissner** [comment]
Opinions are now complete and fixed. I think that's all the requests you had, so please let me know if not.
