### ISSUE TITLE
Investigate using AWS for file storage

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#972]
Take a look at using AWS for storing all the files related to LASC (and maybe other projects?).

Can this integrate with Django, etc.

**Comment by flooie** [comment]
Currently investigating AWS server costs at a worst case scenario.  

1. Currently we estimate ~ 11,217,635 PDFs are in the system at any given time. 
2. We pulled 412 random documents to calculate the average size of a PDF.
3. The average size of a PDF in the sample was 0.587 MB.
4. This gives us a total PDF dataset of ~6.589 TB

More to come

**Comment by flooie** [comment]
Using [Amazon Calculator](https://calculator.s3.amazonaws.com/index.html)
A monthly estimate of 7 TB of storage with 1 mil requests = ~190 / month.

Happy to have someone double check my math.

**Comment by flooie** [comment]
Implementation of AWS PDF storage requires setting up AWS buckets correctly.  

First - we need to generate a bucket with the following name:
Go to S3
1) com-courtlistener-storage
2) Choose US-West S3 location.
3) Set permissions to not block all public access
4) Review and create bucket.

Leave S3- go to IAM and do some combination of the following.

1) Create group for project or use old group
2) Create policy from JSON below

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObjectAcl",
                "s3:GetObject",
                "s3:PutObjectAcl"
            ],
            "Resource": "arn:aws:s3:::com-courtlistener-storage/*"
        }
    ]
}
```

3) Attach policy to group. 
4) Add user to group.

Add users credentials to the private settings file.

**Comment by mlissner** [comment]
Is there more to do here? Seems like we can close this?
