### ISSUE TITLE
Matomo event tracking for recommendations

### ISSUE THREAD

**Issue by malteos** [freelawproject/courtlistener#974]
To evaluate the recommender system, we need to implement event tracking with Matomo (after #952). Setting the tracking up is quite easy and well explained in their documentary ([here](https://matomo.org/docs/event-tracking/#tracking-events) and [there](https://developer.matomo.org/guides/tracking-javascript-guide#manually-trigger-goal-conversions)).

You only must add an onClick-event into the corresponding template:

```html
<a href="#" onclick="_paq.push(['trackEvent', 'Menu', 'Freedom']);">Freedom page</a>
```

I suggest the following schema for the recommendations:

```
# click
['trackEvent', 'relatedOpinionClick', <algorithm>, <seed_opinion_id>, <recommended_opinion_id>, <recommended_opinion_rank>]

## example
['trackEvent', 'relatedOpinionClick', 'mlt', 1, 3, 4]

# views (measures views for CTR)
# triggered on every detail view
['trackEvent', 'relatedOpinionView', <algorithm>, <seed_opinion_id>, '<opinion_id1>,<opinion_id2>,...', <recommendations_count>]


## example
['trackEvent', 'relatedOpinionView', 'mlt', 1, '2,3,4,5,6', 5]
```

See also
- Implement result click tracking for search results to measure improvements to search algo #642

**Comment by nemobis** [comment]
Is this superseded? I see there Plausibile now on courtlistener.com rather than Matomo.

**Comment by mlissner** [comment]
Yep. It's all about Plausible now. Closing, but @malteos if you re-gain your interest in making this happen, I think Plausible's API is decent.
