### ISSUE TITLE
Create docker compose file for developers

### ISSUE THREAD

**Issue by mlissner** [freelawproject/courtlistener#999]
This is finally possible, I think. @malteos has a draft one that I'll be starting with. If it works well, I'll be landing it in CL and recommending it as our way to "get things done™". 

I have hope that after nearly a decade of wishing and sort of attempting to have a good, easy development environment, this will finally be the thing that makes it possible. 

(Previous attempts included all kinds of fun things. Virtual Machines, Vagrant, detailed Wiki instructions. Bleh.)

**Comment by mlissner** [comment]
(@malteos Assigning you so you can tell me when I do dumb things that should be done entirely different ways, like with the solr testing cores. I trust your wisdom!)

**Comment by mlissner** [comment]
This is largely done. Please see the numerous updates in DEVELOPING.md.

**Comment by malteos** [comment]
I just tried to run the `docker-compose` and encounter a few problems:

1) Absolute volume paths: I think it's bad practice to use absolute paths like in the `cl-solr` service:

```
        volumes:
            - /var/run/postgresql:/var/run/postgresql
```

This directory does exist on my host machine and I don't want docker to mess with my system directories. Also, you can assume that most people would just `git clone` the repo and then run `docker-compose`. Thus, the volume path should exist in the repo already. I recommend adding an empty directory to the repo (e.g., `docker/postgresql/run`).

2) Outside dependencies: Similarily, the service `cl-solr` uses a volume that mounts to the `courtlistner-solr-server` repo. Others might not have that repo on their machine or just in another directory. It would be better to mount those directories also relative to the cl repo.

3) DB is not initialized: `cl-celery` and `cl-django` fail with such an error message:

```
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/loaders/base.py", line 114, in init_worker
cl-celery        |     self.import_default_modules()
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/loaders/base.py", line 108, in import_default_modules
cl-celery        |     raise response
cl-celery        | django.db.utils.OperationalError: FATAL:  role "django" does not exist
cl-celery        | 
cl-celery exited with code 1
```

and

```
cl-django        |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/base/base.py", line 189, in connect
cl-django        |     self.connection = self.get_new_connection(conn_params)
cl-django        |   File "/usr/local/lib/python2.7/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
cl-django        |     connection = Database.connect(**conn_params)
cl-django        |   File "/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
cl-django        |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
cl-django        | django.db.utils.OperationalError: FATAL:  role "django" does not exist
cl-django        | 
```

I guess that's related to https://github.com/freelawproject/courtlistener/issues/980

4) Networks: Why do you have the network bridge defined as external? If you leave `external: false`, the extra setup command would not be needed.

**Comment by mlissner** [comment]
1. Re `/var/run/postgresql`, I thought we fixed that when @flooie tried to run this. @flooie can you look into this and get a fix pushed? You're using something different for this, right?

2. I'm not sure what to do about solr. You need that repository *somewhere* for things to work. I don't think it makes sense for it to be inside CourtListener. Maybe the docs need to be clear that that should be `git pull`'ed before you try to run Docker?

3. We had this sorted. I suspect it'll fix once you get number 1 above fixed. You might have to delete the cl-postgres image and start it again to get it to re-initialize though.

4. There was a reason for the external network, but I forget what it was. The extra step doesn't bother me too much, but I suppose if we can avoid it, we should. Could you check the git history, maybe, for a note?

**Comment by malteos** [comment]
1. OK

2. Why do you need the repository? Isn't the docker image supposed to be exactly for that?

3. Sorry, my fault I used the default database settings and didn't update to those mentioned in DEVELOPING.md

4. Alright.

After fixing everything locally, I can run the website. However, `cl-celery` throws this error:

```
cl-celery        | Juriscraper will continue to run, and all logs will be sent to stderr.
cl-celery        | Traceback (most recent call last):
cl-celery        |   File "/usr/local/bin/celery", line 10, in <module>
cl-celery        |     sys.exit(main())
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/__main__.py", line 16, in main
cl-celery        |     _main()
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 322, in main
cl-celery        |     cmd.execute_from_commandline(argv)
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
cl-celery        |     super(CeleryCommand, self).execute_from_commandline(argv)))
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
cl-celery        |     return self.handle_argv(self.prog_name, argv[1:])
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 488, in handle_argv
cl-celery        |     return self.execute(command, argv)
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/bin/celery.py", line 420, in execute
cl-celery        |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/bin/worker.py", line 223, in run_from_argv
cl-celery        |     return self(*args, **options)
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/bin/base.py", line 252, in __call__
cl-celery        |     ret = self.run(*args, **kwargs)
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/bin/worker.py", line 257, in run
cl-celery        |     **kwargs)
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/worker/worker.py", line 96, in __init__
cl-celery        |     self.app.loader.init_worker()
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/loaders/base.py", line 114, in init_worker
cl-celery        |     self.import_default_modules()
cl-celery        |   File "/usr/local/lib/python2.7/site-packages/celery/loaders/base.py", line 108, in import_default_modules
cl-celery        |     raise response
cl-celery        | ImportError: cannot import name ClaimsRegister
```

Do I need to install `juriscraper` beforehand?

**Comment by mlissner** [comment]
1. @flooie  and I talked about this. You're right, we can (and should) remove this line from the compose file. It's not needed if your database connection is to `'HOST': 'cl-postgresql'`, so that should probably go into the `05-private.example` file as well, at the same time.

2. I don't know? I guess we could package the code into the image, and that could be fine. The way I set it up is so that you can make changes to the code without having to make changes to the image. Normal? I don't know. I'm a bit hesitant to change it though since it's in production in the current form. The idea was code and data are outside the image, the rest is inside.

3. Great! If there's a way to highlight this better in docs (or elsewhere), I'm very much +1 doing so so others don't run into this.

4. `ClaimsRegister` is both a model name in Django and a class name in Juriscraper, and that stacktrace doesn't say which import is failing (Ugh, thanks Celery), so I'm not sure which is the issue. But, I think this is from Juriscraper, which tells me you might not have the latest docker images. Try pulling the latest task-server image and you should get the latest juriscraper, and thus a fix?

cc: @jonashleyo — you may want to subscribe here since @malteos is also working through issues on docker and has lots of experience.

**Comment by malteos** [comment]
4. Pulling the last image worked (sorry my fault)

Now, I can run the `docker-compose` without any problems!

**Comment by mlissner** [comment]
> Now, I can run the docker-compose without any problems!

That's great! I guess we didn't end up making *any* changes? I thought we at least needed to tweak those `postgres` directories, right?
